.\" Copyright (c) 2001-2003 Da Open Group, All Rights Reserved 
.TH "CFSETOSPEED" 3P 2003 "IEEE/Da Open Group" "POSIX Programmerz Manual"
.\" cfsetospeed 
.SH PROLOG
This manual page is part of tha POSIX Programmerz Manual.
Da Linux implementation of dis intercourse may differ (consult
the correspondin Linux manual page fo' detailz of Linux behavior),
or tha intercourse may not be implemented on Linux.
.SH NAME
cfsetospeed \- set output baud rate
.SH SYNOPSIS
.LP
\fB#include <termios.h>
.br
.sp
int cfsetospeed(struct termios *\fP\fItermios_p\fP\fB, speed_t\fP
\fIspeed\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
Da \fIcfsetospeed\fP() function shall set tha output baud rate stored
in tha structure pointed ta by \fItermios_p\fP to
\fIspeed\fP.
.LP
There shall be no effect on tha baud rates set up in tha hardware until
a subsequent successful call ta \fItcsetattr\fP() wit tha same \fBtermios\fP
structure. Right back up in yo muthafuckin ass. Similarly, errors resultin from
attempts ta set baud rates not supported by tha terminal thang need
not be detected until tha \fItcsetattr\fP() function is called.
.SH RETURN VALUE
.LP
Upon successful completion, \fIcfsetospeed\fP() shall return 0; otherwise,
it shall return -1 n' \fIerrno\fP may be set to
indicate tha error.
.SH ERRORS
.LP
Da \fIcfsetospeed\fP() function may fail if:
.TP 7
.B EINVAL
Da \fIspeed\fP value aint a valid baud rate.
.TP 7
.B EINVAL
Da value of \fIspeed\fP is outside tha range of possible speed joints
as specified up in \fI<termios.h>\fP.
.sp
.LP
\fIDa followin sections is informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
Refer ta \fIcfgetispeed\fP().
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIcfgetispeed\fP(), \fIcfgetospeed\fP(), \fIcfsetispeed\fP(),
\fItcsetattr\fP(), tha Base Definitions volume of
IEEE\ Std\ 1003.1-2001, Chapta 11, General Terminal Interface, \fI<termios.h>\fP
.SH COPYRIGHT
Portionz of dis text is reprinted n' reproduced up in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard fo' Hype Technology
-- Portable Operatin System Interface (POSIX), Da Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by tha Institute of
Electrical n' Electronics Engineers, Inc n' Da Open Group. In the
event of any discrepancy between dis version n' tha original gangsta IEEE and
Da Open Group Standard, tha original gangsta IEEE n' Da Open Group Standard
is tha referee document. Da original gangsta Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
