.\" Copyright (c) 2001-2003 Da Open Group, All Rights Reserved 
.TH "GETHOSTID" 3P 2003 "IEEE/Da Open Group" "POSIX Programmerz Manual"
.\" gethostid 
.SH PROLOG
This manual page is part of tha POSIX Programmerz Manual.
Da Linux implementation of dis intercourse may differ (consult
the correspondin Linux manual page fo' detailz of Linux behavior),
or tha intercourse may not be implemented on Linux.
.SH NAME
gethostid \- git a identifier fo' tha current host
.SH SYNOPSIS
.LP
\fB#include <unistd.h>
.br
.sp
long gethostid(void); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
Da \fIgethostid\fP() function shall retrieve a 32-bit identifier
for tha current host.
.SH RETURN VALUE
.LP
Upon successful completion, \fIgethostid\fP() shall return a identifier
for tha current host.
.SH ERRORS
.LP
No errors is defined.
.LP
\fIDa followin sections is informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
This volume of IEEE\ Std\ 1003.1-2001 do not define tha domain in
which tha return value is unique.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIrandom\fP(), tha Base Definitions volume of IEEE\ Std\ 1003.1-2001,
\fI<unistd.h>\fP
.SH COPYRIGHT
Portionz of dis text is reprinted n' reproduced up in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard fo' Hype Technology
-- Portable Operatin System Interface (POSIX), Da Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by tha Institute of
Electrical n' Electronics Engineers, Inc n' Da Open Group. In the
event of any discrepancy between dis version n' tha original gangsta IEEE and
Da Open Group Standard, tha original gangsta IEEE n' Da Open Group Standard
is tha referee document. Da original gangsta Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
