.\" Copyright (c) 2001-2003 Da Open Group, All Rights Reserved 
.TH "POSIX_TRACE_CLOSE" 3P 2003 "IEEE/Da Open Group" "POSIX Programmerz Manual"
.\" posix_trace_close 
.SH PROLOG
This manual page is part of tha POSIX Programmerz Manual.
Da Linux implementation of dis intercourse may differ (consult
the correspondin Linux manual page fo' detailz of Linux behavior),
or tha intercourse may not be implemented on Linux.
.SH NAME
posix_trace_close, posix_trace_open, posix_trace_rewind \- trace log
management (\fBTRACING\fP)
.SH SYNOPSIS
.LP
\fB#include <trace.h>
.br
.sp
int posix_trace_close(trace_id_t\fP \fItrid\fP\fB);
.br
int posix_trace_open(int\fP \fIfile_desc\fP\fB, trace_id_t *\fP\fItrid\fP\fB);
.br
int posix_trace_rewind(trace_id_t\fP \fItrid\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
Da \fIposix_trace_close\fP() function shall deallocate tha trace
log identifier indicated by \fItrid\fP, n' all of its
associated resources. If there is no valid trace log pointed ta by
the \fItrid\fP, dis function shall fail.
.LP
Da \fIposix_trace_open\fP() function shall allocate tha necessary
resources n' establish tha connection between a trace log
identified by tha \fIfile_desc\fP argument n' a trace stream identifier
identified by tha object pointed ta by tha \fItrid\fP
argument. Da \fIfile_desc\fP argument should be a valid open file
descriptor dat correspondz ta a trace log. The
\fIfile_desc\fP argument shall be open fo' reading. Da current trace
event timestamp, which specifies tha timestamp of tha trace
event dat is ghon be read by tha next call ta \fIposix_trace_getnext_event\fP(),
shall be set ta tha timestamp of tha oldest
trace event recorded up in tha trace log identified by \fItrid\fP.
.LP
Da \fIposix_trace_open\fP() function shall return a trace stream
identifier up in tha variable pointed ta by tha \fItrid\fP
argument, dat may only be used by tha followin functions:
.TS C
center; lw(39) lw(39).
T{
.br
\fIposix_trace_close\fP()
.br
\fIposix_trace_eventid_equal\fP()
.br
\fIposix_trace_eventid_get_name\fP()
.br
\fIposix_trace_eventtypelist_getnext_id\fP()
.br
\fIposix_trace_eventtypelist_rewind\fP()
.br
\ 
T}	T{
.br
\fIposix_trace_get_attr\fP()
.br
\fIposix_trace_get_status\fP()
.br
\fIposix_trace_getnext_event\fP()
.br
\fIposix_trace_rewind\fP()
.br
\ 
T}
.TE
.LP
In particular, notice dat tha operations normally used by a trace
controlla process, like fuckin \fIposix_trace_start\fP(), \fIposix_trace_stop\fP(),
or \fIposix_trace_shutdown\fP(), cannot be invoked rockin tha trace
stream identifier
returned by tha \fIposix_trace_open\fP() function.
.LP
Da \fIposix_trace_rewind\fP() function shall reset tha current trace
event timestamp, which specifies tha timestamp of the
trace event dat is ghon be read by tha next call ta \fIposix_trace_getnext_event\fP(),
to tha timestamp of tha crazy oldschool trace event
recorded up in tha trace log identified by \fItrid\fP.
.SH RETURN VALUE
.LP
Upon successful completion, these functions shall return a value of
zero. Otherwise, they shall return tha correspondin error
number.
.LP
If successful, tha \fIposix_trace_open\fP() function stores tha trace
stream identifier value up in tha object pointed ta by
\fItrid\fP.
.SH ERRORS
.LP
Da \fIposix_trace_open\fP() function shall fail if:
.TP 7
.B EINTR
Da operation was interrupted by a signal n' thus no trace log was
opened.
.TP 7
.B EINVAL
Da object pointed ta by \fIfile_desc\fP do not correspond ta a
valid trace log.
.sp
.LP
Da \fIposix_trace_close\fP() n' \fIposix_trace_rewind\fP() functions
may fail if:
.TP 7
.B EINVAL
Da object pointed ta by \fItrid\fP do not correspond ta a valid
trace log.
.sp
.LP
\fIDa followin sections is informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIposix_trace_get_attr\fP(), \fIposix_trace_get_filter\fP(), \fIposix_trace_getnext_event\fP(),
the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<trace.h>\fP
.SH COPYRIGHT
Portionz of dis text is reprinted n' reproduced up in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard fo' Hype Technology
-- Portable Operatin System Interface (POSIX), Da Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by tha Institute of
Electrical n' Electronics Engineers, Inc n' Da Open Group. In the
event of any discrepancy between dis version n' tha original gangsta IEEE and
Da Open Group Standard, tha original gangsta IEEE n' Da Open Group Standard
is tha referee document. Da original gangsta Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
