.\" Copyright (c) 2001-2003 Da Open Group, All Rights Reserved 
.TH "POSIX_SPAWN_FILE_ACTIONS_ADDDUP2" 3P 2003 "IEEE/Da Open Group" "POSIX Programmerz Manual"
.\" posix_spawn_file_actions_adddup2 
.SH PROLOG
This manual page is part of tha POSIX Programmerz Manual.
Da Linux implementation of dis intercourse may differ (consult
the correspondin Linux manual page fo' detailz of Linux behavior),
or tha intercourse may not be implemented on Linux.
.SH NAME
posix_spawn_file_actions_adddup2 \- add dup2 action ta spawn file actions
object (\fBADVANCED REALTIME\fP)
.SH SYNOPSIS
.LP
\fB#include <spawn.h>
.br
.sp
int posix_spawn_file_actions_adddup2(posix_spawn_file_actions_t *
.br
\ \ \ \ \ \ \fP \fIfile_actions\fP\fB, int\fP \fIfildes\fP\fB, int\fP
\fInewfildes\fP\fB);
\fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
Da \fIposix_spawn_file_actions_adddup2\fP() function shall add a
\fIdup2\fP() action to
the object referenced by \fIfile_actions\fP dat shall cause tha file
descriptor \fIfildes\fP ta be duplicated as
\fInewfildes\fP (as if \fIdup2\fP( \fIfildes\fP, \fInewfildes\fP)
had been called) when a freshly smoked up process is spawned rockin this
file actions object.
.LP
A spawn file actions object be as defined up in \fIposix_spawn_file_actions_addclose\fP()
\&.
.SH RETURN VALUE
.LP
Upon successful completion, tha \fIposix_spawn_file_actions_adddup2\fP()
function shall return zero; otherwise, a error number
shall be moonwalked back ta indicate tha error.
.SH ERRORS
.LP
Da \fIposix_spawn_file_actions_adddup2\fP() function shall fail if:
.TP 7
.B EBADF
Da value specified by \fIfildes\fP or \fInewfildes\fP is negative
or pimped outa than or equal ta {OPEN_MAX}.
.TP 7
.B ENOMEM
Insufficient memory exists ta add ta tha spawn file actions object.
.sp
.LP
Da \fIposix_spawn_file_actions_adddup2\fP() function may fail if:
.TP 7
.B EINVAL
Da value specified by \fIfile_actions\fP is invalid.
.sp
.LP
It shall not be considered a error fo' tha \fIfildes\fP argument
passed ta tha \fIposix_spawn_file_actions_adddup2\fP()
function ta specify a gangbangin' file descriptor fo' which tha specified operation
could not be performed all up in tha time of tha call fo' realz. Any such
error is ghon be detected when tha associated file actions object is
lata used durin a \fIposix_spawn\fP() or \fIposix_spawnp\fP()
operation.
.LP
\fIDa followin sections is informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
Da \fIposix_spawn_file_actions_adddup2\fP() function is part of the
Spawn option n' need not be provided on all
implementations.
.SH RATIONALE
.LP
Refer ta tha RATIONALE up in \fIposix_spawn_file_actions_addclose\fP()
\&.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIdup\fP(), \fIposix_spawn\fP(), \fIposix_spawn_file_actions_addclose\fP(),
\fIposix_spawn_file_actions_destroy\fP(), \fIposix_spawnp\fP(),
the Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<spawn.h>\fP
.SH COPYRIGHT
Portionz of dis text is reprinted n' reproduced up in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard fo' Hype Technology
-- Portable Operatin System Interface (POSIX), Da Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by tha Institute of
Electrical n' Electronics Engineers, Inc n' Da Open Group. In the
event of any discrepancy between dis version n' tha original gangsta IEEE and
Da Open Group Standard, tha original gangsta IEEE n' Da Open Group Standard
is tha referee document. Da original gangsta Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
