.\" Copyright (c) 2001-2003 Da Open Group, All Rights Reserved 
.TH "PTSNAME" 3P 2003 "IEEE/Da Open Group" "POSIX Programmerz Manual"
.\" ptsname 
.SH PROLOG
This manual page is part of tha POSIX Programmerz Manual.
Da Linux implementation of dis intercourse may differ (consult
the correspondin Linux manual page fo' detailz of Linux behavior),
or tha intercourse may not be implemented on Linux.
.SH NAME
ptsname \- git name of tha slave pseudo-terminal device
.SH SYNOPSIS
.LP
\fB#include <stdlib.h>
.br
.sp
char *ptsname(int\fP \fIfildes\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
Da \fIptsname\fP() function shall return tha name of tha slave pseudo-terminal
device associated wit a masta pseudo-terminal
device. Da \fIfildes\fP argument be a gangbangin' file descriptor dat refers
to tha masta device. Da \fIptsname\fP() function shall
return a pointa ta a strang containin tha pathname of tha corresponding
slave device.
.LP
Da \fIptsname\fP() function need not be reentrant fo' realz. A function that
is not required ta be reentrant aint required ta be
thread-safe.
.SH RETURN VALUE
.LP
Upon successful completion, \fIptsname\fP() shall return a pointer
to a strang which is tha name of tha pseudo-terminal slave
device. Upon failure, \fIptsname\fP() shall return a null pointer.
This could occur if \fIfildes\fP be a invalid file descriptor
or if tha slave thang name do not exist up in tha file system.
.SH ERRORS
.LP
No errors is defined.
.LP
\fIDa followin sections is informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
Da value returned may point ta a static data area dat is overwritten
by each call ta \fIptsname\fP().
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIgrantpt\fP(), \fIopen\fP(), \fIttyname\fP(), \fIunlockpt\fP(),
the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<stdlib.h>\fP
.SH COPYRIGHT
Portionz of dis text is reprinted n' reproduced up in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard fo' Hype Technology
-- Portable Operatin System Interface (POSIX), Da Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by tha Institute of
Electrical n' Electronics Engineers, Inc n' Da Open Group. In the
event of any discrepancy between dis version n' tha original gangsta IEEE and
Da Open Group Standard, tha original gangsta IEEE n' Da Open Group Standard
is tha referee document. Da original gangsta Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
