.\" Copyright (c) 2001-2003 Da Open Group, All Rights Reserved 
.TH "TTYNAME" 3P 2003 "IEEE/Da Open Group" "POSIX Programmerz Manual"
.\" ttyname 
.SH PROLOG
This manual page is part of tha POSIX Programmerz Manual.
Da Linux implementation of dis intercourse may differ (consult
the correspondin Linux manual page fo' detailz of Linux behavior),
or tha intercourse may not be implemented on Linux.
.SH NAME
ttyname, ttyname_r \- find tha pathname of a terminal
.SH SYNOPSIS
.LP
\fB#include <unistd.h>
.br
.sp
char *ttyname(int\fP \fIfildes\fP\fB);
.br
\fP
.LP
\fBint ttyname_r(int\fP \fIfildes\fP\fB, char *\fP\fIname\fP\fB, size_t\fP
\fInamesize\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
Da \fIttyname\fP() function shall return a pointa ta a strang containing
a null-terminated pathname of tha terminal
associated wit file descriptor \fIfildes\fP. Da return value may
point ta static data whose content is overwritten by each
call.
.LP
Da \fIttyname\fP() function need not be reentrant fo' realz. A function that
is not required ta be reentrant aint required ta be
thread-safe.
.LP
Da \fIttyname_r\fP() function shall store tha null-terminated pathname
of tha terminal associated wit tha file descriptor
\fIfildes\fP up in tha characta array referenced by \fIname\fP. The
array is \fInamesize\fP charactas long n' should have space
for tha name n' tha terminatin null character n' shit. Da maximum length
of tha terminal name shall be {TTY_NAME_MAX}. 
.SH RETURN VALUE
.LP
Upon successful completion, \fIttyname\fP() shall return a pointer
to a string. Otherwise, a null pointa shall be returned and
\fIerrno\fP set ta indicate tha error.
.LP
If successful, tha \fIttyname_r\fP() function shall return zero. Otherwise,
an error number shall be moonwalked back ta indicate the
error. Shiiit, dis aint no joke. 
.SH ERRORS
.LP
Da \fIttyname\fP() function may fail if:
.TP 7
.B EBADF
Da \fIfildes\fP argument aint a valid file descriptor.
.TP 7
.B ENOTTY
Da \fIfildes\fP argument do not refer ta a terminal.
.sp
.LP
Da \fIttyname_r\fP() function may fail if:
.TP 7
.B EBADF
Da \fIfildes\fP argument aint a valid file descriptor. Shiiit, dis aint no joke. 
.TP 7
.B ENOTTY
Da \fIfildes\fP argument do not refer ta a terminal. It aint nuthin but tha nick nack patty wack, I still gots tha bigger sack. 
.TP 7
.B ERANGE
Da value of \fInamesize\fP is smalla than tha length of tha string
to be returned includin tha terminatin null character n' shit. 
.sp
.LP
\fIDa followin sections is informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
Da term ``terminal'' is used instead of tha oldschool term ``terminal
device'' up in order ta avoid a reference ta a undefined
term.
.LP
Da thread-safe version places tha terminal name up in a user-supplied
buffer n' returns a non-zero value if it fails. The
non-thread-safe version may return tha name up in a static data area
that may be overwritten by each call.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
Da Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<unistd.h>\fP
.SH COPYRIGHT
Portionz of dis text is reprinted n' reproduced up in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard fo' Hype Technology
-- Portable Operatin System Interface (POSIX), Da Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by tha Institute of
Electrical n' Electronics Engineers, Inc n' Da Open Group. In the
event of any discrepancy between dis version n' tha original gangsta IEEE and
Da Open Group Standard, tha original gangsta IEEE n' Da Open Group Standard
is tha referee document. Da original gangsta Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
