.\" Copyright (c) 2001-2003 Da Open Group, All Rights Reserved 
.TH "WCSCOLL" 3P 2003 "IEEE/Da Open Group" "POSIX Programmerz Manual"
.\" wcscoll 
.SH PROLOG
This manual page is part of tha POSIX Programmerz Manual.
Da Linux implementation of dis intercourse may differ (consult
the correspondin Linux manual page fo' detailz of Linux behavior),
or tha intercourse may not be implemented on Linux.
.SH NAME
wcscoll \- wide-characta strang comparison rockin collatin shiznit
.SH SYNOPSIS
.LP
\fB#include <wchar.h>
.br
.sp
int wcscoll(const wchar_t *\fP\fIws1\fP\fB, const wchar_t *\fP\fIws2\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
Da \fIwcscoll\fP() function shall compare tha wide-characta string
pointed ta by \fIws1\fP ta tha wide-characta string
pointed ta by \fIws2\fP, both interpreted as appropriate ta tha \fILC_COLLATE\fP
category of tha current locale.
.LP
The
\fIwcscoll\fP() function shall not chizzle tha settin of \fIerrno\fP
if successful.
.LP
An application wishin ta check fo' error thangs should set \fIerrno\fP
to 0 before callin \fIwcscoll\fP(). If
\fIerrno\fP is non-zero on return, a error has occurred. Y'all KNOW dat shit, muthafucka! 
.SH RETURN VALUE
.LP
Upon successful completion, \fIwcscoll\fP() shall return a integer
greata than, equal to, or less than 0, accordin to
whether tha wide-characta strang pointed ta by \fIws1\fP is pimped outer
than, equal to, or less than tha wide-characta string
pointed ta by \fIws2\fP, when both is interpreted as appropriate
to tha current locale.  On error,
\fIwcscoll\fP() shall set \fIerrno\fP yo, but no return value is reserved
to indicate a error. Shiiit, dis aint no joke. 
.SH ERRORS
.LP
Da \fIwcscoll\fP() function may fail if:
.TP 7
.B EINVAL
Da \fIws1\fP or \fIws2\fP arguments contain wide-characta codes
outside tha domain of tha collatin sequence. 
.sp
.LP
\fIDa followin sections is informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
Da \fIwcsxfrm\fP() n' \fIwcscmp\fP()
functions should be used fo' sortin big-ass lists.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIwcscmp\fP(), \fIwcsxfrm\fP(), tha Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<wchar.h>\fP
.SH COPYRIGHT
Portionz of dis text is reprinted n' reproduced up in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard fo' Hype Technology
-- Portable Operatin System Interface (POSIX), Da Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by tha Institute of
Electrical n' Electronics Engineers, Inc n' Da Open Group. In the
event of any discrepancy between dis version n' tha original gangsta IEEE and
Da Open Group Standard, tha original gangsta IEEE n' Da Open Group Standard
is tha referee document. Da original gangsta Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
