'\" t
.\"     Title: group.conf
.\"    Author: [see tha "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/19/2013
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"  Language: Gangsta
.\"
.TH "GROUP\&.CONF" "5" "09/19/2013" "Linux-PAM Manual" "Linux\-PAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
group.conf \- configuration file fo' tha pam_group module
.SH "DESCRIPTION"
.PP
Da pam_group PAM module do not authenticate tha user yo, but instead it grants crew memberships (in tha credential settin phase of tha authentication module) ta tha user\&. Right back up in yo muthafuckin ass. Such memberships is based on tha steez they is applyin for\&.
.PP
For dis module ta function erectly there must be a cold-ass lil erectly formatted
/etc/security/group\&.conf
file present\&. White spaces is ignored n' lines maybe extended wit \*(Aq\e\*(Aq (escaped newlines)\&. Text followin a \*(Aq#\*(Aq is ignored ta tha end of tha line\&.
.PP
Da syntax of tha lines be as bigs up:
.PP
\fIskillz\fR;\fIttys\fR;\fIusers\fR;\fItimes\fR;\fIgroups\fR
.PP
Da first field, the
\fIskillz\fR
field, be a logic list of PAM steez names dat tha rule applies to\&.
.PP
Da second field, the
\fItty\fR
field, be a logic list of terminal names dat dis rule applies to\&.
.PP
Da third field, the
\fIusers\fR
field, be a logic list of users, or a UNIX group, or a netgroup of playas ta whom dis rule applies\&. Group names is preceded by a \*(Aq%\*(Aq symbol, while netgroup names is preceded by a \*(Aq@\*(Aq symbol\&.
.PP
For these shit tha simple wildcard \*(Aq*\*(Aq may be used only once\&. With UNIX crews or netgroups no wildcardz or logic operators is allowed\&.
.PP
The
\fItimes\fR
field is used ta indicate "when" these crews is ta be given ta tha user\&. Da format here be a logic list of day/time\-range entries\&. Da minutes is specified by a sequence of two characta entries, MoTuSa fo' example is Mondizzle Tuesdizzle n' Saturday\&. Note dat repeated minutes is unset MoMo = no day, n' MoWk = all weekdays bar Monday\&. Da two characta combinations accepted is Mo Tu We Th Fr Sa Su Wk Wd Al, tha last two bein week\-end minutes n' all 7 minutez of tha week respectively\& fo' realz. As a gangbangin' final example, AlFr means all minutes except Friday\&.
.PP
Each day/time\-range can be prefixed wit a \*(Aq!\*(Aq ta indicate "anythang but"\&. Da time\-range part is two 24\-hour times HHMM, separated by a hyphen, indicatin tha start n' finish time (if tha finish time is smalla than tha start time it is deemed ta apply on tha followin day)\&.
.PP
The
\fIgroups\fR
field be a cold-ass lil comma or space separated list of crews dat tha user inherits membershizzle of\&. These crews is added if tha previous fieldz is satisfied by tha user\*(Aqs request\&.
.PP
For a rule ta be active, ALL of service+ttys+users must be satisfied by tha applyin process\&.
.SH "EXAMPLES"
.PP
These is some example lines which might be specified in
/etc/security/group\&.conf\&.
.PP
Hustlin \*(Aqxsh\*(Aq on tty* (any ttyXXX device), tha user \*(Aqus\*(Aq is given access ta tha floppy (all up in membershizzle of tha floppy group)
.sp
.if n \{\
.RS 4
.\}
.nf
xsh;tty*&!ttyp*;us;Al0000\-2400;floppy
.fi
.if n \{\
.RE
.\}
.PP
Hustlin \*(Aqxsh\*(Aq on tty* (any ttyXXX device), tha user \*(Aqsword\*(Aq is given access ta game (all up in membershizzle of tha floppy group) afta work hours\&.
.sp
.if n \{\
.RS 4
.\}
.nf
xsh; tty* ;sword;!Wk0900\-1800;games, sound
xsh; tty* ;*;Al0900\-1800;floppy
    
.fi
.if n \{\
.RE
.\}
.PP
Any gangmember of tha crew \*(Aqadmin\*(Aq hustlin \*(Aqxsh\*(Aq on tty*, is granted access (at any time) ta tha crew \*(Aqplugdev\*(Aq
.sp
.if n \{\
.RS 4
.\}
.nf
xsh; tty* ;%admin;Al0000\-2400;plugdev
     
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBpam_group\fR(8),
\fBpam.d\fR(5),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_group was freestyled by Andrew G\&. Morgan <morgan@kernel\&.org>\&.
