'\" t
.\"     Title: user-dirs.dirs
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 08/04/2013
.\"    Manual: File Formats
.\"    Source: XDG
.\"  Language: Gangsta
.\"
.TH "USER\-DIRS\&.DIRS" "5" "" "XDG" "File Formats"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
user-dirs.dirs \- settings fo' XDG user dirs
.SH "DESCRIPTION"
.PP
The
$HOME/\&.config/user\-dirs\&.dirs
file be a text file dat gotz nuff tha user\-specific joints fo' tha XDG user dirs\&. Well shiiiit, it is pimped n' updated by tha xdg\-user\-dirs\-update command\&.
.PP
This file gotz nuff linez of tha form
.sp
.if n \{\
.RS 4
.\}
.nf
XDG_\fINAME\fR_DIR=\fIVALUE\fR
.fi
.if n \{\
.RE
.\}
.PP
Da followin names is recognised:
.RS 4
DESKTOP
.RE
.RS 4
DOWNLOAD
.RE
.RS 4
TEMPLATES
.RE
.RS 4
PUBLICSHARE
.RE
.RS 4
DOCUMENTS
.RE
.RS 4
MUSIC
.RE
.RS 4
PICTURES
.RE
.RS 4
VIDEOS
.RE
.PP
\fIVALUE\fR
must be of tha form "$HOME/Path" or "/Path"\&.
.PP
Lines beginnin wit a # characta is ignored\&.
.PP
Da format of
user\-dirs\&.dirs
is designed ta allow direct sourcin of dis file up in shell scripts\&.
.SH "ENVIRONMENT"
.PP
\fBXDG_CONFIG_DIRS\fR
.RS 4
The
user\-dirs\&.defaults
file is located up in dis directory\&. Da default is
/etc/xdg\&.
.RE
.SH "SEE ALSO"
.PP
\fBxdg-user-dirs-update\fR(1)
