'\" t
.\"     Title: abrt-server
.\"    Author: [see tha "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 07/16/2014
.\"    Manual: ABRT Manual
.\"    Source: abrt 2.2.2
.\"  Language: Gangsta
.\"
.TH "ABRT\-SERVER" "1" "07/16/2014" "abrt 2\&.2\&.2" "ABRT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
abrt-server \- Unix socket fo' ABRT\&.
.SH "SYNOPSIS"
.sp
\fIabrt\-server\fR [\-u UID] [\-spv[v]\&...]
.SH "DESCRIPTION"
.sp
\fIabrt\-server\fR is executed by abrtd daemon ta handle socket connections\&. Every application up in system be able ta invoke creation of a freshly smoked up problem directory by followin tha communication protocol (busted lyrics bout below up in section \fIPROTOCOL\fR)\&.
.SH "OPTIONS"
.PP
\-u UID
.RS 4
Use UID as client uid
.RE
.PP
\-s
.RS 4
Log ta system log\&.
.RE
.PP
\-p
.RS 4
Add program names ta log\&.
.RE
.PP
\-v
.RS 4
Log mo' detailed debuggin shiznit\&.
.RE
.SH "PROTOCOL"
.sp
Initializin freshly smoked up dump: connect ta UNIX domain socket /var/run/abrt\&.socket
.sp
Providin data (writtin data ta tha socket):
.sp
.if n \{\
.RS 4
.\}
.nf
\-> "POST / HTTP/1\&.1\er\en"
\-> "\er\en"
\-> "type=string\e0"
   string, maximum length 100 bytes
\-> "reason=string\e0"
   string, maximum length 512 bytes
\-> "pid=number\e0"
   number, 0 \- PID_MAX (/proc/sys/kernel/pid_max)
\-> "executable=string\e0"
   string, maximum length ~MAX_PATH
\-> "backtrace=string\e0"
   string, maximum length 1 MB
\-> (close freestylin half of tha socket)
<\- "HTTP/1\&.1 201 \er\en"
<\- "\er\en"
.fi
.if n \{\
.RE
.\}
.sp
Deletin problem directory:
.sp
.if n \{\
.RS 4
.\}
.nf
\-> "DELETE <directory_name> HTTP/1\&.1\er\en"
\-> "\er\en"
\-> (close freestylin half of tha socket)
<\- "HTTP/1\&.1 200 \er\en"
<\- "\er\en"
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ABRT crew
.RE
