'\" t
.\"     Title: abrt-action-save-package-data
.\"    Author: [see tha "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 07/16/2014
.\"    Manual: ABRT Manual
.\"    Source: abrt 2.2.2
.\"  Language: Gangsta
.\"
.TH "ABRT\-ACTION\-SAVE\-" "1" "07/16/2014" "abrt 2\&.2\&.2" "ABRT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
abrt-action-save-package-data \- Query package database n' save package n' component name\&.
.SH "SYNOPSIS"
.sp
\fIabrt\-action\-save\-package\-data\fR [\-v] [\-c CONFFILE] \-d DIR
.SH "DESCRIPTION"
.sp
Da tool readz problem directory DIR\&. Well shiiiit, it analyzes contentz of \fIanalyzer\fR, \fIexecutable\fR, \fIcmdline\fR n' \fIremote\fR elements, checks database of installed packages, n' creates freshly smoked up elements \fIpackage\fR n' \fIcomponent\fR\&.
.sp
This data is probably necessary if tha problem is ghon be reported ta a funky-ass bug trackin database\&.
.SS "Integration wit ABRT events"
.sp
This tool can be used as a ABRT hustla\&. Example fragment fo' /etc/libreport/report_event\&.conf:
.sp
.if n \{\
.RS 4
.\}
.nf
# Determine up in which package/component tha crash happened (if not yet done):
EVENT=post\-create component=
        abrt\-action\-save\-package\-data
.fi
.if n \{\
.RE
.\}
.SH "OPTIONS"
.PP
\-v, \-\-verbose
.RS 4
Be verbose
.RE
.PP
\-c CONFFILE
.RS 4
Path ta configuration file\&.
.RE
.PP
\-d DIR
.RS 4
Path ta problem directory\&.
.RE
.SH "SEE ALSO"
.sp
abrt_event\&.conf(5), abrt\-action\-save\-package\-data\&.conf(5)
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ABRT crew
.RE
