'\" t
.\"     Title: dconf
.\"    Author: Ryan Lortie <desrt@desrt.ca>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/26/2013
.\"    Manual: User Commands
.\"    Source: dconf
.\"  Language: Gangsta
.\"
.TH "DCONF" "1" "" "dconf" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dconf \- Simple tool fo' manipulatin a thugged-out dconf database
.SH "SYNOPSIS"
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR read \fIKEY\fR
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR list \fIDIR\fR
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR write \fIKEY\fR \fIVALUE\fR
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR reset [\-f] \fIPATH\fR
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR update
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR peep \fIPATH\fR
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR dump \fIDIR\fR
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR load \fIDIR\fR
.HP \w'\fBdconf\fR\ 'u
\fBdconf\fR help [\fICOMMAND\fR]
.SH "DESCRIPTION"
.PP
The
\fBdconf\fR
program can big-ass up various operations on a thugged-out dconf database, like fuckin readin or freestylin individual joints or entire directories\&. This tool operates on dconf directly, without rockin gsettings schema shiznit\&. Therefore, it cannot big-ass up type n' consistency checks on joints\&. The
\fBgsettings\fR(1)
utilitizzle be a alternatizzle if such checks is needed\&.
.PP
The
\fIDIR\fR
arguments must be directory paths (startin n' endin wit \*(Aq/\*(Aq), the
\fIKEY\fR
arguments must be key paths (startin yo, but not endin wit \*(Aq/\*(Aq) n' the
\fIPATH\fR
arguments can be either directory or key paths\&.
.PP
\fIVALUE\fR
arguments must be up in GVariant format, so e\&.g\&. a strang must include explicit quotes: "\*(Aqfoo\*(Aq"\&. This format be also used when printin up joints\&.
.PP
Note dat dconf needz a D\-Bus session bus connection ta write chizzlez ta tha dconf database\&.
.SH "COMMANDS"
.PP
\fBread\fR
.RS 4
Read tha value of a key\&.
.RE
.PP
\fBlist\fR
.RS 4
List tha sub\-keys n' sub\-directoriez of a gangbangin' finger-lickin' directory\&.
.RE
.PP
\fBwrite\fR
.RS 4
Write a freshly smoked up value ta a key\&.
.RE
.PP
\fBreset\fR
.RS 4
Reset a key or a entire directory\&. For directories,
\fB\-f\fR
must be specified\&.
.RE
.PP
\fBupdate\fR
.RS 4
Update tha system dconf databases\&.
.RE
.PP
\fBwatch\fR
.RS 4
Watch a key or directory fo' chizzles\&.
.RE
.PP
\fBdump\fR
.RS 4
Dump a entire subpath ta stdout\&. Da output is up in a keyfile\-like format, wit joints up in GVariant syntax\&.
.RE
.PP
\fBload\fR
.RS 4
Populate a subpath from stdin\&. Da expected format is tha same ol' dirty as produced by
\fBdump\fR\&.
.RE
.PP
\fBhelp\fR
.RS 4
Display help n' exit\&. If
\fICOMMAND\fR
is given, display help fo' dis command\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBDCONF_PROFILE\fR
.RS 4
This environment variable determines which dconf
profile
to use\&. Right back up in yo muthafuckin ass. See
\fBdconf\fR(7)\&.
.RE
.SH "SEE ALSO"
.PP
\fBdconf\fR(7),
\fBgsettings\fR(1),
\fBdconf-editor\fR(1)
