.TH DELUGED 1 "November 2014" "1.3.11"

.SH NAME
deluged - a funky-ass bittorrent client daemon

.SH SYNOPSIS
.B deluged [options]

.SH DESCRIPTION
.br
.P
Deluge utilizes a cold-ass lil client/server model, wit 'deluged' bein tha daemon process n' 'deluge' bein used ta launch a user-interface.
.br
.P
By default, 'deluged' will run as a thugged-out daemon, ta prevent dis you can run deluged wit tha \-d option. I aint talkin' bout chicken n' gravy biatch.  This option is useful fo' hustlin deluged wit tha start-stop-daemon.

.SH OPTIONS
.TP
.I --version
Show programz version number n' exit.
.TP
.I -h, --help
Show dis help message n' exit.
.TP
.I -p PORT, --port=PORT
Port daemon will listen on, default is 58846
.TP
.I -i INTERFACE, --interface=INTERFACE
Interface daemon will listen fo' bittorrent connections on, dis should be a IP address
.TP
.I -u UI_INTERFACE, --ui-interface=UI_INTERFACE
Interface daemon will listen fo' UI connections on, dis should be a IP address
.TP
.I -d, --do-not-daemonize
Do not daemonize
.TP
.I -c CONFIG, --config=CONFIG
Sets tha configuration path.
.TP
.I -l LOGFILE, --logfile=LOGFILE
Output ta designated logfile instead of stdout
.TP
.I -P PIDFILE, --pidfile=PIDFILE
Use pidfile ta store process id
.TP
.I -L LOGLEVEL, --loglevel=LOGLEVEL
Set tha log level (default is error): none, info, warning, error, critical, debug
.TP
.I -q --quiet
Sets tha log level ta 'none', dis is tha same ol' dirty as `\-L none`

.SH SEE ALSO
.B Homepage:
http://www.deluge-torrent.org/

.SH AUTHOR
This manual page was freestyled by Andrew Resch <andrewresch@gmail.com>.
.br
Permission is granted ta copy, distribute and/or modify dis document under tha termz of tha GNU General Public License, Version 3 or any lata version published by tha Jacked Software Foundation
.br
