'\" t
.\"     Title: git-repack
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/25/2014
.\"    Manual: Git Manual
.\"    Source: Git 1.9.3
.\"  Language: Gangsta
.\"
.TH "GIT\-REPACK" "1" "10/25/2014" "Git 1\&.9\&.3" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-repack \- Pack unpacked objects up in a repository
.SH "SYNOPSIS"
.sp
.nf
\fIgit repack\fR [\-a] [\-A] [\-d] [\-f] [\-F] [\-l] [\-n] [\-q] [\-\-window=<n>] [\-\-depth=<n>]
.fi
.sp
.SH "DESCRIPTION"
.sp
This command is used ta combine all objects dat do not currently reside up in a "pack", tha fuck into a pack\&. Well shiiiit, it can also be used ta re\-organize existin packs tha fuck into a single, mo' efficient pack\&.
.sp
A pack be a cold-ass lil collection of objects, individually compressed, wit delta compression applied, stored up in a single file, wit a associated index file\&.
.sp
Packs is used ta reduce tha load on mirror systems, backup engines, disk storage, etc\&.
.SH "OPTIONS"
.PP
\-a
.RS 4
Instead of incrementally packin tha unpacked objects, pack every last muthafuckin thang referenced tha fuck into a single pack\&. Especially useful when packin a repository dat is used fo' private pimpment\&. Use with
\fI\-d\fR\&. This will clean up tha objects that
git prune
leaves behind yo, but
git fsck \-\-full \-\-dangling
shows as dangling\&.
.sp
Note dat playas fetchin over dumb protocols will gotta fetch tha whole freshly smoked up pack up in order ta git any contained object, no matta how tha fuck nuff other objects up in dat pack they already have locally\&.
.RE
.PP
\-A
.RS 4
Same as
\-a, unless
\fI\-d\fR
is used\&. Then any unreachable objects up in a previous pack become loose, unpacked objects, instead of bein left up in tha oldschool pack\&. Unreachable objects is never intentionally added ta a pack, even when repacking\&. This option prevents unreachable objects from bein immediately deleted by way of bein left up in tha oldschool pack n' then removed\&. Instead, tha loose unreachable objects is ghon be pruned accordin ta aiiight expiry rulez wit tha next
\fIgit gc\fR
invocation\&. Right back up in yo muthafuckin ass. See
\fBgit-gc\fR(1)\&.
.RE
.PP
\-d
.RS 4
Afta packing, if tha newly pimped packs cook up some fuckin existin packs redundant, remove tha redundant packs\& fo' realz. Also run
\fIgit prune\-packed\fR
to remove redundant loose object files\&.
.RE
.PP
\-l
.RS 4
Pass the
\-\-local
option to
\fIgit pack\-objects\fR\&. Right back up in yo muthafuckin ass. See
\fBgit-pack-objects\fR(1)\&.
.RE
.PP
\-f
.RS 4
Pass the
\-\-no\-reuse\-delta
option to
git\-pack\-objects, see
\fBgit-pack-objects\fR(1)\&.
.RE
.PP
\-F
.RS 4
Pass the
\-\-no\-reuse\-object
option to
git\-pack\-objects, see
\fBgit-pack-objects\fR(1)\&.
.RE
.PP
\-q
.RS 4
Pass the
\-q
option to
\fIgit pack\-objects\fR\&. Right back up in yo muthafuckin ass. See
\fBgit-pack-objects\fR(1)\&.
.RE
.PP
\-n
.RS 4
Do not update tha server shiznit with
\fIgit update\-server\-info\fR\&. This option skips uppimpin local catalog filez needed ta publish dis repository (or a gangbangin' finger-lickin' direct copy of it) over HTTP or FTP\&. Right back up in yo muthafuckin ass. See
\fBgit-update-server-info\fR(1)\&.
.RE
.PP
\-\-window=<n>, \-\-depth=<n>
.RS 4
These two options affect how tha fuck tha objects contained up in tha pack is stored rockin delta compression\&. Da objects is first internally sorted by type, size n' optionally names n' compared against tha other objects within
\-\-window
to peep if rockin delta compression saves space\&.
\-\-depth
limits tha maximum delta depth; makin it too deep affects tha performizzle on tha unpacker side, cuz delta data need ta be applied dat nuff times ta git ta tha necessary object\&. Da default value fo' \-\-window is 10 n' \-\-depth is 50\&.
.RE
.PP
\-\-window\-memory=<n>
.RS 4
This option serves up a additionizzle limit on top of
\-\-window; tha window size will dynamically scale down so as ta not take up mo' than
\fI<n>\fR
bytes up in memory\&. This is useful up in repositories wit a mix of big-ass n' lil' small-ass objects ta not run outta memory wit a big-ass window yo, but still be able ta take advantage of tha big-ass window fo' tha smalla objects\&. Da size can be suffixed wit "k", "m", or "g"\&.
\-\-window\-memory=0
makes memory usage unlimited, which is tha default\&.
.RE
.PP
\-\-max\-pack\-size=<n>
.RS 4
Maximum size of each output pack file\&. Da size can be suffixed wit "k", "m", or "g"\&. Da minimum size allowed is limited ta 1 MiB\&. If specified, multiple packfilez may be pimped\&. Da default is unlimited, unless tha config variable
pack\&.packSizeLimit
is set\&.
.RE
.SH "CONFIGURATION"
.sp
By default, tha command passes \-\-delta\-base\-offset option ta \fIgit pack\-objects\fR; dis typically thangs up in dis biatch up in slightly smalla packs yo, but tha generated packs is incompatible wit versionz of Git olda than version 1\&.4\&.4\&. If you need ta share yo' repository wit such ancient Git versions, either directly or via tha dumb http or rsync protocol, then you need ta set tha configuration variable repack\&.UseDeltaBaseOffset ta "false" n' repack\& fo' realz. Access from oldschool Git versions over tha natizzle protocol is unaffected by dis option as tha conversion is performed on tha fly as needed up in dat case\&.
.SH "SEE ALSO"
.sp
\fBgit-pack-objects\fR(1) \fBgit-prune-packed\fR(1)
.SH "GIT"
.sp
Part of tha \fBgit\fR(1) suite
