.TH IPENGINE 1 "June 10, 2012" "" ""
.SH NAME
\fBipengine \- IPython parallel computin engine
.SH SYNOPSIS
.B ipengine
.RI [ options ]

.SH DESCRIPTION
ipengine starts a engine fo' tha IPython cluster

For mo' shiznit on how tha fuck ta use ipengine, peep 'ipengine \-\-help',
or 'ipengine \-\-help\-all' fo' all available command\(hyline options.

.SH "SEE ALSO"
.BR ipython(1),
.BR ipcontroller(1),
.BR ipcluster(1)
.br
.SH AUTHORS
\fBipengine\fP ships wit IPython, maintained by tha IPython Development Crew.
