'\" t
.\"     Title: nmblookup
.\"    Author: [see tha "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12/11/2014
.\"    Manual: User Commands
.\"    Source: Samba 4.0
.\"  Language: Gangsta
.\"
.TH "NMBLOOKUP" "1" "12/11/2014" "Samba 4\&.0" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nmblookup \- NetBIOS over TCP/IP client used ta lookup NetBIOS names
.SH "SYNOPSIS"
.HP \w'\ 'u
nmblookup [\-M|\-\-master\-browser] [\-R|\-\-recursion] [\-S|\-\-status] [\-r|\-\-root\-port] [\-A|\-\-lookup\-by\-ip] [\-B|\-\-broadcast\ <broadcast\ address>] [\-U|\-\-unicast\ <unicast\ address>] [\-d\ <debug\ level>] [\-s\ <smb\ config\ file>] [\-i\ <NetBIOS\ scope>] [\-T|\-\-translate] [\-f|\-\-flags] {name}
.SH "DESCRIPTION"
.PP
This tool is part of the
\fBsamba\fR(7)
suite\&.
.PP
nmblookup
is used ta query NetBIOS names n' map dem ta IP addresses up in a network rockin NetBIOS over TCP/IP queries\&. Da options allow tha name queries ta be pimped up at a particular IP broadcast area or ta a particular machine\& fo' realz. All queries is done over UDP\&.
.SH "OPTIONS"
.PP
\-M|\-\-master\-browser
.RS 4
Searches fo' a masta browser by lookin up tha NetBIOS
\fIname\fR
with a type of
\fB0x1d\fR\&. If
\fI name\fR
is "\-" then it do a lookup on tha special name
\fB__MSBROWSE__\fR\&. Please note dat up in order ta use tha name "\-", you need ta make shizzle "\-" isn\*(Aqt parsed as a argument, e\&.g\&. use :
\fBnmblookup \-M \-\- \-\fR\&.
.RE
.PP
\-R|\-\-recursion
.RS 4
Set tha recursion desired bit up in tha packet ta do a recursive lookup\&. This is used when bustin  a name query ta a machine hustlin a WINS server n' tha user wishes ta query tha names up in tha WINS server\&. If dis bit is unset tha aiiight (broadcast responding) NetBIOS processin code on a machine is used instead\&. Right back up in yo muthafuckin ass. See RFC1001, RFC1002 fo' details\&.
.RE
.PP
\-S|\-\-status
.RS 4
Once tha name query has returned a IP address then do a node status query as well\& fo' realz. A node status query returns tha NetBIOS names registered by a host\&.
.RE
.PP
\-r|\-\-root\-port
.RS 4
Try n' bind ta UDP port 137 ta bust n' receive UDP datagrams\&. Da reason fo' dis option be a funky-ass bug up in Windows 95 where it ignores tha source port of tha requestin packet n' only replies ta UDP port 137\&. Unfortunately, on most UNIX systems root privilege is needed ta bind ta dis port, n' up in addition, if the
\fBnmbd\fR(8)
daemon is hustlin on dis machine it also bindz ta dis port\&.
.RE
.PP
\-A|\-\-lookup\-by\-ip
.RS 4
Interpret
\fIname\fR
as a IP Address n' do a node status query on dis address\&.
.RE
.PP
\-n|\-\-netbiosname <primary NetBIOS name>
.RS 4
This option allows you ta override tha NetBIOS name dat Samba uses fo' itself\&. This is identical ta settin the
\m[blue]\fBnetbios name\fR\m[]
parameta up in the
smb\&.conf
file\&. But fuck dat shiznit yo, tha word on tha street is dat a cold-ass lil command line settin will take precedence over settings in
smb\&.conf\&.
.RE
.PP
\-i|\-\-scope <scope>
.RS 4
This specifies a NetBIOS scope that
nmblookup
will use ta rap wit when generatin NetBIOS names\&. For details on tha use of NetBIOS scopes, peep rfc1001\&.txt n' rfc1002\&.txt\&. NetBIOS scopes are
\fIvery\fR
rarely used, only set dis parameta if yo ass is tha system administrator up in charge of all tha NetBIOS systems you rap with\&.
.RE
.PP
\-W|\-\-workgroup=domain
.RS 4
Set tha SMB domain of tha username\&. This overrides tha default domain which is tha domain defined up in smb\&.conf\&. If tha domain specified is tha same ol' dirty as tha servers NetBIOS name, it causes tha client ta log on rockin tha servers local SAM (as opposed ta tha Domain SAM)\&.
.RE
.PP
\-O|\-\-socket\-options socket options
.RS 4
TCP socket options ta set on tha client socket\&. Right back up in yo muthafuckin ass. See tha socket options parameta up in the
smb\&.conf
manual page fo' tha list of valid options\&.
.RE
.PP
\-?|\-\-help
.RS 4
Print a summary of command line options\&.
.RE
.PP
\-\-usage
.RS 4
Display brief usage message\&.
.RE
.PP
\-B|\-\-broadcast <broadcast address>
.RS 4
Send tha query ta tha given broadcast address\&. Without dis option tha default behavior of nmblookup is ta bust tha query ta tha broadcast address of tha network intercourses as either auto\-detected or defined up in the
\fIinterfaces\fR
parameta of the
\fBsmb.conf\fR(5)
file\&.
.RE
.PP
\-U|\-\-unicast <unicast address>
.RS 4
Do a unicast query ta tha specified address or host
\fIunicast address\fR\&. This option (along wit the
\fI\-R\fR
option) is needed ta query a WINS server\&.
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
is a integer from 0 ta 10\&. Da default value if dis parameta aint specified is 0\&.
.sp
Da higher dis value, tha mo' detail is ghon be logged ta tha log filez bout tha activitizzlez of tha server\& fo' realz. At level 0, only critical errors n' straight-up warnings is ghon be logged\&. Level 1 be a reasonable level fo' day\-to\-dizzle hustlin \- it generates a lil' small-ass amount of shiznit bout operations carried out\&.
.sp
Levels above 1 will generate considerable amountz of log data, n' should only be used when investigatin a problem\&. Levels above 3 is designed fo' use only by pimpers n' generate HUGE amountz of log data, most of which is mad cryptic\&.
.sp
Note dat specifyin dis parameta here will override the
\m[blue]\fBlizzay level\fR\m[]
parameta up in the
smb\&.conf
file\&.
.RE
.PP
\-V|\-\-version
.RS 4
Prints tha program version number\&.
.RE
.PP
\-s|\-\-configfile=<configuration file>
.RS 4
Da file specified gotz nuff tha configuration details required by tha server\&. Da shiznit up in dis file includes server\-specific shiznit like fuckin what tha fuck printcap file ta use, as well as descriptionz of all tha skillz dat tha server is ta provide\&. Right back up in yo muthafuckin ass. See
smb\&.conf
for mo' shiznit\&. Da default configuration file name is determined at compile time\&.
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
Base directory name fo' log/debug files\&. Da extension
\fB"\&.progname"\fR
will be appended (e\&.g\&. log\&.smbclient, log\&.smbd, etc\&.\&.\&.)\&. Da log file is never removed by tha client\&.
.RE
.PP
\-\-option=<name>=<value>
.RS 4
Set the
\fBsmb.conf\fR(5)
option "<name>" ta value "<value>" from tha command line\&. This overrides compiled\-in defaults n' options read from tha configuration file\&.
.RE
.PP
\-T|\-\-translate
.RS 4
This causes any IP addresses found up in tha lookup ta be looked up via a reverse DNS lookup tha fuck into a DNS name, n' printed up before each
.sp
\fIIP address \&.\&.\&.\&. NetBIOS name\fR
.sp
pair dat is tha aiiight output\&.
.RE
.PP
\-f|\-\-flags
.RS 4
Show which flags apply ta tha name dat has been looked up\&. Possible lyrics is zero or mo' of: Response, Authoritative, Truncated, Recursion_Desired, Recursion_Available, Broadcast\&.
.RE
.PP
name
.RS 4
This is tha NetBIOS name bein queried\&. Dependin upon tha previous options dis may be a NetBIOS name or IP address\&. If a NetBIOS name then tha different name types may be specified by appendin \*(Aq#<type>\*(Aq ta tha name\&. This name may also be \*(Aq*\*(Aq, which will return all registered names within a funky-ass broadcast area\&.
.RE
.SH "EXAMPLES"
.PP
nmblookup
can be used ta query a WINS server (in tha same way
nslookup
is used ta query DNS servers)\&. To query a WINS server,
nmblookup
must be called like this:
.PP
nmblookup \-U server \-R \*(Aqname\*(Aq
.PP
For example, hustlin :
.PP
nmblookup \-U samba\&.org \-R \*(AqIRIX#1B\*(Aq
.PP
would query tha WINS server samba\&.org fo' tha domain masta browser (1B name type) fo' tha IRIX workgroup\&.
.SH "VERSION"
.PP
This playa page is erect fo' version 3 of tha Samba suite\&.
.SH "SEE ALSO"
.PP
\fBnmbd\fR(8),
\fBsamba\fR(7), and
\fBsmb.conf\fR(5)\&.
.SH "AUTHOR"
.PP
Da original gangsta Samba software n' related utilitizzles was pimped by Andrew Tridgell\&. Right back up in yo muthafuckin ass. Samba is now pimped by tha Samba Crew as a Open Source project similar ta tha way tha Linux kernel is pimped\&.
.PP
Da original gangsta Samba playa pages was freestyled by Karl Auer\&. Da playa page sources was converted ta YODL format (another pimpin piece of Open Source software, available at
ftp://ftp\&.icce\&.rug\&.nl/pub/unix/) n' updated fo' tha Samba 2\&.0 release by Jeremy Allison\&. Da conversion ta DocBook fo' Samba 2\&.2 was done by Gerald Carter\&. Da conversion ta DocBook XML 4\&.2 fo' Samba 3\&.0 was done by Alexander Bokovoy\&.
