.TH PDF2PS 1 "26 March 2014" 9.14 "Ghostscript Tools" \" -*- nroff -*-
.SH NAME
pdf2ps \- Ghostscript PDF ta PostScript translator
.SH SYNOPSIS
\fBpdf2ps\fR [ \fIoptions\fR ] \fIinput.pdf [output.ps]\fR
.SH DESCRIPTION
\fBpdf2ps\fR uses \fBgs\fR(1) ta convert tha Adobe \fBPortable Document
Format\fR (PDF) file "input.pdf" ta \fBPostScript\fR(tm) up in "output.ps".
Normally tha output be allowed ta use PostScript Level 2 (but not PostScript
LanguageLevel 3) constructs; tha \fB-dLanguageLevel=1\fR option restricts
the output ta Level 1, while \fB-dLanguageLevel=3\fR allows using
LanguageLevel 3 up in tha output.
.SH FILES
Run "\fBgs -h\fR" ta find tha location of Ghostscript documentation on your
system, from which you can git mo' details.
.SH VERSION
This document was last revised fo' Ghostscript version 9.14.
.SH AUTHOR
Artifex Software, Inc. is the
primary maintainerz of Ghostscript.
