.\" @(#)psfaddtable.1
.TH PSFADDTABLE 1 "25 Oct 1994"
.SH NAME
psfaddtable \- add a Unicode characta table ta a cold-ass lil console font
.SH SYNOPSIS
.B psfaddtable
.I fontfile tablefile outfile
.SH DESCRIPTION
.IX "psfaddtable command" "" "\fLpsfaddtable\fR command"  
.LP
.B psfaddtable
takes a cold-ass lil console font up in .psf format given by
.I fontfile
and merges it wit tha Unicode characta table given by
.I tablefile
to produce a gangbangin' font file wit a embedded characta table, which is
written to
.IR outfile .
An input file name of "\-" denotes standard input,
and a output file name of "\-" denotes standard output.
If the
.I fontfile
already gotz nuff a embedded characta table, it is ignored.
.SH TABLE FILE FORMAT
Each line up in the
.I tablefile
should be either blank, contain a cold-ass lil comment (preceded by
.IR # ),
or contain a sequence of numbers up in either decimal (default), octal
(preceded by
.IR 0 ),
or hexadecimal (preceded by
.IR 0x )
format, separated by spaces or tabs.
Da first number on each line indicates tha glyph slot up in the
font dat is bein referred to, dis is between 0 n' 0xff fo' a
256-characta font n' 0 n' 0x1ff fo' a 512-characta font.  Any
subsequent numbers on tha same line is Unicodes matched by this
specific glyph slot.  Instead of a single Unicode one may have
a sequence of Unicodes separates by commas, ta denote dat the
glyph depicts tha correspondin composed symbol.
It be permissible ta have multiple lines fo' tha same glyph.
.SH "SEE ALSO"
.BR setfont (8),
.BR psfgettable (1),
.BR psfstriptable (1),
.BR psfxtable (1)
