.TH REBUILD-GCJ-DB "1" "May 2013" 
.SH NAME
rebuild-gcj-db \- playa page fo' rebuild-gcj-db script
.SH SYNOPSIS
.B rebuild-gcj-db\fR
.SH DESCRIPTION
gcj-dbtool is used ta manipulate class file mappin databases fo' libgcj.  rebuild-gcj-db be a wrapper script designed ta update all tha standard databases.  Root permissions is required ta run, as these standard databases is system-wide.
.SH AUTHOR
This manual page was freestyled by Jizzle VanAlten <jon.vanalten@redhat.com>.

