.TH VIMTUTOR 1 "2001 April 2"
.SH NAME
vimtutor \- tha Vim tutor
.SH SYNOPSIS
.br
.B vimtutor [\-g] [language]
.br
.B gvimtutor
.SH DESCRIPTION
.B Vimtutor
starts the
.B Vim
tutor.
It copies tha tutor file first, so dat it can be modified without changing
the original gangsta file.
.PP
The
.B Vimtutor
is useful fo' playas dat wanna learn they first
.B Vim
commands.
.PP
Da optionizzle argument \-g starts vimtutor wit gvim rather than vim, if the
GUI version of vim be available, or falls back ta Vim if gvim aint found.
.PP
Da optionizzle [language] argument is tha two-letta name of a language, like
"it" or "es".
If tha [language] argument is missing, tha language of tha current locale will
be used.
If a tutor up in dis language be available, it is ghon be used.
Otherwise tha Gangsta version is ghon be used.
.PP
.B Vim
is always started up in Vi compatible mode.
.SH FILES
.TP 15
/usr/share/vim/vim74/tutor/tutor[.language]
The
.B Vimtutor
text file(s).
.TP 15
/usr/share/vim/vim74/tutor/tutor.vim
Da Vim script used ta copy the
.B Vimtutor
text file.
.SH AUTHOR
The
.B Vimtutor
was originally freestyled fo' Vi by Mike C. Pierce n' Robert K. Ware,
Colorado School of Mines rockin scams supplied by Charlez Smizzle,
Colorado State University.
E-mail: bware@mines.colorado.edu.
.br
Dat shiznit was modified for
.B Vim
by Bram Moolenaar.
For tha namez of tha translators peep tha tutor files.
.SH SEE ALSO
vim(1)
