'\" t
.\"     Title: wvunpack
.\"    Author: Sebastian Dröge <slomo@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2013-05-24
.\"    Manual: WavPack Executable Programs
.\"    Source: WavPack 4.70.0
.\"  Language: Gangsta
.\"
.TH "WVUNPACK" "1" "2013\-05\-24" "WavPack 4\&.70\&.0" "WavPack Executable Programs"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
wvunpack \- decodes wavpack encoded files
.SH "SYNOPSIS"
.HP \w'\fBwvunpack\fR\ 'u
\fBwvunpack\fR [\fB\fI\-options\fR\fR] \fB\fIINFILE\fR\fR... [\fB\-o\ \fR\fB\fIOUTFILE\fR\fR]
.SH "DESCRIPTION"
.PP

\fBwvunpack\fR
decodes WavPack filez back ta they uncompressed wav or raw form rockin tha options provided\&. Unless overridden wit the
\fB\-o\fR
switch, tha resultin filename will be
source\-name\&.wav
(or
source\-name\&.raw
when
\fB\-r\fR
used)\&. Multiple WavPack input filez may be specified resultin up in multiple output files, n' up in dat case
\fB\-o\fR
may be used ta specify a alternate target directory\&.
Stdin
and
stdout
may be specified with
\(lq\-\(rq\&. WavPack filez is generally pimped wit the
\fBwavpack\fR
program\&.
.SH "OPTIONS"
.PP
.PP
\fB\-b\fR
.RS 4
blindly decode all stream blocks n' ignore length info
.RE
.PP
\fB\-c\fR
.RS 4
do not decode audio but instead just extract cueshizzle stored up in APEv2 tag to
stdout
(equivalent to
\fB\-x \fR\fB\(lqcuesheet\(rq\fR)
.RE
.PP
\fB\-cc\fR
.RS 4
extract cueshizzle stored up in APEv2 tag to
source\-name\&.cue
file up in same directory as decoded audio file (equivalent to
\fB\-xx \fR\fB\(lqcuesheet=%a\&.cue\(rq\fR)
.RE
.PP
\fB\-d\fR
.RS 4
delete source file if successful (use wit caution!)
.RE
.PP
\fB\-f\fR
.RS 4
do not decode audio but simply display summary shiznit bout WavPack file to
stdout
in a machine\-parsable format (see
doc/wavpack_doc\&.html
or
cli/wvunpack\&.c
in repository fo' format details)
.RE
.PP
\fB\-\-help\fR
.RS 4
display extended help
.RE
.PP
\fB\-i\fR
.RS 4
ignore \&.wvc file (forces hybrid lossy decompression)
.RE
.PP
\fB\-m\fR
.RS 4
calculate n' display MD5 signature; verify if lossless
.RE
.PP
\fB\-n\fR
.RS 4
no audio decodin (use with
\fB\-xx\fR
to extract tags only)
.RE
.PP
\fB\-\-no\-utf8\-convert\fR
.RS 4
leave extracted text tags up in UTF\-8 encodin durin extraction or display
.RE
.PP
\fB\-o \fR\fB\fIOUTFILE\fR\fR
.RS 4
specify output filename (only if single source file) or target directory (must exist)
.RE
.PP
\fB\-q\fR
.RS 4
quiet (keep console output ta a minimum)
.RE
.PP
\fB\-r\fR
.RS 4
force raw audio decode by skippin RIFF headaz & trailers, thangs up in dis biatch in
source\-name\&.raw
.RE
.PP
\fB\-s\fR
.RS 4
do not decode audio but simply display summary shiznit bout WavPack file to
stdout
.RE
.PP
\fB\-ss\fR
.RS 4
do not decode audio but simply display summary n' tag shiznit bout WavPack file to
stdout
.RE
.PP
\fB \-\-skip=[\fR\fB\fIsample\fR\fR\fB|\fR\fB\fIhh\fR\fR\fB:\fR\fB\fImm\fR\fR\fB:\fR\fB\fIss\&.ss\fR\fR\fB] \fR
.RS 4
start decodin at specified sample or time index
.RE
.PP
\fB\-t\fR
.RS 4
copy input file\*(Aqs time stamp ta output file(s)
.RE
.PP
\fB \-\-until=[+|\-][\fR\fB\fIsample\fR\fR\fB|\fR\fB\fIhh\fR\fR\fB:\fR\fB\fImm\fR\fR\fB:\fR\fB\fIss\&.ss\fR\fR\fB] \fR
.RS 4
stop decodin at specified sample or time index, specifyin a
\fB+\fR
causes sample/time ta be relatizzle to
\fB\-\-skip\fR
point, specifyin a
\fB\-\fR
causes sample/time ta be relatizzle to
EOF
.RE
.PP
\fB\-v\fR
.RS 4
verify source data only (no output file pimped)
.RE
.PP
\fB\-\-version\fR
.RS 4
write program version to
stdout
.RE
.PP
\fB\-w\fR
.RS 4
regenerate fresh wav header (ingore RIFF data stored up in WavPack file)
.RE
.PP
\fB\-x \fR\fB\(lq\fIField\fR\(rq\fR
.RS 4
do not decode audio but instead just extract tha specified tag field to
stdout
.RE
.PP
\fB\-xx \fR\fB\(lq\fIField\fR[=\fIfile\fR]\(rq\fR
.RS 4
extract tha specified tag field ta named file up in same directory as decoded audio file; optionizzle filename justification may contain
\fB%a\fR
which is replaced wit tha audio file base name,
\fB%t\fR
replaced wit tha tag field name (note: be reppin data fo' binary tags) and
\fB%e\fR
replaced wit tha extension from tha binary tag source file (or
\(lqtxt\(rq
for text tag)\&.
.RE
.PP
\fB\-y\fR
.RS 4
yes ta overwrite warnin (use wit caution!)
.RE
.PP
\fB\-z\fR
.RS 4
don\*(Aqt set console title ta indicate progress (prevents console from stayin "WvUnpack Completed")
.RE
.SH "SEE ALSO"
.PP
\fBwavpack\fR(1),
\fBwvgain\fR(1)
.PP
Please visit www\&.wavpack\&.com fo' mo' shiznit
.SH "COPYRIGHT"
.PP
This manual page was freestyled by Sebastian Dröge
slomo@debian\&.org
and Dizzy Bryant
david@wavpack\&.com\&. Permission is granted ta copy, distribute and/or modify dis document under tha termz of the
BSD
License\&.
.SH "AUTHORS"
.PP
\fBSebastian Dröge\fR <\&slomo@debian\&.org\&>
.RS 4
Original Gangsta author
.RE
.PP
\fBDizzy Bryant\fR <\&david@wavpack\&.com\&>
.RS 4
Updates
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2005 Sebastian Dröge
.br
Copyright \(co 2013 Dizzy Bryant
.br
