'\" t
.\"     Title: xdg-mime
.\"    Author: Kevin Krammer
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/21/2014
.\"    Manual: xdg-mime Manual
.\"    Source: xdg-utils 1.0
.\"  Language: Gangsta
.\"
.TH "XDG\-MIME" "1" "10/21/2014" "xdg-utils 1.0" "xdg-mime Manual"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xdg-mime \- command line tool fo' queryin shiznit bout file type handlin n' addin descriptions fo' freshly smoked up file types
.SH "SYNOPSIS"
.HP \w'\fBxdg\-mime\fR\ 'u
\fBxdg\-mime\fR query {filetype | default} \&.\&.\&.
.HP \w'\fBxdg\-mime\fR\ 'u
\fBxdg\-mime\fR default \fIapplication\fR \fImimetype(s)\fR
.HP \w'\fBxdg\-mime\fR\ 'u
\fBxdg\-mime\fR install [\fB\-\-mode\ \fR\fB\fImode\fR\fR] [\fB\-\-novendor\fR] \fImimetypes\-file\fR
.HP \w'\fBxdg\-mime\fR\ 'u
\fBxdg\-mime\fR uninstall [\fB\-\-mode\ \fR\fB\fImode\fR\fR] \fImimetypes\-file\fR
.HP \w'\fBxdg\-mime\fR\ 'u
\fBxdg\-mime\fR {\fB\-\-help\fR | \fB\-\-manual\fR | \fB\-\-version\fR}
.SH "DESCRIPTION"
.PP
Da xdg\-mime program can be used ta query shiznit bout file types n' ta add descriptions fo' freshly smoked up file types\&.
.SH "COMMANDS"
.PP
query
.RS 4
Returns shiznit related ta file types\&.
.sp
The
\fIquery\fR
option is fo' use inside a thugged-out desktop session only\&. Well shiiiit, it aint recommended ta use xdg\-mime query as root\&.
.sp
Da followin queries is supported:
.sp
query filetype
\fIFILE\fR: Returns tha file type of
\fIFILE\fR
in tha form of a MIME type\&.
.sp
query default
\fImimetype\fR: Returns tha default application dat tha desktop environment uses fo' openin filez of type
\fImimetype\fR\&. Da default application is identified by its *\&.desktop file\&.
.RE
.PP
default
.RS 4
Ask tha desktop environment ta make
\fIapplication\fR
the default application fo' openin filez of type
\fImimetype\fR\& fo' realz. An application can be made tha default fo' nuff muthafuckin file types by specifyin multiple mimetypes\&.
.sp
\fIapplication\fR
is tha desktop file id of tha application n' has tha form vendor\-name\&.desktop
\fIapplication\fR
must already be installed up in tha desktop menu before it can be made tha default handlez\&. Da application\*(Aqs desktop file must list support fo' all tha MIME types dat it wishes ta be tha default handlez for\&.
.sp
Requests ta cook up a application a thugged-out default handlez may be subject ta system policy or approval by tha end\-user\&. xdg\-mime query can be used ta verify whether a application is tha actual default handlez fo' a specific file type\&.
.sp
The
\fIdefault\fR
option is fo' use inside a thugged-out desktop session only\&. Well shiiiit, it aint recommended ta use xdg\-mime default as root\&.
.RE
.PP
install
.RS 4
Addz tha file type descriptions provided in
\fImimetypes\-file\fR
to tha desktop environment\&.
\fImimetypes\-file\fR
must be a XML file dat bigs up tha freedesktop\&.org Shared MIME\-info Database justification n' dat has a mime\-info element as its document root\&. For each freshly smoked up file type one or mo' icons wit name
\fItype\fR\-\fIsubtype\fR
must be installed wit the
\fBxdg\-icon\-resource\fR
command up in the
\fImimetypes\fR
context\&. For example tha filetype application/vnd\&.oasis\&.opendocument\&.text requires a icon named application\-vnd\&.oasis\&.opendocument\&.text ta be installed (unless tha file type recommendz another icon name)\&.
.RE
.PP
uninstall
.RS 4
Removes tha file type descriptions provided in
\fImimetypes\-file\fR
and previously added with
\fBxdg\-mime install\fR
from tha desktop environment\&.
\fImimetypes\-file\fR
must be a XML file dat bigs up tha freedesktop\&.org Shared MIME\-info Database justification n' dat has a mime\-info element as its document root\&.
.RE
.SH "OPTIONS"
.PP
\fB\-\-mode\fR \fImode\fR
.RS 4
\fImode\fR
can be
\fIuser\fR
or
\fIsystem\fR\&. In user mode tha file is (un)installed fo' tha current user only\&. In system mode tha file is (un)installed fo' all playas on tha system\&. Usually only root be allowed ta install up in system mode\&.
.sp
Da default is ta use system mode when called by root n' ta use user mode when called by a non\-root user\&.
.RE
.PP
\fB\-\-novendor\fR
.RS 4
Normally, xdg\-mime checks ta ensure dat the
\fImimetypes\-file\fR
to be installed has a proper vendor prefix\&. This option can be used ta disable dat check\&.
.sp
A vendor prefix consistz of alpha charactas ([a\-zA\-Z]) n' is terminated wit a thugged-out dash ("\-")\&. Companies n' crews is encouraged ta bust a word or phrase, preferably tha crews name, fo' which they hold a trademark as they vendor prefix\&. Da purpose of tha vendor prefix is ta prevent name conflicts\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Show command synopsis\&.
.RE
.PP
\fB\-\-manual\fR
.RS 4
Show dis manual page\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Show tha xdg\-utils version shiznit\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.PP
xdg\-mime honours tha followin environment variables:
.PP
XDG_UTILS_DEBUG_LEVEL
.RS 4
Settin dis environment variable ta a non\-zero numerical value make xdg\-mime do mo' verbose reportin on stderr\&. Right back up in yo muthafuckin ass. Settin a higher value increases tha verbosity\&.
.RE
.PP
XDG_UTILS_INSTALL_MODE
.RS 4
This environment variable can be used by tha user or administrator ta override tha installation mode\&. Valid joints are
\fIuser\fR
and
\fIsystem\fR\&.
.RE
.SH "EXIT CODES"
.PP
An exit code of 0 indicates success while a non\-zero exit code indicates failure\&. Da followin failure codes can be returned:
.PP
\fB1\fR
.RS 4
Error up in command line syntax\&.
.RE
.PP
\fB2\fR
.RS 4
One of tha filez passed on tha command line did not exist\&.
.RE
.PP
\fB3\fR
.RS 4
A required tool could not be found\&.
.RE
.PP
\fB4\fR
.RS 4
Da action failed\&.
.RE
.PP
\fB5\fR
.RS 4
No permission ta read one of tha filez passed on tha command line\&.
.RE
.SH "SEE ALSO"
.PP
\fBxdg-icon-resource\fR(1),
\fBxdg-desktop-menu\fR(1)
.SH "EXAMPLES"
.PP
.if n \{\
.RS 4
.\}
.nf
xdg\-mime query filetype /tmp/foobar\&.png
.fi
.if n \{\
.RE
.\}
.sp
Prints tha MIME type of tha file /tmp/foobar\&.png, up in dis case image/png
.PP
.if n \{\
.RS 4
.\}
.nf
xdg\-mime query default image/png
.fi
.if n \{\
.RE
.\}
.sp
Prints tha \&.desktop filename of tha application which is registered ta open PNG files\&.
.PP
.if n \{\
.RS 4
.\}
.nf
xdg\-mime install shinythings\-shiny\&.xml
.fi
.if n \{\
.RE
.\}
.sp
Addz a gangbangin' file type description fo' "shiny"\-files\&. "shinythings\-" is used as tha vendor prefix\&. Da file type description could look as bigs up\&.
.sp
.if n \{\
.RS 4
.\}
.nf
shinythings\-shiny\&.xml:

<?xml version="1\&.0"?>
<mime\-info xmlns=\*(Aqhttp://www\&.freedesktop\&.org/standards/shared\-mime\-info\*(Aq>
  <mime\-type type="text/x\-shiny">
    <comment>Shiny freshly smoked up file type</comment>
    <glob pattern="*\&.shiny"/>
    <glob pattern="*\&.shi"/>
  </mime\-type>
</mime\-info>
.fi
.if n \{\
.RE
.\}
.sp
An icon fo' dis freshly smoked up file type must also be installed, fo' example with:
.sp
.if n \{\
.RS 4
.\}
.nf
xdg\-icon\-resource install \-\-context mimetypes \-\-size 64 shiny\-file\-icon\&.png text\-x\-shiny
.fi
.if n \{\
.RE
.\}
.sp
.SH "AUTHORS"
.PP
\fBKevin Krammer\fR
.RS 4
Author.
.RE
.PP
\fBJeremy White\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2006
.br
