.\" yum-config-manager
.TH "yum-config-manager" "1" "13 January 2013" "" ""
.SH "NAME"
yum-config-manager \- manage yum configuration options n' yum repositories
.SH "SYNOPSIS"
\fByum-config-manager\fP [options]
.SH "DESCRIPTION"
.PP
\fByum-config-manager\fP be a program dat can manage main yum configuration
options, toggle which repositories is enabled or disabled, n' add new
repositories.
.PP
.SH "OPTIONS"
.IP "\fB\-h, \-\-help\fP"
Display a help message, n' then quit.
.IP "\fB\-\-save\fP"
Save tha current options (useful wit \-\-setopt).
.IP "\fB\-\-enable\fP"
Enable tha specified repos (automatically saves).
.IP "\fB\-\-disable\fP"
Disable tha specified repos (automatically saves).
.IP "\fB\-\-add\-repo=ADDREPO\fP"
Add (and enable) tha repo from tha specified file or url.
.SH "ADDITIONAL OPTIONS"
Yum-config-manager inherits all other options from yum. Right back up in yo muthafuckin ass. See tha yum(8)
man page fo' mo' shiznit.

.PP
.SH "SEE ALSO"
.nf
.I yum.conf (5)
http://yum.baseurl.org/
.fi

.PP
.SH "AUTHORS"
.nf
See tha Authors file included wit dis program.
.fi
