" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::_Caster< _ToType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _ToType::element_type * \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _ToType>struct __gnu_cxx::_Caster< _ToType >"
These functions is here ta allow containers ta support non standard pointa types\&. For aiiight pointers, these resolve ta tha use of tha standard cast operation\&. For other types tha functions will big-ass up tha apprpriate cast to/from tha custom pointa class so long as dat class meets tha followin conditions: 1) has a typedef element_type which names tehe type it points to\&. 2) has a get() const method which returns element_type*\&. 3) has a cold-ass lil constructor which can take one element_type* argument\&. This type supports tha semantics of tha pointa cast operators (below\&.) 
.PP
Definizzle at line 52 of file cast\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen fo' libstdc++ from tha source code\&.
