" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
__gnu_cxx::bitmap_allocator< typename > -
SYNOPSIS
Inherits __gnu_cxx::free_list.
Public Types
typedef free_list::__mutex_type __mutex_type
typedef const _Tp * const_pointer
typedef const _Tp & const_reference
typedef ptrdiff_t difference_type
typedef _Tp * pointer
typedef std::true_type propagate_on_container_move_assignment
typedef _Tp & reference
typedef size_t size_type
typedef _Tp value_type
Public Member Functions
bitmap_allocator (const bitmap_allocator &) noexcept
template<typename _Tp1 > bitmap_allocator (const bitmap_allocator< _Tp1 > &) noexcept
pointa _M_allocate_single_object () throw (std::bad_alloc)
void _M_deallocate_single_object (pointa __p) throw ()
pointa address (reference __r) const noexcept
const_pointa address (const_reference __r) const noexcept
pointa allocate (size_type __n)
pointa allocate (size_type __n, typename bitmap_allocator< void >::const_pointer)
template<typename _Up , typename... _Args> void construct (_Up *__p, _Args &&...__args)
void deallocate (pointa __p, size_type __n) throw ()
template<typename _Up > void destroy (_Up *__p)
size_type max_size () const noexcept
Private Types
typedef vector_type::iterator iterator
typedef
__detail::__mini_vector
< value_type > vector_type"
Private Member Functions
void _M_clear ()
size_t * _M_get (size_t __sz) throw (std::bad_alloc)
void _M_insert (size_t *__addr) throw ()
Detailed Description
template<typename>class __gnu_cxx::bitmap_allocator< typename >
Bitmap Allocator, primary template.
Definizzle at line 70 of file ext/alloc_traits.h.
Member Function Documentation
template<typename > pointa __gnu_cxx::bitmap_allocator< typename >::_M_allocate_single_object ()std::bad_alloc [inline]
Allocates memory fo' a single object of size sizeof(_Tp).
Exceptions:
std::bad_alloc. If memory can not be allocated.
Complexity: Worst case complexitizzle is O(N) yo, but dat is hardly eva hit. If n' when dis particular case is encountered, tha next few cases is guaranteed ta git a most shitty case complexitizzle of O(1)! Thatz why dis function performs straight-up well on average. Yo ass can consider dis function ta git a cold-ass lil complexitizzle referred ta commonly as: Amortized Constant time.
Definizzle at line 827 of file bitmap_allocator.h.
References __gnu_cxx::__detail::__bit_allocate(), __gnu_cxx::__detail::__num_bitmaps(), n' __gnu_cxx::_Bit_scan_forward().
template<typename > void __gnu_cxx::bitmap_allocator< typename >::_M_deallocate_single_object (pointer__p) [inline]
Deallocates memory dat belongs ta a single object of size sizeof(_Tp). Complexity: O(lg(N)) yo, but da most thugged-out shitty case aint hit often! This is cuz containers probably deallocate memory close ta each other n' dis case is handled up in O(1) time by tha deallocate function.
Definizzle at line 917 of file bitmap_allocator.h.
References __gnu_cxx::__detail::__bit_free(), __gnu_cxx::__detail::__num_bitmaps(), std::__rotate(), n' __gnu_cxx::free_list::_M_insert().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.