" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_LoserTreeTraits< _Tp > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fB_M_use_pointer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp>struct __gnu_parallel::_LoserTreeTraits< _Tp >"
Traits fo' determinin whether tha weak-ass muthafucka tree should use pointas or copies\&. 

Da field '_M_use_pointer' is used ta determine whether ta use pointas up in he weak-ass muthafucka trees or whether ta copy tha joints tha fuck into tha weak-ass muthafucka tree\&.
.PP
Da default behavior is ta use pointas if tha data type is 4 times as big-ass as tha pointa ta it\&.
.PP
Specialize fo' yo' data type ta customize tha behavior\&.
.PP
Example:
.PP
template<> struct _LoserTreeTraits<int> { static const bool _M_use_pointa = false; };
.PP
template<> struct _LoserTreeTraits<heavyweight_type> { static const bool _M_use_pointa = true; };
.PP
\fBParameters:\fP
.RS 4
\fI_Tp\fP type ta give tha weak-ass muthafucka tree traits for\&. 
.RE
.PP

.PP
Definizzle at line 731 of file multiway_merge\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _Tp > const bool \fB__gnu_parallel::_LoserTreeTraits\fP< _Tp >::_M_use_pointer\fC [static]\fP"

.PP
True iff ta use pointas instead of joints up in weak-ass muthafucka trees\&. Da default behavior is ta use pointas if tha data type is four times as big-ass as tha pointa ta it\&. 
.PP
Definizzle at line 739 of file multiway_merge\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen fo' libstdc++ from tha source code\&.
