__gnu_debug
NAME
__gnu_debug -
SYNOPSIS
Classes
class _After_nth_from
struct _BeforeBeginHelper
class _Equal_to
class _Not_equal_to
class _Safe_iterator
class _Safe_iterator_base
class _Safe_local_iterator
class _Safe_local_iterator_base
class _Safe_sequence
class _Safe_sequence_base
class _Safe_unordered_container
class _Safe_unordered_container_base
class basic_string
Typedefs
typedef basic_string< char > string
typedef basic_string< wchar_t > wstring
Enumerations
enum _Debug_msg_id { __msg_valid_range, __msg_insert_singular, __msg_insert_different, __msg_erase_bad, __msg_erase_different, __msg_subscript_oob, __msg_empty, __msg_unpartitioned, __msg_unpartitioned_pred, __msg_unsorted, __msg_unsorted_pred, __msg_not_heap, __msg_not_heap_pred, __msg_bad_bitset_write, __msg_bad_bitset_read, __msg_bad_bitset_flip, __msg_self_splice, __msg_splice_alloc, __msg_splice_bad, __msg_splice_other, __msg_splice_overlap, __msg_init_singular, __msg_init_copy_singular, __msg_init_const_singular, __msg_copy_singular, __msg_bad_deref, __msg_bad_inc, __msg_bad_dec, __msg_iter_subscript_oob, __msg_advance_oob, __msg_retreat_oob, __msg_iter_compare_bad, __msg_compare_different, __msg_iter_order_bad, __msg_order_different, __msg_distance_bad, __msg_distance_different, __msg_deref_istream, __msg_inc_istream, __msg_output_ostream, __msg_deref_istreambuf, __msg_inc_istreambuf, __msg_insert_after_end, __msg_erase_after_bad, __msg_valid_range2, __msg_local_iter_compare_bad, __msg_non_empty_range, __msg_self_move_assign, __msg_bucket_index_oob, __msg_valid_load_factor, __msg_equal_allocs }
enum _Distance_precision { __dp_equality, __dp_sign, __dp_exact }
Functions
template<typename _Iterator > _Siter_base< _Iterator >
::iterator_type __base (_Iterator __it)"
template<typename _Iterator > bool __check_dereferenceable (_Iterator &)
template<typename _Tp > bool __check_dereferenceable (const _Tp *__ptr)
template<typename _Iterator , typename _Sequence > bool __check_dereferenceable (const _Safe_iterator< _Iterator, _Sequence > &__x)
template<typename _ForwardIterator , typename _Tp > bool __check_partitioned_lower (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _ForwardIterator , typename _Tp , typename _Pred > bool __check_partitioned_lower (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value, _Pred __pred)
template<typename _ForwardIterator , typename _Tp > bool __check_partitioned_upper (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _ForwardIterator , typename _Tp , typename _Pred > bool __check_partitioned_upper (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value, _Pred __pred)
template<typename _Iterator > bool __check_singular (_Iterator &)
template<typename _Tp > bool __check_singular (const _Tp *__ptr)
template<typename _Iterator , typename _Sequence > bool __check_singular (const _Safe_iterator< _Iterator, _Sequence > &__x)
bool __check_singular_aux (const void *)
bool __check_singular_aux (const _Safe_iterator_base *__x)
template<typename _InputIterator > bool __check_sorted (const _InputIterator &__first, const _InputIterator &__last)
template<typename _InputIterator , typename _Predicate > bool __check_sorted (const _InputIterator &__first, const _InputIterator &__last, _Predicate __pred)
template<typename _InputIterator > bool __check_sorted_aux (const _InputIterator &, const _InputIterator &, std::input_iterator_tag)
template<typename _ForwardIterator > bool __check_sorted_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _Iterator , typename _Sequence > bool __check_sorted_aux (const _Safe_iterator< _Iterator, _Sequence > &__first, const _Safe_iterator< _Iterator, _Sequence > &__last, std::random_access_iterator_tag __tag)
template<typename _InputIterator , typename _Predicate > bool __check_sorted_aux (const _InputIterator &, const _InputIterator &, _Predicate, std::input_iterator_tag)
template<typename _ForwardIterator , typename _Predicate > bool __check_sorted_aux (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, std::forward_iterator_tag)
template<typename _Iterator , typename _Sequence , typename _Predicate > bool __check_sorted_aux (const _Safe_iterator< _Iterator, _Sequence > &__first, const _Safe_iterator< _Iterator, _Sequence > &__last, _Predicate __pred, std::random_access_iterator_tag __tag)
template<typename _InputIterator1 , typename _InputIterator2 > bool __check_sorted_set (const _InputIterator1 &__first, const _InputIterator1 &__last, const _InputIterator2 &)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Predicate > bool __check_sorted_set (const _InputIterator1 &__first, const _InputIterator1 &__last, const _InputIterator2 &, _Predicate __pred)
template<typename _InputIterator > bool __check_sorted_set_aux (const _InputIterator &__first, const _InputIterator &__last, std::__true_type)
template<typename _InputIterator > bool __check_sorted_set_aux (const _InputIterator &, const _InputIterator &, std::__false_type)
template<typename _InputIterator , typename _Predicate > bool __check_sorted_set_aux (const _InputIterator &__first, const _InputIterator &__last, _Predicate __pred, std::__true_type)
template<typename _InputIterator , typename _Predicate > bool __check_sorted_set_aux (const _InputIterator &, const _InputIterator &, _Predicate, std::__false_type)
template<typename _CharT , typename _Integer > const _CharT * __check_string (const _CharT *__s, const _Integer &__n __attribute__((__unused__)))
template<typename _CharT > const _CharT * __check_string (const _CharT *__s)
template<typename _InputIterator > _InputIterator __check_valid_range (const _InputIterator &__first, const _InputIterator &__last __attribute__((__unused__)))
template<typename _Iterator1 , typename _Iterator2 > std::pair< typename
std::iterator_traits
< _Iterator1 >
::difference_type,
_Distance_precision > __get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs, std::random_access_iterator_tag)"
template<typename _Iterator1 , typename _Iterator2 > std::pair< typename
std::iterator_traits
< _Iterator1 >
::difference_type,
_Distance_precision > __get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs, std::forward_iterator_tag)"
template<typename _Iterator1 , typename _Iterator2 > std::pair< typename
std::iterator_traits
< _Iterator1 >
::difference_type,
_Distance_precision > __get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs)"
template<typename _InputIterator > bool __valid_range (const _InputIterator &__first, const _InputIterator &__last)
template<typename _Iterator , typename _Sequence > bool __valid_range (const _Safe_iterator< _Iterator, _Sequence > &__first, const _Safe_iterator< _Iterator, _Sequence > &__last)
template<typename _Iterator , typename _Sequence > bool __valid_range (const _Safe_local_iterator< _Iterator, _Sequence > &__first, const _Safe_local_iterator< _Iterator, _Sequence > &__last)
template<typename _Integral > bool __valid_range_aux (const _Integral &, const _Integral &, std::__true_type)
template<typename _InputIterator > bool __valid_range_aux (const _InputIterator &__first, const _InputIterator &__last, std::__false_type)
template<typename _RandomAccessIterator > bool __valid_range_aux2 (const _RandomAccessIterator &__first, const _RandomAccessIterator &__last, std::random_access_iterator_tag)
template<typename _InputIterator > bool __valid_range_aux2 (const _InputIterator &, const _InputIterator &, std::input_iterator_tag)
template<typename _CharT , typename _Traits , typename _Allocator > std::basic_istream< _CharT,
_Traits > & getline (std::basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Allocator > &__str, _CharT __delim)"
template<typename _CharT , typename _Traits , typename _Allocator > std::basic_istream< _CharT,
_Traits > & getline (std::basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Allocator > &__str)"
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator!= (const _Safe_local_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_local_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator!= (const _Safe_local_iterator< _Iterator, _Sequence > &__lhs, const _Safe_local_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator!= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator!= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator!= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator!= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator!= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _Iterator , typename _Sequence > _Safe_iterator< _Iterator,
_Sequence > operator+ (typename _Safe_iterator< _Iterator, _Sequence >::difference_type __n, const _Safe_iterator< _Iterator, _Sequence > &__i)"
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits,
_Allocator > operator+ (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)"
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits,
_Allocator > operator+ (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)"
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits,
_Allocator > operator+ (_CharT __lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)"
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits,
_Allocator > operator+ (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)"
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits,
_Allocator > operator+ (const basic_string< _CharT, _Traits, _Allocator > &__lhs, _CharT __rhs)"
template<typename _IteratorL , typename _IteratorR , typename _Sequence > _Safe_iterator< _IteratorL,
_Sequence >::difference_type operator- (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)"
template<typename _Iterator , typename _Sequence > _Safe_iterator< _Iterator,
_Sequence >::difference_type operator- (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)"
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator< (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator< (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator< (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator< (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator< (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const basic_string< _CharT, _Traits, _Allocator > &__str)"
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator<= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator<= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator<= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator<= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator<= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator== (const _Safe_local_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_local_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator== (const _Safe_local_iterator< _Iterator, _Sequence > &__lhs, const _Safe_local_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator== (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator== (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator== (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator== (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator== (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator> (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator> (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator> (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator> (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator> (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator>= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator>= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator>= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator>= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator>= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Allocator > &__str)"
template<typename _CharT , typename _Traits , typename _Allocator > void swap (basic_string< _CharT, _Traits, _Allocator > &__lhs, basic_string< _CharT, _Traits, _Allocator > &__rhs)
Detailed Description
GNU debug classes fo' hood use.
Enumeration Type Documentation
enum __gnu_debug::_Distance_precision
Da precision ta which we can calculate tha distizzle between two iterators.
Definizzle at line 70 of file safe_iterator.h.
Function Documentation
template<typename _Iterator > _Siter_base<_Iterator>::iterator_type __gnu_debug::__base (_Iterator__it) [inline]
Helper function ta extract base iterator of random access safe iterator up in order ta reduce performizzle impact of debug mode. Limited ta random access iterator cuz it is tha only category fo' which it is possible ta check fo' erect iterators order up in tha __valid_range function props ta tha < operator.
Definizzle at line 446 of file functions.h.
Referenced by __gnu_parallel::__for_each_template_random_access_workstealing(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable(), std::boolalpha(), std::dec(), std::fixed(), std::hex(), std::internal(), std::left(), std::noboolalpha(), std::noshowbase(), std::noshowpoint(), std::noshowpos(), std::noskipws(), std::nounitbuf(), std::nouppercase(), std::oct(), std::right(), std::scientific(), std::showbase(), std::showpoint(), std::showpos(), std::skipws(), std::unitbuf(), n' std::uppercase().
template<typename _Iterator > bool __gnu_debug::__check_dereferenceable (_Iterator &) [inline]
Assume dat some arbitrary iterator is dereferenceable, cuz we can't prove dat it aint.
Definizzle at line 70 of file functions.h.
template<typename _Tp > bool __gnu_debug::__check_dereferenceable (const _Tp *__ptr) [inline]
Non-NULL pointas is dereferenceable.
Definizzle at line 76 of file functions.h.
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__check_dereferenceable (const _Safe_iterator< _Iterator, _Sequence > &__x) [inline]
Safe iterators know if they is singular.
Definizzle at line 82 of file functions.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
template<typename _Tp > bool __gnu_debug::__check_singular (const _Tp *__ptr) [inline]
Non-NULL pointas is nonsingular.
Definizzle at line 57 of file functions.h.
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__check_singular (const _Safe_iterator< _Iterator, _Sequence > &__x) [inline]
Safe iterators know if they is singular.
Definizzle at line 63 of file functions.h.
References __gnu_debug::_Safe_iterator_base::_M_singular().
bool __gnu_debug::__check_singular_aux (const _Safe_iterator_base *__x) [inline]
Iterators dat derive from _Safe_iterator_base but dat aren't _Safe_iterators can be determined singular or non-singular via _Safe_iterator_base.
Definizzle at line 64 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_singular().
template<typename _CharT , typename _Integer > const _CharT* __gnu_debug::__check_strin (const _CharT *__s, const _Integer &__n __attribute__(__unused__)) [inline]
Checks dat __s is non-NULL or __n == 0, n' then returns __s.
Definizzle at line 168 of file functions.h.
template<typename _CharT > const _CharT* __gnu_debug::__check_strin (const _CharT *__s) [inline]
Checks dat __s is non-NULL n' then returns __s.
Definizzle at line 180 of file functions.h.
template<typename _Iterator1 , typename _Iterator2 > std::pair<typename std::iterator_traits<_Iterator1>::difference_type, _Distance_precision> __gnu_debug::__get_distizzle (const _Iterator1 &__lhs, const _Iterator2 &__rhs, std::random_access_iterator_tag) [inline]
Determine tha distizzle between two iterators wit some known precision.
Definizzle at line 83 of file safe_iterator.h.
References std::make_pair().
template<typename _InputIterator > bool __gnu_debug::__valid_range (const _InputIterator &__first, const _InputIterator &__last) [inline]
Don't know what tha fuck these iterators are, or if they is even iterators (we may git a integral type fo' InputIterator), so peep if they is integral n' pass dem on ta tha next phase otherwise.
Definizzle at line 131 of file functions.h.
References __valid_range_aux().
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__valid_range (const _Safe_iterator< _Iterator, _Sequence > &__first, const _Safe_iterator< _Iterator, _Sequence > &__last) [inline]
Safe iterators know how tha fuck ta check if they form a valid range.
Definizzle at line 140 of file functions.h.
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__valid_range (const _Safe_local_iterator< _Iterator, _Sequence > &__first, const _Safe_local_iterator< _Iterator, _Sequence > &__last) [inline]
Safe local iterators know how tha fuck ta check if they form a valid range.
Definizzle at line 147 of file functions.h.
template<typename _Integral > bool __gnu_debug::__valid_range_aux (const _Integral &, const _Integral &, std::__true_type) [inline]
We say dat integral types fo' a valid range, n' defer ta other routines ta realize what tha fuck ta do wit integral types instead of iterators.
Definizzle at line 111 of file functions.h.
Referenced by __valid_range().
template<typename _InputIterator > bool __gnu_debug::__valid_range_aux (const _InputIterator &__first, const _InputIterator &__last, std::__false_type) [inline]
Our thugged-out asses have iterators, so figure up what tha fuck kind of iterators dat is ta peep if we can check tha range ahead of time.
Definizzle at line 119 of file functions.h.
References std::__iterator_category(), n' __valid_range_aux2().
template<typename _RandomAccessIterator > bool __gnu_debug::__valid_range_aux2 (const _RandomAccessIterator &__first, const _RandomAccessIterator &__last, std::random_access_iterator_tag) [inline]
If tha distizzle between two random access iterators is nonnegative, assume tha range is valid.
Definizzle at line 90 of file functions.h.
Referenced by __valid_range_aux().
template<typename _InputIterator > bool __gnu_debug::__valid_range_aux2 (const _InputIterator &, const _InputIterator &, std::input_iterator_tag) [inline]
Can't test fo' a valid range wit input iterators, cuz iteration may be destructive. Right back up in yo muthafuckin ass. So our laid-back asses just assume dat tha range is valid.
Definizzle at line 101 of file functions.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.