" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::detail::types_traits< Key, Mapped, _Alloc, Store_Hash > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_pbds::detail::type_base< Key, Mapped, _Alloc, Store_Hash >\fP\&.
.PP
Inherited by \fB__gnu_pbds::detail::cc_ht_map< Key, Mapped, Hash_Fn, Eq_Fn, _Alloc, Store_Hash, Comb_Hash_Fn, Resize_Policy >\fP, n' \fB__gnu_pbds::detail::gp_ht_map< Key, Mapped, Hash_Fn, Eq_Fn, _Alloc, Store_Hash, Comb_Probe_Fn, Probe_Fn, Resize_Policy >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::pair\fP< size_type, 
.br
size_type > \fBcomp_hash\fP"
.br
.ti -1c
.RI "typedef __rebind_a::const_pointa \fBkey_const_pointer\fP"
.br
.ti -1c
.RI "typedef __rebind_a::const_reference \fBkey_const_reference\fP"
.br
.ti -1c
.RI "typedef __rebind_a::pointa \fBkey_pointer\fP"
.br
.ti -1c
.RI "typedef __rebind_a::reference \fBkey_reference\fP"
.br
.ti -1c
.RI "typedef __rebind_a::value_type \fBkey_type\fP"
.br
.ti -1c
.RI "typedef __nothrowcopy::indicator \fBno_throw_indicator\fP"
.br
.ti -1c
.RI "typedef _Alloc::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef integral_constant< int, 
.br
Store_Hash > \fBstore_extra\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "no_throw_indicator \fBm_no_throw_copies_indicator\fP"
.br
.ti -1c
.RI "store_extra \fBm_store_extra_indicator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Key, typename Mapped, typename _Alloc, bool Store_Hash>struct __gnu_pbds::detail::types_traits< Key, Mapped, _Alloc, Store_Hash >"
Traits fo' abstract types\&. 
.PP
Definizzle at line 263 of file types_traits\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen fo' libstdc++ from tha source code\&.
