__gnu_parallel
NAME
__gnu_parallel -
SYNOPSIS
Classes
struct __accumulate_binop_reduct
struct __accumulate_selector
struct __adjacent_difference_selector
struct __adjacent_find_selector
class __binder1st
class __binder2nd
struct __count_if_selector
struct __count_selector
struct __fill_selector
struct __find_first_of_selector
struct __find_if_selector
struct __for_each_selector
struct __generate_selector
struct __generic_find_selector
struct __generic_for_each_selector
struct __identity_selector
struct __inner_product_selector
struct __max_element_reduct
struct __min_element_reduct
struct __mismatch_selector
struct __multiway_merge_3_variant_sentinel_switch
struct __multiway_merge_3_variant_sentinel_switch< true, _RAIterIterator, _RAIter3, _DifferenceTp, _Compare >
struct __multiway_merge_4_variant_sentinel_switch
struct __multiway_merge_4_variant_sentinel_switch< true, _RAIterIterator, _RAIter3, _DifferenceTp, _Compare >
struct __multiway_merge_k_variant_sentinel_switch
struct __multiway_merge_k_variant_sentinel_switch< false, __stable, _RAIterIterator, _RAIter3, _DifferenceTp, _Compare >
struct __replace_if_selector
struct __replace_selector
struct __transform1_selector
struct __transform2_selector
class __unary_negate
struct _DRandomShufflingGlobalData
struct _DRSSorterPU
struct _DummyReduct
class _EqualFromLess
struct _EqualTo
class _GuardedIterator
class _IteratorPair
class _IteratorTriple
struct _Job
struct _Less
class _Lexicographic
class _LexicographicReverse
class _LoserTree
class _LoserTree< false, _Tp, _Compare >
class _LoserTreeBase
class _LoserTreePointer
class _LoserTreePointer< false, _Tp, _Compare >
class _LoserTreePointerBase
class _LoserTreePointerUnguarded
class _LoserTreePointerUnguarded< false, _Tp, _Compare >
class _LoserTreePointerUnguardedBase
struct _LoserTreeTraits
class _LoserTreeUnguarded
class _LoserTreeUnguarded< false, _Tp, _Compare >
class _LoserTreeUnguardedBase
struct _Multiplies
struct _Nothing
struct _Piece
struct _Plus
struct _PMWMSSortingData
class _PseudoSequence
class _PseudoSequenceIterator
struct _QSBThreadLocal
class _RandomNumber
class _RestrictedBoundedConcurrentQueue
struct _SamplingSorter
struct _SamplingSorter< false, _RAIter, _StrictWeakOrderin >
struct _Settings
struct _SplitConsistently
struct _SplitConsistently< false, _RAIter, _Compare, _SortingPlacesIterator >
struct _SplitConsistently< true, _RAIter, _Compare, _SortingPlacesIterator >
struct balanced_quicksort_tag
struct balanced_tag
struct constant_size_blocks_tag
struct default_parallel_tag
struct equal_split_tag
struct exact_tag
struct find_tag
struct growing_blocks_tag
struct multiway_mergesort_exact_tag
struct multiway_mergesort_sampling_tag
struct multiway_mergesort_tag
struct omp_loop_static_tag
struct omp_loop_tag
struct parallel_tag
struct quicksort_tag
struct sampling_tag
struct sequential_tag
struct unbalanced_tag
Typedefs
typedef unsigned short _BinIndex
typedef int64_t _CASable
typedef uint64_t _SequenceIndex
typedef uint16_t _ThreadIndex
Enumerations
enum _AlgorithmStrategy { heuristic, force_sequential, force_parallel }
enum _FindAlgorithm { GROWING_BLOCKS, CONSTANT_SIZE_BLOCKS, EQUAL_SPLIT }
enum _MultiwayMergeAlgorithm { LOSER_TREE }
enum _Parallelism { sequential, parallel_unbalanced, parallel_balanced, parallel_omp_loop, parallel_omp_loop_static, parallel_taskqueue }
enum _PartialSumAlgorithm { RECURSIVE, LINEAR }
enum _SortAlgorithm { MWMS, QS, QS_BALANCED }
enum _SplittingAlgorithm { SAMPLING, EXACT }
Functions
template<typename _Tp > _Tp __add_omp (volatile _Tp *__ptr, _Tp __addend)
template<typename _RAIta , typename _DifferenceTp > void __calc_borders (_RAIta __elements, _DifferenceTp __length, _DifferenceTp *__off)
template<typename _Tp > bool __cas_omp (volatile _Tp *__ptr, _Tp __comparand, _Tp __replacement)
template<typename _Tp > bool __compare_and_swap (volatile _Tp *__ptr, _Tp __comparand, _Tp __replacement)
template<typename _IIta , typename _OutputIterator > _OutputIterator __copy_tail (std::pair< _IIter, _IIta > __b, std::pair< _IIter, _IIta > __e, _OutputIterator __r)
void __decode2 (_CASable __x, int &__a, int &__b)
template<typename _RAIta , typename _DifferenceTp > void __determine_samples (_PMWMSSortingData< _RAIta > *__sd, _DifferenceTp __num_samples)
_CASable __encode2 (int __a, int __b)
template<typename _DifferenceType , typename _OutputIterator > _OutputIterator __equally_split (_DifferenceType __n, _ThreadIndex __num_threads, _OutputIterator __s)
template<typename _DifferenceType > _DifferenceType __equally_split_point (_DifferenceType __n, _ThreadIndex __num_threads, _ThreadIndex __thread_no)
template<typename _Tp > _Tp __fetch_and_add (volatile _Tp *__ptr, _Tp __addend)
template<typename _RAIter1 , typename _RAIter2 , typename _Pred , typename _Selector > std::pair< _RAIter1, _RAIter2 > __find_template (_RAIter1 __begin1, _RAIter1 __end1, _RAIter2 __begin2, _Pred __pred, _Selector __selector)
template<typename _RAIter1 , typename _RAIter2 , typename _Pred , typename _Selector > std::pair< _RAIter1, _RAIter2 > __find_template (_RAIter1 __begin1, _RAIter1 __end1, _RAIter2 __begin2, _Pred __pred, _Selector __selector, equal_split_tag)
template<typename _RAIter1 , typename _RAIter2 , typename _Pred , typename _Selector > std::pair< _RAIter1, _RAIter2 > __find_template (_RAIter1 __begin1, _RAIter1 __end1, _RAIter2 __begin2, _Pred __pred, _Selector __selector, growing_blocks_tag)
template<typename _RAIter1 , typename _RAIter2 , typename _Pred , typename _Selector > std::pair< _RAIter1, _RAIter2 > __find_template (_RAIter1 __begin1, _RAIter1 __end1, _RAIter2 __begin2, _Pred __pred, _Selector __selector, constant_size_blocks_tag)
template<typename _IIta , typename _UserOp , typename _Functionalitizzle , typename _Red , typename _Result > _UserOp __for_each_template_random_access (_IIta __begin, _IIta __end, _UserOp __user_op, _Functionalitizzle &__functionality, _Red __reduction, _Result __reduction_start, _Result &__output, typename std::iterator_traits< _IIta >::difference_type __bound, _Parallelism __parallelism_tag)
template<typename _RAIta , typename _Op , typename _Fu , typename _Red , typename _Result > _Op __for_each_template_random_access_ed (_RAIta __begin, _RAIta __end, _Op __o, _Fu &__f, _Red __r, _Result __base, _Result &__output, typename std::iterator_traits< _RAIta >::difference_type __bound)
template<typename _RAIta , typename _Op , typename _Fu , typename _Red , typename _Result > _Op __for_each_template_random_access_omp_loop (_RAIta __begin, _RAIta __end, _Op __o, _Fu &__f, _Red __r, _Result __base, _Result &__output, typename std::iterator_traits< _RAIta >::difference_type __bound)
template<typename _RAIta , typename _Op , typename _Fu , typename _Red , typename _Result > _Op __for_each_template_random_access_omp_loop_static (_RAIta __begin, _RAIta __end, _Op __o, _Fu &__f, _Red __r, _Result __base, _Result &__output, typename std::iterator_traits< _RAIta >::difference_type __bound)
template<typename _RAIta , typename _Op , typename _Fu , typename _Red , typename _Result > _Op __for_each_template_random_access_workstealing (_RAIta __begin, _RAIta __end, _Op __op, _Fu &__f, _Red __r, _Result __base, _Result &__output, typename std::iterator_traits< _RAIta >::difference_type __bound)
_ThreadIndex __get_max_threads ()
bool __is_parallel (const _Parallelism __p)
template<typename _IIta , typename _Compare > bool __is_sorted (_IIta __begin, _IIta __end, _Compare __comp)
template<typename _RAIta , typename _Compare > _RAIta __median_of_three_iterators (_RAIta __a, _RAIta __b, _RAIta __c, _Compare __comp)
template<typename _RAIter1 , typename _RAIter2 , typename _OutputIterator , typename _DifferenceTp , typename _Compare > _OutputIterator __merge_advance (_RAIter1 &__begin1, _RAIter1 __end1, _RAIter2 &__begin2, _RAIter2 __end2, _OutputIterator __target, _DifferenceTp __max_length, _Compare __comp)
template<typename _RAIter1 , typename _RAIter2 , typename _OutputIterator , typename _DifferenceTp , typename _Compare > _OutputIterator __merge_advance_movc (_RAIter1 &__begin1, _RAIter1 __end1, _RAIter2 &__begin2, _RAIter2 __end2, _OutputIterator __target, _DifferenceTp __max_length, _Compare __comp)
template<typename _RAIter1 , typename _RAIter2 , typename _OutputIterator , typename _DifferenceTp , typename _Compare > _OutputIterator __merge_advance_usual (_RAIter1 &__begin1, _RAIter1 __end1, _RAIter2 &__begin2, _RAIter2 __end2, _OutputIterator __target, _DifferenceTp __max_length, _Compare __comp)
template<typename _RAIter1 , typename _RAIter2 , typename _RAIter3 , typename _Compare > _RAIter3 __parallel_merge_advance (_RAIter1 &__begin1, _RAIter1 __end1, _RAIter2 &__begin2, _RAIter2 __end2, _RAIter3 __target, typename std::iterator_traits< _RAIter1 >::difference_type __max_length, _Compare __comp)
template<typename _RAIter1 , typename _RAIter3 , typename _Compare > _RAIter3 __parallel_merge_advance (_RAIter1 &__begin1, _RAIter1 __end1, _RAIter1 &__begin2, _RAIter1 __end2, _RAIter3 __target, typename std::iterator_traits< _RAIter1 >::difference_type __max_length, _Compare __comp)
template<typename _RAIta , typename _Compare > void __parallel_nth_element (_RAIta __begin, _RAIta __nth, _RAIta __end, _Compare __comp)
template<typename _RAIta , typename _Compare > void __parallel_partial_sort (_RAIta __begin, _RAIta __middle, _RAIta __end, _Compare __comp)
template<typename _IIta , typename _OutputIterator , typename _BinaryOperation > _OutputIterator __parallel_partial_sum (_IIta __begin, _IIta __end, _OutputIterator __result, _BinaryOperation __bin_op)
template<typename _IIta , typename _OutputIterator , typename _BinaryOperation > _OutputIterator __parallel_partial_sum_basecase (_IIta __begin, _IIta __end, _OutputIterator __result, _BinaryOperation __bin_op, typename std::iterator_traits< _IIta >::value_type __value)
template<typename _IIta , typename _OutputIterator , typename _BinaryOperation > _OutputIterator __parallel_partial_sum_linear (_IIta __begin, _IIta __end, _OutputIterator __result, _BinaryOperation __bin_op, typename std::iterator_traits< _IIta >::difference_type __n)
template<typename _RAIta , typename _Predicate > std::iterator_traits< _RAIta >
::difference_type __parallel_partition (_RAIta __begin, _RAIta __end, _Predicate __pred, _ThreadIndex __num_threads)"
template<typename _RAIta , typename _RandomNumberGenerator > void __parallel_random_shuffle (_RAIta __begin, _RAIta __end, _RandomNumberGenerator __rng=_RandomNumber())
template<typename _RAIta , typename _RandomNumberGenerator > void __parallel_random_shuffle_drs (_RAIta __begin, _RAIta __end, typename std::iterator_traits< _RAIta >::difference_type __n, _ThreadIndex __num_threads, _RandomNumberGenerator &__rng)
template<typename _RAIta , typename _RandomNumberGenerator > void __parallel_random_shuffle_drs_pu (_DRSSorterPU< _RAIter, _RandomNumberGenerator > *__pus)
template<typename _IIta , typename _OutputIterator , typename _Compare > _OutputIterator __parallel_set_difference (_IIta __begin1, _IIta __end1, _IIta __begin2, _IIta __end2, _OutputIterator __result, _Compare __comp)
template<typename _IIta , typename _OutputIterator , typename _Compare > _OutputIterator __parallel_set_intersection (_IIta __begin1, _IIta __end1, _IIta __begin2, _IIta __end2, _OutputIterator __result, _Compare __comp)
template<typename _IIta , typename _OutputIterator , typename _Operation > _OutputIterator __parallel_set_operation (_IIta __begin1, _IIta __end1, _IIta __begin2, _IIta __end2, _OutputIterator __result, _Operation __op)
template<typename _IIta , typename _OutputIterator , typename _Compare > _OutputIterator __parallel_set_symmetric_difference (_IIta __begin1, _IIta __end1, _IIta __begin2, _IIta __end2, _OutputIterator __result, _Compare __comp)
template<typename _IIta , typename _OutputIterator , typename _Compare > _OutputIterator __parallel_set_union (_IIta __begin1, _IIta __end1, _IIta __begin2, _IIta __end2, _OutputIterator __result, _Compare __comp)
template<bool __stable, typename _RAIta , typename _Compare , typename _Parallelizzle > void __parallel_sort (_RAIta __begin, _RAIta __end, _Compare __comp, _Parallelism __parallelism)
template<bool __stable, typename _RAIta , typename _Compare > void __parallel_sort (_RAIta __begin, _RAIta __end, _Compare __comp, multiway_mergesort_tag __parallelism)
template<bool __stable, typename _RAIta , typename _Compare > void __parallel_sort (_RAIta __begin, _RAIta __end, _Compare __comp, multiway_mergesort_exact_tag __parallelism)
template<bool __stable, typename _RAIta , typename _Compare > void __parallel_sort (_RAIta __begin, _RAIta __end, _Compare __comp, multiway_mergesort_sampling_tag __parallelism)
template<bool __stable, typename _RAIta , typename _Compare > void __parallel_sort (_RAIta __begin, _RAIta __end, _Compare __comp, quicksort_tag __parallelism)
template<bool __stable, typename _RAIta , typename _Compare > void __parallel_sort (_RAIta __begin, _RAIta __end, _Compare __comp, balanced_quicksort_tag __parallelism)
template<bool __stable, typename _RAIta , typename _Compare > void __parallel_sort (_RAIta __begin, _RAIta __end, _Compare __comp, default_parallel_tag __parallelism)
template<bool __stable, typename _RAIta , typename _Compare > void __parallel_sort (_RAIta __begin, _RAIta __end, _Compare __comp, parallel_tag __parallelism)
template<typename _RAIta , typename _Compare > void __parallel_sort_qs (_RAIta __begin, _RAIta __end, _Compare __comp, _ThreadIndex __num_threads)
template<typename _RAIta , typename _Compare > void __parallel_sort_qs_conquer (_RAIta __begin, _RAIta __end, _Compare __comp, _ThreadIndex __num_threads)
template<typename _RAIta , typename _Compare > std::iterator_traits< _RAIta >
::difference_type __parallel_sort_qs_divide (_RAIta __begin, _RAIta __end, _Compare __comp, typename std::iterator_traits< _RAIta >::difference_type __pivot_rank, typename std::iterator_traits< _RAIta >::difference_type __num_samples, _ThreadIndex __num_threads)"
template<typename _RAIta , typename _Compare > void __parallel_sort_qsb (_RAIta __begin, _RAIta __end, _Compare __comp, _ThreadIndex __num_threads)
template<typename _IIta , class _OutputIterator , class _BinaryPredicate > _OutputIterator __parallel_unique_copy (_IIta __first, _IIta __last, _OutputIterator __result, _BinaryPredicate __binary_pred)
template<typename _IIta , class _OutputIterator > _OutputIterator __parallel_unique_copy (_IIta __first, _IIta __last, _OutputIterator __result)
template<typename _RAIta , typename _Compare > void __qsb_conquer (_QSBThreadLocal< _RAIta > **__tls, _RAIta __begin, _RAIta __end, _Compare __comp, _ThreadIndex __iam, _ThreadIndex __num_threads, bool __parent_wait)
template<typename _RAIta , typename _Compare > std::iterator_traits< _RAIta >
::difference_type __qsb_divide (_RAIta __begin, _RAIta __end, _Compare __comp, _ThreadIndex __num_threads)"
template<typename _RAIta , typename _Compare > void __qsb_local_sort_with_helping (_QSBThreadLocal< _RAIta > **__tls, _Compare &__comp, _ThreadIndex __iam, bool __wait)
template<typename _RandomNumberGenerator > int __random_number_pow2 (int __logp, _RandomNumberGenerator &__rng)
template<typename _Size > _Size __rd_log2 (_Size __n)
template<typename _Tp > _Tp __round_up_to_pow2 (_Tp __x)
template<typename __RAIter1 , typename __RAIter2 , typename _Pred > __RAIter1 __search_template (__RAIter1 __begin1, __RAIter1 __end1, __RAIter2 __begin2, __RAIter2 __end2, _Pred __pred)
template<bool __stable, bool __sentinels, typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 __sequential_multiway_merge (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _RAIter3 __target, const typename std::iterator_traits< typename std::iterator_traits< _RAIterIterator >::value_type::first_type >::value_type &__sentinel, _DifferenceTp __length, _Compare __comp)
template<typename _RAIta , typename _RandomNumberGenerator > void __sequential_random_shuffle (_RAIta __begin, _RAIta __end, _RandomNumberGenerator &__rng)
template<typename _IIta > void __shrink (std::vector< _IIta > &__os_starts, size_t &__count_to_two, size_t &__range_length)
template<typename _IIta > void __shrink_and_double (std::vector< _IIta > &__os_starts, size_t &__count_to_two, size_t &__range_length, const bool __make_twice)
void __yield ()
template<typename _IIta , typename _FunctorType > size_t list_partition (const _IIta __begin, const _IIta __end, _IIta *__starts, size_t *__lengths, const int __num_parts, _FunctorType &__f, int __oversampling=0)
template<typename _Tp > const _Tp & max (const _Tp &__a, const _Tp &__b)
template<typename _Tp > const _Tp & min (const _Tp &__a, const _Tp &__b)
template<typename _RanSeqs , typename _RankType , typename _RankIterator , typename _Compare > void multiseq_partition (_RanSeqs __begin_seqs, _RanSeqs __end_seqs, _RankType __rank, _RankIterator __begin_offsets, _Compare __comp=std::less< typename std::iterator_traits< typename std::iterator_traits< _RanSeqs >::value_type::first_type >::value_type >())
template<typename _Tp , typename _RanSeqs , typename _RankType , typename _Compare > _Tp multiseq_selection (_RanSeqs __begin_seqs, _RanSeqs __end_seqs, _RankType __rank, _RankType &__offset, _Compare __comp=std::less< _Tp >())
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::sequential_tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::exact_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::sampling_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, parallel_tag __tag=parallel_tag(0))
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, default_parallel_tag __tag)
template<template< typename RAI, typename C > class iterator, typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 multiway_merge_3_variant (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _RAIter3 __target, _DifferenceTp __length, _Compare __comp)
template<template< typename RAI, typename C > class iterator, typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 multiway_merge_4_variant (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _RAIter3 __target, _DifferenceTp __length, _Compare __comp)
template<bool __stable, typename _RAIterIterator , typename _Compare , typename _DifferenceType > void multiway_merge_exact_splitting (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _DifferenceType __length, _DifferenceType __total_length, _Compare __comp, std::vector< std::pair< _DifferenceType, _DifferenceType > > *__pieces)
template<typename _LT , typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 multiway_merge_loser_tree (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _RAIter3 __target, _DifferenceTp __length, _Compare __comp)
template<typename UnguardedLoserTree , typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 multiway_merge_loser_tree_sentinel (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _RAIter3 __target, const typename std::iterator_traits< typename std::iterator_traits< _RAIterIterator >::value_type::first_type >::value_type &__sentinel, _DifferenceTp __length, _Compare __comp)
template<typename _LT , typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 multiway_merge_loser_tree_unguarded (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _RAIter3 __target, const typename std::iterator_traits< typename std::iterator_traits< _RAIterIterator >::value_type::first_type >::value_type &__sentinel, _DifferenceTp __length, _Compare __comp)
template<bool __stable, typename _RAIterIterator , typename _Compare , typename _DifferenceType > void multiway_merge_sampling_splitting (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _DifferenceType __length, _DifferenceType __total_length, _Compare __comp, std::vector< std::pair< _DifferenceType, _DifferenceType > > *__pieces)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::sequential_tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::exact_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, sampling_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, parallel_tag __tag=parallel_tag(0))
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, default_parallel_tag __tag)
template<bool __stable, bool __sentinels, typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Splitta , typename _Compare > _RAIter3 parallel_multiway_merge (_RAIterIterator __seqs_begin, _RAIterIterator __seqs_end, _RAIter3 __target, _Splitta __splitter, _DifferenceTp __length, _Compare __comp, _ThreadIndex __num_threads)
template<bool __stable, bool __exact, typename _RAIta , typename _Compare > void parallel_sort_mwms (_RAIta __begin, _RAIta __end, _Compare __comp, _ThreadIndex __num_threads)
template<bool __stable, bool __exact, typename _RAIta , typename _Compare > void parallel_sort_mwms_pu (_PMWMSSortingData< _RAIta > *__sd, _Compare &__comp)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::sequential_tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::exact_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, sampling_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, parallel_tag __tag=parallel_tag(0))
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, default_parallel_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::sequential_tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, __gnu_parallel::exact_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, sampling_tag __tag)
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, parallel_tag __tag=parallel_tag(0))
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut stable_multiway_merge_sentinels (_RAIterPairIterator __seqs_begin, _RAIterPairIterator __seqs_end, _RAIterOut __target, _DifferenceTp __length, _Compare __comp, default_parallel_tag __tag)
Variables
static const int _CASable_bits
static const _CASable _CASable_mask
Detailed Description
GNU parallel code fo' hood use.
Typedef Documentation
typedef unsigned short __gnu_parallel::_BinIndex
Type ta hold tha index of a funky-ass bin. Right back up in yo muthafuckin ass. Since nuff variablez of dis type is allocated, it should be chosen as lil' small-ass as possible.
Definizzle at line 47 of file random_shuffle.h.
typedef int64_t __gnu_parallel::_CASable
Longest compare-and-swappable integer type on dis platform.
Definizzle at line 127 of file types.h.
typedef uint64_t __gnu_parallel::_SequenceIndex
Unsigned integer ta index __elements. Da total number of elements fo' each algorithm must fit tha fuck into dis type.
Definizzle at line 117 of file types.h.
typedef uint16_t __gnu_parallel::_ThreadIndex
Unsigned integer ta index a thread number. Da maximum thread number (for each processor) must fit tha fuck into dis type.
Definizzle at line 123 of file types.h.
Enumeration Type Documentation
enum __gnu_parallel::_AlgorithmStrategy
Strategies fo' run-time algorithm selection:
Definizzle at line 67 of file types.h.
enum __gnu_parallel::_FindAlgorithm
Find algorithms:
Definizzle at line 106 of file types.h.
enum __gnu_parallel::_MultiwayMergeAlgorithm
Mergin algorithms:
Definizzle at line 85 of file types.h.
enum __gnu_parallel::_Parallelism
Run-time equivalents fo' tha compile-time tags.
Enumerator
sequential
Not parallel.
parallel_unbalanced
Parallel unbalanced (equal-sized chunks).
parallel_balanced
Parallel balanced (work-stealing).
parallel_omp_loop
Parallel wit OpenMP dynamic load-balancing.
parallel_omp_loop_static
Parallel wit OpenMP static load-balancing.
parallel_taskqueue
Parallel wit OpenMP taskqueue construct.
Definizzle at line 44 of file types.h.
enum __gnu_parallel::_PartialSumAlgorithm
Partial sum algorithms: recursive, linear.
Definizzle at line 91 of file types.h.
enum __gnu_parallel::_SortAlgorithm
Sortin algorithms:
Definizzle at line 76 of file types.h.
enum __gnu_parallel::_SplittingAlgorithm
Sorting/mergin algorithms: sampling, __exact.
Definizzle at line 98 of file types.h.
Function Documentation
template<typename _RAIta , typename _DifferenceTp > void __gnu_parallel::__calc_bordaz (_RAIter__elements, _DifferenceTp__length, _DifferenceTp *__off)
Precalculate __advances fo' Knuth-Morris-Pratt algorithm.
Parameters:
__elements Begin iterator of sequence ta search for.
__length Length of sequence ta search for.
__off Returned __offsets.
Definizzle at line 51 of file search.h.
Referenced by __search_template().
template<typename _Tp > bool __gnu_parallel::__compare_and_swap (volatile _Tp *__ptr, _Tp__comparand, _Tp__replacement) [inline]
Compare-and-swap. Compare *__ptr n' __comparand. If equal, let *__ptr=__replacement n' return true, return false otherwise.
Parameters:
__ptr Pointa ta signed integer.
__comparand Compare value.
__replacement Replacement value.
Definizzle at line 108 of file parallel/compatibility.h.
Referenced by __parallel_partition(), __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::pop_back(), n' __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::pop_front().
void __gnu_parallel::__decode2 (_CASable__x, int &__a, int &__b) [inline]
Decode two integers from one gnu_parallel::_CASable.
Parameters:
__x __gnu_parallel::_CASable ta decode integers from.
__a First integer, ta be decoded from da most thugged-out-significant _CASable_bits/2 bitz of __x.
__b Second integer, ta be encoded up in tha least-significant _CASable_bits/2 bitz of __x.
See Also:
__encode2
Definizzle at line 133 of file parallel/base.h.
References _CASable_bits, n' _CASable_mask.
Referenced by __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::pop_back(), __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::pop_front(), n' __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::push_front().
template<typename _RAIta , typename _DifferenceTp > void __gnu_parallel::__determine_samplez (_PMWMSSortingData< _RAIta > *__sd, _DifferenceTp__num_samples)
Select _M_samplez from a sequence.
Parameters:
__sd Pointa ta algorithm data. _Result is ghon be placed up in __sd->_M_samples.
__num_samples Number of _M_samplez ta select.
Definizzle at line 97 of file multiway_mergesort.h.
References __equally_split(), __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_samples, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_source, n' __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_starts.
_CASable __gnu_parallel::__encode2 (int__a, int__b) [inline]
Encode two integers tha fuck into one gnu_parallel::_CASable.
Parameters:
__a First integer, ta be encoded up in da most thugged-out-significant _CASable_bits/2 bits.
__b Second integer, ta be encoded up in tha least-significant _CASable_bits/2 bits.
Returns:
value encodin __a n' __b.
See Also:
__decode2
Definizzle at line 119 of file parallel/base.h.
References _CASable_bits.
Referenced by __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::_RestrictedBoundedConcurrentQueue(), __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::pop_back(), __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::pop_front(), n' __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::push_front().
template<typename _DifferenceType , typename _OutputIterator > _OutputIterator __gnu_parallel::__equally_split (_DifferenceType__n, _ThreadIndex__num_threads, _OutputIterator__s)
function ta split a sequence tha fuck into partz of almost equal size. Da resultin sequence __z of length __num_threads+1 gotz nuff tha splittin positions when splittin tha range [0,__n) tha fuck into partz of almost equal size (plus minus 1). Da first entry is 0, tha last one n. There may result empty parts.
Parameters:
__n Number of elements
__num_threads Number of parts
__s Splittas
Returns:
End of __splitta sequence, i.e. __s+__num_threads+1
Definizzle at line 48 of file equally_split.h.
Referenced by __determine_samples(), __find_template(), __parallel_partial_sum_linear(), __parallel_unique_copy(), __search_template(), n' multiway_merge_exact_splitting().
template<typename _DifferenceType > _DifferenceType __gnu_parallel::__equally_split_point (_DifferenceType__n, _ThreadIndex__num_threads, _ThreadIndex__thread_no)
function ta split a sequence tha fuck into partz of almost equal size. Returns tha posizzle of tha splittin point between thread number __thread_no (included) n' thread number __thread_no+1 (excluded).
Parameters:
__n Number of elements
__num_threads Number of parts
__thread_no Number of threadz
Returns:
splittin point
Definizzle at line 75 of file equally_split.h.
Referenced by __for_each_template_random_access_ed().
template<typename _Tp > _Tp __gnu_parallel::__fetch_and_add (volatile _Tp *__ptr, _Tp__addend) [inline]
Add a value ta a variable, atomically.
Parameters:
__ptr Pointa ta a signed integer.
__addend Value ta add.
Definizzle at line 74 of file parallel/compatibility.h.
Referenced by __parallel_partition(), n' __gnu_parallel::_RestrictedBoundedConcurrentQueue< pair< _RAIter, _RAIta > >::push_front().
template<typename _RAIter1 , typename _RAIter2 , typename _Pred , typename _Selector > std::pair<_RAIter1, _RAIter2> __gnu_parallel::__find_template (_RAIter1__begin1, _RAIter1__end1, _RAIter2__begin2, _Pred__pred, _Selector__selector) [inline]
Parallel std::find, switch fo' different algorithms.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence. Must have same length as first sequence.
__pred Find predicate.
__selector _Functionalitizzle (e. g. std::find_if(), std::equal(),...)
Returns:
Place of findin up in both sequences.
Definizzle at line 60 of file find.h.
References __gnu_parallel::_Settings::get(), n' std::make_pair().
template<typename _RAIter1 , typename _RAIter2 , typename _Pred , typename _Selector > std::pair<_RAIter1, _RAIter2> __gnu_parallel::__find_template (_RAIter1__begin1, _RAIter1__end1, _RAIter2__begin2, _Pred__pred, _Selector__selector, equal_split_tag)
Parallel std::find, equal splittin variant.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence. Right back up in yo muthafuckin ass. Second __sequence must have same length as first sequence.
__pred Find predicate.
__selector _Functionalitizzle (e. g. std::find_if(), std::equal(),...)
Returns:
Place of findin up in both sequences.
Definizzle at line 97 of file find.h.
References __equally_split(), n' _GLIBCXX_CALL.
template<typename _RAIter1 , typename _RAIter2 , typename _Pred , typename _Selector > std::pair<_RAIter1, _RAIter2> __gnu_parallel::__find_template (_RAIter1__begin1, _RAIter1__end1, _RAIter2__begin2, _Pred__pred, _Selector__selector, growing_blocks_tag)
Parallel std::find, growin block size variant.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence. Right back up in yo muthafuckin ass. Second __sequence must have same length as first sequence.
__pred Find predicate.
__selector _Functionalitizzle (e. g. std::find_if(), std::equal(),...)
Returns:
Place of findin up in both sequences.
See Also:
__gnu_parallel::_Settings::find_sequential_search_size
__gnu_parallel::_Settings::find_scale_factor
There is two main differences between tha growin blocks n' tha constant-size blocks variants. 1. For GB, tha block size grows; fo' CSB, tha block size is fixed. 2. For GB, tha blocks is allocated dynamically; fo' CSB, tha blocks is allocated up in a predetermined manner, namely spacial round-robin.
Definizzle at line 185 of file find.h.
References _GLIBCXX_CALL, __gnu_parallel::_Settings::find_scale_factor, __gnu_parallel::_Settings::find_sequential_search_size, n' __gnu_parallel::_Settings::get().
template<typename _RAIter1 , typename _RAIter2 , typename _Pred , typename _Selector > std::pair<_RAIter1, _RAIter2> __gnu_parallel::__find_template (_RAIter1__begin1, _RAIter1__end1, _RAIter2__begin2, _Pred__pred, _Selector__selector, constant_size_blocks_tag)
Parallel std::find, constant block size variant.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence. Right back up in yo muthafuckin ass. Second __sequence must have same length as first sequence.
__pred Find predicate.
__selector _Functionalitizzle (e. g. std::find_if(), std::equal(),...)
Returns:
Place of findin up in both sequences.
See Also:
__gnu_parallel::_Settings::find_sequential_search_size
__gnu_parallel::_Settings::find_block_size There is two main differences between tha growin blocks n' tha constant-size blocks variants. 1. For GB, tha block size grows; fo' CSB, tha block size is fixed. 2. For GB, tha blocks is allocated dynamically; fo' CSB, tha blocks is allocated up in a predetermined manner, namely spacial round-robin.
Definizzle at line 315 of file find.h.
References _GLIBCXX_CALL, __gnu_parallel::_Settings::find_initial_block_size, __gnu_parallel::_Settings::find_sequential_search_size, n' __gnu_parallel::_Settings::get().
template<typename _IIta , typename _UserOp , typename _Functionalitizzle , typename _Red , typename _Result > _UserOp __gnu_parallel::__for_each_template_random_access (_IIter__begin, _IIter__end, _UserOp__user_op, _Functionalitizzle &__functionality, _Red__reduction, _Result__reduction_start, _Result &__output, typename std::iterator_traits< _IIta >::difference_type__bound, _Parallelism__parallelism_tag)
Chose tha desired algorithm by evaluatin __parallelism_tag.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__user_op A user-specified functor (comparator, predicate, associatizzle operator,...)
__functionality functor ta process a element wit __user_op (dependz on desired functionality, e. g. accumulate, for_each,...
__reduction Reduction functor.
__reduction_start Initial value fo' reduction.
__output Output iterator.
__bound Maximum number of elements processed.
__parallelism_tag Parallelization method
Definizzle at line 61 of file for_each.h.
References __for_each_template_random_access_ed(), __for_each_template_random_access_omp_loop(), __for_each_template_random_access_workstealing(), parallel_omp_loop, parallel_omp_loop_static, n' parallel_unbalanced.
template<typename _RAIta , typename _Op , typename _Fu , typename _Red , typename _Result > _Op __gnu_parallel::__for_each_template_random_access_ed (_RAIter__begin, _RAIter__end, _Op__o, _Fu &__f, _Red__r, _Result__base, _Result &__output, typename std::iterator_traits< _RAIta >::difference_type__bound)
Embarrassingly parallel algorithm fo' random access iterators, rockin hand-crafted parallelization by equal splittin tha work.
Parameters:
__begin Begin iterator of element sequence.
__end End iterator of element sequence.
__o User-supplied functor (comparator, predicate, addin functor, ...)
__f Functor ta 'process' a element wit __op (dependz on desired functionality, e. g. fo' std::for_each(), ...).
__r Functor ta 'add' a single __result ta tha already processed elements (dependz on functionality).
__base Base value fo' reduction.
__output Pointa ta posizzle where final result is freestyled ta
__bound Maximum number of elements processed (e. g. fo' std::count_n()).
Returns:
User-supplied functor (that may contain a part of tha result).
Definizzle at line 67 of file par_loop.h.
References __equally_split_point().
Referenced by __for_each_template_random_access().
template<typename _RAIta , typename _Op , typename _Fu , typename _Red , typename _Result > _Op __gnu_parallel::__for_each_template_random_access_omp_loop (_RAIter__begin, _RAIter__end, _Op__o, _Fu &__f, _Red__r, _Result__base, _Result &__output, typename std::iterator_traits< _RAIta >::difference_type__bound)
Embarrassingly parallel algorithm fo' random access iterators, rockin a OpenMP fo' loop.
Parameters:
__begin Begin iterator of element sequence.
__end End iterator of element sequence.
__o User-supplied functor (comparator, predicate, addin functor, etc.).
__f Functor ta process a element wit __op (dependz on desired functionality, e. g. fo' std::for_each(), ...).
__r Functor ta add a single __result ta tha already processed elements (dependz on functionality).
__base Base value fo' reduction.
__output Pointa ta posizzle where final result is freestyled ta
__bound Maximum number of elements processed (e. g. fo' std::count_n()).
Returns:
User-supplied functor (that may contain a part of tha result).
Definizzle at line 67 of file omp_loop.h.
Referenced by __for_each_template_random_access().
template<typename _RAIta , typename _Op , typename _Fu , typename _Red , typename _Result > _Op __gnu_parallel::__for_each_template_random_access_omp_loop_static (_RAIter__begin, _RAIter__end, _Op__o, _Fu &__f, _Red__r, _Result__base, _Result &__output, typename std::iterator_traits< _RAIta >::difference_type__bound)
Embarrassingly parallel algorithm fo' random access iterators, rockin a OpenMP fo' loop wit static scheduling.
Parameters:
__begin Begin iterator of element sequence.
__end End iterator of element sequence.
__o User-supplied functor (comparator, predicate, addin functor, ...).
__f Functor ta process a element wit __op (dependz on desired functionality, e. g. fo' std::for_each(), ...).
__r Functor ta add a single __result ta tha already processed __elements (dependz on functionality).
__base Base value fo' reduction.
__output Pointa ta posizzle where final result is freestyled ta
__bound Maximum number of elements processed (e. g. fo' std::count_n()).
Returns:
User-supplied functor (that may contain a part of tha result).
Definizzle at line 66 of file omp_loop_static.h.
template<typename _RAIta , typename _Op , typename _Fu , typename _Red , typename _Result > _Op __gnu_parallel::__for_each_template_random_access_workstealin (_RAIter__begin, _RAIter__end, _Op__op, _Fu &__f, _Red__r, _Result__base, _Result &__output, typename std::iterator_traits< _RAIta >::difference_type__bound)
Work jackin algorithm fo' random access iterators. Uses O(1) additionizzle memory. Right back up in yo muthafuckin ass. Synchronization at thang lists is done wit atomic operations.
Parameters:
__begin Begin iterator of element sequence.
__end End iterator of element sequence.
__op User-supplied functor (comparator, predicate, addin functor, ...).
__f Functor ta process a element wit __op (dependz on desired functionality, e. g. fo' std::for_each(), ...).
__r Functor ta add a single __result ta tha already processed elements (dependz on functionality).
__base Base value fo' reduction.
__output Pointa ta posizzle where final result is freestyled ta
__bound Maximum number of elements processed (e. g. fo' std::count_n()).
Returns:
User-supplied functor (that may contain a part of tha result).
Definizzle at line 99 of file workstealing.h.
References __gnu_debug::__base(), __yield(), _GLIBCXX_CALL, __gnu_parallel::_Job< _DifferenceTp >::_M_first, __gnu_parallel::_Job< _DifferenceTp >::_M_last, __gnu_parallel::_Job< _DifferenceTp >::_M_load, __gnu_parallel::_Settings::cache_line_size, __gnu_parallel::_Settings::get(), n' min().
Referenced by __for_each_template_random_access().
template<typename _IIta , typename _Compare > bool __gnu_parallel::__is_sorted (_IIter__begin, _IIter__end, _Compare__comp)
Peep whether [__begin, __end) is sorted accordin ta __comp.
Parameters:
__begin Begin iterator of sequence.
__end End iterator of sequence.
__comp Comparator.
Returns:
true if sorted, false otherwise.
Definizzle at line 51 of file checkers.h.
Referenced by __sequential_multiway_merge(), multiway_merge_loser_tree_sentinel(), n' parallel_multiway_merge().
template<typename _RAIta , typename _Compare > _RAIta __gnu_parallel::__median_of_three_iterators (_RAIter__a, _RAIter__b, _RAIter__c, _Compare__comp)
Compute tha median of three referenced elements, accordin ta __comp.
Parameters:
__a First iterator.
__b Second iterator.
__c Third iterator.
__comp Comparator.
Definizzle at line 398 of file parallel/base.h.
Referenced by __qsb_divide().
template<typename _RAIter1 , typename _RAIter2 , typename _OutputIterator , typename _DifferenceTp , typename _Compare > _OutputIterator __gnu_parallel::__merge_advizzle (_RAIter1 &__begin1, _RAIter1__end1, _RAIter2 &__begin2, _RAIter2__end2, _OutputIterator__target, _DifferenceTp__max_length, _Compare__comp) [inline]
Merge routine bein able ta merge only tha __max_length smallest elements. Da __begin iterators is advanced accordingly, they might not reach __end, up in contrast ta tha usual variant. Right back up in yo muthafuckin ass. Static switch on whether ta use tha conditional-move variant.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence.
__end2 End iterator of second sequence.
__target Target begin iterator.
__max_length Maximum number of elements ta merge.
__comp Comparator.
Returns:
Output end iterator.
Definizzle at line 171 of file merge.h.
References __merge_advance_movc(), n' _GLIBCXX_CALL.
Referenced by __parallel_merge_advance(), n' __sequential_multiway_merge().
template<typename _RAIter1 , typename _RAIter2 , typename _OutputIterator , typename _DifferenceTp , typename _Compare > _OutputIterator __gnu_parallel::__merge_advance_movc (_RAIter1 &__begin1, _RAIter1__end1, _RAIter2 &__begin2, _RAIter2__end2, _OutputIterator__target, _DifferenceTp__max_length, _Compare__comp)
Merge routine bein able ta merge only tha __max_length smallest elements. Da __begin iterators is advanced accordingly, they might not reach __end, up in contrast ta tha usual variant. Right back up in yo muthafuckin ass. Specially designed code should allow tha compila ta generate conditionizzle moves instead of branches.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence.
__end2 End iterator of second sequence.
__target Target begin iterator.
__max_length Maximum number of elements ta merge.
__comp Comparator.
Returns:
Output end iterator.
Definizzle at line 105 of file merge.h.
Referenced by __merge_advance().
template<typename _RAIter1 , typename _RAIter2 , typename _OutputIterator , typename _DifferenceTp , typename _Compare > _OutputIterator __gnu_parallel::__merge_advance_usual (_RAIter1 &__begin1, _RAIter1__end1, _RAIter2 &__begin2, _RAIter2__end2, _OutputIterator__target, _DifferenceTp__max_length, _Compare__comp)
Merge routine bein able ta merge only tha __max_length smallest elements. Da __begin iterators is advanced accordingly, they might not reach __end, up in contrast ta tha usual variant.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence.
__end2 End iterator of second sequence.
__target Target begin iterator.
__max_length Maximum number of elements ta merge.
__comp Comparator.
Returns:
Output end iterator.
Definizzle at line 57 of file merge.h.
template<typename _RAIter1 , typename _RAIter2 , typename _RAIter3 , typename _Compare > _RAIter3 __gnu_parallel::__parallel_merge_advizzle (_RAIter1 &__begin1, _RAIter1__end1, _RAIter2 &__begin2, _RAIter2__end2, _RAIter3__target, typename std::iterator_traits< _RAIter1 >::difference_type__max_length, _Compare__comp) [inline]
Merge routine fallback ta sequential up in case tha iteratorz of tha two input sequences iz of different type.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence.
__end2 End iterator of second sequence.
__target Target begin iterator.
__max_length Maximum number of elements ta merge.
__comp Comparator.
Returns:
Output end iterator.
Definizzle at line 195 of file merge.h.
References __merge_advance().
template<typename _RAIter1 , typename _RAIter3 , typename _Compare > _RAIter3 __gnu_parallel::__parallel_merge_advizzle (_RAIter1 &__begin1, _RAIter1__end1, _RAIter1 &__begin2, _RAIter1__end2, _RAIter3__target, typename std::iterator_traits< _RAIter1 >::difference_type__max_length, _Compare__comp) [inline]
Parallel merge routine bein able ta merge only tha __max_length smallest elements. Da __begin iterators is advanced accordingly, they might not reach __end, up in contrast ta tha usual variant. Da functionalitizzle is projected onto parallel_multiway_merge.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence.
__end2 End iterator of second sequence.
__target Target begin iterator.
__max_length Maximum number of elements ta merge.
__comp Comparator.
Returns:
Output end iterator.
Definizzle at line 223 of file merge.h.
References std::make_pair(), multiway_merge_exact_splitting(), n' parallel_multiway_merge().
template<typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_nth_element (_RAIter__begin, _RAIter__nth, _RAIter__end, _Compare__comp)
Parallel implementation of std::nth_element().
Parameters:
__begin Begin iterator of input sequence.
__nth _Iterator of element dat must be up in posizzle afterwards.
__end End iterator of input sequence.
__comp Comparator.
Definizzle at line 332 of file partition.h.
References __parallel_partition(), _GLIBCXX_CALL, __gnu_parallel::_Settings::get(), std::max(), __gnu_parallel::_Settings::nth_element_minimal_n, n' __gnu_parallel::_Settings::partition_minimal_n.
Referenced by __parallel_partial_sort().
template<typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_partial_sort (_RAIter__begin, _RAIter__middle, _RAIter__end, _Compare__comp)
Parallel implementation of std::partial_sort().
Parameters:
__begin Begin iterator of input sequence.
__middle Sort until dis position.
__end End iterator of input sequence.
__comp Comparator.
Definizzle at line 422 of file partition.h.
References __parallel_nth_element().
template<typename _IIta , typename _OutputIterator , typename _BinaryOperation > _OutputIterator __gnu_parallel::__parallel_partial_sum (_IIter__begin, _IIter__end, _OutputIterator__result, _BinaryOperation__bin_op)
Parallel partial sum front-__end.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__result Begin iterator of output sequence.
__bin_op Associatizzle binary function.
Returns:
End iterator of output sequence.
Definizzle at line 205 of file partial_sum.h.
References __parallel_partial_sum_linear(), _GLIBCXX_CALL, n' __gnu_parallel::_Settings::get().
template<typename _IIta , typename _OutputIterator , typename _BinaryOperation > _OutputIterator __gnu_parallel::__parallel_partial_sum_basecase (_IIter__begin, _IIter__end, _OutputIterator__result, _BinaryOperation__bin_op, typename std::iterator_traits< _IIta >::value_type__value)
Base case prefix sum routine.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__result Begin iterator of output sequence.
__bin_op Associatizzle binary function.
__value Start value. Must be passed since tha neutral element is unknown up in general.
Returns:
End iterator of output sequence.
Definizzle at line 58 of file partial_sum.h.
Referenced by __parallel_partial_sum_linear().
template<typename _IIta , typename _OutputIterator , typename _BinaryOperation > _OutputIterator __gnu_parallel::__parallel_partial_sum_linear (_IIter__begin, _IIter__end, _OutputIterator__result, _BinaryOperation__bin_op, typename std::iterator_traits< _IIta >::difference_type__n)
Parallel partial sum implementation, two-phase approach, no recursion.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__result Begin iterator of output sequence.
__bin_op Associatizzle binary function.
__n Length of sequence.
Returns:
End iterator of output sequence.
Definizzle at line 89 of file partial_sum.h.
References __equally_split(), __parallel_partial_sum_basecase(), std::accumulate(), __gnu_parallel::_Settings::get(), n' __gnu_parallel::_Settings::partial_sum_dilation.
Referenced by __parallel_partial_sum().
template<typename _RAIta , typename _Predicate > std::iterator_traits<_RAIter>::difference_type __gnu_parallel::__parallel_partizzle (_RAIter__begin, _RAIter__end, _Predicate__pred, _ThreadIndex__num_threads)
Parallel implementation of std::partition.
Parameters:
__begin Begin iterator of input sequence ta split.
__end End iterator of input sequence ta split.
__pred Partizzle predicate, possibly includin some kind of pivot.
__num_threads Maximum number of threadz ta use fo' dis task.
Returns:
Number of elements not fulfillin tha predicate.
Definizzle at line 56 of file partition.h.
References __compare_and_swap(), __fetch_and_add(), _GLIBCXX_CALL, _GLIBCXX_VOLATILE, __gnu_parallel::_Settings::get(), __gnu_parallel::_Settings::partition_chunk_share, n' __gnu_parallel::_Settings::partition_chunk_size.
Referenced by __parallel_nth_element(), __parallel_sort_qs_divide(), n' __qsb_divide().
template<typename _RAIta , typename _RandomNumberGenerator > void __gnu_parallel::__parallel_random_shuffle (_RAIter__begin, _RAIter__end, _RandomNumberGenerator__rng = _RandomNumber()) [inline]
Parallel random hood call.
Parameters:
__begin Begin iterator of sequence.
__end End iterator of sequence.
__rng Random number generator ta use.
Definizzle at line 522 of file random_shuffle.h.
References __parallel_random_shuffle_drs().
template<typename _RAIta , typename _RandomNumberGenerator > void __gnu_parallel::__parallel_random_shuffle_drs (_RAIter__begin, _RAIter__end, typename std::iterator_traits< _RAIta >::difference_type__n, _ThreadIndex__num_threads, _RandomNumberGenerator &__rng)
Main parallel random shuffle step.
Parameters:
__begin Begin iterator of sequence.
__end End iterator of sequence.
__n Length of sequence.
__num_threads Number of threadz ta use.
__rng Random number generator ta use.
Definizzle at line 265 of file random_shuffle.h.
References __gnu_parallel::_DRSSorterPU< _RAIter, _RandomNumberGenerator >::__bins_end, __parallel_random_shuffle_drs_pu(), __rd_log2(), __round_up_to_pow2(), __sequential_random_shuffle(), _GLIBCXX_CALL, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_bin_proc, __gnu_parallel::_DRSSorterPU< _RAIter, _RandomNumberGenerator >::_M_bins_begin, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_dist, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_num_bins, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_num_bits, __gnu_parallel::_DRSSorterPU< _RAIter, _RandomNumberGenerator >::_M_num_threads, __gnu_parallel::_DRSSorterPU< _RAIter, _RandomNumberGenerator >::_M_sd, __gnu_parallel::_DRSSorterPU< _RAIter, _RandomNumberGenerator >::_M_seed, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_starts, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_temporaries, __gnu_parallel::_Settings::get(), __gnu_parallel::_Settings::L2_cache_size, std::min(), n' __gnu_parallel::_Settings::TLB_size.
Referenced by __parallel_random_shuffle().
template<typename _RAIta , typename _RandomNumberGenerator > void __gnu_parallel::__parallel_random_shuffle_drs_pu (_DRSSorterPU< _RAIter, _RandomNumberGenerator > *__pus)
Random shuffle code executed by each thread.
Parameters:
__pus Array of thread-local data records.
Definizzle at line 122 of file random_shuffle.h.
References __random_number_pow2(), __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_dist, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_num_bins, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_num_bits, __gnu_parallel::_DRSSorterPU< _RAIter, _RandomNumberGenerator >::_M_num_threads, __gnu_parallel::_DRSSorterPU< _RAIter, _RandomNumberGenerator >::_M_sd, __gnu_parallel::_DRSSorterPU< _RAIter, _RandomNumberGenerator >::_M_seed, __gnu_parallel::_DRandomShufflingGlobalData< _RAIta >::_M_starts, n' std::partial_sum().
Referenced by __parallel_random_shuffle_drs().
template<bool __stable, typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort (_RAIter__begin, _RAIter__end, _Compare__comp, multiway_mergesort_tag__parallelism) [inline]
Choose multiway mergesort, splittin variant at run-time, fo' parallel sorting.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__comp Comparator.
Template Parameters:
__stable Sort stable.
Definizzle at line 75 of file sort.h.
References __gnu_parallel::parallel_tag::__get_num_threads(), _GLIBCXX_CALL, n' __gnu_parallel::_Settings::get().
template<bool __stable, typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort (_RAIter__begin, _RAIter__end, _Compare__comp, multiway_mergesort_exact_tag__parallelism) [inline]
Choose multiway mergesort wit exact splitting, fo' parallel sorting.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__comp Comparator.
Template Parameters:
__stable Sort stable.
Definizzle at line 99 of file sort.h.
References __gnu_parallel::parallel_tag::__get_num_threads(), n' _GLIBCXX_CALL.
template<bool __stable, typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort (_RAIter__begin, _RAIter__end, _Compare__comp, multiway_mergesort_sampling_tag__parallelism) [inline]
Choose multiway mergesort wit splittin by sampling, fo' parallel sorting.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__comp Comparator.
Template Parameters:
__stable Sort stable.
Definizzle at line 120 of file sort.h.
References __gnu_parallel::parallel_tag::__get_num_threads(), n' _GLIBCXX_CALL.
template<bool __stable, typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort (_RAIter__begin, _RAIter__end, _Compare__comp, quicksort_tag__parallelism) [inline]
Choose quicksort fo' parallel sorting.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__comp Comparator.
Template Parameters:
__stable Sort stable.
Definizzle at line 140 of file sort.h.
References __gnu_parallel::parallel_tag::__get_num_threads(), __parallel_sort_qs(), n' _GLIBCXX_CALL.
template<bool __stable, typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort (_RAIter__begin, _RAIter__end, _Compare__comp, balanced_quicksort_tag__parallelism) [inline]
Choose balanced quicksort fo' parallel sorting.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__comp Comparator.
Template Parameters:
__stable Sort stable.
Definizzle at line 161 of file sort.h.
References __gnu_parallel::parallel_tag::__get_num_threads(), __parallel_sort_qsb(), n' _GLIBCXX_CALL.
template<bool __stable, typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort (_RAIter__begin, _RAIter__end, _Compare__comp, default_parallel_tag__parallelism) [inline]
Choose multiway mergesort wit exact splitting, fo' parallel sorting.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__comp Comparator.
Template Parameters:
__stable Sort stable.
Definizzle at line 183 of file sort.h.
References __gnu_parallel::parallel_tag::__get_num_threads(), n' _GLIBCXX_CALL.
template<bool __stable, typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort (_RAIter__begin, _RAIter__end, _Compare__comp, parallel_tag__parallelism) [inline]
Choose a parallel sortin algorithm.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__comp Comparator.
Template Parameters:
__stable Sort stable.
Definizzle at line 203 of file sort.h.
References __gnu_parallel::parallel_tag::__get_num_threads(), __parallel_sort_qs(), __parallel_sort_qsb(), _GLIBCXX_CALL, n' __gnu_parallel::_Settings::get().
template<typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort_qs (_RAIter__begin, _RAIter__end, _Compare__comp, _ThreadIndex__num_threads)
Unbalanced quicksort main call.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator input sequence, ignored.
__comp Comparator.
__num_threads Number of threadz dat is allowed ta work on dis part.
Definizzle at line 154 of file quicksort.h.
References __parallel_sort_qs_conquer(), n' _GLIBCXX_CALL.
Referenced by __parallel_sort().
template<typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort_qs_conquer (_RAIter__begin, _RAIter__end, _Compare__comp, _ThreadIndex__num_threads)
Unbalanced quicksort conquer step.
Parameters:
__begin Begin iterator of subsequence.
__end End iterator of subsequence.
__comp Comparator.
__num_threads Number of threadz dat is allowed ta work on dis part.
Definizzle at line 101 of file quicksort.h.
References __parallel_sort_qs_divide(), n' __gnu_parallel::_Settings::get().
Referenced by __parallel_sort_qs().
template<typename _RAIta , typename _Compare > std::iterator_traits<_RAIter>::difference_type __gnu_parallel::__parallel_sort_qs_divide (_RAIter__begin, _RAIter__end, _Compare__comp, typename std::iterator_traits< _RAIta >::difference_type__pivot_rank, typename std::iterator_traits< _RAIta >::difference_type__num_samples, _ThreadIndex__num_threads)
Unbalanced quicksort divide step.
Parameters:
__begin Begin iterator of subsequence.
__end End iterator of subsequence.
__comp Comparator.
__pivot_rank Desired __rank of tha pivot.
__num_samples Chizzle pivot from dat nuff samples.
__num_threads Number of threadz dat is allowed ta work on dis part.
Definizzle at line 51 of file quicksort.h.
References __parallel_partition(), n' std::min().
Referenced by __parallel_sort_qs_conquer().
template<typename _RAIta , typename _Compare > void __gnu_parallel::__parallel_sort_qsb (_RAIter__begin, _RAIter__end, _Compare__comp, _ThreadIndex__num_threads)
Top-level quicksort routine.
Parameters:
__begin Begin iterator of sequence.
__end End iterator of sequence.
__comp Comparator.
__num_threads Number of threadz dat is allowed ta work on dis part.
Definizzle at line 430 of file balanced_quicksort.h.
References __qsb_conquer(), __rd_log2(), _GLIBCXX_CALL, __gnu_parallel::_QSBThreadLocal< _RAIta >::_M_elements_leftover, n' std::make_pair().
Referenced by __parallel_sort().
template<typename _IIta , class _OutputIterator , class _BinaryPredicate > _OutputIterator __gnu_parallel::__parallel_unique_copy (_IIter__first, _IIter__last, _OutputIterator__result, _BinaryPredicate__binary_pred)
Parallel std::unique_copy(), w/__o explicit equalitizzle predicate.
Parameters:
__first Begin iterator of input sequence.
__last End iterator of input sequence.
__result Begin iterator of result __sequence.
__binary_pred Equalitizzle predicate.
Returns:
End iterator of result __sequence.
Definizzle at line 50 of file unique_copy.h.
References __equally_split(), n' _GLIBCXX_CALL.
Referenced by __parallel_unique_copy().
template<typename _IIta , class _OutputIterator > _OutputIterator __gnu_parallel::__parallel_unique_copy (_IIter__first, _IIter__last, _OutputIterator__result) [inline]
Parallel std::unique_copy(), without explicit equalitizzle predicate.
Parameters:
__first Begin iterator of input sequence.
__last End iterator of input sequence.
__result Begin iterator of result __sequence.
Returns:
End iterator of result __sequence.
Definizzle at line 186 of file unique_copy.h.
References __parallel_unique_copy().
template<typename _RAIta , typename _Compare > void __gnu_parallel::__qsb_conquer (_QSBThreadLocal< _RAIta > **__tls, _RAIter__begin, _RAIter__end, _Compare__comp, _ThreadIndex__iam, _ThreadIndex__num_threads, bool__parent_wait)
Quicksort conquer step.
Parameters:
__tls Array of thread-local storages.
__begin Begin iterator of subsequence.
__end End iterator of subsequence.
__comp Comparator.
__iam Number of tha thread processin dis function.
__num_threads Number of threadz dat is allowed ta work on dis part.
Definizzle at line 171 of file balanced_quicksort.h.
References __qsb_divide(), __qsb_local_sort_with_helping(), __gnu_parallel::_QSBThreadLocal< _RAIta >::_M_elements_leftover, n' __gnu_parallel::_QSBThreadLocal< _RAIta >::_M_initial.
Referenced by __parallel_sort_qsb().
template<typename _RAIta , typename _Compare > std::iterator_traits<_RAIter>::difference_type __gnu_parallel::__qsb_divide (_RAIter__begin, _RAIter__end, _Compare__comp, _ThreadIndex__num_threads)
Balanced quicksort divide step.
Parameters:
__begin Begin iterator of subsequence.
__end End iterator of subsequence.
__comp Comparator.
__num_threads Number of threadz dat is allowed ta work on dis part.
Precondition:
(__end-__begin)>=1
Definizzle at line 100 of file balanced_quicksort.h.
References __median_of_three_iterators(), n' __parallel_partition().
Referenced by __qsb_conquer().
template<typename _RAIta , typename _Compare > void __gnu_parallel::__qsb_local_sort_with_helpin (_QSBThreadLocal< _RAIta > **__tls, _Compare &__comp, _ThreadIndex__iam, bool__wait)
Quicksort step bustin load-balanced local sort.
Parameters:
__tls Array of thread-local storages.
__comp Comparator.
__iam Number of tha thread processin dis function.
Definizzle at line 247 of file balanced_quicksort.h.
References __yield(), _GLIBCXX_ASSERTIONS, __gnu_parallel::_QSBThreadLocal< _RAIta >::_M_elements_leftover, __gnu_parallel::_QSBThreadLocal< _RAIta >::_M_initial, __gnu_parallel::_QSBThreadLocal< _RAIta >::_M_leftover_parts, __gnu_parallel::_QSBThreadLocal< _RAIta >::_M_num_threads, __gnu_parallel::_Settings::get(), std::make_pair(), n' __gnu_parallel::_Settings::sort_qsb_base_case_maximal_n.
Referenced by __qsb_conquer().
template<typename _RandomNumberGenerator > int __gnu_parallel::__random_number_pow2 (int__logp, _RandomNumberGenerator &__rng) [inline]
Generate a random number up in [0,2^__logp).
Parameters:
__logp Logarithm (basis 2) of tha upper range __bound.
__rng Random number generator ta use.
Definizzle at line 115 of file random_shuffle.h.
Referenced by __parallel_random_shuffle_drs_pu(), n' __sequential_random_shuffle().
template<typename _Size > _Size __gnu_parallel::__rd_log2 (_Size__n) [inline]
Calculates tha rounded-down logarithm of __n fo' base 2.
Parameters:
__n Argument.
Returns:
Returns 0 fo' any argument <1.
Definizzle at line 102 of file parallel/base.h.
Referenced by __parallel_random_shuffle_drs(), __parallel_sort_qsb(), __round_up_to_pow2(), __sequential_random_shuffle(), __gnu_parallel::_LoserTreeBase< _Tp, _Compare >::_LoserTreeBase(), multiseq_partition(), n' multiseq_selection().
template<typename _Tp > _Tp __gnu_parallel::__round_up_to_pow2 (_Tp__x)
Round up ta tha next pimped outa juice of 2.
Parameters:
__x _Integer ta round up
Definizzle at line 248 of file random_shuffle.h.
References __rd_log2().
Referenced by __parallel_random_shuffle_drs(), __sequential_random_shuffle(), n' multiseq_selection().
template<typename __RAIter1 , typename __RAIter2 , typename _Pred > __RAIter1 __gnu_parallel::__search_template (__RAIter1__begin1, __RAIter1__end1, __RAIter2__begin2, __RAIter2__end2, _Pred__pred)
Parallel std::search.
Parameters:
__begin1 Begin iterator of first sequence.
__end1 End iterator of first sequence.
__begin2 Begin iterator of second sequence.
__end2 End iterator of second sequence.
__pred Find predicate.
Returns:
Place of findin up in first sequences.
Definizzle at line 81 of file search.h.
References __calc_borders(), __equally_split(), _GLIBCXX_CALL, n' std::min().
template<bool __stable, bool __sentinels, typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 __gnu_parallel::__sequential_multiway_merge (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _RAIter3__target, const typename std::iterator_traits< typename std::iterator_traits< _RAIterIterator >::value_type::first_type >::value_type &__sentinel, _DifferenceTp__length, _Compare__comp)
Sequential multi-way mergin switch. Da _GLIBCXX_PARALLEL_DECISION is based on tha branchin factor n' runtime settings.
Parameters:
__seqs_begin Begin iterator of iterator pair input sequence.
__seqs_end End iterator of iterator pair input sequence.
__target Begin iterator of output sequence.
__comp Comparator.
__length Maximum length ta merge, possibly larger than tha number of elements available.
__sentinel Da sequences have __a __sentinel element.
Returns:
End iterator of output sequence.
Definizzle at line 920 of file multiway_merge.h.
References __is_sorted(), __merge_advance(), _GLIBCXX_CALL, n' _GLIBCXX_PARALLEL_LENGTH.
Referenced by multiway_merge(), n' multiway_merge_sentinels().
template<typename _RAIta , typename _RandomNumberGenerator > void __gnu_parallel::__sequential_random_shuffle (_RAIter__begin, _RAIter__end, _RandomNumberGenerator &__rng)
Sequential cache-efficient random shuffle.
Parameters:
__begin Begin iterator of sequence.
__end End iterator of sequence.
__rng Random number generator ta use.
Definizzle at line 410 of file random_shuffle.h.
References __random_number_pow2(), __rd_log2(), __round_up_to_pow2(), __gnu_parallel::_Settings::get(), __gnu_parallel::_Settings::L2_cache_size, std::min(), std::partial_sum(), n' __gnu_parallel::_Settings::TLB_size.
Referenced by __parallel_random_shuffle_drs().
template<typename _IIta > void __gnu_parallel::__shrink (std::vector< _IIta > &__os_starts, size_t &__count_to_two, size_t &__range_length)
Combines two ranges tha fuck into one n' thus halves tha number of ranges.
Parameters:
__os_starts Start positions hit dat shiznit on (oversampled).
__count_to_two Counts up ta 2.
__range_length Current length of a cold-ass lil chunk.
Definizzle at line 70 of file list_partition.h.
References std::vector< _Tp, _Alloc >::size().
Referenced by __shrink_and_double().
template<typename _IIta > void __gnu_parallel::__shrink_and_double (std::vector< _IIta > &__os_starts, size_t &__count_to_two, size_t &__range_length, const bool__make_twice)
Shrinks n' doublez tha ranges.
Parameters:
__os_starts Start positions hit dat shiznit on (oversampled).
__count_to_two Counts up ta 2.
__range_length Current length of a cold-ass lil chunk.
__make_twice Whether tha __os_starts be allowed ta be grown or not
Definizzle at line 50 of file list_partition.h.
References __shrink(), std::vector< _Tp, _Alloc >::resize(), n' std::vector< _Tp, _Alloc >::size().
Referenced by list_partition().
void __gnu_parallel::__yield () [inline]
Yield control ta another thread, without waitin fo' tha end of tha time slice.
Definizzle at line 121 of file parallel/compatibility.h.
Referenced by __for_each_template_random_access_workstealing(), n' __qsb_local_sort_with_helping().
template<typename _IIta , typename _FunctorType > size_t __gnu_parallel::list_partizzle (const _IIter__begin, const _IIter__end, _IIta *__starts, size_t *__lengths, const int__num_parts, _FunctorType &__f, int__oversamplin = 0)
Splits a sequence given by input iterators tha fuck into partz of almost equal size. Da function needz only one pass over tha sequence.
Parameters:
__begin Begin iterator of input sequence.
__end End iterator of input sequence.
__starts Start iterators fo' tha resultin parts, dimension __num_parts+1. For convenience, __starts [__num_parts] gotz nuff tha end iterator of tha sequence.
__lengths Length of tha resultin parts.
__num_parts Number of parts ta split tha sequence into.
__f Functor ta be applied ta each element by traversin __it
__oversampling Oversamplin factor. If 0, then tha partitions will differ up in at most {{__end} - {__begin}} __elements. Otherwise, tha ratio between tha longest n' tha shortest part is bounded by 1/({__oversampling} {num})
Returns:
Length of tha whole sequence.
Definizzle at line 101 of file list_partition.h.
References __shrink_and_double(), n' std::vector< _Tp, _Alloc >::size().
template<typename _Tp > const _Tp& __gnu_parallel::max (const _Tp &__a, const _Tp &__b) [inline]
Equivalent ta std::max.
Definizzle at line 150 of file parallel/base.h.
template<typename _Tp > const _Tp& __gnu_parallel::min (const _Tp &__a, const _Tp &__b) [inline]
Equivalent ta std::min.
Definizzle at line 144 of file parallel/base.h.
Referenced by __for_each_template_random_access_workstealing().
template<typename _RanSeqs , typename _RankType , typename _RankIterator , typename _Compare > void __gnu_parallel::multiseq_partizzle (_RanSeqs__begin_seqs, _RanSeqs__end_seqs, _RankType__rank, _RankIterator__begin_offsets, _Compare__comp = std::less< typename std::iterator_traits<typename std::iterator_traits<_RanSeqs>::value_type:: first_type>::value_type>())
Splits nuff muthafuckin sorted sequences at a cold-ass lil certain global __rank, resultin up in a splittin point fo' each sequence. Da sequences is passed via a sequence of random-access iterator pairs, none of tha sequences may be empty. If there be nuff muthafuckin equal elements across tha split, tha ones on tha __left side is ghon be chosen from sequences wit smalla number.
Parameters:
__begin_seqs Begin of tha sequence of iterator pairs.
__end_seqs End of tha sequence of iterator pairs.
__rank Da global rank ta partizzle at.
__begin_offsets A random-access __sequence __begin where tha __result is ghon be stored in. Each element of tha sequence be a iterator dat points ta tha straight-up original gangsta element on tha pimped outa part of tha respectizzle __sequence.
__comp Da orderin functor, defaults ta std::less<_Tp>.
Definizzle at line 122 of file multiseq_selection.h.
References __rd_log2(), _GLIBCXX_CALL, std::vector< _Tp, _Alloc >::begin(), std::distance(), std::priority_queue< _Tp, _Sequence, _Compare >::empty(), std::vector< _Tp, _Alloc >::end(), std::make_pair(), std::max(), std::min(), std::priority_queue< _Tp, _Sequence, _Compare >::pop(), std::priority_queue< _Tp, _Sequence, _Compare >::push(), std::vector< _Tp, _Alloc >::push_back(), n' std::priority_queue< _Tp, _Sequence, _Compare >::top().
Referenced by multiway_merge_exact_splitting().
template<typename _Tp , typename _RanSeqs , typename _RankType , typename _Compare > _Tp __gnu_parallel::multiseq_selection (_RanSeqs__begin_seqs, _RanSeqs__end_seqs, _RankType__rank, _RankType &__offset, _Compare__comp = std::less<_Tp>())
Selects tha element at a cold-ass lil certain global __rank from nuff muthafuckin sorted sequences. Da sequences is passed via a sequence of random-access iterator pairs, none of tha sequences may be empty.
Parameters:
__begin_seqs Begin of tha sequence of iterator pairs.
__end_seqs End of tha sequence of iterator pairs.
__rank Da global rank ta partizzle at.
__offset Da rank of tha selected element up in tha global subsequence of elements equal ta tha selected element. If tha selected element is unique, dis number is 0.
__comp Da orderin functor, defaults ta std::less.
Definizzle at line 388 of file multiseq_selection.h.
References __rd_log2(), __round_up_to_pow2(), _GLIBCXX_CALL, std::vector< _Tp, _Alloc >::begin(), std::distance(), std::priority_queue< _Tp, _Sequence, _Compare >::empty(), std::vector< _Tp, _Alloc >::end(), std::make_pair(), std::max(), std::min(), std::priority_queue< _Tp, _Sequence, _Compare >::pop(), std::priority_queue< _Tp, _Sequence, _Compare >::push(), std::vector< _Tp, _Alloc >::push_back(), n' std::priority_queue< _Tp, _Sequence, _Compare >::top().
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut __gnu_parallel::multiway_merge (_RAIterPairIterator__seqs_begin, _RAIterPairIterator__seqs_end, _RAIterOut__target, _DifferenceTp__length, _Compare__comp, __gnu_parallel::sequential_tag)
Multiway Merge Frontend. Merge tha sequences specified by seqs_begin n' __seqs_end tha fuck into __target. __seqs_begin n' __seqs_end must point ta a sequence of pairs. These pairs must contain a iterator ta tha beginnin of a sequence up in they first entry n' a iterator tha _M_end of tha same sequence up in they second entry.
Ties is fucked up arbitrarily. Right back up in yo muthafuckin ass. See stable_multiway_merge fo' a variant dat breaks tizzles by sequence number but is slower.
Da first entriez of tha pairs (i.e. tha begin iterators) is ghon be moved forward.
Da output sequence has ta provide enough space fo' all elements dat is freestyled ta it.
This function will merge tha input sequences:
not stable
parallel, dependin on tha input size n' Settings
usin samplin fo' splitting
not rockin sentinels
Example:
  int sequences[10][10];
  fo' (int __i = 0; __i < 10; ++__i)
    fo' (int __j = 0; __i < 10; ++__j)
      sequences[__i][__j] = __j;
  int __out[33];
  std::vector<std::pair<int*> > seqs;
  fo' (int __i = 0; __i < 10; ++__i)
    { seqs.push(std::make_pair<int*>(sequences[__i],
                                     sequences[__i] + 10)) }
  multiway_merge(seqs.begin(), seqs.end(), __target, std::less<int>(), 33);
See Also:
stable_multiway_merge
Precondition:
All input sequences must be sorted.
Target must provide enough space ta merge up length elements or tha number of elements up in all sequences, whichever is smaller.
Postcondition:
[__target, return __value) gotz nuff merged __elements from tha input sequences.
return __value - __target = min(__length, number of elements up in all sequences).
Template Parameters:
_RAIterPairIterator iterator over sequence of pairz of iterators
_RAIterOut iterator over target sequence
_DifferenceTp difference type fo' tha sequence
_Compare strict weak orderin type ta compare elements up in sequences
Parameters:
__seqs_begin __begin of sequence __sequence
__seqs_end _M_end of sequence __sequence
__target target sequence ta merge to.
__comp strict weak orderin ta use fo' element comparison.
__length Maximum length ta merge, possibly larger than tha number of elements available.
Returns:
_M_end iterator of output sequence
Definizzle at line 1418 of file multiway_merge.h.
References __sequential_multiway_merge(), n' _GLIBCXX_CALL.
template<template< typename RAI, typename C > class iterator, typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 __gnu_parallel::multiway_merge_3_variant (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _RAIter3__target, _DifferenceTp__length, _Compare__comp)
Highly efficient 3-way mergin procedure. Mergin is done wit tha algorithm implementation busted lyrics bout by Peta Sanders. Basically, tha scam is ta minimize tha number of necessary comparison afta mergin a element. Da implementation trick dat make dis fast is dat tha order of tha sequences is stored up in tha instruction pointa (translated tha fuck into labels up in C++).
This works well fo' mergin up ta 4 sequences.
Note dat makin tha mergin stable do not come at a performizzle hit.
Whether tha mergin is done guarded or unguarded is selected by tha used iterator class.
Parameters:
__seqs_begin Begin iterator of iterator pair input sequence.
__seqs_end End iterator of iterator pair input sequence.
__target Begin iterator of output sequence.
__comp Comparator.
__length Maximum length ta merge, less equal than tha total number of elements available.
Returns:
End iterator of output sequence.
Definizzle at line 241 of file multiway_merge.h.
References _GLIBCXX_CALL.
template<template< typename RAI, typename C > class iterator, typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 __gnu_parallel::multiway_merge_4_variant (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _RAIter3__target, _DifferenceTp__length, _Compare__comp)
Highly efficient 4-way mergin procedure. Mergin is done wit tha algorithm implementation busted lyrics bout by Peta Sanders. Basically, tha scam is ta minimize tha number of necessary comparison afta mergin a element. Da implementation trick dat make dis fast is dat tha order of tha sequences is stored up in tha instruction pointa (translated tha fuck into goto labels up in C++).
This works well fo' mergin up ta 4 sequences.
Note dat makin tha mergin stable do not come at a performizzle hit.
Whether tha mergin is done guarded or unguarded is selected by tha used iterator class.
Parameters:
__seqs_begin Begin iterator of iterator pair input sequence.
__seqs_end End iterator of iterator pair input sequence.
__target Begin iterator of output sequence.
__comp Comparator.
__length Maximum length ta merge, less equal than tha total number of elements available.
Returns:
End iterator of output sequence.
Definizzle at line 360 of file multiway_merge.h.
References _GLIBCXX_CALL.
template<bool __stable, typename _RAIterIterator , typename _Compare , typename _DifferenceType > void __gnu_parallel::multiway_merge_exact_splittin (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _DifferenceType__length, _DifferenceType__total_length, _Compare__comp, std::vector< std::pair< _DifferenceType, _DifferenceType > > *__pieces)
Exact splittin fo' parallel multiway-merge routine. None of tha passed sequences may be empty.
Definizzle at line 1120 of file multiway_merge.h.
References __equally_split(), _GLIBCXX_PARALLEL_LENGTH, std::vector< _Tp, _Alloc >::begin(), std::vector< _Tp, _Alloc >::end(), multiseq_partition(), n' std::vector< _Tp, _Alloc >::resize().
Referenced by __parallel_merge_advance().
template<typename _LT , typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 __gnu_parallel::multiway_merge_loser_tree (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _RAIter3__target, _DifferenceTp__length, _Compare__comp)
Multi-way mergin procedure fo' a high branchin factor, guarded case. This mergin variant uses a LoserTree class as selected by _LT.
Stabilitizzle is selected all up in tha used LoserTree class _LT.
At least one non-empty sequence is required.
Parameters:
__seqs_begin Begin iterator of iterator pair input sequence.
__seqs_end End iterator of iterator pair input sequence.
__target Begin iterator of output sequence.
__comp Comparator.
__length Maximum length ta merge, less equal than tha total number of elements available.
Returns:
End iterator of output sequence.
Definizzle at line 491 of file multiway_merge.h.
References _GLIBCXX_CALL, n' _GLIBCXX_PARALLEL_LENGTH.
template<typename UnguardedLoserTree , typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 __gnu_parallel::multiway_merge_loser_tree_sentinel (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _RAIter3__target, const typename std::iterator_traits< typename std::iterator_traits< _RAIterIterator >::value_type::first_type >::value_type &__sentinel, _DifferenceTp__length, _Compare__comp)
Multi-way mergin procedure fo' a high branchin factor, requirin sentinels ta exist.
Template Parameters:
UnguardedLoserTree _Loser Tree variant ta use fo' tha unguarded merging.
Parameters:
__seqs_begin Begin iterator of iterator pair input sequence.
__seqs_end End iterator of iterator pair input sequence.
__target Begin iterator of output sequence.
__comp Comparator.
__length Maximum length ta merge, less equal than tha total number of elements available.
Returns:
End iterator of output sequence.
Definizzle at line 662 of file multiway_merge.h.
References __is_sorted(), n' _GLIBCXX_CALL.
template<typename _LT , typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Compare > _RAIter3 __gnu_parallel::multiway_merge_loser_tree_unguarded (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _RAIter3__target, const typename std::iterator_traits< typename std::iterator_traits< _RAIterIterator >::value_type::first_type >::value_type &__sentinel, _DifferenceTp__length, _Compare__comp)
Multi-way mergin procedure fo' a high branchin factor, unguarded case. Mergin is done rockin tha LoserTree class _LT.
Stabilitizzle is selected by tha used LoserTrees.
Precondition:
No input will run outta elements durin tha merge.
Parameters:
__seqs_begin Begin iterator of iterator pair input sequence.
__seqs_end End iterator of iterator pair input sequence.
__target Begin iterator of output sequence.
__comp Comparator.
__length Maximum length ta merge, less equal than tha total number of elements available.
Returns:
End iterator of output sequence.
Definizzle at line 574 of file multiway_merge.h.
References _GLIBCXX_CALL.
template<bool __stable, typename _RAIterIterator , typename _Compare , typename _DifferenceType > void __gnu_parallel::multiway_merge_sampling_splittin (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _DifferenceType__length, _DifferenceType__total_length, _Compare__comp, std::vector< std::pair< _DifferenceType, _DifferenceType > > *__pieces)
Samplin based splittin fo' parallel multiway-merge routine.
Definizzle at line 1035 of file multiway_merge.h.
References _GLIBCXX_PARALLEL_LENGTH, __gnu_parallel::_Settings::get(), n' __gnu_parallel::_Settings::merge_oversampling.
template<typename _RAIterPairIterator , typename _RAIterOut , typename _DifferenceTp , typename _Compare > _RAIterOut __gnu_parallel::multiway_merge_sentinels (_RAIterPairIterator__seqs_begin, _RAIterPairIterator__seqs_end, _RAIterOut__target, _DifferenceTp__length, _Compare__comp, __gnu_parallel::sequential_tag)
Multiway Merge Frontend. Merge tha sequences specified by seqs_begin n' __seqs_end tha fuck into __target. __seqs_begin n' __seqs_end must point ta a sequence of pairs. These pairs must contain a iterator ta tha beginnin of a sequence up in they first entry n' a iterator tha _M_end of tha same sequence up in they second entry.
Ties is fucked up arbitrarily. Right back up in yo muthafuckin ass. See stable_multiway_merge fo' a variant dat breaks tizzles by sequence number but is slower.
Da first entriez of tha pairs (i.e. tha begin iterators) is ghon be moved forward accordingly.
Da output sequence has ta provide enough space fo' all elements dat is freestyled ta it.
This function will merge tha input sequences:
not stable
parallel, dependin on tha input size n' Settings
usin samplin fo' splitting
usin sentinels
Yo ass gotta take care dat tha element tha _M_end iterator points ta is readable n' gotz nuff a value dat is pimped outa than any other non-sentinel value up in all sequences.
Example:
  int sequences[10][11];
  fo' (int __i = 0; __i < 10; ++__i)
    fo' (int __j = 0; __i < 11; ++__j)
      sequences[__i][__j] = __j; // __last one is sentinel!
  int __out[33];
  std::vector<std::pair<int*> > seqs;
  fo' (int __i = 0; __i < 10; ++__i)
    { seqs.push(std::make_pair<int*>(sequences[__i],
                                     sequences[__i] + 10)) }
  multiway_merge(seqs.begin(), seqs.end(), __target, std::less<int>(), 33);
Precondition:
All input sequences must be sorted.
Target must provide enough space ta merge up length elements or tha number of elements up in all sequences, whichever is smaller.
For each __i, __seqs_begin[__i].second must be tha end marker of tha sequence yo, but also reference tha one mo' __sentinel element.
Postcondition:
[__target, return __value) gotz nuff merged __elements from tha input sequences.
return __value - __target = min(__length, number of elements up in all sequences).
See Also:
stable_multiway_merge_sentinels
Template Parameters:
_RAIterPairIterator iterator over sequence of pairz of iterators
_RAIterOut iterator over target sequence
_DifferenceTp difference type fo' tha sequence
_Compare strict weak orderin type ta compare elements up in sequences
Parameters:
__seqs_begin __begin of sequence __sequence
__seqs_end _M_end of sequence __sequence
__target target sequence ta merge to.
__comp strict weak orderin ta use fo' element comparison.
__length Maximum length ta merge, possibly larger than tha number of elements available.
Returns:
_M_end iterator of output sequence
Definizzle at line 1782 of file multiway_merge.h.
References __sequential_multiway_merge(), n' _GLIBCXX_CALL.
template<bool __stable, bool __sentinels, typename _RAIterIterator , typename _RAIter3 , typename _DifferenceTp , typename _Splitta , typename _Compare > _RAIter3 __gnu_parallel::parallel_multiway_merge (_RAIterIterator__seqs_begin, _RAIterIterator__seqs_end, _RAIter3__target, _Splitter__splitter, _DifferenceTp__length, _Compare__comp, _ThreadIndex__num_threads)
Parallel multi-way merge routine. Da _GLIBCXX_PARALLEL_DECISION is based on tha branchin factor n' runtime settings.
Must not be called if tha number of sequences is 1.
Template Parameters:
_Splitter functor ta split input (either __exact or samplin based)
__stable Stable mergin incurs a performizzle penalty.
__sentinel Ignored.
Parameters:
__seqs_begin Begin iterator of iterator pair input sequence.
__seqs_end End iterator of iterator pair input sequence.
__target Begin iterator of output sequence.
__comp Comparator.
__length Maximum length ta merge, possibly larger than tha number of elements available.
Returns:
End iterator of output sequence.
Definizzle at line 1225 of file multiway_merge.h.
References __is_sorted(), _GLIBCXX_CALL, _GLIBCXX_PARALLEL_LENGTH, __gnu_parallel::_Settings::get(), std::make_pair(), n' __gnu_parallel::_Settings::merge_oversampling.
Referenced by __parallel_merge_advance().
template<bool __stable, bool __exact, typename _RAIta , typename _Compare > void __gnu_parallel::parallel_sort_mwms (_RAIter__begin, _RAIter__end, _Compare__comp, _ThreadIndex__num_threads)
PMWMS main call.
Parameters:
__begin Begin iterator of sequence.
__end End iterator of sequence.
__comp Comparator.
__num_threads Number of threadz ta use.
Definizzle at line 395 of file multiway_mergesort.h.
References _GLIBCXX_CALL, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_num_threads, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_offsets, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_pieces, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_samples, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_source, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_starts, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_temporary, __gnu_parallel::_Settings::get(), n' __gnu_parallel::_Settings::sort_mwms_oversampling.
template<bool __stable, bool __exact, typename _RAIta , typename _Compare > void __gnu_parallel::parallel_sort_mwms_pu (_PMWMSSortingData< _RAIta > *__sd, _Compare &__comp)
PMWMS code executed by each thread.
Parameters:
__sd Pointa ta algorithm data.
__comp Comparator.
Definizzle at line 308 of file multiway_mergesort.h.
References __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_num_threads, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_pieces, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_source, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_starts, __gnu_parallel::_PMWMSSortingData< _RAIta >::_M_temporary, __gnu_parallel::_Settings::get(), std::make_pair(), __gnu_parallel::_Settings::sort_mwms_oversampling, n' std::uninitialized_copy().
Variable Documentation
const int __gnu_parallel::_CASable_bits [static]
Number of bitz of _CASable.
Definizzle at line 130 of file types.h.
Referenced by __decode2(), n' __encode2().
const _CASable __gnu_parallel::_CASable_mask [static]
_CASable wit tha right half of bits set ta 1.
Definizzle at line 133 of file types.h.
Referenced by __decode2().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.