__gnu_debug::_Safe_local_iterator_base
NAME
__gnu_debug::_Safe_local_iterator_base -
SYNOPSIS
Inherits __gnu_debug::_Safe_iterator_base.
Inherited by __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >.
Public Member Functions
void _M_attach (_Safe_sequence_base *__seq, bool __constant)
void _M_attach_single (_Safe_sequence_base *__seq, bool __constant) throw ()
bool _M_attached_to (const _Safe_sequence_base *__seq) const
bool _M_can_compare (const _Safe_iterator_base &__x) const throw ()
void _M_detach ()
void _M_detach_single () throw ()
void _M_invalidate ()
void _M_reset () throw ()
bool _M_singular () const throw ()
void _M_unlink () throw ()
Public Attributes
_Safe_iterator_base * _M_next
_Safe_iterator_base * _M_prior
_Safe_sequence_base * _M_sequence
unsigned int _M_version
Protected Member Functions
_Safe_local_iterator_base ()
_Safe_local_iterator_base (const _Safe_sequence_base *__seq, bool __constant)
_Safe_local_iterator_base (const _Safe_local_iterator_base &__x, bool __constant)
_Safe_local_iterator_base (const _Safe_local_iterator_base &)
_Safe_unordered_container_base * _M_get_container () const noexcept
__gnu_cxx::__mutex & _M_get_mutex () throw ()
_Safe_local_iterator_base & operator= (const _Safe_local_iterator_base &)
Detailed Description
Basic functionalitizzle fo' a safe iterator.
Da _Safe_local_iterator_base base class implements tha functionalitizzle of a safe local iterator dat aint specific ta a particular iterator type. Well shiiiit, it gotz nuff a pointa back ta tha container it references along wit iterator version shiznit n' pointas ta form a thugged-out doubly-linked list of local iterators referenced by tha container.
This class must not big-ass up any operations dat can throw a exception, or tha exception guaranteez of derived iterators is ghon be broken.
Definizzle at line 50 of file safe_unordered_base.h.
Constructor & Destructor Documentation
__gnu_debug::_Safe_local_iterator_base::_Safe_local_iterator_base () [inline], [protected]
Initializes tha iterator n' make it singular.
Definizzle at line 54 of file safe_unordered_base.h.
__gnu_debug::_Safe_local_iterator_base::_Safe_local_iterator_base (const _Safe_sequence_base *__seq, bool__constant) [inline], [protected]
Initialize tha iterator ta reference tha container pointed ta by __seq. __constant is legit when we is initializin a cold-ass lil constant local iterator, n' false if it aint nuthin but a mutable local iterator. Note dat __seq may be NULL, up in which case tha iterator is ghon be singular. Otherwise, tha iterator will reference __seq n' be nonsingular.
Definizzle at line 64 of file safe_unordered_base.h.
References _M_attach().
__gnu_debug::_Safe_local_iterator_base::_Safe_local_iterator_base (const _Safe_local_iterator_base &__x, bool__constant) [inline], [protected]
Initializes tha iterator ta reference tha same container dat __x do. __constant is legit if dis be a cold-ass lil constant iterator, n' false if it is mutable.
Definizzle at line 70 of file safe_unordered_base.h.
References _M_attach(), n' __gnu_debug::_Safe_iterator_base::_M_sequence.
Member Function Documentation
void __gnu_debug::_Safe_local_iterator_base::_M_attach (_Safe_sequence_base *__seq, bool__constant)
Attaches dis iterator ta tha given container, detachin it from whatever container dat shiznit was attached ta originally. If tha freshly smoked up container is tha NULL pointer, tha iterator is left unattached.
Referenced by _Safe_local_iterator_base().
void __gnu_debug::_Safe_local_iterator_base::_M_attach_single (_Safe_sequence_base *__seq, bool__constant)
Likewise yo, but not thread-safe.
bool __gnu_debug::_Safe_iterator_base::_M_attached_to (const _Safe_sequence_base *__seq) const [inline], [inherited]
Determines if we is attached ta tha given sequence.
Definizzle at line 129 of file safe_base.h.
References __gnu_debug::_Safe_iterator_base::_M_sequence.
bool __gnu_debug::_Safe_iterator_base::_M_can_compare (const _Safe_iterator_base &__x) const [inherited]
Can we compare dis iterator ta tha given iterator __x, biatch? Returns legit if both iterators is nonsingular n' reference tha same sequence.
void __gnu_debug::_Safe_local_iterator_base::_M_detach ()
Detach tha iterator fo' whatever container it be attached to, if any.
void __gnu_debug::_Safe_local_iterator_base::_M_detach_single ()
Likewise yo, but not thread-safe.
__gnu_cxx::__mutex& __gnu_debug::_Safe_iterator_base::_M_get_mutex () [protected], [inherited]
For use up in _Safe_iterator.
void __gnu_debug::_Safe_iterator_base::_M_invalidate () [inline], [inherited]
Invalidate tha iterator, makin it singular.
Definizzle at line 142 of file safe_base.h.
References __gnu_debug::_Safe_iterator_base::_M_version.
void __gnu_debug::_Safe_iterator_base::_M_reset () [inherited]
Reset all member variablez
bool __gnu_debug::_Safe_iterator_base::_M_singular () const [inherited]
Is dis iterator singular, biatch?
Referenced by __gnu_debug::__check_singular(), __gnu_debug::__check_singular_aux(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_M_incrementable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), n' __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_Safe_local_iterator().
void __gnu_debug::_Safe_iterator_base::_M_unlink () [inline], [inherited]
Unlink itself
Definizzle at line 151 of file safe_base.h.
References __gnu_debug::_Safe_iterator_base::_M_next, n' __gnu_debug::_Safe_iterator_base::_M_prior.
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_next [inherited]
Pointa ta tha next iterator up in tha sequencez list of iterators. Only valid when _M_sequence != NULL.
Definizzle at line 72 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if(), n' __gnu_debug::_Safe_iterator_base::_M_unlink().
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_prior [inherited]
Pointa ta tha previous iterator up in tha sequencez list of iterators. Only valid when _M_sequence != NULL.
Definizzle at line 68 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if(), n' __gnu_debug::_Safe_iterator_base::_M_unlink().
_Safe_sequence_base* __gnu_debug::_Safe_iterator_base::_M_sequence [inherited]
Da sequence dis iterator references; may be NULL ta indicate a singular iterator.
Definizzle at line 55 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator_base::_M_attached_to(), __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if(), __gnu_debug::_Safe_iterator_base::_Safe_iterator_base(), n' _Safe_local_iterator_base().
unsigned int __gnu_debug::_Safe_iterator_base::_M_version [inherited]
Da version number of dis iterator. Da sentinel value 0 is used ta indicate a invalidated iterator (i.e., one dat is singular cuz of a operation on tha container). This version number must equal tha version number up in tha sequence referenced by _M_sequence fo' tha iterator ta be non-singular.
Definizzle at line 64 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator_base::_M_invalidate().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.