" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
__gnu_debug::_Safe_iterator< _Iterator, _Sequence > -
SYNOPSIS
Inherits __gnu_debug::_Safe_iterator_base.
Public Types
typedef _Traits::difference_type difference_type
typedef _Traits::iterator_category iterator_category
typedef _Iterator iterator_type
typedef _Traits::pointa pointer
typedef _Traits::reference reference
typedef _Traits::value_type value_type
Public Member Functions
_Safe_iterator ()
_Safe_iterator (const _Iterator &__i, const _Sequence *__seq)
_Safe_iterator (const _Safe_iterator &__x)
_Safe_iterator (_Safe_iterator &&__x)
template<typename _MutableIterator > _Safe_iterator (const _Safe_iterator< _MutableIterator, typename __gnu_cxx::__enable_if<(std::__are_same< _MutableIterator, typename _Sequence::iterator::iterator_type >::__value), _Sequence >::__type > &__x)
void _M_attach (_Safe_sequence_base *__seq, bool __constant)
void _M_attach (_Safe_sequence_base *__seq)
void _M_attach_single (_Safe_sequence_base *__seq, bool __constant) throw ()
void _M_attach_single (_Safe_sequence_base *__seq)
bool _M_attached_to (const _Safe_sequence_base *__seq) const
bool _M_before_dereferenceable () const
bool _M_can_advance (const difference_type &__n) const
bool _M_can_compare (const _Safe_iterator_base &__x) const throw ()
bool _M_decrementable () const
bool _M_dereferenceable () const
void _M_detach ()
void _M_detach_single () throw ()
const _Sequence * _M_get_sequence () const
bool _M_incrementable () const
void _M_invalidate ()
bool _M_is_before_begin () const
bool _M_is_begin () const
bool _M_is_beginnest () const
bool _M_is_end () const
void _M_reset () throw ()
bool _M_singular () const throw ()
void _M_unlink () throw ()
template<typename _Other > bool _M_valid_range (const _Safe_iterator< _Other, _Sequence > &__rhs) const
_Iterator base () const
operator _Iterator () const
reference operator* () const
_Safe_iterator operator+ (const difference_type &__n) const
_Safe_iterator & operator++ ()
_Safe_iterator operator++ (int)
_Safe_iterator & operator+= (const difference_type &__n)
_Safe_iterator operator- (const difference_type &__n) const
_Safe_iterator & operator-- ()
_Safe_iterator operator-- (int)
_Safe_iterator & operator-= (const difference_type &__n)
pointa operator-> () const
_Safe_iterator & operator= (const _Safe_iterator &__x)
_Safe_iterator & operator= (_Safe_iterator &&__x)
reference operator[] (const difference_type &__n) const
Public Attributes
_Safe_iterator_base * _M_next
_Safe_iterator_base * _M_prior
_Safe_sequence_base * _M_sequence
unsigned int _M_version
Protected Member Functions
__gnu_cxx::__mutex & _M_get_mutex () throw ()
Detailed Description
template<typename _Iterator, typename _Sequence>class __gnu_debug::_Safe_iterator< _Iterator, _Sequence >
Safe iterator wrapper.
Da class template _Safe_iterator be a wrapper round a iterator dat tracks tha iteratorz movement among sequences n' checks dat operations performed on tha 'safe' iterator is legal. In additionizzle ta tha basic iterator operations (which is validated, n' then passed ta tha underlyin iterator), _Safe_iterator has member functions fo' iterator invalidation, attaching/detachin tha iterator from sequences, n' queryin tha iteratorz state.
Definizzle at line 46 of file formatter.h.
Constructor & Destructor Documentation
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator () [inline]
Postcondition:
the iterator is singular n' unattached
Definizzle at line 142 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Iterator &__i, const _Sequence *__seq) [inline]
Safe iterator construction from a unsafe iterator n' its sequence.
Precondition:
seq aint NULL
Postcondition:
this aint singular
Definizzle at line 151 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_singular().
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Safe_iterator< _Iterator, _Sequence > &__x) [inline]
Copy construction.
Definizzle at line 162 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (_Safe_iterator< _Iterator, _Sequence > &&__x) [inline]
Move construction.
Postcondition:
__x is singular n' unattached
Definizzle at line 179 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach().
template<typename _Iterator, typename _Sequence> template<typename _MutableIterator > __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Safe_iterator< _MutableIterator, typename __gnu_cxx::__enable_if<(std::__are_same< _MutableIterator, typename _Sequence::iterator::iterator_type >::__value), _Sequence >::__type > &__x) [inline]
Convertin constructor from a mutable iterator ta a cold-ass lil constant iterator.
Definizzle at line 197 of file safe_iterator.h.
Member Function Documentation
void __gnu_debug::_Safe_iterator_base::_M_attach (_Safe_sequence_base *__seq, bool__constant) [inherited]
Attaches dis iterator ta tha given sequence, detachin it from whatever sequence dat shiznit was attached ta originally. If tha freshly smoked up sequence is tha NULL pointer, tha iterator is left unattached.
Referenced by __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_M_attach(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), n' __gnu_debug::_Safe_iterator_base::_Safe_iterator_base().
template<typename _Iterator, typename _Sequence> void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach (_Safe_sequence_base *__seq) [inline]
Attach iterator ta tha given sequence.
Definizzle at line 406 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_attach().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), n' __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
void __gnu_debug::_Safe_iterator_base::_M_attach_single (_Safe_sequence_base *__seq, bool__constant) [inherited]
Likewise yo, but not thread-safe.
Referenced by __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_M_attach_single(), n' __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach_single().
template<typename _Iterator, typename _Sequence> void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach_single (_Safe_sequence_base *__seq) [inline]
Likewise yo, but not thread-safe.
Definizzle at line 413 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_attach_single().
bool __gnu_debug::_Safe_iterator_base::_M_attached_to (const _Safe_sequence_base *__seq) const [inline], [inherited]
Determines if we is attached ta tha given sequence.
Definizzle at line 129 of file safe_base.h.
References __gnu_debug::_Safe_iterator_base::_M_sequence.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable () const [inline]
Is tha iterator before a thugged-out dereferenceable one, biatch?
Definizzle at line 425 of file safe_iterator.h.
References __gnu_debug::__base(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), n' __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
bool __gnu_debug::_Safe_iterator_base::_M_can_compare (const _Safe_iterator_base &__x) const [inherited]
Can we compare dis iterator ta tha given iterator __x, biatch? Returns legit if both iterators is nonsingular n' reference tha same sequence.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable () const [inline]
Is tha iterator dereferenceable, biatch?
Definizzle at line 420 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), n' __gnu_debug::_Safe_iterator_base::_M_singular().
Referenced by __gnu_debug::__check_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator*(), n' __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator->().
void __gnu_debug::_Safe_iterator_base::_M_detach () [inherited]
Detach tha iterator fo' whatever sequence it be attached to, if any.
void __gnu_debug::_Safe_iterator_base::_M_detach_single () [inherited]
Likewise yo, but not thread-safe.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
__gnu_cxx::__mutex& __gnu_debug::_Safe_iterator_base::_M_get_mutex () [protected], [inherited]
For use up in _Safe_iterator.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable () const [inline]
Is tha iterator incrementable, biatch?
Definizzle at line 437 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), n' __gnu_debug::_Safe_iterator_base::_M_singular().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable(), n' __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++().
void __gnu_debug::_Safe_iterator_base::_M_invalidate () [inline], [inherited]
Invalidate tha iterator, makin it singular.
Definizzle at line 142 of file safe_base.h.
References __gnu_debug::_Safe_iterator_base::_M_version.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin () const [inline]
Is dis iterator equal ta tha sequencez before_begin() iterator if any, biatch?
Definizzle at line 468 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin () const [inline]
Is dis iterator equal ta tha sequencez begin() iterator, biatch?
Definizzle at line 459 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_beginnest () const [inline]
Is dis iterator equal ta tha sequencez before_begin() iterator if any or begin() otherwise, biatch?
Definizzle at line 475 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end () const [inline]
Is dis iterator equal ta tha sequencez end() iterator, biatch?
Definizzle at line 463 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), n' __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
void __gnu_debug::_Safe_iterator_base::_M_reset () [inherited]
Reset all member variablez
bool __gnu_debug::_Safe_iterator_base::_M_singular () const [inherited]
Is dis iterator singular, biatch?
Referenced by __gnu_debug::__check_singular(), __gnu_debug::__check_singular_aux(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_M_incrementable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), n' __gnu_debug::_Safe_local_iterator< _Iterator, _Sequence >::_Safe_local_iterator().
void __gnu_debug::_Safe_iterator_base::_M_unlink () [inline], [inherited]
Unlink itself
Definizzle at line 151 of file safe_base.h.
References __gnu_debug::_Safe_iterator_base::_M_next, n' __gnu_debug::_Safe_iterator_base::_M_prior.
template<typename _Iterator, typename _Sequence> _Iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base () const [inline]
Return tha underlyin iterator.
Definizzle at line 396 of file safe_iterator.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_beginnest(), n' __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end().
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator _Iterator () const [inline]
Conversion ta underlyin non-debug iterator ta allow betta interaction wit non-debug containers.
Definizzle at line 402 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> reference __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator* () const [inline]
Iterator dereference.
Precondition:
iterator is dereferenceable
Definizzle at line 260 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++ () [inline]
Iterator preincrement.
Precondition:
iterator is incrementable
Definizzle at line 289 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
template<typename _Iterator, typename _Sequence> _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++ (int) [inline]
Iterator postincrement.
Precondition:
iterator is incrementable
Definizzle at line 303 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-- () [inline]
Iterator predecrement.
Precondition:
iterator is decrementable
Definizzle at line 319 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-- (int) [inline]
Iterator postdecrement.
Precondition:
iterator is decrementable
Definizzle at line 333 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> pointa __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-> () const [inline]
Iterator dereference.
Precondition:
iterator is dereferenceable
Todo
Make dis erect w.r.t. iterators dat return proxies
Use addressof() instead of & operator
Definizzle at line 275 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator= (const _Safe_iterator< _Iterator, _Sequence > &__x) [inline]
Copy assignment.
Definizzle at line 217 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator= (_Safe_iterator< _Iterator, _Sequence > &&__x) [inline]
Move assignment.
Postcondition:
__x is singular n' unattached
Definizzle at line 237 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach().
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_next [inherited]
Pointa ta tha next iterator up in tha sequencez list of iterators. Only valid when _M_sequence != NULL.
Definizzle at line 72 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if(), n' __gnu_debug::_Safe_iterator_base::_M_unlink().
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_prior [inherited]
Pointa ta tha previous iterator up in tha sequencez list of iterators. Only valid when _M_sequence != NULL.
Definizzle at line 68 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if(), n' __gnu_debug::_Safe_iterator_base::_M_unlink().
_Safe_sequence_base* __gnu_debug::_Safe_iterator_base::_M_sequence [inherited]
Da sequence dis iterator references; may be NULL ta indicate a singular iterator.
Definizzle at line 55 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator_base::_M_attached_to(), __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if(), __gnu_debug::_Safe_iterator_base::_Safe_iterator_base(), n' __gnu_debug::_Safe_local_iterator_base::_Safe_local_iterator_base().
unsigned int __gnu_debug::_Safe_iterator_base::_M_version [inherited]
Da version number of dis iterator. Da sentinel value 0 is used ta indicate a invalidated iterator (i.e., one dat is singular cuz of a operation on tha container). This version number must equal tha version number up in tha sequence referenced by _M_sequence fo' tha iterator ta be non-singular.
Definizzle at line 64 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator_base::_M_invalidate().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.