" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_debug::_BeforeBeginHelper< _Sequence > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _It::iterator_type \fB_BaseIt\fP"
.br
.ti -1c
.RI "typedef _Sequence::const_iterator \fB_It\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fB_S_Is\fP (_BaseIt, const _Sequence *)"
.br
.ti -1c
.RI "static bool \fB_S_Is_Beginnest\fP (_BaseIt __it, const _Sequence *__seq)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Sequence>struct __gnu_debug::_BeforeBeginHelper< _Sequence >"
Helper struct ta deal wit sequence offerin a funky-ass before_begin iterator\&. 
.PP
Definizzle at line 45 of file safe_iterator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen fo' libstdc++ from tha source code\&.
