" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
__gnu_debug::_Safe_sequence< _Sequence > -
SYNOPSIS
Inherits __gnu_debug::_Safe_sequence_base.
Public Member Functions
void _M_attach (_Safe_iterator_base *__it, bool __constant)
void _M_attach_single (_Safe_iterator_base *__it, bool __constant) throw ()
void _M_detach (_Safe_iterator_base *__it)
void _M_detach_single (_Safe_iterator_base *__it) throw ()
void _M_invalidate_all () const
template<typename _Predicate > void _M_invalidate_if (_Predicate __pred)
template<typename _Predicate > void _M_transfer_from_if (_Safe_sequence &__from, _Predicate __pred)
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
void _M_revalidate_singular ()
void _M_swap (_Safe_sequence_base &__x)
Detailed Description
template<typename _Sequence>class __gnu_debug::_Safe_sequence< _Sequence >
Base class fo' constructin a safe sequence type dat tracks iterators dat reference it.
Da class template _Safe_sequence simplifies tha construction of safe sequences dat track tha iterators dat reference tha sequence, so dat tha iterators is notified of chizzlez up in tha sequence dat may affect they operation, e.g., if tha container invalidates its iterators or is destructed. This class template may only be used by derivin from it n' passin tha name of tha derived class as its template parameta via tha curiously recurrin template pattern. Da derived class must have iterator n' const_iterator types dat is instantiationz of class template _Safe_iterator fo' dis sequence. Iterators will then be tracked automatically.
Definizzle at line 52 of file formatter.h.
Member Function Documentation
void __gnu_debug::_Safe_sequence_base::_M_attach (_Safe_iterator_base *__it, bool__constant) [inherited]
Attach a iterator ta dis sequence.
void __gnu_debug::_Safe_sequence_base::_M_attach_single (_Safe_iterator_base *__it, bool__constant) [inherited]
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach (_Safe_iterator_base *__it) [inherited]
Detach a iterator from dis sequence
void __gnu_debug::_Safe_sequence_base::_M_detach_all () [protected], [inherited]
Detach all iterators, leavin dem singular.
Referenced by __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base().
void __gnu_debug::_Safe_sequence_base::_M_detach_single (_Safe_iterator_base *__it) [inherited]
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () [protected], [inherited]
Detach all singular iterators.
Postcondition:
for all iterators i attached ta dis sequence, i->_M_version == _M_version.
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () [protected], [inherited]
For use up in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const [inline], [inherited]
Invalidates all iterators.
Definizzle at line 233 of file safe_base.h.
References __gnu_debug::_Safe_sequence_base::_M_version.
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if (_Predicate__pred)
Invalidates all iterators x dat reference dis sequence, is not singular, n' fo' which __pred(x) returns true. __pred is ghon be invoked wit tha aiiight iterators nested up in tha safe ones.
Definizzle at line 38 of file safe_sequence.tcc.
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () [protected], [inherited]
Revalidates all attached singular iterators. This method may be used ta validate iterators dat was invalidated before (but fo' some reason, like fuckin a exception, need ta become valid again).
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base &__x) [protected], [inherited]
Swap dis sequence wit tha given sequence. This operation also swaps ballershizzle of tha iterators, so dat when tha operation is complete all iterators dat originally referenced one container now reference tha other container.
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if (_Safe_sequence< _Sequence > &__from, _Predicate__pred)
Transfers all iterators x dat reference from sequence, is not singular, n' fo' which __pred(x) returns true. __pred is ghon be invoked wit tha aiiight iterators nested up in tha safe ones.
Definizzle at line 69 of file safe_sequence.tcc.
References __gnu_debug::_Safe_sequence_base::_M_const_iterators, __gnu_debug::_Safe_iterator_base::_M_detach_single(), __gnu_debug::_Safe_sequence_base::_M_get_mutex(), __gnu_debug::_Safe_sequence_base::_M_iterators, __gnu_debug::_Safe_iterator_base::_M_next, __gnu_debug::_Safe_iterator_base::_M_prior, __gnu_debug::_Safe_iterator_base::_M_sequence, n' __gnu_debug::_Safe_sequence_base::_M_version.
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators [inherited]
Da list of constant iterators dat reference dis container.
Definizzle at line 184 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators [inherited]
Da list of mutable iterators dat reference dis container.
Definizzle at line 181 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
unsigned int __gnu_debug::_Safe_sequence_base::_M_version [mutable], [inherited]
Da container version number. This number may never be 0.
Definizzle at line 187 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), n' __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.