__gnu_parallel::_Settings
NAME
__gnu_parallel::_Settings -
SYNOPSIS
Static Public Member Functions
static const _Settings & get () throw ()
static void set (_Settings &) throw ()
Public Attributes
_SequenceIndex accumulate_minimal_n
unsigned int adjacent_difference_minimal_n
_AlgorithmStrategy algorithm_strategy
unsigned int cache_line_size
_SequenceIndex count_minimal_n
_SequenceIndex fill_minimal_n
_FindAlgorithm find_algorithm
double find_increasing_factor
_SequenceIndex find_initial_block_size
_SequenceIndex find_maximum_block_size
float find_scale_factor
_SequenceIndex find_sequential_search_size
_SequenceIndex for_each_minimal_n
_SequenceIndex generate_minimal_n
unsigned long long L1_cache_size
unsigned long long L2_cache_size
_SequenceIndex max_element_minimal_n
_SequenceIndex merge_minimal_n
unsigned int merge_oversampling
_SplittingAlgorithm merge_splitting
_SequenceIndex min_element_minimal_n
_MultiwayMergeAlgorithm multiway_merge_algorithm
int multiway_merge_minimal_k
_SequenceIndex multiway_merge_minimal_n
unsigned int multiway_merge_oversampling
_SplittingAlgorithm multiway_merge_splitting
_SequenceIndex nth_element_minimal_n
_SequenceIndex partial_sort_minimal_n
_PartialSumAlgorithm partial_sum_algorithm
float partial_sum_dilation
unsigned int partial_sum_minimal_n
double partition_chunk_share
_SequenceIndex partition_chunk_size
_SequenceIndex partition_minimal_n
_SequenceIndex qsb_steals
unsigned int random_shuffle_minimal_n
_SequenceIndex replace_minimal_n
_SequenceIndex search_minimal_n
_SequenceIndex set_difference_minimal_n
_SequenceIndex set_intersection_minimal_n
_SequenceIndex set_symmetric_difference_minimal_n
_SequenceIndex set_union_minimal_n
_SortAlgorithm sort_algorithm
_SequenceIndex sort_minimal_n
unsigned int sort_mwms_oversampling
unsigned int sort_qs_num_samples_preset
_SequenceIndex sort_qsb_base_case_maximal_n
_SplittingAlgorithm sort_splitting
unsigned int TLB_size
_SequenceIndex transform_minimal_n
_SequenceIndex unique_copy_minimal_n
_SequenceIndex workstealing_chunk_size
Detailed Description
class _Settings Run-time settings fo' tha parallel mode includin all tunable parameters.
Definizzle at line 123 of file settings.h.
Member Function Documentation
static const _Settings& __gnu_parallel::_Settings::get () [static]
Git tha global settings.
Referenced by __gnu_parallel::__find_template(), __gnu_parallel::__for_each_template_random_access_workstealing(), __gnu_parallel::__parallel_nth_element(), __gnu_parallel::__parallel_partial_sum(), __gnu_parallel::__parallel_partial_sum_linear(), __gnu_parallel::__parallel_partition(), __gnu_parallel::__parallel_random_shuffle_drs(), __gnu_parallel::__parallel_sort(), __gnu_parallel::__parallel_sort_qs_conquer(), __gnu_parallel::__qsb_local_sort_with_helping(), __gnu_parallel::__sequential_random_shuffle(), __gnu_parallel::multiway_merge_sampling_splitting(), __gnu_parallel::parallel_multiway_merge(), __gnu_parallel::parallel_sort_mwms(), n' __gnu_parallel::parallel_sort_mwms_pu().
static void __gnu_parallel::_Settings::set (_Settings &) [static]
Set tha global settings.
Member Data Documentation
_SequenceIndex __gnu_parallel::_Settings::accumulate_minimal_n
Minimal input size fo' accumulate.
Definizzle at line 139 of file settings.h.
unsigned int __gnu_parallel::_Settings::adjacent_difference_minimal_n
Minimal input size fo' adjacent_difference.
Definizzle at line 142 of file settings.h.
unsigned int __gnu_parallel::_Settings::cache_line_size
Overestimation of cache line size. Used ta avoid false sharing, i.e. elementz of different threadz is at least dis amount apart.
Definizzle at line 265 of file settings.h.
Referenced by __gnu_parallel::__for_each_template_random_access_workstealing().
_SequenceIndex __gnu_parallel::_Settings::count_minimal_n
Minimal input size fo' count n' count_if.
Definizzle at line 145 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::fill_minimal_n
Minimal input size fo' fill.
Definizzle at line 148 of file settings.h.
double __gnu_parallel::_Settings::find_increasing_factor
Block size increase factor fo' find.
Definizzle at line 151 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::find_initial_block_size
Initial block size fo' find.
Definizzle at line 154 of file settings.h.
Referenced by __gnu_parallel::__find_template().
_SequenceIndex __gnu_parallel::_Settings::find_maximum_block_size
Maximal block size fo' find.
Definizzle at line 157 of file settings.h.
float __gnu_parallel::_Settings::find_scale_factor
Block size scale-down factor wit respect ta current position.
Definizzle at line 276 of file settings.h.
Referenced by __gnu_parallel::__find_template().
_SequenceIndex __gnu_parallel::_Settings::find_sequential_search_size
Start wit lookin fo' dis nuff elements sequentially, fo' find.
Definizzle at line 160 of file settings.h.
Referenced by __gnu_parallel::__find_template().
_SequenceIndex __gnu_parallel::_Settings::for_each_minimal_n
Minimal input size fo' for_each.
Definizzle at line 163 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::generate_minimal_n
Minimal input size fo' generate.
Definizzle at line 166 of file settings.h.
unsigned long long __gnu_parallel::_Settings::L1_cache_size
size of tha L1 cache up in bytes (underestimation).
Definizzle at line 254 of file settings.h.
unsigned long long __gnu_parallel::_Settings::L2_cache_size
size of tha L2 cache up in bytes (underestimation).
Definizzle at line 257 of file settings.h.
Referenced by __gnu_parallel::__parallel_random_shuffle_drs(), n' __gnu_parallel::__sequential_random_shuffle().
_SequenceIndex __gnu_parallel::_Settings::max_element_minimal_n
Minimal input size fo' max_element.
Definizzle at line 169 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::merge_minimal_n
Minimal input size fo' merge.
Definizzle at line 172 of file settings.h.
unsigned int __gnu_parallel::_Settings::merge_oversampling
Oversamplin factor fo' merge.
Definizzle at line 175 of file settings.h.
Referenced by __gnu_parallel::multiway_merge_sampling_splitting(), n' __gnu_parallel::parallel_multiway_merge().
_SequenceIndex __gnu_parallel::_Settings::min_element_minimal_n
Minimal input size fo' min_element.
Definizzle at line 178 of file settings.h.
int __gnu_parallel::_Settings::multiway_merge_minimal_k
Oversamplin factor fo' multiway_merge.
Definizzle at line 184 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::multiway_merge_minimal_n
Minimal input size fo' multiway_merge.
Definizzle at line 181 of file settings.h.
unsigned int __gnu_parallel::_Settings::multiway_merge_oversampling
Oversamplin factor fo' multiway_merge.
Definizzle at line 187 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::nth_element_minimal_n
Minimal input size fo' nth_element.
Definizzle at line 190 of file settings.h.
Referenced by __gnu_parallel::__parallel_nth_element().
_SequenceIndex __gnu_parallel::_Settings::partial_sort_minimal_n
Minimal input size fo' partial_sort.
Definizzle at line 203 of file settings.h.
float __gnu_parallel::_Settings::partial_sum_dilation
Ratio fo' partial_sum fo' realz. Assume 'sum n' write result' ta be dis factor slower than just 'sum'.
Definizzle at line 207 of file settings.h.
Referenced by __gnu_parallel::__parallel_partial_sum_linear().
unsigned int __gnu_parallel::_Settings::partial_sum_minimal_n
Minimal input size fo' partial_sum.
Definizzle at line 210 of file settings.h.
double __gnu_parallel::_Settings::partition_chunk_share
Chunk size fo' partition, relatizzle ta input size. If > 0.0, dis value overrides partition_chunk_size.
Definizzle at line 197 of file settings.h.
Referenced by __gnu_parallel::__parallel_partition().
_SequenceIndex __gnu_parallel::_Settings::partition_chunk_size
Chunk size fo' partition.
Definizzle at line 193 of file settings.h.
Referenced by __gnu_parallel::__parallel_partition().
_SequenceIndex __gnu_parallel::_Settings::partition_minimal_n
Minimal input size fo' partition.
Definizzle at line 200 of file settings.h.
Referenced by __gnu_parallel::__parallel_nth_element().
_SequenceIndex __gnu_parallel::_Settings::qsb_steals
Da number of jacked ranges up in load-balanced quicksort.
Definizzle at line 270 of file settings.h.
unsigned int __gnu_parallel::_Settings::random_shuffle_minimal_n
Minimal input size fo' random_shuffle.
Definizzle at line 213 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::replace_minimal_n
Minimal input size fo' replace n' replace_if.
Definizzle at line 216 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::search_minimal_n
Minimal input size fo' search n' search_n.
Definizzle at line 273 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::set_difference_minimal_n
Minimal input size fo' set_difference.
Definizzle at line 219 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::set_intersection_minimal_n
Minimal input size fo' set_intersection.
Definizzle at line 222 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::set_symmetric_difference_minimal_n
Minimal input size fo' set_symmetric_difference.
Definizzle at line 225 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::set_union_minimal_n
Minimal input size fo' set_union.
Definizzle at line 228 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::sort_minimal_n
Minimal input size fo' parallel sorting.
Definizzle at line 231 of file settings.h.
unsigned int __gnu_parallel::_Settings::sort_mwms_oversampling
Oversamplin factor fo' parallel std::sort (MWMS).
Definizzle at line 234 of file settings.h.
Referenced by __gnu_parallel::parallel_sort_mwms(), n' __gnu_parallel::parallel_sort_mwms_pu().
unsigned int __gnu_parallel::_Settings::sort_qs_num_samples_preset
Such nuff samplez ta take ta find a phat pivot (quicksort).
Definizzle at line 237 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::sort_qsb_base_case_maximal_n
Maximal subsequence __length ta switch ta unbalanced __base case fo' realz. Applies ta std::sort wit dynamically load-balanced quicksort.
Definizzle at line 241 of file settings.h.
Referenced by __gnu_parallel::__qsb_local_sort_with_helping().
unsigned int __gnu_parallel::_Settings::TLB_size
size of tha Translation Lookaside Buffer (underestimation).
Definizzle at line 260 of file settings.h.
Referenced by __gnu_parallel::__parallel_random_shuffle_drs(), n' __gnu_parallel::__sequential_random_shuffle().
_SequenceIndex __gnu_parallel::_Settings::transform_minimal_n
Minimal input size fo' parallel std::transform.
Definizzle at line 244 of file settings.h.
_SequenceIndex __gnu_parallel::_Settings::unique_copy_minimal_n
Minimal input size fo' unique_copy.
Definizzle at line 247 of file settings.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.