" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
__gnu_cxx::stdio_sync_filebuf< _CharT, _Traits > -
SYNOPSIS
Inherits std::basic_streambuf< _CharT, _Traits >.
Public Types
typedef _CharT char_type
typedef traits_type::int_type int_type
typedef traits_type::off_type off_type
typedef traits_type::pos_type pos_type
typedef _Traits traits_type
typedef basic_streambuf
< char_type, traits_type > __streambuf_type"
Public Member Functions
stdio_sync_filebuf (std::__c_file *__f)
std::__c_file *const file ()
locale getloc () const
streamsize in_avail ()
locale pubimbue (const locale &__loc)
int_type sbumpc ()
int_type sgetc ()
streamsize sgetn (char_type *__s, streamsize __n)
int_type snextc ()
int_type sputbackc (char_type __c)
int_type sputc (char_type __c)
streamsize sputn (const char_type *__s, streamsize __n)
int_type sungetc ()
basic_streambuf * pubsetbuf (char_type *__s, streamsize __n)
pos_type pubseekoff (off_type __off, ios_base::seekdir __way, ios_base::openmode __mode=ios_base::in|ios_base::out)
pos_type pubseekpos (pos_type __sp, ios_base::openmode __mode=ios_base::in|ios_base::out)
int pubsync ()
Protected Member Functions
void __safe_gbump (streamsize __n)
void __safe_pbump (streamsize __n)
void gbump (int __n)
virtual void imbue (const locale &__loc)
virtual int_type overflow (int_type __c=traits_type::eof())
virtual int_type pbackfail (int_type __c=traits_type::eof())
void pbump (int __n)
virtual std::streampos seekoff (std::streamoff __off, std::ios_base::seekdir __dir, std::ios_base::openmode=std::ios_base::in|std::ios_base::out)
virtual pos_type seekoff (off_type, ios_base::seekdir, ios_base::openmode=ios_base::in|ios_base::out)
virtual std::streampos seekpos (std::streampos __pos, std::ios_base::openmode __mode=std::ios_base::in|std::ios_base::out)
virtual pos_type seekpos (pos_type, ios_base::openmode=ios_base::in|ios_base::out)
virtual basic_streambuf
< char_type, _Traits > * setbuf (char_type *, streamsize)"
void setg (char_type *__gbeg, char_type *__gnext, char_type *__gend)
void setp (char_type *__pbeg, char_type *__pend)
virtual streamsize showmanyc ()
virtual int sync ()
int_type syncgetc ()
template<> stdio_sync_filebuf< char >
::int_type syncgetc ()"
template<> stdio_sync_filebuf< wchar_t >
::int_type syncgetc ()"
int_type syncputc (int_type __c)
template<> stdio_sync_filebuf< char >
::int_type syncputc (int_type __c)"
template<> stdio_sync_filebuf< wchar_t >
::int_type syncputc (int_type __c)"
int_type syncungetc (int_type __c)
template<> stdio_sync_filebuf< char >
::int_type syncungetc (int_type __c)"
template<> stdio_sync_filebuf< wchar_t >
::int_type syncungetc (int_type __c)"
virtual int_type uflow ()
virtual int_type underflow ()
virtual std::streamsize xsgetn (char_type *__s, std::streamsize __n)
template<> std::streamsize xsgetn (char *__s, std::streamsize __n)
template<> std::streamsize xsgetn (wchar_t *__s, std::streamsize __n)
virtual streamsize xsgetn (char_type *__s, streamsize __n)
virtual std::streamsize xsputn (const char_type *__s, std::streamsize __n)
template<> std::streamsize xsputn (const char *__s, std::streamsize __n)
template<> std::streamsize xsputn (const wchar_t *__s, std::streamsize __n)
virtual streamsize xsputn (const char_type *__s, streamsize __n)
char_type * eback () const
char_type * gptr () const
char_type * egptr () const
char_type * pbase () const
char_type * pptr () const
char_type * epptr () const
Protected Attributes
locale _M_buf_locale
char_type * _M_in_beg
char_type * _M_in_cur
char_type * _M_in_end
char_type * _M_out_beg
char_type * _M_out_cur
char_type * _M_out_end
Detailed Description
template<typename _CharT, typename _Traits = std::char_traits<_CharT>>class __gnu_cxx::stdio_sync_filebuf< _CharT, _Traits >
Provides a layer of compatibilitizzle fo' C.
This GNU extension serves up extensions fo' hustlin wit standard C FILE*'s. Well shiiiit, it must be instantiated by tha user wit tha type of characta used up in tha file stream, e.g., stdio_filebuf<char>.
Definizzle at line 56 of file stdio_sync_filebuf.h.
Member Typedef Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> typedef basic_streambuf<char_type, traits_type> std::basic_streambuf< _CharT, _Traits >::__streambuf_type [inherited]
This be a non-standard type.
Definizzle at line 138 of file streambuf.
Member Function Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::eback () const [inline], [protected], [inherited]
Access ta tha git area. These functions is only available ta other protected functions, includin derived classes.
eback() returns tha beginnin pointa fo' tha input sequence
gptr() returns tha next pointa fo' tha input sequence
egptr() returns tha end pointa fo' tha input sequence
Definizzle at line 482 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_destroy_pback(), std::basic_streambuf< char, char_traits< char > >::sputbackc(), n' std::basic_streambuf< char, char_traits< char > >::sungetc().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::egptr () const [inline], [protected], [inherited]
Access ta tha git area. These functions is only available ta other protected functions, includin derived classes.
eback() returns tha beginnin pointa fo' tha input sequence
gptr() returns tha next pointa fo' tha input sequence
egptr() returns tha end pointa fo' tha input sequence
Definizzle at line 488 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), std::basic_streambuf< char, char_traits< char > >::in_avail(), std::basic_streambuf< char, char_traits< char > >::sbumpc(), std::basic_streambuf< char, char_traits< char > >::sgetc(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::showmanyc(), n' std::basic_stringbuf< _CharT, _Traits, _Alloc >::str().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::epptr () const [inline], [protected], [inherited]
Access ta tha put area. These functions is only available ta other protected functions, includin derived classes.
pbase() returns tha beginnin pointa fo' tha output sequence
pptr() returns tha next pointa fo' tha output sequence
epptr() returns tha end pointa fo' tha output sequence
Definizzle at line 535 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sputc().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> std::__c_file* const __gnu_cxx::stdio_sync_filebuf< _CharT, _Traits >::file () [inline]
Returns:
Da underlyin FILE*.
This function can be used ta access tha underlyin C file pointer. Note dat there is no way fo' tha library ta track what tha fuck you do wit tha file, so be careful.
Definizzle at line 88 of file stdio_sync_filebuf.h.
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_streambuf< _CharT, _Traits >::gbump (int__n) [inline], [protected], [inherited]
Movin tha read position.
Parameters:
__n Da delta by which ta move.
This just advances tha read posizzle without returnin any data.
Definizzle at line 498 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sbumpc(), std::basic_streambuf< char, char_traits< char > >::sputbackc(), std::basic_streambuf< char, char_traits< char > >::sungetc(), n' std::basic_streambuf< char, char_traits< char > >::uflow().
template<typename _CharT, typename _Traits = char_traits<_CharT>> locale std::basic_streambuf< _CharT, _Traits >::getloc () const [inline], [inherited]
Locale access.
Returns:
Da current locale up in effect.
If pubimbue(loc) has been called, then da most thugged-out recent loc is returned. Otherwise tha global locale up in effect all up in tha time of construction is returned.
Definizzle at line 226 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pubimbue().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::gptr () const [inline], [protected], [inherited]
Access ta tha git area. These functions is only available ta other protected functions, includin derived classes.
eback() returns tha beginnin pointa fo' tha input sequence
gptr() returns tha next pointa fo' tha input sequence
egptr() returns tha end pointa fo' tha input sequence
Definizzle at line 485 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), std::basic_filebuf< char_type, traits_type >::_M_destroy_pback(), std::basic_streambuf< char, char_traits< char > >::in_avail(), std::basic_streambuf< char, char_traits< char > >::sbumpc(), std::basic_streambuf< char, char_traits< char > >::sgetc(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::showmanyc(), std::basic_streambuf< char, char_traits< char > >::sputbackc(), std::basic_streambuf< char, char_traits< char > >::sungetc(), n' std::basic_streambuf< char, char_traits< char > >::uflow().
template<typename _CharT, typename _Traits = char_traits<_CharT>> virtual void std::basic_streambuf< _CharT, _Traits >::imbue (const locale &__loc) [inline], [protected], [virtual], [inherited]
Changes translations.
Parameters:
__loc A freshly smoked up locale.
Translations done durin I/O which depend on tha current locale is chizzled by dis call. Da standard adds, Between invocationz of dis function a cold-ass lil class derived from streambuf can safely cache thangs up in dis biatch of calls ta locale functions n' ta thugz of facets so obtained.
Note:
Base class version do nothing.
Reimplemented up in std::basic_filebuf< _CharT, _Traits >, std::basic_filebuf< _CharT, encoding_char_traits< _CharT > >, n' std::basic_filebuf< char_type, traits_type >.
Definizzle at line 576 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pubimbue().
template<typename _CharT, typename _Traits = char_traits<_CharT>> streamsize std::basic_streambuf< _CharT, _Traits >::in_avail () [inline], [inherited]
Lookin ahead tha fuck into tha stream.
Returns:
Da number of charactas available.
If a read posizzle be available, returns tha number of charactas available fo' readin before tha buffer must be refilled. Otherwise returns tha derived showmanyc().
Definizzle at line 284 of file streambuf.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> virtual int_type __gnu_cxx::stdio_sync_filebuf< _CharT, _Traits >::overflow (int_type__c = traits_type::eof()) [inline], [protected], [virtual]
Consumes data from tha buffer; writes ta tha controlled sequence.
Parameters:
__c An additionizzle characta ta consume.
Returns:
eof() ta indicate failure, suttin' else (usually __c, or not_eof())
Informally, dis function is called when tha output buffer is full (or do not exist, as bufferin need not straight-up be done). If a funky-ass buffer exists, it is consumed, wit some effect on tha controlled sequence. (Typically, tha buffer is freestyled up ta tha sequence verbatim.) In either case, tha characta c be also freestyled out, if __c aint eof().
For a gangbangin' formal definizzle of dis function, peep a phat text like fuckin Langer & Kreft, or [27.5.2.4.5]/3-7.
A functionin output streambuf can be pimped by overridin only dis function (no buffer area is ghon be used).
Note:
Base class version do nothing, returns eof().
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 141 of file stdio_sync_filebuf.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> virtual int_type __gnu_cxx::stdio_sync_filebuf< _CharT, _Traits >::pbackfail (int_type__c = traits_type::eof()) [inline], [protected], [virtual]
Tries ta back up tha input sequence.
Parameters:
__c Da characta ta be banged back tha fuck into tha sequence.
Returns:
eof() on failure, some other value on success
Postcondition:
Da constraintz of gptr(), eback(), n' pptr() is tha same as fo' underflow().
Note:
Base class version do nothing, returns eof().
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 116 of file stdio_sync_filebuf.h.
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::pbase () const [inline], [protected], [inherited]
Access ta tha put area. These functions is only available ta other protected functions, includin derived classes.
pbase() returns tha beginnin pointa fo' tha output sequence
pptr() returns tha next pointa fo' tha output sequence
epptr() returns tha end pointa fo' tha output sequence
Definizzle at line 529 of file streambuf.
Referenced by std::basic_stringbuf< _CharT, _Traits, _Alloc >::str().
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_streambuf< _CharT, _Traits >::pbump (int__n) [inline], [protected], [inherited]
Movin tha write position.
Parameters:
__n Da delta by which ta move.
This just advances tha write posizzle without returnin any data.
Definizzle at line 545 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sputc().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::pptr () const [inline], [protected], [inherited]
Access ta tha put area. These functions is only available ta other protected functions, includin derived classes.
pbase() returns tha beginnin pointa fo' tha output sequence
pptr() returns tha next pointa fo' tha output sequence
epptr() returns tha end pointa fo' tha output sequence
Definizzle at line 532 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sputc(), n' std::basic_stringbuf< _CharT, _Traits, _Alloc >::str().
template<typename _CharT, typename _Traits = char_traits<_CharT>> locale std::basic_streambuf< _CharT, _Traits >::pubimbue (const locale &__loc) [inline], [inherited]
Entry point fo' imbue().
Parameters:
__loc Da freshly smoked up locale.
Returns:
Da previous locale.
Calls tha derived imbue(__loc).
Definizzle at line 209 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> pos_type std::basic_streambuf< _CharT, _Traits >::pubseekoff (off_type__off, ios_base::seekdir__way, ios_base::openmode__mode = ios_base::in | ios_base::out) [inline], [inherited]
Altas tha stream position.
Parameters:
__off Offset.
__way Value fo' ios_base::seekdir.
__mode Value fo' ios_base::openmode.
Calls virtual seekoff function.
Definizzle at line 251 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> pos_type std::basic_streambuf< _CharT, _Traits >::pubseekpos (pos_type__sp, ios_base::openmode__mode = ios_base::in | ios_base::out) [inline], [inherited]
Altas tha stream position.
Parameters:
__sp Posizzle
__mode Value fo' ios_base::openmode.
Calls virtual seekpos function.
Definizzle at line 263 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> basic_streambuf* std::basic_streambuf< _CharT, _Traits >::pubsetbuf (char_type *__s, streamsize__n) [inline], [inherited]
Entry points fo' derived buffer functions. Da hood versionz of pubfoo dispatch ta tha protected derived foo member functions, passin tha arguments (if any) n' returnin tha result unchanged.
Definizzle at line 239 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> int std::basic_streambuf< _CharT, _Traits >::pubsync () [inline], [inherited]
Calls virtual sync function.
Definizzle at line 271 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::sync().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sbumpc () [inline], [inherited]
Gettin tha next character.
Returns:
Da next character, or eof.
If tha input read posizzle be available, returns dat characta n' increments tha read pointer, otherwise calls n' returns uflow().
Definizzle at line 316 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), std::istreambuf_iterator< _CharT, _Traits >::operator++(), n' std::basic_streambuf< char, char_traits< char > >::snextc().
template<typename _CharT, typename _Traits = char_traits<_CharT>> virtual pos_type std::basic_streambuf< _CharT, _Traits >::seekoff (off_type, ios_base::seekdir, ios_base::openmode = ios_base::in | ios_base::out) [inline], [protected], [virtual], [inherited]
Altas tha stream positions. Each derived class serves up its own appropriate behavior.
Note:
Base class version do nothing, returns a pos_type dat represents a invalid stream position.
Reimplemented up in std::basic_filebuf< _CharT, _Traits >, std::basic_filebuf< _CharT, encoding_char_traits< _CharT > >, std::basic_filebuf< char_type, traits_type >, n' std::basic_stringbuf< _CharT, _Traits, _Alloc >.
Definizzle at line 602 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pubseekoff().
template<typename _CharT, typename _Traits = char_traits<_CharT>> virtual pos_type std::basic_streambuf< _CharT, _Traits >::seekpos (pos_type, ios_base::openmode = ios_base::in | ios_base::out) [inline], [protected], [virtual], [inherited]
Altas tha stream positions. Each derived class serves up its own appropriate behavior.
Note:
Base class version do nothing, returns a pos_type dat represents a invalid stream position.
Reimplemented up in std::basic_filebuf< _CharT, _Traits >, std::basic_filebuf< _CharT, encoding_char_traits< _CharT > >, std::basic_filebuf< char_type, traits_type >, n' std::basic_stringbuf< _CharT, _Traits, _Alloc >.
Definizzle at line 614 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pubseekpos().
template<typename _CharT, typename _Traits = char_traits<_CharT>> virtual basic_streambuf<char_type,_Traits>* std::basic_streambuf< _CharT, _Traits >::setbuf (char_type *, streamsize) [inline], [protected], [virtual], [inherited]
Manipulates tha buffer. Each derived class serves up its own appropriate behavior. Right back up in yo muthafuckin ass. See tha next-to-last paragraph of http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch25s02.html fo' mo' on dis function.
Note:
Base class version do nothing, returns this.
Reimplemented up in std::basic_filebuf< _CharT, _Traits >, std::basic_filebuf< _CharT, encoding_char_traits< _CharT > >, std::basic_filebuf< char_type, traits_type >, n' std::basic_stringbuf< _CharT, _Traits, _Alloc >.
Definizzle at line 591 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pubsetbuf().
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_streambuf< _CharT, _Traits >::setg (char_type *__gbeg, char_type *__gnext, char_type *__gend) [inline], [protected], [inherited]
Settin tha three read area pointers.
Parameters:
__gbeg A pointer.
__gnext A pointer.
__gend A pointer.
Postcondition:
__gbeg == eback(), __gnext == gptr(), n' __gend == egptr()
Definizzle at line 509 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), std::basic_filebuf< char_type, traits_type >::_M_destroy_pback(), n' std::basic_filebuf< char_type, traits_type >::_M_set_buffer().
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_streambuf< _CharT, _Traits >::setp (char_type *__pbeg, char_type *__pend) [inline], [protected], [inherited]
Settin tha three write area pointers.
Parameters:
__pbeg A pointer.
__pend A pointer.
Postcondition:
__pbeg == pbase(), __pbeg == pptr(), n' __pend == epptr()
Definizzle at line 555 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_set_buffer().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sgetc () [inline], [inherited]
Gettin tha next character.
Returns:
Da next character, or eof.
If tha input read posizzle be available, returns dat character, otherwise calls n' returns underflow(). Do not move tha read posizzle afta fetchin tha character.
Definizzle at line 338 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), std::basic_istream< _CharT, _Traits >::sentry::sentry(), n' std::basic_streambuf< char, char_traits< char > >::snextc().
template<typename _CharT, typename _Traits = char_traits<_CharT>> streamsize std::basic_streambuf< _CharT, _Traits >::sgetn (char_type *__s, streamsize__n) [inline], [inherited]
Entry point fo' xsgetn.
Parameters:
__s A buffer area.
__n A count.
Returns xsgetn(__s,__n). Da effect is ta fill __s[0] all up in __s[__n-1] wit charactas from tha input sequence, if possible.
Definizzle at line 357 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> virtual streamsize std::basic_streambuf< _CharT, _Traits >::showmanyc () [inline], [protected], [virtual], [inherited]
Investigatin tha data available.
Returns:
An estimate of tha number of charactas available up in tha input sequence, or -1.
If it returns a positizzle value, then successive calls ta underflow() aint gonna return traits::eof() until at least dat number of charactas done been supplied. If showmanyc() returns -1, then calls ta underflow() or uflow() will fail. [27.5.2.4.3]/1
Note:
Base class version do nothing, returns zero.
Da standard addz dat the intention aint only dat tha calls [to underflow or uflow] aint gonna return eof() but dat they will return immediately.
Da standard addz dat the morphemez of showmanyc is es-how-many-see, not show-manic.
Reimplemented up in std::basic_filebuf< _CharT, _Traits >, std::basic_filebuf< _CharT, encoding_char_traits< _CharT > >, std::basic_filebuf< char_type, traits_type >, n' std::basic_stringbuf< _CharT, _Traits, _Alloc >.
Definizzle at line 649 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::in_avail().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::snextc () [inline], [inherited]
Gettin tha next character.
Returns:
Da next character, or eof.
Calls sbumpc(), n' if dat function returns traits::eof(), so do dis function. Otherwise, sgetc().
Definizzle at line 298 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), n' std::basic_istream< _CharT, _Traits >::sentry::sentry().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sputbackc (char_type__c) [inline], [inherited]
Pushin charactas back tha fuck into tha input stream.
Parameters:
__c Da characta ta push back.
Returns:
Da previous character, if possible.
Similar ta sungetc() yo, but __c is pushed onto tha stream instead of the previous character. If successful, tha next characta fetched from tha input stream is ghon be __c.
Definizzle at line 372 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::putback().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sputc (char_type__c) [inline], [inherited]
Entry point fo' all single-characta output functions.
Parameters:
__c A characta ta output.
Returns:
__c, if possible.
One of two hood output functions.
If a write posizzle be available fo' tha output sequence (i.e., tha buffer aint full), stores __c up in dat position, increments tha position, n' returns traits::to_int_type(__c). If a write posizzle aint available, returns overflow(__c).
Definizzle at line 424 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::get(), n' std::ostreambuf_iterator< _CharT, _Traits >::operator=().
template<typename _CharT, typename _Traits = char_traits<_CharT>> streamsize std::basic_streambuf< _CharT, _Traits >::sputn (const char_type *__s, streamsize__n) [inline], [inherited]
Entry point fo' all single-characta output functions.
Parameters:
__s A buffer read area.
__n A count.
One of two hood output functions.
Returns xsputn(__s,__n). Da effect is ta write __s[0] all up in __s[__n-1] ta tha output sequence, if possible.
Definizzle at line 450 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sungetc () [inline], [inherited]
Movin backwardz up in tha input stream.
Returns:
Da previous character, if possible.
If a putback posizzle be available, dis function decrements tha input pointa n' returns dat character. Otherwise, calls n' returns pbackfail(). Da effect is ta unget tha last characta gotten.
Definizzle at line 397 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::unget().
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> virtual int __gnu_cxx::stdio_sync_filebuf< _CharT, _Traits >::sync (void) [inline], [protected], [virtual]
Synchronizes tha buffer arrays wit tha controlled sequences.
Returns:
-1 on failure.
Each derived class serves up its own appropriate behavior, includin tha definizzle of failure.
Note:
Base class version do nothing, returns zero.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 160 of file stdio_sync_filebuf.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> virtual int_type __gnu_cxx::stdio_sync_filebuf< _CharT, _Traits >::uflow () [inline], [protected], [virtual]
Fetches mo' data from tha controlled sequence.
Returns:
Da first characta from tha pendin sequence.
Informally, dis function do tha same thang as underflow(), n' up in fact is required ta booty-call dat function. Well shiiiit, it also returns tha freshly smoked up character, like underflow() do. But fuck dat shiznit yo, tha word on tha street is dat dis function also moves tha read posizzle forward by one.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 108 of file stdio_sync_filebuf.h.
template<typename _CharT , typename _Traits = std::char_traits<_CharT>> virtual int_type __gnu_cxx::stdio_sync_filebuf< _CharT, _Traits >::underflow () [inline], [protected], [virtual]
Fetches mo' data from tha controlled sequence.
Returns:
Da first characta from tha pendin sequence.
Informally, dis function is called when tha input buffer is exhausted (or do not exist, as bufferin need not straight-up be done). If a funky-ass buffer exists, it is refilled. In either case, tha next available characta is returned, or traits::eof() ta indicate a null pendin sequence.
For a gangbangin' formal definizzle of tha pendin sequence, peep a phat text like fuckin Langer & Kreft, or [27.5.2.4.3]/7-14.
A functionin input streambuf can be pimped by overridin only dis function (no buffer area is ghon be used). For a example, peep http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch25.html
Note:
Base class version do nothing, returns eof().
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 101 of file stdio_sync_filebuf.h.
template<typename _CharT , typename _Traits > streamsize std::basic_streambuf< _CharT, _Traits >::xsgetn (char_type *__s, streamsize__n) [protected], [virtual], [inherited]
Multiple characta extraction.
Parameters:
__s A buffer area.
__n Maximum number of charactas ta assign.
Returns:
Da number of charactas assigned.
Fills __s[0] all up in __s[__n-1] wit charactas from tha input sequence, as if by sbumpc(). Right back up in yo muthafuckin ass. Stops when either __n charactas done been copied, or when traits::eof() would be copied.
It be expected dat derived classes provide a mo' efficient implementation by overridin dis definition.
Reimplemented up in std::basic_filebuf< _CharT, _Traits >, std::basic_filebuf< _CharT, encoding_char_traits< _CharT > >, n' std::basic_filebuf< char_type, traits_type >.
Definizzle at line 46 of file streambuf.tcc.
References std::min().
Referenced by std::basic_streambuf< char, char_traits< char > >::sgetn().
template<typename _CharT , typename _Traits > streamsize std::basic_streambuf< _CharT, _Traits >::xsputn (const char_type *__s, streamsize__n) [protected], [virtual], [inherited]
Multiple characta insertion.
Parameters:
__s A buffer area.
__n Maximum number of charactas ta write.
Returns:
Da number of charactas written.
Writes __s[0] all up in __s[__n-1] ta tha output sequence, as if by sputc(). Right back up in yo muthafuckin ass. Stops when either n charactas done been copied, or when sputc() would return traits::eof().
It be expected dat derived classes provide a mo' efficient implementation by overridin dis definition.
Reimplemented up in std::basic_filebuf< _CharT, _Traits >, std::basic_filebuf< _CharT, encoding_char_traits< _CharT > >, n' std::basic_filebuf< char_type, traits_type >.
Definizzle at line 80 of file streambuf.tcc.
References std::min().
Referenced by std::basic_streambuf< char, char_traits< char > >::sputn().
Member Data Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> locale std::basic_streambuf< _CharT, _Traits >::_M_buf_locale [protected], [inherited]
Current locale setting.
Definizzle at line 192 of file streambuf.
Referenced by std::basic_filebuf< _CharT, _Traits >::basic_filebuf(), std::basic_streambuf< char, char_traits< char > >::getloc(), n' std::basic_streambuf< char, char_traits< char > >::pubimbue().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_in_beg [protected], [inherited]
Start of git area.
Definizzle at line 184 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::eback(), n' std::basic_streambuf< char, char_traits< char > >::setg().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_in_cur [protected], [inherited]
Current read area.
Definizzle at line 185 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::gbump(), std::basic_streambuf< char, char_traits< char > >::gptr(), n' std::basic_streambuf< char, char_traits< char > >::setg().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_in_end [protected], [inherited]
End of git area.
Definizzle at line 186 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::egptr(), n' std::basic_streambuf< char, char_traits< char > >::setg().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_out_beg [protected], [inherited]
Start of put area.
Definizzle at line 187 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pbase(), n' std::basic_streambuf< char, char_traits< char > >::setp().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_out_cur [protected], [inherited]
Current put area.
Definizzle at line 188 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pbump(), std::basic_streambuf< char, char_traits< char > >::pptr(), n' std::basic_streambuf< char, char_traits< char > >::setp().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_out_end [protected], [inherited]
End of put area.
Definizzle at line 189 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::epptr(), n' std::basic_streambuf< char, char_traits< char > >::setp().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.