" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
__gnu_cxx::temporary_buffer< _ForwardIterator, _Tp > -
SYNOPSIS
Inherits std::_Temporary_buffer< _ForwardIterator, _Tp >.
Public Types
typedef pointa iterator
typedef value_type * pointer
typedef ptrdiff_t size_type
typedef _Tp value_type
Public Member Functions
temporary_buffer (_ForwardIterator __first, _ForwardIterator __last)
~temporary_buffer ()
iterator begin ()
iterator end ()
size_type requested_size () const
size_type size () const
Protected Attributes
pointa _M_buffer
size_type _M_len
size_type _M_original_len
Detailed Description
template<class _ForwardIterator, class _Tp = typename std::iterator_traits<_ForwardIterator>::value_type>struct __gnu_cxx::temporary_buffer< _ForwardIterator, _Tp >
This class serves up similar behavior n' semantics of tha standard functions get_temporary_buffer() n' return_temporary_buffer() yo, but encapsulated up in a type vaguely resemblin a standard container.
By default, a temporary_buffer<Iter> stores space fo' objectz of whatever type tha Ita iterator points to. Well shiiiit, it is constructed from a typical [first,last) range, n' serves up tha begin(), end(), size() functions, as well as requested_size(). For non-trivial types, copiez of *first is ghon be used ta initialize tha storage.
malloc is used ta obtain underlyin storage.
Like get_temporary_buffer(), not all tha axed memory may be available. Ideally, tha pimped buffer is ghon be big-ass enough ta hold a cold-ass lil copy of [first,last) yo, but if size() is less than requested_size(), then dis didn't happen.
Definizzle at line 183 of file ext/memory.
Constructor & Destructor Documentation
template<class _ForwardIterator , class _Tp = typename std::iterator_traits<_ForwardIterator>::value_type> __gnu_cxx::temporary_buffer< _ForwardIterator, _Tp >::temporary_buffer (_ForwardIterator__first, _ForwardIterator__last) [inline]
Requests storage big-ass enough ta hold a cold-ass lil copy of [first,last).
Definizzle at line 186 of file ext/memory.
template<class _ForwardIterator , class _Tp = typename std::iterator_traits<_ForwardIterator>::value_type> __gnu_cxx::temporary_buffer< _ForwardIterator, _Tp >::~temporary_buffer () [inline]
Destroys objects n' frees storage.
Definizzle at line 190 of file ext/memory.
Member Function Documentation
template<typename _ForwardIterator, typename _Tp> iterator std::_Temporary_buffer< _ForwardIterator, _Tp >::begin () [inline], [inherited]
As per Table mumble.
Definizzle at line 151 of file stl_tempbuf.h.
Referenced by std::inplace_merge(), std::stable_partition(), n' std::stable_sort().
template<typename _ForwardIterator, typename _Tp> iterator std::_Temporary_buffer< _ForwardIterator, _Tp >::end () [inline], [inherited]
As per Table mumble.
Definizzle at line 156 of file stl_tempbuf.h.
template<typename _ForwardIterator, typename _Tp> size_type std::_Temporary_buffer< _ForwardIterator, _Tp >::requested_size () const [inline], [inherited]
Returns tha size axed by tha constructor; may be >size().
Definizzle at line 146 of file stl_tempbuf.h.
Referenced by std::stable_partition().
template<typename _ForwardIterator, typename _Tp> size_type std::_Temporary_buffer< _ForwardIterator, _Tp >::size () const [inline], [inherited]
As per Table mumble.
Definizzle at line 141 of file stl_tempbuf.h.
Referenced by std::inplace_merge(), std::stable_partition(), n' std::stable_sort().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.