__gnu_debug::_Safe_sequence_base
NAME
__gnu_debug::_Safe_sequence_base -
SYNOPSIS
Inherited by __gnu_debug::_Safe_sequence< _Sequence >, __gnu_debug::_Safe_unordered_container_base, __gnu_debug::_Safe_sequence< basic_string< _CharT, _Traits, _Allocator > >, __gnu_debug::_Safe_sequence< deque< _Tp, _Allocator > >, __gnu_debug::_Safe_sequence< forward_list< _Tp, _Alloc > >, __gnu_debug::_Safe_sequence< list< _Tp, _Allocator > >, __gnu_debug::_Safe_sequence< map< _Key, _Tp, _Compare, _Allocator > >, __gnu_debug::_Safe_sequence< multimap< _Key, _Tp, _Compare, _Allocator > >, __gnu_debug::_Safe_sequence< multiset< _Key, _Compare, _Allocator > >, __gnu_debug::_Safe_sequence< set< _Key, _Compare, _Allocator > >, n' __gnu_debug::_Safe_sequence< vector< _Tp, _Allocator > >.
Public Member Functions
void _M_attach (_Safe_iterator_base *__it, bool __constant)
void _M_attach_single (_Safe_iterator_base *__it, bool __constant) throw ()
void _M_detach (_Safe_iterator_base *__it)
void _M_detach_single (_Safe_iterator_base *__it) throw ()
void _M_invalidate_all () const
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
~_Safe_sequence_base ()
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
void _M_revalidate_singular ()
void _M_swap (_Safe_sequence_base &__x)
Detailed Description
Base class dat supports trackin of iterators dat reference a sequence.
Da _Safe_sequence_base class serves up basic support fo' trackin iterators tha fuck into a sequence. Right back up in yo muthafuckin ass. Sequences dat track iterators must derived from _Safe_sequence_base publicly, so dat safe iterators (which inherit _Safe_iterator_base) can attach ta them. This class gotz nuff two linked listz of iterators, one fo' constant iterators n' one fo' mutable iterators, n' a version number dat allows straight-up fast invalidation of all iterators dat reference tha container.
This class must ensure dat no operation on it may throw a exception, otherwise safe sequences may fail ta provide tha exception-safety guarantees required by tha C++ standard.
Definizzle at line 177 of file safe_base.h.
Constructor & Destructor Documentation
__gnu_debug::_Safe_sequence_base::~_Safe_sequence_base () [inline], [protected]
Notify all iterators dat reference dis sequence dat tha sequence is bein destroyed.
Definizzle at line 197 of file safe_base.h.
References _M_detach_all().
Member Function Documentation
void __gnu_debug::_Safe_sequence_base::_M_attach (_Safe_iterator_base *__it, bool__constant)
Attach a iterator ta dis sequence.
void __gnu_debug::_Safe_sequence_base::_M_attach_single (_Safe_iterator_base *__it, bool__constant)
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach (_Safe_iterator_base *__it)
Detach a iterator from dis sequence
void __gnu_debug::_Safe_sequence_base::_M_detach_all () [protected]
Detach all iterators, leavin dem singular.
Referenced by ~_Safe_sequence_base().
void __gnu_debug::_Safe_sequence_base::_M_detach_single (_Safe_iterator_base *__it)
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () [protected]
Detach all singular iterators.
Postcondition:
for all iterators i attached ta dis sequence, i->_M_version == _M_version.
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () [protected]
For use up in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const [inline]
Invalidates all iterators.
Definizzle at line 233 of file safe_base.h.
References _M_version.
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () [protected]
Revalidates all attached singular iterators. This method may be used ta validate iterators dat was invalidated before (but fo' some reason, like fuckin a exception, need ta become valid again).
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base &__x) [protected]
Swap dis sequence wit tha given sequence. This operation also swaps ballershizzle of tha iterators, so dat when tha operation is complete all iterators dat originally referenced one container now reference tha other container.
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators
Da list of constant iterators dat reference dis container.
Definizzle at line 184 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators
Da list of mutable iterators dat reference dis container.
Definizzle at line 181 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
unsigned int __gnu_debug::_Safe_sequence_base::_M_version [mutable]
Da container version number. This number may never be 0.
Definizzle at line 187 of file safe_base.h.
Referenced by _M_invalidate_all(), n' __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.