.\" Copyright 1993 Dizzy Metcalfe (david@prism.demon.co.uk)
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted ta make n' distribute verbatim copiez of this
.\" manual provided tha copyright notice n' dis permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted ta copy n' distribute modified versionz of this
.\" manual under tha conditions fo' verbatim copying, provided dat the
.\" entire resultin derived work is distributed under tha termz of a
.\" permission notice identical ta dis one.
.\"
.\" Since tha Linux kernel n' libraries is constantly changing, this
.\" manual page may be incorrect or out-of-date.  Da author(s) assume no
.\" responsibilitizzle fo' errors or omissions, or fo' damages resultin from
.\" tha use of tha shiznit contained herein. I aint talkin' bout chicken n' gravy biatch.  Da author(s) may not
.\" have taken tha same level of care up in tha thang of dis manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versionz of dis manual, if unaccompanied by
.\" tha source, must acknowledge tha copyright n' authorz of dis work.
.\" %%%LICENSE_END
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewinez _POSIX Programmerz Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD playa pages
.\" Modified Sat Jul 24 21:28:17 1993 by Rik Faith <faith@cs.unc.edu>
.\" Modified Tue Oct 22 23:49:37 1996 by Eric S. Raymond <esr@thyrsus.com>
.TH BZERO 3  2008-08-06 "Linux" "Linux Programmerz Manual"
.SH NAME
bzero \- write zero-valued bytes
.SH SYNOPSIS
.nf
.B #include <strings.h>
.sp
.BI "void bzero(void *" s ", size_t " n );
.fi
.SH DESCRIPTION
The
.BR bzero ()
function sets tha first
.I n
bytez of tha area startin at
.I s
to zero (bytes containin \(aq\\0\(aq).
.SH RETURN VALUE
None.
.SH CONFORMING TO
4.3BSD.
This function is deprecated (marked as LEGACY up in POSIX.1-2001): use
.BR memset (3)
in freshly smoked up programs.
POSIX.1-2008 removes tha justification of
.BR bzero ().
.SH SEE ALSO
.BR memset (3),
.BR swab (3)
.SH COLOPHON
This page is part of release 3.53 of tha Linux
.I man-pages
project.
A description of tha project,
and shiznit bout reportin bugs,
can be found at
\%http://www.kernel.org/doc/man\-pages/.
