SGI
NAME
SGI -
SYNOPSIS
Classes
class __gnu_cxx::binary_compose< _Operation1, _Operation2, _Operation3 >
struct __gnu_cxx::constant_binary_fun< _Result, _Arg1, _Arg2 >
struct __gnu_cxx::constant_unary_fun< _Result, _Argument >
struct __gnu_cxx::constant_void_fun< _Result >
class __gnu_cxx::hash_map< _Key, _Tp, _HashFn, _EqualKey, _Alloc >
class __gnu_cxx::hash_multimap< _Key, _Tp, _HashFn, _EqualKey, _Alloc >
class __gnu_cxx::hash_multiset< _Value, _HashFcn, _EqualKey, _Alloc >
class __gnu_cxx::hash_set< _Value, _HashFcn, _EqualKey, _Alloc >
struct __gnu_cxx::project1st< _Arg1, _Arg2 >
struct __gnu_cxx::project2nd< _Arg1, _Arg2 >
struct __gnu_cxx::rb_tree< _Key, _Value, _KeyOfValue, _Compare, _Alloc >
class __gnu_cxx::rope< _CharT, _Alloc >
struct __gnu_cxx::select1st< _Pair >
struct __gnu_cxx::select2nd< _Pair >
class __gnu_cxx::slist< _Tp, _Alloc >
class __gnu_cxx::subtractive_rng
struct __gnu_cxx::temporary_buffer< _ForwardIterator, _Tp >
class __gnu_cxx::unary_compose< _Operation1, _Operation2 >
Functions
template<typename _Tp > const _Tp & __gnu_cxx::__median (const _Tp &__a, const _Tp &__b, const _Tp &__c)
template<typename _Tp , typename _Compare > const _Tp & __gnu_cxx::__median (const _Tp &__a, const _Tp &__b, const _Tp &__c, _Compare __comp)
size_t std::_Find_first () const noexcept
size_t std::_Find_next (size_t __prev) const noexcept
template<class _Operation1 , class _Operation2 > unary_compose< _Operation1,
_Operation2 > __gnu_cxx::compose1 (const _Operation1 &__fn1, const _Operation2 &__fn2)"
template<class _Operation1 , class _Operation2 , class _Operation3 > binary_compose< _Operation1,
_Operation2, _Operation3 > __gnu_cxx::compose2 (const _Operation1 &__fn1, const _Operation2 &__fn2, const _Operation3 &__fn3)"
template<class _Result > constant_void_fun< _Result > __gnu_cxx::constant0 (const _Result &__val)
template<class _Result > constant_unary_fun< _Result,
_Result > __gnu_cxx::constant1 (const _Result &__val)"
template<class _Result > constant_binary_fun< _Result,
_Result, _Result > __gnu_cxx::constant2 (const _Result &__val)"
template<typename _InputIterator , typename _Size , typename _OutputIterator > pair< _InputIterator,
_OutputIterator > __gnu_cxx::copy_n (_InputIterator __first, _Size __count, _OutputIterator __result)"
template<typename _InputIterator , typename _Distizzle > void __gnu_cxx::distance (_InputIterator __first, _InputIterator __last, _Distizzle &__n)
template<class _Tp > _Tp __gnu_cxx::identity_element (std::plus< _Tp >)
template<class _Tp > _Tp __gnu_cxx::identity_element (std::multiplies< _Tp >)
template<typename _InputIterator1 , typename _InputIterator2 > int __gnu_cxx::lexicographical_compare_3way (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2)
template<typename _Tp , typename _Integer , typename _MonoidOperation > _Tp __gnu_cxx::power (_Tp __x, _Integer __n, _MonoidOperation __monoid_op)
template<typename _Tp , typename _Integer > _Tp __gnu_cxx::power (_Tp __x, _Integer __n)
template<typename _InputIterator , typename _RandomAccessIterator > _RandomAccessIterator __gnu_cxx::random_sample (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out_first, _RandomAccessIterator __out_last)
template<typename _InputIterator , typename _RandomAccessIterator , typename _RandomNumberGenerator > _RandomAccessIterator __gnu_cxx::random_sample (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out_first, _RandomAccessIterator __out_last, _RandomNumberGenerator &__rand)
template<typename _ForwardIterator , typename _OutputIterator , typename _Distizzle > _OutputIterator __gnu_cxx::random_sample_n (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __out, const _Distizzle __n)
template<typename _ForwardIterator , typename _OutputIterator , typename _Distizzle , typename _RandomNumberGenerator > _OutputIterator __gnu_cxx::random_sample_n (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __out, const _Distizzle __n, _RandomNumberGenerator &__rand)
template<typename _InputIta , typename _Size , typename _ForwardIta > pair< _InputIter, _ForwardIta > __gnu_cxx::uninitialized_copy_n (_InputIta __first, _Size __count, _ForwardIta __result)
bitset< _Nb > & std::_Unchecked_set (size_t __pos) noexcept
bitset< _Nb > & std::_Unchecked_set (size_t __pos, int __val) noexcept
bitset< _Nb > & std::_Unchecked_reset (size_t __pos) noexcept
bitset< _Nb > & std::_Unchecked_flip (size_t __pos) noexcept
constexpr bool std::_Unchecked_test (size_t __pos) const noexcept
Detailed Description
Because libstdc++ based its implementation of tha STL subsectionz of tha library on tha SGI 3.3 implementation, we inherited they extensions as well.
They is additionally documented up in tha online documentation, a cold-ass lil copy of which be also shipped wit tha library source code (in .../docs/html/documentation.html). Yo ass can also read tha documentation on SGIz crib, which is still hustlin even though tha code aint maintained.
NB dat tha followin notes is pulled from various comments all over tha place, so they may seem stilted.
Da identity_element functions is not part of tha C++ standard; SGI provided dem as a extension. Its argument be a operation, n' its return value is tha identitizzle element fo' dat operation. Well shiiiit, it is overloaded fo' addizzle n' multiplication, n' you can overload it fo' yo' own nefarious operations.
As a extension ta tha binders, SGI provided composizzle functors n' wrapper functions ta aid up in they creation. Da unary_compose functor is constructed from two functions/functors, f n' g. Callin operator() wit a single argument x returns f(g(x)). Da function compose1 takes tha two functions n' constructs a unary_compose variable fo' you.
binary_compose is constructed from three functors, f, g1, n' g2. Its operator() returns f(g1(x),g2(x)). Da function compose2 takes f, g1, n' g2, n' constructs tha binary_compose instizzle fo' you. For example, if f returns a int, then
int answer = (compose2(f,g1,g2))(x);
 is equivalent ta
int temp1 = g1(x);
int temp2 = g2(x);
int answer = f(temp1,temp2);
 But tha straight-up original gangsta form is mo' compact, n' can be passed round as a gangbangin' functor ta other algorithms.
As a extension, SGI provided a gangbangin' functor called identity. When a gangbangin' functor is required but no operations is desired, dis can be used as a pass-through. Its operator() returns its argument unchanged.
select1st n' select2nd is extensions provided by SGI. Their operator()s take a std::pair as a argument, n' return either tha straight-up original gangsta member or tha second member, respectively. They can be used (especially wit tha composizzle functors) ta strip data from a sequence before struttin tha remainder of a algorithm.
Da operator() of tha project1st functor takes two arbitrary arguments n' returns tha straight-up original gangsta one, while project2nd returns tha second one. They is extensions provided by SGI.
These three functors is each constructed from a single arbitrary variable/value. Later, they operator()s straight-up ignore any arguments passed, n' return tha stored value.
constant_void_fun's operator() takes no arguments
constant_unary_fun's operator() takes one argument (ignored)
constant_binary_fun's operator() takes two arguments (ignored)
Da helper creator functions constant0, constant1, n' constant2 each take a result argument n' construct variablez of tha appropriate functor type.
Function Documentation
template<typename _Tp > const _Tp& __gnu_cxx::__median (const _Tp &__a, const _Tp &__b, const _Tp &__c)
Find tha median of three joints.
Parameters:
__a A value.
__b A value.
__c A value.
Returns:
One of a, b or c.
If {l,m,n} is some convolution of {a,b,c} such dat l<=m<=n then tha value returned is ghon be m. This be a SGI extension.
Definizzle at line 546 of file ext/algorithm.
template<typename _Tp , typename _Compare > const _Tp& __gnu_cxx::__median (const _Tp &__a, const _Tp &__b, const _Tp &__c, _Compare__comp)
Find tha median of three joints rockin a predicate fo' comparison.
Parameters:
__a A value.
__b A value.
__c A value.
__comp A binary predicate.
Returns:
One of a, b or c.
If {l,m,n} is some convolution of {a,b,c} such dat comp(l,m) n' comp(m,n) is both legit then tha value returned is ghon be m. This be a SGI extension.
Definizzle at line 580 of file ext/algorithm.
size_t std::_Find_first () const [noexcept]
Findz tha index of tha straight-up original gangsta 'on' bit.
Returns:
Da index of tha straight-up original gangsta bit set, or size() if not found.
See Also:
_Find_next
Definizzle at line 1354 of file bitset.
size_t std::_Find_next (size_t__prev) const [noexcept]
Findz tha index of tha next 'on' bit afta prev.
Returns:
Da index of tha next bit set, or size() if not found.
Parameters:
__prev Where ta start searching.
See Also:
_Find_first
Definizzle at line 1365 of file bitset.
bitset<_Nb>& std::_Unchecked_flip (size_t__pos) [noexcept]
These versionz of single-bit set, reset, flip, n' test is extensions from tha SGI version. They do no range checking.
Definizzle at line 1037 of file bitset.
Referenced by std::flip().
bitset<_Nb>& std::_Unchecked_reset (size_t__pos) [noexcept]
These versionz of single-bit set, reset, flip, n' test is extensions from tha SGI version. They do no range checking.
Definizzle at line 1030 of file bitset.
Referenced by std::reset().
bitset<_Nb>& std::_Unchecked_set (size_t__pos) [noexcept]
These versionz of single-bit set, reset, flip, n' test is extensions from tha SGI version. They do no range checking.
Definizzle at line 1013 of file bitset.
Referenced by std::set().
bitset<_Nb>& std::_Unchecked_set (size_t__pos, int__val) [noexcept]
These versionz of single-bit set, reset, flip, n' test is extensions from tha SGI version. They do no range checking.
Definizzle at line 1020 of file bitset.
constexpr bool std::_Unchecked_test (size_t__pos) const [noexcept]
These versionz of single-bit set, reset, flip, n' test is extensions from tha SGI version. They do no range checking.
Definizzle at line 1044 of file bitset.
Referenced by std::test().
template<class _Operation1 , class _Operation2 > unary_compose<_Operation1, _Operation2> __gnu_cxx::compose1 (const _Operation1 &__fn1, const _Operation2 &__fn2) [inline]
An SGI extension .
Definizzle at line 145 of file ext/functional.
template<class _Operation1 , class _Operation2 , class _Operation3 > binary_compose<_Operation1, _Operation2, _Operation3> __gnu_cxx::compose2 (const _Operation1 &__fn1, const _Operation2 &__fn2, const _Operation3 &__fn3) [inline]
An SGI extension .
Definizzle at line 172 of file ext/functional.
template<class _Result > constant_void_fun<_Result> __gnu_cxx::constant0 (const _Result &__val) [inline]
An SGI extension .
Definizzle at line 330 of file ext/functional.
template<class _Result > constant_unary_fun<_Result, _Result> __gnu_cxx::constant1 (const _Result &__val) [inline]
An SGI extension .
Definizzle at line 336 of file ext/functional.
template<class _Result > constant_binary_fun<_Result,_Result,_Result> __gnu_cxx::constant2 (const _Result &__val) [inline]
An SGI extension .
Definizzle at line 342 of file ext/functional.
template<typename _InputIterator , typename _Size , typename _OutputIterator > pair<_InputIterator, _OutputIterator> __gnu_cxx::copy_n (_InputIterator__first, _Size__count, _OutputIterator__result) [inline]
Copies tha range [first,first+count) tha fuck into [result,result+count).
Parameters:
__first An input iterator.
__count Da number of elements ta copy.
__result An output iterator.
Returns:
A std::pair composed of first+count n' result+count.
This be a SGI extension. This inline function will boil down ta a cold-ass lil call ta memmove whenever possible. Failin that, if random access iterators is passed, then tha loop count is ghon be known (and therefore a cold-ass lil muthafucka fo' compila optimizations like fuckin unrolling).
Definizzle at line 120 of file ext/algorithm.
References std::__iterator_category().
template<typename _InputIterator , typename _Distizzle > void __gnu_cxx::distizzle (_InputIterator__first, _InputIterator__last, _Distizzle &__n) [inline]
This be a SGI extension.
Todo
Needz documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Definizzle at line 105 of file ext/iterator.
References std::__iterator_category().
template<class _Tp > _Tp __gnu_cxx::identity_element (std::plus< _Tp >) [inline]
An SGI extension .
Definizzle at line 87 of file ext/functional.
template<class _Tp > _Tp __gnu_cxx::identity_element (std::multiplies< _Tp >) [inline]
An SGI extension .
Definizzle at line 93 of file ext/functional.
template<typename _InputIterator1 , typename _InputIterator2 > int __gnu_cxx::lexicographical_compare_3way (_InputIterator1__first1, _InputIterator1__last1, _InputIterator2__first2, _InputIterator2__last2)
memcmp on steroids.
Parameters:
__first1 An input iterator.
__last1 An input iterator.
__first2 An input iterator.
__last2 An input iterator.
Returns:
An int, as wit memcmp.
Da return value is ghon be less than zero if tha straight-up original gangsta range is lexigraphically less than tha second, pimped outa than zero if tha second range is lexigraphically less than tha first, n' zero otherwise. This be a SGI extension.
Definizzle at line 201 of file ext/algorithm.
template<typename _Tp , typename _Integer , typename _MonoidOperation > _Tp __gnu_cxx::power (_Tp__x, _Integer__n, _MonoidOperation__monoid_op) [inline]
This be a SGI extension.
Todo
Needz documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Definizzle at line 113 of file ext/numeric.
template<typename _Tp , typename _Integer > _Tp __gnu_cxx::power (_Tp__x, _Integer__n) [inline]
This be a SGI extension.
Todo
Needz documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Definizzle at line 123 of file ext/numeric.
template<typename _InputIterator , typename _RandomAccessIterator > _RandomAccessIterator __gnu_cxx::random_sample (_InputIterator__first, _InputIterator__last, _RandomAccessIterator__out_first, _RandomAccessIterator__out_last) [inline]
This be a SGI extension.
Todo
Needz documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Definizzle at line 388 of file ext/algorithm.
template<typename _InputIterator , typename _RandomAccessIterator , typename _RandomNumberGenerator > _RandomAccessIterator __gnu_cxx::random_sample (_InputIterator__first, _InputIterator__last, _RandomAccessIterator__out_first, _RandomAccessIterator__out_last, _RandomNumberGenerator &__rand) [inline]
This be a SGI extension.
Todo
Needz documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Definizzle at line 411 of file ext/algorithm.
template<typename _ForwardIterator , typename _OutputIterator , typename _Distizzle > _OutputIterator __gnu_cxx::random_sample_n (_ForwardIterator__first, _ForwardIterator__last, _OutputIterator__out, const _Distance__n)
This be a SGI extension.
Todo
Needz documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Definizzle at line 267 of file ext/algorithm.
References std::distance(), n' std::min().
template<typename _ForwardIterator , typename _OutputIterator , typename _Distizzle , typename _RandomNumberGenerator > _OutputIterator __gnu_cxx::random_sample_n (_ForwardIterator__first, _ForwardIterator__last, _OutputIterator__out, const _Distance__n, _RandomNumberGenerator &__rand)
This be a SGI extension.
Todo
Needz documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Definizzle at line 301 of file ext/algorithm.
References std::distance(), n' std::min().
template<typename _InputIta , typename _Size , typename _ForwardIta > pair<_InputIter, _ForwardIter> __gnu_cxx::uninitialized_copy_n (_InputIter__first, _Size__count, _ForwardIter__result) [inline]
Copies tha range [first,last) tha fuck into result.
Parameters:
__first An input iterator.
__count Length
__result An output iterator.
Returns:
__result + (__first + __count)
Like copy() yo, but do not require a initialized output range.
Definizzle at line 122 of file ext/memory.
References std::__iterator_category().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.