" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::normal_distribution< _RealType > -
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
normal_distribution (result_type __mean=result_type(0), result_type __stddev=result_type(1))
normal_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
result_type max () const
_RealType mean () const
result_type min () const
template<typename _UniformRandomNumberGenerator > normal_distribution< _RealType >
::result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)"
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
param_type param () const
void param (const param_type &__param)
void reset ()
_RealType stddev () const
Friends
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::normal_distribution< _RealType1 > &__x)"
template<typename _RealType1 > bool operator== (const std::normal_distribution< _RealType1 > &__d1, const std::normal_distribution< _RealType1 > &__d2)
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::normal_distribution< _RealType1 > &__x)"
Detailed Description
template<typename _RealType = double>class std::normal_distribution< _RealType >
A aiiight continuous distribution fo' random numbers.
Da formula fo' tha aiiight probabilitizzle densitizzle function is \[ p(x|\mu,\sigma) = \frac{1}{\sigma \sqrt{2 \pi}} e^{- \frac{{x - \mu}^ {2}}{2 \sigma ^ {2}} } \]
Definizzle at line 2085 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::normal_distribution< _RealType >::result_type
Da type of tha range of tha distribution.
Definizzle at line 2088 of file random.h.
Constructor & Destructor Documentation
template<typename _RealType = double> std::normal_distribution< _RealType >::normal_distribution (result_type__mean = result_type(0), result_type__stddev = result_type(1)) [inline], [explicit]
Constructs a aiiight distribution wit parametas $mean$ n' standard deviation.
Definizzle at line 2130 of file random.h.
Member Function Documentation
template<typename _RealType = double> result_type std::normal_distribution< _RealType >::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 2187 of file random.h.
template<typename _RealType = double> _RealType std::normal_distribution< _RealType >::mean () const [inline]
Returns tha mean of tha distribution.
Definizzle at line 2151 of file random.h.
template<typename _RealType = double> result_type std::normal_distribution< _RealType >::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 2180 of file random.h.
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > normal_distribution<_RealType>::result_type std::normal_distribution< _RealType >::operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)
Polar method cuz of Marsaglia.
Devroye, L. Non-Uniform Random Variates Generation. Right back up in yo muthafuckin ass. Springer-Verlag, New York, 1986, Ch. V, Sect. 4.4.
Definizzle at line 1935 of file bits/random.tcc.
References std::log(), n' std::sqrt().
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::normal_distribution< _RealType >::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 2195 of file random.h.
Referenced by std::normal_distribution< result_type >::operator()().
template<typename _RealType = double> param_type std::normal_distribution< _RealType >::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 2165 of file random.h.
template<typename _RealType = double> void std::normal_distribution< _RealType >::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 2173 of file random.h.
template<typename _RealType = double> void std::normal_distribution< _RealType >::reset () [inline]
Resets tha distribution state.
Definizzle at line 2144 of file random.h.
Referenced by std::lognormal_distribution< _RealType >::reset(), std::gamma_distribution< result_type >::reset(), std::student_t_distribution< _RealType >::reset(), std::binomial_distribution< _IntType >::reset(), n' std::poisson_distribution< _IntType >::reset().
template<typename _RealType = double> _RealType std::normal_distribution< _RealType >::stddev () const [inline]
Returns tha standard deviation of tha distribution.
Definizzle at line 2158 of file random.h.
Playas And Related Function Documentation
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::normal_distribution< _RealType1 > &__x) [friend]
Inserts a normal_distribution random number distribution __x tha fuck into tha output stream __os.
Parameters:
__os An output stream.
__x A normal_distribution random number distribution.
Returns:
Da output stream wit tha state of __x banged or up in a error state.
template<typename _RealType = double> template<typename _RealType1 > bool operator== (const std::normal_distribution< _RealType1 > &__d1, const std::normal_distribution< _RealType1 > &__d2) [friend]
Return legit if two aiiight distributions have tha same parametas n' tha sequences dat would be generated is equal.
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &__is, std::normal_distribution< _RealType1 > &__x) [friend]
Extracts a normal_distribution random number distribution __x from tha input stream __is.
Parameters:
__is An input stream.
__x A normal_distribution random number generator engine.
Returns:
Da input stream wit __x extracted or up in a error state.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.