std::bernoulli_distribution
NAME
std::bernoulli_distribution -
SYNOPSIS
Classes
struct param_type
Public Types
typedef bool result_type
Public Member Functions
bernoulli_distribution (double __p=0.5)
bernoulli_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
double p () const
param_type param () const
void param (const param_type &__param)
void reset ()
Friends
bool operator== (const bernoulli_distribution &__d1, const bernoulli_distribution &__d2)
Detailed Description
A Bernoulli random number distribution.
Generates a sequence of legit n' false joints wit likelihood $p$ dat legit will come up n' $(1 - p)$ dat false will appear.
Definizzle at line 3572 of file random.h.
Member Typedef Documentation
typedef bool std::bernoulli_distribution::result_type
Da type of tha range of tha distribution.
Definizzle at line 3576 of file random.h.
Constructor & Destructor Documentation
std::bernoulli_distribution::bernoulli_distribution (double__p = 0.5) [inline], [explicit]
Constructs a Bernoulli distribution wit likelihood p.
Parameters:
__p [IN] Da likelihood of a legit result bein returned. Must be up in tha interval $[0, 1]$.
Definizzle at line 3609 of file random.h.
Member Function Documentation
result_type std::bernoulli_distribution::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 3659 of file random.h.
References std::numeric_limits< _Tp >::max().
result_type std::bernoulli_distribution::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 3652 of file random.h.
References std::numeric_limits< _Tp >::min().
template<typename _UniformRandomNumberGenerator > result_type std::bernoulli_distribution::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 3667 of file random.h.
double std::bernoulli_distribution::p () const [inline]
Returns tha p parameta of tha distribution.
Definizzle at line 3630 of file random.h.
param_type std::bernoulli_distribution::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 3637 of file random.h.
Referenced by std::operator>>().
void std::bernoulli_distribution::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 3645 of file random.h.
void std::bernoulli_distribution::reset () [inline]
Resets tha distribution state. Do not a god damn thang fo' a Bernoulli distribution.
Definizzle at line 3624 of file random.h.
Playas And Related Function Documentation
bool operator== (const bernoulli_distribution &__d1, const bernoulli_distribution &__d2) [friend]
Return legit if two Bernoulli distributions have tha same parameters.
Definizzle at line 3709 of file random.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.