" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::auto_ptr< _Tp > -
SYNOPSIS
Public Types
typedef _Tp element_type
Public Member Functions
auto_ptr (element_type *__p=0) throw ()
auto_ptr (auto_ptr &__a) throw ()
template<typename _Tp1 > auto_ptr (auto_ptr< _Tp1 > &__a) throw ()
auto_ptr (auto_ptr_ref< element_type > __ref) throw ()
~auto_ptr ()
element_type * get () const throw ()
template<typename _Tp1 > operator auto_ptr< _Tp1 > () throw ()
template<typename _Tp1 > operator auto_ptr_ref< _Tp1 > () throw ()
element_type & operator* () const throw ()
element_type * operator-> () const throw ()
auto_ptr & operator= (auto_ptr &__a) throw ()
template<typename _Tp1 > auto_ptr & operator= (auto_ptr< _Tp1 > &__a) throw ()
auto_ptr & operator= (auto_ptr_ref< element_type > __ref) throw ()
element_type * release () throw ()
void reset (element_type *__p=0) throw ()
Detailed Description
template<typename _Tp>class std::auto_ptr< _Tp >
A simple smart-ass pointa providin strict ballershizzle semantics.
Da Standard says:
An auto_ptr owns tha object it holdz a pointa to. Copying
an auto_ptr copies tha pointa n' transfers ballershizzle ta the
destination. If mo' than one auto_ptr owns tha same ol' dirty object
at tha same time tha behavior of tha program is undefined.
Da usez of auto_ptr include providin temporary
exception-safety fo' dynamically allocated memory, passing
ballershizzle of dynamically allocated memory ta a gangbangin' function, and
returnin dynamically allocated memory from a gangbangin' function. auto_ptr do not hook up tha CopyConstructible n' Assignable
requirements fo' Standard Library container elements n' thus
instantiatin a Standard Library container wit a auto_ptr thangs up in dis biatch up in undefined behavior.
 Quoted from [20.4.5]/3.
Dope examplez of what tha fuck can n' cannot be done wit auto_ptr can be found up in tha libstdc++ testsuite.
_GLIBCXX_RESOLVE_LIB_DEFECTS 127. auto_ptr<> conversion thangs These resolutions have all been incorporated.
Definizzle at line 87 of file auto_ptr.h.
Member Typedef Documentation
template<typename _Tp> typedef _Tp std::auto_ptr< _Tp >::element_type
Da pointed-to type.
Definizzle at line 94 of file auto_ptr.h.
Constructor & Destructor Documentation
template<typename _Tp> std::auto_ptr< _Tp >::auto_ptr (element_type *__p = 0) [inline], [explicit]
An auto_ptr is probably constructed from a raw pointer.
Parameters:
__p A pointa (defaults ta NULL).
This object now owns tha object pointed ta by __p.
Definizzle at line 103 of file auto_ptr.h.
template<typename _Tp> std::auto_ptr< _Tp >::auto_ptr (auto_ptr< _Tp > &__a) [inline]
An auto_ptr can be constructed from another auto_ptr.
Parameters:
__a Another auto_ptr of tha same type.
This object now owns tha object previously owned by __a, which has given up ballership.
Definizzle at line 112 of file auto_ptr.h.
template<typename _Tp> template<typename _Tp1 > std::auto_ptr< _Tp >::auto_ptr (auto_ptr< _Tp1 > &__a) [inline]
An auto_ptr can be constructed from another auto_ptr.
Parameters:
__a Another auto_ptr of a gangbangin' finger-lickin' different but related type.
A pointer-to-Tp1 must be convertible ta a pointer-to-Tp/element_type.
This object now owns tha object previously owned by __a, which has given up ballership.
Definizzle at line 125 of file auto_ptr.h.
template<typename _Tp> std::auto_ptr< _Tp >::~auto_ptr () [inline]
When tha auto_ptr goes outta scope, tha object it owns is deleted. If it no longer owns anythang (i.e., get() is NULL), then dis has no effect.
Da C++ standard say there is supposed ta be a empty throw justification here yo, but omittin it is standard conforming. Its presence can be detected only if _Tp::~_Tp() throws yo, but dis is prohibited. [17.4.3.6]/2
Definizzle at line 170 of file auto_ptr.h.
template<typename _Tp> std::auto_ptr< _Tp >::auto_ptr (auto_ptr_ref< element_type >__ref) [inline]
Automatic conversions. These operations convert a auto_ptr tha fuck into n' from a auto_ptr_ref automatically as needed. This allows constructs like fuckin
auto_ptr<Derived> func_returning_auto_ptr(.....);
...
auto_ptr<Base> ptr = func_returning_auto_ptr(.....);
Definizzle at line 260 of file auto_ptr.h.
Member Function Documentation
template<typename _Tp> element_type* std::auto_ptr< _Tp >::get (void) const [inline]
Bypassin tha smart-ass pointer.
Returns:
Da raw pointa bein managed.
Yo ass can git a cold-ass lil copy of tha pointa dat dis object owns, fo' thangs like fuckin passin ta a gangbangin' function which only accepts a raw pointer.
Note:
This auto_ptr still owns tha memory.
Definizzle at line 211 of file auto_ptr.h.
template<typename _Tp> element_type& std::auto_ptr< _Tp >::operator* () const [inline]
Smart pointa dereferencing. If dis auto_ptr no longer owns anything, then dis operation will crash. (For a smart-ass pointer, no longer owns anything is tha same ol' dirty as bein a null pointer, n' you know what tha fuck happens when you dereference one of them...)
Definizzle at line 181 of file auto_ptr.h.
template<typename _Tp> element_type* std::auto_ptr< _Tp >::operator-> () const [inline]
Smart pointa dereferencing. This returns tha pointa itself, which tha language then will automatically cause ta be dereferenced.
Definizzle at line 194 of file auto_ptr.h.
template<typename _Tp> auto_ptr& std::auto_ptr< _Tp >::operator= (auto_ptr< _Tp > &__a) [inline]
auto_ptr assignment operator.
Parameters:
__a Another auto_ptr of tha same type.
This object now owns tha object previously owned by __a, which has given up ballership. Da object dat dis one used ta own n' track has been deleted.
Definizzle at line 136 of file auto_ptr.h.
References std::auto_ptr< _Tp >::reset().
template<typename _Tp> template<typename _Tp1 > auto_ptr& std::auto_ptr< _Tp >::operator= (auto_ptr< _Tp1 > &__a) [inline]
auto_ptr assignment operator.
Parameters:
__a Another auto_ptr of a gangbangin' finger-lickin' different but related type.
A pointer-to-Tp1 must be convertible ta a pointer-to-Tp/element_type.
This object now owns tha object previously owned by __a, which has given up ballership. Da object dat dis one used ta own n' track has been deleted.
Definizzle at line 154 of file auto_ptr.h.
References std::auto_ptr< _Tp >::reset().
template<typename _Tp> element_type* std::auto_ptr< _Tp >::release () [inline]
Bypassin tha smart-ass pointer.
Returns:
Da raw pointa bein managed.
Yo ass can git a cold-ass lil copy of tha pointa dat dis object owns, fo' thangs like fuckin passin ta a gangbangin' function which only accepts a raw pointer.
Note:
This auto_ptr no longer owns tha memory. When dis object goes outta scope, not a god damn thang will happen.
Definizzle at line 225 of file auto_ptr.h.
template<typename _Tp> void std::auto_ptr< _Tp >::reset (element_type *__p = 0) [inline]
Forcibly deletes tha managed object.
Parameters:
__p A pointa (defaults ta NULL).
This object now owns tha object pointed ta by __p. Da previous object has been deleted.
Definizzle at line 240 of file auto_ptr.h.
Referenced by std::auto_ptr< _Tp >::operator=().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.