" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::linear_congruential_engine< _UIntType, __a, __c, __m > -
SYNOPSIS
Public Types
typedef _UIntType result_type
Public Member Functions
linear_congruential_engine (result_type __s=default_seed)
template<typename _Sseq , typename = typename std::enable_if<!std::is_same<_Sseq, linear_congruential_engine>::value> ::type> linear_congruential_engine (_Sseq &__q)
void discard (unsigned long long __z)
result_type operator() ()
void seed (result_type __s=default_seed)
template<typename _Sseq > std::enable_if< std::is_class
< _Sseq >::value >::type seed (_Sseq &__q)"
Static Public Member Functions
static constexpr result_type max ()
static constexpr result_type min ()
Static Public Attributes
static constexpr result_type default_seed
static constexpr result_type increment
static constexpr result_type modulus
static constexpr result_type multiplier
Friends
template<typename _UIntType1 , _UIntType1 __a1, _UIntType1 __c1, _UIntType1 __m1, typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::linear_congruential_engine< _UIntType1, __a1, __c1, __m1 > &__lcr)"
bool operator== (const linear_congruential_engine &__lhs, const linear_congruential_engine &__rhs)
template<typename _UIntType1 , _UIntType1 __a1, _UIntType1 __c1, _UIntType1 __m1, typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::linear_congruential_engine< _UIntType1, __a1, __c1, __m1 > &__lcr)"
Detailed Description
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m>class std::linear_congruential_engine< _UIntType, __a, __c, __m >
A model of a linear congruential random number generator.
A random number generator dat produces pseudorandom numbers via linear function: \[ x_{i+1}\leftarrow(ax_{i} + c) \bmod m \]
Da template parameta _UIntType must be a unsigned integral type big-ass enough ta store joints up ta (__m-1). If tha template parameta __m is 0, tha modulus __m used is std::numeric_limits<_UIntType>::max() plus 1. Otherwise, tha template parametas __a n' __c must be less than __m.
Da size of tha state is $1$.
Definizzle at line 241 of file random.h.
Member Typedef Documentation
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> typedef _UIntType std::linear_congruential_engine< _UIntType, __a, __c, __m >::result_type
Da type of tha generated random value.
Definizzle at line 244 of file random.h.
Constructor & Destructor Documentation
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> std::linear_congruential_engine< _UIntType, __a, __c, __m >::linear_congruential_engine (result_type__s = default_seed) [inline], [explicit]
Constructs a linear_congruential_engine random number generator engine wit seed __s. Da default seed value is 1.
Parameters:
__s Da initial seed value.
Definizzle at line 268 of file random.h.
References std::linear_congruential_engine< _UIntType, __a, __c, __m >::seed().
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> template<typename _Sseq , typename = typename std::enable_if<!std::is_same<_Sseq, linear_congruential_engine>::value> ::type> std::linear_congruential_engine< _UIntType, __a, __c, __m >::linear_congruential_engine (_Sseq &__q) [inline], [explicit]
Constructs a linear_congruential_engine random number generator engine seeded from tha seed sequence __q.
Parameters:
__q tha seed sequence.
Definizzle at line 281 of file random.h.
References std::linear_congruential_engine< _UIntType, __a, __c, __m >::seed().
Member Function Documentation
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> void std::linear_congruential_engine< _UIntType, __a, __c, __m >::discard (unsigned long long__z) [inline]
Discard a sequence of random numbers.
Definizzle at line 325 of file random.h.
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> static constexpr result_type std::linear_congruential_engine< _UIntType, __a, __c, __m >::max () [inline], [static]
Gets tha phattest possible value up in tha output range.
Definizzle at line 318 of file random.h.
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> static constexpr result_type std::linear_congruential_engine< _UIntType, __a, __c, __m >::min () [inline], [static]
Gets tha smallest possible value up in tha output range. Da minimum dependz on tha __c parameter: if it is zero, tha minimum generated must be > 0, otherwise 0 be allowed.
Definizzle at line 311 of file random.h.
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> result_type std::linear_congruential_engine< _UIntType, __a, __c, __m >::operator() () [inline]
Gets tha next random number up in tha sequence.
Definizzle at line 335 of file random.h.
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m> void std::linear_congruential_engine< _UIntType, __a, __c, __m >::seed (result_type__s = default_seed)
Reseedz tha linear_congruential_engine random number generator engine sequence ta tha seed __s.
Parameters:
__s Da freshly smoked up seed.
Seedz tha LCR wit integral value __s, adjusted so dat tha rang identitizzle is never a gangmember of tha convergence set.
Definizzle at line 120 of file bits/random.tcc.
Referenced by std::linear_congruential_engine< _UIntType, __a, __c, __m >::linear_congruential_engine().
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m> template<typename _Sseq > std::enable_if< std::is_class< _Sseq >::value >::type std::linear_congruential_engine< _UIntType, __a, __c, __m >::seed (_Sseq &__q)
Reseedz tha linear_congruential_engine random number generator engine sequence rockin joints from tha seed sequence __q.
Parameters:
__q tha seed sequence.
Seedz tha LCR engine wit a value generated by __q.
Definizzle at line 136 of file bits/random.tcc.
References std::__lg().
Playas And Related Function Documentation
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> template<typename _UIntType1 , _UIntType1 __a1, _UIntType1 __c1, _UIntType1 __m1, typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::linear_congruential_engine< _UIntType1, __a1, __c1, __m1 > &__lcr) [friend]
Writes tha textual representation of tha state x(i) of x ta __os.
Parameters:
__os Da output stream.
__lcr A % linear_congruential_engine random number generator.
Returns:
__os.
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> bool operator== (const linear_congruential_engine< _UIntType, __a, __c, __m > &__lhs, const linear_congruential_engine< _UIntType, __a, __c, __m > &__rhs) [friend]
Compares two linear congruential random number generator objectz of tha same type fo' equality.
Parameters:
__lhs A linear congruential random number generator object.
__rhs Another linear congruential random number generator object.
Returns:
true if tha infinite sequencez of generated joints would be equal, false otherwise.
Definizzle at line 353 of file random.h.
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> template<typename _UIntType1 , _UIntType1 __a1, _UIntType1 __c1, _UIntType1 __m1, typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &__is, std::linear_congruential_engine< _UIntType1, __a1, __c1, __m1 > &__lcr) [friend]
Sets tha state of tha engine by readin its textual representation from __is. Da textual representation must done been previously freestyled rockin a output stream whose imbued locale n' whose typez template specialization arguments _CharT n' _Traits was tha same as dem of __is.
Parameters:
__is Da input stream.
__lcr A % linear_congruential_engine random number generator.
Returns:
__is.
Member Data Documentation
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> constexpr _UIntType std::linear_congruential_engine< _UIntType, __a, __c, __m >::increment [static]
An increment.
Definizzle at line 255 of file random.h.
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> constexpr _UIntType std::linear_congruential_engine< _UIntType, __a, __c, __m >::modulus [static]
Da modulus.
Definizzle at line 257 of file random.h.
template<typename _UIntType, _UIntType __a, _UIntType __c, _UIntType __m> constexpr _UIntType std::linear_congruential_engine< _UIntType, __a, __c, __m >::multiplier [static]
Da multiplier.
Definizzle at line 253 of file random.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.