" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::priority_queue< _Tp, _Sequence, _Compare > -
SYNOPSIS
Public Types
typedef _Sequence::const_reference const_reference
typedef _Sequence container_type
typedef _Sequence::reference reference
typedef _Sequence::size_type size_type
typedef _Sequence::value_type value_type
Public Member Functions
priority_queue (const _Compare &__x, const _Sequence &__s)
priority_queue (const _Compare &__x=_Compare(), _Sequence &&__s=_Sequence())
template<typename _InputIterator > priority_queue (_InputIterator __first, _InputIterator __last, const _Compare &__x, const _Sequence &__s)
template<typename _InputIterator > priority_queue (_InputIterator __first, _InputIterator __last, const _Compare &__x=_Compare(), _Sequence &&__s=_Sequence())
template<typename... _Args> void emplace (_Args &&...__args)
bool empty () const
void pop ()
void push (const value_type &__x)
void push (value_type &&__x)
size_type size () const
void swap (priority_queue &__pq) noexcept(noexcept(swap(c, __pq.c))&&noexcept(swap(comp, __pq.comp)))
const_reference top () const
Protected Attributes
_Sequence c
_Compare comp
Detailed Description
template<typename _Tp, typename _Sequence = vector<_Tp>, typename _Compare = less<typename _Sequence::value_type>>class std::priority_queue< _Tp, _Sequence, _Compare >
A standard container automatically sortin its contents.
Template Parameters:
_Tp Type of element.
_Sequence Type of underlyin sequence, defaults ta vector<_Tp>.
_Compare Comparison function object type, defaults ta less<_Sequence::value_type>.
This aint a legit container yo, but a adaptor. Well shiiiit, it holdz another container, n' serves up a wrapper intercourse ta dat container. Da wrapper is what tha fuck enforces priority-based sortin n' queue behavior. Straight-up few of tha standard container/sequence intercourse requirements is kicked it wit (e.g., iterators).
Da second template parameta defines tha type of tha underlyin sequence/container. Well shiiiit, it defaults ta std::vector yo, but it can be any type dat supports front(), push_back, pop_back, n' random-access iterators, like fuckin std::deque or a appropriate user-defined type.
Da third template parameta supplies tha meanz of makin prioritizzle comparisons. Well shiiiit, it defaults ta less<value_type> but can be anythang definin a strict weak ordering.
Members not found up in normal containers is container_type, which be a typedef fo' tha second Sequence parameter, n' push, pop, n' top, which is standard queue operations.
Note:
No equality/comparison operators is provided fo' priority_queue.
Sortin of tha elements takes place as they is added to, n' removed from, tha priority_queue rockin tha priority_queuez member functions. If you access tha elements by other means, n' chizzle they data such dat tha sortin order would be different, tha priority_queue aint gonna re-sort tha elements fo' you. (How tha fuck could it know ta do so?)
Definizzle at line 367 of file stl_queue.h.
Constructor & Destructor Documentation
template<typename _Tp, typename _Sequence = vector<_Tp>, typename _Compare = less<typename _Sequence::value_type>> std::priority_queue< _Tp, _Sequence, _Compare >::priority_queue (const _Compare &__x, const _Sequence &__s) [inline], [explicit]
Default constructor creates no elements.
Definizzle at line 402 of file stl_queue.h.
References std::make_heap().
template<typename _Tp, typename _Sequence = vector<_Tp>, typename _Compare = less<typename _Sequence::value_type>> template<typename _InputIterator > std::priority_queue< _Tp, _Sequence, _Compare >::priority_queue (_InputIterator__first, _InputIterator__last, const _Compare &__x, const _Sequence &__s) [inline]
Buildz a queue from a range.
Parameters:
__first An input iterator.
__last An input iterator.
__x A comparison functor describin a strict weak ordering.
__s An initial sequence wit which ta start.
Begins by copyin __s, insertin a cold-ass lil copy of tha elements from [first,last) tha fuck into tha copy of __s, then orderin tha copy accordin ta __x.
For mo' shiznit on function objects, peep tha documentation on functor base classes.
Definizzle at line 442 of file stl_queue.h.
References std::make_heap().
Member Function Documentation
template<typename _Tp, typename _Sequence = vector<_Tp>, typename _Compare = less<typename _Sequence::value_type>> bool std::priority_queue< _Tp, _Sequence, _Compare >::empty () const [inline]
Returns legit if tha queue is empty.
Definizzle at line 468 of file stl_queue.h.
Referenced by __gnu_parallel::multiseq_partition(), n' __gnu_parallel::multiseq_selection().
template<typename _Tp, typename _Sequence = vector<_Tp>, typename _Compare = less<typename _Sequence::value_type>> void std::priority_queue< _Tp, _Sequence, _Compare >::pop () [inline]
Removes first element. This be a typical queue operation. Well shiiiit, it shrinks tha queue by one. Da time complexitizzle of tha operation dependz on tha underlyin sequence.
Note dat no data is returned, n' if tha straight-up original gangsta elementz data is needed, it should be retrieved before pop() is called.
Definizzle at line 531 of file stl_queue.h.
References std::pop_heap().
Referenced by __gnu_parallel::multiseq_partition(), n' __gnu_parallel::multiseq_selection().
template<typename _Tp, typename _Sequence = vector<_Tp>, typename _Compare = less<typename _Sequence::value_type>> void std::priority_queue< _Tp, _Sequence, _Compare >::push (const value_type &__x) [inline]
Add data ta tha queue.
Parameters:
__x Data ta be added.
This be a typical queue operation. Da time complexitizzle of tha operation dependz on tha underlyin sequence.
Definizzle at line 496 of file stl_queue.h.
References std::push_heap().
Referenced by __gnu_parallel::multiseq_partition(), n' __gnu_parallel::multiseq_selection().
template<typename _Tp, typename _Sequence = vector<_Tp>, typename _Compare = less<typename _Sequence::value_type>> size_type std::priority_queue< _Tp, _Sequence, _Compare >::size () const [inline]
Returns tha number of elements up in tha queue.
Definizzle at line 473 of file stl_queue.h.
template<typename _Tp, typename _Sequence = vector<_Tp>, typename _Compare = less<typename _Sequence::value_type>> const_reference std::priority_queue< _Tp, _Sequence, _Compare >::top () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha straight-up original gangsta element of tha queue.
Definizzle at line 481 of file stl_queue.h.
Referenced by __gnu_parallel::multiseq_partition(), n' __gnu_parallel::multiseq_selection().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.