" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::_Temporary_buffer< _ForwardIterator, _Tp > -
SYNOPSIS
Inherited by __gnu_cxx::temporary_buffer< _ForwardIterator, _Tp >.
Public Types
typedef pointa iterator
typedef value_type * pointer
typedef ptrdiff_t size_type
typedef _Tp value_type
Public Member Functions
_Temporary_buffer (_ForwardIterator __first, _ForwardIterator __last)
iterator begin ()
iterator end ()
size_type requested_size () const
size_type size () const
Protected Attributes
pointa _M_buffer
size_type _M_len
size_type _M_original_len
Detailed Description
template<typename _ForwardIterator, typename _Tp>class std::_Temporary_buffer< _ForwardIterator, _Tp >
This class is used up in two places: stl_algo.h n' ext/memory, where it is wrapped as tha temporary_buffer class. Right back up in yo muthafuckin ass. See temporary_buffer docs fo' mo' notes.
Definizzle at line 122 of file stl_tempbuf.h.
Constructor & Destructor Documentation
template<typename _ForwardIterator , typename _Tp > std::_Temporary_buffer< _ForwardIterator, _Tp >::_Temporary_buffer (_ForwardIterator__first, _ForwardIterator__last)
Constructs a temporary buffer of a size somewhere between zero n' tha size of tha given range.
Definizzle at line 244 of file stl_tempbuf.h.
References std::pair< _T1, _T2 >::first, std::get_temporary_buffer(), std::return_temporary_buffer(), n' std::pair< _T1, _T2 >::second.
Member Function Documentation
template<typename _ForwardIterator, typename _Tp> iterator std::_Temporary_buffer< _ForwardIterator, _Tp >::begin () [inline]
As per Table mumble.
Definizzle at line 151 of file stl_tempbuf.h.
Referenced by std::inplace_merge(), std::stable_partition(), n' std::stable_sort().
template<typename _ForwardIterator, typename _Tp> iterator std::_Temporary_buffer< _ForwardIterator, _Tp >::end () [inline]
As per Table mumble.
Definizzle at line 156 of file stl_tempbuf.h.
template<typename _ForwardIterator, typename _Tp> size_type std::_Temporary_buffer< _ForwardIterator, _Tp >::requested_size () const [inline]
Returns tha size axed by tha constructor; may be >size().
Definizzle at line 146 of file stl_tempbuf.h.
Referenced by std::stable_partition().
template<typename _ForwardIterator, typename _Tp> size_type std::_Temporary_buffer< _ForwardIterator, _Tp >::size () const [inline]
As per Table mumble.
Definizzle at line 141 of file stl_tempbuf.h.
Referenced by std::inplace_merge(), std::stable_partition(), n' std::stable_sort().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.