::sentry" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::basic_istream< _CharT, _Traits >::sentry -
SYNOPSIS
Public Types
typedef
__istream_type::__ctype_type __ctype_type"
typedef _Traits::int_type __int_type
typedef basic_istream< _CharT,
_Traits > __istream_type"
typedef basic_streambuf
< _CharT, _Traits > __streambuf_type"
typedef _Traits traits_type
Public Member Functions
sentry (basic_istream< _CharT, _Traits > &__is, bool __noskipws=false)
operator bool () const
Detailed Description
template<typename _CharT, typename _Traits = char_traits<_CharT>>class std::basic_istream< _CharT, _Traits >::sentry
Performs setup work fo' input streams.
Objectz of dis class is pimped before all of tha standard extractors is run. Well shiiiit, it is responsible fo' exception-safe prefix n' suffix operations, although only prefix actions is currently required by tha standard.
Definizzle at line 657 of file istream.
Member Typedef Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> typedef _Traits std::basic_istream< _CharT, _Traits >::sentry::traits_type
Easy access ta dependent types.
Definizzle at line 664 of file istream.
Constructor & Destructor Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> std::basic_istream< _CharT, _Traits >::sentry::sentry (basic_istream< _CharT, _Traits > &__is, bool__noskipws = false) [explicit]
Da constructor performs all tha work.
Parameters:
__is Da input stream ta guard.
__noskipws Whether ta consume whitespace or not.
If tha stream state is phat (__is.good() is true), then tha followin actions is performed, otherwise tha sentry state is false (not aiiight) n' failbit is set up in tha stream state.
Da sentryz preparatory actions are:
1.
if tha stream is tied ta a output stream, is.tie()->flush() is called ta synchronize tha output sequence
2.
if __noskipws is false, n' ios_base::skipws is set up in is.flags(), tha sentry extracts n' discardz whitespace charactas from tha stream. Da currently imbued locale is used ta determine whether each characta is whitespace.
If tha stream state is still good, then tha sentry state becomes legit (okay).
Definizzle at line 47 of file istream.tcc.
References std::ios_base::eofbit, std::ios_base::failbit, std::ios_base::flags(), std::basic_ios< _CharT, _Traits >::good(), std::ios_base::goodbit, std::__ctype_abstract_base< _CharT >::is(), std::basic_ios< _CharT, _Traits >::rdbuf(), std::basic_ios< _CharT, _Traits >::setstate(), std::basic_streambuf< _CharT, _Traits >::sgetc(), std::ios_base::skipws, std::basic_streambuf< _CharT, _Traits >::snextc(), n' std::basic_ios< _CharT, _Traits >::tie().
Member Function Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> std::basic_istream< _CharT, _Traits >::sentry::operator bool () const [inline], [explicit]
Quick status checking.
Returns:
Da sentry state.
For ease of use, sentries may be converted ta booleans. Da return value is dat of tha sentry state (true == aiiight).
Definizzle at line 705 of file istream.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.