" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::numpunct_byname< _CharT > -
SYNOPSIS
Inherits std::numpunct< _CharT >.
Public Types
typedef __numpunct_cache< _CharT > __cache_type
typedef _CharT char_type
typedef basic_string< _CharT > string_type
Public Member Functions
numpunct_byname (const char *__s, size_t __refs=0)
char_type decimal_point () const
string_type falsename () const
string grouping () const
char_type thousands_sep () const
string_type truename () const
Static Public Attributes
static locale::id id
Protected Member Functions
void _M_initialize_numpunct (__c_locale __cloc=0)
template<> void _M_initialize_numpunct (__c_locale __cloc)
template<> void _M_initialize_numpunct (__c_locale __cloc)
virtual char_type do_decimal_point () const
virtual string_type do_falsename () const
virtual string do_grouping () const
virtual char_type do_thousands_sep () const
virtual string_type do_truename () const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Protected Attributes
__cache_type * _M_data
Detailed Description
template<typename _CharT>class std::numpunct_byname< _CharT >
class numpunct_byname [22.2.3.2].
Definizzle at line 1874 of file locale_facets.h.
Member Function Documentation
template<typename _CharT > char_type std::numpunct< _CharT >::decimal_point () const [inline], [inherited]
Return decimal point character. This function returns a cold-ass lil char_type ta use as a thugged-out decimal point. Well shiiiit, it do so by returnin returnin numpunct<char_type>::do_decimal_point().
Returns:
char_type representin a thugged-out decimal point.
Definizzle at line 1707 of file locale_facets.h.
References std::numpunct< _CharT >::do_decimal_point().
template<typename _CharT > virtual char_type std::numpunct< _CharT >::do_decimal_point () const [inline], [protected], [virtual], [inherited]
Return decimal point character. Returns a cold-ass lil char_type ta use as a thugged-out decimal point. This function be a hook fo' derived classes ta chizzle tha value returned.
Returns:
char_type representin a thugged-out decimal point.
Definizzle at line 1794 of file locale_facets.h.
Referenced by std::numpunct< _CharT >::decimal_point().
template<typename _CharT > virtual string_type std::numpunct< _CharT >::do_falsename () const [inline], [protected], [virtual], [inherited]
Return strang representation of bool false. Returns a string_type containin tha text representation fo' false bool variables. This function be a hook fo' derived classes ta chizzle tha value returned.
Returns:
string_type representin printed form of false.
Definizzle at line 1845 of file locale_facets.h.
Referenced by std::numpunct< _CharT >::falsename().
template<typename _CharT > virtual string std::numpunct< _CharT >::do_groupin () const [inline], [protected], [virtual], [inherited]
Return groupin justification. Returns a strang representin groupings fo' tha integer part of a number. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
grouping() fo' details.
Returns:
Strin representin groupin justification.
Definizzle at line 1819 of file locale_facets.h.
Referenced by std::numpunct< _CharT >::grouping().
template<typename _CharT > virtual char_type std::numpunct< _CharT >::do_thousands_sep () const [inline], [protected], [virtual], [inherited]
Return thousandz separator character. Returns a cold-ass lil char_type ta use as a thousandz separator. This function be a hook fo' derived classes ta chizzle tha value returned.
Returns:
char_type representin a thousandz separator.
Definizzle at line 1806 of file locale_facets.h.
Referenced by std::numpunct< _CharT >::thousands_sep().
template<typename _CharT > virtual string_type std::numpunct< _CharT >::do_truename () const [inline], [protected], [virtual], [inherited]
Return strang representation of bool true. Returns a string_type containin tha text representation fo' legit bool variables. This function be a hook fo' derived classes ta chizzle tha value returned.
Returns:
string_type representin printed form of true.
Definizzle at line 1832 of file locale_facets.h.
Referenced by std::numpunct< _CharT >::truename().
template<typename _CharT > string_type std::numpunct< _CharT >::falsename () const [inline], [inherited]
Return strang representation of bool false. This function returns a string_type containin tha text representation fo' false bool variables. Well shiiiit, it do so by callin numpunct<char_type>::do_falsename().
Returns:
string_type representin printed form of false.
Definizzle at line 1777 of file locale_facets.h.
References std::numpunct< _CharT >::do_falsename().
template<typename _CharT > string std::numpunct< _CharT >::groupin () const [inline], [inherited]
Return groupin justification. This function returns a strang representin groupings fo' tha integer part of a number. Groupings indicate where thousandz separators should be banged up in tha integer part of a number.
Each char up in tha return strang is interpret as a integer rather than a cold-ass lil character. These numbers represent tha number of digits up in a group. Da first char up in tha strang represents tha number of digits up in tha least dope group. If a cold-ass lil char is negative, it indicates a unlimited number of digits fo' tha group. If mo' chars from tha strang is required ta crew a number, tha last char is used repeatedly.
For example, if tha grouping() returns '\003\002' n' be applied ta tha number 123456789, dis correspondz ta 12,34,56,789. Note dat if tha strang was '32', dis would put mo' than 50 digits tha fuck into tha least dope crew if tha characta set is ASCII.
Da strang is returned by callin numpunct<char_type>::do_grouping().
Returns:
strin representin groupin justification.
Definizzle at line 1751 of file locale_facets.h.
References std::numpunct< _CharT >::do_grouping().
template<typename _CharT > char_type std::numpunct< _CharT >::thousands_sep () const [inline], [inherited]
Return thousandz separator character. This function returns a cold-ass lil char_type ta use as a thousandz separator. Well shiiiit, it do so by returnin returnin numpunct<char_type>::do_thousands_sep().
Returns:
char_type representin a thousandz separator.
Definizzle at line 1720 of file locale_facets.h.
References std::numpunct< _CharT >::do_thousands_sep().
template<typename _CharT > string_type std::numpunct< _CharT >::truename () const [inline], [inherited]
Return strang representation of bool true. This function returns a string_type containin tha text representation fo' legit bool variables. Well shiiiit, it do so by callin numpunct<char_type>::do_truename().
Returns:
string_type representin printed form of true.
Definizzle at line 1764 of file locale_facets.h.
References std::numpunct< _CharT >::do_truename().
Member Data Documentation
template<typename _CharT > locale::id std::numpunct< _CharT >::id [static], [inherited]
Numpunct facet id.
Definizzle at line 1657 of file locale_facets.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.