" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::basic_string< _CharT, _Traits, _Alloc > -
SYNOPSIS
Public Types
typedef _Alloc allocator_type
typedef
__gnu_cxx::__normal_iterator
< const_pointer, basic_string > const_iterator"
typedef
_CharT_alloc_type::const_pointa const_pointer"
typedef
_CharT_alloc_type::const_reference const_reference"
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator"
typedef
_CharT_alloc_type::difference_type difference_type"
typedef
__gnu_cxx::__normal_iterator
< pointer, basic_string > iterator"
typedef _CharT_alloc_type::pointa pointer
typedef
_CharT_alloc_type::reference reference"
typedef std::reverse_iterator
< iterator > reverse_iterator"
typedef
_CharT_alloc_type::size_type size_type"
typedef _Traits traits_type
typedef _Traits::char_type value_type
Public Member Functions
basic_string ()
basic_string (const _Alloc &__a)
basic_string (const basic_string &__str)
basic_string (const basic_string &__str, size_type __pos, size_type __n=npos)
basic_string (const basic_string &__str, size_type __pos, size_type __n, const _Alloc &__a)
basic_string (const _CharT *__s, size_type __n, const _Alloc &__a=_Alloc())
basic_string (const _CharT *__s, const _Alloc &__a=_Alloc())
basic_string (size_type __n, _CharT __c, const _Alloc &__a=_Alloc())
basic_string (basic_string &&__str) noexcept
basic_string (initializer_list< _CharT > __l, const _Alloc &__a=_Alloc())
template<class _InputIterator > basic_string (_InputIterator __beg, _InputIterator __end, const _Alloc &__a=_Alloc())
~basic_string () noexcept
template<typename _InputIterator > basic_string< _CharT, _Traits,
_Alloc > & _M_replace_dispatch (iterator __i1, iterator __i2, _InputIterator __k1, _InputIterator __k2, __false_type)"
template<typename _InIterator > _CharT * _S_construct (_InIterator __beg, _InIterator __end, const _Alloc &__a, forward_iterator_tag)
basic_string & append (const basic_string &__str)
basic_string & append (const basic_string &__str, size_type __pos, size_type __n)
basic_string & append (const _CharT *__s, size_type __n)
basic_string & append (const _CharT *__s)
basic_string & append (size_type __n, _CharT __c)
basic_string & append (initializer_list< _CharT > __l)
template<class _InputIterator > basic_string & append (_InputIterator __first, _InputIterator __last)
basic_string & assign (const basic_string &__str)
basic_string & assign (basic_string &&__str)
basic_string & assign (const basic_string &__str, size_type __pos, size_type __n)
basic_string & assign (const _CharT *__s, size_type __n)
basic_string & assign (const _CharT *__s)
basic_string & assign (size_type __n, _CharT __c)
template<class _InputIterator > basic_string & assign (_InputIterator __first, _InputIterator __last)
basic_string & assign (initializer_list< _CharT > __l)
const_reference at (size_type __n) const
reference at (size_type __n)
reference back ()
const_reference back () const
iterator begin () noexcept
const_iterator begin () const noexcept
const _CharT * c_str () const noexcept
size_type capacity () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
int compare (const basic_string &__str) const
int compare (size_type __pos, size_type __n, const basic_string &__str) const
int compare (size_type __pos1, size_type __n1, const basic_string &__str, size_type __pos2, size_type __n2) const
int compare (const _CharT *__s) const
int compare (size_type __pos, size_type __n1, const _CharT *__s) const
int compare (size_type __pos, size_type __n1, const _CharT *__s, size_type __n2) const
size_type copy (_CharT *__s, size_type __n, size_type __pos=0) const
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
const _CharT * data () const noexcept
bool empty () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
basic_string & erase (size_type __pos=0, size_type __n=npos)
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
size_type find (const _CharT *__s, size_type __pos, size_type __n) const
size_type find (const basic_string &__str, size_type __pos=0) const noexcept
size_type find (const _CharT *__s, size_type __pos=0) const
size_type find (_CharT __c, size_type __pos=0) const noexcept
size_type find_first_not_of (const basic_string &__str, size_type __pos=0) const noexcept
size_type find_first_not_of (const _CharT *__s, size_type __pos, size_type __n) const
size_type find_first_not_of (const _CharT *__s, size_type __pos=0) const
size_type find_first_not_of (_CharT __c, size_type __pos=0) const noexcept
size_type find_first_of (const basic_string &__str, size_type __pos=0) const noexcept
size_type find_first_of (const _CharT *__s, size_type __pos, size_type __n) const
size_type find_first_of (const _CharT *__s, size_type __pos=0) const
size_type find_first_of (_CharT __c, size_type __pos=0) const noexcept
size_type find_last_not_of (const basic_string &__str, size_type __pos=npos) const noexcept
size_type find_last_not_of (const _CharT *__s, size_type __pos, size_type __n) const
size_type find_last_not_of (const _CharT *__s, size_type __pos=npos) const
size_type find_last_not_of (_CharT __c, size_type __pos=npos) const noexcept
size_type find_last_of (const basic_string &__str, size_type __pos=npos) const noexcept
size_type find_last_of (const _CharT *__s, size_type __pos, size_type __n) const
size_type find_last_of (const _CharT *__s, size_type __pos=npos) const
size_type find_last_of (_CharT __c, size_type __pos=npos) const noexcept
reference front ()
const_reference front () const
allocator_type get_allocator () const noexcept
void insert (iterator __p, size_type __n, _CharT __c)
template<class _InputIterator > void insert (iterator __p, _InputIterator __beg, _InputIterator __end)
void insert (iterator __p, initializer_list< _CharT > __l)
basic_string & insert (size_type __pos1, const basic_string &__str)
basic_string & insert (size_type __pos1, const basic_string &__str, size_type __pos2, size_type __n)
basic_string & insert (size_type __pos, const _CharT *__s, size_type __n)
basic_string & insert (size_type __pos, const _CharT *__s)
basic_string & insert (size_type __pos, size_type __n, _CharT __c)
iterator insert (iterator __p, _CharT __c)
size_type length () const noexcept
size_type max_size () const noexcept
basic_string & operator+= (const basic_string &__str)
basic_string & operator+= (const _CharT *__s)
basic_string & operator+= (_CharT __c)
basic_string & operator+= (initializer_list< _CharT > __l)
basic_string & operator= (const basic_string &__str)
basic_string & operator= (const _CharT *__s)
basic_string & operator= (_CharT __c)
basic_string & operator= (basic_string &&__str)
basic_string & operator= (initializer_list< _CharT > __l)
const_reference operator[] (size_type __pos) const
reference operator[] (size_type __pos)
void pop_back ()
void push_back (_CharT __c)
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
basic_string & replace (size_type __pos, size_type __n, const basic_string &__str)
basic_string & replace (size_type __pos1, size_type __n1, const basic_string &__str, size_type __pos2, size_type __n2)
basic_string & replace (size_type __pos, size_type __n1, const _CharT *__s, size_type __n2)
basic_string & replace (size_type __pos, size_type __n1, const _CharT *__s)
basic_string & replace (size_type __pos, size_type __n1, size_type __n2, _CharT __c)
basic_string & replace (iterator __i1, iterator __i2, const basic_string &__str)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__s, size_type __n)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__s)
basic_string & replace (iterator __i1, iterator __i2, size_type __n, _CharT __c)
template<class _InputIterator > basic_string & replace (iterator __i1, iterator __i2, _InputIterator __k1, _InputIterator __k2)
basic_string & replace (iterator __i1, iterator __i2, _CharT *__k1, _CharT *__k2)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__k1, const _CharT *__k2)
basic_string & replace (iterator __i1, iterator __i2, iterator __k1, iterator __k2)
basic_string & replace (iterator __i1, iterator __i2, const_iterator __k1, const_iterator __k2)
basic_string & replace (iterator __i1, iterator __i2, initializer_list< _CharT > __l)
void reserve (size_type __res_arg=0)
void resize (size_type __n, _CharT __c)
void resize (size_type __n)
size_type rfind (const basic_string &__str, size_type __pos=npos) const noexcept
size_type rfind (const _CharT *__s, size_type __pos, size_type __n) const
size_type rfind (const _CharT *__s, size_type __pos=npos) const
size_type rfind (_CharT __c, size_type __pos=npos) const noexcept
void shrink_to_fit ()
size_type size () const noexcept
basic_string substr (size_type __pos=0, size_type __n=npos) const
void swap (basic_string &__s)
Static Public Attributes
static const size_type npos
Detailed Description
template<typename _CharT, typename _Traits, typename _Alloc>class std::basic_string< _CharT, _Traits, _Alloc >
Managin sequencez of charactas n' character-like objects.
Template Parameters:
_CharT Type of characta
_Traits Traits fo' characta type, defaults ta char_traits<_CharT>.
_Alloc Allocator type, defaults ta allocator<_CharT>.
Meets tha requirementz of a container, a reversible container, n' a sequence. Of tha optionizzle sequence requirements, only push_back, at, n' array access is supported.
Todo
Needz documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Documentation, biatch? Whatz that, biatch? Nathan Myers ncm@cantrip.org.
A strang be lookin like this:
                                     [_Rep]
                                     _M_length
[basic_string<char_type>] _M_capacity
_M_dataplus _M_refcount
_M_p ----------------> unnamed array of char_type
Where tha _M_p points ta tha straight-up original gangsta characta up in tha string, n' you cast it ta a pointer-to-_Rep n' subtract 1 ta git a pointa ta tha header.
This approach has tha enormous advantage dat a strang object requires only one allocation fo' realz. All tha uglinizz is confined within a single pair of inline functions, which each compile ta a single add instruction: _Rep::_M_data(), n' string::_M_rep(); n' tha allocation function which gets a funky-ass block of raw bytes n' wit room enough n' constructs a _Rep object all up in tha front.
Da reason you want _M_data pointin ta tha characta array n' not tha _Rep is so dat tha debugger can peep tha strang contents. (Probably we should add a non-inline member ta git tha _Rep fo' tha debugger ta use, so playas can check tha actual strang length.)
Note dat tha _Rep object be a POD so dat you can gotz a static empty string _Rep object already constructed before static constructors have run. Da reference-count encodin is chosen so dat a 0 indicates one reference, so you never try ta destroy tha empty-strin _Rep object.
All but tha last paragraph is considered pretty conventionizzle fo' a C++ strang implementation.
Definizzle at line 112 of file basic_string.h.
Constructor & Destructor Documentation
template<typename _CharT, typename _Traits, typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string () [inline]
Default constructor creates a empty string.
Definizzle at line 437 of file basic_string.h.
Referenced by std::basic_string< char >::substr().
template<typename _CharT , typename _Traits , typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const _Alloc &__a) [explicit]
Construct a empty strang rockin allocator a.
Definizzle at line 178 of file basic_string.tcc.
template<typename _CharT , typename _Traits , typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const basic_string< _CharT, _Traits, _Alloc > &__str)
Construct strang wit copy of value of str.
Parameters:
__str Source string.
Definizzle at line 170 of file basic_string.tcc.
template<typename _CharT , typename _Traits , typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos, size_type__n = npos)
Construct strang as copy of a substring.
Parameters:
__str Source string.
__pos Index of first characta ta copy from.
__n Number of charactas ta copy (default remainder).
Definizzle at line 184 of file basic_string.tcc.
template<typename _CharT , typename _Traits , typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos, size_type__n, const _Alloc &__a)
Construct strang as copy of a substring.
Parameters:
__str Source string.
__pos Index of first characta ta copy from.
__n Number of charactas ta copy.
__a Allocator ta use.
Definizzle at line 194 of file basic_string.tcc.
template<typename _CharT, typename _Traits , typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const _CharT *__s, size_type__n, const _Alloc &__a = _Alloc())
Construct strang initialized by a cold-ass lil characta array.
Parameters:
__s Source characta array.
__n Number of charactas ta copy.
__a Allocator ta use (default is default allocator).
NB: __s must have at least __n characters, '\0' has no special meaning.
Definizzle at line 206 of file basic_string.tcc.
template<typename _CharT, typename _Traits , typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const _CharT *__s, const _Alloc &__a = _Alloc())
Construct strang as copy of a C string.
Parameters:
__s Source C string.
__a Allocator ta use (default is default allocator).
Definizzle at line 213 of file basic_string.tcc.
template<typename _CharT, typename _Traits , typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (size_type__n, _CharT__c, const _Alloc &__a = _Alloc())
Construct strang as multiple characters.
Parameters:
__n Number of characters.
__c Characta ta use.
__a Allocator ta use (default is default allocator).
Definizzle at line 220 of file basic_string.tcc.
template<typename _CharT, typename _Traits, typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (basic_string< _CharT, _Traits, _Alloc > &&__str) [inline], [noexcept]
Move construct string.
Parameters:
__str Source string.
Da newly-created strang gotz nuff tha exact contentz of __str. __str be a valid yo, but unspecified string.
Definizzle at line 507 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (initializer_list< _CharT >__l, const _Alloc &__a = _Alloc())
Construct strang from a initializer list.
Parameters:
__l std::initializer_list of characters.
__a Allocator ta use (default is default allocator).
Definizzle at line 235 of file basic_string.tcc.
template<typename _CharT , typename _Traits , typename _Alloc> template<typename _InputIterator > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (_InputIterator__beg, _InputIterator__end, const _Alloc &__a = _Alloc())
Construct strang as copy of a range.
Parameters:
__beg Start of range.
__end End of range.
__a Allocator ta use (default is default allocator).
Definizzle at line 228 of file basic_string.tcc.
template<typename _CharT, typename _Traits, typename _Alloc> std::basic_string< _CharT, _Traits, _Alloc >::~basic_string () [inline], [noexcept]
Destroy tha strang instance.
Definizzle at line 538 of file basic_string.h.
Member Function Documentation
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::append (const basic_string< _CharT, _Traits, _Alloc > &__str)
Append a strang ta dis string.
Parameters:
__str Da strang ta append.
Returns:
Reference ta dis string.
Definizzle at line 325 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::size(), n' std::size().
Referenced by std::basic_string< char >::append(), std::collate< _CharT >::do_transform(), std::operator+(), std::basic_string< char >::operator+=(), n' std::operator>>().
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::append (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos, size_type__n)
Append a substring.
Parameters:
__str Da strang ta append.
__pos Index of tha straight-up original gangsta characta of str ta append.
__n Da number of charactas ta append.
Returns:
Reference ta dis string.
Exceptions:
std::out_of_range if __pos aint a valid index.
This function appendz __n charactas from __str startin at __pos ta dis string. If __n is is larger than tha number of available charactas up in __str, tha remainder of __str be appended.
Definizzle at line 342 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::append (const _CharT *__s, size_type__n)
Append a C substring.
Parameters:
__s Da C strang ta append.
__n Da number of charactas ta append.
Returns:
Reference ta dis string.
Definizzle at line 298 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::append (const _CharT *__s) [inline]
Append a C string.
Parameters:
__s Da C strang ta append.
Returns:
Reference ta dis string.
Definizzle at line 1006 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::append (size_type__n, _CharT__c)
Append multiple characters.
Parameters:
__n Da number of charactas ta append.
__c Da characta ta use.
Returns:
Reference ta dis string.
Appendz __n copiez of __c ta dis string.
Definizzle at line 281 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::append (initializer_list< _CharT >__l) [inline]
Append a initializer_list of characters.
Parameters:
__l Da initializer_list of charactas ta append.
Returns:
Reference ta dis string.
Definizzle at line 1030 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> template<class _InputIterator > basic_string& std::basic_string< _CharT, _Traits, _Alloc >::append (_InputIterator__first, _InputIterator__last) [inline]
Append a range of characters.
Parameters:
__first Iterator referencin tha straight-up original gangsta characta ta append.
__last Iterator markin tha end of tha range.
Returns:
Reference ta dis string.
Appendz charactas up in tha range [__first,__last) ta dis string.
Definizzle at line 1044 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::assign (const basic_string< _CharT, _Traits, _Alloc > &__str)
Set value ta contentz of another string.
Parameters:
__str Source strang ta use.
Returns:
Reference ta dis string.
Definizzle at line 243 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::get_allocator().
Referenced by std::basic_string< char >::assign(), std::basic_string< char >::operator=(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::overflow(), n' std::basic_stringbuf< _CharT, _Traits, _Alloc >::str().
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::assign (basic_string< _CharT, _Traits, _Alloc > &&__str) [inline]
Set value ta contentz of another string.
Parameters:
__str Source strang ta use.
Returns:
Reference ta dis string.
This function sets dis strang ta tha exact contentz of __str. __str be a valid yo, but unspecified string.
Definizzle at line 1079 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::assign (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos, size_type__n) [inline]
Set value ta a substrin of a string.
Parameters:
__str Da strang ta use.
__pos Index of tha straight-up original gangsta characta of str.
__n Number of charactas ta use.
Returns:
Reference ta dis string.
Exceptions:
std::out_of_range if pos aint a valid index.
This function sets dis strang ta tha substrin of __str consistin of __n charactas at __pos. If __n is is larger than tha number of available charactas up in __str, tha remainder of __str is used.
Definizzle at line 1100 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::assign (const _CharT *__s, size_type__n)
Set value ta a C substring.
Parameters:
__s Da C strang ta use.
__n Number of charactas ta use.
Returns:
Reference ta dis string.
This function sets tha value of dis strang ta tha straight-up original gangsta __n charactaz of __s. If __n is is larger than tha number of available charactas up in __s, tha remainder of __s is used.
Definizzle at line 259 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::assign (const _CharT *__s) [inline]
Set value ta contentz of a C string.
Parameters:
__s Da C strang ta use.
Returns:
Reference ta dis string.
This function sets tha value of dis strang ta tha value of __s. Da data is copied, so there is no dependence on __s once tha function returns.
Definizzle at line 1128 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::assign (size_type__n, _CharT__c) [inline]
Set value ta multiple characters.
Parameters:
__n Length of tha resultin string.
__c Da characta ta use.
Returns:
Reference ta dis string.
This function sets tha value of dis strang ta __n copiez of characta __c.
Definizzle at line 1144 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> template<class _InputIterator > basic_string& std::basic_string< _CharT, _Traits, _Alloc >::assign (_InputIterator__first, _InputIterator__last) [inline]
Set value ta a range of characters.
Parameters:
__first Iterator referencin tha straight-up original gangsta characta ta append.
__last Iterator markin tha end of tha range.
Returns:
Reference ta dis string.
Sets value of strang ta charactas up in tha range [__first,__last).
Definizzle at line 1157 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::assign (initializer_list< _CharT >__l) [inline]
Set value ta a initializer_list of characters.
Parameters:
__l Da initializer_list of charactas ta assign.
Returns:
Reference ta dis string.
Definizzle at line 1167 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const_reference std::basic_string< _CharT, _Traits, _Alloc >::at (size_type__n) const [inline]
Provides access ta tha data contained up in tha string.
Parameters:
__n Da index of tha characta ta access.
Returns:
Read-only (const) reference ta tha character.
Exceptions:
std::out_of_range If n be a invalid index.
This function serves up fo' less thuggy data access. Da parameta is first checked dat it is up in tha range of tha string. Da function throws out_of_range if tha check fails.
Definizzle at line 864 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> reference std::basic_string< _CharT, _Traits, _Alloc >::at (size_type__n) [inline]
Provides access ta tha data contained up in tha string.
Parameters:
__n Da index of tha characta ta access.
Returns:
Read/write reference ta tha character.
Exceptions:
std::out_of_range If n be a invalid index.
This function serves up fo' less thuggy data access. Da parameta is first checked dat it is up in tha range of tha string. Da function throws out_of_range if tha check fails. Right back up in yo muthafuckin ass. Success thangs up in dis biatch up in unsharin tha string.
Definizzle at line 883 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> reference std::basic_string< _CharT, _Traits, _Alloc >::back () [inline]
Returns a read/write reference ta tha data all up in tha last element of tha string.
Definizzle at line 913 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const_reference std::basic_string< _CharT, _Traits, _Alloc >::back () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha last element of tha string.
Definizzle at line 921 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> iterator std::basic_string< _CharT, _Traits, _Alloc >::begin () [inline], [noexcept]
Returns a read/write iterator dat points ta tha straight-up original gangsta characta up in tha string. Unshares tha string.
Definizzle at line 605 of file basic_string.h.
Referenced by std::basic_string< char >::crend(), std::regex_match(), std::regex_replace(), std::regex_search(), n' std::basic_string< char >::rend().
template<typename _CharT, typename _Traits, typename _Alloc> const_iterator std::basic_string< _CharT, _Traits, _Alloc >::begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta characta up in tha string.
Definizzle at line 616 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const _CharT* std::basic_string< _CharT, _Traits, _Alloc >::c_str () const [inline], [noexcept]
Return const pointa ta null-terminated contents. This be a handle ta internal data. Do not modify or dire thangs may happen.
Definizzle at line 1800 of file basic_string.h.
Referenced by std::collate< _CharT >::do_compare(), std::money_get< _CharT, _InIta >::do_get(), std::num_get< _CharT, _InIta >::do_get(), std::collate< _CharT >::do_transform(), std::basic_filebuf< char_type, traits_type >::open(), n' std::operator==().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::capacitizzle () const [inline], [noexcept]
Returns tha total number of charactas dat tha strang can hold before needin ta allocate mo' memory.
Definizzle at line 776 of file basic_string.h.
Referenced by std::basic_string< char >::push_back(), n' std::basic_string< char >::shrink_to_fit().
template<typename _CharT, typename _Traits, typename _Alloc> const_iterator std::basic_string< _CharT, _Traits, _Alloc >::cbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta characta up in tha string.
Definizzle at line 680 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const_iterator std::basic_string< _CharT, _Traits, _Alloc >::cend () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last characta up in tha string.
Definizzle at line 688 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> void std::basic_string< _CharT, _Traits, _Alloc >::clear () [inline], [noexcept]
Erases tha string, makin it empty.
Definizzle at line 803 of file basic_string.h.
Referenced by std::basic_stringbuf< _CharT, _Traits, _Alloc >::setbuf().
template<typename _CharT, typename _Traits, typename _Alloc> int std::basic_string< _CharT, _Traits, _Alloc >::compare (const basic_string< _CharT, _Traits, _Alloc > &__str) const [inline]
Compare ta a string.
Parameters:
__str Strin ta compare against.
Returns:
Integer < 0, 0, or > 0.
Returns a integer < 0 if dis strang is ordered before __str, 0 if they joints is equivalent, or > 0 if dis strang is ordered afta __str. Determines tha effectizzle length rlen of tha strings ta compare as tha smallest of size() n' str.size(). Da function then compares tha two strings by callin traits::compare(data(), str.data(),rlen). If tha result of tha comparison is nonzero returns it, otherwise tha shorta one is ordered first.
Definizzle at line 2225 of file basic_string.h.
Referenced by std::sub_match< _Bi_ita >::compare(), std::operator<(), std::operator<=(), std::operator==(), std::operator>(), n' std::operator>=().
template<typename _CharT , typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type__pos, size_type__n, const basic_string< _CharT, _Traits, _Alloc > &__str) const
Compare substrin ta a string.
Parameters:
__pos Index of first characta of substring.
__n Number of charactas up in substring.
__str Strin ta compare against.
Returns:
Integer < 0, 0, or > 0.
Form tha substrin of dis strang from tha __n charactas startin at __pos. Returns a integer < 0 if tha substrin is ordered before __str, 0 if they joints is equivalent, or > 0 if tha substrin is ordered afta __str. Determines tha effectizzle length rlen of tha strings ta compare as tha smallest of tha length of tha substrin n' __str.size(). Da function then compares tha two strings by callin traits::compare(substring.data(),str.data(),rlen). If tha result of tha comparison is nonzero returns it, otherwise tha shorta one is ordered first.
Definizzle at line 916 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), std::min(), n' std::basic_string< _CharT, _Traits, _Alloc >::size().
template<typename _CharT , typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type__pos1, size_type__n1, const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos2, size_type__n2) const
Compare substrin ta a substring.
Parameters:
__pos1 Index of first characta of substring.
__n1 Number of charactas up in substring.
__str Strin ta compare against.
__pos2 Index of first characta of substrin of str.
__n2 Number of charactas up in substrin of str.
Returns:
Integer < 0, 0, or > 0.
Form tha substrin of dis strang from tha __n1 charactas startin at __pos1. Form tha substrin of __str from tha __n2 charactas startin at __pos2. Returns a integer < 0 if dis substrin is ordered before tha substrin of __str, 0 if they joints is equivalent, or > 0 if dis substrin is ordered afta tha substrin of __str. Determines tha effectizzle length rlen of tha strings ta compare as tha smallest of tha lengthz of tha substrings. Da function then compares tha two strings by callin traits::compare(substring.data(),str.substr(pos2,n2).data(),rlen). If tha result of tha comparison is nonzero returns it, otherwise tha shorta one is ordered first.
Definizzle at line 931 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), n' std::min().
template<typename _CharT, typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (const _CharT *__s) const
Compare ta a C string.
Parameters:
__s C strang ta compare against.
Returns:
Integer < 0, 0, or > 0.
Returns a integer < 0 if dis strang is ordered before __s, 0 if they joints is equivalent, or > 0 if dis strang is ordered afta __s. Determines tha effectizzle length rlen of tha strings ta compare as tha smallest of size() n' tha length of a strang constructed from __s. Da function then compares tha two strings by callin traits::compare(data(),s,rlen). If tha result of tha comparison is nonzero returns it, otherwise tha shorta one is ordered first.
Definizzle at line 949 of file basic_string.tcc.
References std::min(), n' std::size().
template<typename _CharT, typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type__pos, size_type__n1, const _CharT *__s) const
Compare substrin ta a C string.
Parameters:
__pos Index of first characta of substring.
__n1 Number of charactas up in substring.
__s C strang ta compare against.
Returns:
Integer < 0, 0, or > 0.
Form tha substrin of dis strang from tha __n1 charactas startin at pos. Returns a integer < 0 if tha substrin is ordered before __s, 0 if they joints is equivalent, or > 0 if tha substrin is ordered afta __s. Determines tha effectizzle length rlen of tha strings ta compare as tha smallest of tha length of tha substrin n' tha length of a strang constructed from __s. Da function then compares tha two strang by callin traits::compare(substring.data(),__s,rlen). If tha result of tha comparison is nonzero returns it, otherwise tha shorta one is ordered first.
Definizzle at line 964 of file basic_string.tcc.
References std::min().
template<typename _CharT, typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type__pos, size_type__n1, const _CharT *__s, size_type__n2) const
Compare substrin against a cold-ass lil characta array.
Parameters:
__pos Index of first characta of substring.
__n1 Number of charactas up in substring.
__s characta array ta compare against.
__n2 Number of charactaz of s.
Returns:
Integer < 0, 0, or > 0.
Form tha substrin of dis strang from tha __n1 charactas startin at __pos. Form a strang from tha straight-up original gangsta __n2 charactaz of __s. Returns a integer < 0 if dis substrin is ordered before tha strang from __s, 0 if they joints is equivalent, or > 0 if dis substrin is ordered afta tha strang from __s. Determines tha effectizzle length rlen of tha strings ta compare as tha smallest of tha length of tha substrin n' __n2. Da function then compares tha two strings by callin traits::compare(substring.data(),s,rlen). If tha result of tha comparison is nonzero returns it, otherwise tha shorta one is ordered first.
NB: s must have at least n2 characters, '\0' has no special meaning.
Definizzle at line 980 of file basic_string.tcc.
References std::min().
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::copy (_CharT *__s, size_type__n, size_type__pos = 0) const
Copy substrin tha fuck into C string.
Parameters:
__s C strang ta copy value into.
__n Number of charactas ta copy.
__pos Index of first characta ta copy.
Returns:
Number of charactas straight-up copied
Exceptions:
std::out_of_range If __pos > size().
Copies up ta __n charactas startin at __pos tha fuck into tha C strang __s. If __pos is pimped outa than size(), out_of_range is thrown.
Definizzle at line 723 of file basic_string.tcc.
template<typename _CharT, typename _Traits, typename _Alloc> const_reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::crbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last characta up in tha string. Iteration is done up in reverse element order.
Definizzle at line 697 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const_reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::crend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta characta up in tha string. Iteration is done up in reverse element order.
Definizzle at line 706 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const _CharT* std::basic_string< _CharT, _Traits, _Alloc >::data () const [inline], [noexcept]
Return const pointa ta contents. This be a handle ta internal data. Do not modify or dire thangs may happen.
Definizzle at line 1810 of file basic_string.h.
Referenced by std::basic_string< char >::compare(), std::basic_string< _CharT, _Traits, _Alloc >::compare(), std::collate< _CharT >::do_compare(), std::collate< _CharT >::do_transform(), std::basic_string< char >::find(), std::basic_string< char >::find_first_not_of(), std::basic_string< char >::find_last_of(), std::match_results< _FwdIterT, _Alloc >::format(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::str(), n' std::regex_traits< _Ch_type >::transform().
template<typename _CharT, typename _Traits, typename _Alloc> bool std::basic_string< _CharT, _Traits, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha strang is empty. Equivalent ta *this == ''.
Definizzle at line 811 of file basic_string.h.
Referenced by std::tr2::operator>>(), n' std::operator>>().
template<typename _CharT, typename _Traits, typename _Alloc> iterator std::basic_string< _CharT, _Traits, _Alloc >::end () [inline], [noexcept]
Returns a read/write iterator dat points one past tha last characta up in tha string. Unshares tha string.
Definizzle at line 624 of file basic_string.h.
Referenced by std::basic_string< char >::crbegin(), std::basic_string< char >::rbegin(), std::regex_match(), std::regex_replace(), n' std::regex_search().
template<typename _CharT, typename _Traits, typename _Alloc> const_iterator std::basic_string< _CharT, _Traits, _Alloc >::end () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last characta up in tha string.
Definizzle at line 635 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::erase (size_type__pos = 0, size_type__n = npos) [inline]
Remove characters.
Parameters:
__pos Index of first characta ta remove (default 0).
__n Number of charactas ta remove (default remainder).
Returns:
Reference ta dis string.
Exceptions:
std::out_of_range If pos is beyond tha end of dis string.
Removes __n charactas from dis strang startin at __pos. Da length of tha strang is reduced by __n. If there be < __n charactas ta remove, tha remainder of tha strang is truncated. If __p is beyond end of string, out_of_range is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1362 of file basic_string.h.
Referenced by std::getline(), std::operator>>(), n' std::basic_string< char >::pop_back().
template<typename _CharT, typename _Traits, typename _Alloc> iterator std::basic_string< _CharT, _Traits, _Alloc >::erase (iterator__position) [inline]
Remove one character.
Parameters:
__position Iterator referencin tha characta ta remove.
Returns:
iterator referencin same location afta removal.
Removes tha characta at __position from dis string. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1378 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::iterator std::basic_string< _CharT, _Traits, _Alloc >::erase (iterator__first, iterator__last)
Remove a range of characters.
Parameters:
__first Iterator referencin tha straight-up original gangsta characta ta remove.
__last Iterator referencin tha end of tha range.
Returns:
Iterator referencin location of first afta removal.
Removes tha charactas up in tha range [first,last) from dis string. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 391 of file basic_string.tcc.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find (const _CharT *__s, size_type__pos, size_type__n) const
Find posizzle of a C substring.
Parameters:
__s C strang ta locate.
__pos Index of characta ta search from.
__n Number of charactas from s ta search for.
Returns:
Index of start of first occurrence.
Startin from __pos, searches forward fo' tha straight-up original gangsta __n charactas up in __s within dis string. If found, returns tha index where it begins. If not found, returns npos.
Definizzle at line 737 of file basic_string.tcc.
References std::size().
Referenced by std::basic_string< char >::find(), n' std::basic_string< char >::find_first_of().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos = 0) const [inline], [noexcept]
Find posizzle of a string.
Parameters:
__str Strin ta locate.
__pos Index of characta ta search from (default 0).
Returns:
Index of start of first occurrence.
Startin from __pos, searches forward fo' value of __str within dis string. If found, returns tha index where it begins. If not found, returns npos.
Definizzle at line 1846 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find (const _CharT *__s, size_type__pos = 0) const [inline]
Find posizzle of a C string.
Parameters:
__s C strang ta locate.
__pos Index of characta ta search from (default 0).
Returns:
Index of start of first occurrence.
Startin from __pos, searches forward fo' tha value of __s within dis string. If found, returns tha index where it begins. If not found, returns npos.
Definizzle at line 1861 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find (_CharT__c, size_type__pos = 0) const [noexcept]
Find posizzle of a cold-ass lil character.
Parameters:
__c Characta ta locate.
__pos Index of characta ta search from (default 0).
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' __c within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 760 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos = 0) const [inline], [noexcept]
Find posizzle of a cold-ass lil characta not up in string.
Parameters:
__str Strin containin charactas ta avoid.
__pos Index of characta ta search from (default 0).
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' a cold-ass lil characta not contained up in __str within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 2079 of file basic_string.h.
Referenced by std::basic_string< char >::find_first_not_of().
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (const _CharT *__s, size_type__pos, size_type__n) const
Find posizzle of a cold-ass lil characta not up in C substring.
Parameters:
__s C strang containin charactas ta avoid.
__pos Index of characta ta search from.
__n Number of charactas from __s ta consider.
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' a cold-ass lil characta not contained up in tha straight-up original gangsta __n charactaz of __s within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 852 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (const _CharT *__s, size_type__pos = 0) const [inline]
Find posizzle of a cold-ass lil characta not up in C string.
Parameters:
__s C strang containin charactas ta avoid.
__pos Index of characta ta search from (default 0).
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' a cold-ass lil characta not contained up in __s within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 2110 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (_CharT__c, size_type__pos = 0) const [noexcept]
Find posizzle of a gangbangin' finger-lickin' different character.
Parameters:
__c Characta ta avoid.
__pos Index of characta ta search from (default 0).
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' a cold-ass lil characta other than __c within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 864 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos = 0) const [inline], [noexcept]
Find posizzle of a cold-ass lil characta of string.
Parameters:
__str Strin containin charactas ta locate.
__pos Index of characta ta search from (default 0).
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' one of tha charactaz of __str within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 1952 of file basic_string.h.
Referenced by std::basic_string< char >::find_first_of().
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (const _CharT *__s, size_type__pos, size_type__n) const
Find posizzle of a cold-ass lil characta of C substring.
Parameters:
__s Strin containin charactas ta locate.
__pos Index of characta ta search from.
__n Number of charactas from s ta search for.
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' one of tha straight-up original gangsta __n charactaz of __s within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 816 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (const _CharT *__s, size_type__pos = 0) const [inline]
Find posizzle of a cold-ass lil characta of C string.
Parameters:
__s Strin containin charactas ta locate.
__pos Index of characta ta search from (default 0).
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' one of tha charactaz of __s within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 1982 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (_CharT__c, size_type__pos = 0) const [inline], [noexcept]
Find posizzle of a cold-ass lil character.
Parameters:
__c Characta ta locate.
__pos Index of characta ta search from (default 0).
Returns:
Index of first occurrence.
Startin from __pos, searches forward fo' tha characta __c within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Note: equivalent ta find(__c, __pos).
Definizzle at line 2001 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos = npos) const [inline], [noexcept]
Find last posizzle of a cold-ass lil characta not up in string.
Parameters:
__str Strin containin charactas ta avoid.
__pos Index of characta ta search back from (default end).
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' a cold-ass lil characta not contained up in __str within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 2142 of file basic_string.h.
Referenced by std::basic_string< char >::find_last_not_of().
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (const _CharT *__s, size_type__pos, size_type__n) const
Find last posizzle of a cold-ass lil characta not up in C substring.
Parameters:
__s C strang containin charactas ta avoid.
__pos Index of characta ta search back from.
__n Number of charactas from s ta consider.
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' a cold-ass lil characta not contained up in tha straight-up original gangsta __n charactaz of __s within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 875 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (const _CharT *__s, size_type__pos = npos) const [inline]
Find last posizzle of a cold-ass lil characta not up in C string.
Parameters:
__s C strang containin charactas ta avoid.
__pos Index of characta ta search back from (default end).
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' a cold-ass lil characta not contained up in __s within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 2173 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (_CharT__c, size_type__pos = npos) const [noexcept]
Find last posizzle of a gangbangin' finger-lickin' different character.
Parameters:
__c Characta ta avoid.
__pos Index of characta ta search back from (default end).
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' a cold-ass lil characta other than __c within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 896 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos = npos) const [inline], [noexcept]
Find last posizzle of a cold-ass lil characta of string.
Parameters:
__str Strin containin charactas ta locate.
__pos Index of characta ta search back from (default end).
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' one of tha charactaz of __str within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 2016 of file basic_string.h.
Referenced by std::basic_string< char >::find_last_of().
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (const _CharT *__s, size_type__pos, size_type__n) const
Find last posizzle of a cold-ass lil characta of C substring.
Parameters:
__s C strang containin charactas ta locate.
__pos Index of characta ta search back from.
__n Number of charactas from s ta search for.
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' one of tha straight-up original gangsta __n charactaz of __s within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 831 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (const _CharT *__s, size_type__pos = npos) const [inline]
Find last posizzle of a cold-ass lil characta of C string.
Parameters:
__s C strang containin charactas ta locate.
__pos Index of characta ta search back from (default end).
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' one of tha charactaz of __s within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 2046 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (_CharT__c, size_type__pos = npos) const [inline], [noexcept]
Find last posizzle of a cold-ass lil character.
Parameters:
__c Characta ta locate.
__pos Index of characta ta search back from (default end).
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' __c within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Note: equivalent ta rfind(__c, __pos).
Definizzle at line 2065 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> reference std::basic_string< _CharT, _Traits, _Alloc >::front () [inline]
Returns a read/write reference ta tha data all up in tha straight-up original gangsta element of tha string.
Definizzle at line 897 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const_reference std::basic_string< _CharT, _Traits, _Alloc >::front () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha straight-up original gangsta element of tha string.
Definizzle at line 905 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> allocator_type std::basic_string< _CharT, _Traits, _Alloc >::get_allocator () const [inline], [noexcept]
Return copy of allocator used ta construct dis string.
Definizzle at line 1817 of file basic_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::assign(), std::basic_string< char >::basic_string(), std::basic_string< _CharT, _Traits, _Alloc >::swap(), n' std::basic_string< char >::~basic_string().
template<typename _CharT, typename _Traits, typename _Alloc> void std::basic_string< _CharT, _Traits, _Alloc >::insert (iterator__p, size_type__n, _CharT__c) [inline]
Insert multiple characters.
Parameters:
__p Iterator referencin location up in strang ta bang at.
__n Number of charactas ta bang
__c Da characta ta insert.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Inserts __n copiez of characta __c startin all up in tha posizzle referenced by iterator __p. If addin charactas causes tha length ta exceed max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1185 of file basic_string.h.
Referenced by std::basic_string< char >::insert().
template<typename _CharT, typename _Traits, typename _Alloc> template<class _InputIterator > void std::basic_string< _CharT, _Traits, _Alloc >::insert (iterator__p, _InputIterator__beg, _InputIterator__end) [inline]
Insert a range of characters.
Parameters:
__p Iterator referencin location up in strang ta bang at.
__beg Start of range.
__end End of range.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Inserts charactas up in range [__beg,__end). If addin charactas causes tha length ta exceed max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1202 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> void std::basic_string< _CharT, _Traits, _Alloc >::insert (iterator__p, initializer_list< _CharT >__l) [inline]
Insert a initializer_list of characters.
Parameters:
__p Iterator referencin location up in strang ta bang at.
__l Da initializer_list of charactas ta insert.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Definizzle at line 1213 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type__pos1, const basic_string< _CharT, _Traits, _Alloc > &__str) [inline]
Insert value of a string.
Parameters:
__pos1 Iterator referencin location up in strang ta bang at.
__str Da strang ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Inserts value of __str startin at __pos1. If addin charactas causes tha length ta exceed max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1233 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type__pos1, const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos2, size_type__n) [inline]
Insert a substring.
Parameters:
__pos1 Iterator referencin location up in strang ta bang at.
__str Da strang ta insert.
__pos2 Start of charactas up in str ta insert.
__n Number of charactas ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
std::out_of_range If pos1 > size() or __pos2 > str.size().
Startin at pos1, bang __n characta of __str beginnin wit __pos2. If addin charactas causes tha length ta exceed max_size(), length_error is thrown. If __pos1 is beyond tha end of dis strang or __pos2 is beyond tha end of __str, out_of_range is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1255 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type__pos, const _CharT *__s, size_type__n)
Insert a C substring.
Parameters:
__pos Iterator referencin location up in strang ta bang at.
__s Da C strang ta insert.
__n Da number of charactas ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
std::out_of_range If __pos is beyond tha end of dis string.
Inserts tha straight-up original gangsta __n charactaz of __s startin at __pos. If addin charactas causes tha length ta exceed max_size(), length_error is thrown. If __pos is beyond end(), out_of_range is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 360 of file basic_string.tcc.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type__pos, const _CharT *__s) [inline]
Insert a C string.
Parameters:
__pos Iterator referencin location up in strang ta bang at.
__s Da C strang ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
std::out_of_range If pos is beyond tha end of dis string.
Inserts tha straight-up original gangsta n charactaz of __s startin at __pos. If addin charactas causes tha length ta exceed max_size(), length_error is thrown. If __pos is beyond end(), out_of_range is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1296 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type__pos, size_type__n, _CharT__c) [inline]
Insert multiple characters.
Parameters:
__pos Index up in strang ta bang at.
__n Number of charactas ta bang
__c Da characta ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
std::out_of_range If __pos is beyond tha end of dis string.
Inserts __n copiez of characta __c startin at index __pos. If addin charactas causes tha length ta exceed max_size(), length_error is thrown. If __pos > length(), out_of_range is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1319 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> iterator std::basic_string< _CharT, _Traits, _Alloc >::insert (iterator__p, _CharT__c) [inline]
Insert one character.
Parameters:
__p Iterator referencin posizzle up in strang ta bang at.
__c Da characta ta insert.
Returns:
Iterator referencin newly banged char.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Inserts characta __c at posizzle referenced by __p. If addin characta causes tha length ta exceed max_size(), length_error is thrown. If __p is beyond end of string, out_of_range is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1337 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::length () const [inline], [noexcept]
Returns tha number of charactas up in tha string, not includin any null-termination.
Definizzle at line 721 of file basic_string.h.
Referenced by std::collate< _CharT >::do_compare(), n' std::collate< _CharT >::do_transform().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::max_size () const [inline], [noexcept]
Returns tha size() of tha phattest possible string.
Definizzle at line 726 of file basic_string.h.
Referenced by std::getline(), n' std::operator>>().
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator+= (const basic_string< _CharT, _Traits, _Alloc > &__str) [inline]
Append a strang ta dis string.
Parameters:
__str Da strang ta append.
Returns:
Reference ta dis string.
Definizzle at line 932 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator+= (const _CharT *__s) [inline]
Append a C string.
Parameters:
__s Da C strang ta append.
Returns:
Reference ta dis string.
Definizzle at line 941 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator+= (_CharT__c) [inline]
Append a cold-ass lil character.
Parameters:
__c Da characta ta append.
Returns:
Reference ta dis string.
Definizzle at line 950 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator+= (initializer_list< _CharT >__l) [inline]
Append a initializer_list of characters.
Parameters:
__l Da initializer_list of charactas ta be appended.
Returns:
Reference ta dis string.
Definizzle at line 963 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator= (const basic_string< _CharT, _Traits, _Alloc > &__str) [inline]
Assign tha value of str ta dis string.
Parameters:
__str Source string.
Definizzle at line 546 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator= (const _CharT *__s) [inline]
Copy contentz of s tha fuck into dis string.
Parameters:
__s Source null-terminated string.
Definizzle at line 554 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator= (_CharT__c) [inline]
Set value ta strang of length 1.
Parameters:
__c Source character.
Assignin ta a cold-ass lil characta make dis strang length 1 n' (*this)[0] == c.
Definizzle at line 565 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator= (basic_string< _CharT, _Traits, _Alloc > &&__str) [inline]
Move assign tha value of str ta dis string.
Parameters:
__str Source string.
Da contentz of str is moved tha fuck into dis strang (without copying). str be a valid yo, but unspecified string.
Definizzle at line 580 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::operator= (initializer_list< _CharT >__l) [inline]
Set value ta strang constructed from initializer list.
Parameters:
__l std::initializer_list.
Definizzle at line 592 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const_reference std::basic_string< _CharT, _Traits, _Alloc >::operator[] (size_type__pos) const [inline]
Subscript access ta tha data contained up in tha string.
Parameters:
__pos Da index of tha characta ta access.
Returns:
Read-only (constant) reference ta tha character.
This operator allows fo' easy as fuck , array-style, data access. Note dat data access wit dis operator is unchecked n' out_of_range lookups is not defined. (For checked lookups peep at().)
Definizzle at line 826 of file basic_string.h.
Referenced by std::basic_string< char >::back(), n' std::basic_string< char >::front().
template<typename _CharT, typename _Traits, typename _Alloc> reference std::basic_string< _CharT, _Traits, _Alloc >::operator[] (size_type__pos) [inline]
Subscript access ta tha data contained up in tha string.
Parameters:
__pos Da index of tha characta ta access.
Returns:
Read/write reference ta tha character.
This operator allows fo' easy as fuck , array-style, data access. Note dat data access wit dis operator is unchecked n' out_of_range lookups is not defined. (For checked lookups peep at().) Unshares tha string.
Definizzle at line 843 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> void std::basic_string< _CharT, _Traits, _Alloc >::pop_back () [inline]
Remove tha last character. Da strang must be non-empty.
Definizzle at line 1407 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> void std::basic_string< _CharT, _Traits, _Alloc >::push_back (_CharT__c) [inline]
Append a single character.
Parameters:
__c Characta ta append.
Definizzle at line 1052 of file basic_string.h.
Referenced by std::collate< _CharT >::do_transform(), std::basic_string< char >::operator+=(), std::tr2::operator>>(), std::operator>>(), n' std::basic_stringbuf< _CharT, _Traits, _Alloc >::overflow().
template<typename _CharT, typename _Traits, typename _Alloc> reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::rbegin () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta tha last characta up in tha string. Iteration is done up in reverse element order. Unshares tha string.
Definizzle at line 644 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const_reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::rbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last characta up in tha string. Iteration is done up in reverse element order.
Definizzle at line 653 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::rend () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta one before tha straight-up original gangsta characta up in tha string. Iteration is done up in reverse element order. Unshares tha string.
Definizzle at line 662 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> const_reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::rend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta characta up in tha string. Iteration is done up in reverse element order.
Definizzle at line 671 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type__pos, size_type__n, const basic_string< _CharT, _Traits, _Alloc > &__str) [inline]
Replace charactas wit value from another string.
Parameters:
__pos Index of first characta ta replace.
__n Number of charactas ta be replaced.
__str Strin ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::out_of_range If pos is beyond tha end of dis string.
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__pos,__pos+__n) from dis string. In place, tha value of __str is inserted. If __pos is beyond end of string, out_of_range is thrown. If tha length of tha result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1429 of file basic_string.h.
Referenced by std::basic_string< char >::append(), std::basic_string< char >::assign(), std::basic_string< char >::insert(), n' std::basic_string< char >::replace().
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type__pos1, size_type__n1, const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos2, size_type__n2) [inline]
Replace charactas wit value from another string.
Parameters:
__pos1 Index of first characta ta replace.
__n1 Number of charactas ta be replaced.
__str Strin ta insert.
__pos2 Index of first characta of str ta use.
__n2 Number of charactas from str ta use.
Returns:
Reference ta dis string.
Exceptions:
std::out_of_range If __pos1 > size() or __pos2 > __str.size().
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__pos1,__pos1 + n) from dis string. In place, tha value of __str is inserted. If __pos is beyond end of string, out_of_range is thrown. If tha length of tha result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1451 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type__pos, size_type__n1, const _CharT *__s, size_type__n2)
Replace charactas wit value of a C substring.
Parameters:
__pos Index of first characta ta replace.
__n1 Number of charactas ta be replaced.
__s C strang ta insert.
__n2 Number of charactas from s ta use.
Returns:
Reference ta dis string.
Exceptions:
std::out_of_range If pos1 > size().
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__pos,__pos + __n1) from dis string. In place, tha straight-up original gangsta __n2 charactaz of __s is inserted, or all of __s if __n2 is too large. If __pos is beyond end of string, out_of_range is thrown. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 414 of file basic_string.tcc.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type__pos, size_type__n1, const _CharT *__s) [inline]
Replace charactas wit value of a C string.
Parameters:
__pos Index of first characta ta replace.
__n1 Number of charactas ta be replaced.
__s C strang ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::out_of_range If pos > size().
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__pos,__pos + __n1) from dis string. In place, tha charactaz of __s is inserted. If __pos is beyond end of string, out_of_range is thrown. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1496 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type__pos, size_type__n1, size_type__n2, _CharT__c) [inline]
Replace charactas wit multiple characters.
Parameters:
__pos Index of first characta ta replace.
__n1 Number of charactas ta be replaced.
__n2 Number of charactas ta insert.
__c Characta ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::out_of_range If __pos > size().
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [pos,pos + n1) from dis string. In place, __n2 copiez of __c is inserted. If __pos is beyond end of string, out_of_range is thrown. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1520 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator__i1, iterator__i2, const basic_string< _CharT, _Traits, _Alloc > &__str) [inline]
Replace range of charactas wit string.
Parameters:
__i1 Iterator referencin start of range ta replace.
__i2 Iterator referencin end of range ta replace.
__str Strin value ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__i1,__i2). In place, tha value of __str is inserted. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1538 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator__i1, iterator__i2, const _CharT *__s, size_type__n) [inline]
Replace range of charactas wit C substring.
Parameters:
__i1 Iterator referencin start of range ta replace.
__i2 Iterator referencin end of range ta replace.
__s C strang value ta insert.
__n Number of charactas from s ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__i1,__i2). In place, tha straight-up original gangsta __n charactaz of __s is inserted. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1557 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator__i1, iterator__i2, const _CharT *__s) [inline]
Replace range of charactas wit C string.
Parameters:
__i1 Iterator referencin start of range ta replace.
__i2 Iterator referencin end of range ta replace.
__s C strang value ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__i1,__i2). In place, tha charactaz of __s is inserted. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1578 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator__i1, iterator__i2, size_type__n, _CharT__c) [inline]
Replace range of charactas wit multiple characters.
Parameters:
__i1 Iterator referencin start of range ta replace.
__i2 Iterator referencin end of range ta replace.
__n Number of charactas ta insert.
__c Characta ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__i1,__i2). In place, __n copiez of __c is inserted. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1599 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> template<class _InputIterator > basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator__i1, iterator__i2, _InputIterator__k1, _InputIterator__k2) [inline]
Replace range of charactas wit range.
Parameters:
__i1 Iterator referencin start of range ta replace.
__i2 Iterator referencin end of range ta replace.
__k1 Iterator referencin start of range ta insert.
__k2 Iterator referencin end of range ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__i1,__i2). In place, charactas up in tha range [__k1,__k2) is inserted. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1623 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> basic_string& std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator__i1, iterator__i2, initializer_list< _CharT >__l) [inline]
Replace range of charactas wit initializer_list.
Parameters:
__i1 Iterator referencin start of range ta replace.
__i2 Iterator referencin end of range ta replace.
__l Da initializer_list of charactas ta insert.
Returns:
Reference ta dis string.
Exceptions:
std::length_error If freshly smoked up length exceedz max_size().
Removes tha charactas up in tha range [__i1,__i2). In place, charactas up in tha range [__k1,__k2) is inserted. If tha length of result exceedz max_size(), length_error is thrown. Da value of tha strang don't chizzle if a error is thrown.
Definizzle at line 1692 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::reserve (size_type__res_arg = 0)
Attempt ta preallocate enough memory fo' specified number of characters.
Parameters:
__res_arg Number of charactas required.
Exceptions:
std::length_error If __res_arg exceedz max_size().
This function attempts ta reserve enough memory fo' tha strang ta hold tha specified number of characters. If tha number axed is mo' than max_size(), length_error is thrown.
Da advantage of dis function is dat if optimal code be a necessitizzle n' tha user can determine tha strang length dat is ghon be required, tha user can reserve tha memory up in advance, n' thus prevent a possible reallocation of memory n' copyin of strang data.
Definizzle at line 502 of file basic_string.tcc.
References std::size().
Referenced by std::num_get< _CharT, _InIta >::do_get(), std::tr2::operator>>(), std::operator>>(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::overflow(), std::basic_string< char >::push_back(), n' std::basic_string< char >::shrink_to_fit().
template<typename _CharT, typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::resize (size_type__n, _CharT__c)
Resizes tha strang ta tha specified number of characters.
Parameters:
__n Number of charactas tha strang should contain.
__c Characta ta fill any freshly smoked up elements.
This function will resize tha strang ta tha specified number of characters. If tha number is smalla than tha stringz current size tha strang is truncated, otherwise tha strang is extended n' freshly smoked up elements is set ta __c.
Definizzle at line 640 of file basic_string.tcc.
References std::size().
Referenced by std::money_get< _CharT, _InIta >::do_get(), n' std::basic_string< char >::resize().
template<typename _CharT, typename _Traits, typename _Alloc> void std::basic_string< _CharT, _Traits, _Alloc >::resize (size_type__n) [inline]
Resizes tha strang ta tha specified number of characters.
Parameters:
__n Number of charactas tha strang should contain.
This function will resize tha strang ta tha specified length. If tha freshly smoked up size is smalla than tha stringz current size tha strang is truncated, otherwise tha strang is extended n' freshly smoked up charactas is default-constructed. For basic types like fuckin char, dis means settin dem ta 0.
Definizzle at line 753 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::rfind (const basic_string< _CharT, _Traits, _Alloc > &__str, size_type__pos = npos) const [inline], [noexcept]
Find last posizzle of a string.
Parameters:
__str Strin ta locate.
__pos Index of characta ta search back from (default end).
Returns:
Index of start of last occurrence.
Startin from __pos, searches backward fo' value of __str within dis string. If found, returns tha index where it begins. If not found, returns npos.
Definizzle at line 1891 of file basic_string.h.
Referenced by std::basic_string< char >::find_last_of(), n' std::basic_string< char >::rfind().
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::rfind (const _CharT *__s, size_type__pos, size_type__n) const
Find last posizzle of a C substring.
Parameters:
__s C strang ta locate.
__pos Index of characta ta search back from.
__n Number of charactas from s ta search for.
Returns:
Index of start of last occurrence.
Startin from __pos, searches backward fo' tha straight-up original gangsta __n charactas up in __s within dis string. If found, returns tha index where it begins. If not found, returns npos.
Definizzle at line 778 of file basic_string.tcc.
References std::min(), n' std::size().
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::rfind (const _CharT *__s, size_type__pos = npos) const [inline]
Find last posizzle of a C string.
Parameters:
__s C strang ta locate.
__pos Index of characta ta start search at (default end).
Returns:
Index of start of last occurrence.
Startin from __pos, searches backward fo' tha value of __s within dis string. If found, returns tha index where it begins. If not found, returns npos.
Definizzle at line 1921 of file basic_string.h.
template<typename _CharT, typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::rfind (_CharT__c, size_type__pos = npos) const [noexcept]
Find last posizzle of a cold-ass lil character.
Parameters:
__c Characta ta locate.
__pos Index of characta ta search back from (default end).
Returns:
Index of last occurrence.
Startin from __pos, searches backward fo' __c within dis string. If found, returns tha index where dat shiznit was found. If not found, returns npos.
Definizzle at line 799 of file basic_string.tcc.
References std::size().
template<typename _CharT, typename _Traits, typename _Alloc> void std::basic_string< _CharT, _Traits, _Alloc >::shrink_to_fit () [inline]
A non-bindin request ta reduce capacity() ta size().
Definizzle at line 759 of file basic_string.h.
template<typename _CharT, typename _Traits, typename _Alloc> size_type std::basic_string< _CharT, _Traits, _Alloc >::size () const [inline], [noexcept]
Returns tha number of charactas up in tha string, not includin any null-termination.
Definizzle at line 715 of file basic_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< char >::assign(), std::basic_string< char >::at(), std::basic_string< char >::back(), std::basic_string< char >::cend(), std::basic_string< char >::clear(), std::basic_string< char >::compare(), std::basic_string< _CharT, _Traits, _Alloc >::compare(), std::tr2::dynamic_bitset< _WordT, _Alloc >::dynamic_bitset(), std::basic_string< char >::empty(), std::basic_string< char >::end(), std::basic_string< char >::find(), std::basic_string< char >::find_first_not_of(), std::basic_string< char >::find_last_of(), std::match_results< _FwdIterT, _Alloc >::format(), std::basic_string< char >::insert(), std::operator+(), std::tr2::operator>>(), std::basic_string< char >::operator[](), std::basic_string< char >::pop_back(), std::basic_string< char >::push_back(), std::basic_string< char >::replace(), std::basic_string< char >::shrink_to_fit(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::str(), n' std::regex_traits< _Ch_type >::transform().
template<typename _CharT, typename _Traits, typename _Alloc> basic_string std::basic_string< _CharT, _Traits, _Alloc >::substr (size_type__pos = 0, size_type__n = npos) const [inline]
Git a substring.
Parameters:
__pos Index of first characta (default 0).
__n Number of charactas up in substrin (default remainder).
Returns:
Da freshly smoked up string.
Exceptions:
std::out_of_range If __pos > size().
Construct n' return a freshly smoked up strang rockin tha __n charactas startin at __pos. If tha strang is too short, use tha remainder of tha characters. If __pos is beyond tha end of tha string, out_of_range is thrown.
Definizzle at line 2206 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::swap (basic_string< _CharT, _Traits, _Alloc > &__s)
Swap contents wit another string.
Parameters:
__s Strin ta swap with.
Exchanges tha contentz of dis strang wit dat of __s up in constant time.
Definizzle at line 519 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::get_allocator().
Referenced by std::basic_string< char >::assign(), std::basic_string< char >::operator=(), n' std::swap().
Member Data Documentation
template<typename _CharT, typename _Traits, typename _Alloc> const basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::npos [static]
Value returned by various member functions when they fail.
Definizzle at line 285 of file basic_string.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.