" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::money_get< _CharT, _InIta > -
SYNOPSIS
Inherits std::locale::facet.
Public Types
typedef _CharT char_type
typedef _InIta iter_type
typedef basic_string< _CharT > string_type
Public Member Functions
money_get (size_t __refs=0)
template<bool _Intl> _InIta _M_extract (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, string &__units) const
iter_type get (iter_type __s, iter_type __end, bool __intl, ios_base &__io, ios_base::iostate &__err, long double &__units) const
iter_type get (iter_type __s, iter_type __end, bool __intl, ios_base &__io, ios_base::iostate &__err, string_type &__digits) const
Static Public Attributes
static locale::id id
Protected Member Functions
virtual ~money_get ()
template<bool _Intl> iter_type _M_extract (iter_type __s, iter_type __end, ios_base &__io, ios_base::iostate &__err, string &__digits) const
virtual iter_type do_get (iter_type __s, iter_type __end, bool __intl, ios_base &__io, ios_base::iostate &__err, long double &__units) const
virtual iter_type do_get (iter_type __s, iter_type __end, bool __intl, ios_base &__io, ios_base::iostate &__err, string_type &__digits) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Detailed Description
template<typename _CharT, typename _InIter>class std::money_get< _CharT, _InIta >
Primary class template scrilla_get.
This facet encapsulates tha code ta parse n' return a monetary amount from a string.
Da scrilla_get template uses protected virtual functions ta provide tha actual thangs up in dis biatch. Da hood accessors forward tha call ta tha virtual functions. These virtual functions is hooks fo' pimpers ta implement tha behavior they require from tha scrilla_get facet.
Definizzle at line 1370 of file locale_facets_nonio.h.
Member Typedef Documentation
template<typename _CharT , typename _InIta > typedef _CharT std::money_get< _CharT, _InIta >::char_type
Public typedefs.
Definizzle at line 1376 of file locale_facets_nonio.h.
template<typename _CharT , typename _InIta > typedef _InIta std::money_get< _CharT, _InIta >::iter_type
Public typedefs.
Definizzle at line 1377 of file locale_facets_nonio.h.
template<typename _CharT , typename _InIta > typedef basic_string<_CharT> std::money_get< _CharT, _InIta >::string_type
Public typedefs.
Definizzle at line 1378 of file locale_facets_nonio.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _InIta > std::money_get< _CharT, _InIta >::money_get (size_t__refs = 0) [inline], [explicit]
Constructor performs initialization. This is tha constructor provided by tha standard.
Parameters:
__refs Passed ta tha base facet class.
Definizzle at line 1392 of file locale_facets_nonio.h.
template<typename _CharT , typename _InIta > virtual std::money_get< _CharT, _InIta >::~money_get () [inline], [protected], [virtual]
Destructor.
Definizzle at line 1460 of file locale_facets_nonio.h.
Member Function Documentation
template<typename _CharT , typename _InIta > _InIta std::money_get< _CharT, _InIta >::do_get (iter_type__s, iter_type__end, bool__intl, ios_base &__io, ios_base::iostate &__err, long double &__units) const [protected], [virtual]
Read n' parse a monetary value. This function readz n' parses charactas representin a monetary value. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' details.
Definizzle at line 365 of file locale_facets_nonio.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::c_str().
Referenced by std::money_get< _CharT, _InIta >::get().
template<typename _CharT , typename _InIta > _InIta std::money_get< _CharT, _InIta >::do_get (iter_type__s, iter_type__end, bool__intl, ios_base &__io, ios_base::iostate &__err, string_type &__digits) const [protected], [virtual]
Read n' parse a monetary value. This function readz n' parses charactas representin a monetary value. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' details.
Definizzle at line 378 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), std::basic_string< _CharT, _Traits, _Alloc >::resize(), n' std::__ctype_abstract_base< _CharT >::widen().
template<typename _CharT , typename _InIta > iter_type std::money_get< _CharT, _InIta >::get (iter_type__s, iter_type__end, bool__intl, ios_base &__io, ios_base::iostate &__err, long double &__units) const [inline]
Read n' parse a monetary value. This function readz charactas from __s, interprets dem as a monetary value accordin ta scrillapunct n' ctype facets retrieved from io.getloc(), n' returns tha result up in units as a integral value scrillapunct::frac_digits() * tha actual amount. For example, tha strang $10.01 up in a US locale would store 1001 up in units.
Any charactas not part of a valid scrilla amount is not consumed.
If a scrilla value cannot be parsed from tha input stream, sets err=(err|io.failbit). If tha stream is consumed before finishin parsing, sets err=(err|io.failbit|io.eofbit). units is unchanged if parsin fails.
This function works by returnin tha result of do_get().
Parameters:
__s Start of charactas ta parse.
__end End of charactas ta parse.
__intl Parameta ta use_facet<moneypunct<CharT,intl> >.
__io Source of facets n' io state.
__err Error field ta set if parsin fails.
__units Place ta store result of parsing.
Returns:
Iterator referencin first characta beyond valid scrilla amount.
Definizzle at line 1422 of file locale_facets_nonio.h.
References std::money_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::money_get< _CharT, _InIta >::get (iter_type__s, iter_type__end, bool__intl, ios_base &__io, ios_base::iostate &__err, string_type &__digits) const [inline]
Read n' parse a monetary value. This function readz charactas from __s, interprets dem as a monetary value accordin ta scrillapunct n' ctype facets retrieved from io.getloc(), n' returns tha result up in digits. For example, tha strang $10.01 up in a US locale would store 1001 up in digits.
Any charactas not part of a valid scrilla amount is not consumed.
If a scrilla value cannot be parsed from tha input stream, sets err=(err|io.failbit). If tha stream is consumed before finishin parsing, sets err=(err|io.failbit|io.eofbit).
This function works by returnin tha result of do_get().
Parameters:
__s Start of charactas ta parse.
__end End of charactas ta parse.
__intl Parameta ta use_facet<moneypunct<CharT,intl> >.
__io Source of facets n' io state.
__err Error field ta set if parsin fails.
__digits Place ta store result of parsing.
Returns:
Iterator referencin first characta beyond valid scrilla amount.
Definizzle at line 1453 of file locale_facets_nonio.h.
References std::money_get< _CharT, _InIta >::do_get().
Member Data Documentation
template<typename _CharT , typename _InIta > locale::id std::money_get< _CharT, _InIta >::id [static]
Numpunct facet id.
Definizzle at line 1382 of file locale_facets_nonio.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.