" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::rank< typename > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::integral_constant< std::size_t, 0 >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP
.br
< std::size_t, __v > \fBtype\fP"
.br
.ti -1c
.RI "typedef std::size_t \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBoperator value_type\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr std::size_t \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename>struct std::rank< typename >"
rank 
.PP
Definizzle at line 1243 of file type_traits\&.

.SH "Author"
.PP 
Generated automatically by Doxygen fo' libstdc++ from tha source code\&.
