" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::num_get< _CharT, _InIta > -
SYNOPSIS
Inherits std::locale::facet.
Public Types
typedef _CharT char_type
typedef _InIta iter_type
Public Member Functions
num_get (size_t __refs=0)
template<typename _ValueT > _InIta _M_extract_int (_InIta __beg, _InIta __end, ios_base &__io, ios_base::iostate &__err, _ValueT &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, bool &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, void *&__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, long &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, unsigned short &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, unsigned int &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, unsigned long &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, long long &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, unsigned long long &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, float &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, double &__v) const
iter_type get (iter_type __in, iter_type __end, ios_base &__io, ios_base::iostate &__err, long double &__v) const
Static Public Attributes
static locale::id id
Protected Member Functions
virtual ~num_get ()
iter_type _M_extract_float (iter_type, iter_type, ios_base &, ios_base::iostate &, string &) const
template<typename _ValueT > iter_type _M_extract_int (iter_type, iter_type, ios_base &, ios_base::iostate &, _ValueT &) const
template<typename _CharT2 > __gnu_cxx::__enable_if
< __is_char< _CharT2 >
::__value, int >::__type _M_find (const _CharT2 *, size_t __len, _CharT2 __c) const "
template<typename _CharT2 > __gnu_cxx::__enable_if
<!__is_char< _CharT2 >
::__value, int >::__type _M_find (const _CharT2 *__zero, size_t __len, _CharT2 __c) const "
virtual iter_type do_get (iter_type, iter_type, ios_base &, ios_base::iostate &, bool &) const
virtual iter_type do_get (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, long &__v) const
virtual iter_type do_get (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, unsigned short &__v) const
virtual iter_type do_get (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, unsigned int &__v) const
virtual iter_type do_get (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, unsigned long &__v) const
virtual iter_type do_get (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, long long &__v) const
virtual iter_type do_get (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, unsigned long long &__v) const
virtual iter_type do_get (iter_type, iter_type, ios_base &, ios_base::iostate &, float &) const
virtual iter_type do_get (iter_type, iter_type, ios_base &, ios_base::iostate &, double &) const
virtual iter_type do_get (iter_type, iter_type, ios_base &, ios_base::iostate &, long double &) const
virtual iter_type do_get (iter_type, iter_type, ios_base &, ios_base::iostate &, void *&) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Detailed Description
template<typename _CharT, typename _InIter>class std::num_get< _CharT, _InIta >
Primary class template num_get.
This facet encapsulates tha code ta parse n' return a number from a string. Well shiiiit, it is used by tha istream numeric extraction operators.
Da num_get template uses protected virtual functions ta provide tha actual thangs up in dis biatch. Da hood accessors forward tha call ta tha virtual functions. These virtual functions is hooks fo' pimpers ta implement tha behavior they require from tha num_get facet.
Definizzle at line 1915 of file locale_facets.h.
Member Typedef Documentation
template<typename _CharT , typename _InIta > typedef _CharT std::num_get< _CharT, _InIta >::char_type
Public typedefs.
Definizzle at line 1921 of file locale_facets.h.
template<typename _CharT , typename _InIta > typedef _InIta std::num_get< _CharT, _InIta >::iter_type
Public typedefs.
Definizzle at line 1922 of file locale_facets.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _InIta > std::num_get< _CharT, _InIta >::num_get (size_t__refs = 0) [inline], [explicit]
Constructor performs initialization. This is tha constructor provided by tha standard.
Parameters:
__refs Passed ta tha base facet class.
Definizzle at line 1936 of file locale_facets.h.
template<typename _CharT , typename _InIta > virtual std::num_get< _CharT, _InIta >::~num_get () [inline], [protected], [virtual]
Destructor.
Definizzle at line 2108 of file locale_facets.h.
Member Function Documentation
template<typename _CharT , typename _InIta > _InIta std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, bool &__v) const [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 590 of file locale_facets.tcc.
References std::ios_base::_M_getloc(), std::ios_base::boolalpha, std::ios_base::eofbit, std::ios_base::failbit, std::ios_base::flags(), n' std::ios_base::goodbit.
Referenced by std::num_get< _CharT, _InIta >::get().
template<typename _CharT , typename _InIta > virtual iter_type std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, long &__v) const [inline], [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2176 of file locale_facets.h.
template<typename _CharT , typename _InIta > virtual iter_type std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, unsigned short &__v) const [inline], [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2181 of file locale_facets.h.
template<typename _CharT , typename _InIta > virtual iter_type std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, unsigned int &__v) const [inline], [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2186 of file locale_facets.h.
template<typename _CharT , typename _InIta > virtual iter_type std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, unsigned long &__v) const [inline], [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2191 of file locale_facets.h.
template<typename _CharT , typename _InIta > virtual iter_type std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, long long &__v) const [inline], [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2197 of file locale_facets.h.
template<typename _CharT , typename _InIta > virtual iter_type std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, unsigned long long &__v) const [inline], [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2202 of file locale_facets.h.
template<typename _CharT , typename _InIta > _InIta std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, float &__v) const [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 686 of file locale_facets.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, n' std::basic_string< _CharT, _Traits, _Alloc >::reserve().
template<typename _CharT , typename _InIta > _InIta std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, double &__v) const [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 701 of file locale_facets.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, n' std::basic_string< _CharT, _Traits, _Alloc >::reserve().
template<typename _CharT , typename _InIta > _InIta std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, long double &__v) const [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 733 of file locale_facets.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, n' std::basic_string< _CharT, _Traits, _Alloc >::reserve().
template<typename _CharT , typename _InIta > _InIta std::num_get< _CharT, _InIta >::do_get (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, void *&__v) const [protected], [virtual]
Numeric parsing. Parses tha input stream tha fuck into tha variable v. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get() fo' mo' details.
Parameters:
__beg Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 748 of file locale_facets.tcc.
References std::ios_base::basefield, std::ios_base::flags(), n' std::ios_base::hex.
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, bool &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha bool v. Well shiiiit, it do so by callin num_get::do_get().
If ios_base::boolalpha is set, attempts ta read ctype<CharT>::truename() or ctype<CharT>::falsename(). Right back up in yo muthafuckin ass. Sets v ta legit or false if successful. Right back up in yo muthafuckin ass. Sets err ta ios_base::failbit if readin tha strang fails. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
If ios_base::boolalpha aint set, proceedz as wit readin a long, except if tha value is 1, sets v ta true, if tha value is 0, sets v ta false, n' otherwise set err ta ios_base::failbit.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 1962 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
Referenced by std::basic_istream< _CharT, _Traits >::operator>>().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, long &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Parsin be affected by tha flag settings up in io.
Da basic parse be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, parses like tha scanf o specifier. Else if equal ta ios_base::hex, parses like X specifier. Else if basefield equal ta 0, parses like tha i specifier. Otherwise, parses like d fo' signed n' u fo' unsigned types. Da matchin type length modifier be also used.
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 1999 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, unsigned short &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Parsin be affected by tha flag settings up in io.
Da basic parse be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, parses like tha scanf o specifier. Else if equal ta ios_base::hex, parses like X specifier. Else if basefield equal ta 0, parses like tha i specifier. Otherwise, parses like d fo' signed n' u fo' unsigned types. Da matchin type length modifier be also used.
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2004 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, unsigned int &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Parsin be affected by tha flag settings up in io.
Da basic parse be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, parses like tha scanf o specifier. Else if equal ta ios_base::hex, parses like X specifier. Else if basefield equal ta 0, parses like tha i specifier. Otherwise, parses like d fo' signed n' u fo' unsigned types. Da matchin type length modifier be also used.
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2009 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, unsigned long &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Parsin be affected by tha flag settings up in io.
Da basic parse be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, parses like tha scanf o specifier. Else if equal ta ios_base::hex, parses like X specifier. Else if basefield equal ta 0, parses like tha i specifier. Otherwise, parses like d fo' signed n' u fo' unsigned types. Da matchin type length modifier be also used.
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2014 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, long long &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Parsin be affected by tha flag settings up in io.
Da basic parse be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, parses like tha scanf o specifier. Else if equal ta ios_base::hex, parses like X specifier. Else if basefield equal ta 0, parses like tha i specifier. Otherwise, parses like d fo' signed n' u fo' unsigned types. Da matchin type length modifier be also used.
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2020 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, unsigned long long &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Parsin be affected by tha flag settings up in io.
Da basic parse be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, parses like tha scanf o specifier. Else if equal ta ios_base::hex, parses like X specifier. Else if basefield equal ta 0, parses like tha i specifier. Otherwise, parses like d fo' signed n' u fo' unsigned types. Da matchin type length modifier be also used.
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2025 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, float &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Da input charactas is parsed like tha scanf g specifier. Da matchin type length modifier be also used.
Da decimal point characta used is numpunct::decimal_point(). Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2059 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, double &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Da input charactas is parsed like tha scanf g specifier. Da matchin type length modifier be also used.
Da decimal point characta used is numpunct::decimal_point(). Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2064 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, long double &__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha integral variable v. Well shiiiit, it do so by callin num_get::do_get().
Da input charactas is parsed like tha scanf g specifier. Da matchin type length modifier be also used.
Da decimal point characta used is numpunct::decimal_point(). Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2069 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
template<typename _CharT , typename _InIta > iter_type std::num_get< _CharT, _InIta >::get (iter_type__in, iter_type__end, ios_base &__io, ios_base::iostate &__err, void *&__v) const [inline]
Numeric parsing. Parses tha input stream tha fuck into tha pointa variable v. Well shiiiit, it do so by callin num_get::do_get().
Da input charactas is parsed like tha scanf p specifier.
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep(). If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit.
Note dat tha digit groupin effect fo' pointas be a lil' bit ambiguous up in tha standard n' shouldn't be relied on. Right back up in yo muthafuckin ass. See DR 344.
If parsin tha strang yieldz a valid value fo' v, v is set. Otherwise, sets err ta ios_base::failbit n' leaves v unaltered. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied.
Parameters:
__in Start of input stream.
__end End of input stream.
__io Source of locale n' flags.
__err Error flags ta set.
__v Value ta format n' insert.
Returns:
Iterator afta reading.
Definizzle at line 2102 of file locale_facets.h.
References std::num_get< _CharT, _InIta >::do_get().
Member Data Documentation
template<typename _CharT , typename _InIta > locale::id std::num_get< _CharT, _InIta >::id [static]
Numpunct facet id.
Definizzle at line 1926 of file locale_facets.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.