" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::poisson_distribution< _IntType > -
SYNOPSIS
Classes
struct param_type
Public Types
typedef _IntType result_type
Public Member Functions
poisson_distribution (double __mean=1.0)
poisson_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
result_type max () const
double mean () const
result_type min () const
template<typename _UniformRandomNumberGenerator > poisson_distribution< _IntType >
::result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)"
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
param_type param () const
void param (const param_type &__param)
void reset ()
Friends
template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::poisson_distribution< _IntType1 > &__x)"
bool operator== (const poisson_distribution &__d1, const poisson_distribution &__d2)
template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::poisson_distribution< _IntType1 > &__x)"
Detailed Description
template<typename _IntType = int>class std::poisson_distribution< _IntType >
A discrete Poisson random number distribution.
Da formula fo' tha Poisson probabilitizzle densitizzle function is $p(i|\mu) = \frac{\mu^i}{i!} e^{-\mu}$ where $\mu$ is tha parameta of tha distribution.
Definizzle at line 4430 of file random.h.
Member Typedef Documentation
template<typename _IntType = int> typedef _IntType std::poisson_distribution< _IntType >::result_type
Da type of tha range of tha distribution.
Definizzle at line 4433 of file random.h.
Member Function Documentation
template<typename _IntType = int> result_type std::poisson_distribution< _IntType >::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 4524 of file random.h.
References std::numeric_limits< _Tp >::max().
template<typename _IntType = int> double std::poisson_distribution< _IntType >::mean () const [inline]
Returns tha distribution parameta mean.
Definizzle at line 4495 of file random.h.
template<typename _IntType = int> result_type std::poisson_distribution< _IntType >::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 4517 of file random.h.
template<typename _IntType = int> template<typename _UniformRandomNumberGenerator > poisson_distribution<_IntType>::result_type std::poisson_distribution< _IntType >::operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)
A rejection algorithm when mean >= 12 n' a simple method based upon tha multiplication of uniform random variates otherwise. NB: Da forma be available only if _GLIBCXX_USE_C99_MATH_TR1 is defined.
Reference: Devroye, L. Non-Uniform Random Variates Generation. Right back up in yo muthafuckin ass. Springer-Verlag, New York, 1986, Ch. X, Sects. 3.3 & 3.4 (+ Errata!).
Definizzle at line 1436 of file bits/random.tcc.
References std::abs(), std::numeric_limits< _Tp >::epsilon(), std::log(), n' std::numeric_limits< _Tp >::max().
template<typename _IntType = int> template<typename _UniformRandomNumberGenerator > result_type std::poisson_distribution< _IntType >::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 4532 of file random.h.
template<typename _IntType = int> param_type std::poisson_distribution< _IntType >::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 4502 of file random.h.
template<typename _IntType = int> void std::poisson_distribution< _IntType >::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 4510 of file random.h.
template<typename _IntType = int> void std::poisson_distribution< _IntType >::reset () [inline]
Resets tha distribution state.
Definizzle at line 4488 of file random.h.
References std::normal_distribution< _RealType >::reset().
Playas And Related Function Documentation
template<typename _IntType = int> template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::poisson_distribution< _IntType1 > &__x) [friend]
Inserts a poisson_distribution random number distribution __x tha fuck into tha output stream __os.
Parameters:
__os An output stream.
__x A poisson_distribution random number distribution.
Returns:
Da output stream wit tha state of __x banged or up in a error state.
template<typename _IntType = int> bool operator== (const poisson_distribution< _IntType > &__d1, const poisson_distribution< _IntType > &__d2) [friend]
Return legit if two Poisson distributions have tha same parametas n' tha sequences dat would be generated is equal.
Definizzle at line 4568 of file random.h.
template<typename _IntType = int> template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &__is, std::poisson_distribution< _IntType1 > &__x) [friend]
Extracts a poisson_distribution random number distribution __x from tha input stream __is.
Parameters:
__is An input stream.
__x A poisson_distribution random number generator engine.
Returns:
Da input stream wit __x extracted or up in a error state.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.