" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::ctype< _CharT > -
SYNOPSIS
Inherits std::__ctype_abstract_base< _CharT >.
Inherited by std::ctype_byname< _CharT >.
Public Types
typedef const int * __to_type
typedef _CharT char_type
typedef __ctype_abstract_base
< _CharT >::mask mask"
Public Member Functions
ctype (size_t __refs=0)
bool is (mask __m, char_type __c) const
const char_type * is (const char_type *__lo, const char_type *__hi, mask *__vec) const
char narrow (char_type __c, char __dfault) const
const char_type * narrow (const char_type *__lo, const char_type *__hi, char __dfault, char *__to) const
const char_type * scan_is (mask __m, const char_type *__lo, const char_type *__hi) const
const char_type * scan_not (mask __m, const char_type *__lo, const char_type *__hi) const
char_type tolower (char_type __c) const
const char_type * tolower (char_type *__lo, const char_type *__hi) const
char_type toupper (char_type __c) const
const char_type * toupper (char_type *__lo, const char_type *__hi) const
char_type widen (char __c) const
const char * widen (const char *__lo, const char *__hi, char_type *__to) const
Static Public Attributes
static const mask alnum
static const mask alpha
static const mask cntrl
static const mask digit
static const mask graph
static locale::id id
static const mask lower
static const mask print
static const mask punct
static const mask space
static const mask upper
static const mask xdigit
Protected Member Functions
virtual bool do_is (mask __m, char_type __c) const
virtual const char_type * do_is (const char_type *__lo, const char_type *__hi, mask *__vec) const
virtual char do_narrow (char_type, char __dfault) const
virtual const char_type * do_narrow (const char_type *__lo, const char_type *__hi, char __dfault, char *__to) const
virtual const char_type * do_scan_is (mask __m, const char_type *__lo, const char_type *__hi) const
virtual const char_type * do_scan_not (mask __m, const char_type *__lo, const char_type *__hi) const
virtual char_type do_tolower (char_type __c) const
virtual const char_type * do_tolower (char_type *__lo, const char_type *__hi) const
virtual char_type do_toupper (char_type __c) const
virtual const char_type * do_toupper (char_type *__lo, const char_type *__hi) const
virtual char_type do_widen (char __c) const
virtual const char * do_widen (const char *__lo, const char *__hi, char_type *__dest) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Detailed Description
template<typename _CharT>class std::ctype< _CharT >
Primary class template ctype facet.
This template class defines classification n' conversion functions fo' characta sets. Well shiiiit, it wraps cctype functionality. Ctype gets used by streams fo' nuff I/O operations.
This template serves up tha protected virtual functions tha pimper will gotta replace up in a thugged-out derived class or specialization ta cook up a hustlin facet. Da hood functions dat access dem is defined up in __ctype_abstract_base, ta allow fo' implementation flexibility. Right back up in yo muthafuckin ass. See ctype<wchar_t> fo' a example. Da functions is documented up in __ctype_abstract_base.
Note: implementations is provided fo' all tha protected virtual functions yo, but will likely not be useful.
Definizzle at line 605 of file locale_facets.h.
Member Function Documentation
template<typename _CharT> virtual bool std::ctype< _CharT >::do_is (mask__m, char_type__c) const [protected], [virtual]
Test char_type classification. This function findz a mask M fo' c n' compares it ta mask m.
do_is() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of classifying. do_is() must always return tha same result fo' tha same input.
Parameters:
__c Da char_type ta find tha mask of.
__m Da mask ta compare against.
Returns:
(M & __m) != 0.
Implements std::__ctype_abstract_base< _CharT >.
template<typename _CharT> virtual const char_type* std::ctype< _CharT >::do_is (const char_type *__lo, const char_type *__hi, mask *__vec) const [protected], [virtual]
Return a mask array. This function findz tha mask fo' each char_type up in tha range [lo,hi) n' successively writes it ta vec. vec must have as nuff elements as tha input.
do_is() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of classifying. do_is() must always return tha same result fo' tha same input.
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
__vec Pointa ta a array of mask storage.
Returns:
__hi.
Implements std::__ctype_abstract_base< _CharT >.
template<typename _CharT> virtual char std::ctype< _CharT >::do_narrow (char_type__c, char__dfault) const [protected], [virtual]
Narrow char_type ta char. This virtual function converts tha argument ta char rockin tha simplest reasonable transformation. If tha conversion fails, dfault is returned instead.
do_narrow() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of narrowing. do_narrow() must always return tha same result fo' tha same input.
Note: dis aint what tha fuck you want fo' codepage conversions. Right back up in yo muthafuckin ass. See codecvt fo' that.
Parameters:
__c Da char_type ta convert.
__dfault Char ta return if conversion fails.
Returns:
Da converted char.
Implements std::__ctype_abstract_base< _CharT >.
Referenced by std::ctype< char >::narrow().
template<typename _CharT> virtual const char_type* std::ctype< _CharT >::do_narrow (const char_type *__lo, const char_type *__hi, char__dfault, char *__to) const [protected], [virtual]
Narrow char_type array ta char. This virtual function converts each char_type up in tha range [__lo,__hi) ta char rockin tha simplest reasonable transformation n' writes tha thangs up in dis biatch ta tha destination array. For any element up in tha input dat cannot be converted, __dfault is used instead.
do_narrow() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of narrowing. do_narrow() must always return tha same result fo' tha same input.
Note: dis aint what tha fuck you want fo' codepage conversions. Right back up in yo muthafuckin ass. See codecvt fo' that.
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
__dfault Char ta use if conversion fails.
__to Pointa ta tha destination array.
Returns:
__hi.
Implements std::__ctype_abstract_base< _CharT >.
template<typename _CharT> virtual const char_type* std::ctype< _CharT >::do_scan_is (mask__m, const char_type *__lo, const char_type *__hi) const [protected], [virtual]
Find char_type matchin mask. This function searches fo' n' returns tha straight-up original gangsta char_type c up in [__lo,__hi) fo' which is(__m,c) is true.
do_scan_is() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of match searching. do_is() must always return tha same result fo' tha same input.
Parameters:
__m Da mask ta compare against.
__lo Pointa ta start of range.
__hi Pointa ta end of range.
Returns:
Pointa ta a matchin char_type if found, else __hi.
Implements std::__ctype_abstract_base< _CharT >.
template<typename _CharT> virtual const char_type* std::ctype< _CharT >::do_scan_not (mask__m, const char_type *__lo, const char_type *__hi) const [protected], [virtual]
Find char_type not matchin mask. This function searches fo' n' returns a pointa ta tha straight-up original gangsta char_type c of [lo,hi) fo' which is(m,c) is false.
do_scan_is() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of match searching. do_is() must always return tha same result fo' tha same input.
Parameters:
__m Da mask ta compare against.
__lo Pointa ta start of range.
__hi Pointa ta end of range.
Returns:
Pointa ta a non-matchin char_type if found, else __hi.
Implements std::__ctype_abstract_base< _CharT >.
template<typename _CharT> virtual char_type std::ctype< _CharT >::do_tolower (char_type__c) const [protected], [virtual]
Convert ta lowercase. This virtual function converts tha argument ta lowercase if possible. If not possible (for example, '2'), returns tha argument.
do_tolower() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of lowercasing. do_tolower() must always return tha same result fo' tha same input.
Parameters:
__c Da char_type ta convert.
Returns:
Da lowercase char_type if convertible, else __c.
Implements std::__ctype_abstract_base< _CharT >.
Referenced by std::ctype< char >::tolower().
template<typename _CharT> virtual const char_type* std::ctype< _CharT >::do_tolower (char_type *__lo, const char_type *__hi) const [protected], [virtual]
Convert array ta lowercase. This virtual function converts each char_type up in tha range [__lo,__hi) ta lowercase if possible. Other elements remain untouched.
do_tolower() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of lowercasing. do_tolower() must always return tha same result fo' tha same input.
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
Returns:
__hi.
Implements std::__ctype_abstract_base< _CharT >.
template<typename _CharT> virtual char_type std::ctype< _CharT >::do_toupper (char_type__c) const [protected], [virtual]
Convert ta uppercase. This virtual function converts tha char_type argument ta uppercase if possible. If not possible (for example, '2'), returns tha argument.
do_toupper() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of uppercasing. do_toupper() must always return tha same result fo' tha same input.
Parameters:
__c Da char_type ta convert.
Returns:
Da uppercase char_type if convertible, else __c.
Implements std::__ctype_abstract_base< _CharT >.
Referenced by std::ctype< char >::toupper().
template<typename _CharT> virtual const char_type* std::ctype< _CharT >::do_toupper (char_type *__lo, const char_type *__hi) const [protected], [virtual]
Convert array ta uppercase. This virtual function converts each char_type up in tha range [__lo,__hi) ta uppercase if possible. Other elements remain untouched.
do_toupper() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of uppercasing. do_toupper() must always return tha same result fo' tha same input.
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
Returns:
__hi.
Implements std::__ctype_abstract_base< _CharT >.
template<typename _CharT> virtual char_type std::ctype< _CharT >::do_widen (char__c) const [protected], [virtual]
Widen char. This virtual function converts tha char ta char_type rockin tha simplest reasonable transformation.
do_widen() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of widening. do_widen() must always return tha same result fo' tha same input.
Note: dis aint what tha fuck you want fo' codepage conversions. Right back up in yo muthafuckin ass. See codecvt fo' that.
Parameters:
__c Da char ta convert.
Returns:
Da converted char_type
Implements std::__ctype_abstract_base< _CharT >.
Referenced by std::ctype< char >::widen().
template<typename _CharT> virtual const char* std::ctype< _CharT >::do_widen (const char *__lo, const char *__hi, char_type *__to) const [protected], [virtual]
Widen char array. This function converts each char up in tha input ta char_type rockin tha simplest reasonable transformation.
do_widen() be a hook fo' a thugged-out derived facet ta chizzle tha behavior of widening. do_widen() must always return tha same result fo' tha same input.
Note: dis aint what tha fuck you want fo' codepage conversions. Right back up in yo muthafuckin ass. See codecvt fo' that.
Parameters:
__lo Pointa ta start range.
__hi Pointa ta end of range.
__to Pointa ta tha destination array.
Returns:
__hi.
Implements std::__ctype_abstract_base< _CharT >.
template<typename _CharT> bool std::__ctype_abstract_base< _CharT >::is (mask__m, char_type__c) const [inline], [inherited]
Test char_type classification. This function findz a mask M fo' __c n' compares it ta mask __m. Well shiiiit, it do so by returnin tha value of ctype<char_type>::do_is().
Parameters:
__c Da char_type ta compare tha mask of.
__m Da mask ta compare against.
Returns:
(M & __m) != 0.
Definizzle at line 162 of file locale_facets.h.
Referenced by std::basic_istream< _CharT, _Traits >::sentry::sentry().
template<typename _CharT> const char_type* std::__ctype_abstract_base< _CharT >::is (const char_type *__lo, const char_type *__hi, mask *__vec) const [inline], [inherited]
Return a mask array. This function findz tha mask fo' each char_type up in tha range [lo,hi) n' successively writes it ta vec. vec must have as nuff elements as tha char array. Well shiiiit, it do so by returnin tha value of ctype<char_type>::do_is().
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
__vec Pointa ta a array of mask storage.
Returns:
__hi.
Definizzle at line 179 of file locale_facets.h.
template<typename _CharT> char std::__ctype_abstract_base< _CharT >::narrow (char_type__c, char__dfault) const [inline], [inherited]
Narrow char_type ta char. This function converts tha char_type ta char rockin tha simplest reasonable transformation. If tha conversion fails, dfault is returned instead. Well shiiiit, it do so by returnin ctype<char_type>::do_narrow(__c).
Note: dis aint what tha fuck you want fo' codepage conversions. Right back up in yo muthafuckin ass. See codecvt fo' that.
Parameters:
__c Da char_type ta convert.
__dfault Char ta return if conversion fails.
Returns:
Da converted char.
Definizzle at line 324 of file locale_facets.h.
Referenced by std::time_put< _CharT, _OutIta >::put().
template<typename _CharT> const char_type* std::__ctype_abstract_base< _CharT >::narrow (const char_type *__lo, const char_type *__hi, char__dfault, char *__to) const [inline], [inherited]
Narrow array ta char array. This function converts each char_type up in tha input ta char rockin tha simplest reasonable transformation n' writes tha thangs up in dis biatch ta tha destination array. For any char_type up in tha input dat cannot be converted, dfault is used instead. Well shiiiit, it do so by returnin ctype<char_type>::do_narrow(__lo, __hi, __dfault, __to).
Note: dis aint what tha fuck you want fo' codepage conversions. Right back up in yo muthafuckin ass. See codecvt fo' that.
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
__dfault Char ta use if conversion fails.
__to Pointa ta tha destination array.
Returns:
__hi.
Definizzle at line 346 of file locale_facets.h.
template<typename _CharT> const char_type* std::__ctype_abstract_base< _CharT >::scan_is (mask__m, const char_type *__lo, const char_type *__hi) const [inline], [inherited]
Find char_type matchin a mask. This function searches fo' n' returns tha straight-up original gangsta char_type c up in [lo,hi) fo' which is(m,c) is true. Well shiiiit, it do so by returnin ctype<char_type>::do_scan_is().
Parameters:
__m Da mask ta compare against.
__lo Pointa ta start of range.
__hi Pointa ta end of range.
Returns:
Pointa ta matchin char_type if found, else __hi.
Definizzle at line 195 of file locale_facets.h.
template<typename _CharT> const char_type* std::__ctype_abstract_base< _CharT >::scan_not (mask__m, const char_type *__lo, const char_type *__hi) const [inline], [inherited]
Find char_type not matchin a mask. This function searches fo' n' returns tha straight-up original gangsta char_type c up in [lo,hi) fo' which is(m,c) is false. Well shiiiit, it do so by returnin ctype<char_type>::do_scan_not().
Parameters:
__m Da mask ta compare against.
__lo Pointa ta first char up in range.
__hi Pointa ta end of range.
Returns:
Pointa ta non-matchin char if found, else __hi.
Definizzle at line 211 of file locale_facets.h.
template<typename _CharT> char_type std::__ctype_abstract_base< _CharT >::tolower (char_type__c) const [inline], [inherited]
Convert ta lowercase. This function converts tha argument ta lowercase if possible. If not possible (for example, '2'), returns tha argument. Well shiiiit, it do so by returnin ctype<char_type>::do_tolower(c).
Parameters:
__c Da char_type ta convert.
Returns:
Da lowercase char_type if convertible, else __c.
Definizzle at line 254 of file locale_facets.h.
template<typename _CharT> const char_type* std::__ctype_abstract_base< _CharT >::tolower (char_type *__lo, const char_type *__hi) const [inline], [inherited]
Convert array ta lowercase. This function converts each char_type up in tha range [__lo,__hi) ta lowercase if possible. Other elements remain untouched. Well shiiiit, it do so by returnin ctype<char_type>:: do_tolower(__lo, __hi).
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
Returns:
__hi.
Definizzle at line 269 of file locale_facets.h.
template<typename _CharT> char_type std::__ctype_abstract_base< _CharT >::toupper (char_type__c) const [inline], [inherited]
Convert ta uppercase. This function converts tha argument ta uppercase if possible. If not possible (for example, '2'), returns tha argument. Well shiiiit, it do so by returnin ctype<char_type>::do_toupper().
Parameters:
__c Da char_type ta convert.
Returns:
Da uppercase char_type if convertible, else __c.
Definizzle at line 225 of file locale_facets.h.
template<typename _CharT> const char_type* std::__ctype_abstract_base< _CharT >::toupper (char_type *__lo, const char_type *__hi) const [inline], [inherited]
Convert array ta uppercase. This function converts each char_type up in tha range [lo,hi) ta uppercase if possible. Other elements remain untouched. Well shiiiit, it do so by returnin ctype<char_type>:: do_toupper(lo, hi).
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
Returns:
__hi.
Definizzle at line 240 of file locale_facets.h.
template<typename _CharT> char_type std::__ctype_abstract_base< _CharT >::widen (char__c) const [inline], [inherited]
Widen char ta char_type. This function converts tha char argument ta char_type rockin tha simplest reasonable transformation. Well shiiiit, it do so by returnin ctype<char_type>::do_widen(c).
Note: dis aint what tha fuck you want fo' codepage conversions. Right back up in yo muthafuckin ass. See codecvt fo' that.
Parameters:
__c Da char ta convert.
Returns:
Da converted char_type.
Definizzle at line 286 of file locale_facets.h.
Referenced by std::money_get< _CharT, _InIta >::do_get(), std::time_put< _CharT, _OutIta >::do_put(), std::money_put< _CharT, _OutIta >::do_put(), std::tr2::operator<<(), n' std::operator<<().
template<typename _CharT> const char* std::__ctype_abstract_base< _CharT >::widen (const char *__lo, const char *__hi, char_type *__to) const [inline], [inherited]
Widen array ta char_type. This function converts each char up in tha input ta char_type rockin tha simplest reasonable transformation. Well shiiiit, it do so by returnin ctype<char_type>::do_widen(c).
Note: dis aint what tha fuck you want fo' codepage conversions. Right back up in yo muthafuckin ass. See codecvt fo' that.
Parameters:
__lo Pointa ta start of range.
__hi Pointa ta end of range.
__to Pointa ta tha destination array.
Returns:
__hi.
Definizzle at line 305 of file locale_facets.h.
Member Data Documentation
template<typename _CharT> locale::id std::ctype< _CharT >::id [static]
Da facet id fo' ctype<char_type>
Definizzle at line 613 of file locale_facets.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.