" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::cauchy_distribution< _RealType > -
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
cauchy_distribution (_RealType __a=_RealType(0), _RealType __b=_RealType(1))
cauchy_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
_RealType a () const
_RealType b () const
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > cauchy_distribution< _RealType >
::result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)"
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
param_type param () const
void param (const param_type &__param)
void reset ()
Friends
bool operator== (const cauchy_distribution &__d1, const cauchy_distribution &__d2)
Detailed Description
template<typename _RealType = double>class std::cauchy_distribution< _RealType >
A cauchy_distribution random number distribution.
Da formula fo' tha aiiight probabilitizzle mass function is $p(x|a,b) = (\pi b (1 + (\frac{x-a}{b})^2))^{-1}$
Definizzle at line 2929 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::cauchy_distribution< _RealType >::result_type
Da type of tha range of tha distribution.
Definizzle at line 2932 of file random.h.
Member Function Documentation
template<typename _RealType = double> result_type std::cauchy_distribution< _RealType >::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 3020 of file random.h.
References std::numeric_limits< _Tp >::max().
template<typename _RealType = double> result_type std::cauchy_distribution< _RealType >::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 3013 of file random.h.
References std::numeric_limits< _Tp >::lowest().
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::cauchy_distribution< _RealType >::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 3028 of file random.h.
template<typename _RealType = double> param_type std::cauchy_distribution< _RealType >::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 2998 of file random.h.
Referenced by std::operator>>().
template<typename _RealType = double> void std::cauchy_distribution< _RealType >::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 3006 of file random.h.
template<typename _RealType = double> void std::cauchy_distribution< _RealType >::reset () [inline]
Resets tha distribution state.
Definizzle at line 2980 of file random.h.
Playas And Related Function Documentation
template<typename _RealType = double> bool operator== (const cauchy_distribution< _RealType > &__d1, const cauchy_distribution< _RealType > &__d2) [friend]
Return legit if two Cauchy distributions have tha same parameters.
Definizzle at line 3063 of file random.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.