" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::basic_filebuf< _CharT, _Traits > -
SYNOPSIS
Inherits std::basic_streambuf< _CharT, _Traits >.
Inherited by __gnu_cxx::stdio_filebuf< _CharT, _Traits >.
Public Types
typedef codecvt< char_type,
char, __state_type > __codecvt_type"
typedef __basic_file< char > __file_type
typedef basic_filebuf
< char_type, traits_type > __filebuf_type"
typedef traits_type::state_type __state_type
typedef basic_streambuf
< char_type, traits_type > __streambuf_type"
typedef _CharT char_type
typedef traits_type::int_type int_type
typedef traits_type::off_type off_type
typedef traits_type::pos_type pos_type
typedef _Traits traits_type
Public Member Functions
basic_filebuf ()
virtual ~basic_filebuf ()
__filebuf_type * close ()
locale getloc () const
streamsize in_avail ()
bool is_open () const throw ()
__filebuf_type * open (const char *__s, ios_base::openmode __mode)
__filebuf_type * open (const std::string &__s, ios_base::openmode __mode)
locale pubimbue (const locale &__loc)
int_type sbumpc ()
int_type sgetc ()
streamsize sgetn (char_type *__s, streamsize __n)
int_type snextc ()
int_type sputbackc (char_type __c)
int_type sputc (char_type __c)
streamsize sputn (const char_type *__s, streamsize __n)
int_type sungetc ()
basic_streambuf * pubsetbuf (char_type *__s, streamsize __n)
pos_type pubseekoff (off_type __off, ios_base::seekdir __way, ios_base::openmode __mode=ios_base::in|ios_base::out)
pos_type pubseekpos (pos_type __sp, ios_base::openmode __mode=ios_base::in|ios_base::out)
int pubsync ()
Protected Member Functions
void __safe_gbump (streamsize __n)
void __safe_pbump (streamsize __n)
void _M_allocate_internal_buffer ()
bool _M_convert_to_external (char_type *, streamsize)
void _M_create_pback ()
void _M_destroy_internal_buffer () throw ()
void _M_destroy_pback () throw ()
int _M_get_ext_pos (__state_type &__state)
pos_type _M_seek (off_type __off, ios_base::seekdir __way, __state_type __state)
void _M_set_buffer (streamsize __off)
bool _M_terminate_output ()
void gbump (int __n)
virtual void imbue (const locale &__loc)
virtual int_type overflow (int_type __c=_Traits::eof())
virtual int_type pbackfail (int_type __c=_Traits::eof())
void pbump (int __n)
virtual pos_type seekoff (off_type __off, ios_base::seekdir __way, ios_base::openmode __mode=ios_base::in|ios_base::out)
virtual pos_type seekpos (pos_type __pos, ios_base::openmode __mode=ios_base::in|ios_base::out)
virtual __streambuf_type * setbuf (char_type *__s, streamsize __n)
void setg (char_type *__gbeg, char_type *__gnext, char_type *__gend)
void setp (char_type *__pbeg, char_type *__pend)
virtual streamsize showmanyc ()
virtual int sync ()
virtual int_type uflow ()
virtual int_type underflow ()
virtual streamsize xsgetn (char_type *__s, streamsize __n)
virtual streamsize xsputn (const char_type *__s, streamsize __n)
char_type * eback () const
char_type * gptr () const
char_type * egptr () const
char_type * pbase () const
char_type * pptr () const
char_type * epptr () const
Protected Attributes
char_type * _M_buf
bool _M_buf_allocated
locale _M_buf_locale
size_t _M_buf_size
const __codecvt_type * _M_codecvt
char * _M_ext_buf
streamsize _M_ext_buf_size
char * _M_ext_end
const char * _M_ext_next
__file_type _M_file
char_type * _M_in_beg
char_type * _M_in_cur
char_type * _M_in_end
__c_lock _M_lock
ios_base::openmode _M_mode
char_type * _M_out_beg
char_type * _M_out_cur
char_type * _M_out_end
bool _M_reading
__state_type _M_state_beg
__state_type _M_state_cur
__state_type _M_state_last
bool _M_writing
char_type _M_pback
char_type * _M_pback_cur_save
char_type * _M_pback_end_save
bool _M_pback_init
Friends
class ios_base
Detailed Description
template<typename _CharT, typename _Traits>class std::basic_filebuf< _CharT, _Traits >
Da actual work of input n' output (for files).
Template Parameters:
_CharT Type of characta stream.
_Traits Traits fo' characta type, defaults ta char_traits<_CharT>.
This class associates both its input n' output sequence wit a external disk file, n' maintains a joint file posizzle fo' both sequences. Many of its semantics is busted lyrics bout up in termz of similar behavior up in tha Standard C Libraryz FILE streams.
Requirements on traits_type, specific ta dis class:
traits_type::pos_type must be fpos<traits_type::state_type>
traits_type::off_type must be streamoff
traits_type::state_type must be Assignable n' DefaultConstructible,
traits_type::state_type() must be tha initial state fo' codecvt.
Definizzle at line 72 of file fstream.
Constructor & Destructor Documentation
template<typename _CharT , typename _Traits > std::basic_filebuf< _CharT, _Traits >::basic_filebuf ()
Do not open any files. Da default constructor initializes tha parent class rockin its own default ctor.
Definizzle at line 79 of file fstream.tcc.
References std::basic_streambuf< _CharT, _Traits >::_M_buf_locale.
template<typename _CharT, typename _Traits> virtual std::basic_filebuf< _CharT, _Traits >::~basic_filebuf () [inline], [virtual]
Da destructor closes tha file first.
Definizzle at line 219 of file fstream.
Member Function Documentation
template<typename _CharT, typename _Traits> void std::basic_filebuf< _CharT, _Traits >::_M_create_pback () [inline], [protected]
Initializes pback buffers, n' moves aiiight buffers ta safety fo' realz. Assumptions: _M_in_cur has already been moved back
Definizzle at line 177 of file fstream.
template<typename _CharT, typename _Traits> void std::basic_filebuf< _CharT, _Traits >::_M_destroy_pback () [inline], [protected]
Deactivates pback buffer contents, n' restores aiiight buffer fo' realz. Assumptions: Da pback buffer has only moved forward.
Definizzle at line 194 of file fstream.
template<typename _CharT, typename _Traits> void std::basic_filebuf< _CharT, _Traits >::_M_set_buffer (streamsize__off) [inline], [protected]
This function sets tha pointaz of tha internal buffer, both git n' put areas. Typically:
__off == egptr() - eback() upon underflow/uflow (read mode); __off == 0 upon overflow (write mode); __off == -1 upon open, setbuf, seekoff/pos (uncommitted mode).
NB: epptr() - pbase() == _M_buf_size - 1, since _M_buf_size reflects tha actual allocated memory n' tha last cell is reserved fo' tha overflow char of a gangbangin' full put area.
Definizzle at line 395 of file fstream.
template<typename _CharT , typename _Traits > basic_filebuf< _CharT, _Traits >::__filebuf_type * std::basic_filebuf< _CharT, _Traits >::close ()
Closes tha currently associated file.
Returns:
this on success, NULL on failure
If no file is currently open, dis function immediately fails.
If a put buffer area exists, overflow(eof) is called ta flush all tha characters. Da file is then closed.
If any operations fail, dis function also fails.
Definizzle at line 128 of file fstream.tcc.
Referenced by std::basic_ifstream< _CharT, _Traits >::close(), std::basic_ofstream< _CharT, _Traits >::close(), std::basic_fstream< _CharT, _Traits >::close(), n' std::basic_filebuf< char_type, traits_type >::~basic_filebuf().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::eback () const [inline], [protected], [inherited]
Access ta tha git area. These functions is only available ta other protected functions, includin derived classes.
eback() returns tha beginnin pointa fo' tha input sequence
gptr() returns tha next pointa fo' tha input sequence
egptr() returns tha end pointa fo' tha input sequence
Definizzle at line 482 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_destroy_pback(), std::basic_streambuf< char, char_traits< char > >::sputbackc(), n' std::basic_streambuf< char, char_traits< char > >::sungetc().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::egptr () const [inline], [protected], [inherited]
Access ta tha git area. These functions is only available ta other protected functions, includin derived classes.
eback() returns tha beginnin pointa fo' tha input sequence
gptr() returns tha next pointa fo' tha input sequence
egptr() returns tha end pointa fo' tha input sequence
Definizzle at line 488 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), std::basic_streambuf< char, char_traits< char > >::in_avail(), std::basic_streambuf< char, char_traits< char > >::sbumpc(), std::basic_streambuf< char, char_traits< char > >::sgetc(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::showmanyc(), n' std::basic_stringbuf< _CharT, _Traits, _Alloc >::str().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::epptr () const [inline], [protected], [inherited]
Access ta tha put area. These functions is only available ta other protected functions, includin derived classes.
pbase() returns tha beginnin pointa fo' tha output sequence
pptr() returns tha next pointa fo' tha output sequence
epptr() returns tha end pointa fo' tha output sequence
Definizzle at line 535 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sputc().
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_streambuf< _CharT, _Traits >::gbump (int__n) [inline], [protected], [inherited]
Movin tha read position.
Parameters:
__n Da delta by which ta move.
This just advances tha read posizzle without returnin any data.
Definizzle at line 498 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sbumpc(), std::basic_streambuf< char, char_traits< char > >::sputbackc(), std::basic_streambuf< char, char_traits< char > >::sungetc(), n' std::basic_streambuf< char, char_traits< char > >::uflow().
template<typename _CharT, typename _Traits = char_traits<_CharT>> locale std::basic_streambuf< _CharT, _Traits >::getloc () const [inline], [inherited]
Locale access.
Returns:
Da current locale up in effect.
If pubimbue(loc) has been called, then da most thugged-out recent loc is returned. Otherwise tha global locale up in effect all up in tha time of construction is returned.
Definizzle at line 226 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pubimbue().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::gptr () const [inline], [protected], [inherited]
Access ta tha git area. These functions is only available ta other protected functions, includin derived classes.
eback() returns tha beginnin pointa fo' tha input sequence
gptr() returns tha next pointa fo' tha input sequence
egptr() returns tha end pointa fo' tha input sequence
Definizzle at line 485 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), std::basic_filebuf< char_type, traits_type >::_M_destroy_pback(), std::basic_streambuf< char, char_traits< char > >::in_avail(), std::basic_streambuf< char, char_traits< char > >::sbumpc(), std::basic_streambuf< char, char_traits< char > >::sgetc(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::showmanyc(), std::basic_streambuf< char, char_traits< char > >::sputbackc(), std::basic_streambuf< char, char_traits< char > >::sungetc(), n' std::basic_streambuf< char, char_traits< char > >::uflow().
template<typename _CharT , typename _Traits > void std::basic_filebuf< _CharT, _Traits >::imbue (const locale &__loc) [protected], [virtual]
Changes translations.
Parameters:
__loc A freshly smoked up locale.
Translations done durin I/O which depend on tha current locale is chizzled by dis call. Da standard adds, Between invocationz of dis function a cold-ass lil class derived from streambuf can safely cache thangs up in dis biatch of calls ta locale functions n' ta thugz of facets so obtained.
Note:
Base class version do nothing.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 910 of file fstream.tcc.
References std::ios_base::cur.
template<typename _CharT, typename _Traits = char_traits<_CharT>> streamsize std::basic_streambuf< _CharT, _Traits >::in_avail () [inline], [inherited]
Lookin ahead tha fuck into tha stream.
Returns:
Da number of charactas available.
If a read posizzle be available, returns tha number of charactas available fo' readin before tha buffer must be refilled. Otherwise returns tha derived showmanyc().
Definizzle at line 284 of file streambuf.
template<typename _CharT, typename _Traits> bool std::basic_filebuf< _CharT, _Traits >::is_open () const [inline]
Returns legit if tha external file is open.
Definizzle at line 227 of file fstream.
Referenced by std::basic_ifstream< _CharT, _Traits >::is_open(), std::basic_ofstream< _CharT, _Traits >::is_open(), n' std::basic_fstream< _CharT, _Traits >::is_open().
template<typename _CharT , typename _Traits > basic_filebuf< _CharT, _Traits >::__filebuf_type * std::basic_filebuf< _CharT, _Traits >::open (const char *__s, ios_base::openmode__mode)
Opens a external file.
Parameters:
__s Da name of tha file.
__mode Da open mode flags.
Returns:
this on success, NULL on failure
If a gangbangin' file be already open, dis function immediately fails. Otherwise it tries ta open tha file named __s rockin tha flags given up in __mode.
Table 92, adapted here, gives tha relation between openmode combinations n' tha equivalent fopen() flags. (NB: lines app, in|out|app, in|app, binary|app, binary|in|out|app, n' binary|in|app per DR 596) +---------------------------------------------------------+ | ios_base Flag combination stdio equivalent | |binary up in up trunc app | +---------------------------------------------------------+ | + w | | + + a | | + a | | + + w | | + r | | + + r+ | | + + + w+ | | + + + a+ | | + + a+ | +---------------------------------------------------------+ | + + wb | | + + + ab | | + + ab | | + + + wb | | + + rb | | + + + r+b | | + + + + w+b | | + + + + a+b | | + + + a+b | +---------------------------------------------------------+
Definizzle at line 94 of file fstream.tcc.
References std::ios_base::ate, std::ios_base::end, n' std::basic_filebuf< _CharT, _Traits >::open().
Referenced by std::basic_filebuf< _CharT, _Traits >::open(), std::basic_filebuf< char_type, traits_type >::open(), std::basic_ifstream< _CharT, _Traits >::open(), std::basic_ofstream< _CharT, _Traits >::open(), n' std::basic_fstream< _CharT, _Traits >::open().
template<typename _CharT, typename _Traits> __filebuf_type* std::basic_filebuf< _CharT, _Traits >::open (const std::string &__s, ios_base::openmode__mode) [inline]
Opens a external file.
Parameters:
__s Da name of tha file.
__mode Da open mode flags.
Returns:
this on success, NULL on failure
Definizzle at line 280 of file fstream.
template<typename _CharT , typename _Traits > basic_filebuf< _CharT, _Traits >::int_type std::basic_filebuf< _CharT, _Traits >::overflow (int_type__c = _Traits::eof()) [protected], [virtual]
Consumes data from tha buffer; writes ta tha controlled sequence.
Parameters:
__c An additionizzle characta ta consume.
Returns:
eof() ta indicate failure, suttin' else (usually __c, or not_eof())
Informally, dis function is called when tha output buffer is full (or do not exist, as bufferin need not straight-up be done). If a funky-ass buffer exists, it is consumed, wit some effect on tha controlled sequence. (Typically, tha buffer is freestyled up ta tha sequence verbatim.) In either case, tha characta c be also freestyled out, if __c aint eof().
For a gangbangin' formal definizzle of dis function, peep a phat text like fuckin Langer & Kreft, or [27.5.2.4.5]/3-7.
A functionin output streambuf can be pimped by overridin only dis function (no buffer area is ghon be used).
Note:
Base class version do nothing, returns eof().
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 422 of file fstream.tcc.
References std::ios_base::cur, n' std::ios_base::out.
template<typename _CharT , typename _Traits > basic_filebuf< _CharT, _Traits >::int_type std::basic_filebuf< _CharT, _Traits >::pbackfail (int_type__c = _Traits::eof()) [protected], [virtual]
Tries ta back up tha input sequence.
Parameters:
__c Da characta ta be banged back tha fuck into tha sequence.
Returns:
eof() on failure, some other value on success
Postcondition:
Da constraintz of gptr(), eback(), n' pptr() is tha same as fo' underflow().
Note:
Base class version do nothing, returns eof().
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 363 of file fstream.tcc.
References std::ios_base::cur, n' std::ios_base::in.
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::pbase () const [inline], [protected], [inherited]
Access ta tha put area. These functions is only available ta other protected functions, includin derived classes.
pbase() returns tha beginnin pointa fo' tha output sequence
pptr() returns tha next pointa fo' tha output sequence
epptr() returns tha end pointa fo' tha output sequence
Definizzle at line 529 of file streambuf.
Referenced by std::basic_stringbuf< _CharT, _Traits, _Alloc >::str().
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_streambuf< _CharT, _Traits >::pbump (int__n) [inline], [protected], [inherited]
Movin tha write position.
Parameters:
__n Da delta by which ta move.
This just advances tha write posizzle without returnin any data.
Definizzle at line 545 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sputc().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::pptr () const [inline], [protected], [inherited]
Access ta tha put area. These functions is only available ta other protected functions, includin derived classes.
pbase() returns tha beginnin pointa fo' tha output sequence
pptr() returns tha next pointa fo' tha output sequence
epptr() returns tha end pointa fo' tha output sequence
Definizzle at line 532 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sputc(), n' std::basic_stringbuf< _CharT, _Traits, _Alloc >::str().
template<typename _CharT, typename _Traits = char_traits<_CharT>> locale std::basic_streambuf< _CharT, _Traits >::pubimbue (const locale &__loc) [inline], [inherited]
Entry point fo' imbue().
Parameters:
__loc Da freshly smoked up locale.
Returns:
Da previous locale.
Calls tha derived imbue(__loc).
Definizzle at line 209 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> pos_type std::basic_streambuf< _CharT, _Traits >::pubseekoff (off_type__off, ios_base::seekdir__way, ios_base::openmode__mode = ios_base::in | ios_base::out) [inline], [inherited]
Altas tha stream position.
Parameters:
__off Offset.
__way Value fo' ios_base::seekdir.
__mode Value fo' ios_base::openmode.
Calls virtual seekoff function.
Definizzle at line 251 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> pos_type std::basic_streambuf< _CharT, _Traits >::pubseekpos (pos_type__sp, ios_base::openmode__mode = ios_base::in | ios_base::out) [inline], [inherited]
Altas tha stream position.
Parameters:
__sp Posizzle
__mode Value fo' ios_base::openmode.
Calls virtual seekpos function.
Definizzle at line 263 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> basic_streambuf* std::basic_streambuf< _CharT, _Traits >::pubsetbuf (char_type *__s, streamsize__n) [inline], [inherited]
Entry points fo' derived buffer functions. Da hood versionz of pubfoo dispatch ta tha protected derived foo member functions, passin tha arguments (if any) n' returnin tha result unchanged.
Definizzle at line 239 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> int std::basic_streambuf< _CharT, _Traits >::pubsync () [inline], [inherited]
Calls virtual sync function.
Definizzle at line 271 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::sync().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sbumpc () [inline], [inherited]
Gettin tha next character.
Returns:
Da next character, or eof.
If tha input read posizzle be available, returns dat characta n' increments tha read pointer, otherwise calls n' returns uflow().
Definizzle at line 316 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), std::istreambuf_iterator< _CharT, _Traits >::operator++(), n' std::basic_streambuf< char, char_traits< char > >::snextc().
template<typename _CharT , typename _Traits > basic_filebuf< _CharT, _Traits >::pos_type std::basic_filebuf< _CharT, _Traits >::seekoff (off_type, ios_base::seekdir, ios_base::openmode = ios_base::in | ios_base::out) [protected], [virtual]
Altas tha stream positions. Each derived class serves up its own appropriate behavior.
Note:
Base class version do nothing, returns a pos_type dat represents a invalid stream position.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 713 of file fstream.tcc.
References std::ios_base::cur.
template<typename _CharT , typename _Traits > basic_filebuf< _CharT, _Traits >::pos_type std::basic_filebuf< _CharT, _Traits >::seekpos (pos_type, ios_base::openmode = ios_base::in | ios_base::out) [protected], [virtual]
Altas tha stream positions. Each derived class serves up its own appropriate behavior.
Note:
Base class version do nothing, returns a pos_type dat represents a invalid stream position.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 773 of file fstream.tcc.
References std::ios_base::beg.
template<typename _CharT , typename _Traits > basic_filebuf< _CharT, _Traits >::__streambuf_type * std::basic_filebuf< _CharT, _Traits >::setbuf (char_type *__s, streamsize__n) [protected], [virtual]
Manipulates tha buffer.
Parameters:
__s Pointa ta a funky-ass buffer area.
__n Size of __s.
Returns:
this
If no file has been opened, n' both __s n' __n is zero, then tha stream becomes unbuffered. Otherwise, __s is used as a funky-ass buffer; peep http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch25s02.html fo' more.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 684 of file fstream.tcc.
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_streambuf< _CharT, _Traits >::setg (char_type *__gbeg, char_type *__gnext, char_type *__gend) [inline], [protected], [inherited]
Settin tha three read area pointers.
Parameters:
__gbeg A pointer.
__gnext A pointer.
__gend A pointer.
Postcondition:
__gbeg == eback(), __gnext == gptr(), n' __gend == egptr()
Definizzle at line 509 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), std::basic_filebuf< char_type, traits_type >::_M_destroy_pback(), n' std::basic_filebuf< char_type, traits_type >::_M_set_buffer().
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_streambuf< _CharT, _Traits >::setp (char_type *__pbeg, char_type *__pend) [inline], [protected], [inherited]
Settin tha three write area pointers.
Parameters:
__pbeg A pointer.
__pend A pointer.
Postcondition:
__pbeg == pbase(), __pbeg == pptr(), n' __pend == epptr()
Definizzle at line 555 of file streambuf.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_set_buffer().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sgetc () [inline], [inherited]
Gettin tha next character.
Returns:
Da next character, or eof.
If tha input read posizzle be available, returns dat character, otherwise calls n' returns underflow(). Do not move tha read posizzle afta fetchin tha character.
Definizzle at line 338 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), std::basic_istream< _CharT, _Traits >::sentry::sentry(), n' std::basic_streambuf< char, char_traits< char > >::snextc().
template<typename _CharT, typename _Traits = char_traits<_CharT>> streamsize std::basic_streambuf< _CharT, _Traits >::sgetn (char_type *__s, streamsize__n) [inline], [inherited]
Entry point fo' xsgetn.
Parameters:
__s A buffer area.
__n A count.
Returns xsgetn(__s,__n). Da effect is ta fill __s[0] all up in __s[__n-1] wit charactas from tha input sequence, if possible.
Definizzle at line 357 of file streambuf.
template<typename _CharT , typename _Traits > streamsize std::basic_filebuf< _CharT, _Traits >::showmanyc () [protected], [virtual]
Investigatin tha data available.
Returns:
An estimate of tha number of charactas available up in tha input sequence, or -1.
If it returns a positizzle value, then successive calls ta underflow() aint gonna return traits::eof() until at least dat number of charactas done been supplied. If showmanyc() returns -1, then calls ta underflow() or uflow() will fail. [27.5.2.4.3]/1
Note:
Base class version do nothing, returns zero.
Da standard addz dat the intention aint only dat tha calls [to underflow or uflow] aint gonna return eof() but dat they will return immediately.
Da standard addz dat the morphemez of showmanyc is es-how-many-see, not show-manic.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 178 of file fstream.tcc.
References std::ios_base::binary, n' std::ios_base::in.
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::snextc () [inline], [inherited]
Gettin tha next character.
Returns:
Da next character, or eof.
Calls sbumpc(), n' if dat function returns traits::eof(), so do dis function. Otherwise, sgetc().
Definizzle at line 298 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), n' std::basic_istream< _CharT, _Traits >::sentry::sentry().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sputbackc (char_type__c) [inline], [inherited]
Pushin charactas back tha fuck into tha input stream.
Parameters:
__c Da characta ta push back.
Returns:
Da previous character, if possible.
Similar ta sungetc() yo, but __c is pushed onto tha stream instead of the previous character. If successful, tha next characta fetched from tha input stream is ghon be __c.
Definizzle at line 372 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::putback().
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sputc (char_type__c) [inline], [inherited]
Entry point fo' all single-characta output functions.
Parameters:
__c A characta ta output.
Returns:
__c, if possible.
One of two hood output functions.
If a write posizzle be available fo' tha output sequence (i.e., tha buffer aint full), stores __c up in dat position, increments tha position, n' returns traits::to_int_type(__c). If a write posizzle aint available, returns overflow(__c).
Definizzle at line 424 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::get(), n' std::ostreambuf_iterator< _CharT, _Traits >::operator=().
template<typename _CharT, typename _Traits = char_traits<_CharT>> streamsize std::basic_streambuf< _CharT, _Traits >::sputn (const char_type *__s, streamsize__n) [inline], [inherited]
Entry point fo' all single-characta output functions.
Parameters:
__s A buffer read area.
__n A count.
One of two hood output functions.
Returns xsputn(__s,__n). Da effect is ta write __s[0] all up in __s[__n-1] ta tha output sequence, if possible.
Definizzle at line 450 of file streambuf.
template<typename _CharT, typename _Traits = char_traits<_CharT>> int_type std::basic_streambuf< _CharT, _Traits >::sungetc () [inline], [inherited]
Movin backwardz up in tha input stream.
Returns:
Da previous character, if possible.
If a putback posizzle be available, dis function decrements tha input pointa n' returns dat character. Otherwise, calls n' returns pbackfail(). Da effect is ta unget tha last characta gotten.
Definizzle at line 397 of file streambuf.
Referenced by std::basic_istream< _CharT, _Traits >::unget().
template<typename _CharT , typename _Traits > int std::basic_filebuf< _CharT, _Traits >::sync () [protected], [virtual]
Synchronizes tha buffer arrays wit tha controlled sequences.
Returns:
-1 on failure.
Each derived class serves up its own appropriate behavior, includin tha definizzle of failure.
Note:
Base class version do nothing, returns zero.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 893 of file fstream.tcc.
template<typename _CharT, typename _Traits = char_traits<_CharT>> virtual int_type std::basic_streambuf< _CharT, _Traits >::uflow () [inline], [protected], [virtual], [inherited]
Fetches mo' data from tha controlled sequence.
Returns:
Da first characta from tha pendin sequence.
Informally, dis function do tha same thang as underflow(), n' up in fact is required ta booty-call dat function. Well shiiiit, it also returns tha freshly smoked up character, like underflow() do. But fuck dat shiznit yo, tha word on tha street is dat dis function also moves tha read posizzle forward by one.
Reimplemented up in __gnu_cxx::stdio_sync_filebuf< _CharT, _Traits >.
Definizzle at line 700 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::sbumpc().
template<typename _CharT , typename _Traits > basic_filebuf< _CharT, _Traits >::int_type std::basic_filebuf< _CharT, _Traits >::underflow () [protected], [virtual]
Fetches mo' data from tha controlled sequence.
Returns:
Da first characta from tha pendin sequence.
Informally, dis function is called when tha input buffer is exhausted (or do not exist, as bufferin need not straight-up be done). If a funky-ass buffer exists, it is refilled. In either case, tha next available characta is returned, or traits::eof() ta indicate a null pendin sequence.
For a gangbangin' formal definizzle of tha pendin sequence, peep a phat text like fuckin Langer & Kreft, or [27.5.2.4.3]/7-14.
A functionin input streambuf can be pimped by overridin only dis function (no buffer area is ghon be used). For a example, peep http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch25.html
Note:
Base class version do nothing, returns eof().
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 204 of file fstream.tcc.
References std::ios_base::in, n' std::min().
template<typename _CharT , typename _Traits > streamsize std::basic_filebuf< _CharT, _Traits >::xsgetn (char_type *__s, streamsize__n) [protected], [virtual]
Multiple characta extraction.
Parameters:
__s A buffer area.
__n Maximum number of charactas ta assign.
Returns:
Da number of charactas assigned.
Fills __s[0] all up in __s[__n-1] wit charactas from tha input sequence, as if by sbumpc(). Right back up in yo muthafuckin ass. Stops when either __n charactas done been copied, or when traits::eof() would be copied.
It be expected dat derived classes provide a mo' efficient implementation by overridin dis definition.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 549 of file fstream.tcc.
References std::ios_base::in.
template<typename _CharT , typename _Traits > streamsize std::basic_filebuf< _CharT, _Traits >::xsputn (const char_type *__s, streamsize__n) [protected], [virtual]
Multiple characta insertion.
Parameters:
__s A buffer area.
__n Maximum number of charactas ta write.
Returns:
Da number of charactas written.
Writes __s[0] all up in __s[__n-1] ta tha output sequence, as if by sputc(). Right back up in yo muthafuckin ass. Stops when either n charactas done been copied, or when sputc() would return traits::eof().
It be expected dat derived classes provide a mo' efficient implementation by overridin dis definition.
Reimplemented from std::basic_streambuf< _CharT, _Traits >.
Definizzle at line 637 of file fstream.tcc.
References std::min(), n' std::ios_base::out.
Member Data Documentation
template<typename _CharT, typename _Traits> char_type* std::basic_filebuf< _CharT, _Traits >::_M_buf [protected]
Pointa ta tha beginnin of internal buffer.
Definizzle at line 114 of file fstream.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_destroy_pback(), n' std::basic_filebuf< char_type, traits_type >::_M_set_buffer().
template<typename _CharT, typename _Traits = char_traits<_CharT>> locale std::basic_streambuf< _CharT, _Traits >::_M_buf_locale [protected], [inherited]
Current locale setting.
Definizzle at line 192 of file streambuf.
Referenced by std::basic_filebuf< _CharT, _Traits >::basic_filebuf(), std::basic_streambuf< char, char_traits< char > >::getloc(), n' std::basic_streambuf< char, char_traits< char > >::pubimbue().
template<typename _CharT, typename _Traits> size_t std::basic_filebuf< _CharT, _Traits >::_M_buf_size [protected]
Actual size of internal buffer. This number is equal ta tha size of tha put area + 1 position, reserved fo' tha overflow char of a gangbangin' full area.
Definizzle at line 121 of file fstream.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_set_buffer().
template<typename _CharT, typename _Traits> char* std::basic_filebuf< _CharT, _Traits >::_M_ext_buf [protected]
Buffer fo' external characters. Used fo' input when codecvt::always_noconv() == false. When valid, dis correspondz ta eback().
Definizzle at line 156 of file fstream.
template<typename _CharT, typename _Traits> streamsize std::basic_filebuf< _CharT, _Traits >::_M_ext_buf_size [protected]
Size of buffer held by _M_ext_buf.
Definizzle at line 161 of file fstream.
template<typename _CharT, typename _Traits> const char* std::basic_filebuf< _CharT, _Traits >::_M_ext_next [protected]
Pointas tha fuck into tha buffer held by _M_ext_buf dat delimit a subsequence of bytes dat done been read but not yet converted. When valid, _M_ext_next correspondz ta egptr().
Definizzle at line 168 of file fstream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_in_beg [protected], [inherited]
Start of git area.
Definizzle at line 184 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::eback(), n' std::basic_streambuf< char, char_traits< char > >::setg().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_in_cur [protected], [inherited]
Current read area.
Definizzle at line 185 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::gbump(), std::basic_streambuf< char, char_traits< char > >::gptr(), n' std::basic_streambuf< char, char_traits< char > >::setg().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_in_end [protected], [inherited]
End of git area.
Definizzle at line 186 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::egptr(), n' std::basic_streambuf< char, char_traits< char > >::setg().
template<typename _CharT, typename _Traits> ios_base::openmode std::basic_filebuf< _CharT, _Traits >::_M_mode [protected]
Place ta stash up in || up || up in | up settings fo' current filebuf.
Definizzle at line 99 of file fstream.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_set_buffer().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_out_beg [protected], [inherited]
Start of put area.
Definizzle at line 187 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pbase(), n' std::basic_streambuf< char, char_traits< char > >::setp().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_out_cur [protected], [inherited]
Current put area.
Definizzle at line 188 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::pbump(), std::basic_streambuf< char, char_traits< char > >::pptr(), n' std::basic_streambuf< char, char_traits< char > >::setp().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type* std::basic_streambuf< _CharT, _Traits >::_M_out_end [protected], [inherited]
End of put area.
Definizzle at line 189 of file streambuf.
Referenced by std::basic_streambuf< char, char_traits< char > >::epptr(), n' std::basic_streambuf< char, char_traits< char > >::setp().
template<typename _CharT, typename _Traits> char_type std::basic_filebuf< _CharT, _Traits >::_M_pback [protected]
Necessary bits fo' putback buffer pimpment.
Note:
pbackz of over one characta is not currently supported.
Definizzle at line 142 of file fstream.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback().
template<typename _CharT, typename _Traits> char_type* std::basic_filebuf< _CharT, _Traits >::_M_pback_cur_save [protected]
Necessary bits fo' putback buffer pimpment.
Note:
pbackz of over one characta is not currently supported.
Definizzle at line 143 of file fstream.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), n' std::basic_filebuf< char_type, traits_type >::_M_destroy_pback().
template<typename _CharT, typename _Traits> char_type* std::basic_filebuf< _CharT, _Traits >::_M_pback_end_save [protected]
Necessary bits fo' putback buffer pimpment.
Note:
pbackz of over one characta is not currently supported.
Definizzle at line 144 of file fstream.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), n' std::basic_filebuf< char_type, traits_type >::_M_destroy_pback().
template<typename _CharT, typename _Traits> bool std::basic_filebuf< _CharT, _Traits >::_M_pback_init [protected]
Necessary bits fo' putback buffer pimpment.
Note:
pbackz of over one characta is not currently supported.
Definizzle at line 145 of file fstream.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_create_pback(), n' std::basic_filebuf< char_type, traits_type >::_M_destroy_pback().
template<typename _CharT, typename _Traits> bool std::basic_filebuf< _CharT, _Traits >::_M_reading [protected]
_M_readin == false && _M_writin == false fo' uncommitted mode; _M_readin == legit fo' read mode; _M_writin == legit fo' write mode;
NB: _M_readin == legit && _M_writin == legit is unused.
Definizzle at line 133 of file fstream.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.