" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::set< _Key, _Compare, _Alloc > -
SYNOPSIS
Public Types
typedef _Key key_type
typedef _Key value_type
typedef _Compare key_compare
typedef _Compare value_compare
typedef _Alloc allocator_type
typedef _Key_alloc_type::pointa pointer
typedef
_Key_alloc_type::const_pointa const_pointer"
typedef _Key_alloc_type::reference reference
typedef
_Key_alloc_type::const_reference const_reference"
typedef _Rep_type::const_iterator iterator
typedef _Rep_type::const_iterator const_iterator
typedef
_Rep_type::const_reverse_iterator reverse_iterator"
typedef
_Rep_type::const_reverse_iterator const_reverse_iterator"
typedef _Rep_type::size_type size_type
typedef _Rep_type::difference_type difference_type
Public Member Functions
set ()
set (const _Compare &__comp, const allocator_type &__a=allocator_type())
template<typename _InputIterator > set (_InputIterator __first, _InputIterator __last)
template<typename _InputIterator > set (_InputIterator __first, _InputIterator __last, const _Compare &__comp, const allocator_type &__a=allocator_type())
set (const set &__x)
set (set &&__x) noexcept(is_nothrow_copy_constructible< _Compare >::value)
set (initializer_list< value_type > __l, const _Compare &__comp=_Compare(), const allocator_type &__a=allocator_type())
iterator begin () const noexcept
iterator cbegin () const noexcept
iterator cend () const noexcept
void clear () noexcept
size_type count (const key_type &__x) const
reverse_iterator crbegin () const noexcept
reverse_iterator crend () const noexcept
template<typename... _Args> std::pair< iterator, bool > emplace (_Args &&...__args)
template<typename... _Args> iterator emplace_hint (const_iterator __pos, _Args &&...__args)
bool empty () const noexcept
iterator end () const noexcept
_GLIBCXX_ABI_TAG_CXX11 iterator erase (const_iterator __position)
size_type erase (const key_type &__x)
_GLIBCXX_ABI_TAG_CXX11 iterator erase (const_iterator __first, const_iterator __last)
allocator_type get_allocator () const noexcept
std::pair< iterator, bool > insert (const value_type &__x)
std::pair< iterator, bool > insert (value_type &&__x)
iterator insert (const_iterator __position, const value_type &__x)
iterator insert (const_iterator __position, value_type &&__x)
template<typename _InputIterator > void insert (_InputIterator __first, _InputIterator __last)
void insert (initializer_list< value_type > __l)
key_compare key_comp () const
size_type max_size () const noexcept
set & operator= (const set &__x)
set & operator= (set &&__x)
set & operator= (initializer_list< value_type > __l)
reverse_iterator rbegin () const noexcept
reverse_iterator rend () const noexcept
size_type size () const noexcept
void swap (set &__x)
value_compare value_comp () const
iterator find (const key_type &__x)
const_iterator find (const key_type &__x) const
iterator lower_bound (const key_type &__x)
const_iterator lower_bound (const key_type &__x) const
iterator upper_bound (const key_type &__x)
const_iterator upper_bound (const key_type &__x) const
std::pair< iterator, iterator > equal_range (const key_type &__x)
std::pair< const_iterator,
const_iterator > equal_range (const key_type &__x) const "
Friends
template<typename _K1 , typename _C1 , typename _A1 > bool operator< (const set< _K1, _C1, _A1 > &, const set< _K1, _C1, _A1 > &)
template<typename _K1 , typename _C1 , typename _A1 > bool operator== (const set< _K1, _C1, _A1 > &, const set< _K1, _C1, _A1 > &)
Detailed Description
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>>class std::set< _Key, _Compare, _Alloc >
A standard container made up of unique keys, which can be retrieved up in logarithmic time.
Template Parameters:
_Key Type of key objects.
_Compare Comparison function object type, defaults ta less<_Key>.
_Alloc Allocator type, defaults ta allocator<_Key>.
Meets tha requirementz of a container, a reversible container, n' a associatizzle container (usin unique keys).
Sets support bidirectionizzle iterators.
Da private tree data is declared exactly tha same way fo' set n' multiset; tha distinction is made entirely up in how tha fuck tha tree functions is called (*_unique versus *_equal, same as tha standard).
Definizzle at line 90 of file stl_set.h.
Member Typedef Documentation
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Alloc std::set< _Key, _Compare, _Alloc >::allocator_type
Public typedefs.
Definizzle at line 107 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Rep_type::const_iterator std::set< _Key, _Compare, _Alloc >::const_iterator
Iterator-related typedefs.
Definizzle at line 128 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Key_alloc_type::const_pointa std::set< _Key, _Compare, _Alloc >::const_pointer
Iterator-related typedefs.
Definizzle at line 121 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Key_alloc_type::const_reference std::set< _Key, _Compare, _Alloc >::const_reference
Iterator-related typedefs.
Definizzle at line 123 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Rep_type::const_reverse_iterator std::set< _Key, _Compare, _Alloc >::const_reverse_iterator
Iterator-related typedefs.
Definizzle at line 130 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Rep_type::difference_type std::set< _Key, _Compare, _Alloc >::difference_type
Iterator-related typedefs.
Definizzle at line 132 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Rep_type::const_iterator std::set< _Key, _Compare, _Alloc >::iterator
Iterator-related typedefs.
Definizzle at line 127 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Compare std::set< _Key, _Compare, _Alloc >::key_compare
Public typedefs.
Definizzle at line 105 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Key std::set< _Key, _Compare, _Alloc >::key_type
Public typedefs.
Definizzle at line 103 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Key_alloc_type::pointa std::set< _Key, _Compare, _Alloc >::pointer
Iterator-related typedefs.
Definizzle at line 120 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Key_alloc_type::reference std::set< _Key, _Compare, _Alloc >::reference
Iterator-related typedefs.
Definizzle at line 122 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Rep_type::const_reverse_iterator std::set< _Key, _Compare, _Alloc >::reverse_iterator
Iterator-related typedefs.
Definizzle at line 129 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Rep_type::size_type std::set< _Key, _Compare, _Alloc >::size_type
Iterator-related typedefs.
Definizzle at line 131 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Compare std::set< _Key, _Compare, _Alloc >::value_compare
Public typedefs.
Definizzle at line 106 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> typedef _Key std::set< _Key, _Compare, _Alloc >::value_type
Public typedefs.
Definizzle at line 104 of file stl_set.h.
Constructor & Destructor Documentation
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::set< _Key, _Compare, _Alloc >::set () [inline]
Default constructor creates no elements.
Definizzle at line 139 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::set< _Key, _Compare, _Alloc >::set (const _Compare &__comp, const allocator_type &__a = allocator_type()) [inline], [explicit]
Creates a set wit no elements.
Parameters:
__comp Comparator ta use.
__a An allocator object.
Definizzle at line 148 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename _InputIterator > std::set< _Key, _Compare, _Alloc >::set (_InputIterator__first, _InputIterator__last) [inline]
Buildz a set from a range.
Parameters:
__first An input iterator.
__last An input iterator.
Smoke a set consistin of copiez of tha elements from [__first,__last). This is linear up in N if tha range be already sorted, n' NlogN otherwise (where N is distance(__first,__last)).
Definizzle at line 163 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename _InputIterator > std::set< _Key, _Compare, _Alloc >::set (_InputIterator__first, _InputIterator__last, const _Compare &__comp, const allocator_type &__a = allocator_type()) [inline]
Buildz a set from a range.
Parameters:
__first An input iterator.
__last An input iterator.
__comp A comparison functor.
__a An allocator object.
Smoke a set consistin of copiez of tha elements from [__first,__last). This is linear up in N if tha range be already sorted, n' NlogN otherwise (where N is distance(__first,__last)).
Definizzle at line 180 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::set< _Key, _Compare, _Alloc >::set (const set< _Key, _Compare, _Alloc > &__x) [inline]
Set copy constructor.
Parameters:
__x A set of identical element n' allocator types.
Da newly-created set uses a cold-ass lil copy of tha allocation object used by __x.
Definizzle at line 193 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::set< _Key, _Compare, _Alloc >::set (set< _Key, _Compare, _Alloc > &&__x) [inline], [noexcept]
Set move constructor
Parameters:
__x A set of identical element n' allocator types.
Da newly-created set gotz nuff tha exact contentz of x. Da contentz of x is a valid yo, but unspecified set.
Definizzle at line 204 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::set< _Key, _Compare, _Alloc >::set (initializer_list< value_type >__l, const _Compare &__comp = _Compare(), const allocator_type &__a = allocator_type()) [inline]
Buildz a set from a initializer_list.
Parameters:
__l An initializer_list.
__comp A comparison functor.
__a An allocator object.
Smoke a set consistin of copiez of tha elements up in tha list. This is linear up in N if tha list be already sorted, n' NlogN otherwise (where N is __l.size()).
Definizzle at line 218 of file stl_set.h.
Member Function Documentation
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::set< _Key, _Compare, _Alloc >::begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha set. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 298 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::set< _Key, _Compare, _Alloc >::cbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha set. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 335 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::set< _Key, _Compare, _Alloc >::cend () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha set. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 344 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> void std::set< _Key, _Compare, _Alloc >::clear () [inline], [noexcept]
Erases all elements up in a set. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 630 of file stl_set.h.
Referenced by std::set< _StateIdT >::operator=().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> size_type std::set< _Key, _Compare, _Alloc >::count (const key_type &__x) const [inline]
Findz tha number of elements.
Parameters:
__x Element ta located.
Returns:
Number of elements wit specified key.
This function only make sense fo' multisets; fo' set tha result will either be 0 (not present) or 1 (present).
Definizzle at line 644 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> reverse_iterator std::set< _Key, _Compare, _Alloc >::crbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha last element up in tha set. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 353 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> reverse_iterator std::set< _Key, _Compare, _Alloc >::crend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last pair up in tha set. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 362 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename... _Args> std::pair<iterator, bool> std::set< _Key, _Compare, _Alloc >::emplace (_Args &&...__args) [inline]
Attempts ta build n' bang a element tha fuck into tha set.
Parameters:
__args Arguments used ta generate a element.
Returns:
A pair, of which tha straight-up original gangsta element be a iterator dat points ta tha possibly banged element, n' tha second be a funky-ass bool dat is legit if tha element was straight-up inserted.
This function attempts ta build n' bang a element tha fuck into tha set fo' realz. A set relies on unique keys n' thus a element is only banged if it aint already present up in tha set.
Insertion requires logarithmic time.
Definizzle at line 413 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename... _Args> iterator std::set< _Key, _Compare, _Alloc >::emplace_hint (const_iterator__pos, _Args &&...__args) [inline]
Attempts ta bang a element tha fuck into tha set.
Parameters:
__pos An iterator dat serves as a hint as ta where tha element should be inserted.
__args Arguments used ta generate tha element ta be inserted.
Returns:
An iterator dat points ta tha element wit key equivalent ta tha one generated from __args (may or may not be tha element itself).
This function aint concerned bout whether tha insertion took place, n' thus do not return a funky-ass boolean like tha single-argument emplace() do. Note dat tha straight-up original gangsta parameta is only a hint n' can potentially improve tha performizzle of tha insertion process fo' realz. A wack hint would cause no gains up in efficiency.
For mo' on hinting, see: http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html
Insertion requires logarithmic time (if tha hint aint taken).
Definizzle at line 439 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> bool std::set< _Key, _Compare, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha set is empty.
Definizzle at line 368 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::set< _Key, _Compare, _Alloc >::end () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha set. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 307 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::pair<iterator, iterator> std::set< _Key, _Compare, _Alloc >::equal_range (const key_type &__x) [inline]
Findz a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Pair of iterators dat possibly points ta tha subsequence matchin given key.
This function is equivalent ta
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
 (but is fasta than makin tha calls separately).
This function probably only make sense fo' multisets.
Definizzle at line 724 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::pair<const_iterator, const_iterator> std::set< _Key, _Compare, _Alloc >::equal_range (const key_type &__x) const [inline]
Findz a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Pair of iterators dat possibly points ta tha subsequence matchin given key.
This function is equivalent ta
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
 (but is fasta than makin tha calls separately).
This function probably only make sense fo' multisets.
Definizzle at line 728 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> _GLIBCXX_ABI_TAG_CXX11 iterator std::set< _Key, _Compare, _Alloc >::erase (const_iterator__position) [inline]
Erases a element from a set.
Parameters:
__position An iterator pointin ta tha element ta be erased.
Returns:
An iterator pointin ta tha element immediately followin __position prior ta tha element bein erased. If no such element exists, end() is returned.
This function erases a element, pointed ta by tha given iterator, from a set. Note dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 551 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> size_type std::set< _Key, _Compare, _Alloc >::erase (const key_type &__x) [inline]
Erases elements accordin ta tha provided key.
Parameters:
__x Key of element ta be erased.
Returns:
Da number of elements erased.
This function erases all tha elements located by tha given key from a set. Note dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 581 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> _GLIBCXX_ABI_TAG_CXX11 iterator std::set< _Key, _Compare, _Alloc >::erase (const_iterator__first, const_iterator__last) [inline]
Erases a [__first,__last) range of elements from a set.
Parameters:
__first Iterator pointin ta tha start of tha range ta be erased.
__last Iterator pointin ta tha end of tha range ta be erased.
Returns:
Da iterator __last.
This function erases a sequence of elements from a set. Note dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 603 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::set< _Key, _Compare, _Alloc >::find (const key_type &__x) [inline]
Tries ta locate a element up in a set.
Parameters:
__x Element ta be located.
Returns:
Iterator pointin ta sought-afta element, or end() if not found.
This function takes a key n' tries ta locate tha element wit which tha key matches. If successful tha function returns a iterator pointin ta tha sought afta element. If unsuccessful it returns tha past-the-end ( end() ) iterator.
Definizzle at line 662 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> const_iterator std::set< _Key, _Compare, _Alloc >::find (const key_type &__x) const [inline]
Tries ta locate a element up in a set.
Parameters:
__x Element ta be located.
Returns:
Iterator pointin ta sought-afta element, or end() if not found.
This function takes a key n' tries ta locate tha element wit which tha key matches. If successful tha function returns a iterator pointin ta tha sought afta element. If unsuccessful it returns tha past-the-end ( end() ) iterator.
Definizzle at line 666 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> allocator_type std::set< _Key, _Compare, _Alloc >::get_allocator () const [inline], [noexcept]
Returns tha allocator object wit which tha set was constructed.
Definizzle at line 289 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::pair<iterator, bool> std::set< _Key, _Compare, _Alloc >::insert (const value_type &__x) [inline]
Attempts ta bang a element tha fuck into tha set.
Parameters:
__x Element ta be inserted.
Returns:
A pair, of which tha straight-up original gangsta element be a iterator dat points ta tha possibly banged element, n' tha second be a funky-ass bool dat is legit if tha element was straight-up inserted.
This function attempts ta bang a element tha fuck into tha set fo' realz. A set relies on unique keys n' thus a element is only banged if it aint already present up in tha set.
Insertion requires logarithmic time.
Definizzle at line 460 of file stl_set.h.
Referenced by std::set< _StateIdT >::insert(), n' std::set< _StateIdT >::operator=().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::set< _Key, _Compare, _Alloc >::insert (const_iterator__position, const value_type &__x) [inline]
Attempts ta bang a element tha fuck into tha set.
Parameters:
__position An iterator dat serves as a hint as ta where tha element should be inserted.
__x Element ta be inserted.
Returns:
An iterator dat points ta tha element wit key of __x (may or may not be tha element passed in).
This function aint concerned bout whether tha insertion took place, n' thus do not return a funky-ass boolean like tha single-argument insert() do. Note dat tha straight-up original gangsta parameta is only a hint n' can potentially improve tha performizzle of tha insertion process fo' realz. A wack hint would cause no gains up in efficiency.
For mo' on hinting, see: http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html
Insertion requires logarithmic time (if tha hint aint taken).
Definizzle at line 497 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename _InputIterator > void std::set< _Key, _Compare, _Alloc >::insert (_InputIterator__first, _InputIterator__last) [inline]
A template function dat attempts ta bang a range of elements.
Parameters:
__first Iterator pointin ta tha start of tha range ta be inserted.
__last Iterator pointin ta tha end of tha range.
Complexitizzle similar ta dat of tha range constructor.
Definizzle at line 517 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> void std::set< _Key, _Compare, _Alloc >::insert (initializer_list< value_type >__l) [inline]
Attempts ta bang a list of elements tha fuck into tha set.
Parameters:
__l A std::initializer_list<value_type> of elements ta be inserted.
Complexitizzle similar ta dat of tha range constructor.
Definizzle at line 529 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> key_compare std::set< _Key, _Compare, _Alloc >::key_comp () const [inline]
Returns tha comparison object wit which tha set was constructed.
Definizzle at line 281 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::set< _Key, _Compare, _Alloc >::lower_bound (const key_type &__x) [inline]
Findz tha beginnin of a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Iterator pointin ta first element equal ta or pimped outa than key, or end().
This function returns tha straight-up original gangsta element of a subsequence of elements dat matches tha given key. If unsuccessful it returns a iterator pointin ta tha straight-up original gangsta element dat has a pimped outa value than given key or end() if no such element exists.
Definizzle at line 683 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> const_iterator std::set< _Key, _Compare, _Alloc >::lower_bound (const key_type &__x) const [inline]
Findz tha beginnin of a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Iterator pointin ta first element equal ta or pimped outa than key, or end().
This function returns tha straight-up original gangsta element of a subsequence of elements dat matches tha given key. If unsuccessful it returns a iterator pointin ta tha straight-up original gangsta element dat has a pimped outa value than given key or end() if no such element exists.
Definizzle at line 687 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> size_type std::set< _Key, _Compare, _Alloc >::max_size () const [inline], [noexcept]
Returns tha maximum size of tha set.
Definizzle at line 378 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> set& std::set< _Key, _Compare, _Alloc >::operator= (const set< _Key, _Compare, _Alloc > &__x) [inline]
Set assignment operator.
Parameters:
__x A set of identical element n' allocator types.
All tha elementz of __x is copied yo, but unlike tha copy constructor, tha allocator object aint copied.
Definizzle at line 233 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> set& std::set< _Key, _Compare, _Alloc >::operator= (set< _Key, _Compare, _Alloc > &&__x) [inline]
Set move assignment operator.
Parameters:
__x A set of identical element n' allocator types.
Da contentz of __x is moved tha fuck into dis set (without copying). __x be a valid yo, but unspecified set.
Definizzle at line 248 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> set& std::set< _Key, _Compare, _Alloc >::operator= (initializer_list< value_type >__l) [inline]
Set list assignment operator.
Parameters:
__l An initializer_list.
This function fills a set wit copiez of tha elements up in tha initializer list __l.
Note dat tha assignment straight-up chizzlez tha set n' dat tha resultin setz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 269 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> reverse_iterator std::set< _Key, _Compare, _Alloc >::rbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha last element up in tha set. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 316 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> reverse_iterator std::set< _Key, _Compare, _Alloc >::rend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last pair up in tha set. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 325 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> size_type std::set< _Key, _Compare, _Alloc >::size () const [inline], [noexcept]
Returns tha size of tha set.
Definizzle at line 373 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> void std::set< _Key, _Compare, _Alloc >::swap (set< _Key, _Compare, _Alloc > &__x) [inline]
Swaps data wit another set.
Parameters:
__x A set of tha same element n' allocator types.
This exchanges tha elements between two sets up in constant time. (It be only swappin a pointer, a integer, n' a instizzle of tha Compare type (which itself is often stateless n' empty), so it should be like fast.) Note dat tha global std::swap() function is specialized such dat std::swap(s1,s2) will feed ta dis function.
Definizzle at line 393 of file stl_set.h.
Referenced by std::set< _StateIdT >::operator=(), n' std::swap().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::set< _Key, _Compare, _Alloc >::upper_bound (const key_type &__x) [inline]
Findz tha end of a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Iterator pointin ta tha straight-up original gangsta element pimped outa than key, or end().
Definizzle at line 699 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> const_iterator std::set< _Key, _Compare, _Alloc >::upper_bound (const key_type &__x) const [inline]
Findz tha end of a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Iterator pointin ta tha straight-up original gangsta element pimped outa than key, or end().
Definizzle at line 703 of file stl_set.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> value_compare std::set< _Key, _Compare, _Alloc >::value_comp () const [inline]
Returns tha comparison object wit which tha set was constructed.
Definizzle at line 285 of file stl_set.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.