" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::vector< _Tp, _Alloc > -
SYNOPSIS
Inherits std::_Vector_base< _Tp, _Alloc >.
Inherited by std::match_results< _Bi_ita > [private], n' std::match_results< _FwdIterT, _Alloc > [private].
Public Types
typedef _Alloc allocator_type
typedef
__gnu_cxx::__normal_iterator
< const_pointer, vector > const_iterator"
typedef
_Alloc_traits::const_pointa const_pointer"
typedef
_Alloc_traits::const_reference const_reference"
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator"
typedef ptrdiff_t difference_type
typedef
__gnu_cxx::__normal_iterator
< pointer, vector > iterator"
typedef _Base::pointa pointer
typedef _Alloc_traits::reference reference
typedef std::reverse_iterator
< iterator > reverse_iterator"
typedef size_t size_type
typedef _Tp value_type
Public Member Functions
vector ()
vector (const allocator_type &__a)
vector (size_type __n, const allocator_type &__a=allocator_type())
vector (size_type __n, const value_type &__value, const allocator_type &__a=allocator_type())
vector (const vector &__x)
vector (vector &&__x) noexcept
vector (const vector &__x, const allocator_type &__a)
vector (vector &&__rv, const allocator_type &__m)
vector (initializer_list< value_type > __l, const allocator_type &__a=allocator_type())
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> vector (_InputIterator __first, _InputIterator __last, const allocator_type &__a=allocator_type())
~vector () noexcept
void assign (size_type __n, const value_type &__val)
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void assign (_InputIterator __first, _InputIterator __last)
void assign (initializer_list< value_type > __l)
reference at (size_type __n)
const_reference at (size_type __n) const
reference back ()
const_reference back () const
iterator begin () noexcept
const_iterator begin () const noexcept
size_type capacity () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
_Tp * data () noexcept
const _Tp * data () const noexcept
template<typename... _Args> vector< _Tp, _Alloc >::iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> void emplace_back (_Args &&...__args)
bool empty () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
reference front ()
const_reference front () const
iterator insert (iterator __position, const value_type &__x)
iterator insert (iterator __position, value_type &&__x)
void insert (iterator __position, initializer_list< value_type > __l)
void insert (iterator __position, size_type __n, const value_type &__x)
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void insert (iterator __position, _InputIterator __first, _InputIterator __last)
size_type max_size () const noexcept
vector & operator= (const vector &__x)
vector & operator= (vector &&__x) noexcept(_Alloc_traits::_S_nothrow_move())
vector & operator= (initializer_list< value_type > __l)
reference operator[] (size_type __n)
const_reference operator[] (size_type __n) const
void pop_back ()
void push_back (const value_type &__x)
void push_back (value_type &&__x)
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
void reserve (size_type __n)
void resize (size_type __new_size)
void resize (size_type __new_size, const value_type &__x)
void shrink_to_fit ()
size_type size () const noexcept
void swap (vector &__x) noexcept(_Alloc_traits::_S_nothrow_swap())
Protected Member Functions
pointa _M_allocate (size_t __n)
template<typename _ForwardIterator > pointa _M_allocate_and_copy (size_type __n, _ForwardIterator __first, _ForwardIterator __last)
template<typename _InputIterator > void _M_assign_aux (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
template<typename _ForwardIterator > void _M_assign_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _Integer > void _M_assign_dispatch (_Integer __n, _Integer __val, __true_type)
template<typename _InputIterator > void _M_assign_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
size_type _M_check_len (size_type __n, const char *__s) const
void _M_deallocate (pointa __p, size_t __n)
void _M_default_append (size_type __n)
void _M_default_initialize (size_type __n)
template<typename... _Args> void _M_emplace_back_aux (_Args &&...__args)
void _M_erase_at_end (pointa __pos)
void _M_fill_assign (size_type __n, const value_type &__val)
void _M_fill_initialize (size_type __n, const value_type &__value)
void _M_fill_insert (iterator __pos, size_type __n, const value_type &__x)
_Tp_alloc_type & _M_get_Tp_allocator () noexcept
const _Tp_alloc_type & _M_get_Tp_allocator () const noexcept
template<typename _Integer > void _M_initialize_dispatch (_Integer __n, _Integer __value, __true_type)
template<typename _InputIterator > void _M_initialize_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
template<typename... _Args> void _M_insert_aux (iterator __position, _Args &&...__args)
template<typename _Integer > void _M_insert_dispatch (iterator __pos, _Integer __n, _Integer __val, __true_type)
template<typename _InputIterator > void _M_insert_dispatch (iterator __pos, _InputIterator __first, _InputIterator __last, __false_type)
void _M_range_check (size_type __n) const
template<typename _InputIterator > void _M_range_initialize (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
template<typename _ForwardIterator > void _M_range_initialize (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _InputIterator > void _M_range_insert (iterator __pos, _InputIterator __first, _InputIterator __last, std::input_iterator_tag)
template<typename _ForwardIterator > void _M_range_insert (iterator __pos, _ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
bool _M_shrink_to_fit ()
allocator_type get_allocator () const noexcept
Protected Attributes
_Vector_impl _M_impl
Detailed Description
template<typename _Tp, typename _Alloc = std::allocator<_Tp>>class std::vector< _Tp, _Alloc >
A standard container which offers fixed time access ta individual elements up in any order.
Template Parameters:
_Tp Type of element.
_Alloc Allocator type, defaults ta allocator<_Tp>.
Meets tha requirementz of a container, a reversible container, n' a sequence, includin tha optionizzle sequence requirements wit tha exception of push_front n' pop_front.
In some terminologizzle a vector can be busted lyrics bout as a thugged-out dynamic C-style array, it offers fast n' efficient access ta individual elements up in any order n' saves tha user from worryin bout memory n' size allocation. Right back up in yo muthafuckin ass. Subscriptin ( [] ) access be also provided as wit C-style arrays.
Definizzle at line 210 of file stl_vector.h.
Constructor & Destructor Documentation
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector () [inline]
Default constructor creates no elements.
Definizzle at line 248 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector (const allocator_type &__a) [inline], [explicit]
Creates a vector wit no elements.
Parameters:
__a An allocator object.
Definizzle at line 256 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector (size_type__n, const allocator_type &__a = allocator_type()) [inline], [explicit]
Creates a vector wit default constructed elements.
Parameters:
__n Da number of elements ta initially create.
__a An allocator.
This constructor fills tha vector wit __n default constructed elements.
Definizzle at line 269 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector (size_type__n, const value_type &__value, const allocator_type &__a = allocator_type()) [inline]
Creates a vector wit copiez of a exemplar element.
Parameters:
__n Da number of elements ta initially create.
__value An element ta copy.
__a An allocator.
This constructor fills tha vector wit __n copiez of __value.
Definizzle at line 281 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector (const vector< _Tp, _Alloc > &__x) [inline]
Vector copy constructor.
Parameters:
__x A vector of identical element n' allocator types.
Da newly-created vector uses a cold-ass lil copy of tha allocation object used by __x fo' realz. All tha elementz of __x is copied yo, but any extra memory up in __x (for fast expansion) aint gonna be copied.
Definizzle at line 310 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector (vector< _Tp, _Alloc > &&__x) [inline], [noexcept]
Vector move constructor.
Parameters:
__x A vector of identical element n' allocator types.
Da newly-created vector gotz nuff tha exact contentz of __x. Da contentz of __x is a valid yo, but unspecified vector.
Definizzle at line 327 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector (const vector< _Tp, _Alloc > &__x, const allocator_type &__a) [inline]
Copy constructor wit alternatizzle allocator.
Definizzle at line 331 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector (vector< _Tp, _Alloc > &&__rv, const allocator_type &__m) [inline]
Move constructor wit alternatizzle allocator.
Definizzle at line 340 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::vector (initializer_list< value_type >__l, const allocator_type &__a = allocator_type()) [inline]
Buildz a vector from a initializer list.
Parameters:
__l An initializer_list.
__a An allocator.
Smoke a vector consistin of copiez of tha elements up in tha initializer_list __l.
This will call tha element typez copy constructor N times (where N is __l.size()) n' do no memory reallocation.
Definizzle at line 364 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> std::vector< _Tp, _Alloc >::vector (_InputIterator__first, _InputIterator__last, const allocator_type &__a = allocator_type()) [inline]
Buildz a vector from a range.
Parameters:
__first An input iterator.
__last An input iterator.
__a An allocator.
Smoke a vector consistin of copiez of tha elements from [first,last).
If tha iterators is forward, bidirectional, or random-access, then dis will call tha elements' copy constructor N times (where N is distance(first,last)) n' do no memory reallocation. But if only input iterators is used, then dis will do at most 2N calls ta tha copy constructor, n' logN memory reallocations.
Definizzle at line 392 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::vector< _Tp, _Alloc >::~vector () [inline], [noexcept]
Da dtor only erases tha elements, n' note dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 414 of file stl_vector.h.
Member Function Documentation
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _ForwardIterator > pointa std::vector< _Tp, _Alloc >::_M_allocate_and_copy (size_type__n, _ForwardIterator__first, _ForwardIterator__last) [inline], [protected]
Memory expansion handlez. Uses tha member allocation function ta obtain n bytez of memory, n' then copies [first,last) tha fuck into it.
Definizzle at line 1135 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::_M_range_check (size_type__n) const [inline], [protected]
Safety check used only from at().
Definizzle at line 791 of file stl_vector.h.
Referenced by std::vector< _State >::at().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::assign (size_type__n, const value_type &__val) [inline]
Assigns a given value ta a vector.
Parameters:
__n Number of elements ta be assigned.
__val Value ta be assigned.
This function fills a vector wit __n copiez of tha given value. Note dat tha assignment straight-up chizzlez tha vector n' dat tha resultin vectorz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 479 of file stl_vector.h.
Referenced by std::vector< _State >::assign(), n' std::vector< _State >::operator=().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void std::vector< _Tp, _Alloc >::assign (_InputIterator__first, _InputIterator__last) [inline]
Assigns a range ta a vector.
Parameters:
__first An input iterator.
__last An input iterator.
This function fills a vector wit copiez of tha elements up in tha range [__first,__last).
Note dat tha assignment straight-up chizzlez tha vector n' dat tha resultin vectorz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 498 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::assign (initializer_list< value_type >__l) [inline]
Assigns a initializer list ta a vector.
Parameters:
__l An initializer_list.
This function fills a vector wit copiez of tha elements up in tha initializer list __l.
Note dat tha assignment straight-up chizzlez tha vector n' dat tha resultin vectorz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 524 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::vector< _Tp, _Alloc >::at (size_type__n) [inline]
Provides access ta tha data contained up in tha vector.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read/write reference ta data.
Exceptions:
std::out_of_range If __n be a invalid index.
This function serves up fo' less thuggy data access. Da parameta is first checked dat it is up in tha range of tha vector. Da function throws out_of_range if tha check fails.
Definizzle at line 810 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::vector< _Tp, _Alloc >::at (size_type__n) const [inline]
Provides access ta tha data contained up in tha vector.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read-only (constant) reference ta data.
Exceptions:
std::out_of_range If __n be a invalid index.
This function serves up fo' less thuggy data access. Da parameta is first checked dat it is up in tha range of tha vector. Da function throws out_of_range if tha check fails.
Definizzle at line 828 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::vector< _Tp, _Alloc >::back () [inline]
Returns a read/write reference ta tha data all up in tha last element of tha vector.
Definizzle at line 855 of file stl_vector.h.
Referenced by std::piecewise_constant_distribution< _RealType >::max(), n' std::piecewise_linear_distribution< _RealType >::max().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::vector< _Tp, _Alloc >::back () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha last element of tha vector.
Definizzle at line 863 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::vector< _Tp, _Alloc >::begin () [inline], [noexcept]
Returns a read/write iterator dat points ta tha straight-up original gangsta element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 538 of file stl_vector.h.
Referenced by std::vector< _State >::crend(), std::vector< _State >::empty(), std::vector< _State >::front(), __gnu_parallel::multiseq_partition(), __gnu_parallel::multiseq_selection(), __gnu_parallel::multiway_merge_exact_splitting(), std::operator<(), std::vector< _Tp, _Alloc >::operator=(), std::operator==(), std::vector< _State >::rend(), n' std::vector< _State >::vector().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::vector< _Tp, _Alloc >::begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 547 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::vector< _Tp, _Alloc >::capacitizzle () const [inline], [noexcept]
Returns tha total number of elements dat tha vector can hold before needin ta allocate mo' memory.
Definizzle at line 725 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::vector< _Tp, _Alloc >::cbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 611 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::vector< _Tp, _Alloc >::cend () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 620 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::clear () [inline], [noexcept]
Erases all tha elements. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 1125 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::vector< _Tp, _Alloc >::crbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 629 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::vector< _Tp, _Alloc >::crend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 638 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> _Tp* std::vector< _Tp, _Alloc >::data () [inline], [noexcept]
Returns a pointa such dat [data(), data() + size()) be a valid range. For a non-empty vector, data() == &front().
Definizzle at line 878 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename... _Args> iterator std::vector< _Tp, _Alloc >::emplace (iterator__position, _Args &&...__args)
Inserts a object up in vector before specified iterator.
Parameters:
__position An iterator tha fuck into tha vector.
__args Arguments.
Returns:
An iterator dat points ta tha banged data.
This function will bang a object of type T constructed wit T(std::forward<Args>(args)...) before tha specified location. Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Referenced by std::vector< _State >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> bool std::vector< _Tp, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha vector is empty. (Thus begin() would equal end().)
Definizzle at line 734 of file stl_vector.h.
Referenced by std::piecewise_constant_distribution< _RealType >::densities(), std::piecewise_linear_distribution< _RealType >::densities(), std::piecewise_constant_distribution< _RealType >::intervals(), std::piecewise_linear_distribution< _RealType >::intervals(), std::discrete_distribution< _IntType >::max(), std::piecewise_constant_distribution< _RealType >::max(), std::piecewise_linear_distribution< _RealType >::max(), std::piecewise_constant_distribution< _RealType >::min(), std::piecewise_linear_distribution< _RealType >::min(), n' std::discrete_distribution< _IntType >::probabilities().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::vector< _Tp, _Alloc >::end () [inline], [noexcept]
Returns a read/write iterator dat points one past tha last element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 556 of file stl_vector.h.
Referenced by std::vector< _State >::back(), std::vector< _State >::crbegin(), std::vector< _State >::empty(), __gnu_parallel::multiseq_partition(), __gnu_parallel::multiseq_selection(), __gnu_parallel::multiway_merge_exact_splitting(), std::operator<(), std::vector< _Tp, _Alloc >::operator=(), std::operator==(), std::vector< _State >::push_back(), std::vector< _State >::rbegin(), std::vector< _State >::resize(), n' std::vector< _State >::vector().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::vector< _Tp, _Alloc >::end () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 565 of file stl_vector.h.
template<typename _Tp , typename _Alloc > vector< _Tp, _Alloc >::iterator vector::erase (iterator__position)
Remove element at given position.
Parameters:
__position Iterator pointin ta element ta be erased.
Returns:
An iterator pointin ta tha next element (or end()).
This function will erase tha element all up in tha given posizzle n' thus shorten tha vector by one.
Note This operation could be high-rollin' n' if it is frequently used tha user should consider rockin std::list. Da user be also cautioned dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 135 of file vector.tcc.
References std::end().
template<typename _Tp , typename _Alloc > vector< _Tp, _Alloc >::iterator vector::erase (iterator__first, iterator__last)
Remove a range of elements.
Parameters:
__first Iterator pointin ta tha straight-up original gangsta element ta be erased.
__last Iterator pointin ta one past tha last element ta be erased.
Returns:
An iterator pointin ta tha element pointed ta by __last prior ta erasin (or end()).
This function will erase tha elements up in tha range [__first,__last) n' shorten tha vector accordingly.
Note This operation could be high-rollin' n' if it is frequently used tha user should consider rockin std::list. Da user be also cautioned dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 147 of file vector.tcc.
References std::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::vector< _Tp, _Alloc >::front () [inline]
Returns a read/write reference ta tha data all up in tha straight-up original gangsta element of tha vector.
Definizzle at line 839 of file stl_vector.h.
Referenced by std::vector< _State >::data(), std::piecewise_constant_distribution< _RealType >::min(), n' std::piecewise_linear_distribution< _RealType >::min().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::vector< _Tp, _Alloc >::front () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha straight-up original gangsta element of tha vector.
Definizzle at line 847 of file stl_vector.h.
template<typename _Tp , typename _Alloc > vector< _Tp, _Alloc >::iterator vector::insert (iterator__position, const value_type &__x)
Inserts given value tha fuck into vector before specified iterator.
Parameters:
__position An iterator tha fuck into tha vector.
__x Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given value before tha specified location. Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 108 of file vector.tcc.
References std::begin(), n' std::end().
Referenced by std::vector< _State >::insert(), n' std::vector< _State >::resize().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::vector< _Tp, _Alloc >::insert (iterator__position, value_type &&__x) [inline]
Inserts given rvalue tha fuck into vector before specified iterator.
Parameters:
__position An iterator tha fuck into tha vector.
__x Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given rvalue before tha specified location. Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 988 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::insert (iterator__position, initializer_list< value_type >__l) [inline]
Inserts a initializer_list tha fuck into tha vector.
Parameters:
__position An iterator tha fuck into tha vector.
__l An initializer_list.
This function will bang copiez of tha data up in tha initializer_list l tha fuck into tha vector before tha location specified by position.
Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 1005 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::insert (iterator__position, size_type__n, const value_type &__x) [inline]
Inserts a fuckin shitload of copiez of given data tha fuck into tha vector.
Parameters:
__position An iterator tha fuck into tha vector.
__n Number of elements ta be inserted.
__x Data ta be inserted.
This function will bang a specified number of copiez of tha given data before tha location specified by position.
Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 1023 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void std::vector< _Tp, _Alloc >::insert (iterator__position, _InputIterator__first, _InputIterator__last) [inline]
Inserts a range tha fuck into tha vector.
Parameters:
__position An iterator tha fuck into tha vector.
__first An input iterator.
__last An input iterator.
This function will bang copiez of tha data up in tha range [__first,__last) tha fuck into tha vector before tha location specified by pos.
Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 1044 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::vector< _Tp, _Alloc >::max_size () const [inline], [noexcept]
Returns tha size() of tha phattest possible vector.
Definizzle at line 650 of file stl_vector.h.
template<typename _Tp , typename _Alloc > vector< _Tp, _Alloc > & vector::operator= (const vector< _Tp, _Alloc > &__x)
Vector assignment operator.
Parameters:
__x A vector of identical element n' allocator types.
All tha elementz of __x is copied yo, but any extra memory up in __x (for fast expansion) aint gonna be copied. Unlike tha copy constructor, tha allocator object aint copied.
Definizzle at line 161 of file vector.tcc.
References std::_Destroy(), std::begin(), std::vector< _Tp, _Alloc >::begin(), std::end(), std::vector< _Tp, _Alloc >::end(), std::vector< _Tp, _Alloc >::size(), n' std::size().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> vector& std::vector< _Tp, _Alloc >::operator= (vector< _Tp, _Alloc > &&__x) [inline], [noexcept]
Vector move assignment operator.
Parameters:
__x A vector of identical element n' allocator types.
Da contentz of __x is moved tha fuck into dis vector (without copying, if tha allocators permit it). __x be a valid yo, but unspecified vector.
Definizzle at line 439 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> vector& std::vector< _Tp, _Alloc >::operator= (initializer_list< value_type >__l) [inline]
Vector list assignment operator.
Parameters:
__l An initializer_list.
This function fills a vector wit copiez of tha elements up in tha initializer list __l.
Note dat tha assignment straight-up chizzlez tha vector n' dat tha resultin vectorz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 461 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::vector< _Tp, _Alloc >::operator[] (size_type__n) [inline]
Subscript access ta tha data contained up in tha vector.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read/write reference ta data.
This operator allows fo' easy as fuck , array-style, data access. Note dat data access wit dis operator is unchecked n' out_of_range lookups is not defined. (For checked lookups peep at().)
Definizzle at line 770 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::vector< _Tp, _Alloc >::operator[] (size_type__n) const [inline]
Subscript access ta tha data contained up in tha vector.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read-only (constant) reference ta data.
This operator allows fo' easy as fuck , array-style, data access. Note dat data access wit dis operator is unchecked n' out_of_range lookups is not defined. (For checked lookups peep at().)
Definizzle at line 785 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::pop_back () [inline]
Removes last element. This be a typical stack operation. Well shiiiit, it shrinks tha vector by one.
Note dat no data is returned, n' if tha last elementz data is needed, it should be retrieved before pop_back() is called.
Definizzle at line 937 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::push_back (const value_type &__x) [inline]
Add data ta tha end of tha vector.
Parameters:
__x Data ta be added.
This be a typical stack operation. Da function creates a element all up in tha end of tha vector n' assigns tha given data ta it. Cuz of tha nature of a vector dis operation can be done up in constant time if tha vector has preallocated space available.
Definizzle at line 901 of file stl_vector.h.
Referenced by __gnu_parallel::multiseq_partition(), n' __gnu_parallel::multiseq_selection().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::vector< _Tp, _Alloc >::rbegin () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta tha last element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 574 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::vector< _Tp, _Alloc >::rbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 583 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::vector< _Tp, _Alloc >::rend () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta one before tha straight-up original gangsta element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 592 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::vector< _Tp, _Alloc >::rend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 601 of file stl_vector.h.
template<typename _Tp , typename _Alloc > void vector::reserve (size_type__n)
Attempt ta preallocate enough memory fo' specified number of elements.
Parameters:
__n Number of elements required.
Exceptions:
std::length_error If n exceedz max_size().
This function attempts ta reserve enough memory fo' tha vector ta hold tha specified number of elements. If tha number axed is mo' than max_size(), length_error is thrown.
Da advantage of dis function is dat if optimal code be a necessitizzle n' tha user can determine tha number of elements dat is ghon be required, tha user can reserve tha memory up in advance, n' thus prevent a possible reallocation of memory n' copyin of vector data.
Definizzle at line 66 of file vector.tcc.
References std::_Destroy(), n' std::size().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::resize (size_type__new_size) [inline]
Resizes tha vector ta tha specified number of elements.
Parameters:
__new_size Number of elements tha vector should contain.
This function will resize tha vector ta tha specified number of elements. If tha number is smalla than tha vectorz current size tha vector is truncated, otherwise default constructed elements is appended.
Definizzle at line 664 of file stl_vector.h.
Referenced by __gnu_parallel::__shrink_and_double(), n' __gnu_parallel::multiway_merge_exact_splitting().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::resize (size_type__new_size, const value_type &__x) [inline]
Resizes tha vector ta tha specified number of elements.
Parameters:
__new_size Number of elements tha vector should contain.
__x Data wit which freshly smoked up elements should be populated.
This function will resize tha vector ta tha specified number of elements. If tha number is smalla than tha vectorz current size tha vector is truncated, otherwise tha vector is extended n' freshly smoked up elements is populated wit given data.
Definizzle at line 684 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::shrink_to_fit () [inline]
A non-bindin request ta reduce capacity() ta size().
Definizzle at line 716 of file stl_vector.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::vector< _Tp, _Alloc >::size () const [inline], [noexcept]
Returns tha number of elements up in tha vector.
Definizzle at line 645 of file stl_vector.h.
Referenced by __gnu_parallel::__shrink(), __gnu_parallel::__shrink_and_double(), std::vector< _State >::_M_range_check(), __gnu_parallel::list_partition(), std::discrete_distribution< _IntType >::max(), std::vector< _Tp, _Alloc >::operator=(), std::operator==(), n' std::vector< _State >::resize().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::vector< _Tp, _Alloc >::swap (vector< _Tp, _Alloc > &__x) [inline], [noexcept]
Swaps data wit another vector.
Parameters:
__x A vector of tha same element n' allocator types.
This exchanges tha elements between two vectors up in constant time. (Three pointers, so it should be like fast.) Note dat tha global std::swap() function is specialized such dat std::swap(v1,v2) will feed ta dis function.
Definizzle at line 1108 of file stl_vector.h.
Referenced by std::swap().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.