" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::reverse_iterator< _Iterator > -
SYNOPSIS
Inherits std::iterator< iterator_traits< _Iterator >::iterator_category, iterator_traits< _Iterator >::value_type, iterator_traits< _Iterator >::difference_type, iterator_traits< _Iterator >::pointer, iterator_traits< _Iterator >::reference >.
Public Types
typedef
__traits_type::difference_type difference_type"
typedef iterator_traits
< _Iterator >
::iterator_category iterator_category"
typedef _Iterator iterator_type
typedef __traits_type::pointa pointer
typedef __traits_type::reference reference
typedef iterator_traits
< _Iterator >::value_type value_type"
Public Member Functions
reverse_iterator ()
reverse_iterator (iterator_type __x)
reverse_iterator (const reverse_iterator &__x)
template<typename _Ita > reverse_iterator (const reverse_iterator< _Ita > &__x)
iterator_type base () const
reference operator* () const
reverse_iterator operator+ (difference_type __n) const
reverse_iterator & operator++ ()
reverse_iterator operator++ (int)
reverse_iterator & operator+= (difference_type __n)
reverse_iterator operator- (difference_type __n) const
reverse_iterator & operator-- ()
reverse_iterator operator-- (int)
reverse_iterator & operator-= (difference_type __n)
pointa operator-> () const
reference operator[] (difference_type __n) const
Protected Types
typedef iterator_traits
< _Iterator > __traits_type"
Protected Attributes
_Iterator current
Detailed Description
template<typename _Iterator>class std::reverse_iterator< _Iterator >
Bidirectionizzle n' random access iterators have correspondin reverse iterator adaptors dat iterate all up in tha data structure up in tha opposite direction. They have tha same signatures as tha correspondin iterators. Da fundamenstrual relation between a reverse iterator n' its correspondin iterator i is established by tha identity:
&*(reverse_iterator(i)) == &*(i - 1)
This mappin is dictated by tha fact dat while there be always a pointa past tha end of a array, there might not be a valid pointa before tha beginnin of a array. [24.4.1]/1,2
Reverse iterators can be tricky n' surprisin at first. Their semantics make sense, however, n' tha trickinizz be a side effect of tha requirement dat tha iterators must be safe.
Definizzle at line 96 of file stl_iterator.h.
Member Typedef Documentation
typedef iterator_traits< _Iterator >::iterator_category std::iterator< iterator_traits< _Iterator >::iterator_category , iterator_traits< _Iterator >::value_type , iterator_traits< _Iterator >::difference_type , iterator_traits< _Iterator >::pointa , iterator_traits< _Iterator >::reference >::iterator_category [inherited]
One of tha tag types.
Definizzle at line 121 of file stl_iterator_base_types.h.
typedef iterator_traits< _Iterator >::value_type std::iterator< iterator_traits< _Iterator >::iterator_category , iterator_traits< _Iterator >::value_type , iterator_traits< _Iterator >::difference_type , iterator_traits< _Iterator >::pointa , iterator_traits< _Iterator >::reference >::value_type [inherited]
Da type 'pointed to' by tha iterator.
Definizzle at line 123 of file stl_iterator_base_types.h.
Constructor & Destructor Documentation
template<typename _Iterator> std::reverse_iterator< _Iterator >::reverse_iterator () [inline]
Da default constructor value-initializes member current. If it aint nuthin but a pointer, dat means it is zero-initialized.
Definizzle at line 120 of file stl_iterator.h.
Referenced by std::reverse_iterator< _Iterator >::operator+(), n' std::reverse_iterator< _Iterator >::operator-().
template<typename _Iterator> std::reverse_iterator< _Iterator >::reverse_iterator (iterator_type__x) [inline], [explicit]
This iterator will move up in tha opposite direction dat x do.
Definizzle at line 126 of file stl_iterator.h.
template<typename _Iterator> std::reverse_iterator< _Iterator >::reverse_iterator (const reverse_iterator< _Iterator > &__x) [inline]
Da copy constructor is normal.
Definizzle at line 131 of file stl_iterator.h.
template<typename _Iterator> template<typename _Ita > std::reverse_iterator< _Iterator >::reverse_iterator (const reverse_iterator< _Ita > &__x) [inline]
A reverse_iterator across other types can be copied if tha underlyin iterator can be converted ta tha type of current.
Definizzle at line 139 of file stl_iterator.h.
Member Function Documentation
template<typename _Iterator> iterator_type std::reverse_iterator< _Iterator >::base () const [inline]
Returns:
current, tha iterator used fo' underlyin work.
Definizzle at line 146 of file stl_iterator.h.
Referenced by std::operator==().
template<typename _Iterator> reference std::reverse_iterator< _Iterator >::operator* () const [inline]
Returns:
A reference ta tha value at --current
This requires dat --current is dereferenceable.
Warning:
This implementation requires dat fo' a iterator of tha underlyin iterator type, x, a reference obtained by *x remains valid afta x has been modified or destroyed. This be a funky-ass bug: http://gcc.gnu.org/PR51823
Definizzle at line 160 of file stl_iterator.h.
Referenced by std::reverse_iterator< _Iterator >::operator->().
template<typename _Iterator> reverse_iterator std::reverse_iterator< _Iterator >::operator+ (difference_type__n) const [inline]
Returns:
A reverse_iterator dat refers ta current - __n
Da underlyin iterator must be a Random Access Iterator.
Definizzle at line 231 of file stl_iterator.h.
References std::reverse_iterator< _Iterator >::reverse_iterator().
template<typename _Iterator> reverse_iterator& std::reverse_iterator< _Iterator >::operator++ () [inline]
Returns:
*this
Decrements tha underlyin iterator.
Definizzle at line 181 of file stl_iterator.h.
template<typename _Iterator> reverse_iterator std::reverse_iterator< _Iterator >::operator++ (int) [inline]
Returns:
Da original gangsta value of *this
Decrements tha underlyin iterator.
Definizzle at line 193 of file stl_iterator.h.
template<typename _Iterator> reverse_iterator& std::reverse_iterator< _Iterator >::operator+= (difference_type__n) [inline]
Returns:
*this
Moves tha underlyin iterator backwardz __n steps. Da underlyin iterator must be a Random Access Iterator.
Definizzle at line 241 of file stl_iterator.h.
template<typename _Iterator> reverse_iterator std::reverse_iterator< _Iterator >::operator- (difference_type__n) const [inline]
Returns:
A reverse_iterator dat refers ta current - __n
Da underlyin iterator must be a Random Access Iterator.
Definizzle at line 253 of file stl_iterator.h.
References std::reverse_iterator< _Iterator >::reverse_iterator().
template<typename _Iterator> reverse_iterator& std::reverse_iterator< _Iterator >::operator-- () [inline]
Returns:
*this
Increments tha underlyin iterator.
Definizzle at line 206 of file stl_iterator.h.
template<typename _Iterator> reverse_iterator std::reverse_iterator< _Iterator >::operator-- (int) [inline]
Returns:
A reverse_iterator wit tha previous value of *this
Increments tha underlyin iterator.
Definizzle at line 218 of file stl_iterator.h.
template<typename _Iterator> reverse_iterator& std::reverse_iterator< _Iterator >::operator-= (difference_type__n) [inline]
Returns:
*this
Moves tha underlyin iterator forwardz __n steps. Da underlyin iterator must be a Random Access Iterator.
Definizzle at line 263 of file stl_iterator.h.
template<typename _Iterator> pointa std::reverse_iterator< _Iterator >::operator-> () const [inline]
Returns:
A pointa ta tha value at --current
This requires dat --current is dereferenceable.
Definizzle at line 172 of file stl_iterator.h.
References std::reverse_iterator< _Iterator >::operator*().
template<typename _Iterator> reference std::reverse_iterator< _Iterator >::operator[] (difference_type__n) const [inline]
Returns:
Da value at current - __n - 1
Da underlyin iterator must be a Random Access Iterator.
Definizzle at line 275 of file stl_iterator.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.