" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::basic_ofstream< _CharT, _Traits > -
SYNOPSIS
Inherits std::basic_ostream< _CharT, _Traits >.
Public Types
typedef ctype< _CharT > __ctype_type
typedef basic_filebuf
< char_type, traits_type > __filebuf_type"
typedef basic_ios< _CharT,
_Traits > __ios_type"
typedef num_put< _CharT,
ostreambuf_iterator< _CharT,
_Traits > > __num_put_type"
typedef basic_ostream
< char_type, traits_type > __ostream_type"
typedef basic_streambuf
< _CharT, _Traits > __streambuf_type"
typedef _CharT char_type
enum event { erase_event, imbue_event, copyfmt_event }
typedef void(* event_callback )(event __e, ios_base &__b, int __i)
typedef _Ios_Fmtflags fmtflags
typedef traits_type::int_type int_type
typedef int io_state
typedef _Ios_Iostate iostate
typedef traits_type::off_type off_type
typedef int open_mode
typedef _Ios_Openmode openmode
typedef traits_type::pos_type pos_type
typedef int seek_dir
typedef _Ios_Seekdir seekdir
typedef std::streamoff streamoff
typedef std::streampos streampos
typedef _Traits traits_type
typedef num_get< _CharT,
istreambuf_iterator< _CharT,
_Traits > > __num_get_type"
Public Member Functions
basic_ofstream ()
basic_ofstream (const char *__s, ios_base::openmode __mode=ios_base::out|ios_base::trunc)
basic_ofstream (const std::string &__s, ios_base::openmode __mode=ios_base::out|ios_base::trunc)
~basic_ofstream ()
const locale & _M_getloc () const
template<typename _ValueT > basic_ostream< _CharT, _Traits > & _M_insert (_ValueT __v)
void _M_setstate (iostate __state)
bool bad () const
void clear (iostate __state=goodbit)
void close ()
basic_ios & copyfmt (const basic_ios &__rhs)
bool eof () const
iostate exceptions () const
void exceptions (iostate __except)
bool fail () const
char_type fill () const
char_type fill (char_type __ch)
fmtflags flags () const
fmtflags flags (fmtflags __fmtfl)
__ostream_type & flush ()
locale getloc () const
bool good () const
locale imbue (const locale &__loc)
bool is_open ()
bool is_open () const
long & iword (int __ix)
char narrow (char_type __c, char __dfault) const
void open (const char *__s, ios_base::openmode __mode=ios_base::out|ios_base::trunc)
void open (const std::string &__s, ios_base::openmode __mode=ios_base::out|ios_base::trunc)
__ostream_type & operator<< (const void *__p)
__ostream_type & operator<< (__streambuf_type *__sb)
streamsize precision () const
streamsize precision (streamsize __prec)
void *& pword (int __ix)
basic_streambuf< _CharT,
_Traits > * rdbuf (basic_streambuf< _CharT, _Traits > *__sb)"
__filebuf_type * rdbuf () const
iostate rdstate () const
void register_callback (event_callback __fn, int __index)
__ostream_type & seekp (pos_type)
__ostream_type & seekp (off_type, ios_base::seekdir)
fmtflags setf (fmtflags __fmtfl)
fmtflags setf (fmtflags __fmtfl, fmtflags __mask)
void setstate (iostate __state)
pos_type tellp ()
basic_ostream< _CharT, _Traits > * tie () const
basic_ostream< _CharT, _Traits > * tie (basic_ostream< _CharT, _Traits > *__tiestr)
void unsetf (fmtflags __mask)
char_type widen (char __c) const
streamsize width () const
streamsize width (streamsize __wide)
__ostream_type & operator<< (__ostream_type &(*__pf)(__ostream_type &))
__ostream_type & operator<< (__ios_type &(*__pf)(__ios_type &))
__ostream_type & operator<< (ios_base &(*__pf)(ios_base &))
Inserters
All tha operator<< functions (aka formatted output functions) have some common behavior. Each starts by constructin a temporary object of type std::basic_ostream::sentry. This can have nuff muthafuckin effects, concludin wit tha settin of a status flag; peep tha sentry documentation fo' more.
If tha sentry status is good, tha function tries ta generate whatever data be appropriate fo' tha type of tha argument.
If a exception is thrown durin insertion, ios_base::badbit is ghon be turned on up in tha streamz error state without causin a ios_base::failure ta be thrown. Da original gangsta exception will then be rethrown.
__ostream_type & operator<< (long __n)
__ostream_type & operator<< (unsigned long __n)
__ostream_type & operator<< (bool __n)
__ostream_type & operator<< (short __n)
__ostream_type & operator<< (unsigned short __n)
__ostream_type & operator<< (int __n)
__ostream_type & operator<< (unsigned int __n)
__ostream_type & operator<< (long long __n)
__ostream_type & operator<< (unsigned long long __n)
__ostream_type & operator<< (double __f)
__ostream_type & operator<< (float __f)
__ostream_type & operator<< (long double __f)
Unformatted Output Functions
All tha unformatted output functions have some common behavior. Each starts by constructin a temporary object of type std::basic_ostream::sentry. This has nuff muthafuckin effects, concludin wit tha settin of a status flag; peep tha sentry documentation fo' more.
If tha sentry status is good, tha function tries ta generate whatever data be appropriate fo' tha type of tha argument.
If a exception is thrown durin insertion, ios_base::badbit is ghon be turned on up in tha streamz error state. If badbit is on up in tha streamz exceptions mask, tha exception is ghon be rethrown without completin its actions.
__ostream_type & put (char_type __c)
void _M_write (const char_type *__s, streamsize __n)
__ostream_type & write (const char_type *__s, streamsize __n)
operator void * () const
bool operator! () const
Static Public Member Functions
static bool sync_with_stdio (bool __sync=true)
static int xalloc () throw ()
Static Public Attributes
static const fmtflags adjustfield
static const openmode app
static const openmode ate
static const iostate badbit
static const fmtflags basefield
static const seekdir beg
static const openmode binary
static const fmtflags boolalpha
static const seekdir cur
static const fmtflags dec
static const seekdir end
static const iostate eofbit
static const iostate failbit
static const fmtflags fixed
static const fmtflags floatfield
static const iostate goodbit
static const fmtflags hex
static const openmode in
static const fmtflags internal
static const fmtflags left
static const fmtflags oct
static const openmode out
static const fmtflags right
static const fmtflags scientific
static const fmtflags showbase
static const fmtflags showpoint
static const fmtflags showpos
static const fmtflags skipws
static const openmode trunc
static const fmtflags unitbuf
static const fmtflags uppercase
Protected Types
enum { _S_local_word_size }
Protected Member Functions
void _M_cache_locale (const locale &__loc)
void _M_call_callbacks (event __ev) throw ()
void _M_dispose_callbacks (void) throw ()
_Lyrics & _M_grow_words (int __index, bool __iword)
void _M_init () throw ()
template<typename _ValueT > __ostream_type & _M_insert (_ValueT __v)
void init (basic_streambuf< _CharT, _Traits > *__sb)
Protected Attributes
_Callback_list * _M_callbacks
const __ctype_type * _M_ctype
iostate _M_exception
char_type _M_fill
bool _M_fill_init
fmtflags _M_flags
locale _M_ios_locale
_Lyrics _M_local_word [_S_local_word_size]
const __num_get_type * _M_num_get
const __num_put_type * _M_num_put
streamsize _M_precision
basic_streambuf< _CharT,
_Traits > * _M_streambuf"
iostate _M_streambuf_state
basic_ostream< _CharT, _Traits > * _M_tie
streamsize _M_width
_Lyrics * _M_word
int _M_word_size
_Lyrics _M_word_zero
Detailed Description
template<typename _CharT, typename _Traits>class std::basic_ofstream< _CharT, _Traits >
Controllin output fo' files.
Template Parameters:
_CharT Type of characta stream.
_Traits Traits fo' characta type, defaults ta char_traits<_CharT>.
This class supports readin from named files, rockin tha inherited functions from std::basic_ostream. To control tha associated sequence, a instizzle of std::basic_filebuf is used, which dis page refers ta as sb.
Definizzle at line 599 of file fstream.
Member Typedef Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> typedef num_get<_CharT, istreambuf_iterator<_CharT, _Traits> > std::basic_ios< _CharT, _Traits >::__num_get_type [inherited]
These is non-standard types.
Definizzle at line 90 of file basic_ios.h.
typedef void(* std::ios_base::event_callback)(event __e, ios_base &__b, int __i) [inherited]
Da type of a event callback function.
Parameters:
__e One of tha thugz of tha event enum.
__b Reference ta tha ios_base object.
__i Da integer provided when tha callback was registered.
Event callbacks is user defined functions dat git called durin nuff muthafuckin ios_base n' basic_ios functions, specifically imbue(), copyfmt(), n' ~ios().
Definizzle at line 436 of file ios_base.h.
typedef _Ios_Fmtflags std::ios_base::fmtflags [inherited]
This be a funky-ass bitmask type. _Ios_Fmtflags is implementation-defined yo, but it is valid ta big-ass up bitwise operations on these joints n' expect tha Right Thin ta happen. Defined objectz of type fmtflags are:
boolalpha
dec
fixed
hex
internal
left
oct
right
scientific
showbase
showpoint
showpos
skipws
unitbuf
uppercase
adjustfield
basefield
floatfield
Definizzle at line 255 of file ios_base.h.
typedef _Ios_Iostate std::ios_base::iostate [inherited]
This be a funky-ass bitmask type. _Ios_Iostate is implementation-defined yo, but it is valid ta big-ass up bitwise operations on these joints n' expect tha Right Thin ta happen. Defined objectz of type iostate are:
badbit
eofbit
failbit
goodbit
Definizzle at line 330 of file ios_base.h.
typedef _Ios_Openmode std::ios_base::openmode [inherited]
This be a funky-ass bitmask type. _Ios_Openmode is implementation-defined yo, but it is valid ta big-ass up bitwise operations on these joints n' expect tha Right Thin ta happen. Defined objectz of type openmode are:
app
ate
binary
in
out
trunc
Definizzle at line 361 of file ios_base.h.
typedef _Ios_Seekdir std::ios_base::seekdir [inherited]
This be a enumerated type. _Ios_Seekdir is implementation-defined. Defined jointz of type seekdir are:
beg
cur, equivalent ta SEEK_CUR up in tha C standard library.
end, equivalent ta SEEK_END up in tha C standard library.
Definizzle at line 393 of file ios_base.h.
Member Enumeration Documentation
enum std::ios_base::event [inherited]
Da set of events dat may be passed ta a event callback. erase_event is used durin ~ios() n' copyfmt(). imbue_event is used durin imbue(). copyfmt_event is used durin copyfmt().
Definizzle at line 419 of file ios_base.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _Traits > std::basic_ofstream< _CharT, _Traits >::basic_ofstream () [inline]
Default constructor. Initializes sb rockin its default constructor, n' passes &sb ta tha base class initializer. Do not open any filez (you aint given it a gangbangin' filename ta open).
Definizzle at line 625 of file fstream.
References std::basic_ios< _CharT, _Traits >::init().
template<typename _CharT , typename _Traits > std::basic_ofstream< _CharT, _Traits >::basic_ofstream (const char *__s, ios_base::openmode__mode = ios_base::out|ios_base::trunc) [inline], [explicit]
Smoke a output file stream.
Parameters:
__s Null terminated strang specifyin tha filename.
__mode Open file up in specified mode (see std::ios_base).
ios_base::out | ios_base::trunc be automatically included up in __mode.
Tip: When rockin std::strin ta hold tha filename, you must use .c_str() before passin it ta dis constructor.
Definizzle at line 640 of file fstream.
References std::basic_ios< _CharT, _Traits >::init(), n' std::basic_ofstream< _CharT, _Traits >::open().
template<typename _CharT , typename _Traits > std::basic_ofstream< _CharT, _Traits >::basic_ofstream (const std::string &__s, ios_base::openmode__mode = ios_base::out|ios_base::trunc) [inline], [explicit]
Smoke a output file stream.
Parameters:
__s std::strin specifyin tha filename.
__mode Open file up in specified mode (see std::ios_base).
ios_base::out | ios_base::trunc be automatically included up in __mode.
Definizzle at line 658 of file fstream.
References std::basic_ios< _CharT, _Traits >::init(), n' std::basic_ofstream< _CharT, _Traits >::open().
template<typename _CharT , typename _Traits > std::basic_ofstream< _CharT, _Traits >::~basic_ofstream () [inline]
Da destructor do nothing. Da file is closed by tha filebuf object, not tha formattin stream.
Definizzle at line 673 of file fstream.
Member Function Documentation
const locale& std::ios_base::_M_getloc () const [inline], [inherited]
Locale access.
Returns:
A reference ta tha current locale.
Like getloc above yo, but returns a reference instead of generatin a cold-ass lil copy.
Definizzle at line 706 of file ios_base.h.
Referenced by std::money_get< _CharT, _InIta >::do_get(), std::num_get< _CharT, _InIta >::do_get(), std::time_get< _CharT, _InIta >::do_get_date(), std::time_get< _CharT, _InIta >::do_get_monthname(), std::time_get< _CharT, _InIta >::do_get_time(), std::time_get< _CharT, _InIta >::do_get_weekday(), std::time_get< _CharT, _InIta >::do_get_year(), std::time_put< _CharT, _OutIta >::do_put(), std::num_put< _CharT, _OutIta >::do_put(), n' std::time_put< _CharT, _OutIta >::put().
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_ostream< _CharT, _Traits >::_M_write (const char_type *__s, streamsize__n) [inline], [inherited]
Core write functionality, without sentry.
Parameters:
__s Da array ta insert.
__n Maximum number of charactas ta insert.
Definizzle at line 311 of file ostream.
Referenced by std::basic_ostream< _CharT, _Traits >::write().
template<typename _CharT, typename _Traits = char_traits<_CharT>> bool std::basic_ios< _CharT, _Traits >::bad () const [inline], [inherited]
Fast error checking.
Returns:
True if tha badbit is set.
Note dat other iostate flags may also be set.
Definizzle at line 205 of file basic_ios.h.
template<typename _CharT , typename _Traits > void std::basic_ios< _CharT, _Traits >::clear (iostate__state = goodbit) [inherited]
[Re]sets tha error state.
Parameters:
__state Da freshly smoked up state flag(s) ta set.
See std::ios_base::iostate fo' tha possible bit joints. Most playas aint gonna need ta pass a argument.
Definizzle at line 41 of file basic_ios.tcc.
Referenced by std::basic_ios< char, char_traits< char > >::exceptions(), std::basic_ifstream< _CharT, _Traits >::open(), std::basic_ofstream< _CharT, _Traits >::open(), std::basic_fstream< _CharT, _Traits >::open(), std::basic_istream< _CharT, _Traits >::putback(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_ios< char, char_traits< char > >::setstate(), n' std::basic_istream< _CharT, _Traits >::unget().
template<typename _CharT , typename _Traits > void std::basic_ofstream< _CharT, _Traits >::close () [inline]
Close tha file. Calls std::basic_filebuf::close(). If dat function fails, failbit is set up in tha streamz error state.
Definizzle at line 753 of file fstream.
References std::basic_filebuf< _CharT, _Traits >::close(), std::ios_base::failbit, n' std::basic_ios< _CharT, _Traits >::setstate().
template<typename _CharT , typename _Traits > basic_ios< _CharT, _Traits > & std::basic_ios< _CharT, _Traits >::copyfmt (const basic_ios< _CharT, _Traits > &__rhs) [inherited]
Copies fieldz of __rhs tha fuck into this.
Parameters:
__rhs Da source joints fo' tha copies.
Returns:
Reference ta dis object.
All fieldz of __rhs is copied tha fuck into dis object except dat rdbuf() n' rdstate() remain unchanged fo' realz. All joints up in tha pword n' iword arrays is copied. Before copying, each callback is invoked wit erase_event fo' realz. Afta copying, each (new) callback is invoked wit copyfmt_event. Da final step is ta copy exceptions().
Definizzle at line 63 of file basic_ios.tcc.
References std::basic_ios< _CharT, _Traits >::exceptions(), std::basic_ios< _CharT, _Traits >::fill(), std::ios_base::flags(), std::ios_base::getloc(), std::ios_base::precision(), std::basic_ios< _CharT, _Traits >::tie(), std::tie(), n' std::ios_base::width().
template<typename _CharT, typename _Traits = char_traits<_CharT>> bool std::basic_ios< _CharT, _Traits >::eof () const [inline], [inherited]
Fast error checking.
Returns:
True if tha eofbit is set.
Note dat other iostate flags may also be set.
Definizzle at line 184 of file basic_ios.h.
template<typename _CharT, typename _Traits = char_traits<_CharT>> iostate std::basic_ios< _CharT, _Traits >::exceptions () const [inline], [inherited]
Throwin exceptions on errors.
Returns:
Da current exceptions mask.
This chizzlez not a god damn thang up in tha stream. Right back up in yo muthafuckin ass. See tha one-argument version of exceptions(iostate) fo' tha meanin of tha return value.
Definizzle at line 216 of file basic_ios.h.
Referenced by std::basic_ios< _CharT, _Traits >::copyfmt().
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_ios< _CharT, _Traits >::exceptions (iostate__except) [inline], [inherited]
Throwin exceptions on errors.
Parameters:
__except Da freshly smoked up exceptions mask.
By default, error flags is set silently. Yo ass can set a exceptions mask fo' each stream; if a lil' bit up in tha mask becomes set up in tha error flags, then a exception of type std::ios_base::failure is thrown.
If tha error flag be already set when tha exceptions mask be added, tha exception is immediately thrown. Try hustlin tha followin under GCC 3.1 or later:
#include <iostream>
#include <fstream>
#include <exception>
int main()
{
    std::set_terminizzle (__gnu_cxx::__verbose_terminate_handlez);
    std::ifstream f ("/etc/motd");
    std::cerr << "Settin badbit\n";
    f.setstate (std::ios_base::badbit);
    std::cerr << "Settin exception mask\n";
    f.exceptions (std::ios_base::badbit);
}
Definizzle at line 251 of file basic_ios.h.
template<typename _CharT, typename _Traits = char_traits<_CharT>> bool std::basic_ios< _CharT, _Traits >::fail () const [inline], [inherited]
Fast error checking.
Returns:
True if either tha badbit or tha failbit is set.
Checkin tha badbit up in fail() is oldschool practice. Note dat other iostate flags may also be set.
Definizzle at line 195 of file basic_ios.h.
Referenced by std::basic_ios< char, char_traits< char > >::operator void *(), std::basic_ios< char, char_traits< char > >::operator!(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_ostream< _CharT, _Traits >::seekp(), std::basic_istream< _CharT, _Traits >::tellg(), std::basic_ostream< _CharT, _Traits >::tellp(), n' std::regex_traits< _Ch_type >::value().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type std::basic_ios< _CharT, _Traits >::fill () const [inline], [inherited]
Retrieves tha empty character.
Returns:
Da current fill character.
It defaults ta a space (' ') up in tha current locale.
Definizzle at line 364 of file basic_ios.h.
Referenced by std::basic_ios< _CharT, _Traits >::copyfmt(), n' std::basic_ios< char, char_traits< char > >::fill().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type std::basic_ios< _CharT, _Traits >::fill (char_type__ch) [inline], [inherited]
Sets a freshly smoked up empty character.
Parameters:
__ch Da freshly smoked up character.
Returns:
Da previous fill character.
Da fill characta is used ta fill up space when P+ charactas done been axed (e.g., via setw), Q charactas is straight-up used, n' Q<P. Well shiiiit, it defaults ta a space (' ') up in tha current locale.
Definizzle at line 384 of file basic_ios.h.
fmtflags std::ios_base::flags () const [inline], [inherited]
Access ta format flags.
Returns:
Da format control flags fo' both input n' output.
Definizzle at line 551 of file ios_base.h.
Referenced by std::basic_ios< _CharT, _Traits >::copyfmt(), std::num_get< _CharT, _InIta >::do_get(), std::num_put< _CharT, _OutIta >::do_put(), std::basic_ostream< _CharT, _Traits >::operator<<(), std::operator<<(), std::operator>>(), n' std::basic_istream< _CharT, _Traits >::sentry::sentry().
fmtflags std::ios_base::flags (fmtflags__fmtfl) [inline], [inherited]
Settin freshly smoked up format flags all at once.
Parameters:
__fmtfl Da freshly smoked up flags ta set.
Returns:
Da previous format control flags.
This function overwrites all tha format flags wit __fmtfl.
Definizzle at line 562 of file ios_base.h.
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::basic_ostream< _CharT, _Traits >::flush () [inherited]
Synchronizin tha stream buffer.
Returns:
*this
If rdbuf() be a null pointer, chizzlez nothing.
Otherwise, calls rdbuf()->pubsync(), n' if dat returns -1, sets badbit.
Definizzle at line 211 of file ostream.tcc.
References std::ios_base::badbit, std::ios_base::goodbit, std::basic_ios< _CharT, _Traits >::rdbuf(), n' std::basic_ios< _CharT, _Traits >::setstate().
locale std::ios_base::getloc () const [inline], [inherited]
Locale access.
Returns:
A copy of tha current locale.
If imbue(loc) has previously been called, then dis function returns loc. Otherwise, it returns a cold-ass lil copy of std::locale(), tha global C++ locale.
Definizzle at line 695 of file ios_base.h.
Referenced by std::basic_ios< _CharT, _Traits >::copyfmt(), std::money_put< _CharT, _OutIta >::do_put(), std::operator>>(), n' std::ws().
template<typename _CharT, typename _Traits = char_traits<_CharT>> bool std::basic_ios< _CharT, _Traits >::phat () const [inline], [inherited]
Fast error checking.
Returns:
True if no error flags is set.
A wrapper round rdstate.
Definizzle at line 174 of file basic_ios.h.
Referenced by std::basic_ostream< _CharT, _Traits >::sentry::sentry(), n' std::basic_istream< _CharT, _Traits >::sentry::sentry().
template<typename _CharT , typename _Traits > locale std::basic_ios< _CharT, _Traits >::imbue (const locale &__loc) [inherited]
Moves ta a freshly smoked up locale.
Parameters:
__loc Da freshly smoked up locale.
Returns:
Da previous locale.
Calls ios_base::imbue(loc), n' if a stream buffer be associated wit dis stream, calls dat bufferz pubimbue(loc).
Additionizzle l10n notes is at http://gcc.gnu.org/onlinedocs/libstdc++/manual/localization.html
Definizzle at line 114 of file basic_ios.tcc.
References std::ios_base::imbue().
Referenced by std::operator<<().
template<typename _CharT, typename _Traits> void std::basic_ios< _CharT, _Traits >::init (basic_streambuf< _CharT, _Traits > *__sb) [protected], [inherited]
All setup is performed here. This is called from tha hood constructor. Well shiiiit, it aint virtual n' cannot be redefined.
Definizzle at line 126 of file basic_ios.tcc.
Referenced by std::basic_fstream< _CharT, _Traits >::basic_fstream(), std::basic_ifstream< _CharT, _Traits >::basic_ifstream(), std::basic_ios< char, char_traits< char > >::basic_ios(), std::basic_istream< char >::basic_istream(), std::basic_istringstream< _CharT, _Traits, _Alloc >::basic_istringstream(), std::basic_ofstream< _CharT, _Traits >::basic_ofstream(), std::basic_ostream< char >::basic_ostream(), std::basic_ostringstream< _CharT, _Traits, _Alloc >::basic_ostringstream(), n' std::basic_stringstream< _CharT, _Traits, _Alloc >::basic_stringstream().
template<typename _CharT , typename _Traits > bool std::basic_ofstream< _CharT, _Traits >::is_open () [inline]
Wrapper ta test fo' a open file.
Returns:
rdbuf()->is_open()
Definizzle at line 692 of file fstream.
References std::basic_filebuf< _CharT, _Traits >::is_open().
long& std::ios_base::iword (int__ix) [inline], [inherited]
Access ta integer array.
Parameters:
__ix Index tha fuck into tha array.
Returns:
A reference ta a integer associated wit tha index.
Da iword function serves up access ta a array of integers dat can be used fo' any purpose. Da array grows as required ta hold tha supplied index fo' realz. All integers up in tha array is initialized ta 0.
Da implementation reserves nuff muthafuckin indices. Yo ass should use xalloc ta obtain a index dat is safe ta use fo' realz. Also note dat since tha array can grow dynamically, it aint safe ta hold onto tha reference.
Definizzle at line 741 of file ios_base.h.
template<typename _CharT, typename _Traits = char_traits<_CharT>> char std::basic_ios< _CharT, _Traits >::narrow (char_type__c, char__dfault) const [inline], [inherited]
Squeezes characters.
Parameters:
__c Da characta ta narrow.
__dfault Da characta ta narrow.
Returns:
Da narrowed character.
Maps a cold-ass lil characta of char_type ta a cold-ass lil characta of char, if possible.
Returns tha result of
std::use_facet<ctype<char_type> >(getloc()).narrow(c,dfault)
Additionizzle l10n notes is at http://gcc.gnu.org/onlinedocs/libstdc++/manual/localization.html
Definizzle at line 424 of file basic_ios.h.
template<typename _CharT , typename _Traits > void std::basic_ofstream< _CharT, _Traits >::open (const char *__s, ios_base::openmode__mode = ios_base::out | ios_base::trunc) [inline]
Opens a external file.
Parameters:
__s Da name of tha file.
__mode Da open mode flags.
Calls std::basic_filebuf::open(__s,__mode|out|trunc). If dat function fails, failbit is set up in tha streamz error state.
Tip: When rockin std::strin ta hold tha filename, you must use .c_str() before passin it ta dis constructor.
Definizzle at line 713 of file fstream.
References std::basic_ios< _CharT, _Traits >::clear(), std::ios_base::failbit, std::basic_filebuf< _CharT, _Traits >::open(), std::ios_base::out, n' std::basic_ios< _CharT, _Traits >::setstate().
Referenced by std::basic_ofstream< _CharT, _Traits >::basic_ofstream().
template<typename _CharT , typename _Traits > void std::basic_ofstream< _CharT, _Traits >::open (const std::string &__s, ios_base::openmode__mode = ios_base::out | ios_base::trunc) [inline]
Opens a external file.
Parameters:
__s Da name of tha file.
__mode Da open mode flags.
Calls std::basic_filebuf::open(s,mode|out|trunc). If dat function fails, failbit is set up in tha streamz error state.
Definizzle at line 734 of file fstream.
References std::basic_ios< _CharT, _Traits >::clear(), std::ios_base::failbit, std::basic_filebuf< _CharT, _Traits >::open(), std::ios_base::out, n' std::basic_ios< _CharT, _Traits >::setstate().
template<typename _CharT, typename _Traits = char_traits<_CharT>> std::basic_ios< _CharT, _Traits >::operator void * () const [inline], [inherited]
Da quick-and-easy status check. This allows you ta write constructs like fuckin if (!a_stream) ... n' while (a_stream) ...
Definizzle at line 115 of file basic_ios.h.
template<typename _CharT, typename _Traits = char_traits<_CharT>> bool std::basic_ios< _CharT, _Traits >::operator playa! () const [inline], [inherited]
Da quick-and-easy status check. This allows you ta write constructs like fuckin if (!a_stream) ... n' while (a_stream) ...
Definizzle at line 119 of file basic_ios.h.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (__ostream_type &(*)(__ostream_type &)__pf) [inline], [inherited]
Interface fo' manipulators. Manipulators like fuckin std::endl n' std::hex use these functions up in constructs like 'std::cout << std::endl'. For mo' shiznit, peep tha iomanip header.
Definizzle at line 108 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (__ios_type &(*)(__ios_type &)__pf) [inline], [inherited]
Interface fo' manipulators. Manipulators like fuckin std::endl n' std::hex use these functions up in constructs like 'std::cout << std::endl'. For mo' shiznit, peep tha iomanip header.
Definizzle at line 117 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (ios_base &(*)(ios_base &)__pf) [inline], [inherited]
Interface fo' manipulators. Manipulators like fuckin std::endl n' std::hex use these functions up in constructs like 'std::cout << std::endl'. For mo' shiznit, peep tha iomanip header.
Definizzle at line 127 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (long__n) [inline], [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 166 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (unsigned long__n) [inline], [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 170 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (bool__n) [inline], [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 174 of file ostream.
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::basic_ostream< _CharT, _Traits >::operator<< (short__n) [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 92 of file ostream.tcc.
References std::ios_base::basefield, std::ios_base::flags(), std::ios_base::hex, n' std::ios_base::oct.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (unsigned short__n) [inline], [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 181 of file ostream.
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::basic_ostream< _CharT, _Traits >::operator<< (int__n) [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 106 of file ostream.tcc.
References std::ios_base::basefield, std::ios_base::flags(), std::ios_base::hex, n' std::ios_base::oct.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (unsigned int__n) [inline], [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 192 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (long long__n) [inline], [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 201 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (unsigned long long__n) [inline], [inherited]
Integer arithmetic inserters.
Parameters:
__n A variable of builtin integral type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 205 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (double__f) [inline], [inherited]
Floatin point arithmetic inserters.
Parameters:
__f A variable of builtin floatin point type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 220 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (float__f) [inline], [inherited]
Floatin point arithmetic inserters.
Parameters:
__f A variable of builtin floatin point type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 224 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (long double__f) [inline], [inherited]
Floatin point arithmetic inserters.
Parameters:
__f A variable of builtin floatin point type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 232 of file ostream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> __ostream_type& std::basic_ostream< _CharT, _Traits >::operator<< (const void *__p) [inline], [inherited]
Pointa arithmetic inserters.
Parameters:
__p A variable of pointa type.
Returns:
*this if successful
These functions use tha streamz current locale (specifically, tha num_get facet) ta big-ass up numeric formatting.
Definizzle at line 245 of file ostream.
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::basic_ostream< _CharT, _Traits >::operator<< (__streambuf_type *__sb) [inherited]
Extractin from another streambuf.
Parameters:
__sb A pointa ta a streambuf
This function behaves like one of tha basic arithmetic extractors, up in dat it also constructs a sentry object n' has tha same ol' dirty error handlin behavior.
If __sb is NULL, tha stream will set failbit up in its error state.
Charactas is extracted from __sb n' banged tha fuck into *this until one of tha followin occurs:
the input stream reaches end-of-file,
insertion tha fuck into tha output sequence fails (in dis case, tha characta dat would done been banged aint extracted), or
an exception occurs while gettin a cold-ass lil characta from __sb, which sets failbit up in tha error state
If tha function bangs no characters, failbit is set.
Definizzle at line 120 of file ostream.tcc.
References std::ios_base::badbit, std::ios_base::failbit, std::ios_base::goodbit, std::basic_ios< _CharT, _Traits >::rdbuf(), n' std::basic_ios< _CharT, _Traits >::setstate().
streamsize std::ios_base::precision () const [inline], [inherited]
Flags access.
Returns:
Da precision ta generate on certain output operations.
Be careful if you try ta give a thugged-out definizzle of precision here; peep DR 189.
Definizzle at line 621 of file ios_base.h.
Referenced by std::basic_ios< _CharT, _Traits >::copyfmt(), n' std::operator<<().
streamsize std::ios_base::precision (streamsize__prec) [inline], [inherited]
Changin flags.
Parameters:
__prec Da freshly smoked up precision value.
Returns:
Da previous value of precision().
Definizzle at line 630 of file ios_base.h.
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::basic_ostream< _CharT, _Traits >::put (char_type__c) [inherited]
Simple insertion.
Parameters:
__c Da characta ta insert.
Returns:
*this
Tries ta bang __c.
Note:
This function aint overloaded on signed char n' unsigned char.
Definizzle at line 149 of file ostream.tcc.
References std::ios_base::badbit, std::ios_base::goodbit, std::basic_ios< _CharT, _Traits >::rdbuf(), n' std::basic_ios< _CharT, _Traits >::setstate().
void*& std::ios_base::pword (int__ix) [inline], [inherited]
Access ta void pointa array.
Parameters:
__ix Index tha fuck into tha array.
Returns:
A reference ta a void* associated wit tha index.
Da pword function serves up access ta a array of pointas dat can be used fo' any purpose. Da array grows as required ta hold tha supplied index fo' realz. All pointas up in tha array is initialized ta 0.
Da implementation reserves nuff muthafuckin indices. Yo ass should use xalloc ta obtain a index dat is safe ta use fo' realz. Also note dat since tha array can grow dynamically, it aint safe ta hold onto tha reference.
Definizzle at line 762 of file ios_base.h.
template<typename _CharT, typename _Traits> basic_streambuf< _CharT, _Traits > * std::basic_ios< _CharT, _Traits >::rdbuf (basic_streambuf< _CharT, _Traits > *__sb) [inherited]
Changin tha underlyin buffer.
Parameters:
__sb Da freshly smoked up stream buffer.
Returns:
Da previous stream buffer.
Associates a freshly smoked up buffer wit tha current stream, n' clears tha error state.
Cuz of oldschool accidents which tha LWG refuses ta erect, tha I/O library suffers from a thugged-out design error: dis function is hidden up in derived classes by overridez of tha zero-argument rdbuf(), which is non-virtual fo' hysterical raisins fo' realz. As a result, you must use explicit qualifications ta access dis function via any derived class. For example:
std::fstream foo; // or some other derived type
std::streambuf* p = .....;
foo.ios::rdbuf(p); // ios == basic_ios<char>
Definizzle at line 53 of file basic_ios.tcc.
template<typename _CharT , typename _Traits > __filebuf_type* std::basic_ofstream< _CharT, _Traits >::rdbuf () const [inline]
Accessin tha underlyin buffer.
Returns:
Da current basic_filebuf buffer.
This hides both signaturez of std::basic_ios::rdbuf().
Definizzle at line 684 of file fstream.
template<typename _CharT, typename _Traits = char_traits<_CharT>> iostate std::basic_ios< _CharT, _Traits >::rdstate () const [inline], [inherited]
Returns tha error state of tha stream buffer.
Returns:
A bit pattern (well, aint every last muthafuckin thang?)
See std::ios_base::iostate fo' tha possible bit joints. Most playas will call one of tha interpretin wrappers, e.g., good().
Definizzle at line 131 of file basic_ios.h.
Referenced by std::basic_ios< char, char_traits< char > >::bad(), std::basic_ios< char, char_traits< char > >::eof(), std::basic_ios< char, char_traits< char > >::fail(), std::basic_ios< char, char_traits< char > >::good(), std::basic_istream< _CharT, _Traits >::putback(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_ios< char, char_traits< char > >::setstate(), n' std::basic_istream< _CharT, _Traits >::unget().
void std::ios_base::register_callback (event_callback__fn, int__index) [inherited]
Add tha callback __fn wit parameta __index.
Parameters:
__fn Da function ta add.
__index Da integer ta pass ta tha function when invoked.
Registas a gangbangin' function as a event callback wit a integer parameta ta be passed ta tha function when invoked. Multiple copiez of tha function is allowed. If there be multiple callbacks, they is invoked up in tha order they was registered.
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::basic_ostream< _CharT, _Traits >::seekp (pos_type__pos) [inherited]
Changin tha current write position.
Parameters:
__pos A file posizzle object.
Returns:
*this
If fail() aint true, calls rdbuf()->pubseekpos(pos). If dat function fails, sets failbit.
Definizzle at line 258 of file ostream.tcc.
References std::ios_base::badbit, std::basic_ios< _CharT, _Traits >::fail(), std::ios_base::failbit, std::ios_base::goodbit, std::ios_base::out, std::basic_ios< _CharT, _Traits >::rdbuf(), n' std::basic_ios< _CharT, _Traits >::setstate().
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::basic_ostream< _CharT, _Traits >::seekp (off_type__off, ios_base::seekdir__dir) [inherited]
Changin tha current write position.
Parameters:
__off A file offset object.
__dir Da direction up in which ta seek.
Returns:
*this
If fail() aint true, calls rdbuf()->pubseekoff(off,dir). If dat function fails, sets failbit.
Definizzle at line 290 of file ostream.tcc.
References std::ios_base::badbit, std::basic_ios< _CharT, _Traits >::fail(), std::ios_base::failbit, std::ios_base::goodbit, std::ios_base::out, std::basic_ios< _CharT, _Traits >::rdbuf(), n' std::basic_ios< _CharT, _Traits >::setstate().
fmtflags std::ios_base::setf (fmtflags__fmtfl) [inline], [inherited]
Settin freshly smoked up format flags.
Parameters:
__fmtfl Additionizzle flags ta set.
Returns:
Da previous format control flags.
This function sets additionizzle flags up in format control. Flags dat was previously set remain set.
Definizzle at line 578 of file ios_base.h.
Referenced by std::dec(), std::fixed(), std::hex(), std::left(), std::oct(), std::right(), std::scientific(), std::showbase(), std::showpoint(), std::showpos(), std::skipws(), std::unitbuf(), n' std::uppercase().
fmtflags std::ios_base::setf (fmtflags__fmtfl, fmtflags__mask) [inline], [inherited]
Settin freshly smoked up format flags.
Parameters:
__fmtfl Additionizzle flags ta set.
__mask Da flags mask fo' fmtfl.
Returns:
Da previous format control flags.
This function clears mask up in tha format flags, then sets fmtfl & mask fo' realz. An example mask is ios_base::adjustfield.
Definizzle at line 595 of file ios_base.h.
template<typename _CharT, typename _Traits = char_traits<_CharT>> void std::basic_ios< _CharT, _Traits >::setstate (iostate__state) [inline], [inherited]
Sets additionizzle flags up in tha error state.
Parameters:
__state Da additionizzle state flag(s) ta set.
See std::ios_base::iostate fo' tha possible bit joints.
Definizzle at line 151 of file basic_ios.h.
Referenced by std::basic_ostream< char >::_M_write(), std::basic_ifstream< _CharT, _Traits >::close(), std::basic_ofstream< _CharT, _Traits >::close(), std::basic_fstream< _CharT, _Traits >::close(), std::basic_ostream< _CharT, _Traits >::flush(), std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::getline(), std::basic_istream< _CharT, _Traits >::ignore(), std::basic_ifstream< _CharT, _Traits >::open(), std::basic_ofstream< _CharT, _Traits >::open(), std::basic_fstream< _CharT, _Traits >::open(), std::basic_ostream< _CharT, _Traits >::operator<<(), std::operator<<(), std::basic_istream< _CharT, _Traits >::operator>>(), std::tr2::operator>>(), std::operator>>(), std::basic_istream< _CharT, _Traits >::peek(), std::basic_ostream< _CharT, _Traits >::put(), std::basic_istream< _CharT, _Traits >::putback(), std::basic_istream< _CharT, _Traits >::read(), std::basic_istream< _CharT, _Traits >::readsome(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_ostream< _CharT, _Traits >::seekp(), std::basic_ostream< _CharT, _Traits >::sentry::sentry(), std::basic_istream< _CharT, _Traits >::sentry::sentry(), std::basic_istream< _CharT, _Traits >::sync(), std::basic_istream< _CharT, _Traits >::unget(), n' std::ws().
static bool std::ios_base::sync_with_stdio (bool__sync = true) [static], [inherited]
Interaction wit tha standard C I/O objects.
Parameters:
__sync Whether ta synchronize or not.
Returns:
True if tha standard streams was previously synchronized.
Da synchronization referred ta is only dat between tha standard C facilitizzles (e.g., stdout) n' tha standard C++ objects (e.g., cout). User-declared streams is unaffected. Right back up in yo muthafuckin ass. See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch28s02.html
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits >::pos_type std::basic_ostream< _CharT, _Traits >::tellp () [inherited]
Gettin tha current write position.
Returns:
A file posizzle object.
If fail() aint false, returns pos_type(-1) ta indicate failure. Otherwise returns rdbuf()->pubseekoff(0,cur,out).
Definizzle at line 237 of file ostream.tcc.
References std::ios_base::badbit, std::ios_base::cur, std::basic_ios< _CharT, _Traits >::fail(), std::ios_base::out, n' std::basic_ios< _CharT, _Traits >::rdbuf().
template<typename _CharT, typename _Traits = char_traits<_CharT>> basic_ostream<_CharT, _Traits>* std::basic_ios< _CharT, _Traits >::tie () const [inline], [inherited]
Fetches tha current tied stream.
Returns:
A pointa ta tha tied stream, or NULL if tha stream aint tied.
A stream may be tied (or synchronized) ta a second output stream. When dis stream performs any I/O, tha tied stream is first flushed. For example, std::cin is tied ta std::cout.
Definizzle at line 289 of file basic_ios.h.
Referenced by std::basic_ios< _CharT, _Traits >::copyfmt(), std::basic_ostream< _CharT, _Traits >::sentry::sentry(), n' std::basic_istream< _CharT, _Traits >::sentry::sentry().
template<typename _CharT, typename _Traits = char_traits<_CharT>> basic_ostream<_CharT, _Traits>* std::basic_ios< _CharT, _Traits >::tie (basic_ostream< _CharT, _Traits > *__tiestr) [inline], [inherited]
Ties dis stream ta a output stream.
Parameters:
__tiestr Da output stream.
Returns:
Da previously tied output stream, or NULL if tha stream was not tied.
This sets up a freshly smoked up tie; peep tie() fo' more.
Definizzle at line 301 of file basic_ios.h.
void std::ios_base::unsetf (fmtflags__mask) [inline], [inherited]
Clearin format flags.
Parameters:
__mask Da flags ta unset.
This function clears __mask up in tha format flags.
Definizzle at line 610 of file ios_base.h.
Referenced by std::noboolalpha(), std::noshowbase(), std::noshowpoint(), std::noshowpos(), std::noskipws(), std::nounitbuf(), n' std::nouppercase().
template<typename _CharT, typename _Traits = char_traits<_CharT>> char_type std::basic_ios< _CharT, _Traits >::widen (char__c) const [inline], [inherited]
Widens characters.
Parameters:
__c Da characta ta widen.
Returns:
Da widened character.
Maps a cold-ass lil characta of char ta a cold-ass lil characta of char_type.
Returns tha result of
std::use_facet<ctype<char_type> >(getloc()).widen(c)
Additionizzle l10n notes is at http://gcc.gnu.org/onlinedocs/libstdc++/manual/localization.html
Definizzle at line 443 of file basic_ios.h.
Referenced by std::basic_ios< char, char_traits< char > >::fill(), std::basic_istream< char >::get(), std::basic_istream< char >::getline(), std::getline(), std::tr2::operator>>(), n' std::operator>>().
streamsize std::ios_base::width () const [inline], [inherited]
Flags access.
Returns:
Da minimum field width ta generate on output operations.
Minimum field width refers ta tha number of characters.
Definizzle at line 644 of file ios_base.h.
Referenced by std::basic_ios< _CharT, _Traits >::copyfmt(), std::num_put< _CharT, _OutIta >::do_put(), n' std::operator>>().
streamsize std::ios_base::width (streamsize__wide) [inline], [inherited]
Changin flags.
Parameters:
__wide Da freshly smoked up width value.
Returns:
Da previous value of width().
Definizzle at line 653 of file ios_base.h.
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::basic_ostream< _CharT, _Traits >::write (const char_type *__s, streamsize__n) [inherited]
Characta strang insertion.
Parameters:
__s Da array ta insert.
__n Maximum number of charactas ta insert.
Returns:
*this
Charactas is copied from __s n' banged tha fuck into tha stream until one of tha followin happens:
__n charactas is inserted
insertin tha fuck into tha output sequence fails (in dis case, badbit is ghon be set up in tha streamz error state)
Note:
This function aint overloaded on signed char n' unsigned char.
Definizzle at line 183 of file ostream.tcc.
References std::basic_ostream< _CharT, _Traits >::_M_write(), n' std::ios_base::badbit.
static int std::ios_base::xalloc () [static], [inherited]
Access ta unique indices.
Returns:
An integer different from all previous calls.
This function returns a unique integer every last muthafuckin time it is called. Well shiiiit, it can be used fo' any purpose yo, but is primarily intended ta be a unique index fo' tha iword n' pword functions. Da expectation is dat a application calls xalloc up in order ta obtain a index up in tha iword n' pword arrays dat can be used without fear of conflict.
Da implementation maintains a static variable dat is incremented n' returned on each invocation. xalloc is guaranteed ta return a index dat is safe ta use up in tha iword n' pword arrays.
Member Data Documentation
const fmtflags std::ios_base::adjustfield [static], [inherited]
A mask of left|right|internal. Useful fo' tha 2-arg form of setf.
Definizzle at line 310 of file ios_base.h.
Referenced by std::num_put< _CharT, _OutIta >::do_put(), std::internal(), std::left(), n' std::right().
const openmode std::ios_base::app [static], [inherited]
Seek ta end before each write.
Definizzle at line 364 of file ios_base.h.
const openmode std::ios_base::ate [static], [inherited]
Open n' seek ta end immediately afta opening.
Definizzle at line 367 of file ios_base.h.
Referenced by std::basic_filebuf< _CharT, _Traits >::open().
const iostate std::ios_base::badbit [static], [inherited]
Indicates a loss of integritizzle up in a input or output sequence (like fuckin a irrecoverable read error from a gangbangin' file).
Definizzle at line 334 of file ios_base.h.
Referenced by std::basic_ostream< char >::_M_write(), std::basic_ios< char, char_traits< char > >::bad(), std::basic_ios< char, char_traits< char > >::fail(), std::basic_ostream< _CharT, _Traits >::flush(), std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), std::basic_ostream< _CharT, _Traits >::operator<<(), std::operator<<(), std::basic_istream< _CharT, _Traits >::operator>>(), std::operator>>(), std::basic_istream< _CharT, _Traits >::peek(), std::basic_ostream< _CharT, _Traits >::put(), std::basic_istream< _CharT, _Traits >::putback(), std::basic_istream< _CharT, _Traits >::read(), std::basic_istream< _CharT, _Traits >::readsome(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_ostream< _CharT, _Traits >::seekp(), std::basic_istream< _CharT, _Traits >::sync(), std::basic_istream< _CharT, _Traits >::tellg(), std::basic_ostream< _CharT, _Traits >::tellp(), std::basic_istream< _CharT, _Traits >::unget(), std::basic_ostream< _CharT, _Traits >::write(), n' std::basic_ostream< _CharT, _Traits >::sentry::~sentry().
const fmtflags std::ios_base::basefield [static], [inherited]
A mask of dec|oct|hex. Useful fo' tha 2-arg form of setf.
Definizzle at line 313 of file ios_base.h.
Referenced by std::dec(), std::num_get< _CharT, _InIta >::do_get(), std::hex(), std::oct(), n' std::basic_ostream< _CharT, _Traits >::operator<<().
const seekdir std::ios_base::beg [static], [inherited]
Request a seek relatizzle ta tha beginnin of tha stream.
Definizzle at line 396 of file ios_base.h.
Referenced by std::basic_filebuf< _CharT, _Traits >::seekpos().
const openmode std::ios_base::binary [static], [inherited]
Perform input n' output up in binary mode (as opposed ta text mode). This is probably not what tha fuck you be thinkin it is; peep http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch27s02.html.
Definizzle at line 372 of file ios_base.h.
Referenced by std::basic_filebuf< _CharT, _Traits >::showmanyc().
const fmtflags std::ios_base::boolalpha [static], [inherited]
Insert/extract bool up in alphabetic rather than numeric format.
Definizzle at line 258 of file ios_base.h.
Referenced by std::boolalpha(), std::num_get< _CharT, _InIta >::do_get(), std::num_put< _CharT, _OutIta >::do_put(), n' std::noboolalpha().
const seekdir std::ios_base::cur [static], [inherited]
Request a seek relatizzle ta tha current posizzle within tha sequence.
Definizzle at line 399 of file ios_base.h.
Referenced by std::basic_filebuf< _CharT, _Traits >::imbue(), std::basic_filebuf< _CharT, _Traits >::overflow(), std::basic_filebuf< _CharT, _Traits >::pbackfail(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::seekoff(), std::basic_filebuf< _CharT, _Traits >::seekoff(), std::basic_istream< _CharT, _Traits >::tellg(), n' std::basic_ostream< _CharT, _Traits >::tellp().
const fmtflags std::ios_base::dec [static], [inherited]
Converts integer input or generates integer output up in decimal base.
Definizzle at line 261 of file ios_base.h.
Referenced by std::dec().
const seekdir std::ios_base::end [static], [inherited]
Request a seek relatizzle ta tha current end of tha sequence.
Definizzle at line 402 of file ios_base.h.
Referenced by std::basic_filebuf< _CharT, _Traits >::open(), n' std::basic_stringbuf< _CharT, _Traits, _Alloc >::seekoff().
const iostate std::ios_base::eofbit [static], [inherited]
Indicates dat a input operation reached tha end of a input sequence.
Definizzle at line 337 of file ios_base.h.
Referenced by std::num_get< _CharT, _InIta >::do_get(), std::time_get< _CharT, _InIta >::do_get_date(), std::time_get< _CharT, _InIta >::do_get_monthname(), std::time_get< _CharT, _InIta >::do_get_time(), std::time_get< _CharT, _InIta >::do_get_weekday(), std::time_get< _CharT, _InIta >::do_get_year(), std::basic_ios< char, char_traits< char > >::eof(), std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), std::basic_istream< _CharT, _Traits >::operator>>(), std::operator>>(), std::basic_istream< _CharT, _Traits >::peek(), std::basic_istream< _CharT, _Traits >::putback(), std::basic_istream< _CharT, _Traits >::read(), std::basic_istream< _CharT, _Traits >::readsome(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_istream< _CharT, _Traits >::sentry::sentry(), std::basic_istream< _CharT, _Traits >::unget(), n' std::ws().
const iostate std::ios_base::failbit [static], [inherited]
Indicates dat a input operation failed ta read tha expected characters, or dat a output operation failed ta generate tha desired characters.
Definizzle at line 342 of file ios_base.h.
Referenced by std::basic_ifstream< _CharT, _Traits >::close(), std::basic_ofstream< _CharT, _Traits >::close(), std::basic_fstream< _CharT, _Traits >::close(), std::num_get< _CharT, _InIta >::do_get(), std::time_get< _CharT, _InIta >::do_get_monthname(), std::time_get< _CharT, _InIta >::do_get_weekday(), std::time_get< _CharT, _InIta >::do_get_year(), std::basic_ios< char, char_traits< char > >::fail(), std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::basic_ifstream< _CharT, _Traits >::open(), std::basic_ofstream< _CharT, _Traits >::open(), std::basic_fstream< _CharT, _Traits >::open(), std::basic_ostream< _CharT, _Traits >::operator<<(), std::basic_istream< _CharT, _Traits >::operator>>(), std::operator>>(), std::basic_istream< _CharT, _Traits >::read(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_ostream< _CharT, _Traits >::seekp(), std::basic_ostream< _CharT, _Traits >::sentry::sentry(), n' std::basic_istream< _CharT, _Traits >::sentry::sentry().
const fmtflags std::ios_base::fixed [static], [inherited]
Generate floating-point output up in fixed-point notation.
Definizzle at line 264 of file ios_base.h.
Referenced by std::fixed().
const fmtflags std::ios_base::floatfield [static], [inherited]
A mask of scientific|fixed. Useful fo' tha 2-arg form of setf.
Definizzle at line 316 of file ios_base.h.
Referenced by std::fixed(), n' std::scientific().
const iostate std::ios_base::goodbit [static], [inherited]
Indicates all is well.
Definizzle at line 345 of file ios_base.h.
Referenced by std::num_get< _CharT, _InIta >::do_get(), std::time_get< _CharT, _InIta >::do_get_monthname(), std::time_get< _CharT, _InIta >::do_get_weekday(), std::time_get< _CharT, _InIta >::do_get_year(), std::basic_ostream< _CharT, _Traits >::flush(), std::basic_istream< _CharT, _Traits >::get(), std::basic_istream< _CharT, _Traits >::getline(), std::basic_istream< _CharT, _Traits >::ignore(), std::basic_ostream< _CharT, _Traits >::operator<<(), std::basic_istream< _CharT, _Traits >::operator>>(), std::operator>>(), std::basic_istream< _CharT, _Traits >::peek(), std::basic_ostream< _CharT, _Traits >::put(), std::basic_istream< _CharT, _Traits >::putback(), std::basic_istream< _CharT, _Traits >::read(), std::basic_istream< _CharT, _Traits >::readsome(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_ostream< _CharT, _Traits >::seekp(), std::basic_istream< _CharT, _Traits >::sentry::sentry(), std::basic_istream< _CharT, _Traits >::sync(), n' std::basic_istream< _CharT, _Traits >::unget().
const fmtflags std::ios_base::hex [static], [inherited]
Converts integer input or generates integer output up in hexadecimal base.
Definizzle at line 267 of file ios_base.h.
Referenced by std::num_get< _CharT, _InIta >::do_get(), std::num_put< _CharT, _OutIta >::do_put(), std::hex(), n' std::basic_ostream< _CharT, _Traits >::operator<<().
const openmode std::ios_base::in [static], [inherited]
Open fo' input. Default fo' ifstream n' fstream.
Definizzle at line 375 of file ios_base.h.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_set_buffer(), std::basic_ifstream< _CharT, _Traits >::open(), std::basic_filebuf< _CharT, _Traits >::pbackfail(), std::basic_istream< _CharT, _Traits >::seekg(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::seekoff(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::seekpos(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::showmanyc(), std::basic_filebuf< _CharT, _Traits >::showmanyc(), std::basic_istream< _CharT, _Traits >::tellg(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::underflow(), std::basic_filebuf< _CharT, _Traits >::underflow(), n' std::basic_filebuf< _CharT, _Traits >::xsgetn().
const fmtflags std::ios_base::internal [static], [inherited]
Addz fill charactas at a thugged-out designated internal point up in certain generated output, or identical ta right if no such point is designated.
Definizzle at line 272 of file ios_base.h.
Referenced by std::internal().
const fmtflags std::ios_base::left [static], [inherited]
Addz fill charactas on tha right (final positions) of certain generated output. (I.e., tha thang you print is flush left.)
Definizzle at line 276 of file ios_base.h.
Referenced by std::num_put< _CharT, _OutIta >::do_put(), n' std::left().
const fmtflags std::ios_base::oct [static], [inherited]
Converts integer input or generates integer output up in octal base.
Definizzle at line 279 of file ios_base.h.
Referenced by std::oct(), n' std::basic_ostream< _CharT, _Traits >::operator<<().
const openmode std::ios_base::out [static], [inherited]
Open fo' output. Default fo' ofstream n' fstream.
Definizzle at line 378 of file ios_base.h.
Referenced by std::basic_filebuf< char_type, traits_type >::_M_set_buffer(), std::basic_ofstream< _CharT, _Traits >::open(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::overflow(), std::basic_filebuf< _CharT, _Traits >::overflow(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::pbackfail(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::seekoff(), std::basic_ostream< _CharT, _Traits >::seekp(), std::basic_stringbuf< _CharT, _Traits, _Alloc >::seekpos(), std::basic_ostream< _CharT, _Traits >::tellp(), n' std::basic_filebuf< _CharT, _Traits >::xsputn().
const fmtflags std::ios_base::right [static], [inherited]
Addz fill charactas on tha left (initial positions) of certain generated output. (I.e., tha thang you print is flush right.)
Definizzle at line 283 of file ios_base.h.
Referenced by std::right().
const fmtflags std::ios_base::scientific [static], [inherited]
Generates floating-point output up in scientistical notation.
Definizzle at line 286 of file ios_base.h.
Referenced by std::scientific().
const fmtflags std::ios_base::showbase [static], [inherited]
Generates a prefix indicatin tha numeric base of generated integer output.
Definizzle at line 290 of file ios_base.h.
Referenced by std::noshowbase(), n' std::showbase().
const fmtflags std::ios_base::showpoint [static], [inherited]
Generates a thugged-out decimal-point characta unconditionally up in generated floating-point output.
Definizzle at line 294 of file ios_base.h.
Referenced by std::noshowpoint(), n' std::showpoint().
const fmtflags std::ios_base::showpos [static], [inherited]
Generates a + sign up in non-negatizzle generated numeric output.
Definizzle at line 297 of file ios_base.h.
Referenced by std::noshowpos(), n' std::showpos().
const fmtflags std::ios_base::skipws [static], [inherited]
Skips leadin white space before certain input operations.
Definizzle at line 300 of file ios_base.h.
Referenced by std::noskipws(), std::basic_istream< _CharT, _Traits >::sentry::sentry(), n' std::skipws().
const openmode std::ios_base::trunc [static], [inherited]
Open fo' input. Default fo' ofstream.
Definizzle at line 381 of file ios_base.h.
const fmtflags std::ios_base::unitbuf [static], [inherited]
Flushes output afta each output operation.
Definizzle at line 303 of file ios_base.h.
Referenced by std::nounitbuf(), std::unitbuf(), n' std::basic_ostream< _CharT, _Traits >::sentry::~sentry().
const fmtflags std::ios_base::uppercase [static], [inherited]
Replaces certain lowercase lettas wit they uppercase equivalents up in generated output.
Definizzle at line 307 of file ios_base.h.
Referenced by std::num_put< _CharT, _OutIta >::do_put(), std::nouppercase(), n' std::uppercase().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.