" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::collate< _CharT > -
SYNOPSIS
Inherits std::locale::facet.
Inherited by std::collate_byname< _CharT >.
Public Types
typedef _CharT char_type
typedef basic_string< _CharT > string_type
Public Member Functions
collate (size_t __refs=0)
collate (__c_locale __cloc, size_t __refs=0)
int _M_compare (const _CharT *, const _CharT *) const throw ()
template<> int _M_compare (const char *, const char *) const throw()
template<> int _M_compare (const wchar_t *, const wchar_t *) const throw()
size_t _M_transform (_CharT *, const _CharT *, size_t) const throw ()
template<> size_t _M_transform (char *, const char *, size_t) const throw()
template<> size_t _M_transform (wchar_t *, const wchar_t *, size_t) const throw()
int compare (const _CharT *__lo1, const _CharT *__hi1, const _CharT *__lo2, const _CharT *__hi2) const
long hash (const _CharT *__lo, const _CharT *__hi) const
string_type transform (const _CharT *__lo, const _CharT *__hi) const
Static Public Attributes
static locale::id id
Protected Member Functions
virtual ~collate ()
virtual int do_compare (const _CharT *__lo1, const _CharT *__hi1, const _CharT *__lo2, const _CharT *__hi2) const
virtual long do_hash (const _CharT *__lo, const _CharT *__hi) const
virtual string_type do_transform (const _CharT *__lo, const _CharT *__hi) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Protected Attributes
__c_locale _M_c_locale_collate
Detailed Description
template<typename _CharT>class std::collate< _CharT >
Facet fo' localized strang comparison.
This facet encapsulates tha code ta compare strings up in a localized manner.
Da collate template uses protected virtual functions ta provide tha actual thangs up in dis biatch. Da hood accessors forward tha call ta tha virtual functions. These virtual functions is hooks fo' pimpers ta implement tha behavior they require from tha collate facet.
Definizzle at line 584 of file locale_classes.h.
Member Typedef Documentation
template<typename _CharT> typedef _CharT std::collate< _CharT >::char_type
Public typedefs.
Definizzle at line 590 of file locale_classes.h.
template<typename _CharT> typedef basic_string<_CharT> std::collate< _CharT >::string_type
Public typedefs.
Definizzle at line 591 of file locale_classes.h.
Constructor & Destructor Documentation
template<typename _CharT> std::collate< _CharT >::collate (size_t__refs = 0) [inline], [explicit]
Constructor performs initialization. This is tha constructor provided by tha standard.
Parameters:
__refs Passed ta tha base facet class.
Definizzle at line 611 of file locale_classes.h.
template<typename _CharT> std::collate< _CharT >::collate (__c_locale__cloc, size_t__refs = 0) [inline], [explicit]
Internal constructor. Not fo' general use. This be a cold-ass lil constructor fo' use by tha library itself ta set up freshly smoked up locales.
Parameters:
__cloc Da C locale.
__refs Passed ta tha base facet class.
Definizzle at line 625 of file locale_classes.h.
template<typename _CharT> virtual std::collate< _CharT >::~collate () [inline], [protected], [virtual]
Destructor.
Definizzle at line 688 of file locale_classes.h.
Member Function Documentation
template<typename _CharT> int std::collate< _CharT >::compare (const _CharT *__lo1, const _CharT *__hi1, const _CharT *__lo2, const _CharT *__hi2) const [inline]
Compare two strings. This function compares two strings n' returns tha result by callin collate::do_compare().
Parameters:
__lo1 Start of strang 1.
__hi1 End of strang 1.
__lo2 Start of strang 2.
__hi2 End of strang 2.
Returns:
1 if string1 > string2, -1 if string1 < string2, else 0.
Definizzle at line 642 of file locale_classes.h.
template<typename _CharT> int std::collate< _CharT >::do_compare (const _CharT *__lo1, const _CharT *__hi1, const _CharT *__lo2, const _CharT *__hi2) const [protected], [virtual]
Compare two strings. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
compare().
Parameters:
__lo1 Start of strang 1.
__hi1 End of strang 1.
__lo2 Start of strang 2.
__hi2 End of strang 2.
Returns:
1 if string1 > string2, -1 if string1 < string2, else 0.
Definizzle at line 161 of file locale_classes.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::basic_string< _CharT, _Traits, _Alloc >::data(), n' std::basic_string< _CharT, _Traits, _Alloc >::length().
template<typename _CharT> long std::collate< _CharT >::do_hash (const _CharT *__lo, const _CharT *__hi) const [protected], [virtual]
Return hash of a string. This function computes n' returns a hash on tha input string. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__lo Start of string.
__hi End of string.
Returns:
Hash value.
Definizzle at line 256 of file locale_classes.tcc.
template<typename _CharT> collate< _CharT >::string_type std::collate< _CharT >::do_transform (const _CharT *__lo, const _CharT *__hi) const [protected], [virtual]
Transform strang ta comparable form. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__lo Start.
__hi End.
Returns:
transformed string.
Definizzle at line 200 of file locale_classes.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::basic_string< _CharT, _Traits, _Alloc >::data(), std::basic_string< _CharT, _Traits, _Alloc >::length(), n' std::basic_string< _CharT, _Traits, _Alloc >::push_back().
template<typename _CharT> long std::collate< _CharT >::hash (const _CharT *__lo, const _CharT *__hi) const [inline]
Return hash of a string. This function computes n' returns a hash on tha input string. Well shiiiit, it do so by returnin collate::do_hash().
Parameters:
__lo Start of string.
__hi End of string.
Returns:
Hash value.
Definizzle at line 675 of file locale_classes.h.
template<typename _CharT> string_type std::collate< _CharT >::transform (const _CharT *__lo, const _CharT *__hi) const [inline]
Transform strang ta comparable form. This function be a wrapper fo' strxfrm functionality. Well shiiiit, it takes tha input strang n' returns a modified strang dat can be directly compared ta other transformed strings. In tha C locale, dis function just returns a cold-ass lil copy of tha input string. In some other locales, it may replace two chars wit one, chizzle a cold-ass lil char fo' another, etc. Well shiiiit, it do so by returnin collate::do_transform().
Parameters:
__lo Start of string.
__hi End of string.
Returns:
Transformed string_type.
Definizzle at line 661 of file locale_classes.h.
Member Data Documentation
template<typename _CharT> locale::id std::collate< _CharT >::id [static]
Numpunct facet id.
Definizzle at line 601 of file locale_classes.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.