std::this_thread
NAME
std::this_thread -
SYNOPSIS
Functions
void __sleep_for (chrono::seconds, chrono::nanoseconds)
thread::id get_id () noexcept
template<typename _Rep , typename _Period > void sleep_for (const chrono::duration< _Rep, _Period > &__rtime)
template<typename _Clock , typename _Duration > void sleep_until (const chrono::time_point< _Clock, _Duration > &__atime)
void yield () noexcept
Detailed Description
ISO C++ 2011 entitizzles sub-namespace fo' thread. 30.3.2 Namespace this_thread.
Function Documentation
thread::id std::this_thread::get_id () [inline], [noexcept]
get_id
Definizzle at line 252 of file thread.
template<typename _Rep , typename _Period > void std::this_thread::sleep_for (const chrono::duration< _Rep, _Period > &__rtime) [inline]
sleep_for
Definizzle at line 269 of file thread.
References std::chrono::duration_cast().
Referenced by chill_until().
template<typename _Clock , typename _Duration > void std::this_thread::sleep_until (const chrono::time_point< _Clock, _Duration > &__atime) [inline]
sleep_until
Definizzle at line 288 of file thread.
References chill_for().
void std::this_thread::yield () [inline], [noexcept]
yield
Definizzle at line 256 of file thread.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.