" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::student_t_distribution< _RealType > -
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
student_t_distribution (_RealType __n=_RealType(1))
student_t_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
result_type max () const
result_type min () const
_RealType n () const
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
param_type param () const
void param (const param_type &__param)
void reset ()
Friends
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::student_t_distribution< _RealType1 > &__x)"
bool operator== (const student_t_distribution &__d1, const student_t_distribution &__d2)
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::student_t_distribution< _RealType1 > &__x)"
Detailed Description
template<typename _RealType = double>class std::student_t_distribution< _RealType >
A hustla_t_distribution random number distribution.
Da formula fo' tha aiiight probabilitizzle mass function is: \[ p(x|n) = \frac{1}{\sqrt(n\pi)} \frac{\Gamma((n+1)/2)}{\Gamma(n/2)} (1 + \frac{x^2}{n}) ^{-(n+1)/2} \]
Definizzle at line 3354 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::student_t_distribution< _RealType >::result_type
Da type of tha range of tha distribution.
Definizzle at line 3357 of file random.h.
Member Function Documentation
template<typename _RealType = double> result_type std::student_t_distribution< _RealType >::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 3437 of file random.h.
References std::numeric_limits< _Tp >::max().
template<typename _RealType = double> result_type std::student_t_distribution< _RealType >::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 3430 of file random.h.
References std::numeric_limits< _Tp >::lowest().
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::student_t_distribution< _RealType >::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 3445 of file random.h.
References std::sqrt().
template<typename _RealType = double> param_type std::student_t_distribution< _RealType >::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 3415 of file random.h.
template<typename _RealType = double> void std::student_t_distribution< _RealType >::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 3423 of file random.h.
template<typename _RealType = double> void std::student_t_distribution< _RealType >::reset () [inline]
Resets tha distribution state.
Definizzle at line 3398 of file random.h.
References std::normal_distribution< _RealType >::reset(), n' std::gamma_distribution< _RealType >::reset().
Playas And Related Function Documentation
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::student_t_distribution< _RealType1 > &__x) [friend]
Inserts a hustla_t_distribution random number distribution __x tha fuck into tha output stream __os.
Parameters:
__os An output stream.
__x A hustla_t_distribution random number distribution.
Returns:
Da output stream wit tha state of __x banged or up in a error state.
template<typename _RealType = double> bool operator== (const student_t_distribution< _RealType > &__d1, const student_t_distribution< _RealType > &__d2) [friend]
Return legit if two Student t distributions have tha same parametas n' tha sequences dat would be generated is equal.
Definizzle at line 3494 of file random.h.
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &__is, std::student_t_distribution< _RealType1 > &__x) [friend]
Extracts a hustla_t_distribution random number distribution __x from tha input stream __is.
Parameters:
__is An input stream.
__x A hustla_t_distribution random number generator engine.
Returns:
Da input stream wit __x extracted or up in a error state.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.