" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::extreme_value_distribution< _RealType > -
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
extreme_value_distribution (_RealType __a=_RealType(0), _RealType __b=_RealType(1))
extreme_value_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
_RealType a () const
_RealType b () const
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > extreme_value_distribution
< _RealType >::result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)"
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
param_type param () const
void param (const param_type &__param)
void reset ()
Friends
bool operator== (const extreme_value_distribution &__d1, const extreme_value_distribution &__d2)
Detailed Description
template<typename _RealType = double>class std::extreme_value_distribution< _RealType >
A extreme_value_distribution random number distribution.
Da formula fo' tha aiiight probabilitizzle mass function is \[ p(x|a,b) = \frac{1}{b} \xp( \frac{a-x}{b} - \xp(\frac{a-x}{b})) \]
Definizzle at line 5051 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::extreme_value_distribution< _RealType >::result_type
Da type of tha range of tha distribution.
Definizzle at line 5054 of file random.h.
Member Function Documentation
template<typename _RealType = double> _RealType std::extreme_value_distribution< _RealType >::a () const [inline]
Return tha $a$ parameta of tha distribution.
Definizzle at line 5109 of file random.h.
template<typename _RealType = double> _RealType std::extreme_value_distribution< _RealType >::b () const [inline]
Return tha $b$ parameta of tha distribution.
Definizzle at line 5116 of file random.h.
template<typename _RealType = double> result_type std::extreme_value_distribution< _RealType >::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 5145 of file random.h.
References std::numeric_limits< _Tp >::max().
template<typename _RealType = double> result_type std::extreme_value_distribution< _RealType >::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 5138 of file random.h.
References std::numeric_limits< _Tp >::lowest().
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::extreme_value_distribution< _RealType >::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 5153 of file random.h.
template<typename _RealType = double> param_type std::extreme_value_distribution< _RealType >::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 5123 of file random.h.
Referenced by std::operator>>().
template<typename _RealType = double> void std::extreme_value_distribution< _RealType >::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 5131 of file random.h.
template<typename _RealType = double> void std::extreme_value_distribution< _RealType >::reset () [inline]
Resets tha distribution state.
Definizzle at line 5102 of file random.h.
Playas And Related Function Documentation
template<typename _RealType = double> bool operator== (const extreme_value_distribution< _RealType > &__d1, const extreme_value_distribution< _RealType > &__d2) [friend]
Return legit if two off tha hook value distributions have tha same parameters.
Definizzle at line 5188 of file random.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.