" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::numeric_limits< _Tp > -
SYNOPSIS
Inherits std::__numeric_limits_base.
Inherited by std::numeric_limits< const _Tp >, std::numeric_limits< const volatile _Tp >, n' std::numeric_limits< volatile _Tp >.
Static Public Member Functions
static constexpr _Tp denorm_min () noexcept
static constexpr _Tp epsilon () noexcept
static constexpr _Tp infinity () noexcept
static constexpr _Tp lowest () noexcept
static constexpr _Tp max () noexcept
static constexpr _Tp min () noexcept
static constexpr _Tp quiet_NaN () noexcept
static constexpr _Tp round_error () noexcept
static constexpr _Tp signaling_NaN () noexcept
Static Public Attributes
static constexpr int digits
static constexpr int digits10
static constexpr float_denorm_style has_denorm
static constexpr bool has_denorm_loss
static constexpr bool has_infinity
static constexpr bool has_quiet_NaN
static constexpr bool has_signaling_NaN
static constexpr bool is_bounded
static constexpr bool is_exact
static constexpr bool is_iec559
static constexpr bool is_integer
static constexpr bool is_modulo
static constexpr bool is_signed
static constexpr bool is_specialized
static constexpr int max_digits10
static constexpr int max_exponent
static constexpr int max_exponent10
static constexpr int min_exponent
static constexpr int min_exponent10
static constexpr int radix
static constexpr float_round_style round_style
static constexpr bool tinyness_before
static constexpr bool traps
Detailed Description
template<typename _Tp>struct std::numeric_limits< _Tp >
Propertizzlez of fundamenstrual types.
This class allows a program ta obtain shiznit bout tha representation of a gangbangin' fundamenstrual type on a given platform. For non-fundamenstrual types, tha functions will return 0 n' tha data thugz will all be false.
_GLIBCXX_RESOLVE_LIB_DEFECTS: DRs 201 n' 184 (hi Gaby!) is noted yo, but not incorporated up in dis documented (yet).
Definizzle at line 304 of file limits.
Member Function Documentation
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::denorm_min () [inline], [static], [noexcept]
Da minimum positizzle denormalized value. For types where has_denorm is false, dis is tha minimum positizzle normalized value.
Definizzle at line 349 of file limits.
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::epsilon () [inline], [static], [noexcept]
Da machine epsilon: tha difference between 1 n' tha least value pimped outa than 1 dat is representable.
Definizzle at line 325 of file limits.
Referenced by std::poisson_distribution< _IntType >::operator()(), n' std::binomial_distribution< _IntType >::operator()().
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::infinitizzle () [inline], [static], [noexcept]
Da representation of positizzle infinity, if has_infinity.
Definizzle at line 333 of file limits.
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::lowest () [inline], [static], [noexcept]
A finite value x such dat there is no other finite value y where y < x.
Definizzle at line 319 of file limits.
Referenced by std::normal_distribution< result_type >::min(), std::cauchy_distribution< _RealType >::min(), std::student_t_distribution< _RealType >::min(), n' std::extreme_value_distribution< _RealType >::min().
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::max () [inline], [static], [noexcept]
Da maximum finite value.
Definizzle at line 313 of file limits.
Referenced by std::normal_distribution< result_type >::max(), std::lognormal_distribution< _RealType >::max(), std::gamma_distribution< result_type >::max(), std::chi_squared_distribution< _RealType >::max(), std::cauchy_distribution< _RealType >::max(), std::fisher_f_distribution< _RealType >::max(), std::student_t_distribution< _RealType >::max(), std::bernoulli_distribution::max(), std::geometric_distribution< _IntType >::max(), std::negative_binomial_distribution< _IntType >::max(), std::poisson_distribution< _IntType >::max(), std::exponential_distribution< _RealType >::max(), std::weibull_distribution< _RealType >::max(), std::extreme_value_distribution< _RealType >::max(), std::tr2::dynamic_bitset< _WordT, _Alloc >::max_size(), std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType >::operator()(), std::poisson_distribution< _IntType >::operator()(), n' std::binomial_distribution< _IntType >::operator()().
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::min () [inline], [static], [noexcept]
Da minimum finite value, or fo' floatin types wit denormalization, tha minimum positizzle normalized value.
Definizzle at line 309 of file limits.
Referenced by std::bernoulli_distribution::min(), n' std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType >::operator()().
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::quiet_NaN () [inline], [static], [noexcept]
Da representation of a on tha down-low Not a Number, if has_quiet_NaN.
Definizzle at line 338 of file limits.
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::round_error () [inline], [static], [noexcept]
Da maximum roundin error measurement (see LIA-1).
Definizzle at line 329 of file limits.
template<typename _Tp > static constexpr _Tp std::numeric_limits< _Tp >::signaling_NaN () [inline], [static], [noexcept]
Da representation of a signalin Not a Number, if has_signaling_NaN.
Definizzle at line 343 of file limits.
Member Data Documentation
constexpr int std::__numeric_limits_base::digits [static], [inherited]
Da number of radix digits dat be represented without chizzle: fo' integer types, tha number of non-sign bits up in tha mantissa; fo' floatin types, tha number of radix digits up in tha mantissa.
Definizzle at line 200 of file limits.
constexpr int std::__numeric_limits_base::digits10 [static], [inherited]
Da number of base 10 digits dat can be represented without chizzle.
Definizzle at line 203 of file limits.
constexpr float_denorm_style std::__numeric_limits_base::has_denorm [static], [inherited]
See std::float_denorm_style fo' mo' shiznit.
Definizzle at line 255 of file limits.
constexpr bool std::__numeric_limits_base::has_denorm_loss [static], [inherited]
True if loss of accuracy is detected as a thugged-out denormalization loss, rather than as a inexact result.
Definizzle at line 259 of file limits.
constexpr bool std::__numeric_limits_base::has_infinity [static], [inherited]
True if tha type has a representation fo' positizzle infinity.
Definizzle at line 244 of file limits.
constexpr bool std::__numeric_limits_base::has_quiet_NaN [static], [inherited]
True if tha type has a representation fo' a on tha down-low (non-signaling) Not a Number.
Definizzle at line 248 of file limits.
constexpr bool std::__numeric_limits_base::has_signaling_NaN [static], [inherited]
True if tha type has a representation fo' a signalin Not a Number.
Definizzle at line 252 of file limits.
constexpr bool std::__numeric_limits_base::is_bounded [static], [inherited]
True if tha set of joints representable by tha type is finite fo' realz. All built-in types is bounded, dis member would be false fo' arbitrary precision types.
Definizzle at line 268 of file limits.
constexpr bool std::__numeric_limits_base::is_exact [static], [inherited]
True if tha type uses a exact representation fo' realz. All integer types is exact yo, but not all exact types is integer. For example, rationizzle n' fixed-exponent representations is exact but not integer.
Definizzle at line 220 of file limits.
constexpr bool std::__numeric_limits_base::is_iec559 [static], [inherited]
True if-and-only-if tha type adheres ta tha IEC 559 standard, also known as IEEE 754. (Only make sense fo' floatin point types.)
Definizzle at line 263 of file limits.
constexpr bool std::__numeric_limits_base::is_integer [static], [inherited]
True if tha type is integer.
Definizzle at line 215 of file limits.
constexpr bool std::__numeric_limits_base::is_modulo [static], [inherited]
True if tha type is modulo fo' realz. A type is modulo if, fo' any operation involvin +, -, or * on jointz of dat type whose result would fall outside tha range [min(),max()], tha value returned differs from tha legit value by a integer multiple of max() - min() + 1. On most machines, dis is false fo' floatin types, legit fo' unsigned integers, n' legit fo' signed integers. Right back up in yo muthafuckin ass. See PR22200 bout signed integers.
Definizzle at line 277 of file limits.
constexpr bool std::__numeric_limits_base::is_signed [static], [inherited]
True if tha type is signed.
Definizzle at line 212 of file limits.
constexpr bool std::__numeric_limits_base::is_specialized [static], [inherited]
This is ghon be legit fo' all fundamenstrual types (which have specializations), n' false fo' every last muthafuckin thang else.
Definizzle at line 195 of file limits.
constexpr int std::__numeric_limits_base::max_digits10 [static], [inherited]
Da number of base 10 digits required ta ensure dat joints which differ is always differentiated.
Definizzle at line 208 of file limits.
constexpr int std::__numeric_limits_base::max_exponent [static], [inherited]
Da maximum positizzle integer such dat radix raised ta tha juice of (one less than dat integer) be a representable finite floatin point number.
Definizzle at line 237 of file limits.
constexpr int std::__numeric_limits_base::max_exponent10 [static], [inherited]
Da maximum positizzle integer such dat 10 raised ta dat juice is up in tha range of representable finite floatin point numbers.
Definizzle at line 241 of file limits.
constexpr int std::__numeric_limits_base::min_exponent [static], [inherited]
Da minimum wack integer such dat radix raised ta tha juice of (one less than dat integer) be a normalized floatin point number.
Definizzle at line 228 of file limits.
constexpr int std::__numeric_limits_base::min_exponent10 [static], [inherited]
Da minimum wack integer such dat 10 raised ta dat juice is up in tha range of normalized floatin point numbers.
Definizzle at line 232 of file limits.
constexpr int std::__numeric_limits_base::radix [static], [inherited]
For integer types, specifies tha base of tha representation. For floatin types, specifies tha base of tha exponent representation.
Definizzle at line 224 of file limits.
constexpr float_round_style std::__numeric_limits_base::round_style [static], [inherited]
See std::float_round_style fo' mo' shiznit. This is only meaningful fo' floatin types; integer types will all be round_toward_zero.
Definizzle at line 288 of file limits.
constexpr bool std::__numeric_limits_base::tinyness_before [static], [inherited]
True if tininizz is detected before rounding. (see IEC 559)
Definizzle at line 283 of file limits.
constexpr bool std::__numeric_limits_base::traps [static], [inherited]
True if trappin is implemented fo' dis type.
Definizzle at line 280 of file limits.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.