" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::forward_list< _Tp, _Alloc > -
SYNOPSIS
Inherits std::_Fwd_list_base< _Tp, _Alloc >.
Public Types
typedef _Alloc allocator_type
typedef
_Fwd_list_const_iterator< _Tp > const_iterator"
typedef
_Alloc_traits::const_pointa const_pointer"
typedef
_Alloc_traits::const_reference const_reference"
typedef std::ptrdiff_t difference_type
typedef _Fwd_list_iterator< _Tp > iterator
typedef _Alloc_traits::pointa pointer
typedef _Alloc_traits::reference reference
typedef std::size_t size_type
typedef _Tp value_type
Public Member Functions
forward_list (const _Alloc &__al=_Alloc())
forward_list (const forward_list &__list, const _Alloc &__al)
forward_list (forward_list &&__list, const _Alloc &__al) noexcept(_Node_alloc_traits::_S_always_equal())
forward_list (size_type __n, const _Alloc &__al=_Alloc())
forward_list (size_type __n, const _Tp &__value, const _Alloc &__al=_Alloc())
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> forward_list (_InputIterator __first, _InputIterator __last, const _Alloc &__al=_Alloc())
forward_list (const forward_list &__list)
forward_list (forward_list &&__list) noexcept
forward_list (std::initializer_list< _Tp > __il, const _Alloc &__al=_Alloc())
~forward_list () noexcept
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void assign (_InputIterator __first, _InputIterator __last)
void assign (size_type __n, const _Tp &__val)
void assign (std::initializer_list< _Tp > __il)
iterator before_begin () noexcept
const_iterator before_begin () const noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbefore_begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
template<typename... _Args> iterator emplace_after (const_iterator __pos, _Args &&...__args)
template<typename... _Args> void emplace_front (_Args &&...__args)
bool empty () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
iterator erase_after (const_iterator __pos)
iterator erase_after (const_iterator __pos, const_iterator __last)
reference front ()
const_reference front () const
allocator_type get_allocator () const noexcept
template<typename _InputIterator , typename > forward_list< _Tp, _Alloc >
::iterator insert_after (const_iterator __pos, _InputIterator __first, _InputIterator __last)"
iterator insert_after (const_iterator __pos, const _Tp &__val)
iterator insert_after (const_iterator __pos, _Tp &&__val)
iterator insert_after (const_iterator __pos, size_type __n, const _Tp &__val)
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> iterator insert_after (const_iterator __pos, _InputIterator __first, _InputIterator __last)
iterator insert_after (const_iterator __pos, std::initializer_list< _Tp > __il)
size_type max_size () const noexcept
void merge (forward_list &&__list)
void merge (forward_list &__list)
template<typename _Comp > void merge (forward_list &&__list, _Comp __comp)
template<typename _Comp > void merge (forward_list &__list, _Comp __comp)
forward_list & operator= (const forward_list &__list)
forward_list & operator= (forward_list &&__list) noexcept(_Node_alloc_traits::_S_nothrow_move())
forward_list & operator= (std::initializer_list< _Tp > __il)
void pop_front ()
void push_front (const _Tp &__val)
void push_front (_Tp &&__val)
void remove (const _Tp &__val)
template<typename _Pred > void remove_if (_Pred __pred)
void resize (size_type __sz)
void resize (size_type __sz, const value_type &__val)
void reverse () noexcept
void sort ()
template<typename _Comp > void sort (_Comp __comp)
void splice_after (const_iterator __pos, forward_list &&__list)
void splice_after (const_iterator __pos, forward_list &__list)
void splice_after (const_iterator __pos, forward_list &&__list, const_iterator __i)
void splice_after (const_iterator __pos, forward_list &__list, const_iterator __i)
void splice_after (const_iterator __pos, forward_list &&, const_iterator __before, const_iterator __last)
void splice_after (const_iterator __pos, forward_list &, const_iterator __before, const_iterator __last)
void swap (forward_list &__list) noexcept(_Node_alloc_traits::_S_nothrow_swap())
void unique ()
template<typename _BinPred > void unique (_BinPred __binary_pred)
Private Member Functions
template<typename... _Args> _Node * _M_create_node (_Args &&...__args)
_Fwd_list_node_base * _M_erase_after (_Fwd_list_node_base *__pos)
_Fwd_list_node_base * _M_erase_after (_Fwd_list_node_base *__pos, _Fwd_list_node_base *__last)
_Node * _M_get_node ()
_Node_alloc_type & _M_get_Node_allocator () noexcept
const _Node_alloc_type & _M_get_Node_allocator () const noexcept
template<typename... _Args> _Fwd_list_node_base * _M_insert_after (const_iterator __pos, _Args &&...__args)
void _M_put_node (_Node *__p)
Private Attributes
_Fwd_list_impl _M_impl
Detailed Description
template<typename _Tp, typename _Alloc = allocator<_Tp>>class std::forward_list< _Tp, _Alloc >
A standard container wit linear time access ta elements, n' fixed time insertion/deletion at any point up in tha sequence.
Template Parameters:
_Tp Type of element.
_Alloc Allocator type, defaults ta allocator<_Tp>.
Meets tha requirementz of a container, a sequence, includin tha optionizzle sequence requirements wit tha exception of at n' operator[].
This be a singly linked list. Traversal up tha list requires linear time yo, but addin n' removin elements (or nodes) is done up in constant time, regardless of where tha chizzle takes place. Unlike std::vector n' std::deque, random-access iterators is not provided, so subscriptin ( [] ) access aint allowed. For algorithms which only need sequential access, dis lack make no difference.
Also unlike tha other standard containers, std::forward_list serves up specialized algorithms unique ta linked lists, like fuckin splicing, sorting, n' in-place reversal.
Definizzle at line 408 of file forward_list.h.
Constructor & Destructor Documentation
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::forward_list (const _Alloc &__al = _Alloc()) [inline], [explicit]
Creates a gangbangin' forward_list wit no elements.
Parameters:
__al An allocator object.
Definizzle at line 440 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::forward_list (const forward_list< _Tp, _Alloc > &__list, const _Alloc &__al) [inline]
Copy constructor wit allocator argument.
Parameters:
__list Input list ta copy.
__al An allocator object.
Definizzle at line 449 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::begin(), n' std::forward_list< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::forward_list (forward_list< _Tp, _Alloc > &&__list, const _Alloc &__al) [inline], [noexcept]
Move constructor wit allocator argument.
Parameters:
__list Input list ta move.
__al An allocator object.
Definizzle at line 458 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::forward_list (size_type__n, const _Alloc &__al = _Alloc()) [inline], [explicit]
Creates a gangbangin' forward_list wit default constructed elements.
Parameters:
__n Da number of elements ta initially create.
This constructor creates tha forward_list wit __n default constructed elements.
Definizzle at line 471 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::forward_list (size_type__n, const _Tp &__value, const _Alloc &__al = _Alloc()) [inline]
Creates a gangbangin' forward_list wit copiez of a exemplar element.
Parameters:
__n Da number of elements ta initially create.
__value An element ta copy.
__al An allocator object.
This constructor fills tha forward_list wit __n copiez of __value.
Definizzle at line 484 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> std::forward_list< _Tp, _Alloc >::forward_list (_InputIterator__first, _InputIterator__last, const _Alloc &__al = _Alloc()) [inline]
Buildz a gangbangin' forward_list from a range.
Parameters:
__first An input iterator.
__last An input iterator.
__al An allocator object.
Smoke a gangbangin' forward_list consistin of copiez of tha elements from [__first,__last). This is linear up in N (where N is distance(__first,__last)).
Definizzle at line 501 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::forward_list (const forward_list< _Tp, _Alloc > &__list) [inline]
Da forward_list copy constructor.
Parameters:
__list A forward_list of identical element n' allocator types.
Definizzle at line 511 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::begin(), n' std::forward_list< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::forward_list (forward_list< _Tp, _Alloc > &&__list) [inline], [noexcept]
Da forward_list move constructor.
Parameters:
__list A forward_list of identical element n' allocator types.
Da newly-created forward_list gotz nuff tha exact contentz of __list. Da contentz of __list is a valid yo, but unspecified forward_list.
Definizzle at line 525 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::forward_list (std::initializer_list< _Tp >__il, const _Alloc &__al = _Alloc()) [inline]
Buildz a gangbangin' forward_list from a initializer_list.
Parameters:
__il An initializer_list of value_type.
__al An allocator object.
Smoke a gangbangin' forward_list consistin of copiez of tha elements up in tha initializer_list __il. This is linear up in __il.size().
Definizzle at line 536 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> std::forward_list< _Tp, _Alloc >::~forward_list () [inline], [noexcept]
Da forward_list dtor.
Definizzle at line 544 of file forward_list.h.
Member Function Documentation
template<typename _Tp, typename _Alloc = allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void std::forward_list< _Tp, _Alloc >::assign (_InputIterator__first, _InputIterator__last) [inline]
Assigns a range ta a gangbangin' forward_list.
Parameters:
__first An input iterator.
__last An input iterator.
This function fills a gangbangin' forward_list wit copiez of tha elements up in tha range [__first,__last).
Note dat tha assignment straight-up chizzlez tha forward_list n' dat tha number of elementz of tha resultin forward_list is tha same ol' dirty as tha number of elements assigned. Oldskool data is lost.
Definizzle at line 609 of file forward_list.h.
Referenced by std::forward_list< _Tp, _Alloc >::assign(), n' std::forward_list< _Tp, _Alloc >::operator=().
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::assign (size_type__n, const _Tp &__val) [inline]
Assigns a given value ta a gangbangin' forward_list.
Parameters:
__n Number of elements ta be assigned.
__val Value ta be assigned.
This function fills a gangbangin' forward_list wit __n copiez of tha given value. Note dat tha assignment straight-up chizzlez tha forward_list, n' dat tha resultin forward_list has __n elements. Oldskool data is lost.
Definizzle at line 626 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::assign (std::initializer_list< _Tp >__il) [inline]
Assigns a initializer_list ta a gangbangin' forward_list.
Parameters:
__il An initializer_list of value_type.
Replace tha contentz of tha forward_list wit copiez of tha elements up in tha initializer_list __il. This is linear up in il.size().
Definizzle at line 638 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::assign().
template<typename _Tp, typename _Alloc = allocator<_Tp>> iterator std::forward_list< _Tp, _Alloc >::before_begin () [inline], [noexcept]
Returns a read/write iterator dat points before tha straight-up original gangsta element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 653 of file forward_list.h.
Referenced by std::forward_list< _Tp, _Alloc >::insert_after().
template<typename _Tp, typename _Alloc = allocator<_Tp>> const_iterator std::forward_list< _Tp, _Alloc >::before_begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points before tha straight-up original gangsta element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 662 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> iterator std::forward_list< _Tp, _Alloc >::begin () [inline], [noexcept]
Returns a read/write iterator dat points ta tha straight-up original gangsta element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 670 of file forward_list.h.
Referenced by std::forward_list< _Tp, _Alloc >::forward_list().
template<typename _Tp, typename _Alloc = allocator<_Tp>> const_iterator std::forward_list< _Tp, _Alloc >::begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 679 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> const_iterator std::forward_list< _Tp, _Alloc >::cbefore_begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points before tha straight-up original gangsta element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 715 of file forward_list.h.
Referenced by std::forward_list< _Tp, _Alloc >::emplace_front(), n' std::forward_list< _Tp, _Alloc >::push_front().
template<typename _Tp, typename _Alloc = allocator<_Tp>> const_iterator std::forward_list< _Tp, _Alloc >::cbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 706 of file forward_list.h.
Referenced by std::forward_list< _Tp, _Alloc >::operator=(), n' std::operator==().
template<typename _Tp, typename _Alloc = allocator<_Tp>> const_iterator std::forward_list< _Tp, _Alloc >::cend () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 724 of file forward_list.h.
Referenced by std::forward_list< _Tp, _Alloc >::operator=(), n' std::operator==().
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::clear () [inline], [noexcept]
Erases all tha elements. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 1027 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> template<typename... _Args> iterator std::forward_list< _Tp, _Alloc >::emplace_afta (const_iterator__pos, _Args &&...__args) [inline]
Constructs object up in forward_list afta tha specified iterator.
Parameters:
__pos A const_iterator tha fuck into tha forward_list.
__args Arguments.
Returns:
An iterator dat points ta tha banged data.
This function will bang a object of type T constructed wit T(std::forward<Args>(args)...) afta tha specified location. Cuz of tha nature of a gangbangin' forward_list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Definizzle at line 837 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> template<typename... _Args> void std::forward_list< _Tp, _Alloc >::emplace_front (_Args &&...__args) [inline]
Constructs object up in forward_list all up in tha front of tha list.
Parameters:
__args Arguments.
This function will bang a object of type Tp constructed wit Tp(std::forward<Args>(args)...) all up in tha front of tha list Cuz of tha nature of a gangbangin' forward_list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Definizzle at line 781 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::cbefore_begin().
template<typename _Tp, typename _Alloc = allocator<_Tp>> bool std::forward_list< _Tp, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha forward_list is empty. (Thus begin() would equal end().)
Definizzle at line 732 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> iterator std::forward_list< _Tp, _Alloc >::end () [inline], [noexcept]
Returns a read/write iterator dat points one past tha last element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 688 of file forward_list.h.
Referenced by std::forward_list< _Tp, _Alloc >::forward_list(), n' std::forward_list< _Tp, _Alloc >::insert_after().
template<typename _Tp, typename _Alloc = allocator<_Tp>> const_iterator std::forward_list< _Tp, _Alloc >::end () const [inline], [noexcept]
Returns a read-only iterator dat points one past tha last element up in tha forward_list. Iteration is done up in ordinary element order.
Definizzle at line 697 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> iterator std::forward_list< _Tp, _Alloc >::erase_afta (const_iterator__pos) [inline]
Removes tha element pointed ta by tha iterator followin pos.
Parameters:
__pos Iterator pointin before element ta be erased.
Returns:
An iterator pointin ta tha element followin tha one dat was erased, or end() if no such element exists.
This function will erase tha element all up in tha given posizzle n' thus shorten tha forward_list by one.
Cuz of tha nature of a gangbangin' forward_list dis operation can be done up in constant time, n' only invalidates iterators/references ta tha element bein removed. Da user be also cautioned dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 940 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> iterator std::forward_list< _Tp, _Alloc >::erase_afta (const_iterator__pos, const_iterator__last) [inline]
Remove a range of elements.
Parameters:
__pos Iterator pointin before tha straight-up original gangsta element ta be erased.
__last Iterator pointin ta one past tha last element ta be erased.
Returns:
@ __last.
This function will erase tha elements up in tha range (__pos,__last) n' shorten tha forward_list accordingly.
This operation is linear time up in tha size of tha range n' only invalidates iterators/references ta tha element bein removed. Da user be also cautioned dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 963 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> reference std::forward_list< _Tp, _Alloc >::front () [inline]
Returns a read/write reference ta tha data all up in tha straight-up original gangsta element of tha forward_list.
Definizzle at line 749 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> const_reference std::forward_list< _Tp, _Alloc >::front () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha straight-up original gangsta element of tha forward_list.
Definizzle at line 760 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> allocator_type std::forward_list< _Tp, _Alloc >::get_allocator () const [inline], [noexcept]
Git a cold-ass lil copy of tha memory allocation object.
Definizzle at line 643 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> iterator std::forward_list< _Tp, _Alloc >::insert_afta (const_iterator__pos, const _Tp &__val) [inline]
Inserts given value tha fuck into forward_list afta specified iterator.
Parameters:
__pos An iterator tha fuck into tha forward_list.
__val Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given value afta tha specified location. Cuz of tha nature of a gangbangin' forward_list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Definizzle at line 854 of file forward_list.h.
Referenced by std::forward_list< _Tp, _Alloc >::insert_after().
template<typename _Tp, typename _Alloc > forward_list< _Tp, _Alloc >::iterator forward_list::insert_afta (const_iterator__pos, size_type__n, const _Tp &__val)
Inserts a fuckin shitload of copiez of given data tha fuck into tha forward_list.
Parameters:
__pos An iterator tha fuck into tha forward_list.
__n Number of elements ta be inserted.
__val Data ta be inserted.
Returns:
An iterator pointin ta tha last banged copy of val or pos if n == 0.
This function will bang a specified number of copiez of tha given data afta tha location specified by pos.
This operation is linear up in tha number of elements banged n' do not invalidate iterators n' references.
Definizzle at line 272 of file forward_list.tcc.
References std::forward_list< _Tp, _Alloc >::before_begin(), n' std::forward_list< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> iterator std::forward_list< _Tp, _Alloc >::insert_afta (const_iterator__pos, _InputIterator__first, _InputIterator__last)
Inserts a range tha fuck into tha forward_list.
Parameters:
__pos An iterator tha fuck into tha forward_list.
__first An input iterator.
__last An input iterator.
Returns:
An iterator pointin ta tha last banged element or __pos if __first == __last.
This function will bang copiez of tha data up in tha range [__first,__last) tha fuck into tha forward_list afta tha location specified by __pos.
This operation is linear up in tha number of elements banged n' do not invalidate iterators n' references.
template<typename _Tp, typename _Alloc = allocator<_Tp>> iterator std::forward_list< _Tp, _Alloc >::insert_afta (const_iterator__pos, std::initializer_list< _Tp >__il) [inline]
Inserts tha contentz of a initializer_list tha fuck into forward_list afta tha specified iterator.
Parameters:
__pos An iterator tha fuck into tha forward_list.
__il An initializer_list of value_type.
Returns:
An iterator pointin ta tha last banged element or __pos if __il is empty.
This function will bang copiez of tha data up in tha initializer_list __il tha fuck into tha forward_list before tha location specified by __pos.
This operation is linear up in tha number of elements banged n' do not invalidate iterators n' references.
Definizzle at line 919 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::insert_after().
template<typename _Tp, typename _Alloc = allocator<_Tp>> size_type std::forward_list< _Tp, _Alloc >::max_size () const [inline], [noexcept]
Returns tha phattest possible number of elementz of forward_list.
Definizzle at line 739 of file forward_list.h.
References std::allocator_traits< _Alloc >::max_size().
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::merge (forward_list< _Tp, _Alloc > &&__list) [inline]
Merge sorted lists.
Parameters:
__list Sorted list ta merge.
Assumes dat both list n' dis list is sorted accordin ta operator<(). Merges elementz of __list tha fuck into dis list up in sorted order, leavin __list empty when complete. Elements up in dis list precede elements up in __list dat is equal.
Definizzle at line 1165 of file forward_list.h.
template<typename _Tp , typename _Alloc > template<typename _Comp > void forward_list::merge (forward_list< _Tp, _Alloc > &&__list, _Comp__comp)
Merge sorted lists accordin ta comparison function.
Parameters:
__list Sorted list ta merge.
__comp Comparison function definin sort order.
Assumes dat both __list n' dis list is sorted accordin ta comp. Merges elementz of __list tha fuck into dis list up in sorted order, leavin __list empty when complete. Elements up in dis list precede elements up in __list dat is equivalent accordin ta comp().
Definizzle at line 365 of file forward_list.tcc.
template<typename _Tp , typename _Alloc > forward_list< _Tp, _Alloc > & forward_list::operator= (const forward_list< _Tp, _Alloc > &__list)
Da forward_list assignment operator.
Parameters:
__list A forward_list of identical element n' allocator types.
All tha elementz of __list is copied yo, but unlike tha copy constructor, tha allocator object aint copied.
Definizzle at line 156 of file forward_list.tcc.
References std::forward_list< _Tp, _Alloc >::cbegin(), n' std::forward_list< _Tp, _Alloc >::cend().
template<typename _Tp, typename _Alloc = allocator<_Tp>> forward_list& std::forward_list< _Tp, _Alloc >::operator= (forward_list< _Tp, _Alloc > &&__list) [inline], [noexcept]
Da forward_list move assignment operator.
Parameters:
__list A forward_list of identical element n' allocator types.
Da contentz of __list is moved tha fuck into dis forward_list (without copying, if tha allocators permit it). __list be a valid yo, but unspecified forward_list
Definizzle at line 568 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> forward_list& std::forward_list< _Tp, _Alloc >::operator= (std::initializer_list< _Tp >__il) [inline]
Da forward_list initializer list assignment operator.
Parameters:
__il An initializer_list of value_type.
Replace tha contentz of tha forward_list wit copiez of tha elements up in tha initializer_list __il. This is linear up in __il.size().
Definizzle at line 588 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::assign().
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::pop_front () [inline]
Removes first element. This be a typical stack operation. Well shiiiit, it shrinks tha forward_list by one. Cuz of tha nature of a gangbangin' forward_list dis operation can be done up in constant time, n' only invalidates iterators/references ta tha element bein removed.
Note dat no data is returned, n' if tha straight-up original gangsta elementz data is needed, it should be retrieved before pop_front() is called.
Definizzle at line 819 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::push_front (const _Tp &__val) [inline]
Add data ta tha front of tha forward_list.
Parameters:
__val Data ta be added.
This be a typical stack operation. Da function creates a element all up in tha front of tha forward_list n' assigns tha given data ta it. Cuz of tha nature of a gangbangin' forward_list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Definizzle at line 796 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::cbefore_begin().
template<typename _Tp, typename _Alloc > void forward_list::remove (const _Tp &__val)
Remove all elements equal ta value.
Parameters:
__val Da value ta remove.
Removes every last muthafuckin element up in tha list equal ta __val. Remainin elements stay up in list order. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 300 of file forward_list.tcc.
References std::__addressof().
template<typename _Tp , typename _Alloc > template<typename _Pred > void forward_list::remove_if (_Pred__pred)
Remove all elements satisfyin a predicate.
Parameters:
__pred Unary predicate function or object.
Removes every last muthafuckin element up in tha list fo' which tha predicate returns true. Remainin elements stay up in list order. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 328 of file forward_list.tcc.
template<typename _Tp , typename _Alloc > void forward_list::resize (size_type__sz)
Resizes tha forward_list ta tha specified number of elements.
Parameters:
__sz Number of elements tha forward_list should contain.
This function will resize tha forward_list ta tha specified number of elements. If tha number is smalla than tha forward_listz current number of elements tha forward_list is truncated, otherwise tha forward_list is extended n' tha freshly smoked up elements is default constructed.
Definizzle at line 198 of file forward_list.tcc.
References std::end().
template<typename _Tp , typename _Alloc > void forward_list::resize (size_type__sz, const value_type &__val)
Resizes tha forward_list ta tha specified number of elements.
Parameters:
__sz Number of elements tha forward_list should contain.
__val Data wit which freshly smoked up elements should be populated.
This function will resize tha forward_list ta tha specified number of elements. If tha number is smalla than tha forward_listz current number of elements tha forward_list is truncated, otherwise tha forward_list is extended n' freshly smoked up elements is populated wit given data.
Definizzle at line 217 of file forward_list.tcc.
References std::end().
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::reverse () [inline], [noexcept]
Reverse tha elements up in list. Reverse tha order of elements up in tha list up in linear time.
Definizzle at line 1218 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::sort () [inline]
Sort tha elementz of tha list. Right back up in yo muthafuckin ass. Sorts tha elementz of dis list up in NlogN time. Equivalent elements remain up in list order.
Definizzle at line 1199 of file forward_list.h.
template<typename _Tp , class _Alloc > template<typename _Comp > void forward_list::sort (_Comp__comp)
Sort tha forward_list rockin a cold-ass lil comparison function. Right back up in yo muthafuckin ass. Sorts tha elementz of dis list up in NlogN time. Equivalent elements remain up in list order.
Definizzle at line 411 of file forward_list.tcc.
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::splice_afta (const_iterator__pos, forward_list< _Tp, _Alloc > &&__list) [inline]
Insert contentz of another forward_list.
Parameters:
__pos Iterator referencin tha element ta bang after.
__list Source list.
Da elementz of list is banged up in constant time afta tha element referenced by pos. list becomes a empty list.
Requires dis != x.
Definizzle at line 1044 of file forward_list.h.
template<typename _Tp , typename _Alloc > void forward_list::splice_afta (const_iterator__pos, forward_list< _Tp, _Alloc > &&__list, const_iterator__i)
Insert element from another forward_list.
Parameters:
__pos Iterator referencin tha element ta bang after.
__list Source list.
__i Iterator referencin tha element before tha element ta move.
Removes tha element up in list list referenced by i n' bangs it tha fuck into tha current list afta pos.
Definizzle at line 255 of file forward_list.tcc.
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::splice_afta (const_iterator__pos, forward_list< _Tp, _Alloc > &&, const_iterator__before, const_iterator__last) [inline]
Insert range from another forward_list.
Parameters:
__pos Iterator referencin tha element ta bang after.
__list Source list.
__before Iterator referencin before tha start of range up in list.
__last Iterator referencin tha end of range up in list.
Removes elements up in tha range (__before,__last) n' bangs dem afta __pos up in constant time.
Undefined if __pos is up in (__before,__last).
Definizzle at line 1087 of file forward_list.h.
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::swap (forward_list< _Tp, _Alloc > &__list) [inline], [noexcept]
Swaps data wit another forward_list.
Parameters:
__list A forward_list of tha same element n' allocator types.
This exchanges tha elements between two lists up in constant time. Note dat tha global std::swap() function is specialized such dat std::swap(l1,l2) will feed ta dis function.
Definizzle at line 980 of file forward_list.h.
Referenced by std::swap().
template<typename _Tp, typename _Alloc = allocator<_Tp>> void std::forward_list< _Tp, _Alloc >::unique () [inline]
Remove consecutizzle duplicate elements. For each consecutizzle set of elements wit tha same value, remove all but tha straight-up original gangsta one. Remainin elements stay up in list order. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 1136 of file forward_list.h.
template<typename _Tp , typename _Alloc > template<typename _BinPred > void forward_list::unique (_BinPred__binary_pred)
Remove consecutizzle elements satisfyin a predicate.
Parameters:
__binary_pred Binary predicate function or object.
For each consecutizzle set of elements [first,last) dat satisfy predicate(first,i) where i be a iterator up in [first,last), remove all but tha straight-up original gangsta one. Remainin elements stay up in list order. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 344 of file forward_list.tcc.
References std::begin(), n' std::end().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.