" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::num_get< _CharT, _InIta > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::locale::facet\fP\&.
.SS "Public Types"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef _InIta \fBiter_type\fP"
.br
.in -1c
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnum_get\fP (size_t __refs=0)"
.br
.ti -1c
.RI "template<typename _ValueT > _InIta \fB_M_extract_int\fP (_InIta __beg, _InIta __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, _ValueT &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, bool &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, void *&__v) const "
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned short &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned int &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long long &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long long &__v) const "
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, float &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, double &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long double &__v) const "
.br
.in -1c
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBlocale::id\fP \fBid\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~num_get\fP ()"
.br
.ti -1c
.RI "\fBiter_type\fP \fB_M_extract_float\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, \fBstring\fP &) const "
.br
.ti -1c
.RI "template<typename _ValueT > \fBiter_type\fP \fB_M_extract_int\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, _ValueT &) const "
.br
.ti -1c
.RI "template<typename _CharT2 > __gnu_cxx::__enable_if
.br
< __is_char< _CharT2 >
.br
::__value, int >::__type \fB_M_find\fP (const _CharT2 *, size_t __len, _CharT2 __c) const "
.br
.ti -1c
.RI "template<typename _CharT2 > __gnu_cxx::__enable_if
.br
<!__is_char< _CharT2 >
.br
::__value, int >::__type \fB_M_find\fP (const _CharT2 *__zero, size_t __len, _CharT2 __c) const "
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, bool &) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned short &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned int &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long long &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long long &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, float &) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, double &) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, long double &) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, void *&) const "
.br
.in -1c
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static __c_locale \fB_S_clone_c_locale\fP (__c_locale &__cloc)  throw ()"
.br
.ti -1c
.RI "static void \fB_S_create_c_locale\fP (__c_locale &__cloc, const char *__s, __c_locale __old=0)"
.br
.ti -1c
.RI "static void \fB_S_destroy_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static __c_locale \fB_S_get_c_locale\fP ()"
.br
.ti -1c
.RI "static const char * \fB_S_get_c_name\fP ()  throw ()"
.br
.ti -1c
.RI "static __c_locale \fB_S_lc_ctype_c_locale\fP (__c_locale __cloc, const char *__s)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT, typename _InIter>class std::num_get< _CharT, _InIta >"
Primary class template num_get\&.
.PP
This facet encapsulates tha code ta parse n' return a number from a string\&. Well shiiiit, it is used by tha istream numeric extraction operators\&. 

Da num_get template uses protected virtual functions ta provide tha actual thangs up in dis biatch\&. Da hood accessors forward tha call ta tha virtual functions\&. These virtual functions is hooks fo' pimpers ta implement tha behavior they require from tha num_get facet\&. 
.PP
Definizzle at line 1915 of file locale_facets\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _CharT , typename _InIta > typedef _CharT \fBstd::num_get\fP< _CharT, _InIta >::\fBchar_type\fP"

.PP
Public typedefs\&. 
.PP
Definizzle at line 1921 of file locale_facets\&.h\&.
.SS "template<typename _CharT , typename _InIta > typedef _InIta \fBstd::num_get\fP< _CharT, _InIta >::\fBiter_type\fP"

.PP
Public typedefs\&. 
.PP
Definizzle at line 1922 of file locale_facets\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _CharT , typename _InIta > \fBstd::num_get\fP< _CharT, _InIta >::\fBnum_get\fP (size_t__refs = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Constructor performs initialization\&. This is tha constructor provided by tha standard\&.
.PP
\fBParameters:\fP
.RS 4
\fI__refs\fP Passed ta tha base facet class\&. 
.RE
.PP

.PP
Definizzle at line 1936 of file locale_facets\&.h\&.
.SS "template<typename _CharT , typename _InIta > virtual \fBstd::num_get\fP< _CharT, _InIta >::~\fBnum_get\fP ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Destructor\&. 
.PP
Definizzle at line 2108 of file locale_facets\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _CharT , typename _InIta > _InIta \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, bool &__v) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 590 of file locale_facets\&.tcc\&.
.PP
References std::ios_base::_M_getloc(), std::ios_base::boolalpha, std::ios_base::eofbit, std::ios_base::failbit, std::ios_base::flags(), n' std::ios_base::goodbit\&.
.PP
Referenced by std::num_get< _CharT, _InIta >::get()\&.
.SS "template<typename _CharT , typename _InIta > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long &__v) const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2176 of file locale_facets\&.h\&.
.SS "template<typename _CharT , typename _InIta > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned short &__v) const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2181 of file locale_facets\&.h\&.
.SS "template<typename _CharT , typename _InIta > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned int &__v) const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2186 of file locale_facets\&.h\&.
.SS "template<typename _CharT , typename _InIta > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long &__v) const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2191 of file locale_facets\&.h\&.
.SS "template<typename _CharT , typename _InIta > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long long &__v) const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2197 of file locale_facets\&.h\&.
.SS "template<typename _CharT , typename _InIta > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long long &__v) const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2202 of file locale_facets\&.h\&.
.SS "template<typename _CharT , typename _InIta > _InIta \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, float &__v) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 686 of file locale_facets\&.tcc\&.
.PP
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, n' std::basic_string< _CharT, _Traits, _Alloc >::reserve()\&.
.SS "template<typename _CharT , typename _InIta > _InIta \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, double &__v) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 701 of file locale_facets\&.tcc\&.
.PP
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, n' std::basic_string< _CharT, _Traits, _Alloc >::reserve()\&.
.SS "template<typename _CharT , typename _InIta > _InIta \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long double &__v) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 733 of file locale_facets\&.tcc\&.
.PP
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, n' std::basic_string< _CharT, _Traits, _Alloc >::reserve()\&.
.SS "template<typename _CharT , typename _InIta > _InIta \fBstd::num_get\fP< _CharT, _InIta >::do_get (\fBiter_type\fP__beg, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, void *&__v) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha variable \fIv\fP\&. This function be a hook fo' derived classes ta chizzle tha value returned\&. 
.PP
\fBSee Also:\fP
.RS 4
get() fo' mo' details\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__beg\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 748 of file locale_facets\&.tcc\&.
.PP
References std::ios_base::basefield, std::ios_base::flags(), n' std::ios_base::hex\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, bool &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha bool \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
If ios_base::boolalpha is set, attempts ta read ctype<CharT>::truename() or ctype<CharT>::falsename()\&. Right back up in yo muthafuckin ass. Sets \fIv\fP ta legit or false if successful\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::failbit if readin tha strang fails\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
If ios_base::boolalpha aint set, proceedz as wit readin a long, except if tha value is 1, sets \fIv\fP ta true, if tha value is 0, sets \fIv\fP ta false, n' otherwise set err ta ios_base::failbit\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 1962 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.PP
Referenced by std::basic_istream< _CharT, _Traits >::operator>>()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Parsin be affected by tha flag settings up in \fIio\fP\&.
.PP
Da basic parse be affected by tha value of io\&.flags() & ios_base::basefield\&. If equal ta ios_base::oct, parses like tha scanf o specifier\&. Else if equal ta ios_base::hex, parses like X specifier\&. Else if basefield equal ta 0, parses like tha i specifier\&. Otherwise, parses like d fo' signed n' u fo' unsigned types\&. Da matchin type length modifier be also used\&.
.PP
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 1999 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned short &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Parsin be affected by tha flag settings up in \fIio\fP\&.
.PP
Da basic parse be affected by tha value of io\&.flags() & ios_base::basefield\&. If equal ta ios_base::oct, parses like tha scanf o specifier\&. Else if equal ta ios_base::hex, parses like X specifier\&. Else if basefield equal ta 0, parses like tha i specifier\&. Otherwise, parses like d fo' signed n' u fo' unsigned types\&. Da matchin type length modifier be also used\&.
.PP
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2004 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned int &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Parsin be affected by tha flag settings up in \fIio\fP\&.
.PP
Da basic parse be affected by tha value of io\&.flags() & ios_base::basefield\&. If equal ta ios_base::oct, parses like tha scanf o specifier\&. Else if equal ta ios_base::hex, parses like X specifier\&. Else if basefield equal ta 0, parses like tha i specifier\&. Otherwise, parses like d fo' signed n' u fo' unsigned types\&. Da matchin type length modifier be also used\&.
.PP
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2009 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Parsin be affected by tha flag settings up in \fIio\fP\&.
.PP
Da basic parse be affected by tha value of io\&.flags() & ios_base::basefield\&. If equal ta ios_base::oct, parses like tha scanf o specifier\&. Else if equal ta ios_base::hex, parses like X specifier\&. Else if basefield equal ta 0, parses like tha i specifier\&. Otherwise, parses like d fo' signed n' u fo' unsigned types\&. Da matchin type length modifier be also used\&.
.PP
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2014 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long long &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Parsin be affected by tha flag settings up in \fIio\fP\&.
.PP
Da basic parse be affected by tha value of io\&.flags() & ios_base::basefield\&. If equal ta ios_base::oct, parses like tha scanf o specifier\&. Else if equal ta ios_base::hex, parses like X specifier\&. Else if basefield equal ta 0, parses like tha i specifier\&. Otherwise, parses like d fo' signed n' u fo' unsigned types\&. Da matchin type length modifier be also used\&.
.PP
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2020 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long long &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Parsin be affected by tha flag settings up in \fIio\fP\&.
.PP
Da basic parse be affected by tha value of io\&.flags() & ios_base::basefield\&. If equal ta ios_base::oct, parses like tha scanf o specifier\&. Else if equal ta ios_base::hex, parses like X specifier\&. Else if basefield equal ta 0, parses like tha i specifier\&. Otherwise, parses like d fo' signed n' u fo' unsigned types\&. Da matchin type length modifier be also used\&.
.PP
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2025 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, float &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Da input charactas is parsed like tha scanf g specifier\&. Da matchin type length modifier be also used\&.
.PP
Da decimal point characta used is numpunct::decimal_point()\&. Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2059 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, double &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Da input charactas is parsed like tha scanf g specifier\&. Da matchin type length modifier be also used\&.
.PP
Da decimal point characta used is numpunct::decimal_point()\&. Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2064 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long double &__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha integral variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Da input charactas is parsed like tha scanf g specifier\&. Da matchin type length modifier be also used\&.
.PP
Da decimal point characta used is numpunct::decimal_point()\&. Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2069 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SS "template<typename _CharT , typename _InIta > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIta >::get (\fBiter_type\fP__in, \fBiter_type\fP__end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, void *&__v) const\fC [inline]\fP"

.PP
Numeric parsing\&. Parses tha input stream tha fuck into tha pointa variable \fIv\fP\&. Well shiiiit, it do so by callin num_get::do_get()\&.
.PP
Da input charactas is parsed like tha scanf p specifier\&.
.PP
Digit groupin is interpreted accordin ta numpunct::grouping() n' numpunct::thousands_sep()\&. If tha pattern of digit crews aint consistent, sets err ta ios_base::failbit\&.
.PP
Note dat tha digit groupin effect fo' pointas be a lil' bit ambiguous up in tha standard n' shouldn't be relied on\&. Right back up in yo muthafuckin ass. See DR 344\&.
.PP
If parsin tha strang yieldz a valid value fo' \fIv\fP, \fIv\fP is set\&. Otherwise, sets err ta ios_base::failbit n' leaves \fIv\fP unaltered\&. Right back up in yo muthafuckin ass. Sets err ta ios_base::eofbit if tha stream is emptied\&.
.PP
\fBParameters:\fP
.RS 4
\fI__in\fP Start of input stream\&. 
.br
\fI__end\fP End of input stream\&. 
.br
\fI__io\fP Source of locale n' flags\&. 
.br
\fI__err\fP Error flags ta set\&. 
.br
\fI__v\fP Value ta format n' insert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator afta reading\&. 
.RE
.PP

.PP
Definizzle at line 2102 of file locale_facets\&.h\&.
.PP
References std::num_get< _CharT, _InIta >::do_get()\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _CharT , typename _InIta > \fBlocale::id\fP \fBstd::num_get\fP< _CharT, _InIta >::id\fC [static]\fP"

.PP
Numpunct facet id\&. 
.PP
Definizzle at line 1926 of file locale_facets\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen fo' libstdc++ from tha source code\&.
