" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::moneypunct_byname< _CharT, _Intl > -
SYNOPSIS
Inherits std::moneypunct< _CharT, _Intl >.
Public Types
enum { _S_minus, _S_zero, _S_end }
typedef __moneypunct_cache
< _CharT, _Intl > __cache_type"
typedef _CharT char_type
enum part { none, space, symbol, sign, value }
typedef basic_string< _CharT > string_type
Public Member Functions
moneypunct_byname (const char *__s, size_t __refs=0)
string_type curr_symbol () const
char_type decimal_point () const
int frac_digits () const
string grouping () const
string_type negative_sign () const
string_type positive_sign () const
char_type thousands_sep () const
pattern pos_format () const
pattern neg_format () const
Static Public Member Functions
static pattern _S_construct_pattern (char __precedes, char __space, char __posn) throw ()
Static Public Attributes
static const char * _S_atoms
static const pattern _S_default_pattern
static locale::id id
static const bool intl
Protected Member Functions
void _M_initialize_moneypunct (__c_locale __cloc=0, const char *__name=0)
template<> void _M_initialize_moneypunct (__c_locale, const char *)
template<> void _M_initialize_moneypunct (__c_locale, const char *)
template<> void _M_initialize_moneypunct (__c_locale, const char *)
template<> void _M_initialize_moneypunct (__c_locale, const char *)
virtual string_type do_curr_symbol () const
virtual char_type do_decimal_point () const
virtual int do_frac_digits () const
virtual string do_grouping () const
virtual pattern do_neg_format () const
virtual string_type do_negative_sign () const
virtual pattern do_pos_format () const
virtual string_type do_positive_sign () const
virtual char_type do_thousands_sep () const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Detailed Description
template<typename _CharT, bool _Intl>class std::moneypunct_byname< _CharT, _Intl >
class scrillapunct_byname [22.2.6.4].
Definizzle at line 1324 of file locale_facets_nonio.h.
Member Function Documentation
template<typename _CharT , bool _Intl> string_type std::moneypunct< _CharT, _Intl >::curr_symbol () const [inline], [inherited]
Return currency symbol string. This function returns a string_type ta use as a cold-ass lil currency symbol. Well shiiiit, it do so by returnin returnin scrillapunct<char_type>::do_curr_symbol().
Returns:
string_type representin a cold-ass lil currency symbol.
Definizzle at line 1061 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_curr_symbol().
template<typename _CharT , bool _Intl> char_type std::moneypunct< _CharT, _Intl >::decimal_point () const [inline], [inherited]
Return decimal point character. This function returns a cold-ass lil char_type ta use as a thugged-out decimal point. Well shiiiit, it do so by returnin returnin scrillapunct<char_type>::do_decimal_point().
Returns:
char_type representin a thugged-out decimal point.
Definizzle at line 1005 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_decimal_point().
template<typename _CharT , bool _Intl> virtual string_type std::moneypunct< _CharT, _Intl >::do_curr_symbol () const [inline], [protected], [virtual], [inherited]
Return currency symbol string. This function returns a string_type ta use as a cold-ass lil currency symbol. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
curr_symbol() fo' details.
Returns:
string_type representin a cold-ass lil currency symbol.
Definizzle at line 1207 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::curr_symbol().
template<typename _CharT , bool _Intl> virtual char_type std::moneypunct< _CharT, _Intl >::do_decimal_point () const [inline], [protected], [virtual], [inherited]
Return decimal point character. Returns a cold-ass lil char_type ta use as a thugged-out decimal point. This function be a hook fo' derived classes ta chizzle tha value returned.
Returns:
char_type representin a thugged-out decimal point.
Definizzle at line 1169 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::decimal_point().
template<typename _CharT , bool _Intl> virtual int std::moneypunct< _CharT, _Intl >::do_frac_digits () const [inline], [protected], [virtual], [inherited]
Return number of digits up in fraction. This function returns tha exact number of digits dat make up tha fractionizzle part of a scrilla amount. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
frac_digits() fo' details.
Returns:
Number of digits up in amount fraction.
Definizzle at line 1247 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::frac_digits().
template<typename _CharT , bool _Intl> virtual string std::moneypunct< _CharT, _Intl >::do_groupin () const [inline], [protected], [virtual], [inherited]
Return groupin justification. Returns a strang representin groupings fo' tha integer part of a number. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
grouping() fo' details.
Returns:
Strin representin groupin justification.
Definizzle at line 1194 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::grouping().
template<typename _CharT , bool _Intl> virtual pattern std::moneypunct< _CharT, _Intl >::do_neg_format () const [inline], [protected], [virtual], [inherited]
Return pattern fo' scrilla joints. This function returns a pattern describin tha formattin of a wack valued scrilla amount. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
neg_format() fo' details.
Returns:
Pattern fo' scrilla joints.
Definizzle at line 1275 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::neg_format().
template<typename _CharT , bool _Intl> virtual string_type std::moneypunct< _CharT, _Intl >::do_negative_sign () const [inline], [protected], [virtual], [inherited]
Return wack sign string. This function returns a string_type ta use as a sign fo' wack amounts. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
negative_sign() fo' details.
Returns:
string_type representin a wack sign.
Definizzle at line 1233 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::negative_sign().
template<typename _CharT , bool _Intl> virtual pattern std::moneypunct< _CharT, _Intl >::do_pos_format () const [inline], [protected], [virtual], [inherited]
Return pattern fo' scrilla joints. This function returns a pattern describin tha formattin of a positizzle valued scrilla amount. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
pos_format() fo' details.
Returns:
Pattern fo' scrilla joints.
Definizzle at line 1261 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::pos_format().
template<typename _CharT , bool _Intl> virtual string_type std::moneypunct< _CharT, _Intl >::do_positive_sign () const [inline], [protected], [virtual], [inherited]
Return positizzle sign string. This function returns a string_type ta use as a sign fo' positizzle amounts. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
positive_sign() fo' details.
Returns:
string_type representin a positizzle sign.
Definizzle at line 1220 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::positive_sign().
template<typename _CharT , bool _Intl> virtual char_type std::moneypunct< _CharT, _Intl >::do_thousands_sep () const [inline], [protected], [virtual], [inherited]
Return thousandz separator character. Returns a cold-ass lil char_type ta use as a thousandz separator. This function be a hook fo' derived classes ta chizzle tha value returned.
Returns:
char_type representin a thousandz separator.
Definizzle at line 1181 of file locale_facets_nonio.h.
Referenced by std::moneypunct< _CharT, _Intl >::thousands_sep().
template<typename _CharT , bool _Intl> int std::moneypunct< _CharT, _Intl >::frac_digits () const [inline], [inherited]
Return number of digits up in fraction. This function returns tha exact number of digits dat make up tha fractionizzle part of a scrilla amount. Well shiiiit, it do so by returnin returnin scrillapunct<char_type>::do_frac_digits().
Da fractionizzle part of a scrilla amount is optional. But if it is present, there must be frac_digits() digits.
Returns:
Number of digits up in amount fraction.
Definizzle at line 1111 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_frac_digits().
template<typename _CharT , bool _Intl> string std::moneypunct< _CharT, _Intl >::groupin () const [inline], [inherited]
Return groupin justification. This function returns a strang representin groupings fo' tha integer part of a amount. Groupings indicate where thousandz separators should be inserted.
Each char up in tha return strang is interpret as a integer rather than a cold-ass lil character. These numbers represent tha number of digits up in a group. Da first char up in tha strang represents tha number of digits up in tha least dope group. If a cold-ass lil char is negative, it indicates a unlimited number of digits fo' tha group. If mo' chars from tha strang is required ta crew a number, tha last char is used repeatedly.
For example, if tha grouping() returns \003\002 n' be applied ta tha number 123456789, dis correspondz ta 12,34,56,789. Note dat if tha strang was 32, dis would put mo' than 50 digits tha fuck into tha least dope crew if tha characta set is ASCII.
Da strang is returned by callin scrillapunct<char_type>::do_grouping().
Returns:
strin representin groupin justification.
Definizzle at line 1048 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_grouping().
template<typename _CharT , bool _Intl> pattern std::moneypunct< _CharT, _Intl >::neg_format () const [inline], [inherited]
Return pattern fo' scrilla joints. This function returns a pattern describin tha formattin of a positizzle or wack valued scrilla amount. Well shiiiit, it do so by returnin returnin scrillapunct<char_type>::do_pos_format() or scrillapunct<char_type>::do_neg_format().
Da pattern has 4 fieldz describin tha orderin of symbol, sign, value, n' none or space. There must be one of each up in tha pattern. Da none n' space enums may not step tha fuck up in tha straight-up original gangsta field n' space may not step tha fuck up in tha final field.
Da partz of a scrilla strang must step tha fuck up in tha order indicated by tha fieldz of tha pattern. Da symbol field indicates dat tha value of curr_symbol() may be present. Da sign field indicates dat tha value of positive_sign() or negative_sign() must be present. Da value field indicates dat tha absolute value of tha scrilla amount is present. none indicates 0 or mo' whitespace characters, except all up in tha end, where it permits no whitespace. space indicates dat 1 or mo' whitespace charactas must be present.
For example, fo' tha US locale n' pos_format() pattern {symbol,sign,value,none}, curr_symbol() == '$' positive_sign() == '+', n' value 10.01, n' options set ta force tha symbol, tha correspondin strang is $+10.01.
Returns:
Pattern fo' scrilla joints.
Definizzle at line 1151 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_neg_format().
template<typename _CharT , bool _Intl> string_type std::moneypunct< _CharT, _Intl >::negative_sign () const [inline], [inherited]
Return wack sign string. This function returns a string_type ta use as a sign fo' wack amounts. Well shiiiit, it do so by returnin returnin scrillapunct<char_type>::do_negative_sign().
If tha return value gotz nuff mo' than one character, tha straight-up original gangsta characta appears up in tha posizzle indicated by neg_format() n' tha remainder step tha fuck up all up in tha end of tha formatted string.
Returns:
string_type representin a wack sign.
Definizzle at line 1095 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_negative_sign().
template<typename _CharT , bool _Intl> pattern std::moneypunct< _CharT, _Intl >::pos_format () const [inline], [inherited]
Return pattern fo' scrilla joints. This function returns a pattern describin tha formattin of a positizzle or wack valued scrilla amount. Well shiiiit, it do so by returnin returnin scrillapunct<char_type>::do_pos_format() or scrillapunct<char_type>::do_neg_format().
Da pattern has 4 fieldz describin tha orderin of symbol, sign, value, n' none or space. There must be one of each up in tha pattern. Da none n' space enums may not step tha fuck up in tha straight-up original gangsta field n' space may not step tha fuck up in tha final field.
Da partz of a scrilla strang must step tha fuck up in tha order indicated by tha fieldz of tha pattern. Da symbol field indicates dat tha value of curr_symbol() may be present. Da sign field indicates dat tha value of positive_sign() or negative_sign() must be present. Da value field indicates dat tha absolute value of tha scrilla amount is present. none indicates 0 or mo' whitespace characters, except all up in tha end, where it permits no whitespace. space indicates dat 1 or mo' whitespace charactas must be present.
For example, fo' tha US locale n' pos_format() pattern {symbol,sign,value,none}, curr_symbol() == '$' positive_sign() == '+', n' value 10.01, n' options set ta force tha symbol, tha correspondin strang is $+10.01.
Returns:
Pattern fo' scrilla joints.
Definizzle at line 1147 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_pos_format().
template<typename _CharT , bool _Intl> string_type std::moneypunct< _CharT, _Intl >::positive_sign () const [inline], [inherited]
Return positizzle sign string. This function returns a string_type ta use as a sign fo' positizzle amounts. Well shiiiit, it do so by returnin returnin scrillapunct<char_type>::do_positive_sign().
If tha return value gotz nuff mo' than one character, tha straight-up original gangsta characta appears up in tha posizzle indicated by pos_format() n' tha remainder step tha fuck up all up in tha end of tha formatted string.
Returns:
string_type representin a positizzle sign.
Definizzle at line 1078 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_positive_sign().
template<typename _CharT , bool _Intl> char_type std::moneypunct< _CharT, _Intl >::thousands_sep () const [inline], [inherited]
Return thousandz separator character. This function returns a cold-ass lil char_type ta use as a thousandz separator. Well shiiiit, it do so by returnin returnin scrillapunct<char_type>::do_thousands_sep().
Returns:
char_type representin a thousandz separator.
Definizzle at line 1018 of file locale_facets_nonio.h.
References std::moneypunct< _CharT, _Intl >::do_thousands_sep().
Member Data Documentation
template<typename _CharT , bool _Intl> locale::id std::moneypunct< _CharT, _Intl >::id [static], [inherited]
Numpunct facet id.
Definizzle at line 953 of file locale_facets_nonio.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.