" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::map< _Key, _Tp, _Compare, _Alloc > -
SYNOPSIS
Public Types
typedef _Alloc allocator_type
typedef _Rep_type::const_iterator const_iterator
typedef
_Pair_alloc_type::const_pointa const_pointer"
typedef
_Pair_alloc_type::const_reference const_reference"
typedef
_Rep_type::const_reverse_iterator const_reverse_iterator"
typedef _Rep_type::difference_type difference_type
typedef _Rep_type::iterator iterator
typedef _Compare key_compare
typedef _Key key_type
typedef _Tp mapped_type
typedef _Pair_alloc_type::pointa pointer
typedef _Pair_alloc_type::reference reference
typedef _Rep_type::reverse_iterator reverse_iterator
typedef _Rep_type::size_type size_type
typedef std::pair< const _Key,
_Tp > value_type"
Public Member Functions
map ()
map (const _Compare &__comp, const allocator_type &__a=allocator_type())
map (const map &__x)
map (map &&__x) noexcept(is_nothrow_copy_constructible< _Compare >::value)
map (initializer_list< value_type > __l, const _Compare &__comp=_Compare(), const allocator_type &__a=allocator_type())
template<typename _InputIterator > map (_InputIterator __first, _InputIterator __last)
template<typename _InputIterator > map (_InputIterator __first, _InputIterator __last, const _Compare &__comp, const allocator_type &__a=allocator_type())
mapped_type & at (const key_type &__k)
const mapped_type & at (const key_type &__k) const
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
size_type count (const key_type &__x) const
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
template<typename... _Args> std::pair< iterator, bool > emplace (_Args &&...__args)
template<typename... _Args> iterator emplace_hint (const_iterator __pos, _Args &&...__args)
bool empty () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
std::pair< iterator, iterator > equal_range (const key_type &__x)
std::pair< const_iterator,
const_iterator > equal_range (const key_type &__x) const "
iterator erase (const_iterator __position)
_GLIBCXX_ABI_TAG_CXX11 iterator erase (iterator __position)
size_type erase (const key_type &__x)
iterator erase (const_iterator __first, const_iterator __last)
iterator find (const key_type &__x)
const_iterator find (const key_type &__x) const
allocator_type get_allocator () const noexcept
std::pair< iterator, bool > insert (const value_type &__x)
template<typename _Pair , typename = typename std::enable_if<std::is_constructible<value_type,						    _Pair&&>::value>::type> std::pair< iterator, bool > insert (_Pair &&__x)
void insert (std::initializer_list< value_type > __list)
iterator insert (const_iterator __position, const value_type &__x)
template<typename _Pair , typename = typename std::enable_if<std::is_constructible<value_type,						    _Pair&&>::value>::type> iterator insert (const_iterator __position, _Pair &&__x)
template<typename _InputIterator > void insert (_InputIterator __first, _InputIterator __last)
key_compare key_comp () const
iterator lower_bound (const key_type &__x)
const_iterator lower_bound (const key_type &__x) const
size_type max_size () const noexcept
map & operator= (const map &__x)
map & operator= (map &&__x)
map & operator= (initializer_list< value_type > __l)
mapped_type & operator[] (const key_type &__k)
mapped_type & operator[] (key_type &&__k)
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
size_type size () const noexcept
void swap (map &__x)
iterator upper_bound (const key_type &__x)
const_iterator upper_bound (const key_type &__x) const
value_compare value_comp () const
Friends
template<typename _K1 , typename _T1 , typename _C1 , typename _A1 > bool operator< (const map< _K1, _T1, _C1, _A1 > &, const map< _K1, _T1, _C1, _A1 > &)
template<typename _K1 , typename _T1 , typename _C1 , typename _A1 > bool operator== (const map< _K1, _T1, _C1, _A1 > &, const map< _K1, _T1, _C1, _A1 > &)
Detailed Description
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >>class std::map< _Key, _Tp, _Compare, _Alloc >
A standard container made up of (key,value) pairs, which can be retrieved based on a key, up in logarithmic time.
Template Parameters:
_Key Type of key objects.
_Tp Type of mapped objects.
_Compare Comparison function object type, defaults ta less<_Key>.
_Alloc Allocator type, defaults ta allocator<pair<const _Key, _Tp>.
Meets tha requirementz of a container, a reversible container, n' a associatizzle container (usin unique keys). For a map<Key,T> tha key_type is Key, tha mapped_type is T, n' tha value_type is std::pair<const Key,T>.
Maps support bidirectionizzle iterators.
Da private tree data is declared exactly tha same way fo' map n' multimap; tha distinction is made entirely up in how tha fuck tha tree functions is called (*_unique versus *_equal, same as tha standard).
Definizzle at line 96 of file stl_map.h.
Constructor & Destructor Documentation
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::map< _Key, _Tp, _Compare, _Alloc >::map () [inline]
Default constructor creates no elements.
Definizzle at line 160 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::map< _Key, _Tp, _Compare, _Alloc >::map (const _Compare &__comp, const allocator_type &__a = allocator_type()) [inline], [explicit]
Creates a map wit no elements.
Parameters:
__comp A comparison object.
__a An allocator object.
Definizzle at line 169 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::map< _Key, _Tp, _Compare, _Alloc >::map (const map< _Key, _Tp, _Compare, _Alloc > &__x) [inline]
Map copy constructor.
Parameters:
__x A map of identical element n' allocator types.
Da newly-created map uses a cold-ass lil copy of tha allocation object used by __x.
Definizzle at line 180 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::map< _Key, _Tp, _Compare, _Alloc >::map (map< _Key, _Tp, _Compare, _Alloc > &&__x) [inline], [noexcept]
Map move constructor.
Parameters:
__x A map of identical element n' allocator types.
Da newly-created map gotz nuff tha exact contentz of __x. Da contentz of __x is a valid yo, but unspecified map.
Definizzle at line 191 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::map< _Key, _Tp, _Compare, _Alloc >::map (initializer_list< value_type >__l, const _Compare &__comp = _Compare(), const allocator_type &__a = allocator_type()) [inline]
Buildz a map from a initializer_list.
Parameters:
__l An initializer_list.
__comp A comparison object.
__a An allocator object.
Smoke a map consistin of copiez of tha elements up in tha initializer_list __l. This is linear up in N if tha range be already sorted, n' NlogN otherwise (where N is __l.size()).
Definizzle at line 206 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> template<typename _InputIterator > std::map< _Key, _Tp, _Compare, _Alloc >::map (_InputIterator__first, _InputIterator__last) [inline]
Buildz a map from a range.
Parameters:
__first An input iterator.
__last An input iterator.
Smoke a map consistin of copiez of tha elements from [__first,__last). This is linear up in N if tha range be already sorted, n' NlogN otherwise (where N is distance(__first,__last)).
Definizzle at line 224 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> template<typename _InputIterator > std::map< _Key, _Tp, _Compare, _Alloc >::map (_InputIterator__first, _InputIterator__last, const _Compare &__comp, const allocator_type &__a = allocator_type()) [inline]
Buildz a map from a range.
Parameters:
__first An input iterator.
__last An input iterator.
__comp A comparison functor.
__a An allocator object.
Smoke a map consistin of copiez of tha elements from [__first,__last). This is linear up in N if tha range be already sorted, n' NlogN otherwise (where N is distance(__first,__last)).
Definizzle at line 241 of file stl_map.h.
Member Function Documentation
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> mapped_type& std::map< _Key, _Tp, _Compare, _Alloc >::at (const key_type &__k) [inline]
Access ta map data.
Parameters:
__k Da key fo' which data should be retrieved.
Returns:
A reference ta tha data whose key is equivalent ta __k, if such a thugged-out data is present up in tha map.
Exceptions:
std::out_of_range If no such data is present.
Definizzle at line 501 of file stl_map.h.
References std::map< _Key, _Tp, _Compare, _Alloc >::end(), std::map< _Key, _Tp, _Compare, _Alloc >::key_comp(), n' std::map< _Key, _Tp, _Compare, _Alloc >::lower_bound().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator std::map< _Key, _Tp, _Compare, _Alloc >::begin () [inline], [noexcept]
Returns a read/write iterator dat points ta tha straight-up original gangsta pair up in tha map. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 320 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator std::map< _Key, _Tp, _Compare, _Alloc >::begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta pair up in tha map. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 329 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator std::map< _Key, _Tp, _Compare, _Alloc >::cbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta pair up in tha map. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 393 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator std::map< _Key, _Tp, _Compare, _Alloc >::cend () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last pair up in tha map. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 402 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> void std::map< _Key, _Tp, _Compare, _Alloc >::clear () [inline], [noexcept]
Erases all elements up in a map. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 788 of file stl_map.h.
Referenced by std::map< _Key, _Tp, _Compare, _Alloc >::operator=().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> size_type std::map< _Key, _Tp, _Compare, _Alloc >::count (const key_type &__x) const [inline]
Findz tha number of elements wit given key.
Parameters:
__x Key of (key, value) pairs ta be located.
Returns:
Number of elements wit specified key.
This function only make sense fo' multimaps; fo' map tha result will either be 0 (not present) or 1 (present).
Definizzle at line 848 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_reverse_iterator std::map< _Key, _Tp, _Compare, _Alloc >::crbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last pair up in tha map. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 411 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_reverse_iterator std::map< _Key, _Tp, _Compare, _Alloc >::crend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta pair up in tha map. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 420 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> template<typename... _Args> std::pair<iterator, bool> std::map< _Key, _Tp, _Compare, _Alloc >::emplace (_Args &&...__args) [inline]
Attempts ta build n' bang a std::pair tha fuck into tha map.
Parameters:
__args Arguments used ta generate a freshly smoked up pair instizzle (see std::piecewise_contruct fo' passin arguments ta each part of tha pair constructor).
Returns:
A pair, of which tha straight-up original gangsta element be a iterator dat points ta tha possibly banged pair, n' tha second be a funky-ass bool dat is legit if tha pair was straight-up inserted.
This function attempts ta build n' bang a (key, value) pair tha fuck into tha map fo' realz. A map relies on unique keys n' thus a pair is only banged if its first element (the key) aint already present up in tha map.
Insertion requires logarithmic time.
Definizzle at line 540 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> template<typename... _Args> iterator std::map< _Key, _Tp, _Compare, _Alloc >::emplace_hint (const_iterator__pos, _Args &&...__args) [inline]
Attempts ta build n' bang a std::pair tha fuck into tha map.
Parameters:
__pos An iterator dat serves as a hint as ta where tha pair should be inserted.
__args Arguments used ta generate a freshly smoked up pair instizzle (see std::piecewise_contruct fo' passin arguments ta each part of tha pair constructor).
Returns:
An iterator dat points ta tha element wit key of tha std::pair built from __args (may or may not be dat std::pair).
This function aint concerned bout whether tha insertion took place, n' thus do not return a funky-ass boolean like tha single-argument emplace() do. Note dat tha straight-up original gangsta parameta is only a hint n' can potentially improve tha performizzle of tha insertion process fo' realz. A wack hint would cause no gains up in efficiency.
See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html fo' mo' on hinting.
Insertion requires logarithmic time (if tha hint aint taken).
Definizzle at line 570 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> bool std::map< _Key, _Tp, _Compare, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha map is empty. (Thus begin() would equal end().)
Definizzle at line 429 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator std::map< _Key, _Tp, _Compare, _Alloc >::end () [inline], [noexcept]
Returns a read/write iterator dat points one past tha last pair up in tha map. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 338 of file stl_map.h.
Referenced by std::map< _Key, _Tp, _Compare, _Alloc >::at(), n' std::map< _Key, _Tp, _Compare, _Alloc >::operator[]().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator std::map< _Key, _Tp, _Compare, _Alloc >::end () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last pair up in tha map. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 347 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::pair<iterator, iterator> std::map< _Key, _Tp, _Compare, _Alloc >::equal_range (const key_type &__x) [inline]
Findz a subsequence matchin given key.
Parameters:
__x Key of (key, value) pairs ta be located.
Returns:
Pair of iterators dat possibly points ta tha subsequence matchin given key.
This function is equivalent ta
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
 (but is fasta than makin tha calls separately).
This function probably only make sense fo' multimaps.
Definizzle at line 917 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::pair<const_iterator, const_iterator> std::map< _Key, _Tp, _Compare, _Alloc >::equal_range (const key_type &__x) const [inline]
Findz a subsequence matchin given key.
Parameters:
__x Key of (key, value) pairs ta be located.
Returns:
Pair of read-only (constant) iterators dat possibly points ta tha subsequence matchin given key.
This function is equivalent ta
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
 (but is fasta than makin tha calls separately).
This function probably only make sense fo' multimaps.
Definizzle at line 936 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator std::map< _Key, _Tp, _Compare, _Alloc >::erase (const_iterator__position) [inline]
Erases a element from a map.
Parameters:
__position An iterator pointin ta tha element ta be erased.
Returns:
An iterator pointin ta tha element immediately followin position prior ta tha element bein erased. If no such element exists, end() is returned.
This function erases a element, pointed ta by tha given iterator, from a map. Note dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 690 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> size_type std::map< _Key, _Tp, _Compare, _Alloc >::erase (const key_type &__x) [inline]
Erases elements accordin ta tha provided key.
Parameters:
__x Key of element ta be erased.
Returns:
Da number of elements erased.
This function erases all tha elements located by tha given key from a map. Note dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 726 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator std::map< _Key, _Tp, _Compare, _Alloc >::erase (const_iterator__first, const_iterator__last) [inline]
Erases a [first,last) range of elements from a map.
Parameters:
__first Iterator pointin ta tha start of tha range ta be erased.
__last Iterator pointin ta tha end of tha range ta be erased.
Returns:
Da iterator __last.
This function erases a sequence of elements from a map. Note dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 746 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator std::map< _Key, _Tp, _Compare, _Alloc >::find (const key_type &__x) [inline]
Tries ta locate a element up in a map.
Parameters:
__x Key of (key, value) pair ta be located.
Returns:
Iterator pointin ta sought-afta element, or end() if not found.
This function takes a key n' tries ta locate tha element wit which tha key matches. If successful tha function returns a iterator pointin ta tha sought afta pair. If unsuccessful it returns tha past-the-end ( end() ) iterator.
Definizzle at line 821 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator std::map< _Key, _Tp, _Compare, _Alloc >::find (const key_type &__x) const [inline]
Tries ta locate a element up in a map.
Parameters:
__x Key of (key, value) pair ta be located.
Returns:
Read-only (constant) iterator pointin ta sought-afta element, or end() if not found.
This function takes a key n' tries ta locate tha element wit which tha key matches. If successful tha function returns a cold-ass lil constant iterator pointin ta tha sought afta pair. If unsuccessful it returns tha past-the-end ( end() ) iterator.
Definizzle at line 836 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> allocator_type std::map< _Key, _Tp, _Compare, _Alloc >::get_allocator () const [inline], [noexcept]
Git a cold-ass lil copy of tha memory allocation object.
Definizzle at line 310 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::pair<iterator, bool> std::map< _Key, _Tp, _Compare, _Alloc >::insert (const value_type &__x) [inline]
Attempts ta bang a std::pair tha fuck into tha map.
Parameters:
__x Pair ta be banged (see std::make_pair fo' easy as fuck creation of pairs).
Returns:
A pair, of which tha straight-up original gangsta element be a iterator dat points ta tha possibly banged pair, n' tha second be a funky-ass bool dat is legit if tha pair was straight-up inserted.
This function attempts ta bang a (key, value) pair tha fuck into tha map fo' realz. A map relies on unique keys n' thus a pair is only banged if its first element (the key) aint already present up in tha map.
Insertion requires logarithmic time.
Definizzle at line 594 of file stl_map.h.
Referenced by std::map< _Key, _Tp, _Compare, _Alloc >::insert(), std::map< _Key, _Tp, _Compare, _Alloc >::operator=(), n' std::map< _Key, _Tp, _Compare, _Alloc >::operator[]().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> void std::map< _Key, _Tp, _Compare, _Alloc >::insert (std::initializer_list< value_type >__list) [inline]
Attempts ta bang a list of std::pairs tha fuck into tha map.
Parameters:
__list A std::initializer_list<value_type> of pairs ta be inserted.
Complexitizzle similar ta dat of tha range constructor.
Definizzle at line 615 of file stl_map.h.
References std::map< _Key, _Tp, _Compare, _Alloc >::insert().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator std::map< _Key, _Tp, _Compare, _Alloc >::insert (const_iterator__position, const value_type &__x) [inline]
Attempts ta bang a std::pair tha fuck into tha map.
Parameters:
__position An iterator dat serves as a hint as ta where tha pair should be inserted.
__x Pair ta be banged (see std::make_pair fo' easy as fuck creation of pairs).
Returns:
An iterator dat points ta tha element wit key of __x (may or may not be tha pair passed in).
This function aint concerned bout whether tha insertion took place, n' thus do not return a funky-ass boolean like tha single-argument insert() do. Note dat tha straight-up original gangsta parameta is only a hint n' can potentially improve tha performizzle of tha insertion process fo' realz. A wack hint would cause no gains up in efficiency.
See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html fo' mo' on hinting.
Insertion requires logarithmic time (if tha hint aint taken).
Definizzle at line 644 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> template<typename _InputIterator > void std::map< _Key, _Tp, _Compare, _Alloc >::insert (_InputIterator__first, _InputIterator__last) [inline]
Template function dat attempts ta bang a range of elements.
Parameters:
__first Iterator pointin ta tha start of tha range ta be inserted.
__last Iterator pointin ta tha end of tha range.
Complexitizzle similar ta dat of tha range constructor.
Definizzle at line 670 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> key_compare std::map< _Key, _Tp, _Compare, _Alloc >::key_comp () const [inline]
Returns tha key comparison object outta which tha map was constructed.
Definizzle at line 797 of file stl_map.h.
Referenced by std::map< _Key, _Tp, _Compare, _Alloc >::at(), n' std::map< _Key, _Tp, _Compare, _Alloc >::operator[]().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator std::map< _Key, _Tp, _Compare, _Alloc >::lower_bound (const key_type &__x) [inline]
Findz tha beginnin of a subsequence matchin given key.
Parameters:
__x Key of (key, value) pair ta be located.
Returns:
Iterator pointin ta first element equal ta or pimped outa than key, or end().
This function returns tha straight-up original gangsta element of a subsequence of elements dat matches tha given key. If unsuccessful it returns a iterator pointin ta tha straight-up original gangsta element dat has a pimped outa value than given key or end() if no such element exists.
Definizzle at line 863 of file stl_map.h.
Referenced by std::map< _Key, _Tp, _Compare, _Alloc >::at(), n' std::map< _Key, _Tp, _Compare, _Alloc >::operator[]().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator std::map< _Key, _Tp, _Compare, _Alloc >::lower_bound (const key_type &__x) const [inline]
Findz tha beginnin of a subsequence matchin given key.
Parameters:
__x Key of (key, value) pair ta be located.
Returns:
Read-only (constant) iterator pointin ta first element equal ta or pimped outa than key, or end().
This function returns tha straight-up original gangsta element of a subsequence of elements dat matches tha given key. If unsuccessful it returns a iterator pointin ta tha straight-up original gangsta element dat has a pimped outa value than given key or end() if no such element exists.
Definizzle at line 878 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> size_type std::map< _Key, _Tp, _Compare, _Alloc >::max_size () const [inline], [noexcept]
Returns tha maximum size of tha map.
Definizzle at line 439 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> map& std::map< _Key, _Tp, _Compare, _Alloc >::operator= (const map< _Key, _Tp, _Compare, _Alloc > &__x) [inline]
Map assignment operator. Da dtor only erases tha elements, n' note dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Parameters:
__x A map of identical element n' allocator types.
All tha elementz of __x is copied yo, but unlike tha copy constructor, tha allocator object aint copied.
Definizzle at line 264 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> map& std::map< _Key, _Tp, _Compare, _Alloc >::operator= (map< _Key, _Tp, _Compare, _Alloc > &&__x) [inline]
Map move assignment operator.
Parameters:
__x A map of identical element n' allocator types.
Da contentz of __x is moved tha fuck into dis map (without copying). __x be a valid yo, but unspecified map.
Definizzle at line 279 of file stl_map.h.
References std::map< _Key, _Tp, _Compare, _Alloc >::clear(), n' std::map< _Key, _Tp, _Compare, _Alloc >::swap().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> map& std::map< _Key, _Tp, _Compare, _Alloc >::operator= (initializer_list< value_type >__l) [inline]
Map list assignment operator.
Parameters:
__l An initializer_list.
This function fills a map wit copiez of tha elements up in tha initializer list __l.
Note dat tha assignment straight-up chizzlez tha map n' dat tha resultin mapz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 300 of file stl_map.h.
References std::map< _Key, _Tp, _Compare, _Alloc >::clear(), n' std::map< _Key, _Tp, _Compare, _Alloc >::insert().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> mapped_type& std::map< _Key, _Tp, _Compare, _Alloc >::operator[] (const key_type &__k) [inline]
Subscript ( [] ) access ta map data.
Parameters:
__k Da key fo' which data should be retrieved.
Returns:
A reference ta tha data of tha (key,data) pair.
Allows fo' easy as fuck lookup wit tha subscript ( [] ) operator. Returns data associated wit tha key specified up in subscript. If tha key do not exist, a pair wit dat key is pimped rockin default joints, which is then returned.
Lookup requires logarithmic time.
Definizzle at line 456 of file stl_map.h.
References std::map< _Key, _Tp, _Compare, _Alloc >::end(), std::map< _Key, _Tp, _Compare, _Alloc >::insert(), std::map< _Key, _Tp, _Compare, _Alloc >::key_comp(), std::map< _Key, _Tp, _Compare, _Alloc >::lower_bound(), n' std::piecewise_construct.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> reverse_iterator std::map< _Key, _Tp, _Compare, _Alloc >::rbegin () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta tha last pair up in tha map. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 356 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_reverse_iterator std::map< _Key, _Tp, _Compare, _Alloc >::rbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last pair up in tha map. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 365 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> reverse_iterator std::map< _Key, _Tp, _Compare, _Alloc >::rend () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta one before tha straight-up original gangsta pair up in tha map. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 374 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_reverse_iterator std::map< _Key, _Tp, _Compare, _Alloc >::rend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta pair up in tha map. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 383 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> size_type std::map< _Key, _Tp, _Compare, _Alloc >::size () const [inline], [noexcept]
Returns tha size of tha map.
Definizzle at line 434 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> void std::map< _Key, _Tp, _Compare, _Alloc >::swap (map< _Key, _Tp, _Compare, _Alloc > &__x) [inline]
Swaps data wit another map.
Parameters:
__x A map of tha same element n' allocator types.
This exchanges tha elements between two maps up in constant time. (It be only swappin a pointer, a integer, n' a instizzle of tha Compare type (which itself is often stateless n' empty), so it should be like fast.) Note dat tha global std::swap() function is specialized such dat std::swap(m1,m2) will feed ta dis function.
Definizzle at line 778 of file stl_map.h.
Referenced by std::map< _Key, _Tp, _Compare, _Alloc >::operator=(), n' std::swap().
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator std::map< _Key, _Tp, _Compare, _Alloc >::upper_bound (const key_type &__x) [inline]
Findz tha end of a subsequence matchin given key.
Parameters:
__x Key of (key, value) pair ta be located.
Returns:
Iterator pointin ta tha straight-up original gangsta element pimped outa than key, or end().
Definizzle at line 888 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator std::map< _Key, _Tp, _Compare, _Alloc >::upper_bound (const key_type &__x) const [inline]
Findz tha end of a subsequence matchin given key.
Parameters:
__x Key of (key, value) pair ta be located.
Returns:
Read-only (constant) iterator pointin ta first iterator pimped outa than key, or end().
Definizzle at line 898 of file stl_map.h.
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> value_compare std::map< _Key, _Tp, _Compare, _Alloc >::value_comp () const [inline]
Returns a value comparison object, built from tha key comparison object outta which tha map was constructed.
Definizzle at line 805 of file stl_map.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.