::sentry" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::basic_ostream< _CharT, _Traits >::sentry -
SYNOPSIS
Public Member Functions
sentry (basic_ostream< _CharT, _Traits > &__os)
~sentry ()
operator bool () const
Detailed Description
template<typename _CharT, typename _Traits = char_traits<_CharT>>class std::basic_ostream< _CharT, _Traits >::sentry
Performs setup work fo' output streams.
Objectz of dis class is pimped before all of tha standard insertas is run. Well shiiiit, it is responsible fo' exception-safe prefix n' suffix operations.
Definizzle at line 400 of file ostream.
Constructor & Destructor Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> std::basic_ostream< _CharT, _Traits >::sentry::sentry (basic_ostream< _CharT, _Traits > &__os) [explicit]
Da constructor performs preparatory work.
Parameters:
__os Da output stream ta guard.
If tha stream state is phat (__os.good() is true), then if tha stream is tied ta another output stream, is.tie()->flush() is called ta synchronize tha output sequences.
If tha stream state is still good, then tha sentry state becomes legit (okay).
Definizzle at line 47 of file ostream.tcc.
References std::ios_base::failbit, std::basic_ios< _CharT, _Traits >::good(), std::basic_ios< _CharT, _Traits >::setstate(), n' std::basic_ios< _CharT, _Traits >::tie().
template<typename _CharT, typename _Traits = char_traits<_CharT>> std::basic_ostream< _CharT, _Traits >::sentry::~sentry () [inline]
Possibly flushes tha stream. If ios_base::unitbuf is set up in os.flags(), n' std::uncaught_exception() is true, tha sentry destructor calls flush() on tha output stream.
Definizzle at line 428 of file ostream.
References std::ios_base::badbit, std::uncaught_exception(), n' std::ios_base::unitbuf.
Member Function Documentation
template<typename _CharT, typename _Traits = char_traits<_CharT>> std::basic_ostream< _CharT, _Traits >::sentry::operator bool () const [inline], [explicit]
Quick status checking.
Returns:
Da sentry state.
For ease of use, sentries may be converted ta booleans. Da return value is dat of tha sentry state (true == aiiight).
Definizzle at line 449 of file ostream.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.