" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::time_put< _CharT, _OutIta > -
SYNOPSIS
Inherits std::locale::facet.
Inherited by std::time_put_byname< _CharT, _OutIta >.
Public Types
typedef _CharT char_type
typedef _OutIta iter_type
Public Member Functions
time_put (size_t __refs=0)
iter_type put (iter_type __s, ios_base &__io, char_type __fill, const tm *__tm, const _CharT *__beg, const _CharT *__end) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, const tm *__tm, char __format, char __mod=0) const
Static Public Attributes
static locale::id id
Protected Member Functions
virtual ~time_put ()
virtual iter_type do_put (iter_type __s, ios_base &__io, char_type __fill, const tm *__tm, char __format, char __mod) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Detailed Description
template<typename _CharT, typename _OutIter>class std::time_put< _CharT, _OutIta >
Primary class template time_put.
This facet encapsulates tha code ta format n' output dates n' times accordin ta formats used by strftime().
Da time_put template uses protected virtual functions ta provide tha actual thangs up in dis biatch. Da hood accessors forward tha call ta tha virtual functions. These virtual functions is hooks fo' pimpers ta implement tha behavior they require from tha time_put facet.
Definizzle at line 715 of file locale_facets_nonio.h.
Member Typedef Documentation
template<typename _CharT , typename _OutIta > typedef _CharT std::time_put< _CharT, _OutIta >::char_type
Public typedefs.
Definizzle at line 721 of file locale_facets_nonio.h.
template<typename _CharT , typename _OutIta > typedef _OutIta std::time_put< _CharT, _OutIta >::iter_type
Public typedefs.
Definizzle at line 722 of file locale_facets_nonio.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _OutIta > std::time_put< _CharT, _OutIta >::time_put (size_t__refs = 0) [inline], [explicit]
Constructor performs initialization. This is tha constructor provided by tha standard.
Parameters:
__refs Passed ta tha base facet class.
Definizzle at line 736 of file locale_facets_nonio.h.
template<typename _CharT , typename _OutIta > virtual std::time_put< _CharT, _OutIta >::~time_put () [inline], [protected], [virtual]
Destructor.
Definizzle at line 782 of file locale_facets_nonio.h.
Member Function Documentation
template<typename _CharT , typename _OutIta > _OutIta std::time_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, const tm *__tm, char__format, char__mod) const [protected], [virtual]
Format n' output a time or date. This function formats tha data up in struct tm accordin ta tha provided format char n' optionizzle modifier. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
put() fo' mo' details.
Parameters:
__s Da stream ta write to.
__io Source of locale.
__fill char_type ta use fo' padding.
__tm Struct tm wit date n' time info ta format.
__format Format char.
__mod Optionizzle modifier char.
Returns:
Iterator afta writing.
Definizzle at line 1178 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), n' std::__ctype_abstract_base< _CharT >::widen().
Referenced by std::time_put< _CharT, _OutIta >::put().
template<typename _CharT , typename _OutIta > _OutIta std::time_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, const tm *__tm, const _CharT *__beg, const _CharT *__end) const
Format n' output a time or date. This function formats tha data up in struct tm accordin ta tha provided format string. Da format strang is interpreted as by strftime().
Parameters:
__s Da stream ta write to.
__io Source of locale.
__fill char_type ta use fo' padding.
__tm Struct tm wit date n' time info ta format.
__beg Start of format string.
__end End of format string.
Returns:
Iterator afta writing.
Definizzle at line 1143 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), n' std::__ctype_abstract_base< _CharT >::narrow().
template<typename _CharT , typename _OutIta > iter_type std::time_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, const tm *__tm, char__format, char__mod = 0) const [inline]
Format n' output a time or date. This function formats tha data up in struct tm accordin ta tha provided format char n' optionizzle modifier. Da format n' modifier is interpreted as by strftime(). Well shiiiit, it do so by returnin time_put::do_put().
Parameters:
__s Da stream ta write to.
__io Source of locale.
__fill char_type ta use fo' padding.
__tm Struct tm wit date n' time info ta format.
__format Format char.
__mod Optionizzle modifier char.
Returns:
Iterator afta writing.
Definizzle at line 775 of file locale_facets_nonio.h.
References std::time_put< _CharT, _OutIta >::do_put().
Member Data Documentation
template<typename _CharT , typename _OutIta > locale::id std::time_put< _CharT, _OutIta >::id [static]
Numpunct facet id.
Definizzle at line 726 of file locale_facets_nonio.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.