" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::sub_match< _BiIta > -
SYNOPSIS
Inherits std::pair< _BiIter, _BiIta >.
Public Types
typedef
__iter_traits::difference_type difference_type"
typedef _BiIta first_type
typedef _BiIta iterator
typedef _BiIta second_type
typedef std::basic_string
< value_type > string_type"
typedef __iter_traits::value_type value_type
Public Member Functions
int compare (const sub_match &__s) const
int compare (const string_type &__s) const
int compare (const value_type *__s) const
difference_type length () const
operator string_type () const
string_type str () const
void swap (pair &__p) noexcept(noexcept(swap(first, __p.first))&&noexcept(swap(second, __p.second)))
Public Attributes
_BiIta first
bool matched
_BiIta second
Detailed Description
template<typename _BiIter>class std::sub_match< _BiIta >
A sequence of charactas matched by a particular marked sub-expression.
An object of dis class is essentially a pair of iterators markin a matched subexpression within a regular expression pattern match. Right back up in yo muthafuckin ass. Such objects can be converted ta n' compared wit std::basic_strin objectz of a similar base characta type as tha pattern matched by tha regular expression.
Da iterators dat make up tha pair is tha usual half-open interval referencin tha actual original gangsta pattern matched.
Definizzle at line 741 of file regex.h.
Member Typedef Documentation
typedef _BiIta std::pair< _BiIta , _BiIta >::second_type [inherited]
first_type is tha straight-up original gangsta bound type
Definizzle at line 99 of file stl_pair.h.
Member Function Documentation
template<typename _BiIter> int std::sub_match< _BiIta >::compare (const sub_match< _BiIta > &__s) const [inline]
Compares dis n' another matched sequence.
Parameters:
__s Another matched sequence ta compare ta dis one.
Return joints:
<0 dis matched sequence will collate before __s.
=0 dis matched sequence is equivalent ta __s.
<0 dis matched sequence will collate afta __s.
Definizzle at line 802 of file regex.h.
Referenced by std::operator!=(), std::operator<(), std::operator<=(), std::operator==(), std::operator>(), n' std::operator>=().
template<typename _BiIter> int std::sub_match< _BiIta >::compare (const string_type &__s) const [inline]
Compares dis sub_match ta a string.
Parameters:
__s A strang ta compare ta dis sub_match.
Return joints:
<0 dis matched sequence will collate before __s.
=0 dis matched sequence is equivalent ta __s.
<0 dis matched sequence will collate afta __s.
Definizzle at line 815 of file regex.h.
template<typename _BiIter> int std::sub_match< _BiIta >::compare (const value_type *__s) const [inline]
Compares dis sub_match ta a C-style string.
Parameters:
__s A C-style strang ta compare ta dis sub_match.
Return joints:
<0 dis matched sequence will collate before __s.
=0 dis matched sequence is equivalent ta __s.
<0 dis matched sequence will collate afta __s.
Definizzle at line 828 of file regex.h.
template<typename _BiIter> difference_type std::sub_match< _BiIta >::length () const [inline]
Gets tha length of tha matchin sequence.
Definizzle at line 759 of file regex.h.
template<typename _BiIter> std::sub_match< _BiIta >::operator string_type () const [inline]
Gets tha matchin sequence as a string.
Returns:
the matchin sequence as a string.
This is tha implicit conversion operator. Well shiiiit, it is identical ta tha str() member function except dat it will wanna pop up in unexpected places n' cause a pimped out deal of mad drama n' cursin from tha unwary.
Definizzle at line 772 of file regex.h.
template<typename _BiIter> string_type std::sub_match< _BiIta >::str () const [inline]
Gets tha matchin sequence as a string.
Returns:
the matchin sequence as a string.
Definizzle at line 785 of file regex.h.
Referenced by std::sub_match< _Bi_ita >::compare(), n' std::operator<<().
Member Data Documentation
_BiIta std::pair< _BiIta , _BiIta >::first [inherited]
second_type is tha second bound type
Definizzle at line 101 of file stl_pair.h.
Referenced by std::sub_match< _Bi_ita >::length(), std::sub_match< _Bi_ita >::operator string_type(), n' std::sub_match< _Bi_ita >::str().
_BiIta std::pair< _BiIta , _BiIta >::second [inherited]
first be a cold-ass lil copy of tha straight-up original gangsta object
Definizzle at line 102 of file stl_pair.h.
Referenced by std::sub_match< _Bi_ita >::length(), std::sub_match< _Bi_ita >::operator string_type(), n' std::sub_match< _Bi_ita >::str().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.