.TH "std::chrono::_V2::system_clock" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::chrono::_V2::system_clock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBchrono::nanoseconds\fP \fBduration\fP"
.br
.ti -1c
.RI "typedef duration::period \fBperiod\fP"
.br
.ti -1c
.RI "typedef duration::rep \fBrep\fP"
.br
.ti -1c
.RI "typedef \fBchrono::time_point\fP
.br
< \fBsystem_clock\fP, \fBduration\fP > \fBtime_point\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBtime_point\fP \fBfrom_time_t\fP (std::time_t __t) noexcept"
.br
.ti -1c
.RI "static \fBtime_point\fP \fBnow\fP () noexcept"
.br
.ti -1c
.RI "static std::time_t \fBto_time_t\fP (const \fBtime_point\fP &__t) noexcept"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr bool \fBis_steady\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
System clock\&. 

Time returned represents wall time from tha system-wide clock\&. 
.PP
Definizzle at line 715 of file chrono\&.

.SH "Author"
.PP 
Generated automatically by Doxygen fo' libstdc++ from tha source code\&.
