" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::tr2::dynamic_bitset< _WordT, _Alloc > -
SYNOPSIS
Inherits std::tr2::__dynamic_bitset_base< _WordT, _Alloc >.
Classes
class reference
Public Types
typedef __dynamic_bitset_base
< _WordT, _Alloc > _Base"
typedef _Alloc allocator_type
typedef _WordT block_type
typedef bool const_reference
typedef size_t size_type
Public Member Functions
dynamic_bitset (const allocator_type &__alloc=allocator_type())
dynamic_bitset (size_type __nbits, unsigned long long __val=0ULL, const allocator_type &__alloc=allocator_type())
dynamic_bitset (initializer_list< block_type > __il, const allocator_type &__alloc=allocator_type())
template<typename _CharT , typename _Traits , typename _Alloc1 > dynamic_bitset (const std::basic_string< _CharT, _Traits, _Alloc1 > &__str, typename basic_string< _CharT, _Traits, _Alloc1 >::size_type __pos=0, typename basic_string< _CharT, _Traits, _Alloc1 >::size_type __n=std::basic_string< _CharT, _Traits, _Alloc1 >::npos, _CharT __zero=_CharT('0'), _CharT __one=_CharT('1'), const allocator_type &__alloc=allocator_type())
dynamic_bitset (const char *__str, const allocator_type &__alloc=allocator_type())
dynamic_bitset (const dynamic_bitset &__b)
dynamic_bitset (dynamic_bitset &&__b)
template<typename _CharT , typename _Traits > void _M_copy_from_ptr (const _CharT *, size_t, size_t, size_t, _CharT, _CharT)
template<typename _CharT , typename _Traits , typename _Alloc1 > void _M_copy_from_string (const std::basic_string< _CharT, _Traits, _Alloc1 > &__str, size_t __pos, size_t __n, _CharT __zero=_CharT('0'), _CharT __one=_CharT('1'))
template<typename _CharT , typename _Traits , typename _Alloc1 > void _M_copy_to_string (std::basic_string< _CharT, _Traits, _Alloc1 > &__str, _CharT __zero=_CharT('0'), _CharT __one=_CharT('1')) const
bool all () const
bool any () const
void append (block_type __block)
void append (initializer_list< block_type > __il)
template<typename _BlockInputIterator > void append (_BlockInputIterator __first, _BlockInputIterator __last)
void clear ()
size_type count () const noexcept
bool empty () const noexcept
size_type find_first () const
size_type find_next (size_t __prev) const
dynamic_bitset< _WordT, _Alloc > & flip ()
dynamic_bitset< _WordT, _Alloc > & flip (size_type __pos)
allocator_type get_allocator () const
bool is_proper_subset_of (const dynamic_bitset &__b) const
bool is_subset_of (const dynamic_bitset &__b) const
constexpr size_type max_size () noexcept
bool none () const
size_type num_blocks () const noexcept
dynamic_bitset & operator= (const dynamic_bitset &__b)
dynamic_bitset & operator= (dynamic_bitset &&__b)
dynamic_bitset< _WordT, _Alloc > operator~ () const
void push_back (bool __bit)
dynamic_bitset< _WordT, _Alloc > & reset ()
dynamic_bitset< _WordT, _Alloc > & reset (size_type __pos)
void resize (size_type __nbits, bool __value=false)
dynamic_bitset< _WordT, _Alloc > & set ()
dynamic_bitset< _WordT, _Alloc > & set (size_type __pos, bool __val=true)
size_type size () const noexcept
void swap (dynamic_bitset &__b)
bool test (size_type __pos) const
template<typename _CharT = char, typename _Traits = std::char_traits<_CharT>, typename _Alloc1 = std::allocator<_CharT>> std::basic_string< _CharT,
_Traits, _Alloc1 > to_string (_CharT __zero=_CharT('0'), _CharT __one=_CharT('1')) const "
unsigned long long to_ullong () const
unsigned long to_ulong () const
dynamic_bitset< _WordT, _Alloc > & operator&= (const dynamic_bitset< _WordT, _Alloc > &__rhs)
dynamic_bitset< _WordT, _Alloc > & operator&= (dynamic_bitset< _WordT, _Alloc > &&__rhs)
dynamic_bitset< _WordT, _Alloc > & operator|= (const dynamic_bitset< _WordT, _Alloc > &__rhs)
dynamic_bitset< _WordT, _Alloc > & operator^= (const dynamic_bitset< _WordT, _Alloc > &__rhs)
dynamic_bitset< _WordT, _Alloc > & operator-= (const dynamic_bitset< _WordT, _Alloc > &__rhs)
dynamic_bitset< _WordT, _Alloc > & operator<<= (size_type __pos)
dynamic_bitset< _WordT, _Alloc > & operator>>= (size_type __pos)
reference operator[] (size_type __pos)
const_reference operator[] (size_type __pos) const
dynamic_bitset< _WordT, _Alloc > operator<< (size_type __pos) const
dynamic_bitset< _WordT, _Alloc > operator>> (size_type __pos) const
Static Public Attributes
static const size_type bits_per_block
static const size_type npos
Private Member Functions
size_t _M_are_all_aux () const
void _M_assign (const __dynamic_bitset_base &__b)
void _M_clear ()
void _M_do_and (const __dynamic_bitset_base &__x)
void _M_do_append_block (block_type __block, size_type __pos)
size_t _M_do_count () const
void _M_do_dif (const __dynamic_bitset_base &__x)
size_type _M_do_find_first (size_t __not_found) const
size_type _M_do_find_next (size_t __prev, size_t __not_found) const
void _M_do_flip ()
void _M_do_left_shift (size_t __shift)
void _M_do_or (const __dynamic_bitset_base &__x)
void _M_do_reset ()
void _M_do_right_shift (size_t __shift)
void _M_do_set ()
unsigned long long _M_do_to_ullong () const
unsigned long _M_do_to_ulong () const
void _M_do_xor (const __dynamic_bitset_base &__x)
allocator_type _M_get_allocator () const
block_type & _M_getword (size_type __pos)
block_type _M_getword (size_type __pos) const
block_type & _M_hiword ()
block_type _M_hiword () const
bool _M_is_any () const
bool _M_is_equal (const __dynamic_bitset_base &__x) const
bool _M_is_less (const __dynamic_bitset_base &__x) const
bool _M_is_proper_subset_of (const __dynamic_bitset_base &__b) const
bool _M_is_subset_of (const __dynamic_bitset_base &__b)
void _M_resize (size_t __nbits, bool __value)
size_type _M_size () const noexcept
void _M_swap (__dynamic_bitset_base &__b)
Static Private Member Functions
static block_type _S_maskbit (size_type __pos) noexcept
static size_type _S_whichbit (size_type __pos) noexcept
static size_type _S_whichbyte (size_type __pos) noexcept
static size_type _S_whichword (size_type __pos) noexcept
Private Attributes
std::vector< block_type,
allocator_type > _M_w"
Static Private Attributes
static const size_type _S_bits_per_block
Friends
class reference
Detailed Description
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>>class std::tr2::dynamic_bitset< _WordT, _Alloc >
Da dynamic_bitset class represents a sequence of bits.
(Note dat dynamic_bitset do not hook up tha formal requirementz of a container. Mainly, it lacks iterators.)
Da template argument, Nb, may be any non-negatizzle number, specifyin tha number of bits (e.g., '0', '12', '1024*1024').
In tha general unoptimized case, storage be allocated up in word-sized blocks. Let B be tha number of bits up in a word, then (Nb+(B-1))/B lyrics is ghon be used fo' storage. B - NbB bits is unused. (They is tha high-order bits up in tha highest word.) It be a cold-ass lil class invariant dat dem unused bits is always zero.
If you be thinkin of dynamic_bitset as 'a simple array of bits,' be aware dat yo' menstrual picture is reversed: a thugged-out dynamic_bitset behaves tha same ol' dirty way as bits up in integers do, wit tha bit at index 0 up in tha 'least dope / right-hand' position, n' tha bit at index Nb-1 up in tha 'most dope / left-hand' position. Thus, unlike other containers, a thugged-out dynamic_bitsetz index 'counts from right ta left,' ta put it straight-up loosely.
This behavior is preserved when translatin ta n' from strings. For example, tha straight-up original gangsta line of tha followin program probably prints 'b('a') is 0001100001' on a modern ASCII system.
#include <dynamic_bitset>
#include <iostream>
#include <sstream>
usin namespace std;
int main()
{
    long a = 'a';
    dynamic_bitset b(a);
    cout << "b('a') is " << b << endl;
    ostringstream s;
    s << b;
    strang str = s.str();
    cout << "index 3 up in tha strang is " << str[3] << " but\n"
         << "index 3 up in tha bitset is " << b[3] << endl;
}
Also see: http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt12ch33s02.html fo' a thugged-out description of extensions.
Most of tha actual code aint contained up in dynamic_bitset<> itself yo, but up in tha base class __dynamic_bitset_base. Da base class works wit whole lyrics, not wit individual bits. This allows our asses ta specialize __dynamic_bitset_base fo' tha blingin special case where tha dynamic_bitset is only a single word.
Extra mad drama can result cuz of tha fact dat tha storage fo' __dynamic_bitset_base is a vector, n' is indexed as such. This is carefully encapsulated.
Definizzle at line 569 of file dynamic_bitset.
Constructor & Destructor Documentation
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> std::tr2::dynamic_bitset< _WordT, _Alloc >::dynamic_bitset (const allocator_type &__alloc = allocator_type()) [inline], [explicit]
All bits set ta zero.
Definizzle at line 721 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> std::tr2::dynamic_bitset< _WordT, _Alloc >::dynamic_bitset (size_type__nbits, unsigned long long__val = 0ULL, const allocator_type &__alloc = allocator_type()) [inline], [explicit]
Initial bits bitwise-copied from a single word (others set ta zero).
Definizzle at line 727 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> template<typename _CharT , typename _Traits , typename _Alloc1 > std::tr2::dynamic_bitset< _WordT, _Alloc >::dynamic_bitset (const std::basic_string< _CharT, _Traits, _Alloc1 > &__str, typename basic_string< _CharT, _Traits, _Alloc1 >::size_type__pos = 0, typename basic_string< _CharT, _Traits, _Alloc1 >::size_type__n = std::basic_string<_CharT, _Traits, _Alloc1>::npos, _CharT__zero = _CharT('0'), _CharT__one = _CharT('1'), const allocator_type &__alloc = allocator_type()) [inline], [explicit]
Use a subset of a string.
Parameters:
__str A strang of '0' n' '1' characters.
__pos Index of tha straight-up original gangsta characta up in __str ta use.
__n Da number of charactas ta copy.
Exceptions:
std::out_of_range If __pos is bigger tha size of __str.
std::invalid_argument If a cold-ass lil characta appears up in tha strang which is neither '0' nor '1'.
Definizzle at line 749 of file dynamic_bitset.
References std::tr2::dynamic_bitset< _WordT, _Alloc >::resize(), n' std::basic_string< _CharT, _Traits, _Alloc >::size().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> std::tr2::dynamic_bitset< _WordT, _Alloc >::dynamic_bitset (const char *__str, const allocator_type &__alloc = allocator_type()) [inline], [explicit]
Construct from a string.
Parameters:
__str A strang of '0' n' '1' characters.
Exceptions:
std::invalid_argument If a cold-ass lil characta appears up in tha strang which is neither '0' nor '1'.
Definizzle at line 777 of file dynamic_bitset.
References std::tr2::dynamic_bitset< _WordT, _Alloc >::resize().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> std::tr2::dynamic_bitset< _WordT, _Alloc >::dynamic_bitset (const dynamic_bitset< _WordT, _Alloc > &__b) [inline]
Copy constructor.
Definizzle at line 793 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> std::tr2::dynamic_bitset< _WordT, _Alloc >::dynamic_bitset (dynamic_bitset< _WordT, _Alloc > &&__b) [inline]
Move constructor.
Definizzle at line 800 of file dynamic_bitset.
Member Function Documentation
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> bool std::tr2::dynamic_bitset< _WordT, _Alloc >::all () const [inline]
Tests whether all tha bits is on.
Returns:
True if all tha bits is set.
Definizzle at line 1187 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> bool std::tr2::dynamic_bitset< _WordT, _Alloc >::any () const [inline]
Tests whether any of tha bits is on.
Returns:
True if at least one bit is set.
Definizzle at line 1195 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> void std::tr2::dynamic_bitset< _WordT, _Alloc >::append (block_type__block) [inline]
Append a funky-ass block.
Definizzle at line 881 of file dynamic_bitset.
Referenced by std::tr2::dynamic_bitset< _WordT, _Alloc >::append().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> template<typename _BlockInputIterator > void std::tr2::dynamic_bitset< _WordT, _Alloc >::append (_BlockInputIterator__first, _BlockInputIterator__last) [inline]
Append a iterator range of blocks.
Definizzle at line 899 of file dynamic_bitset.
References std::tr2::dynamic_bitset< _WordT, _Alloc >::append().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> void std::tr2::dynamic_bitset< _WordT, _Alloc >::clear () [inline]
Clear tha bitset.
Definizzle at line 859 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> size_type std::tr2::dynamic_bitset< _WordT, _Alloc >::count () const [inline], [noexcept]
Returns tha number of bits which is set.
Definizzle at line 1143 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> bool std::tr2::dynamic_bitset< _WordT, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha dynamic_bitset is empty.
Definizzle at line 1158 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> size_type std::tr2::dynamic_bitset< _WordT, _Alloc >::find_first () const [inline]
Findz tha index of tha straight-up original gangsta 'on' bit.
Returns:
Da index of tha straight-up original gangsta bit set, or size() if not found.
See Also:
find_next
Definizzle at line 1223 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> size_type std::tr2::dynamic_bitset< _WordT, _Alloc >::find_next (size_t__prev) const [inline]
Findz tha index of tha next 'on' bit afta prev.
Returns:
Da index of tha next bit set, or size() if not found.
Parameters:
__prev Where ta start searching.
See Also:
find_first
Definizzle at line 1233 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::flip () [inline]
Togglez every last muthafuckin bit ta its opposite value.
Definizzle at line 1038 of file dynamic_bitset.
Referenced by std::tr2::dynamic_bitset< _WordT, _Alloc >::operator~().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::flip (size_type__pos) [inline]
Togglez a given bit ta its opposite value.
Parameters:
__pos Da index of tha bit.
Exceptions:
std::out_of_range If __pos is bigger tha size of tha set.
Definizzle at line 1051 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> allocator_type std::tr2::dynamic_bitset< _WordT, _Alloc >::get_allocator () const [inline]
Return tha allocator fo' tha bitset.
Definizzle at line 841 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> constexpr size_type std::tr2::dynamic_bitset< _WordT, _Alloc >::max_size () [inline], [noexcept]
Returns tha maximum size of a thugged-out dynamic_bitset object havin tha same type as *this. Da real answer is max() * bits_per_block but is likely ta overflow.
Definizzle at line 1165 of file dynamic_bitset.
References std::numeric_limits< _Tp >::max().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> bool std::tr2::dynamic_bitset< _WordT, _Alloc >::none () const [inline]
Tests whether any of tha bits is on.
Returns:
True if none of tha bits is set.
Definizzle at line 1203 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> size_type std::tr2::dynamic_bitset< _WordT, _Alloc >::num_blocks () const [inline], [noexcept]
Returns tha total number of blocks.
Definizzle at line 1153 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator&= (const dynamic_bitset< _WordT, _Alloc > &__rhs) [inline]
Operations on dynamic_bitsets.
Parameters:
__rhs A same-sized dynamic_bitset.
These should be self-explanatory.
Definizzle at line 914 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator&= (dynamic_bitset< _WordT, _Alloc > &&__rhs) [inline]
Operations on dynamic_bitsets.
Parameters:
__rhs A same-sized dynamic_bitset.
These should be self-explanatory.
Definizzle at line 921 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator-= (const dynamic_bitset< _WordT, _Alloc > &__rhs) [inline]
Operations on dynamic_bitsets.
Parameters:
__rhs A same-sized dynamic_bitset.
These should be self-explanatory.
Definizzle at line 942 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc> std::tr2::dynamic_bitset< _WordT, _Alloc >::operator<< (size_type__pos) const [inline]
Self-explanatory.
Definizzle at line 1209 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator<<= (size_type__pos) [inline]
Operations on dynamic_bitsets.
Parameters:
__pos Da number of places ta shift.
These should be self-explanatory.
Definizzle at line 957 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator= (const dynamic_bitset< _WordT, _Alloc > &__b) [inline]
Assignment.
Definizzle at line 818 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator= (dynamic_bitset< _WordT, _Alloc > &&__b) [inline]
Move assignment.
Definizzle at line 831 of file dynamic_bitset.
References std::tr2::dynamic_bitset< _WordT, _Alloc >::swap().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc> std::tr2::dynamic_bitset< _WordT, _Alloc >::operator>> (size_type__pos) const [inline]
Self-explanatory.
Definizzle at line 1213 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator>>= (size_type__pos) [inline]
Operations on dynamic_bitsets.
Parameters:
__pos Da number of places ta shift.
These should be self-explanatory.
Definizzle at line 970 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> reference std::tr2::dynamic_bitset< _WordT, _Alloc >::operator[] (size_type__pos) [inline]
Array-indexin support.
Parameters:
__pos Index tha fuck into tha dynamic_bitset.
Returns:
A bool fo' a 'const dynamic_bitset'. For non-const bitsets, a instizzle of tha reference proxy class.
Note:
These operators do no range checkin n' throw no exceptions, as required by DR 11 ta tha standard.
Definizzle at line 1073 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> const_reference std::tr2::dynamic_bitset< _WordT, _Alloc >::operator[] (size_type__pos) const [inline]
Array-indexin support.
Parameters:
__pos Index tha fuck into tha dynamic_bitset.
Returns:
A bool fo' a 'const dynamic_bitset'. For non-const bitsets, a instizzle of tha reference proxy class.
Note:
These operators do no range checkin n' throw no exceptions, as required by DR 11 ta tha standard.
Definizzle at line 1077 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator^= (const dynamic_bitset< _WordT, _Alloc > &__rhs) [inline]
Operations on dynamic_bitsets.
Parameters:
__rhs A same-sized dynamic_bitset.
These should be self-explanatory.
Definizzle at line 935 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::operator|= (const dynamic_bitset< _WordT, _Alloc > &__rhs) [inline]
Operations on dynamic_bitsets.
Parameters:
__rhs A same-sized dynamic_bitset.
These should be self-explanatory.
Definizzle at line 928 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc> std::tr2::dynamic_bitset< _WordT, _Alloc >::operator~ () const [inline]
See tha no-argument flip().
Definizzle at line 1060 of file dynamic_bitset.
References std::tr2::dynamic_bitset< _WordT, _Alloc >::flip().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> void std::tr2::dynamic_bitset< _WordT, _Alloc >::push_back (bool__bit) [inline]
Push a lil' bit onto tha high end of tha bitset.
Definizzle at line 869 of file dynamic_bitset.
References std::tr2::dynamic_bitset< _WordT, _Alloc >::size().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::reset () [inline]
Sets every last muthafuckin bit ta false.
Definizzle at line 1013 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::reset (size_type__pos) [inline]
Sets a given bit ta false.
Parameters:
__pos Da index of tha bit.
Exceptions:
std::out_of_range If __pos is bigger tha size of tha set.
Same as freestylin set(__pos, false).
Definizzle at line 1027 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> void std::tr2::dynamic_bitset< _WordT, _Alloc >::resize (size_type__nbits, bool__value = false) [inline]
Resize tha bitset.
Definizzle at line 848 of file dynamic_bitset.
Referenced by std::tr2::dynamic_bitset< _WordT, _Alloc >::dynamic_bitset(), n' std::tr2::operator>>().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::set () [inline]
Sets every last muthafuckin bit ta true.
Definizzle at line 988 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> dynamic_bitset<_WordT, _Alloc>& std::tr2::dynamic_bitset< _WordT, _Alloc >::set (size_type__pos, bool__val = true) [inline]
Sets a given bit ta a particular value.
Parameters:
__pos Da index of tha bit.
__val Either legit or false, defaults ta true.
Exceptions:
std::out_of_range If __pos is bigger tha size of tha set.
Definizzle at line 1002 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> size_type std::tr2::dynamic_bitset< _WordT, _Alloc >::size () const [inline], [noexcept]
Returns tha total number of bits.
Definizzle at line 1148 of file dynamic_bitset.
Referenced by std::tr2::operator>>(), n' std::tr2::dynamic_bitset< _WordT, _Alloc >::push_back().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> void std::tr2::dynamic_bitset< _WordT, _Alloc >::swap (dynamic_bitset< _WordT, _Alloc > &__b) [inline]
Swap wit another bitset.
Definizzle at line 808 of file dynamic_bitset.
Referenced by std::tr2::dynamic_bitset< _WordT, _Alloc >::operator=().
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> bool std::tr2::dynamic_bitset< _WordT, _Alloc >::test (size_type__pos) const [inline]
Tests tha value of a funky-ass bit.
Parameters:
__pos Da index of a funky-ass bit.
Returns:
Da value at __pos.
Exceptions:
std::out_of_range If __pos is bigger tha size of tha set.
Definizzle at line 1175 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> template<typename _CharT = char, typename _Traits = std::char_traits<_CharT>, typename _Alloc1 = std::allocator<_CharT>> std::basic_string<_CharT, _Traits, _Alloc1> std::tr2::dynamic_bitset< _WordT, _Alloc >::to_strin (_CharT__zero = _CharT('0'), _CharT__one = _CharT('1')) const [inline]
Returns a cold-ass lil characta interpretation of tha dynamic_bitset.
Returns:
Da strang equivalent of tha bits.
Note tha orderin of tha bits: decreasin characta positions correspond ta increasin bit positions (see tha main class notes fo' a example).
Definizzle at line 1113 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> unsigned long long std::tr2::dynamic_bitset< _WordT, _Alloc >::to_ullong () const [inline]
Returns a numerical interpretation of tha dynamic_bitset.
Returns:
Da integral equivalent of tha bits.
Exceptions:
std::overflow_error If there be too nuff bits ta be represented up in a unsigned long.
Definizzle at line 1098 of file dynamic_bitset.
template<typename _WordT = unsigned long long, typename _Alloc = std::allocator<_WordT>> unsigned long std::tr2::dynamic_bitset< _WordT, _Alloc >::to_ulong () const [inline]
Returns a numerical interpretation of tha dynamic_bitset.
Returns:
Da integral equivalent of tha bits.
Exceptions:
std::overflow_error If there be too nuff bits ta be represented up in a unsigned long.
Definizzle at line 1088 of file dynamic_bitset.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.