std::__detail::_Nfa
NAME
std::__detail::_Nfa -
SYNOPSIS
Inherits std::__detail::_Automaton, n' std::vector< _State >.
Public Types
typedef
regex_constants::syntax_option_type _FlagT"
typedef unsigned int _SizeT
typedef _State _StateT
typedef std::allocator< _State > allocator_type
typedef
__gnu_cxx::__normal_iterator
< const_pointer, vector > const_iterator"
typedef
_Alloc_traits::const_pointa const_pointer"
typedef
_Alloc_traits::const_reference const_reference"
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator"
typedef ptrdiff_t difference_type
typedef
__gnu_cxx::__normal_iterator
< pointer, vector > iterator"
typedef _Base::pointa pointer
typedef _Alloc_traits::reference reference
typedef std::reverse_iterator
< iterator > reverse_iterator"
typedef size_t size_type
typedef _State value_type
Public Member Functions
_Nfa (_FlagT __f)
const _StateSet & _M_final_states () const
_StateIdT _M_insert_accept ()
_StateIdT _M_insert_alt (_StateIdT __next, _StateIdT __alt)
_StateIdT _M_insert_matcher (_Matcher __m)
_StateIdT _M_insert_subexpr_begin (const _Tagger &__t)
_StateIdT _M_insert_subexpr_end (unsigned int __i, const _Tagger &__t)
_FlagT _M_options () const
_StateIdT _M_start () const
_SizeT _M_sub_count () const
void assign (size_type __n, const value_type &__val)
void assign (_InputIterator __first, _InputIterator __last)
void assign (initializer_list< value_type > __l)
reference at (size_type __n)
const_reference at (size_type __n) const
reference back ()
const_reference back () const
iterator begin () noexcept
const_iterator begin () const noexcept
size_type capacity () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
_State * data () noexcept
const _State * data () const noexcept
iterator emplace (iterator __position, _Args &&...__args)
void emplace_back (_Args &&...__args)
bool empty () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
reference front ()
const_reference front () const
iterator insert (iterator __position, const value_type &__x)
iterator insert (iterator __position, value_type &&__x)
void insert (iterator __position, initializer_list< value_type > __l)
void insert (iterator __position, size_type __n, const value_type &__x)
void insert (iterator __position, _InputIterator __first, _InputIterator __last)
size_type max_size () const noexcept
reference operator[] (size_type __n)
const_reference operator[] (size_type __n) const
void pop_back ()
void push_back (const value_type &__x)
void push_back (value_type &&__x)
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
void reserve (size_type __n)
void resize (size_type __new_size)
void resize (size_type __new_size, const value_type &__x)
void shrink_to_fit ()
size_type size () const noexcept
void swap (vector &__x) noexcept(_Alloc_traits::_S_nothrow_swap())
Protected Member Functions
pointa _M_allocate (size_t __n)
pointa _M_allocate_and_copy (size_type __n, _ForwardIterator __first, _ForwardIterator __last)
void _M_assign_aux (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
void _M_assign_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
void _M_assign_dispatch (_Integer __n, _Integer __val, __true_type)
void _M_assign_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
size_type _M_check_len (size_type __n, const char *__s) const
void _M_deallocate (pointa __p, size_t __n)
void _M_default_append (size_type __n)
void _M_default_initialize (size_type __n)
void _M_emplace_back_aux (_Args &&...__args)
void _M_erase_at_end (pointa __pos)
void _M_fill_assign (size_type __n, const value_type &__val)
void _M_fill_initialize (size_type __n, const value_type &__value)
void _M_fill_insert (iterator __pos, size_type __n, const value_type &__x)
_Tp_alloc_type & _M_get_Tp_allocator () noexcept
const _Tp_alloc_type & _M_get_Tp_allocator () const noexcept
void _M_initialize_dispatch (_Integer __n, _Integer __value, __true_type)
void _M_initialize_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
void _M_insert_aux (iterator __position, _Args &&...__args)
void _M_insert_dispatch (iterator __pos, _Integer __n, _Integer __val, __true_type)
void _M_insert_dispatch (iterator __pos, _InputIterator __first, _InputIterator __last, __false_type)
void _M_range_check (size_type __n) const
void _M_range_initialize (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
void _M_range_initialize (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
void _M_range_insert (iterator __pos, _InputIterator __first, _InputIterator __last, std::input_iterator_tag)
void _M_range_insert (iterator __pos, _ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
bool _M_shrink_to_fit ()
allocator_type get_allocator () const noexcept
Protected Attributes
_Vector_impl _M_impl
Detailed Description
struct _Nfa
A collection of all states makin up a NFA.
An NFA be a 4-tuple M = (K, S, s, F), where K be a gangbangin' finite set of states, S is tha alphabet of tha NFA, s is tha initial state, F be a set of final (accepting) states.
This NFA class is templated on S, a type dat will hold jointz of tha underlyin alphabet (without regard ta semantics of dat alphabet). Da other elementz of tha tuple is generated durin construction of tha NFA n' is available all up in accessor member functions.
Definizzle at line 269 of file regex_nfa.h.
Member Function Documentation
pointa std::vector< _State , std::allocator<_State > >::_M_allocate_and_copy (size_type__n, _ForwardIterator__first, _ForwardIterator__last) [inline], [protected], [inherited]
Memory expansion handlez. Uses tha member allocation function ta obtain n bytez of memory, n' then copies [first,last) tha fuck into it.
Definizzle at line 1135 of file stl_vector.h.
void std::vector< _State , std::allocator<_State > >::_M_range_check (size_type__n) const [inline], [protected], [inherited]
Safety check used only from at().
Definizzle at line 791 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::size().
void std::vector< _State , std::allocator<_State > >::assign (size_type__n, const value_type &__val) [inline], [inherited]
Assigns a given value ta a vector.
Parameters:
__n Number of elements ta be assigned.
__val Value ta be assigned.
This function fills a vector wit __n copiez of tha given value. Note dat tha assignment straight-up chizzlez tha vector n' dat tha resultin vectorz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 479 of file stl_vector.h.
void std::vector< _State , std::allocator<_State > >::assign (_InputIterator__first, _InputIterator__last) [inline], [inherited]
Assigns a range ta a vector.
Parameters:
__first An input iterator.
__last An input iterator.
This function fills a vector wit copiez of tha elements up in tha range [__first,__last).
Note dat tha assignment straight-up chizzlez tha vector n' dat tha resultin vectorz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 498 of file stl_vector.h.
void std::vector< _State , std::allocator<_State > >::assign (initializer_list< value_type >__l) [inline], [inherited]
Assigns a initializer list ta a vector.
Parameters:
__l An initializer_list.
This function fills a vector wit copiez of tha elements up in tha initializer list __l.
Note dat tha assignment straight-up chizzlez tha vector n' dat tha resultin vectorz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 524 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::assign().
reference std::vector< _State , std::allocator<_State > >::at (size_type__n) [inline], [inherited]
Provides access ta tha data contained up in tha vector.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read/write reference ta data.
Exceptions:
std::out_of_range If __n be a invalid index.
This function serves up fo' less thuggy data access. Da parameta is first checked dat it is up in tha range of tha vector. Da function throws out_of_range if tha check fails.
Definizzle at line 810 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::_M_range_check().
const_reference std::vector< _State , std::allocator<_State > >::at (size_type__n) const [inline], [inherited]
Provides access ta tha data contained up in tha vector.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read-only (constant) reference ta data.
Exceptions:
std::out_of_range If __n be a invalid index.
This function serves up fo' less thuggy data access. Da parameta is first checked dat it is up in tha range of tha vector. Da function throws out_of_range if tha check fails.
Definizzle at line 828 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::_M_range_check().
reference std::vector< _State , std::allocator<_State > >::back () [inline], [inherited]
Returns a read/write reference ta tha data all up in tha last element of tha vector.
Definizzle at line 855 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::end().
const_reference std::vector< _State , std::allocator<_State > >::back () const [inline], [inherited]
Returns a read-only (constant) reference ta tha data all up in tha last element of tha vector.
Definizzle at line 863 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::end().
iterator std::vector< _State , std::allocator<_State > >::begin () [inline], [noexcept], [inherited]
Returns a read/write iterator dat points ta tha straight-up original gangsta element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 538 of file stl_vector.h.
const_iterator std::vector< _State , std::allocator<_State > >::begin () const [inline], [noexcept], [inherited]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 547 of file stl_vector.h.
size_type std::vector< _State , std::allocator<_State > >::capacitizzle () const [inline], [noexcept], [inherited]
Returns tha total number of elements dat tha vector can hold before needin ta allocate mo' memory.
Definizzle at line 725 of file stl_vector.h.
const_iterator std::vector< _State , std::allocator<_State > >::cbegin () const [inline], [noexcept], [inherited]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 611 of file stl_vector.h.
const_iterator std::vector< _State , std::allocator<_State > >::cend () const [inline], [noexcept], [inherited]
Returns a read-only (constant) iterator dat points one past tha last element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 620 of file stl_vector.h.
void std::vector< _State , std::allocator<_State > >::clear () [inline], [noexcept], [inherited]
Erases all tha elements. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 1125 of file stl_vector.h.
const_reverse_iterator std::vector< _State , std::allocator<_State > >::crbegin () const [inline], [noexcept], [inherited]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 629 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::end().
const_reverse_iterator std::vector< _State , std::allocator<_State > >::crend () const [inline], [noexcept], [inherited]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 638 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin().
_State * std::vector< _State , std::allocator<_State > >::data () [inline], [noexcept], [inherited]
Returns a pointa such dat [data(), data() + size()) be a valid range. For a non-empty vector, data() == &front().
Definizzle at line 878 of file stl_vector.h.
References std::__addressof(), n' std::vector< _Tp, _Alloc >::front().
iterator std::vector< _State , std::allocator<_State > >::emplace (iterator__position, _Args &&...__args) [inherited]
Inserts a object up in vector before specified iterator.
Parameters:
__position An iterator tha fuck into tha vector.
__args Arguments.
Returns:
An iterator dat points ta tha banged data.
This function will bang a object of type T constructed wit T(std::forward<Args>(args)...) before tha specified location. Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
bool std::vector< _State , std::allocator<_State > >::empty () const [inline], [noexcept], [inherited]
Returns legit if tha vector is empty. (Thus begin() would equal end().)
Definizzle at line 734 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin(), n' std::vector< _Tp, _Alloc >::end().
iterator std::vector< _State , std::allocator<_State > >::end () [inline], [noexcept], [inherited]
Returns a read/write iterator dat points one past tha last element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 556 of file stl_vector.h.
const_iterator std::vector< _State , std::allocator<_State > >::end () const [inline], [noexcept], [inherited]
Returns a read-only (constant) iterator dat points one past tha last element up in tha vector. Iteration is done up in ordinary element order.
Definizzle at line 565 of file stl_vector.h.
iterator std::vector< _State , std::allocator<_State > >::erase (iterator__position) [inherited]
Remove element at given position.
Parameters:
__position Iterator pointin ta element ta be erased.
Returns:
An iterator pointin ta tha next element (or end()).
This function will erase tha element all up in tha given posizzle n' thus shorten tha vector by one.
Note This operation could be high-rollin' n' if it is frequently used tha user should consider rockin std::list. Da user be also cautioned dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
iterator std::vector< _State , std::allocator<_State > >::erase (iterator__first, iterator__last) [inherited]
Remove a range of elements.
Parameters:
__first Iterator pointin ta tha straight-up original gangsta element ta be erased.
__last Iterator pointin ta one past tha last element ta be erased.
Returns:
An iterator pointin ta tha element pointed ta by __last prior ta erasin (or end()).
This function will erase tha elements up in tha range [__first,__last) n' shorten tha vector accordingly.
Note This operation could be high-rollin' n' if it is frequently used tha user should consider rockin std::list. Da user be also cautioned dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
reference std::vector< _State , std::allocator<_State > >::front () [inline], [inherited]
Returns a read/write reference ta tha data all up in tha straight-up original gangsta element of tha vector.
Definizzle at line 839 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin().
const_reference std::vector< _State , std::allocator<_State > >::front () const [inline], [inherited]
Returns a read-only (constant) reference ta tha data all up in tha straight-up original gangsta element of tha vector.
Definizzle at line 847 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin().
iterator std::vector< _State , std::allocator<_State > >::insert (iterator__position, const value_type &__x) [inherited]
Inserts given value tha fuck into vector before specified iterator.
Parameters:
__position An iterator tha fuck into tha vector.
__x Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given value before tha specified location. Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
iterator std::vector< _State , std::allocator<_State > >::insert (iterator__position, value_type &&__x) [inline], [inherited]
Inserts given rvalue tha fuck into vector before specified iterator.
Parameters:
__position An iterator tha fuck into tha vector.
__x Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given rvalue before tha specified location. Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 988 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::emplace().
void std::vector< _State , std::allocator<_State > >::insert (iterator__position, initializer_list< value_type >__l) [inline], [inherited]
Inserts a initializer_list tha fuck into tha vector.
Parameters:
__position An iterator tha fuck into tha vector.
__l An initializer_list.
This function will bang copiez of tha data up in tha initializer_list l tha fuck into tha vector before tha location specified by position.
Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 1005 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::insert().
void std::vector< _State , std::allocator<_State > >::insert (iterator__position, size_type__n, const value_type &__x) [inline], [inherited]
Inserts a fuckin shitload of copiez of given data tha fuck into tha vector.
Parameters:
__position An iterator tha fuck into tha vector.
__n Number of elements ta be inserted.
__x Data ta be inserted.
This function will bang a specified number of copiez of tha given data before tha location specified by position.
Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 1023 of file stl_vector.h.
void std::vector< _State , std::allocator<_State > >::insert (iterator__position, _InputIterator__first, _InputIterator__last) [inline], [inherited]
Inserts a range tha fuck into tha vector.
Parameters:
__position An iterator tha fuck into tha vector.
__first An input iterator.
__last An input iterator.
This function will bang copiez of tha data up in tha range [__first,__last) tha fuck into tha vector before tha location specified by pos.
Note dat dis kind of operation could be high-rollin' fo' a vector n' if it is frequently used tha user should consider rockin std::list.
Definizzle at line 1044 of file stl_vector.h.
size_type std::vector< _State , std::allocator<_State > >::max_size () const [inline], [noexcept], [inherited]
Returns tha size() of tha phattest possible vector.
Definizzle at line 650 of file stl_vector.h.
References std::allocator_traits< _Tp_alloc_type >::max_size().
reference std::vector< _State , std::allocator<_State > >::operator[] (size_type__n) [inline], [inherited]
Subscript access ta tha data contained up in tha vector.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read/write reference ta data.
This operator allows fo' easy as fuck , array-style, data access. Note dat data access wit dis operator is unchecked n' out_of_range lookups is not defined. (For checked lookups peep at().)
Definizzle at line 770 of file stl_vector.h.
const_reference std::vector< _State , std::allocator<_State > >::operator[] (size_type__n) const [inline], [inherited]
Subscript access ta tha data contained up in tha vector.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read-only (constant) reference ta data.
This operator allows fo' easy as fuck , array-style, data access. Note dat data access wit dis operator is unchecked n' out_of_range lookups is not defined. (For checked lookups peep at().)
Definizzle at line 785 of file stl_vector.h.
void std::vector< _State , std::allocator<_State > >::pop_back () [inline], [inherited]
Removes last element. This be a typical stack operation. Well shiiiit, it shrinks tha vector by one.
Note dat no data is returned, n' if tha last elementz data is needed, it should be retrieved before pop_back() is called.
Definizzle at line 937 of file stl_vector.h.
void std::vector< _State , std::allocator<_State > >::push_back (const value_type &__x) [inline], [inherited]
Add data ta tha end of tha vector.
Parameters:
__x Data ta be added.
This be a typical stack operation. Da function creates a element all up in tha end of tha vector n' assigns tha given data ta it. Cuz of tha nature of a vector dis operation can be done up in constant time if tha vector has preallocated space available.
Definizzle at line 901 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::end().
reverse_iterator std::vector< _State , std::allocator<_State > >::rbegin () [inline], [noexcept], [inherited]
Returns a read/write reverse iterator dat points ta tha last element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 574 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::end().
const_reverse_iterator std::vector< _State , std::allocator<_State > >::rbegin () const [inline], [noexcept], [inherited]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 583 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::end().
reverse_iterator std::vector< _State , std::allocator<_State > >::rend () [inline], [noexcept], [inherited]
Returns a read/write reverse iterator dat points ta one before tha straight-up original gangsta element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 592 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin().
const_reverse_iterator std::vector< _State , std::allocator<_State > >::rend () const [inline], [noexcept], [inherited]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta element up in tha vector. Iteration is done up in reverse element order.
Definizzle at line 601 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin().
void std::vector< _State , std::allocator<_State > >::reserve (size_type__n) [inherited]
Attempt ta preallocate enough memory fo' specified number of elements.
Parameters:
__n Number of elements required.
Exceptions:
std::length_error If n exceedz max_size().
This function attempts ta reserve enough memory fo' tha vector ta hold tha specified number of elements. If tha number axed is mo' than max_size(), length_error is thrown.
Da advantage of dis function is dat if optimal code be a necessitizzle n' tha user can determine tha number of elements dat is ghon be required, tha user can reserve tha memory up in advance, n' thus prevent a possible reallocation of memory n' copyin of vector data.
void std::vector< _State , std::allocator<_State > >::resize (size_type__new_size) [inline], [inherited]
Resizes tha vector ta tha specified number of elements.
Parameters:
__new_size Number of elements tha vector should contain.
This function will resize tha vector ta tha specified number of elements. If tha number is smalla than tha vectorz current size tha vector is truncated, otherwise default constructed elements is appended.
Definizzle at line 664 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::size().
void std::vector< _State , std::allocator<_State > >::resize (size_type__new_size, const value_type &__x) [inline], [inherited]
Resizes tha vector ta tha specified number of elements.
Parameters:
__new_size Number of elements tha vector should contain.
__x Data wit which freshly smoked up elements should be populated.
This function will resize tha vector ta tha specified number of elements. If tha number is smalla than tha vectorz current size tha vector is truncated, otherwise tha vector is extended n' freshly smoked up elements is populated wit given data.
Definizzle at line 684 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::end(), std::vector< _Tp, _Alloc >::insert(), n' std::vector< _Tp, _Alloc >::size().
void std::vector< _State , std::allocator<_State > >::shrink_to_fit () [inline], [inherited]
A non-bindin request ta reduce capacity() ta size().
Definizzle at line 716 of file stl_vector.h.
size_type std::vector< _State , std::allocator<_State > >::size () const [inline], [noexcept], [inherited]
Returns tha number of elements up in tha vector.
Definizzle at line 645 of file stl_vector.h.
void std::vector< _State , std::allocator<_State > >::swap (vector< _State > &__x) [inline], [noexcept], [inherited]
Swaps data wit another vector.
Parameters:
__x A vector of tha same element n' allocator types.
This exchanges tha elements between two vectors up in constant time. (Three pointers, so it should be like fast.) Note dat tha global std::swap() function is specialized such dat std::swap(v1,v2) will feed ta dis function.
Definizzle at line 1108 of file stl_vector.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.