" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::discrete_distribution< _IntType > -
SYNOPSIS
Classes
struct param_type
Public Types
typedef _IntType result_type
Public Member Functions
template<typename _InputIterator > discrete_distribution (_InputIterator __wbegin, _InputIterator __wend)
discrete_distribution (initializer_list< double > __wl)
template<typename _Func > discrete_distribution (size_t __nw, double __xmin, double __xmax, _Func __fw)
discrete_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > discrete_distribution
< _IntType >::result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)"
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
param_type param () const
void param (const param_type &__param)
std::vector< double > probabilities () const
void reset ()
Friends
template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::discrete_distribution< _IntType1 > &__x)"
bool operator== (const discrete_distribution &__d1, const discrete_distribution &__d2)
template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::discrete_distribution< _IntType1 > &__x)"
Detailed Description
template<typename _IntType = int>class std::discrete_distribution< _IntType >
A discrete_distribution random number distribution.
Da formula fo' tha discrete probabilitizzle mass function is
Definizzle at line 5251 of file random.h.
Member Typedef Documentation
template<typename _IntType = int> typedef _IntType std::discrete_distribution< _IntType >::result_type
Da type of tha range of tha distribution.
Definizzle at line 5254 of file random.h.
Member Function Documentation
template<typename _IntType = int> result_type std::discrete_distribution< _IntType >::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 5371 of file random.h.
References std::vector< _Tp, _Alloc >::empty(), n' std::vector< _Tp, _Alloc >::size().
template<typename _IntType = int> result_type std::discrete_distribution< _IntType >::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 5364 of file random.h.
template<typename _IntType = int> template<typename _UniformRandomNumberGenerator > result_type std::discrete_distribution< _IntType >::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 5382 of file random.h.
template<typename _IntType = int> param_type std::discrete_distribution< _IntType >::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 5349 of file random.h.
template<typename _IntType = int> void std::discrete_distribution< _IntType >::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 5357 of file random.h.
template<typename _IntType = int> std::vector<double> std::discrete_distribution< _IntType >::probabilitizzles () const [inline]
Returns tha probabilitizzlez of tha distribution.
Definizzle at line 5339 of file random.h.
References std::vector< _Tp, _Alloc >::empty().
template<typename _IntType = int> void std::discrete_distribution< _IntType >::reset () [inline]
Resets tha distribution state.
Definizzle at line 5332 of file random.h.
Playas And Related Function Documentation
template<typename _IntType = int> template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::discrete_distribution< _IntType1 > &__x) [friend]
Inserts a gangbangin' finger-lickin' discrete_distribution random number distribution __x tha fuck into tha output stream __os.
Parameters:
__os An output stream.
__x A discrete_distribution random number distribution.
Returns:
Da output stream wit tha state of __x banged or up in a error state.
template<typename _IntType = int> bool operator== (const discrete_distribution< _IntType > &__d1, const discrete_distribution< _IntType > &__d2) [friend]
Return legit if two discrete distributions have tha same parameters.
Definizzle at line 5417 of file random.h.
template<typename _IntType = int> template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &__is, std::discrete_distribution< _IntType1 > &__x) [friend]
Extracts a gangbangin' finger-lickin' discrete_distribution random number distribution __x from tha input stream __is.
Parameters:
__is An input stream.
__x A discrete_distribution random number generator engine.
Returns:
Da input stream wit __x extracted or up in a error state.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.