" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::deque< _Tp, _Alloc > -
SYNOPSIS
Inherits std::_Deque_base< _Tp, _Alloc >.
Public Types
typedef _Alloc allocator_type
typedef _Base::const_iterator const_iterator
typedef
_Tp_alloc_type::const_pointa const_pointer"
typedef
_Tp_alloc_type::const_reference const_reference"
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator"
typedef ptrdiff_t difference_type
typedef _Base::iterator iterator
typedef _Tp_alloc_type::pointa pointer
typedef _Tp_alloc_type::reference reference
typedef std::reverse_iterator
< iterator > reverse_iterator"
typedef size_t size_type
typedef _Tp value_type
Public Member Functions
deque ()
deque (const allocator_type &__a)
deque (size_type __n)
deque (size_type __n, const value_type &__value, const allocator_type &__a=allocator_type())
deque (const deque &__x)
deque (deque &&__x)
deque (initializer_list< value_type > __l, const allocator_type &__a=allocator_type())
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> deque (_InputIterator __first, _InputIterator __last, const allocator_type &__a=allocator_type())
~deque () noexcept
template<typename... _Args> deque< _Tp, _Alloc >::iterator _M_insert_aux (iterator __pos, _Args &&...__args)
void assign (size_type __n, const value_type &__val)
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void assign (_InputIterator __first, _InputIterator __last)
void assign (initializer_list< value_type > __l)
reference at (size_type __n)
const_reference at (size_type __n) const
reference back ()
const_reference back () const
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
template<typename... _Args> deque< _Tp, _Alloc >::iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> void emplace_back (_Args &&...__args)
template<typename... _Args> void emplace_front (_Args &&...__args)
bool empty () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
reference front ()
const_reference front () const
allocator_type get_allocator () const noexcept
iterator insert (iterator __position, const value_type &__x)
iterator insert (iterator __position, value_type &&__x)
void insert (iterator __p, initializer_list< value_type > __l)
void insert (iterator __position, size_type __n, const value_type &__x)
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void insert (iterator __position, _InputIterator __first, _InputIterator __last)
size_type max_size () const noexcept
deque & operator= (const deque &__x)
deque & operator= (deque &&__x)
deque & operator= (initializer_list< value_type > __l)
reference operator[] (size_type __n)
const_reference operator[] (size_type __n) const
void pop_back ()
void pop_front ()
void push_back (const value_type &__x)
void push_back (value_type &&__x)
void push_front (const value_type &__x)
void push_front (value_type &&__x)
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
void resize (size_type __new_size)
void resize (size_type __new_size, const value_type &__x)
void shrink_to_fit ()
size_type size () const noexcept
void swap (deque &__x)
Protected Types
enum { _S_initial_map_size }
typedef _Alloc::template
rebind< _Tp * >::other _Map_alloc_type"
typedef pointa * _Map_pointer
Protected Member Functions
_Tp ** _M_allocate_map (size_t __n)
_Tp * _M_allocate_node ()
template<typename _InputIterator > void _M_assign_aux (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
template<typename _ForwardIterator > void _M_assign_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _Integer > void _M_assign_dispatch (_Integer __n, _Integer __val, __true_type)
template<typename _InputIterator > void _M_assign_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
void _M_create_nodes (_Tp **__nstart, _Tp **__nfinish)
void _M_deallocate_map (_Tp **__p, size_t __n)
void _M_deallocate_node (_Tp *__p)
void _M_default_append (size_type __n)
void _M_default_initialize ()
template<typename _Alloc1 > void _M_destroy_data (iterator __first, iterator __last, const _Alloc1 &)
void _M_destroy_data (iterator __first, iterator __last, const std::allocator< _Tp > &)
void _M_destroy_data_aux (iterator __first, iterator __last)
void _M_destroy_nodes (_Tp **__nstart, _Tp **__nfinish)
void _M_erase_at_begin (iterator __pos)
void _M_erase_at_end (iterator __pos)
void _M_fill_assign (size_type __n, const value_type &__val)
void _M_fill_initialize (const value_type &__value)
void _M_fill_insert (iterator __pos, size_type __n, const value_type &__x)
_Map_alloc_type _M_get_map_allocator () const noexcept
_Tp_alloc_type & _M_get_Tp_allocator () noexcept
const _Tp_alloc_type & _M_get_Tp_allocator () const noexcept
template<typename _Integer > void _M_initialize_dispatch (_Integer __n, _Integer __x, __true_type)
template<typename _InputIterator > void _M_initialize_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
void _M_initialize_map (size_t)
template<typename... _Args> iterator _M_insert_aux (iterator __pos, _Args &&...__args)
void _M_insert_aux (iterator __pos, size_type __n, const value_type &__x)
template<typename _ForwardIterator > void _M_insert_aux (iterator __pos, _ForwardIterator __first, _ForwardIterator __last, size_type __n)
template<typename _Integer > void _M_insert_dispatch (iterator __pos, _Integer __n, _Integer __x, __true_type)
template<typename _InputIterator > void _M_insert_dispatch (iterator __pos, _InputIterator __first, _InputIterator __last, __false_type)
void _M_range_check (size_type __n) const
template<typename _InputIterator > void _M_range_insert_aux (iterator __pos, _InputIterator __first, _InputIterator __last, std::input_iterator_tag)
template<typename _ForwardIterator > void _M_range_insert_aux (iterator __pos, _ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
bool _M_shrink_to_fit ()
template<typename _InputIterator > void _M_range_initialize (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
template<typename _ForwardIterator > void _M_range_initialize (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename... _Args> void _M_push_back_aux (_Args &&...__args)
template<typename... _Args> void _M_push_front_aux (_Args &&...__args)
void _M_pop_back_aux ()
void _M_pop_front_aux ()
iterator _M_reserve_elements_at_front (size_type __n)
iterator _M_reserve_elements_at_back (size_type __n)
void _M_new_elements_at_front (size_type __new_elements)
void _M_new_elements_at_back (size_type __new_elements)
void _M_reserve_map_at_back (size_type __nodes_to_add=1)
void _M_reserve_map_at_front (size_type __nodes_to_add=1)
void _M_reallocate_map (size_type __nodes_to_add, bool __add_at_front)
Static Protected Member Functions
static size_t _S_buffer_size ()
Protected Attributes
_Deque_impl _M_impl
Detailed Description
template<typename _Tp, typename _Alloc = std::allocator<_Tp>>class std::deque< _Tp, _Alloc >
A standard container rockin fixed-size memory allocation n' constant-time manipulation of elements at either end.
Template Parameters:
_Tp Type of element.
_Alloc Allocator type, defaults ta allocator<_Tp>.
Meets tha requirementz of a container, a reversible container, n' a sequence, includin tha optionizzle sequence requirements.
In previous HP/SGI versionz of deque, there was a extra template parameta so playas could control tha node size. This extension turned up ta violate tha C++ standard (it can be detected rockin template template parameters), n' dat shiznit was removed.
Herez how tha fuck a thugged-out deque<Tp> manages memory. Each deque has 4 members:
Tp** _M_map
size_t _M_map_size
iterator _M_start, _M_finish
map_size be at least 8. map be a array of map_size pointers-to-nodes. (Da name map has not a god damn thang ta do wit tha std::map class, n' nodes should not be trippin wit std::listz usage of node.)
A node has no specific type name as such yo, but it is referred ta as node up in dis file. Well shiiiit, it aint nuthin but a simple array-of-Tp. If Tp is straight-up large, there is ghon be one Tp element per node (i.e., a array of one). For non-huge Tp's, node size is inversely related ta Tp size: tha larger tha Tp, tha fewer Tpz will fit up in a node. Da goal here is ta keep tha total size of a node relatively lil' small-ass n' constant over different Tp's, ta improve allocator efficiency.
Not every last muthafuckin pointa up in tha map array will point ta a node. If tha initial number of elements up in tha deque is small, tha /middle/ map pointas is ghon be valid, n' tha ones all up in tha edges is ghon be unused. This same thang will arise as tha map grows: available map pointers, if any, is ghon be on tha ends fo' realz. As freshly smoked up nodes is pimped, only a subset of tha mapz pointas need ta be copied outward.
Class invariants:
For any nonsingular iterator i:
i.node points ta a gangmember of tha map array. (Yes, you read dat erectly: i.node do not straight-up point ta a node.) Da gangmember of tha map array is what tha fuck straight-up points ta tha node.
i.first == *(i.node) (This points ta tha node (first Tp element).)
i.last == i.first + node_size
i.cur be a pointa up in tha range [i.first, i.last). NOTE: tha implication of dis is dat i.cur be always a thugged-out dereferenceable pointer, even if i be a past-the-end iterator.
Start n' Finish is always nonsingular iterators. NOTE: dis means dat a empty deque must have one node, a thugged-out deque wit <N elements (where N is tha node buffer size) must have one node, a thugged-out deque wit N all up in (2N-1) elements must have two nodes, etc.
For every last muthafuckin node other than start.node n' finish.node, every last muthafuckin element up in tha node be a initialized object. If start.node == finish.node, then [start.cur, finish.cur) is initialized objects, n' tha elements outside dat range is uninitialized storage. Otherwise, [start.cur, start.last) n' [finish.first, finish.cur) is initialized objects, n' [start.first, start.cur) n' [finish.cur, finish.last) is uninitialized storage.
[map, map + map_size) be a valid, non-empty range.
[start.node, finish.node] be a valid range contained within [map, map + map_size).
A pointa up in tha range [map, map + map_size) points ta a allocated node if n' only if tha pointa is up in tha range [start.node, finish.node].
Herez tha magic: not a god damn thang up in deque is aware of tha discontiguous storage!
Da memory setup n' layout occurs up in tha parent, _Base, n' tha iterator class is entirely responsible fo' leaping from one node ta tha next fo' realz. All tha implementation routines fo' deque itself work only all up in tha start n' finish iterators. This keeps tha routines simple n' sane, n' we can use other standard algorithms as well.
Definizzle at line 730 of file stl_deque.h.
Constructor & Destructor Documentation
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque () [inline]
Default constructor creates no elements.
Definizzle at line 782 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (const allocator_type &__a) [inline], [explicit]
Creates a thugged-out deque wit no elements.
Parameters:
__a An allocator object.
Definizzle at line 790 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (size_type__n) [inline], [explicit]
Creates a thugged-out deque wit default constructed elements.
Parameters:
__n Da number of elements ta initially create.
This constructor fills tha deque wit n default constructed elements.
Definizzle at line 802 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (size_type__n, const value_type &__value, const allocator_type &__a = allocator_type()) [inline]
Creates a thugged-out deque wit copiez of a exemplar element.
Parameters:
__n Da number of elements ta initially create.
__value An element ta copy.
__a An allocator.
This constructor fills tha deque wit __n copiez of __value.
Definizzle at line 814 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_fill_initialize().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (const deque< _Tp, _Alloc > &__x) [inline]
Deque copy constructor.
Parameters:
__x A deque of identical element n' allocator types.
Da newly-created deque uses a cold-ass lil copy of tha allocation object used by __x.
Definizzle at line 841 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin(), n' std::deque< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (deque< _Tp, _Alloc > &&__x) [inline]
Deque move constructor.
Parameters:
__x A deque of identical element n' allocator types.
Da newly-created deque gotz nuff tha exact contentz of __x. Da contentz of __x is a valid yo, but unspecified deque.
Definizzle at line 855 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (initializer_list< value_type >__l, const allocator_type &__a = allocator_type()) [inline]
Buildz a thugged-out deque from a initializer list.
Parameters:
__l An initializer_list.
__a An allocator object.
Smoke a thugged-out deque consistin of copiez of tha elements up in tha initializer_list __l.
This will call tha element typez copy constructor N times (where N is __l.size()) n' do no memory reallocation.
Definizzle at line 869 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_range_initialize().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> std::deque< _Tp, _Alloc >::deque (_InputIterator__first, _InputIterator__last, const allocator_type &__a = allocator_type()) [inline]
Buildz a thugged-out deque from a range.
Parameters:
__first An input iterator.
__last An input iterator.
__a An allocator object.
Smoke a thugged-out deque consistin of copiez of tha elements from [__first, __last).
If tha iterators is forward, bidirectional, or random-access, then dis will call tha elements' copy constructor N times (where N is distance(__first,__last)) n' do no memory reallocation. But if only input iterators is used, then dis will do at most 2N calls ta tha copy constructor, n' logN memory reallocations.
Definizzle at line 896 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::~deque () [inline], [noexcept]
Da dtor only erases tha elements, n' note dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 917 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin(), n' std::deque< _Tp, _Alloc >::end().
Member Function Documentation
template<typename _Tp , typename _Alloc > void deque::_M_fill_initialize (const value_type &__value) [protected]
Fills tha deque wit copiez of value.
Parameters:
__value Initial value.
Returns:
Nothing.
Precondition:
_M_start n' _M_finish have already been initialized yo, but none of tha dequez elements have yet been constructed.
This function is called only when tha user serves up a explicit size (with or without a explicit exemplar value).
Definizzle at line 351 of file deque.tcc.
References std::_Destroy().
Referenced by std::deque< _Tp, _Alloc >::deque().
template<typename _Tp , typename _Alloc > void std::_Deque_base< _Tp, _Alloc >::_M_initialize_map (size_t__num_elements) [protected], [inherited]
Layout storage.
Parameters:
__num_elements Da count of Tz fo' which ta allocate space at first.
Returns:
Nothing.
Da initial underlyin memory layout be a lil' bit fucked up...
Definizzle at line 582 of file stl_deque.h.
References std::max().
template<typename _Tp , typename _Alloc > void deque::_M_new_elements_at_back (size_type__new_elements) [protected]
Memory-handlin helpers fo' tha previous internal bang functions.
Definizzle at line 849 of file deque.tcc.
References std::size().
Referenced by std::deque< _Tp, _Alloc >::_M_reserve_elements_at_back().
template<typename _Tp , typename _Alloc > void deque::_M_new_elements_at_front (size_type__new_elements) [protected]
Memory-handlin helpers fo' tha previous internal bang functions.
Definizzle at line 824 of file deque.tcc.
References std::size().
Referenced by std::deque< _Tp, _Alloc >::_M_reserve_elements_at_front().
template<typename _Tp , typename _Alloc > void deque::_M_pop_back_aux () [protected]
Helper functions fo' push_* n' pop_*.
Definizzle at line 505 of file deque.tcc.
Referenced by std::deque< _Tp, _Alloc >::pop_back().
template<typename _Tp , typename _Alloc > void deque::_M_pop_front_aux () [protected]
Helper functions fo' push_* n' pop_*.
Definizzle at line 520 of file deque.tcc.
Referenced by std::deque< _Tp, _Alloc >::pop_front().
template<typename _Tp , typename _Alloc > template<typename... _Args> void deque::_M_push_back_aux (_Args &&...__args) [protected]
Helper functions fo' push_* n' pop_*.
Definizzle at line 439 of file deque.tcc.
Referenced by std::deque< _Tp, _Alloc >::push_back().
template<typename _Tp , typename _Alloc > template<typename... _Args> void deque::_M_push_front_aux (_Args &&...__args) [protected]
Helper functions fo' push_* n' pop_*.
Definizzle at line 473 of file deque.tcc.
Referenced by std::deque< _Tp, _Alloc >::push_front().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::_M_range_check (size_type__n) const [inline], [protected]
Safety check used only from at().
Definizzle at line 1265 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::size().
Referenced by std::deque< _Tp, _Alloc >::at().
template<typename _Tp , typename _Alloc > template<typename _InputIterator > void deque::_M_range_initialize (_InputIterator__first, _InputIterator__last, std::input_iterator_tag) [protected]
Fills tha deque wit whatever is up in [first,last).
Parameters:
__first An input iterator.
__last An input iterator.
Returns:
Nothing.
If tha iterators is straight-up forward iterators (or better), then tha memory layout can be done all at once. Else we move forward rockin push_back on each value from tha iterator.
Definizzle at line 377 of file deque.tcc.
Referenced by std::deque< _Tp, _Alloc >::deque().
template<typename _Tp , typename _Alloc > template<typename _ForwardIterator > void deque::_M_range_initialize (_ForwardIterator__first, _ForwardIterator__last, std::forward_iterator_tag) [protected]
Fills tha deque wit whatever is up in [first,last).
Parameters:
__first An input iterator.
__last An input iterator.
Returns:
Nothing.
If tha iterators is straight-up forward iterators (or better), then tha memory layout can be done all at once. Else we move forward rockin push_back on each value from tha iterator.
Definizzle at line 401 of file deque.tcc.
References std::_Destroy(), std::advance(), n' std::distance().
template<typename _Tp , typename _Alloc > void deque::_M_reallocate_map (size_type__nodes_to_add, bool__add_at_front) [protected]
Memory-handlin helpers fo' tha major map. Makes shizzle tha _M_map has space fo' freshly smoked up nodes. Do not straight-up add tha nodes. Can invalidate _M_map pointers. (And consequently, deque iterators.)
Definizzle at line 874 of file deque.tcc.
References std::max().
Referenced by std::deque< _Tp, _Alloc >::_M_reserve_map_at_back(), n' std::deque< _Tp, _Alloc >::_M_reserve_map_at_front().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::_M_reserve_elements_at_back (size_type__n) [inline], [protected]
Memory-handlin helpers fo' tha previous internal bang functions.
Definizzle at line 1898 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_new_elements_at_back().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::_M_reserve_elements_at_front (size_type__n) [inline], [protected]
Memory-handlin helpers fo' tha previous internal bang functions.
Definizzle at line 1888 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_new_elements_at_front().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::_M_reserve_map_at_back (size_type__nodes_to_add = 1) [inline], [protected]
Memory-handlin helpers fo' tha major map. Makes shizzle tha _M_map has space fo' freshly smoked up nodes. Do not straight-up add tha nodes. Can invalidate _M_map pointers. (And consequently, deque iterators.)
Definizzle at line 1924 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_reallocate_map().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::_M_reserve_map_at_front (size_type__nodes_to_add = 1) [inline], [protected]
Memory-handlin helpers fo' tha major map. Makes shizzle tha _M_map has space fo' freshly smoked up nodes. Do not straight-up add tha nodes. Can invalidate _M_map pointers. (And consequently, deque iterators.)
Definizzle at line 1932 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_reallocate_map().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::assign (size_type__n, const value_type &__val) [inline]
Assigns a given value ta a thugged-out deque.
Parameters:
__n Number of elements ta be assigned.
__val Value ta be assigned.
This function fills a thugged-out deque wit n copiez of tha given value. Note dat tha assignment straight-up chizzlez tha deque n' dat tha resultin dequez size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 978 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::assign(), n' std::deque< _Tp, _Alloc >::operator=().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void std::deque< _Tp, _Alloc >::assign (_InputIterator__first, _InputIterator__last) [inline]
Assigns a range ta a thugged-out deque.
Parameters:
__first An input iterator.
__last An input iterator.
This function fills a thugged-out deque wit copiez of tha elements up in tha range [__first,__last).
Note dat tha assignment straight-up chizzlez tha deque n' dat tha resultin dequez size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 997 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::assign (initializer_list< value_type >__l) [inline]
Assigns a initializer list ta a thugged-out deque.
Parameters:
__l An initializer_list.
This function fills a thugged-out deque wit copiez of tha elements up in tha initializer_list __l.
Note dat tha assignment straight-up chizzlez tha deque n' dat tha resultin dequez size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 1022 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::assign().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::deque< _Tp, _Alloc >::at (size_type__n) [inline]
Provides access ta tha data contained up in tha deque.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read/write reference ta data.
Exceptions:
std::out_of_range If __n be a invalid index.
This function serves up fo' less thuggy data access. Da parameta is first checked dat it is up in tha range of tha deque. Da function throws out_of_range if tha check fails.
Definizzle at line 1284 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_range_check().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::deque< _Tp, _Alloc >::at (size_type__n) const [inline]
Provides access ta tha data contained up in tha deque.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read-only (constant) reference ta data.
Exceptions:
std::out_of_range If __n be a invalid index.
This function serves up fo' less thuggy data access. Da parameta is first checked dat it is up in tha range of tha deque. Da function throws out_of_range if tha check fails.
Definizzle at line 1302 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_range_check().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::deque< _Tp, _Alloc >::back () [inline]
Returns a read/write reference ta tha data all up in tha last element of tha deque.
Definizzle at line 1329 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::deque< _Tp, _Alloc >::back () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha last element of tha deque.
Definizzle at line 1341 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::begin () [inline], [noexcept]
Returns a read/write iterator dat points ta tha straight-up original gangsta element up in tha deque. Iteration is done up in ordinary element order.
Definizzle at line 1037 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::clear(), std::deque< _Tp, _Alloc >::deque(), std::deque< _Tp, _Alloc >::front(), std::deque< _Tp, _Alloc >::operator=(), std::operator==(), n' std::deque< _Tp, _Alloc >::~deque().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::deque< _Tp, _Alloc >::begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha deque. Iteration is done up in ordinary element order.
Definizzle at line 1045 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::deque< _Tp, _Alloc >::cbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha deque. Iteration is done up in ordinary element order.
Definizzle at line 1108 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::deque< _Tp, _Alloc >::cend () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha deque. Iteration is done up in ordinary element order.
Definizzle at line 1117 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::clear () [inline], [noexcept]
Erases all tha elements. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 1616 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin().
Referenced by std::deque< _Tp, _Alloc >::operator=().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::deque< _Tp, _Alloc >::crbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha deque. Iteration is done up in reverse element order.
Definizzle at line 1126 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::deque< _Tp, _Alloc >::crend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta element up in tha deque. Iteration is done up in reverse element order.
Definizzle at line 1135 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename... _Args> iterator std::deque< _Tp, _Alloc >::emplace (iterator__position, _Args &&...__args)
Inserts a object up in deque before specified iterator.
Parameters:
__position An iterator tha fuck into tha deque.
__args Arguments.
Returns:
An iterator dat points ta tha banged data.
This function will bang a object of type T constructed wit T(std::forward<Args>(args)...) before tha specified location.
Referenced by std::deque< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> bool std::deque< _Tp, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha deque is empty. (Thus begin() would equal end().)
Definizzle at line 1228 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::end () [inline], [noexcept]
Returns a read/write iterator dat points one past tha last element up in tha deque. Iteration is done up in ordinary element order.
Definizzle at line 1054 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::back(), std::deque< _Tp, _Alloc >::deque(), std::deque< _Tp, _Alloc >::operator=(), std::operator==(), n' std::deque< _Tp, _Alloc >::~deque().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::deque< _Tp, _Alloc >::end () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha deque. Iteration is done up in ordinary element order.
Definizzle at line 1063 of file stl_deque.h.
template<typename _Tp , typename _Alloc > deque< _Tp, _Alloc >::iterator deque::erase (iterator__position)
Remove element at given position.
Parameters:
__position Iterator pointin ta element ta be erased.
Returns:
An iterator pointin ta tha next element (or end()).
This function will erase tha element all up in tha given posizzle n' thus shorten tha deque by one.
Da user is cautioned dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 194 of file deque.tcc.
References std::begin(), std::end(), n' std::size().
template<typename _Tp , typename _Alloc > deque< _Tp, _Alloc >::iterator deque::erase (iterator__first, iterator__last)
Remove a range of elements.
Parameters:
__first Iterator pointin ta tha straight-up original gangsta element ta be erased.
__last Iterator pointin ta one past tha last element ta be erased.
Returns:
An iterator pointin ta tha element pointed ta by last prior ta erasin (or end()).
This function will erase tha elements up in tha range [__first,__last) n' shorten tha deque accordingly.
Da user is cautioned dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 217 of file deque.tcc.
References std::begin(), std::end(), n' std::size().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::deque< _Tp, _Alloc >::front () [inline]
Returns a read/write reference ta tha data all up in tha straight-up original gangsta element of tha deque.
Definizzle at line 1313 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::deque< _Tp, _Alloc >::front () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha straight-up original gangsta element of tha deque.
Definizzle at line 1321 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> allocator_type std::deque< _Tp, _Alloc >::get_allocator () const [inline], [noexcept]
Git a cold-ass lil copy of tha memory allocation object.
Definizzle at line 1028 of file stl_deque.h.
template<typename _Tp , typename _Alloc > deque< _Tp, _Alloc >::iterator deque::insert (iterator__position, const value_type &__x)
Inserts given value tha fuck into deque before specified iterator.
Parameters:
__position An iterator tha fuck into tha deque.
__x Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given value before tha specified location.
Definizzle at line 149 of file deque.tcc.
Referenced by std::deque< _Tp, _Alloc >::insert(), n' std::deque< _Tp, _Alloc >::resize().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::insert (iterator__position, value_type &&__x) [inline]
Inserts given rvalue tha fuck into deque before specified iterator.
Parameters:
__position An iterator tha fuck into tha deque.
__x Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given rvalue before tha specified location.
Definizzle at line 1492 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::emplace().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::insert (iterator__p, initializer_list< value_type >__l) [inline]
Inserts a initializer list tha fuck into tha deque.
Parameters:
__p An iterator tha fuck into tha deque.
__l An initializer_list.
This function will bang copiez of tha data up in tha initializer_list __l tha fuck into tha deque before tha location specified by __p. This is known as list insert.
Definizzle at line 1505 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::insert (iterator__position, size_type__n, const value_type &__x) [inline]
Inserts a fuckin shitload of copiez of given data tha fuck into tha deque.
Parameters:
__position An iterator tha fuck into tha deque.
__n Number of elements ta be inserted.
__x Data ta be inserted.
This function will bang a specified number of copiez of tha given data before tha location specified by __position.
Definizzle at line 1519 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void std::deque< _Tp, _Alloc >::insert (iterator__position, _InputIterator__first, _InputIterator__last) [inline]
Inserts a range tha fuck into tha deque.
Parameters:
__position An iterator tha fuck into tha deque.
__first An input iterator.
__last An input iterator.
This function will bang copiez of tha data up in tha range [__first,__last) tha fuck into tha deque before tha location specified by __position. This is known as range insert.
Definizzle at line 1536 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::deque< _Tp, _Alloc >::max_size () const [inline], [noexcept]
Returns tha size() of tha phattest possible deque.
Definizzle at line 1147 of file stl_deque.h.
template<typename _Tp , typename _Alloc > deque< _Tp, _Alloc > & deque::operator= (const deque< _Tp, _Alloc > &__x)
Deque assignment operator.
Parameters:
__x A deque of identical element n' allocator types.
All tha elementz of x is copied yo, but unlike tha copy constructor, tha allocator object aint copied.
Definizzle at line 93 of file deque.tcc.
References std::deque< _Tp, _Alloc >::begin(), std::deque< _Tp, _Alloc >::end(), std::deque< _Tp, _Alloc >::size(), n' std::size().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> deque& std::deque< _Tp, _Alloc >::operator= (deque< _Tp, _Alloc > &&__x) [inline]
Deque move assignment operator.
Parameters:
__x A deque of identical element n' allocator types.
Da contentz of __x is moved tha fuck into dis deque (without copying). __x be a valid yo, but unspecified deque.
Definizzle at line 939 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::clear(), n' std::deque< _Tp, _Alloc >::swap().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> deque& std::deque< _Tp, _Alloc >::operator= (initializer_list< value_type >__l) [inline]
Assigns a initializer list ta a thugged-out deque.
Parameters:
__l An initializer_list.
This function fills a thugged-out deque wit copiez of tha elements up in tha initializer_list __l.
Note dat tha assignment straight-up chizzlez tha deque n' dat tha resultin dequez size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 960 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::assign().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::deque< _Tp, _Alloc >::operator[] (size_type__n) [inline]
Subscript access ta tha data contained up in tha deque.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read/write reference ta data.
This operator allows fo' easy as fuck , array-style, data access. Note dat data access wit dis operator is unchecked n' out_of_range lookups is not defined. (For checked lookups peep at().)
Definizzle at line 1244 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::deque< _Tp, _Alloc >::operator[] (size_type__n) const [inline]
Subscript access ta tha data contained up in tha deque.
Parameters:
__n Da index of tha element fo' which data should be accessed.
Returns:
Read-only (constant) reference ta data.
This operator allows fo' easy as fuck , array-style, data access. Note dat data access wit dis operator is unchecked n' out_of_range lookups is not defined. (For checked lookups peep at().)
Definizzle at line 1259 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::pop_back () [inline]
Removes last element. This be a typical stack operation. Well shiiiit, it shrinks tha deque by one.
Note dat no data is returned, n' if tha last elementz data is needed, it should be retrieved before pop_back() is called.
Definizzle at line 1442 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_pop_back_aux().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::pop_front () [inline]
Removes first element. This be a typical stack operation. Well shiiiit, it shrinks tha deque by one.
Note dat no data is returned, n' if tha straight-up original gangsta elementz data is needed, it should be retrieved before pop_front() is called.
Definizzle at line 1421 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_pop_front_aux().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::push_back (const value_type &__x) [inline]
Add data ta tha end of tha deque.
Parameters:
__x Data ta be added.
This be a typical stack operation. Da function creates a element all up in tha end of tha deque n' assigns tha given data ta it. Cuz of tha nature of a thugged-out deque dis operation can be done up in constant time.
Definizzle at line 1390 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_push_back_aux().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::push_front (const value_type &__x) [inline]
Add data ta tha front of tha deque.
Parameters:
__x Data ta be added.
This be a typical stack operation. Da function creates a element all up in tha front of tha deque n' assigns tha given data ta it. Cuz of tha nature of a thugged-out deque dis operation can be done up in constant time.
Definizzle at line 1359 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::_M_push_front_aux().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::deque< _Tp, _Alloc >::rbegin () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta tha last element up in tha deque. Iteration is done up in reverse element order.
Definizzle at line 1072 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::deque< _Tp, _Alloc >::rbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha deque. Iteration is done up in reverse element order.
Definizzle at line 1081 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::deque< _Tp, _Alloc >::rend () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta one before tha straight-up original gangsta element up in tha deque. Iteration is done up in reverse element order.
Definizzle at line 1090 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::deque< _Tp, _Alloc >::rend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta element up in tha deque. Iteration is done up in reverse element order.
Definizzle at line 1099 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::resize (size_type__new_size) [inline]
Resizes tha deque ta tha specified number of elements.
Parameters:
__new_size Number of elements tha deque should contain.
This function will resize tha deque ta tha specified number of elements. If tha number is smalla than tha dequez current size tha deque is truncated, otherwise default constructed elements is appended.
Definizzle at line 1161 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::size().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::resize (size_type__new_size, const value_type &__x) [inline]
Resizes tha deque ta tha specified number of elements.
Parameters:
__new_size Number of elements tha deque should contain.
__x Data wit which freshly smoked up elements should be populated.
This function will resize tha deque ta tha specified number of elements. If tha number is smalla than tha dequez current size tha deque is truncated, otherwise tha deque is extended n' freshly smoked up elements is populated wit given data.
Definizzle at line 1183 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::insert(), n' std::deque< _Tp, _Alloc >::size().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::shrink_to_fit () [inline]
A non-bindin request ta reduce memory use.
Definizzle at line 1219 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::deque< _Tp, _Alloc >::size () const [inline], [noexcept]
Returns tha number of elements up in tha deque.
Definizzle at line 1142 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::_M_range_check(), std::deque< _Tp, _Alloc >::operator=(), std::operator==(), n' std::deque< _Tp, _Alloc >::resize().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::swap (deque< _Tp, _Alloc > &__x) [inline]
Swaps data wit another deque.
Parameters:
__x A deque of tha same element n' allocator types.
This exchanges tha elements between two deques up in constant time. (Four pointers, so it should be like fast.) Note dat tha global std::swap() function is specialized such dat std::swap(d1,d2) will feed ta dis function.
Definizzle at line 1596 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::operator=(), n' std::swap().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.