" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::binomial_distribution< _IntType > -
SYNOPSIS
Classes
struct param_type
Public Types
typedef _IntType result_type
Public Member Functions
binomial_distribution (_IntType __t=_IntType(1), double __p=0.5)
binomial_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > binomial_distribution
< _IntType >::result_type _M_waiting (_UniformRandomNumberGenerator &__urng, _IntType __t, double __q)"
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > binomial_distribution
< _IntType >::result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)"
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
double p () const
param_type param () const
void param (const param_type &__param)
void reset ()
_IntType t () const
Friends
template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::binomial_distribution< _IntType1 > &__x)"
bool operator== (const binomial_distribution &__d1, const binomial_distribution &__d2)
template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::binomial_distribution< _IntType1 > &__x)"
Detailed Description
template<typename _IntType = int>class std::binomial_distribution< _IntType >
A discrete binomial random number distribution.
Da formula fo' tha binomial probabilitizzle densitizzle function is $p(i|t,p) = \binom{t}{i} p^i (1 - p)^{t - i}$ where $t$ n' $p$ is tha parametaz of tha distribution.
Definizzle at line 3777 of file random.h.
Member Typedef Documentation
template<typename _IntType = int> typedef _IntType std::binomial_distribution< _IntType >::result_type
Da type of tha range of tha distribution.
Definizzle at line 3780 of file random.h.
Member Function Documentation
template<typename _IntType = int> result_type std::binomial_distribution< _IntType >::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 3887 of file random.h.
template<typename _IntType = int> result_type std::binomial_distribution< _IntType >::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 3880 of file random.h.
template<typename _IntType = int> template<typename _UniformRandomNumberGenerator > binomial_distribution<_IntType>::result_type std::binomial_distribution< _IntType >::operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)
A rejection algorithm when t * p >= 8 n' a simple waitin time method - tha second up in tha referenced book - otherwise. NB: Da forma be available only if _GLIBCXX_USE_C99_MATH_TR1 is defined.
Reference: Devroye, L. Non-Uniform Random Variates Generation. Right back up in yo muthafuckin ass. Springer-Verlag, New York, 1986, Ch. X, Sect. 4 (+ Errata!).
Definizzle at line 1686 of file bits/random.tcc.
References std::abs(), std::numeric_limits< _Tp >::epsilon(), std::log(), n' std::numeric_limits< _Tp >::max().
template<typename _IntType = int> template<typename _UniformRandomNumberGenerator > result_type std::binomial_distribution< _IntType >::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 3895 of file random.h.
template<typename _IntType = int> double std::binomial_distribution< _IntType >::p () const [inline]
Returns tha distribution p parameter.
Definizzle at line 3858 of file random.h.
template<typename _IntType = int> param_type std::binomial_distribution< _IntType >::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 3865 of file random.h.
template<typename _IntType = int> void std::binomial_distribution< _IntType >::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 3873 of file random.h.
template<typename _IntType = int> void std::binomial_distribution< _IntType >::reset () [inline]
Resets tha distribution state.
Definizzle at line 3844 of file random.h.
References std::normal_distribution< _RealType >::reset().
template<typename _IntType = int> _IntType std::binomial_distribution< _IntType >::t () const [inline]
Returns tha distribution t parameter.
Definizzle at line 3851 of file random.h.
Playas And Related Function Documentation
template<typename _IntType = int> template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::binomial_distribution< _IntType1 > &__x) [friend]
Inserts a funky-ass binomial_distribution random number distribution __x tha fuck into tha output stream __os.
Parameters:
__os An output stream.
__x A binomial_distribution random number distribution.
Returns:
Da output stream wit tha state of __x banged or up in a error state.
template<typename _IntType = int> bool operator== (const binomial_distribution< _IntType > &__d1, const binomial_distribution< _IntType > &__d2) [friend]
Return legit if two binomial distributions have tha same parametas n' tha sequences dat would be generated is equal.
Definizzle at line 3931 of file random.h.
template<typename _IntType = int> template<typename _IntType1 , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &__is, std::binomial_distribution< _IntType1 > &__x) [friend]
Extracts a funky-ass binomial_distribution random number distribution __x from tha input stream __is.
Parameters:
__is An input stream.
__x A binomial_distribution random number generator engine.
Returns:
Da input stream wit __x extracted or up in a error state.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.