" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::list< _Tp, _Alloc > -
SYNOPSIS
Inherits std::_List_base< _Tp, _Alloc >.
Public Types
typedef _Alloc allocator_type
typedef _List_const_iterator< _Tp > const_iterator
typedef
_Tp_alloc_type::const_pointa const_pointer"
typedef
_Tp_alloc_type::const_reference const_reference"
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator"
typedef ptrdiff_t difference_type
typedef _List_iterator< _Tp > iterator
typedef _Tp_alloc_type::pointa pointer
typedef _Tp_alloc_type::reference reference
typedef std::reverse_iterator
< iterator > reverse_iterator"
typedef size_t size_type
typedef _Tp value_type
Public Member Functions
list ()
list (const allocator_type &__a)
list (size_type __n)
list (size_type __n, const value_type &__value, const allocator_type &__a=allocator_type())
list (const list &__x)
list (list &&__x) noexcept
list (initializer_list< value_type > __l, const allocator_type &__a=allocator_type())
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> list (_InputIterator __first, _InputIterator __last, const allocator_type &__a=allocator_type())
void assign (size_type __n, const value_type &__val)
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void assign (_InputIterator __first, _InputIterator __last)
void assign (initializer_list< value_type > __l)
reference back ()
const_reference back () const
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
template<typename... _Args> list< _Tp, _Alloc >::iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> void emplace_back (_Args &&...__args)
template<typename... _Args> void emplace_front (_Args &&...__args)
bool empty () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
reference front ()
const_reference front () const
allocator_type get_allocator () const noexcept
iterator insert (iterator __position, const value_type &__x)
iterator insert (iterator __position, value_type &&__x)
void insert (iterator __p, initializer_list< value_type > __l)
void insert (iterator __position, size_type __n, const value_type &__x)
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void insert (iterator __position, _InputIterator __first, _InputIterator __last)
size_type max_size () const noexcept
void merge (list &&__x)
void merge (list &__x)
template<typename _StrictWeakOrderin > void merge (list &&__x, _StrictWeakOrderin __comp)
template<typename _StrictWeakOrderin > void merge (list &__x, _StrictWeakOrderin __comp)
list & operator= (const list &__x)
list & operator= (list &&__x)
list & operator= (initializer_list< value_type > __l)
void pop_back ()
void pop_front ()
void push_back (const value_type &__x)
void push_back (value_type &&__x)
void push_front (const value_type &__x)
void push_front (value_type &&__x)
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
void remove (const _Tp &__value)
template<typename _Predicate > void remove_if (_Predicate)
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
void resize (size_type __new_size)
void resize (size_type __new_size, const value_type &__x)
void reverse () noexcept
size_type size () const noexcept
void sort ()
template<typename _StrictWeakOrderin > void sort (_StrictWeakOrdering)
void splice (iterator __position, list &&__x)
void splice (iterator __position, list &__x)
void splice (iterator __position, list &&__x, iterator __i)
void splice (iterator __position, list &__x, iterator __i)
void splice (iterator __position, list &&__x, iterator __first, iterator __last)
void splice (iterator __position, list &__x, iterator __first, iterator __last)
void swap (list &__x)
void unique ()
template<typename _BinaryPredicate > void unique (_BinaryPredicate)
Protected Types
typedef _List_node< _Tp > _Node
Protected Member Functions
template<typename _Integer > void _M_assign_dispatch (_Integer __n, _Integer __val, __true_type)
template<typename _InputIterator > void _M_assign_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
void _M_check_equal_allocators (list &__x)
void _M_clear ()
template<typename... _Args> _Node * _M_create_node (_Args &&...__args)
void _M_default_append (size_type __n)
void _M_default_initialize (size_type __n)
void _M_erase (iterator __position)
void _M_fill_assign (size_type __n, const value_type &__val)
void _M_fill_initialize (size_type __n, const value_type &__x)
_List_node< _Tp > * _M_get_node ()
_Node_alloc_type & _M_get_Node_allocator () noexcept
const _Node_alloc_type & _M_get_Node_allocator () const noexcept
_Tp_alloc_type _M_get_Tp_allocator () const noexcept
void _M_init ()
template<typename _Integer > void _M_initialize_dispatch (_Integer __n, _Integer __x, __true_type)
template<typename _InputIterator > void _M_initialize_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
template<typename... _Args> void _M_insert (iterator __position, _Args &&...__args)
void _M_put_node (_List_node< _Tp > *__p)
void _M_transfer (iterator __position, iterator __first, iterator __last)
Protected Attributes
_List_impl _M_impl
Detailed Description
template<typename _Tp, typename _Alloc = std::allocator<_Tp>>class std::list< _Tp, _Alloc >
A standard container wit linear time access ta elements, n' fixed time insertion/deletion at any point up in tha sequence.
Template Parameters:
_Tp Type of element.
_Alloc Allocator type, defaults ta allocator<_Tp>.
Meets tha requirementz of a container, a reversible container, n' a sequence, includin tha optionizzle sequence requirements wit tha exception of at n' operator[].
This be a doubly linked list. Traversal up n' down tha list requires linear time yo, but addin n' removin elements (or nodes) is done up in constant time, regardless of where tha chizzle takes place. Unlike std::vector n' std::deque, random-access iterators is not provided, so subscriptin ( [] ) access aint allowed. For algorithms which only need sequential access, dis lack make no difference.
Also unlike tha other standard containers, std::list serves up specialized algorithms unique ta linked lists, like fuckin splicing, sorting, n' in-place reversal.
A couple points on memory allocation fo' list<Tp>:
First, we never straight-up allocate a Tp, we allocate List_node<Tp>z n' trust [20.1.5]/4 ta DTRT. This is ta ensure dat afta elements from list<X,Alloc1> is spliced tha fuck into list<X,Alloc2>, beatin tha livin shiznit outta tha memory of tha second list be a valid operation, i.e., Alloc1 giveth n' Alloc2 taketh away.
Second, a list conceptually represented as
A <---> B <---> C <---> D
 is straight-up circular; a link exists between A n' D. Da list class holdz (as its only data member) a private list::iterator pointin ta D, not ta A! To git ta tha head of tha list, we start all up in tha tail n' move forward by one. When dis member iteratorz next/previous pointas refer ta itself, tha list is empty.
Definizzle at line 438 of file stl_list.h.
Constructor & Destructor Documentation
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list () [inline]
Default constructor creates no elements.
Definizzle at line 523 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (const allocator_type &__a) [inline], [explicit]
Creates a list wit no elements.
Parameters:
__a An allocator object.
Definizzle at line 531 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (size_type__n) [inline], [explicit]
Creates a list wit default constructed elements.
Parameters:
__n Da number of elements ta initially create.
This constructor fills tha list wit __n default constructed elements.
Definizzle at line 543 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (size_type__n, const value_type &__value, const allocator_type &__a = allocator_type()) [inline]
Creates a list wit copiez of a exemplar element.
Parameters:
__n Da number of elements ta initially create.
__value An element ta copy.
__a An allocator object.
This constructor fills tha list wit __n copiez of __value.
Definizzle at line 555 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (const list< _Tp, _Alloc > &__x) [inline]
List copy constructor.
Parameters:
__x A list of identical element n' allocator types.
Da newly-created list uses a cold-ass lil copy of tha allocation object used by __x.
Definizzle at line 582 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (list< _Tp, _Alloc > &&__x) [inline], [noexcept]
List move constructor.
Parameters:
__x A list of identical element n' allocator types.
Da newly-created list gotz nuff tha exact contentz of __x. Da contentz of __x is a valid yo, but unspecified list.
Definizzle at line 594 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (initializer_list< value_type >__l, const allocator_type &__a = allocator_type()) [inline]
Buildz a list from a initializer_list.
Parameters:
__l An initializer_list of value_type.
__a An allocator object.
Smoke a list consistin of copiez of tha elements up in tha initializer_list __l. This is linear up in __l.size().
Definizzle at line 605 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> std::list< _Tp, _Alloc >::list (_InputIterator__first, _InputIterator__last, const allocator_type &__a = allocator_type()) [inline]
Buildz a list from a range.
Parameters:
__first An input iterator.
__last An input iterator.
__a An allocator object.
Smoke a list consistin of copiez of tha elements from [__first,__last). This is linear up in N (where N is distance(__first,__last)).
Definizzle at line 624 of file stl_list.h.
Member Function Documentation
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename... _Args> _Node* std::list< _Tp, _Alloc >::_M_create_node (_Args &&...__args) [inline], [protected]
Parameters:
__args An instizzle of user data.
Allocates space fo' a freshly smoked up node n' constructs a cold-ass lil copy of __args up in it.
Definizzle at line 500 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::assign (size_type__n, const value_type &__val) [inline]
Assigns a given value ta a list.
Parameters:
__n Number of elements ta be assigned.
__val Value ta be assigned.
This function fills a list wit __n copiez of tha given value. Note dat tha assignment straight-up chizzlez tha list n' dat tha resultin listz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 702 of file stl_list.h.
Referenced by std::list< __inp, __rebind_inp >::assign(), n' std::list< __inp, __rebind_inp >::operator=().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void std::list< _Tp, _Alloc >::assign (_InputIterator__first, _InputIterator__last) [inline]
Assigns a range ta a list.
Parameters:
__first An input iterator.
__last An input iterator.
This function fills a list wit copiez of tha elements up in tha range [__first,__last).
Note dat tha assignment straight-up chizzlez tha list n' dat tha resultin listz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 721 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::assign (initializer_list< value_type >__l) [inline]
Assigns a initializer_list ta a list.
Parameters:
__l An initializer_list of value_type.
Replace tha contentz of tha list wit copiez of tha elements up in tha initializer_list __l. This is linear up in __l.size().
Definizzle at line 743 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::list< _Tp, _Alloc >::back () [inline]
Returns a read/write reference ta tha data all up in tha last element of tha list.
Definizzle at line 943 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::list< _Tp, _Alloc >::back () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha last element of tha list.
Definizzle at line 955 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::list< _Tp, _Alloc >::begin () [inline], [noexcept]
Returns a read/write iterator dat points ta tha straight-up original gangsta element up in tha list. Iteration is done up in ordinary element order.
Definizzle at line 758 of file stl_list.h.
Referenced by std::list< __inp, __rebind_inp >::crend(), std::list< __inp, __rebind_inp >::front(), std::list< __inp, __rebind_inp >::list(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::operator=(), std::operator==(), std::list< __inp, __rebind_inp >::pop_front(), std::list< __inp, __rebind_inp >::push_front(), std::list< __inp, __rebind_inp >::rend(), std::list< __inp, __rebind_inp >::size(), std::list< _Tp, _Alloc >::sort(), n' std::list< __inp, __rebind_inp >::splice().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::list< _Tp, _Alloc >::begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha list. Iteration is done up in ordinary element order.
Definizzle at line 767 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::list< _Tp, _Alloc >::cbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha list. Iteration is done up in ordinary element order.
Definizzle at line 831 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::list< _Tp, _Alloc >::cend () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha list. Iteration is done up in ordinary element order.
Definizzle at line 840 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::clear () [inline], [noexcept]
Erases all tha elements. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 1228 of file stl_list.h.
Referenced by std::list< __inp, __rebind_inp >::operator=().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::list< _Tp, _Alloc >::crbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha list. Iteration is done up in reverse element order.
Definizzle at line 849 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::list< _Tp, _Alloc >::crend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta element up in tha list. Iteration is done up in reverse element order.
Definizzle at line 858 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename... _Args> iterator std::list< _Tp, _Alloc >::emplace (iterator__position, _Args &&...__args)
Constructs object up in list before specified iterator.
Parameters:
__position A const_iterator tha fuck into tha list.
__args Arguments.
Returns:
An iterator dat points ta tha banged data.
This function will bang a object of type T constructed wit T(std::forward<Args>(args)...) before tha specified location. Cuz of tha nature of a list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Referenced by std::list< __inp, __rebind_inp >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> bool std::list< _Tp, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha list is empty. (Thus begin() would equal end().)
Definizzle at line 868 of file stl_list.h.
Referenced by std::list< _Tp, _Alloc >::sort(), n' std::list< __inp, __rebind_inp >::splice().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::list< _Tp, _Alloc >::end () [inline], [noexcept]
Returns a read/write iterator dat points one past tha last element up in tha list. Iteration is done up in ordinary element order.
Definizzle at line 776 of file stl_list.h.
Referenced by std::list< __inp, __rebind_inp >::back(), std::list< __inp, __rebind_inp >::crbegin(), std::list< __inp, __rebind_inp >::list(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::operator=(), std::operator==(), std::list< __inp, __rebind_inp >::push_back(), std::list< __inp, __rebind_inp >::rbegin(), std::list< __inp, __rebind_inp >::size(), n' std::list< __inp, __rebind_inp >::splice().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::list< _Tp, _Alloc >::end () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha list. Iteration is done up in ordinary element order.
Definizzle at line 785 of file stl_list.h.
template<typename _Tp , typename _Alloc > list< _Tp, _Alloc >::iterator list::erase (iterator__position)
Remove element at given position.
Parameters:
__position Iterator pointin ta element ta be erased.
Returns:
An iterator pointin ta tha next element (or end()).
This function will erase tha element all up in tha given posizzle n' thus shorten tha list by one.
Cuz of tha nature of a list dis operation can be done up in constant time, n' only invalidates iterators/references ta tha element bein removed. Da user be also cautioned dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 109 of file list.tcc.
Referenced by std::list< __inp, __rebind_inp >::erase().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::list< _Tp, _Alloc >::erase (iterator__first, iterator__last) [inline]
Remove a range of elements.
Parameters:
__first Iterator pointin ta tha straight-up original gangsta element ta be erased.
__last Iterator pointin ta one past tha last element ta be erased.
Returns:
An iterator pointin ta tha element pointed ta by last prior ta erasin (or end()).
This function will erase tha elements up in tha range [first,last) n' shorten tha list accordingly.
This operation is linear time up in tha size of tha range n' only invalidates iterators/references ta tha element bein removed. Da user be also cautioned dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 1193 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::list< _Tp, _Alloc >::front () [inline]
Returns a read/write reference ta tha data all up in tha straight-up original gangsta element of tha list.
Definizzle at line 927 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::list< _Tp, _Alloc >::front () const [inline]
Returns a read-only (constant) reference ta tha data all up in tha straight-up original gangsta element of tha list.
Definizzle at line 935 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> allocator_type std::list< _Tp, _Alloc >::get_allocator () const [inline], [noexcept]
Git a cold-ass lil copy of tha memory allocation object.
Definizzle at line 749 of file stl_list.h.
Referenced by std::list< __inp, __rebind_inp >::insert().
template<typename _Tp , typename _Alloc > list< _Tp, _Alloc >::iterator list::insert (iterator__position, const value_type &__x)
Inserts given value tha fuck into list before specified iterator.
Parameters:
__position An iterator tha fuck into tha list.
__x Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given value before tha specified location. Cuz of tha nature of a list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Definizzle at line 99 of file list.tcc.
Referenced by std::list< __inp, __rebind_inp >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::list< _Tp, _Alloc >::insert (iterator__position, value_type &&__x) [inline]
Inserts given rvalue tha fuck into list before specified iterator.
Parameters:
__position An iterator tha fuck into tha list.
__x Data ta be inserted.
Returns:
An iterator dat points ta tha banged data.
This function will bang a cold-ass lil copy of tha given rvalue before tha specified location. Cuz of tha nature of a list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Definizzle at line 1089 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::insert (iterator__p, initializer_list< value_type >__l) [inline]
Inserts tha contentz of a initializer_list tha fuck into list before specified iterator.
Parameters:
__p An iterator tha fuck into tha list.
__l An initializer_list of value_type.
This function will bang copiez of tha data up in tha initializer_list l tha fuck into tha list before tha location specified by p.
This operation is linear up in tha number of elements banged n' do not invalidate iterators n' references.
Definizzle at line 1106 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::insert (iterator__position, size_type__n, const value_type &__x) [inline]
Inserts a fuckin shitload of copiez of given data tha fuck into tha list.
Parameters:
__position An iterator tha fuck into tha list.
__n Number of elements ta be inserted.
__x Data ta be inserted.
This function will bang a specified number of copiez of tha given data before tha location specified by position.
This operation is linear up in tha number of elements banged n' do not invalidate iterators n' references.
Definizzle at line 1123 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>> void std::list< _Tp, _Alloc >::insert (iterator__position, _InputIterator__first, _InputIterator__last) [inline]
Inserts a range tha fuck into tha list.
Parameters:
__position An iterator tha fuck into tha list.
__first An input iterator.
__last An input iterator.
This function will bang copiez of tha data up in tha range [first,last) tha fuck into tha list before tha location specified by position.
This operation is linear up in tha number of elements banged n' do not invalidate iterators n' references.
Definizzle at line 1149 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::list< _Tp, _Alloc >::max_size () const [inline], [noexcept]
Returns tha size() of tha phattest possible list.
Definizzle at line 878 of file stl_list.h.
template<typename _Tp , typename _Alloc > void list::merge (list< _Tp, _Alloc > &&__x)
Merge sorted lists.
Parameters:
__x Sorted list ta merge.
Assumes dat both __x n' dis list is sorted accordin ta operator<(). Merges elementz of __x tha fuck into dis list up in sorted order, leavin __x empty when complete. Elements up in dis list precede elements up in __x dat is equal.
Definizzle at line 288 of file list.tcc.
References std::begin(), std::list< _Tp, _Alloc >::begin(), std::end(), n' std::list< _Tp, _Alloc >::end().
Referenced by std::list< _Tp, _Alloc >::sort().
template<typename _Tp , typename _Alloc > template<typename _StrictWeakOrderin > void list::merge (list< _Tp, _Alloc > &&__x, _StrictWeakOrdering__comp)
Merge sorted lists accordin ta comparison function.
Template Parameters:
_StrictWeakOrdering Comparison function definin sort order.
Parameters:
__x Sorted list ta merge.
__comp Comparison functor.
Assumes dat both __x n' dis list is sorted accordin ta StrictWeakOrdering. Merges elementz of __x tha fuck into dis list up in sorted order, leavin __x empty when complete. Elements up in dis list precede elements up in __x dat is equivalent accordin ta StrictWeakOrdering().
Definizzle at line 322 of file list.tcc.
References std::begin(), std::list< _Tp, _Alloc >::begin(), std::end(), n' std::list< _Tp, _Alloc >::end().
template<typename _Tp , typename _Alloc > list< _Tp, _Alloc > & list::operator= (const list< _Tp, _Alloc > &__x)
List assignment operator. No explicit dtor needed as tha _Base dtor takes care of thangs. Da _Base dtor only erases tha elements, n' note dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Parameters:
__x A list of identical element n' allocator types.
All tha elementz of __x is copied yo, but unlike tha copy constructor, tha allocator object aint copied.
Definizzle at line 185 of file list.tcc.
References std::begin(), std::list< _Tp, _Alloc >::begin(), std::end(), n' std::list< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> list& std::list< _Tp, _Alloc >::operator= (list< _Tp, _Alloc > &&__x) [inline]
List move assignment operator.
Parameters:
__x A list of identical element n' allocator types.
Da contentz of __x is moved tha fuck into dis list (without copying). __x be a valid yo, but unspecified list
Definizzle at line 667 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> list& std::list< _Tp, _Alloc >::operator= (initializer_list< value_type >__l) [inline]
List initializer list assignment operator.
Parameters:
__l An initializer_list of value_type.
Replace tha contentz of tha list wit copiez of tha elements up in tha initializer_list __l. This is linear up in l.size().
Definizzle at line 684 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::pop_back () [inline]
Removes last element. This be a typical stack operation. Well shiiiit, it shrinks tha list by one. Cuz of tha nature of a list dis operation can be done up in constant time, n' only invalidates iterators/references ta tha element bein removed.
Note dat no data is returned, n' if tha last elementz data is needed, it should be retrieved before pop_back() is called.
Definizzle at line 1041 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::pop_front () [inline]
Removes first element. This be a typical stack operation. Well shiiiit, it shrinks tha list by one. Cuz of tha nature of a list dis operation can be done up in constant time, n' only invalidates iterators/references ta tha element bein removed.
Note dat no data is returned, n' if tha straight-up original gangsta elementz data is needed, it should be retrieved before pop_front() is called.
Definizzle at line 1001 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::push_back (const value_type &__x) [inline]
Add data ta tha end of tha list.
Parameters:
__x Data ta be added.
This be a typical stack operation. Da function creates a element all up in tha end of tha list n' assigns tha given data ta it. Cuz of tha nature of a list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Definizzle at line 1015 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::push_front (const value_type &__x) [inline]
Add data ta tha front of tha list.
Parameters:
__x Data ta be added.
This be a typical stack operation. Da function creates a element all up in tha front of tha list n' assigns tha given data ta it. Cuz of tha nature of a list dis operation can be done up in constant time, n' do not invalidate iterators n' references.
Definizzle at line 974 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::list< _Tp, _Alloc >::rbegin () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta tha last element up in tha list. Iteration is done up in reverse element order.
Definizzle at line 794 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::list< _Tp, _Alloc >::rbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha list. Iteration is done up in reverse element order.
Definizzle at line 803 of file stl_list.h.
template<typename _Tp, typename _Alloc > void list::remove (const _Tp &__value)
Remove all elements equal ta value.
Parameters:
__value Da value ta remove.
Removes every last muthafuckin element up in tha list equal ta value. Remainin elements stay up in list order. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 239 of file list.tcc.
References std::__addressof(), std::begin(), n' std::end().
template<typename _Tp , typename _Alloc > template<typename _Predicate > void list::remove_if (_Predicate__pred)
Remove all elements satisfyin a predicate.
Template Parameters:
_Predicate Unary predicate function or object.
Removes every last muthafuckin element up in tha list fo' which tha predicate returns true. Remainin elements stay up in list order. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 392 of file list.tcc.
References std::begin(), n' std::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::list< _Tp, _Alloc >::rend () [inline], [noexcept]
Returns a read/write reverse iterator dat points ta one before tha straight-up original gangsta element up in tha list. Iteration is done up in reverse element order.
Definizzle at line 812 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::list< _Tp, _Alloc >::rend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta one before tha straight-up original gangsta element up in tha list. Iteration is done up in reverse element order.
Definizzle at line 821 of file stl_list.h.
template<typename _Tp , typename _Alloc > void list::resize (size_type__new_size)
Resizes tha list ta tha specified number of elements.
Parameters:
__new_size Number of elements tha list should contain.
This function will resize tha list ta tha specified number of elements. If tha number is smalla than tha listz current size tha list is truncated, otherwise default constructed elements is appended.
Definizzle at line 139 of file list.tcc.
References std::begin(), n' std::end().
template<typename _Tp , typename _Alloc > void list::resize (size_type__new_size, const value_type &__x)
Resizes tha list ta tha specified number of elements.
Parameters:
__new_size Number of elements tha list should contain.
__x Data wit which freshly smoked up elements should be populated.
This function will resize tha list ta tha specified number of elements. If tha number is smalla than tha listz current size tha list is truncated, otherwise tha list is extended n' freshly smoked up elements is populated wit given data.
Definizzle at line 154 of file list.tcc.
References std::begin(), n' std::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::reverse () [inline], [noexcept]
Reverse tha elements up in list. Reverse tha order of elements up in tha list up in linear time.
Definizzle at line 1449 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::list< _Tp, _Alloc >::size () const [inline], [noexcept]
Returns tha number of elements up in tha list.
Definizzle at line 873 of file stl_list.h.
template<typename _Tp , typename _Alloc > void list::sort ()
Sort tha elements. Right back up in yo muthafuckin ass. Sorts tha elementz of dis list up in NlogN time. Equivalent elements remain up in list order.
Definizzle at line 354 of file list.tcc.
References std::begin(), std::list< _Tp, _Alloc >::begin(), std::list< _Tp, _Alloc >::empty(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::splice(), n' std::list< _Tp, _Alloc >::swap().
template<typename _Tp , typename _Alloc > template<typename _StrictWeakOrderin > void list::sort (_StrictWeakOrdering__comp)
Sort tha elements accordin ta comparison function. Right back up in yo muthafuckin ass. Sorts tha elementz of dis list up in NlogN time. Equivalent elements remain up in list order.
Definizzle at line 431 of file list.tcc.
References std::begin(), std::list< _Tp, _Alloc >::begin(), std::list< _Tp, _Alloc >::empty(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::splice(), n' std::list< _Tp, _Alloc >::swap().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::splice (iterator__position, list< _Tp, _Alloc > &&__x) [inline]
Insert contentz of another list.
Parameters:
__position Iterator referencin tha element ta bang before.
__x Source list.
Da elementz of __x is banged up in constant time up in front of tha element referenced by __position. __x becomes a empty list.
Requires dis != __x.
Definizzle at line 1248 of file stl_list.h.
Referenced by std::list< __inp, __rebind_inp >::insert(), n' std::list< _Tp, _Alloc >::sort().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::splice (iterator__position, list< _Tp, _Alloc > &&__x, iterator__i) [inline]
Insert element from another list.
Parameters:
__position Iterator referencin tha element ta bang before.
__x Source list.
__i Iterator referencin tha element ta move.
Removes tha element up in list __x referenced by __i n' bangs it tha fuck into tha current list before __position.
Definizzle at line 1278 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::splice (iterator__position, list< _Tp, _Alloc > &&__x, iterator__first, iterator__last) [inline]
Insert range from another list.
Parameters:
__position Iterator referencin tha element ta bang before.
__x Source list.
__first Iterator referencin tha start of range up in x.
__last Iterator referencin tha end of range up in x.
Removes elements up in tha range [__first,__last) n' bangs dem before __position up in constant time.
Undefined if __position is up in [__first,__last).
Definizzle at line 1314 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::swap (list< _Tp, _Alloc > &__x) [inline]
Swaps data wit another list.
Parameters:
__x A list of tha same element n' allocator types.
This exchanges tha elements between two lists up in constant time. Note dat tha global std::swap() function is specialized such dat std::swap(l1,l2) will feed ta dis function.
Definizzle at line 1210 of file stl_list.h.
Referenced by std::list< __inp, __rebind_inp >::operator=(), std::list< _Tp, _Alloc >::sort(), n' std::swap().
template<typename _Tp , typename _Alloc > void list::unique ()
Remove consecutizzle duplicate elements. For each consecutizzle set of elements wit tha same value, remove all but tha straight-up original gangsta one. Remainin elements stay up in list order. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 267 of file list.tcc.
References std::begin(), n' std::end().
template<typename _Tp , typename _Alloc > template<typename _BinaryPredicate > void list::unique (_BinaryPredicate__binary_pred)
Remove consecutizzle elements satisfyin a predicate.
Template Parameters:
_BinaryPredicate Binary predicate function or object.
For each consecutizzle set of elements [first,last) dat satisfy predicate(first,i) where i be a iterator up in [first,last), remove all but tha straight-up original gangsta one. Remainin elements stay up in list order. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 410 of file list.tcc.
References std::begin(), n' std::end().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.