" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::num_put< _CharT, _OutIta > -
SYNOPSIS
Inherits std::locale::facet.
Public Types
typedef _CharT char_type
typedef _OutIta iter_type
Public Member Functions
num_put (size_t __refs=0)
template<typename _ValueT > _OutIta _M_insert_float (_OutIta __s, ios_base &__io, _CharT __fill, char __mod, _ValueT __v) const
template<typename _ValueT > _OutIta _M_insert_int (_OutIta __s, ios_base &__io, _CharT __fill, _ValueT __v) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, bool __v) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, const void *__v) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, long __v) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, unsigned long __v) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, long long __v) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, unsigned long long __v) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, double __v) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, long double __v) const
Static Public Attributes
static locale::id id
Protected Member Functions
virtual ~num_put ()
void _M_group_float (const char *__grouping, size_t __grouping_size, char_type __sep, const char_type *__p, char_type *__new, char_type *__cs, int &__len) const
void _M_group_int (const char *__grouping, size_t __grouping_size, char_type __sep, ios_base &__io, char_type *__new, char_type *__cs, int &__len) const
template<typename _ValueT > iter_type _M_insert_float (iter_type, ios_base &__io, char_type __fill, char __mod, _ValueT __v) const
template<typename _ValueT > iter_type _M_insert_int (iter_type, ios_base &__io, char_type __fill, _ValueT __v) const
void _M_pad (char_type __fill, streamsize __w, ios_base &__io, char_type *__new, const char_type *__cs, int &__len) const
virtual iter_type do_put (iter_type __s, ios_base &__io, char_type __fill, bool __v) const
virtual iter_type do_put (iter_type __s, ios_base &__io, char_type __fill, long __v) const
virtual iter_type do_put (iter_type __s, ios_base &__io, char_type __fill, unsigned long __v) const
virtual iter_type do_put (iter_type __s, ios_base &__io, char_type __fill, long long __v) const
virtual iter_type do_put (iter_type __s, ios_base &__io, char_type __fill, unsigned long long __v) const
virtual iter_type do_put (iter_type, ios_base &, char_type, double) const
virtual iter_type do_put (iter_type, ios_base &, char_type, long double) const
virtual iter_type do_put (iter_type, ios_base &, char_type, const void *) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Detailed Description
template<typename _CharT, typename _OutIter>class std::num_put< _CharT, _OutIta >
Primary class template num_put.
This facet encapsulates tha code ta convert a number ta a string. Well shiiiit, it is used by tha ostream numeric insertion operators.
Da num_put template uses protected virtual functions ta provide tha actual thangs up in dis biatch. Da hood accessors forward tha call ta tha virtual functions. These virtual functions is hooks fo' pimpers ta implement tha behavior they require from tha num_put facet.
Definizzle at line 2254 of file locale_facets.h.
Member Typedef Documentation
template<typename _CharT , typename _OutIta > typedef _CharT std::num_put< _CharT, _OutIta >::char_type
Public typedefs.
Definizzle at line 2260 of file locale_facets.h.
template<typename _CharT , typename _OutIta > typedef _OutIta std::num_put< _CharT, _OutIta >::iter_type
Public typedefs.
Definizzle at line 2261 of file locale_facets.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _OutIta > std::num_put< _CharT, _OutIta >::num_put (size_t__refs = 0) [inline], [explicit]
Constructor performs initialization. This is tha constructor provided by tha standard.
Parameters:
__refs Passed ta tha base facet class.
Definizzle at line 2275 of file locale_facets.h.
template<typename _CharT , typename _OutIta > virtual std::num_put< _CharT, _OutIta >::~num_put () [inline], [protected], [virtual]
Destructor.
Definizzle at line 2454 of file locale_facets.h.
Member Function Documentation
template<typename _CharT , typename _OutIta > _OutIta std::num_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, bool__v) const [protected], [virtual]
Numeric formatting. These functions do tha work of formattin numeric joints n' insertin dem tha fuck into a stream. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 1089 of file locale_facets.tcc.
References std::ios_base::_M_getloc(), std::ios_base::adjustfield, std::ios_base::boolalpha, std::ios_base::flags(), std::ios_base::left, n' std::ios_base::width().
Referenced by std::num_put< _CharT, _OutIta >::put().
template<typename _CharT , typename _OutIta > virtual iter_type std::num_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, long__v) const [inline], [protected], [virtual]
Numeric formatting. These functions do tha work of formattin numeric joints n' insertin dem tha fuck into a stream. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2474 of file locale_facets.h.
template<typename _CharT , typename _OutIta > virtual iter_type std::num_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, unsigned long__v) const [inline], [protected], [virtual]
Numeric formatting. These functions do tha work of formattin numeric joints n' insertin dem tha fuck into a stream. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2478 of file locale_facets.h.
template<typename _CharT , typename _OutIta > virtual iter_type std::num_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, long long__v) const [inline], [protected], [virtual]
Numeric formatting. These functions do tha work of formattin numeric joints n' insertin dem tha fuck into a stream. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2484 of file locale_facets.h.
template<typename _CharT , typename _OutIta > virtual iter_type std::num_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, unsigned long long__v) const [inline], [protected], [virtual]
Numeric formatting. These functions do tha work of formattin numeric joints n' insertin dem tha fuck into a stream. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2489 of file locale_facets.h.
template<typename _CharT , typename _OutIta > _OutIta std::num_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, double__v) const [protected], [virtual]
Numeric formatting. These functions do tha work of formattin numeric joints n' insertin dem tha fuck into a stream. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 1141 of file locale_facets.tcc.
template<typename _CharT , typename _OutIta > _OutIta std::num_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, long double__v) const [protected], [virtual]
Numeric formatting. These functions do tha work of formattin numeric joints n' insertin dem tha fuck into a stream. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 1155 of file locale_facets.tcc.
template<typename _CharT , typename _OutIta > _OutIta std::num_put< _CharT, _OutIta >::do_put (iter_type__s, ios_base &__io, char_type__fill, const void *__v) const [protected], [virtual]
Numeric formatting. These functions do tha work of formattin numeric joints n' insertin dem tha fuck into a stream. This function be a hook fo' derived classes ta chizzle tha value returned.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 1162 of file locale_facets.tcc.
References std::ios_base::flags(), std::ios_base::hex, n' std::ios_base::uppercase.
template<typename _CharT , typename _OutIta > iter_type std::num_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, bool__v) const [inline]
Numeric formatting. Formats tha boolean v n' bangs it tha fuck into a stream. Well shiiiit, it do so by callin num_put::do_put().
If ios_base::boolalpha is set, writes ctype<CharT>::truename() or ctype<CharT>::falsename(). Otherwise formats v as a int.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2293 of file locale_facets.h.
References std::num_put< _CharT, _OutIta >::do_put().
template<typename _CharT , typename _OutIta > iter_type std::num_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, long__v) const [inline]
Numeric formatting. Formats tha integral value v n' bangs it tha fuck into a stream. Well shiiiit, it do so by callin num_put::do_put().
Formattin be affected by tha flag settings up in io.
Da basic format be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, formats like tha printf o specifier. Else if equal ta ios_base::hex, formats like x or X wit ios_base::uppercase unset or set respectively. Otherwise, formats like d, ld, lld fo' signed n' u, lu, llu fo' unsigned joints. Note dat if both oct n' hex is set, neither will take effect.
If ios_base::showpos is set, '+' is output before positizzle joints. If ios_base::showbase is set, '0' precedes octal joints (except 0) n' '0[xX]' precedes hex joints.
Da decimal point characta used is numpunct::decimal_point(). Thousandz separators is banged accordin ta numpunct::grouping() n' numpunct::thousands_sep().
If io.width() is non-zero, enough fill charactas is banged ta make tha result at least dat wide. If (io.flags() & ios_base::adjustfield) == ios_base::left, result is padded all up in tha end. If ios_base::internal, then paddin occurs immediately afta either a '+' or '-' or afta '0x' or '0X'. Otherwise, paddin occurs all up in tha beginning.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2335 of file locale_facets.h.
References std::num_put< _CharT, _OutIta >::do_put().
template<typename _CharT , typename _OutIta > iter_type std::num_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, unsigned long__v) const [inline]
Numeric formatting. Formats tha integral value v n' bangs it tha fuck into a stream. Well shiiiit, it do so by callin num_put::do_put().
Formattin be affected by tha flag settings up in io.
Da basic format be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, formats like tha printf o specifier. Else if equal ta ios_base::hex, formats like x or X wit ios_base::uppercase unset or set respectively. Otherwise, formats like d, ld, lld fo' signed n' u, lu, llu fo' unsigned joints. Note dat if both oct n' hex is set, neither will take effect.
If ios_base::showpos is set, '+' is output before positizzle joints. If ios_base::showbase is set, '0' precedes octal joints (except 0) n' '0[xX]' precedes hex joints.
Da decimal point characta used is numpunct::decimal_point(). Thousandz separators is banged accordin ta numpunct::grouping() n' numpunct::thousands_sep().
If io.width() is non-zero, enough fill charactas is banged ta make tha result at least dat wide. If (io.flags() & ios_base::adjustfield) == ios_base::left, result is padded all up in tha end. If ios_base::internal, then paddin occurs immediately afta either a '+' or '-' or afta '0x' or '0X'. Otherwise, paddin occurs all up in tha beginning.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2339 of file locale_facets.h.
References std::num_put< _CharT, _OutIta >::do_put().
template<typename _CharT , typename _OutIta > iter_type std::num_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, long long__v) const [inline]
Numeric formatting. Formats tha integral value v n' bangs it tha fuck into a stream. Well shiiiit, it do so by callin num_put::do_put().
Formattin be affected by tha flag settings up in io.
Da basic format be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, formats like tha printf o specifier. Else if equal ta ios_base::hex, formats like x or X wit ios_base::uppercase unset or set respectively. Otherwise, formats like d, ld, lld fo' signed n' u, lu, llu fo' unsigned joints. Note dat if both oct n' hex is set, neither will take effect.
If ios_base::showpos is set, '+' is output before positizzle joints. If ios_base::showbase is set, '0' precedes octal joints (except 0) n' '0[xX]' precedes hex joints.
Da decimal point characta used is numpunct::decimal_point(). Thousandz separators is banged accordin ta numpunct::grouping() n' numpunct::thousands_sep().
If io.width() is non-zero, enough fill charactas is banged ta make tha result at least dat wide. If (io.flags() & ios_base::adjustfield) == ios_base::left, result is padded all up in tha end. If ios_base::internal, then paddin occurs immediately afta either a '+' or '-' or afta '0x' or '0X'. Otherwise, paddin occurs all up in tha beginning.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2345 of file locale_facets.h.
References std::num_put< _CharT, _OutIta >::do_put().
template<typename _CharT , typename _OutIta > iter_type std::num_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, unsigned long long__v) const [inline]
Numeric formatting. Formats tha integral value v n' bangs it tha fuck into a stream. Well shiiiit, it do so by callin num_put::do_put().
Formattin be affected by tha flag settings up in io.
Da basic format be affected by tha value of io.flags() & ios_base::basefield. If equal ta ios_base::oct, formats like tha printf o specifier. Else if equal ta ios_base::hex, formats like x or X wit ios_base::uppercase unset or set respectively. Otherwise, formats like d, ld, lld fo' signed n' u, lu, llu fo' unsigned joints. Note dat if both oct n' hex is set, neither will take effect.
If ios_base::showpos is set, '+' is output before positizzle joints. If ios_base::showbase is set, '0' precedes octal joints (except 0) n' '0[xX]' precedes hex joints.
Da decimal point characta used is numpunct::decimal_point(). Thousandz separators is banged accordin ta numpunct::grouping() n' numpunct::thousands_sep().
If io.width() is non-zero, enough fill charactas is banged ta make tha result at least dat wide. If (io.flags() & ios_base::adjustfield) == ios_base::left, result is padded all up in tha end. If ios_base::internal, then paddin occurs immediately afta either a '+' or '-' or afta '0x' or '0X'. Otherwise, paddin occurs all up in tha beginning.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2349 of file locale_facets.h.
References std::num_put< _CharT, _OutIta >::do_put().
template<typename _CharT , typename _OutIta > iter_type std::num_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, double__v) const [inline]
Numeric formatting. Formats tha floatin point value v n' bangs it tha fuck into a stream. Well shiiiit, it do so by callin num_put::do_put().
Formattin be affected by tha flag settings up in io.
Da basic format be affected by tha value of io.flags() & ios_base::floatfield. If equal ta ios_base::fixed, formats like tha printf f specifier. Else if equal ta ios_base::scientific, formats like e or E wit ios_base::uppercase unset or set respectively. Otherwise, formats like g or G dependin on uppercase. Note dat if both fixed n' scientistical is set, tha effect will also be like g or G.
Da output precision is given by io.precision(). This precision is capped at numeric_limits::digits10 + 2 (different fo' double n' long double). Da default precision is 6.
If ios_base::showpos is set, '+' is output before positizzle joints. If ios_base::showpoint is set, a thugged-out decimal point will always be output.
Da decimal point characta used is numpunct::decimal_point(). Thousandz separators is banged accordin ta numpunct::grouping() n' numpunct::thousands_sep().
If io.width() is non-zero, enough fill charactas is banged ta make tha result at least dat wide. If (io.flags() & ios_base::adjustfield) == ios_base::left, result is padded all up in tha end. If ios_base::internal, then paddin occurs immediately afta either a '+' or '-' or afta '0x' or '0X'. Otherwise, paddin occurs all up in tha beginning.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2398 of file locale_facets.h.
References std::num_put< _CharT, _OutIta >::do_put().
template<typename _CharT , typename _OutIta > iter_type std::num_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, long double__v) const [inline]
Numeric formatting. Formats tha floatin point value v n' bangs it tha fuck into a stream. Well shiiiit, it do so by callin num_put::do_put().
Formattin be affected by tha flag settings up in io.
Da basic format be affected by tha value of io.flags() & ios_base::floatfield. If equal ta ios_base::fixed, formats like tha printf f specifier. Else if equal ta ios_base::scientific, formats like e or E wit ios_base::uppercase unset or set respectively. Otherwise, formats like g or G dependin on uppercase. Note dat if both fixed n' scientistical is set, tha effect will also be like g or G.
Da output precision is given by io.precision(). This precision is capped at numeric_limits::digits10 + 2 (different fo' double n' long double). Da default precision is 6.
If ios_base::showpos is set, '+' is output before positizzle joints. If ios_base::showpoint is set, a thugged-out decimal point will always be output.
Da decimal point characta used is numpunct::decimal_point(). Thousandz separators is banged accordin ta numpunct::grouping() n' numpunct::thousands_sep().
If io.width() is non-zero, enough fill charactas is banged ta make tha result at least dat wide. If (io.flags() & ios_base::adjustfield) == ios_base::left, result is padded all up in tha end. If ios_base::internal, then paddin occurs immediately afta either a '+' or '-' or afta '0x' or '0X'. Otherwise, paddin occurs all up in tha beginning.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2402 of file locale_facets.h.
References std::num_put< _CharT, _OutIta >::do_put().
template<typename _CharT , typename _OutIta > iter_type std::num_put< _CharT, _OutIta >::put (iter_type__s, ios_base &__io, char_type__fill, const void *__v) const [inline]
Numeric formatting. Formats tha pointa value v n' bangs it tha fuck into a stream. Well shiiiit, it do so by callin num_put::do_put().
This function formats v as a unsigned long wit ios_base::hex n' ios_base::showbase set.
Parameters:
__s Stream ta write to.
__io Source of locale n' flags.
__fill Char_type ta use fo' filling.
__v Value ta format n' insert.
Returns:
Iterator afta writing.
Definizzle at line 2423 of file locale_facets.h.
References std::num_put< _CharT, _OutIta >::do_put().
Member Data Documentation
template<typename _CharT , typename _OutIta > locale::id std::num_put< _CharT, _OutIta >::id [static]
Numpunct facet id.
Definizzle at line 2265 of file locale_facets.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.