" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::remove_extent< _Tp > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp>struct std::remove_extent< _Tp >"
remove_extent 
.PP
Definizzle at line 1624 of file type_traits\&.

.SH "Author"
.PP 
Generated automatically by Doxygen fo' libstdc++ from tha source code\&.
