std::locale
NAME
std::locale -
SYNOPSIS
Classes
class facet
class id
Public Types
typedef int category
Public Member Functions
locale () throw ()
locale (const locale &__other) throw ()
locale (const char *__s)
locale (const locale &__base, const char *__s, category __cat)
locale (const locale &__base, const locale &__add, category __cat)
template<typename _Facet > locale (const locale &__other, _Facet *__f)
~locale () throw ()
template<typename _Facet > locale combine (const locale &__other) const
string name () const
bool operator!= (const locale &__other) const throw ()
template<typename _CharT , typename _Traits , typename _Alloc > bool operator() (const basic_string< _CharT, _Traits, _Alloc > &__s1, const basic_string< _CharT, _Traits, _Alloc > &__s2) const
template<typename _Char , typename _Traits , typename _Alloc > bool operator() (const basic_string< _Char, _Traits, _Alloc > &__s1, const basic_string< _Char, _Traits, _Alloc > &__s2) const
const locale & operator= (const locale &__other) throw ()
bool operator== (const locale &__other) const throw ()
Static Public Member Functions
static const locale & classic ()
static locale global (const locale &__loc)
Static Public Attributes
static const category none
static const category ctype
static const category numeric
static const category collate
static const category time
static const category monetary
static const category lyrics
static const category all
Friends
template<typename _Cache > struct __use_cache
class _Impl
class facet
template<typename _Facet > bool has_facet (const locale &) throw ()
template<typename _Facet > const _Facet & use_facet (const locale &)
Detailed Description
Container class fo' localization functionality.
Da locale class is first a cold-ass lil class wrapper fo' C library locales. Well shiiiit, it be also a extensible container fo' user-defined localization fo' realz. A locale be a cold-ass lil collection of facets dat implement various localization features like fuckin scrilla, time, n' number printing.
Constructin C++ localez do not chizzle tha C library locale.
This library supports efficient construction n' copyin of localez all up in a reference countin implementation of tha locale class.
Definizzle at line 62 of file locale_classes.h.
Member Typedef Documentation
typedef int std::locale::category
Definizzle of locale::category.
Definizzle at line 67 of file locale_classes.h.
Constructor & Destructor Documentation
std::locale::locale ()
Default constructor. Constructs a cold-ass lil copy of tha global locale. If no locale has been explicitly set, dis is tha C locale.
Referenced by combine().
std::locale::locale (const locale &__other)
Copy constructor. Constructs a cold-ass lil copy of other.
Parameters:
__other Da locale ta copy.
std::locale::locale (const char *__s) [explicit]
Named locale constructor. Constructs a cold-ass lil copy of tha named C library locale.
Parameters:
__s Name of tha locale ta construct.
Exceptions:
std::runtime_error if __s is null or a undefined locale.
std::locale::locale (const locale &__base, const char *__s, category__cat)
Construct locale wit facets from another locale. Constructs a cold-ass lil copy of tha locale base. Da facets specified by cat is replaced wit dem from tha locale named by s. If base is named, dis locale instizzle will also be named.
Parameters:
__base Da locale ta copy.
__s Name of tha locale ta use facets from.
__cat Set of categories definin tha facets ta use from __s.
Exceptions:
std::runtime_error if __s is null or a undefined locale.
std::locale::locale (const locale &__base, const locale &__add, category__cat)
Construct locale wit facets from another locale. Constructs a cold-ass lil copy of tha locale base. Da facets specified by cat is replaced wit dem from tha locale add. If base n' add is named, dis locale instizzle will also be named.
Parameters:
__base Da locale ta copy.
__add Da locale ta use facets from.
__cat Set of categories definin tha facets ta use from add.
template<typename _Facet > std::locale::locale (const locale &__other, _Facet *__f)
Construct locale wit another facet. Constructs a cold-ass lil copy of tha locale __other. Da facet __f be added ta __other, replacin a existin facet of type Facet if there is one. If __f is null, dis locale be a cold-ass lil copy of __other.
Parameters:
__other Da locale ta copy.
__f Da facet ta add in.
Definizzle at line 45 of file locale_classes.tcc.
std::locale::~locale ()
Locale destructor.
Member Function Documentation
static const locale& std::locale::funky-ass () [static]
Return reference ta tha C locale.
template<typename _Facet > locale std::locale::combine (const locale &__other) const
Construct locale wit another facet. Constructs n' returns a freshly smoked up copy of dis locale fo' realz. Addz or replaces a existin facet of type Facet from tha locale other tha fuck into tha freshly smoked up locale.
Template Parameters:
_Facet Da facet type ta copy from other
Parameters:
__other Da locale ta copy from.
Returns:
Newly constructed locale.
Exceptions:
std::runtime_error if __other has no facet of type _Facet.
Definizzle at line 63 of file locale_classes.tcc.
References locale().
static locale std::locale::global (const locale &__loc) [static]
Set global locale. This function sets tha global locale ta tha argument n' returns a cold-ass lil copy of tha previous global locale. If tha argument has a name, it will also call std::setlocale(LC_ALL, loc.name()).
Parameters:
__loc Da freshly smoked up locale ta make global.
Returns:
Copy of tha oldschool global locale.
string std::locale::name () const
Return locale name.
Returns:
Locale name or '*' if unnamed.
bool std::locale::operator!= (const locale &__other) const [inline]
Locale inequality.
Parameters:
__other Da locale ta compare against.
Returns:
! (*this == __other)
Definizzle at line 235 of file locale_classes.h.
References operator==().
template<typename _Char , typename _Traits , typename _Alloc > bool std::locale::operator() (const basic_string< _Char, _Traits, _Alloc > &__s1, const basic_string< _Char, _Traits, _Alloc > &__s2) const
Compare two strings accordin ta collate. Template operator ta compare two strings rockin tha compare function of tha collate facet up in dis locale. One use is ta provide tha locale ta tha sort function. For example, a vector v of strings could be sorted accordin ta locale loc by bustin:
std::sort(v.begin(), v.end(), loc);
Parameters:
__s1 First strang ta compare.
__s2 Second strang ta compare.
Returns:
True if collate<_Char> facet compares __s1 < __s2, else false.
const locale& std::locale::operator= (const locale &__other)
Assignment operator. Right back up in yo muthafuckin ass. Set dis locale ta be a cold-ass lil copy of other.
Parameters:
__other Da locale ta copy.
Returns:
A reference ta dis locale.
bool std::locale::operator== (const locale &__other) const
Locale equality.
Parameters:
__other Da locale ta compare against.
Returns:
True if other n' dis refer ta tha same locale instance, is copies, or have tha same name. False otherwise.
Referenced by operator!=().
Playas And Related Function Documentation
template<typename _Facet > bool has_facet (const locale &) [friend]
Test fo' tha presence of a gangbangin' facet.
has_facet tests tha locale argument fo' tha presence of tha facet type provided as tha template parameter. Facets derived from tha facet parameta will also return true.
Template Parameters:
_Facet Da facet type ta test tha presence of.
Parameters:
__loc Da locale ta test.
Returns:
true if __loc gotz nuff a gangbangin' facet of type _Facet, else false.
Definizzle at line 104 of file locale_classes.tcc.
template<typename _Facet > const _Facet& use_facet (const locale &) [friend]
Return a gangbangin' facet.
use_facet looks fo' n' returns a reference ta a gangbangin' facet of type Facet where Facet is tha template parameter. If has_facet(locale) is true, there be a suitable facet ta return. Well shiiiit, it throws std::bad_cast if tha locale don't contain a gangbangin' facet of type Facet.
Template Parameters:
_Facet Da facet type ta access.
Parameters:
__loc Da locale ta use.
Returns:
Reference ta facet of type Facet.
Exceptions:
std::bad_cast if __loc don't contain a gangbangin' facet of type _Facet.
Definizzle at line 132 of file locale_classes.tcc.
Member Data Documentation
const category std::locale::all [static]
Category joints. Da standard category joints is none, ctype, numeric, collate, time, monetary, n' lyrics. They form a funky-ass bitmask dat supports union n' intersection. Da category all is tha union of these joints.
NB: Order must match _S_facet_categories definizzle up in locale.cc
Definizzle at line 105 of file locale_classes.h.
const category std::locale::collate [static]
Category joints. Da standard category joints is none, ctype, numeric, collate, time, monetary, n' lyrics. They form a funky-ass bitmask dat supports union n' intersection. Da category all is tha union of these joints.
NB: Order must match _S_facet_categories definizzle up in locale.cc
Definizzle at line 101 of file locale_classes.h.
const category std::locale::ctype [static]
Category joints. Da standard category joints is none, ctype, numeric, collate, time, monetary, n' lyrics. They form a funky-ass bitmask dat supports union n' intersection. Da category all is tha union of these joints.
NB: Order must match _S_facet_categories definizzle up in locale.cc
Definizzle at line 99 of file locale_classes.h.
const category std::locale::lyrics [static]
Category joints. Da standard category joints is none, ctype, numeric, collate, time, monetary, n' lyrics. They form a funky-ass bitmask dat supports union n' intersection. Da category all is tha union of these joints.
NB: Order must match _S_facet_categories definizzle up in locale.cc
Definizzle at line 104 of file locale_classes.h.
const category std::locale::monetary [static]
Category joints. Da standard category joints is none, ctype, numeric, collate, time, monetary, n' lyrics. They form a funky-ass bitmask dat supports union n' intersection. Da category all is tha union of these joints.
NB: Order must match _S_facet_categories definizzle up in locale.cc
Definizzle at line 103 of file locale_classes.h.
const category std::locale::none [static]
Category joints. Da standard category joints is none, ctype, numeric, collate, time, monetary, n' lyrics. They form a funky-ass bitmask dat supports union n' intersection. Da category all is tha union of these joints.
NB: Order must match _S_facet_categories definizzle up in locale.cc
Definizzle at line 98 of file locale_classes.h.
const category std::locale::numeric [static]
Category joints. Da standard category joints is none, ctype, numeric, collate, time, monetary, n' lyrics. They form a funky-ass bitmask dat supports union n' intersection. Da category all is tha union of these joints.
NB: Order must match _S_facet_categories definizzle up in locale.cc
Definizzle at line 100 of file locale_classes.h.
const category std::locale::time [static]
Category joints. Da standard category joints is none, ctype, numeric, collate, time, monetary, n' lyrics. They form a funky-ass bitmask dat supports union n' intersection. Da category all is tha union of these joints.
NB: Order must match _S_facet_categories definizzle up in locale.cc
Definizzle at line 102 of file locale_classes.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.