" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::basic_regex< _Ch_type, _Rx_traits > -
SYNOPSIS
Public Types
typedef
regex_constants::syntax_option_type flag_type"
typedef traits_type::locale_type locale_type
typedef traits_type::string_type string_type
typedef _Rx_traits traits_type
typedef _Ch_type value_type
Public Member Functions
basic_regex ()
basic_regex (const _Ch_type *__p, flag_type __f=ECMAScript)
basic_regex (const _Ch_type *__p, std::size_t __len, flag_type __f)
basic_regex (const basic_regex &__rhs)
basic_regex (const basic_regex &&__rhs) noexcept
template<typename _Ch_traits , typename _Ch_alloc > basic_regex (const std::basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, flag_type __f=ECMAScript)
template<typename _InputIterator > basic_regex (_InputIterator __first, _InputIterator __last, flag_type __f=ECMAScript)
basic_regex (initializer_list< _Ch_type > __l, flag_type __f=ECMAScript)
~basic_regex ()
const __detail::_AutomatonPtr & _M_get_automaton () const
basic_regex & assign (const basic_regex &__rhs)
basic_regex & assign (basic_regex &&__rhs) noexcept
basic_regex & assign (const _Ch_type *__p, flag_type __flags=ECMAScript)
basic_regex & assign (const _Ch_type *__p, std::size_t __len, flag_type __flags)
template<typename _Ch_typeraits , typename _Alloc > basic_regex & assign (const basic_string< _Ch_type, _Ch_typeraits, _Alloc > &__s, flag_type __flags=ECMAScript)
template<typename _InputIterator > basic_regex & assign (_InputIterator __first, _InputIterator __last, flag_type __flags=ECMAScript)
basic_regex & assign (initializer_list< _Ch_type > __l, flag_type __flags=ECMAScript)
flag_type flags () const
locale_type getloc () const
locale_type imbue (locale_type __loc)
unsigned int mark_count () const
basic_regex & operator= (const basic_regex &__rhs)
basic_regex & operator= (basic_regex &&__rhs) noexcept
basic_regex & operator= (const _Ch_type *__p)
template<typename _Ch_typeraits , typename _Alloc > basic_regex & operator= (const basic_string< _Ch_type, _Ch_typeraits, _Alloc > &__s)
void swap (basic_regex &__rhs)
Static Public Attributes
Constants
std [28.8.1](1)
static constexpr flag_type icase
static constexpr flag_type nosubs
static constexpr flag_type optimize
static constexpr flag_type collate
static constexpr flag_type ECMAScript
static constexpr flag_type basic
static constexpr flag_type extended
static constexpr flag_type awk
static constexpr flag_type grep
static constexpr flag_type egrep
Protected Attributes
__detail::_AutomatonPtr _M_automaton
flag_type _M_flags
_Rx_traits _M_traits
Detailed Description
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>>class std::basic_regex< _Ch_type, _Rx_traits >
Objectz of specializationz of dis class represent regular expressions constructed from sequencez of characta type _Ch_type.
Storage fo' tha regular expression be allocated n' deallocated as necessary by tha member functionz of dis class.
Definizzle at line 335 of file regex.h.
Constructor & Destructor Documentation
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> std::basic_regex< _Ch_type, _Rx_traits >::basic_regex () [inline]
Constructs a funky-ass basic regular expression dat do not match any characta sequence.
Definizzle at line 367 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> std::basic_regex< _Ch_type, _Rx_traits >::basic_regex (const _Ch_type *__p, flag_type__f = ECMAScript) [inline], [explicit]
Constructs a funky-ass basic regular expression from tha sequence [__p, __p + char_traits<_Ch_type>::length(__p)) interpreted accordin ta tha flags up in __f.
Parameters:
__p A pointa ta tha start of a C-style null-terminated strang containin a regular expression.
__f Flags indicatin tha syntax rulez n' options.
Exceptions:
regex_error if __p aint a valid regular expression.
Definizzle at line 385 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> std::basic_regex< _Ch_type, _Rx_traits >::basic_regex (const _Ch_type *__p, std::size_t__len, flag_type__f) [inline]
Constructs a funky-ass basic regular expression from tha sequence [p, p + len) interpreted accordin ta tha flags up in f.
Parameters:
__p A pointa ta tha start of a strang containin a regular expression.
__len Da length of tha strang containin tha regular expression.
__f Flags indicatin tha syntax rulez n' options.
Exceptions:
regex_error if __p aint a valid regular expression.
Definizzle at line 403 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> std::basic_regex< _Ch_type, _Rx_traits >::basic_regex (const basic_regex< _Ch_type, _Rx_traits > &__rhs) [inline]
Copy-constructs a funky-ass basic regular expression.
Parameters:
__rhs A regex object.
Definizzle at line 413 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> std::basic_regex< _Ch_type, _Rx_traits >::basic_regex (const basic_regex< _Ch_type, _Rx_traits > &&__rhs) [inline], [noexcept]
Move-constructs a funky-ass basic regular expression.
Parameters:
__rhs A regex object.
Definizzle at line 423 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> template<typename _Ch_traits , typename _Ch_alloc > std::basic_regex< _Ch_type, _Rx_traits >::basic_regex (const std::basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, flag_type__f = ECMAScript) [inline], [explicit]
Constructs a funky-ass basic regular expression from tha strang s interpreted accordin ta tha flags up in f.
Parameters:
__s A strang containin a regular expression.
__f Flags indicatin tha syntax rulez n' options.
Exceptions:
regex_error if __s aint a valid regular expression.
Definizzle at line 439 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> template<typename _InputIterator > std::basic_regex< _Ch_type, _Rx_traits >::basic_regex (_InputIterator__first, _InputIterator__last, flag_type__f = ECMAScript) [inline]
Constructs a funky-ass basic regular expression from tha range [first, last) interpreted accordin ta tha flags up in f.
Parameters:
__first Da start of a range containin a valid regular expression.
__last Da end of a range containin a valid regular expression.
__f Da format flagz of tha regular expression.
Exceptions:
regex_error if [__first, __last) aint a valid regular expression.
Definizzle at line 461 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> std::basic_regex< _Ch_type, _Rx_traits >::basic_regex (initializer_list< _Ch_type >__l, flag_type__f = ECMAScript) [inline]
Constructs a funky-ass basic regular expression from a initializer list.
Parameters:
__l Da initializer list.
__f Da format flagz of tha regular expression.
Exceptions:
regex_error if __l aint a valid regular expression.
Definizzle at line 475 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> std::basic_regex< _Ch_type, _Rx_traits >::~basic_regex () [inline]
Destroys a funky-ass basic regular expression.
Definizzle at line 485 of file regex.h.
Member Function Documentation
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::assign (const basic_regex< _Ch_type, _Rx_traits > &__rhs) [inline]
the real assignment operator.
Parameters:
__rhs Another regular expression object.
Definizzle at line 531 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::swap().
Referenced by std::basic_regex< _Ch_type, _Rx_traits >::assign(), n' std::basic_regex< _Ch_type, _Rx_traits >::operator=().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::assign (basic_regex< _Ch_type, _Rx_traits > &&__rhs) [inline], [noexcept]
Da move-assignment operator.
Parameters:
__rhs Another regular expression object.
Definizzle at line 544 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::swap().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::assign (const _Ch_type *__p, flag_type__flags = ECMAScript) [inline]
Assigns a freshly smoked up regular expression ta a regex object from a C-style null-terminated strang containin a regular expression pattern.
Parameters:
__p A pointa ta a C-style null-terminated strang containin a regular expression pattern.
__flags Syntax option flags.
Exceptions:
regex_error if __p do not contain a valid regular expression pattern interpreted accordin ta __flags. If regex_error is thrown, *this remains unchanged.
Definizzle at line 565 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::assign().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::assign (const _Ch_type *__p, std::size_t__len, flag_type__flags) [inline]
Assigns a freshly smoked up regular expression ta a regex object from a C-style strang containin a regular expression pattern.
Parameters:
__p A pointa ta a C-style strang containin a regular expression pattern.
__len Da length of tha regular expression pattern string.
__flags Syntax option flags.
Exceptions:
regex_error if p do not contain a valid regular expression pattern interpreted accordin ta __flags. If regex_error is thrown, *this remains unchanged.
Definizzle at line 582 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::assign().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> template<typename _Ch_typeraits , typename _Alloc > basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::assign (const basic_string< _Ch_type, _Ch_typeraits, _Alloc > &__s, flag_type__flags = ECMAScript) [inline]
Assigns a freshly smoked up regular expression ta a regex object from a strang containin a regular expression pattern.
Parameters:
__s A strang containin a regular expression pattern.
__flags Syntax option flags.
Exceptions:
regex_error if __s do not contain a valid regular expression pattern interpreted accordin ta __flags. If regex_error is thrown, *this remains unchanged.
Definizzle at line 598 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::swap().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> template<typename _InputIterator > basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::assign (_InputIterator__first, _InputIterator__last, flag_type__flags = ECMAScript) [inline]
Assigns a freshly smoked up regular expression ta a regex object.
Parameters:
__first Da start of a range containin a valid regular expression.
__last Da end of a range containin a valid regular expression.
__flags Syntax option flags.
Exceptions:
regex_error if p do not contain a valid regular expression pattern interpreted accordin ta __flags. If regex_error is thrown, tha object remains unchanged.
Definizzle at line 621 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::assign().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::assign (initializer_list< _Ch_type >__l, flag_type__flags = ECMAScript) [inline]
Assigns a freshly smoked up regular expression ta a regex object.
Parameters:
__l An initializer list representin a regular expression.
__flags Syntax option flags.
Exceptions:
regex_error if __l do not contain a valid regular expression pattern interpreted accordin ta __flags. If regex_error is thrown, tha object remains unchanged.
Definizzle at line 637 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::assign().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> flag_type std::basic_regex< _Ch_type, _Rx_traits >::flags () const [inline]
Gets tha flags used ta construct tha regular expression or up in tha last call ta assign().
Definizzle at line 654 of file regex.h.
Referenced by std::basic_regex< _Ch_type, _Rx_traits >::operator=().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> locale_type std::basic_regex< _Ch_type, _Rx_traits >::getloc () const [inline]
Gets tha locale currently imbued up in tha regular expression object.
Definizzle at line 672 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> locale_type std::basic_regex< _Ch_type, _Rx_traits >::imbue (locale_type__loc) [inline]
Imbues tha regular expression object wit tha given locale.
Parameters:
__loc A locale.
Definizzle at line 664 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> unsigned int std::basic_regex< _Ch_type, _Rx_traits >::mark_count () const [inline]
Gets tha number of marked subexpressions within tha regular expression.
Definizzle at line 646 of file regex.h.
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::operator= (const basic_regex< _Ch_type, _Rx_traits > &__rhs) [inline]
Assigns one regular expression ta another.
Definizzle at line 492 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::assign().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::operator= (basic_regex< _Ch_type, _Rx_traits > &&__rhs) [inline], [noexcept]
Move-assigns one regular expression ta another.
Definizzle at line 499 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::assign().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::operator= (const _Ch_type *__p) [inline]
Replaces a regular expression wit a freshly smoked up one constructed from a C-style null-terminated string.
Parameters:
__p A pointa ta tha start of a null-terminated C-style strang containin a regular expression.
Definizzle at line 510 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::assign(), n' std::basic_regex< _Ch_type, _Rx_traits >::flags().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> template<typename _Ch_typeraits , typename _Alloc > basic_regex& std::basic_regex< _Ch_type, _Rx_traits >::operator= (const basic_string< _Ch_type, _Ch_typeraits, _Alloc > &__s) [inline]
Replaces a regular expression wit a freshly smoked up one constructed from a string.
Parameters:
__s A pointa ta a strang containin a regular expression.
Definizzle at line 521 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::assign(), n' std::basic_regex< _Ch_type, _Rx_traits >::flags().
template<typename _Ch_type, typename _Rx_traits = regex_traits<_Ch_type>> void std::basic_regex< _Ch_type, _Rx_traits >::swap (basic_regex< _Ch_type, _Rx_traits > &__rhs) [inline]
Swaps tha contentz of two regular expression objects.
Parameters:
__rhs Another regular expression object.
Definizzle at line 682 of file regex.h.
Referenced by std::basic_regex< _Ch_type, _Rx_traits >::assign(), n' std::swap().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.