" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::match_results< _Bi_iter, _Alloc > -
SYNOPSIS
Inherits std::vector< sub_match< _Bi_ita >, _Alloc >.
Public Member Functions
bool ready () const
Private Types
typedef
_Alloc_traits::const_pointa const_pointer"
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator"
typedef _Base::pointa pointer
typedef std::reverse_iterator
< iterator > reverse_iterator"
Private Member Functions
pointa _M_allocate (size_t __n)
pointa _M_allocate_and_copy (size_type __n, _ForwardIterator __first, _ForwardIterator __last)
void _M_assign_aux (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
void _M_assign_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
void _M_assign_dispatch (_Integer __n, _Integer __val, __true_type)
void _M_assign_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
size_type _M_check_len (size_type __n, const char *__s) const
void _M_deallocate (pointa __p, size_t __n)
void _M_default_append (size_type __n)
void _M_default_initialize (size_type __n)
void _M_emplace_back_aux (_Args &&...__args)
void _M_erase_at_end (pointa __pos)
void _M_fill_assign (size_type __n, const value_type &__val)
void _M_fill_initialize (size_type __n, const value_type &__value)
void _M_fill_insert (iterator __pos, size_type __n, const value_type &__x)
_Tp_alloc_type & _M_get_Tp_allocator () noexcept
const _Tp_alloc_type & _M_get_Tp_allocator () const noexcept
void _M_initialize_dispatch (_Integer __n, _Integer __value, __true_type)
void _M_initialize_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
void _M_insert_aux (iterator __position, _Args &&...__args)
void _M_insert_dispatch (iterator __pos, _Integer __n, _Integer __val, __true_type)
void _M_insert_dispatch (iterator __pos, _InputIterator __first, _InputIterator __last, __false_type)
void _M_range_check (size_type __n) const
void _M_range_initialize (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
void _M_range_initialize (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
void _M_range_insert (iterator __pos, _InputIterator __first, _InputIterator __last, std::input_iterator_tag)
void _M_range_insert (iterator __pos, _ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
bool _M_shrink_to_fit ()
void assign (size_type __n, const value_type &__val)
void assign (_InputIterator __first, _InputIterator __last)
void assign (initializer_list< value_type > __l)
reference at (size_type __n)
const_reference at (size_type __n) const
reference back ()
const_reference back () const
iterator begin () noexcept
size_type capacity () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
sub_match< _Bi_ita > * data () noexcept
const sub_match< _Bi_ita > * data () const noexcept
iterator emplace (iterator __position, _Args &&...__args)
void emplace_back (_Args &&...__args)
iterator end () noexcept
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
reference front ()
const_reference front () const
iterator insert (iterator __position, const value_type &__x)
iterator insert (iterator __position, value_type &&__x)
void insert (iterator __position, initializer_list< value_type > __l)
void insert (iterator __position, size_type __n, const value_type &__x)
void insert (iterator __position, _InputIterator __first, _InputIterator __last)
reference operator[] (size_type __n)
const_reference operator[] (size_type __n) const
void pop_back ()
void push_back (const value_type &__x)
void push_back (value_type &&__x)
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
void reserve (size_type __n)
void resize (size_type __new_size)
void resize (size_type __new_size, const value_type &__x)
void shrink_to_fit ()
void swap (vector &__x) noexcept(_Alloc_traits::_S_nothrow_swap())
Private Attributes
_Vector_impl _M_impl
Friends
class __detail::_SpecializedResults< _Bi_iter, _Alloc >
10.? Public Types
typedef _Alloc allocator_type
typedef sub_match< _Bi_ita > value_type
typedef const value_type & const_reference
typedef const_reference reference
typedef _Base_type::const_iterator const_iterator
typedef const_iterator iterator
typedef
__iter_traits::difference_type difference_type"
typedef __iter_traits::value_type char_type
typedef allocator_traits
< _Alloc >::size_type size_type"
typedef std::basic_string
< char_type > string_type"
28.10.1 Construction, Copying, n' Destruction
match_results (const _Alloc &__a=_Alloc())
match_results (const match_results &__rhs)
match_results (match_results &&__rhs) noexcept
match_results & operator= (const match_results &__rhs)
match_results & operator= (match_results &&__rhs)
~match_results ()
28.10.2 Size
size_type size () const
size_type max_size () const
bool empty () const
10.3 Element Access
difference_type length (size_type __sub=0) const
difference_type position (size_type __sub=0) const
string_type str (size_type __sub=0) const
const_reference operator[] (size_type __sub) const
const_reference prefix () const
const_reference suffix () const
const_iterator begin () const
const_iterator cbegin () const
const_iterator end () const
const_iterator cend () const
10.4 Formatting
These functions big-ass up formatted substitution of tha matched characta sequences tha fuck into they target. Da format specifiers n' escape sequences accepted by these functions is determined by they flags parameta as documented above.
template<typename _Out_ita > _Out_ita format (_Out_ita __out, const char_type *__fmt_first, const char_type *__fmt_last, match_flag_type __flags=regex_constants::format_default) const
template<typename _Out_ita , typename _St , typename _Sa > _Out_ita format (_Out_ita __out, const basic_string< char_type, _St, _Sa > &__fmt, match_flag_type __flags=regex_constants::format_default) const
template<typename _Out_ita , typename _St , typename _Sa > basic_string< char_type, _St, _Sa > format (const basic_string< char_type, _St, _Sa > &__fmt, match_flag_type __flags=regex_constants::format_default) const
string_type format (const char_type *__fmt, match_flag_type __flags=regex_constants::format_default) const
10.5 Allocator
allocator_type get_allocator () const
10.6 Swap
void swap (match_results &__that)
Detailed Description
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >>class std::match_results< _Bi_iter, _Alloc >
Da thangs up in dis biatch of a match or search operation.
A collection of characta sequences representin tha result of a regular expression match. Right back up in yo muthafuckin ass. Storage fo' tha collection be allocated n' freed as necessary by tha member functionz of class template match_results.
This class satisfies tha Sequence requirements, wit tha exception dat only tha operations defined fo' a cold-ass lil const-qualified Sequence is supported.
Da sub_match object stored at index 0 represents sub-expression 0, i.e. tha whole match. In dis case tha sub_match member matched be always true. Da sub_match object stored at index n denotes what tha fuck matched tha marked sub-expression n within tha matched expression. If tha sub-expression n participated up in a regular expression match then tha sub_match member matched evaluates ta true, n' thugz first n' second denote tha range of charactas [first, second) which formed dat match. Otherwise matched is false, n' thugz first n' second point ta tha end of tha sequence dat was searched.
Definizzle at line 1429 of file regex.h.
Constructor & Destructor Documentation
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> std::match_results< _Bi_iter, _Alloc >::match_results (const _Alloc &__a = _Alloc()) [inline], [explicit]
Constructs a thugged-out default match_results container.
Postcondition:
size() returns 0 n' str() returns a empty string.
Definizzle at line 1478 of file regex.h.
Referenced by std::match_results< _FwdIterT, _Alloc >::operator=().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> std::match_results< _Bi_iter, _Alloc >::match_results (const match_results< _Bi_iter, _Alloc > &__rhs) [inline]
Copy constructs a match_results.
Definizzle at line 1485 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> std::match_results< _Bi_iter, _Alloc >::match_results (match_results< _Bi_iter, _Alloc > &&__rhs) [inline], [noexcept]
Move constructs a match_results.
Definizzle at line 1492 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> std::match_results< _Bi_iter, _Alloc >::~match_results () [inline]
Destroys a match_results object.
Definizzle at line 1519 of file regex.h.
Member Function Documentation
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> const_iterator std::match_results< _Bi_iter, _Alloc >::begin () const [inline]
Gets a iterator ta tha start of tha sub_match collection.
Definizzle at line 1676 of file regex.h.
Referenced by std::operator==().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> const_iterator std::match_results< _Bi_iter, _Alloc >::cbegin () const [inline]
Gets a iterator ta tha start of tha sub_match collection.
Definizzle at line 1683 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> const_iterator std::match_results< _Bi_iter, _Alloc >::cend () const [inline]
Gets a iterator ta one-past-the-end of tha collection.
Definizzle at line 1697 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> bool std::match_results< _Bi_iter, _Alloc >::empty () const [inline]
Indicates if tha match_results gotz nuff no thangs up in dis biatch.
Return joints:
true Da match_results object is empty.
false Da match_results object aint empty.
Definizzle at line 1563 of file regex.h.
Referenced by std::match_results< _FwdIterT, _Alloc >::end(), std::operator==(), std::match_results< _FwdIterT, _Alloc >::prefix(), n' std::match_results< _FwdIterT, _Alloc >::suffix().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> const_iterator std::match_results< _Bi_iter, _Alloc >::end () const [inline]
Gets a iterator ta one-past-the-end of tha collection.
Definizzle at line 1690 of file regex.h.
Referenced by std::match_results< _FwdIterT, _Alloc >::cend(), n' std::operator==().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> template<typename _Out_ita > _Out_ita std::match_results< _Bi_iter, _Alloc >::format (_Out_iter__out, const char_type *__fmt_first, const char_type *__fmt_last, match_flag_type__flags = regex_constants::format_default) const [inline]
Precondition:
ready() == legit
Todo
Implement dis function.
Definizzle at line 1718 of file regex.h.
Referenced by std::match_results< _FwdIterT, _Alloc >::format().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> template<typename _Out_ita , typename _St , typename _Sa > _Out_ita std::match_results< _Bi_iter, _Alloc >::format (_Out_iter__out, const basic_string< char_type, _St, _Sa > &__fmt, match_flag_type__flags = regex_constants::format_default) const [inline]
Precondition:
ready() == legit
Definizzle at line 1728 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> template<typename _Out_ita , typename _St , typename _Sa > basic_string<char_type, _St, _Sa> std::match_results< _Bi_iter, _Alloc >::format (const basic_string< char_type, _St, _Sa > &__fmt, match_flag_type__flags = regex_constants::format_default) const [inline]
Precondition:
ready() == legit
Definizzle at line 1740 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> string_type std::match_results< _Bi_iter, _Alloc >::format (const char_type *__fmt, match_flag_type__flags = regex_constants::format_default) const [inline]
Precondition:
ready() == legit
Definizzle at line 1752 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> allocator_type std::match_results< _Bi_iter, _Alloc >::get_allocator () const [inline]
Gets a cold-ass lil copy of tha allocator.
Definizzle at line 1773 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> difference_type std::match_results< _Bi_iter, _Alloc >::length (size_type__sub = 0) const [inline]
Gets tha length of tha indicated submatch.
Parameters:
__sub indicates tha submatch.
Precondition:
ready() == true
This function returns tha length of tha indicated submatch, or tha length of tha entire match if __sub is zero (the default).
Definizzle at line 1582 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> size_type std::match_results< _Bi_iter, _Alloc >::max_size () const [inline]
Gets tha number of matches n' submatches. Da number of matches fo' a given regular expression is ghon be either 0 if there was no match or mark_count() + 1 if a match was successful. Right back up in yo muthafuckin ass. Some matches may be empty.
Returns:
the number of matches found.
Definizzle at line 1554 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> match_results& std::match_results< _Bi_iter, _Alloc >::operator= (const match_results< _Bi_iter, _Alloc > &__rhs) [inline]
Assigns rhs ta *this.
Definizzle at line 1500 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> match_results& std::match_results< _Bi_iter, _Alloc >::operator= (match_results< _Bi_iter, _Alloc > &&__rhs) [inline]
Move-assigns rhs ta *this.
Definizzle at line 1510 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> const_reference std::match_results< _Bi_iter, _Alloc >::operator[] (size_type__sub) const [inline]
Gets a sub_match reference fo' tha match or submatch.
Parameters:
__sub indicates tha submatch.
Precondition:
ready() == true
This function gets a reference ta tha indicated submatch, or tha entire match if __sub is zero.
If __sub >= size() then dis function returns a sub_match wit a special value indicatin no submatch.
Definizzle at line 1630 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> difference_type std::match_results< _Bi_iter, _Alloc >::posizzle (size_type__sub = 0) const [inline]
Gets tha offset of tha beginnin of tha indicated submatch.
Parameters:
__sub indicates tha submatch.
Precondition:
ready() == true
This function returns tha offset from tha beginnin of tha target sequence ta tha beginnin of tha submatch, unless tha value of __sub is zero (the default), up in which case dis function returns tha offset from tha beginnin of tha target sequence ta tha beginnin of tha match.
Returns -1 if __sub is outta range.
Definizzle at line 1599 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> const_reference std::match_results< _Bi_iter, _Alloc >::prefix () const [inline]
Gets a sub_match representin tha match prefix.
Precondition:
ready() == true
This function gets a reference ta a sub_match object representin tha part of tha target range between tha start of tha target range n' tha start of tha match.
Definizzle at line 1647 of file regex.h.
Referenced by std::operator==(), n' std::match_results< _FwdIterT, _Alloc >::position().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> bool std::match_results< _Bi_iter, _Alloc >::ready () const [inline]
Indicates if tha match_results is ready.
Return joints:
true Da object has a gangbangin' fully-established result state.
false Da object aint ready.
Definizzle at line 1530 of file regex.h.
Referenced by std::operator==(), std::match_results< _FwdIterT, _Alloc >::operator[](), std::match_results< _FwdIterT, _Alloc >::prefix(), n' std::match_results< _FwdIterT, _Alloc >::suffix().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> size_type std::match_results< _Bi_iter, _Alloc >::size () const [inline]
Gets tha number of matches n' submatches. Da number of matches fo' a given regular expression is ghon be either 0 if there was no match or mark_count() + 1 if a match was successful. Right back up in yo muthafuckin ass. Some matches may be empty.
Returns:
the number of matches found.
Definizzle at line 1547 of file regex.h.
Referenced by std::match_results< _FwdIterT, _Alloc >::empty(), std::operator==(), std::match_results< _FwdIterT, _Alloc >::operator[](), n' std::match_results< _FwdIterT, _Alloc >::position().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> string_type std::match_results< _Bi_iter, _Alloc >::str (size_type__sub = 0) const [inline]
Gets tha match or submatch converted ta a strang type.
Parameters:
__sub indicates tha submatch.
Precondition:
ready() == true
This function gets tha submatch (or match, if __sub is zero) extracted from tha target range n' converted ta tha associated strang type.
Definizzle at line 1615 of file regex.h.
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> const_reference std::match_results< _Bi_iter, _Alloc >::suffix () const [inline]
Gets a sub_match representin tha match suffix.
Precondition:
ready() == true
This function gets a reference ta a sub_match object representin tha part of tha target range between tha end of tha match n' tha end of tha target range.
Definizzle at line 1664 of file regex.h.
Referenced by std::operator==().
template<typename _Bi_iter, typename _Alloc = allocator<sub_match<_Bi_iter> >> void std::match_results< _Bi_iter, _Alloc >::swap (match_results< _Bi_iter, _Alloc > &__that) [inline]
Swaps tha contentz of two match_results.
Definizzle at line 1787 of file regex.h.
Referenced by std::swap().
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.