" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::gamma_distribution< _RealType > -
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
gamma_distribution (_RealType __alpha_val=_RealType(1), _RealType __beta_val=_RealType(1))
gamma_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
_RealType alpha () const
_RealType beta () const
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > gamma_distribution< _RealType >
::result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)"
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
param_type param () const
void param (const param_type &__param)
void reset ()
Friends
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::gamma_distribution< _RealType1 > &__x)"
bool operator== (const gamma_distribution &__d1, const gamma_distribution &__d2)
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::gamma_distribution< _RealType1 > &__x)"
Detailed Description
template<typename _RealType = double>class std::gamma_distribution< _RealType >
A gamma continuous distribution fo' random numbers.
Da formula fo' tha gamma probabilitizzle densitizzle function is: \[ p(x|\alpha,\beta) = \frac{1}{\beta\Gamma(\alpha)} (x/\beta)^{\alpha - 1} e^{-x/\beta} \]
Definizzle at line 2502 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::gamma_distribution< _RealType >::result_type
Da type of tha range of tha distribution.
Definizzle at line 2505 of file random.h.
Constructor & Destructor Documentation
template<typename _RealType = double> std::gamma_distribution< _RealType >::gamma_distribution (_RealType__alpha_val = _RealType(1), _RealType__beta_val = _RealType(1)) [inline], [explicit]
Constructs a gamma distribution wit parametas $\alpha$ n' $\beta$.
Definizzle at line 2554 of file random.h.
Member Function Documentation
template<typename _RealType = double> _RealType std::gamma_distribution< _RealType >::alpha () const [inline]
Returns tha $\alpha$ of tha distribution.
Definizzle at line 2575 of file random.h.
template<typename _RealType = double> _RealType std::gamma_distribution< _RealType >::beta () const [inline]
Returns tha $\beta$ of tha distribution.
Definizzle at line 2582 of file random.h.
template<typename _RealType = double> result_type std::gamma_distribution< _RealType >::max () const [inline]
Returns tha least upper bound value of tha distribution.
Definizzle at line 2611 of file random.h.
template<typename _RealType = double> result_type std::gamma_distribution< _RealType >::min () const [inline]
Returns tha top billin lower bound value of tha distribution.
Definizzle at line 2604 of file random.h.
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > gamma_distribution<_RealType>::result_type std::gamma_distribution< _RealType >::operator() (_UniformRandomNumberGenerator &__urng, const param_type &__param)
Marsaglia, G. n' Tsang, W. W. 'A Simple Method fo' Generatin Gamma Variables' ACM Transactions on Mathematical Software, 26, 3, 363-372, 2000.
Definizzle at line 2489 of file bits/random.tcc.
References std::log(), n' std::pow().
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::gamma_distribution< _RealType >::operator() (_UniformRandomNumberGenerator &__urng) [inline]
Generatin functions.
Definizzle at line 2619 of file random.h.
Referenced by std::gamma_distribution< result_type >::operator()().
template<typename _RealType = double> param_type std::gamma_distribution< _RealType >::param () const [inline]
Returns tha parameta set of tha distribution.
Definizzle at line 2589 of file random.h.
template<typename _RealType = double> void std::gamma_distribution< _RealType >::param (const param_type &__param) [inline]
Sets tha parameta set of tha distribution.
Parameters:
__param Da freshly smoked up parameta set of tha distribution.
Definizzle at line 2597 of file random.h.
template<typename _RealType = double> void std::gamma_distribution< _RealType >::reset () [inline]
Resets tha distribution state.
Definizzle at line 2568 of file random.h.
Referenced by std::chi_squared_distribution< _RealType >::reset(), std::fisher_f_distribution< _RealType >::reset(), std::student_t_distribution< _RealType >::reset(), n' std::negative_binomial_distribution< _IntType >::reset().
Playas And Related Function Documentation
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::gamma_distribution< _RealType1 > &__x) [friend]
Inserts a gamma_distribution random number distribution __x tha fuck into tha output stream __os.
Parameters:
__os An output stream.
__x A gamma_distribution random number distribution.
Returns:
Da output stream wit tha state of __x banged or up in a error state.
template<typename _RealType = double> bool operator== (const gamma_distribution< _RealType > &__d1, const gamma_distribution< _RealType > &__d2) [friend]
Return legit if two gamma distributions have tha same parametas n' tha sequences dat would be generated is equal.
Definizzle at line 2655 of file random.h.
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &__is, std::gamma_distribution< _RealType1 > &__x) [friend]
Extracts a gamma_distribution random number distribution __x from tha input stream __is.
Parameters:
__is An input stream.
__x A gamma_distribution random number generator engine.
Returns:
Da input stream wit __x extracted or up in a error state.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.