" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::money_put< _CharT, _OutIta > -
SYNOPSIS
Inherits std::locale::facet.
Public Types
typedef _CharT char_type
typedef _OutIta iter_type
typedef basic_string< _CharT > string_type
Public Member Functions
money_put (size_t __refs=0)
template<bool _Intl> _OutIta _M_insert (iter_type __s, ios_base &__io, char_type __fill, const string_type &__digits) const
iter_type put (iter_type __s, bool __intl, ios_base &__io, char_type __fill, long double __units) const
iter_type put (iter_type __s, bool __intl, ios_base &__io, char_type __fill, const string_type &__digits) const
Static Public Attributes
static locale::id id
Protected Member Functions
virtual ~money_put ()
template<bool _Intl> iter_type _M_insert (iter_type __s, ios_base &__io, char_type __fill, const string_type &__digits) const
virtual iter_type do_put (iter_type __s, bool __intl, ios_base &__io, char_type __fill, long double __units) const
virtual iter_type do_put (iter_type __s, bool __intl, ios_base &__io, char_type __fill, const string_type &__digits) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Detailed Description
template<typename _CharT, typename _OutIter>class std::money_put< _CharT, _OutIta >
Primary class template scrilla_put.
This facet encapsulates tha code ta format n' output a monetary amount.
Da scrilla_put template uses protected virtual functions ta provide tha actual thangs up in dis biatch. Da hood accessors forward tha call ta tha virtual functions. These virtual functions is hooks fo' pimpers ta implement tha behavior they require from tha scrilla_put facet.
Definizzle at line 1521 of file locale_facets_nonio.h.
Member Typedef Documentation
template<typename _CharT , typename _OutIta > typedef _CharT std::money_put< _CharT, _OutIta >::char_type
Public typedefs.
Definizzle at line 1526 of file locale_facets_nonio.h.
template<typename _CharT , typename _OutIta > typedef _OutIta std::money_put< _CharT, _OutIta >::iter_type
Public typedefs.
Definizzle at line 1527 of file locale_facets_nonio.h.
template<typename _CharT , typename _OutIta > typedef basic_string<_CharT> std::money_put< _CharT, _OutIta >::string_type
Public typedefs.
Definizzle at line 1528 of file locale_facets_nonio.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _OutIta > std::money_put< _CharT, _OutIta >::money_put (size_t__refs = 0) [inline], [explicit]
Constructor performs initialization. This is tha constructor provided by tha standard.
Parameters:
__refs Passed ta tha base facet class.
Definizzle at line 1542 of file locale_facets_nonio.h.
template<typename _CharT , typename _OutIta > virtual std::money_put< _CharT, _OutIta >::~money_put () [inline], [protected], [virtual]
Destructor.
Definizzle at line 1592 of file locale_facets_nonio.h.
Member Function Documentation
template<typename _CharT , typename _OutIta > _OutIta std::money_put< _CharT, _OutIta >::do_put (iter_type__s, bool__intl, ios_base &__io, char_type__fill, long double__units) const [protected], [virtual]
Format n' output a monetary value. This function formats units as a monetary value accordin ta scrillapunct n' ctype facets retrieved from io.getloc(), n' writes tha resultin charactas ta __s. For example, tha value 1001 up in a US locale would write $10.01 ta __s.
This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
put().
Parameters:
__s Da stream ta write to.
__intl Parameta ta use_facet<moneypunct<CharT,intl> >.
__io Source of facets n' io state.
__fill char_type ta use fo' padding.
__units Place ta store result of parsing.
Returns:
Iterator afta writing.
Definizzle at line 570 of file locale_facets_nonio.tcc.
References std::ios_base::getloc(), n' std::__ctype_abstract_base< _CharT >::widen().
Referenced by std::money_put< _CharT, _OutIta >::put().
template<typename _CharT , typename _OutIta > _OutIta std::money_put< _CharT, _OutIta >::do_put (iter_type__s, bool__intl, ios_base &__io, char_type__fill, const string_type &__digits) const [protected], [virtual]
Format n' output a monetary value. This function formats digits as a monetary value accordin ta scrillapunct n' ctype facets retrieved from io.getloc(), n' writes tha resultin charactas ta __s. For example, tha strang 1001 up in a US locale would write $10.01 ta __s.
This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
put().
Parameters:
__s Da stream ta write to.
__intl Parameta ta use_facet<moneypunct<CharT,intl> >.
__io Source of facets n' io state.
__fill char_type ta use fo' padding.
__digits Place ta store result of parsing.
Returns:
Iterator afta writing.
Definizzle at line 608 of file locale_facets_nonio.tcc.
template<typename _CharT , typename _OutIta > iter_type std::money_put< _CharT, _OutIta >::put (iter_type__s, bool__intl, ios_base &__io, char_type__fill, long double__units) const [inline]
Format n' output a monetary value. This function formats units as a monetary value accordin ta scrillapunct n' ctype facets retrieved from io.getloc(), n' writes tha resultin charactas ta __s. For example, tha value 1001 up in a US locale would write $10.01 ta __s.
This function works by returnin tha result of do_put().
Parameters:
__s Da stream ta write to.
__intl Parameta ta use_facet<moneypunct<CharT,intl> >.
__io Source of facets n' io state.
__fill char_type ta use fo' padding.
__units Place ta store result of parsing.
Returns:
Iterator afta writing.
Definizzle at line 1562 of file locale_facets_nonio.h.
References std::money_put< _CharT, _OutIta >::do_put().
template<typename _CharT , typename _OutIta > iter_type std::money_put< _CharT, _OutIta >::put (iter_type__s, bool__intl, ios_base &__io, char_type__fill, const string_type &__digits) const [inline]
Format n' output a monetary value. This function formats digits as a monetary value accordin ta scrillapunct n' ctype facets retrieved from io.getloc(), n' writes tha resultin charactas ta __s. For example, tha strang 1001 up in a US locale would write $10.01 ta __s.
This function works by returnin tha result of do_put().
Parameters:
__s Da stream ta write to.
__intl Parameta ta use_facet<moneypunct<CharT,intl> >.
__io Source of facets n' io state.
__fill char_type ta use fo' padding.
__digits Place ta store result of parsing.
Returns:
Iterator afta writing.
Definizzle at line 1585 of file locale_facets_nonio.h.
References std::money_put< _CharT, _OutIta >::do_put().
Member Data Documentation
template<typename _CharT , typename _OutIta > locale::id std::money_put< _CharT, _OutIta >::id [static]
Numpunct facet id.
Definizzle at line 1532 of file locale_facets_nonio.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.