" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::multiset< _Key, _Compare, _Alloc > -
SYNOPSIS
Public Types
typedef _Alloc allocator_type
typedef _Rep_type::const_iterator const_iterator
typedef
_Key_alloc_type::const_pointa const_pointer"
typedef
_Key_alloc_type::const_reference const_reference"
typedef
_Rep_type::const_reverse_iterator const_reverse_iterator"
typedef _Rep_type::difference_type difference_type
typedef _Rep_type::const_iterator iterator
typedef _Compare key_compare
typedef _Key key_type
typedef _Key_alloc_type::pointa pointer
typedef _Key_alloc_type::reference reference
typedef
_Rep_type::const_reverse_iterator reverse_iterator"
typedef _Rep_type::size_type size_type
typedef _Compare value_compare
typedef _Key value_type
Public Member Functions
multiset ()
multiset (const _Compare &__comp, const allocator_type &__a=allocator_type())
template<typename _InputIterator > multiset (_InputIterator __first, _InputIterator __last)
template<typename _InputIterator > multiset (_InputIterator __first, _InputIterator __last, const _Compare &__comp, const allocator_type &__a=allocator_type())
multiset (const multiset &__x)
multiset (multiset &&__x) noexcept(is_nothrow_copy_constructible< _Compare >::value)
multiset (initializer_list< value_type > __l, const _Compare &__comp=_Compare(), const allocator_type &__a=allocator_type())
iterator begin () const noexcept
iterator cbegin () const noexcept
iterator cend () const noexcept
void clear () noexcept
size_type count (const key_type &__x) const
reverse_iterator crbegin () const noexcept
reverse_iterator crend () const noexcept
template<typename... _Args> iterator emplace (_Args &&...__args)
template<typename... _Args> iterator emplace_hint (const_iterator __pos, _Args &&...__args)
bool empty () const noexcept
iterator end () const noexcept
_GLIBCXX_ABI_TAG_CXX11 iterator erase (const_iterator __position)
size_type erase (const key_type &__x)
_GLIBCXX_ABI_TAG_CXX11 iterator erase (const_iterator __first, const_iterator __last)
allocator_type get_allocator () const noexcept
iterator insert (const value_type &__x)
iterator insert (value_type &&__x)
iterator insert (const_iterator __position, const value_type &__x)
iterator insert (const_iterator __position, value_type &&__x)
template<typename _InputIterator > void insert (_InputIterator __first, _InputIterator __last)
void insert (initializer_list< value_type > __l)
key_compare key_comp () const
size_type max_size () const noexcept
multiset & operator= (const multiset &__x)
multiset & operator= (multiset &&__x)
multiset & operator= (initializer_list< value_type > __l)
reverse_iterator rbegin () const noexcept
reverse_iterator rend () const noexcept
size_type size () const noexcept
void swap (multiset &__x)
value_compare value_comp () const
iterator find (const key_type &__x)
const_iterator find (const key_type &__x) const
iterator lower_bound (const key_type &__x)
const_iterator lower_bound (const key_type &__x) const
iterator upper_bound (const key_type &__x)
const_iterator upper_bound (const key_type &__x) const
std::pair< iterator, iterator > equal_range (const key_type &__x)
std::pair< const_iterator,
const_iterator > equal_range (const key_type &__x) const "
Friends
template<typename _K1 , typename _C1 , typename _A1 > bool operator< (const multiset< _K1, _C1, _A1 > &, const multiset< _K1, _C1, _A1 > &)
template<typename _K1 , typename _C1 , typename _A1 > bool operator== (const multiset< _K1, _C1, _A1 > &, const multiset< _K1, _C1, _A1 > &)
Detailed Description
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>>class std::multiset< _Key, _Compare, _Alloc >
A standard container made up of elements, which can be retrieved up in logarithmic time.
Template Parameters:
_Key Type of key objects.
_Compare Comparison function object type, defaults ta less<_Key>.
_Alloc Allocator type, defaults ta allocator<_Key>.
Meets tha requirementz of a container, a reversible container, n' a associatizzle container (usin equivalent keys). For a multiset<Key> tha key_type n' value_type is Key.
Multisets support bidirectionizzle iterators.
Da private tree data is declared exactly tha same way fo' set n' multiset; tha distinction is made entirely up in how tha fuck tha tree functions is called (*_unique versus *_equal, same as tha standard).
Definizzle at line 92 of file stl_multiset.h.
Constructor & Destructor Documentation
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::multiset< _Key, _Compare, _Alloc >::multiset () [inline]
Default constructor creates no elements.
Definizzle at line 137 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::multiset< _Key, _Compare, _Alloc >::multiset (const _Compare &__comp, const allocator_type &__a = allocator_type()) [inline], [explicit]
Creates a multiset wit no elements.
Parameters:
__comp Comparator ta use.
__a An allocator object.
Definizzle at line 146 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename _InputIterator > std::multiset< _Key, _Compare, _Alloc >::multiset (_InputIterator__first, _InputIterator__last) [inline]
Buildz a multiset from a range.
Parameters:
__first An input iterator.
__last An input iterator.
Smoke a multiset consistin of copiez of tha elements from [first,last). This is linear up in N if tha range be already sorted, n' NlogN otherwise (where N is distance(__first,__last)).
Definizzle at line 160 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename _InputIterator > std::multiset< _Key, _Compare, _Alloc >::multiset (_InputIterator__first, _InputIterator__last, const _Compare &__comp, const allocator_type &__a = allocator_type()) [inline]
Buildz a multiset from a range.
Parameters:
__first An input iterator.
__last An input iterator.
__comp A comparison functor.
__a An allocator object.
Smoke a multiset consistin of copiez of tha elements from [__first,__last). This is linear up in N if tha range be already sorted, n' NlogN otherwise (where N is distance(__first,__last)).
Definizzle at line 176 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::multiset< _Key, _Compare, _Alloc >::multiset (const multiset< _Key, _Compare, _Alloc > &__x) [inline]
Multiset copy constructor.
Parameters:
__x A multiset of identical element n' allocator types.
Da newly-created multiset uses a cold-ass lil copy of tha allocation object used by __x.
Definizzle at line 189 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::multiset< _Key, _Compare, _Alloc >::multiset (multiset< _Key, _Compare, _Alloc > &&__x) [inline], [noexcept]
Multiset move constructor.
Parameters:
__x A multiset of identical element n' allocator types.
Da newly-created multiset gotz nuff tha exact contentz of __x. Da contentz of __x is a valid yo, but unspecified multiset.
Definizzle at line 200 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::multiset< _Key, _Compare, _Alloc >::multiset (initializer_list< value_type >__l, const _Compare &__comp = _Compare(), const allocator_type &__a = allocator_type()) [inline]
Buildz a multiset from a initializer_list.
Parameters:
__l An initializer_list.
__comp A comparison functor.
__a An allocator object.
Smoke a multiset consistin of copiez of tha elements from tha list. This is linear up in N if tha list be already sorted, n' NlogN otherwise (where N is __l.size()).
Definizzle at line 214 of file stl_multiset.h.
Member Function Documentation
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::begin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha multiset. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 295 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::cbegin () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points ta tha straight-up original gangsta element up in tha multiset. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 332 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::cend () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha multiset. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 341 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> void std::multiset< _Key, _Compare, _Alloc >::clear () [inline], [noexcept]
Erases all elements up in a multiset. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 616 of file stl_multiset.h.
Referenced by std::multiset< _Key, _Compare, _Alloc >::operator=().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> size_type std::multiset< _Key, _Compare, _Alloc >::count (const key_type &__x) const [inline]
Findz tha number of elements wit given key.
Parameters:
__x Key of elements ta be located.
Returns:
Number of elements wit specified key.
Definizzle at line 627 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> reverse_iterator std::multiset< _Key, _Compare, _Alloc >::crbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha multiset. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 350 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> reverse_iterator std::multiset< _Key, _Compare, _Alloc >::crend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha multiset. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 359 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename... _Args> iterator std::multiset< _Key, _Compare, _Alloc >::emplace (_Args &&...__args) [inline]
Buildz n' bangs a element tha fuck into tha multiset.
Parameters:
__args Arguments used ta generate tha element instizzle ta be inserted.
Returns:
An iterator dat points ta tha banged element.
This function bangs a element tha fuck into tha multiset. Contrary ta a std::set tha multiset do not rely on unique keys n' thus multiple copiez of tha same element can be inserted.
Insertion requires logarithmic time.
Definizzle at line 409 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename... _Args> iterator std::multiset< _Key, _Compare, _Alloc >::emplace_hint (const_iterator__pos, _Args &&...__args) [inline]
Buildz n' bangs a element tha fuck into tha multiset.
Parameters:
__pos An iterator dat serves as a hint as ta where tha element should be inserted.
__args Arguments used ta generate tha element instizzle ta be inserted.
Returns:
An iterator dat points ta tha banged element.
This function bangs a element tha fuck into tha multiset. Contrary ta a std::set tha multiset do not rely on unique keys n' thus multiple copiez of tha same element can be inserted.
Note dat tha straight-up original gangsta parameta is only a hint n' can potentially improve tha performizzle of tha insertion process fo' realz. A wack hint would cause no gains up in efficiency.
See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html fo' mo' on hinting.
Insertion requires logarithmic time (if tha hint aint taken).
Definizzle at line 435 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> bool std::multiset< _Key, _Compare, _Alloc >::empty () const [inline], [noexcept]
Returns legit if tha set is empty.
Definizzle at line 365 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::end () const [inline], [noexcept]
Returns a read-only (constant) iterator dat points one past tha last element up in tha multiset. Iteration is done up in ascendin order accordin ta tha keys.
Definizzle at line 304 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::pair<iterator, iterator> std::multiset< _Key, _Compare, _Alloc >::equal_range (const key_type &__x) [inline]
Findz a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Pair of iterators dat possibly points ta tha subsequence matchin given key.
This function is equivalent ta
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
 (but is fasta than makin tha calls separately).
This function probably only make sense fo' multisets.
Definizzle at line 707 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> std::pair<const_iterator, const_iterator> std::multiset< _Key, _Compare, _Alloc >::equal_range (const key_type &__x) const [inline]
Findz a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Pair of iterators dat possibly points ta tha subsequence matchin given key.
This function is equivalent ta
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
 (but is fasta than makin tha calls separately).
This function probably only make sense fo' multisets.
Definizzle at line 711 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> _GLIBCXX_ABI_TAG_CXX11 iterator std::multiset< _Key, _Compare, _Alloc >::erase (const_iterator__position) [inline]
Erases a element from a multiset.
Parameters:
__position An iterator pointin ta tha element ta be erased.
Returns:
An iterator pointin ta tha element immediately followin position prior ta tha element bein erased. If no such element exists, end() is returned.
This function erases a element, pointed ta by tha given iterator, from a multiset. Note dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 537 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> size_type std::multiset< _Key, _Compare, _Alloc >::erase (const key_type &__x) [inline]
Erases elements accordin ta tha provided key.
Parameters:
__x Key of element ta be erased.
Returns:
Da number of elements erased.
This function erases all elements located by tha given key from a multiset. Note dat dis function only erases tha element, n' dat if tha element is itself a pointer, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 567 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> _GLIBCXX_ABI_TAG_CXX11 iterator std::multiset< _Key, _Compare, _Alloc >::erase (const_iterator__first, const_iterator__last) [inline]
Erases a [first,last) range of elements from a multiset.
Parameters:
__first Iterator pointin ta tha start of tha range ta be erased.
__last Iterator pointin ta tha end of tha range ta be erased.
Returns:
Da iterator last.
This function erases a sequence of elements from a multiset. Note dat dis function only erases tha elements, n' dat if tha elements theyselves is pointers, tha pointed-to memory aint touched up in any way. Managin tha pointa is tha userz responsibility.
Definizzle at line 589 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::find (const key_type &__x) [inline]
Tries ta locate a element up in a set.
Parameters:
__x Element ta be located.
Returns:
Iterator pointin ta sought-afta element, or end() if not found.
This function takes a key n' tries ta locate tha element wit which tha key matches. If successful tha function returns a iterator pointin ta tha sought afta element. If unsuccessful it returns tha past-the-end ( end() ) iterator.
Definizzle at line 645 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> const_iterator std::multiset< _Key, _Compare, _Alloc >::find (const key_type &__x) const [inline]
Tries ta locate a element up in a set.
Parameters:
__x Element ta be located.
Returns:
Iterator pointin ta sought-afta element, or end() if not found.
This function takes a key n' tries ta locate tha element wit which tha key matches. If successful tha function returns a iterator pointin ta tha sought afta element. If unsuccessful it returns tha past-the-end ( end() ) iterator.
Definizzle at line 649 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> allocator_type std::multiset< _Key, _Compare, _Alloc >::get_allocator () const [inline], [noexcept]
Returns tha memory allocation object.
Definizzle at line 286 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::insert (const value_type &__x) [inline]
Inserts a element tha fuck into tha multiset.
Parameters:
__x Element ta be inserted.
Returns:
An iterator dat points ta tha banged element.
This function bangs a element tha fuck into tha multiset. Contrary ta a std::set tha multiset do not rely on unique keys n' thus multiple copiez of tha same element can be inserted.
Insertion requires logarithmic time.
Definizzle at line 454 of file stl_multiset.h.
Referenced by std::multiset< _Key, _Compare, _Alloc >::insert(), n' std::multiset< _Key, _Compare, _Alloc >::operator=().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::insert (const_iterator__position, const value_type &__x) [inline]
Inserts a element tha fuck into tha multiset.
Parameters:
__position An iterator dat serves as a hint as ta where tha element should be inserted.
__x Element ta be inserted.
Returns:
An iterator dat points ta tha banged element.
This function bangs a element tha fuck into tha multiset. Contrary ta a std::set tha multiset do not rely on unique keys n' thus multiple copiez of tha same element can be inserted.
Note dat tha straight-up original gangsta parameta is only a hint n' can potentially improve tha performizzle of tha insertion process fo' realz. A wack hint would cause no gains up in efficiency.
See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html fo' mo' on hinting.
Insertion requires logarithmic time (if tha hint aint taken).
Definizzle at line 484 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> template<typename _InputIterator > void std::multiset< _Key, _Compare, _Alloc >::insert (_InputIterator__first, _InputIterator__last) [inline]
A template function dat tries ta bang a range of elements.
Parameters:
__first Iterator pointin ta tha start of tha range ta be inserted.
__last Iterator pointin ta tha end of tha range.
Complexitizzle similar ta dat of tha range constructor.
Definizzle at line 503 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> void std::multiset< _Key, _Compare, _Alloc >::insert (initializer_list< value_type >__l) [inline]
Attempts ta bang a list of elements tha fuck into tha multiset.
Parameters:
__l A std::initializer_list<value_type> of elements ta be inserted.
Complexitizzle similar ta dat of tha range constructor.
Definizzle at line 515 of file stl_multiset.h.
References std::multiset< _Key, _Compare, _Alloc >::insert().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> key_compare std::multiset< _Key, _Compare, _Alloc >::key_comp () const [inline]
Returns tha comparison object.
Definizzle at line 278 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::lower_bound (const key_type &__x) [inline]
Findz tha beginnin of a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Iterator pointin ta first element equal ta or pimped outa than key, or end().
This function returns tha straight-up original gangsta element of a subsequence of elements dat matches tha given key. If unsuccessful it returns a iterator pointin ta tha straight-up original gangsta element dat has a pimped outa value than given key or end() if no such element exists.
Definizzle at line 666 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> const_iterator std::multiset< _Key, _Compare, _Alloc >::lower_bound (const key_type &__x) const [inline]
Findz tha beginnin of a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Iterator pointin ta first element equal ta or pimped outa than key, or end().
This function returns tha straight-up original gangsta element of a subsequence of elements dat matches tha given key. If unsuccessful it returns a iterator pointin ta tha straight-up original gangsta element dat has a pimped outa value than given key or end() if no such element exists.
Definizzle at line 670 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> size_type std::multiset< _Key, _Compare, _Alloc >::max_size () const [inline], [noexcept]
Returns tha maximum size of tha set.
Definizzle at line 375 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> multiset& std::multiset< _Key, _Compare, _Alloc >::operator= (const multiset< _Key, _Compare, _Alloc > &__x) [inline]
Multiset assignment operator.
Parameters:
__x A multiset of identical element n' allocator types.
All tha elementz of __x is copied yo, but unlike tha copy constructor, tha allocator object aint copied.
Definizzle at line 229 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> multiset& std::multiset< _Key, _Compare, _Alloc >::operator= (multiset< _Key, _Compare, _Alloc > &&__x) [inline]
Multiset move assignment operator.
Parameters:
__x A multiset of identical element n' allocator types.
Da contentz of __x is moved tha fuck into dis multiset (without copying). __x be a valid yo, but unspecified multiset.
Definizzle at line 245 of file stl_multiset.h.
References std::multiset< _Key, _Compare, _Alloc >::clear(), n' std::multiset< _Key, _Compare, _Alloc >::swap().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> multiset& std::multiset< _Key, _Compare, _Alloc >::operator= (initializer_list< value_type >__l) [inline]
Multiset list assignment operator.
Parameters:
__l An initializer_list.
This function fills a multiset wit copiez of tha elements up in tha initializer list __l.
Note dat tha assignment straight-up chizzlez tha multiset n' dat tha resultin multisetz size is tha same ol' dirty as tha number of elements assigned. Oldskool data may be lost.
Definizzle at line 266 of file stl_multiset.h.
References std::multiset< _Key, _Compare, _Alloc >::clear(), n' std::multiset< _Key, _Compare, _Alloc >::insert().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> reverse_iterator std::multiset< _Key, _Compare, _Alloc >::rbegin () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha multiset. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 313 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> reverse_iterator std::multiset< _Key, _Compare, _Alloc >::rend () const [inline], [noexcept]
Returns a read-only (constant) reverse iterator dat points ta tha last element up in tha multiset. Iteration is done up in descendin order accordin ta tha keys.
Definizzle at line 322 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> size_type std::multiset< _Key, _Compare, _Alloc >::size () const [inline], [noexcept]
Returns tha size of tha set.
Definizzle at line 370 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> void std::multiset< _Key, _Compare, _Alloc >::swap (multiset< _Key, _Compare, _Alloc > &__x) [inline]
Swaps data wit another multiset.
Parameters:
__x A multiset of tha same element n' allocator types.
This exchanges tha elements between two multisets up in constant time. (It be only swappin a pointer, a integer, n' a instizzle of tha Compare type (which itself is often stateless n' empty), so it should be like fast.) Note dat tha global std::swap() function is specialized such dat std::swap(s1,s2) will feed ta dis function.
Definizzle at line 390 of file stl_multiset.h.
Referenced by std::multiset< _Key, _Compare, _Alloc >::operator=(), n' std::swap().
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> iterator std::multiset< _Key, _Compare, _Alloc >::upper_bound (const key_type &__x) [inline]
Findz tha end of a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Iterator pointin ta tha straight-up original gangsta element pimped outa than key, or end().
Definizzle at line 682 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> const_iterator std::multiset< _Key, _Compare, _Alloc >::upper_bound (const key_type &__x) const [inline]
Findz tha end of a subsequence matchin given key.
Parameters:
__x Key ta be located.
Returns:
Iterator pointin ta tha straight-up original gangsta element pimped outa than key, or end().
Definizzle at line 686 of file stl_multiset.h.
template<typename _Key, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<_Key>> value_compare std::multiset< _Key, _Compare, _Alloc >::value_comp () const [inline]
Returns tha comparison object.
Definizzle at line 282 of file stl_multiset.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.