" 3 "Thu Sep 11 2014" "libstdc++" \" -*- nroff -*-
NAME
std::time_get< _CharT, _InIta > -
SYNOPSIS
Inherits std::locale::facet, n' std::time_base.
Inherited by std::time_get_byname< _CharT, _InIta >.
Public Types
typedef basic_string< _CharT > __string_type
enum dateorder { no_order, dmy, mdy, ymd, ydm }
typedef _CharT char_type
typedef _InIta iter_type
Public Member Functions
time_get (size_t __refs=0)
dateorder date_order () const
iter_type get_date (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const
iter_type get_monthname (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const
iter_type get_time (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const
iter_type get_weekday (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const
iter_type get_year (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const
Static Public Attributes
static locale::id id
Protected Member Functions
virtual ~time_get ()
iter_type _M_extract_name (iter_type __beg, iter_type __end, int &__member, const _CharT **__names, size_t __indexlen, ios_base &__io, ios_base::iostate &__err) const
iter_type _M_extract_num (iter_type __beg, iter_type __end, int &__member, int __min, int __max, size_t __len, ios_base &__io, ios_base::iostate &__err) const
iter_type _M_extract_via_format (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm, const _CharT *__format) const
iter_type _M_extract_wday_or_month (iter_type __beg, iter_type __end, int &__member, const _CharT **__names, size_t __indexlen, ios_base &__io, ios_base::iostate &__err) const
virtual dateorder do_date_order () const
virtual iter_type do_get_date (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const
virtual iter_type do_get_monthname (iter_type __beg, iter_type __end, ios_base &, ios_base::iostate &__err, tm *__tm) const
virtual iter_type do_get_time (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const
virtual iter_type do_get_weekday (iter_type __beg, iter_type __end, ios_base &, ios_base::iostate &__err, tm *__tm) const
virtual iter_type do_get_year (iter_type __beg, iter_type __end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Detailed Description
template<typename _CharT, typename _InIter>class std::time_get< _CharT, _InIta >
Primary class template time_get.
This facet encapsulates tha code ta parse n' return a thugged-out date or time from a string. Well shiiiit, it is used by tha istream numeric extraction operators.
Da time_get template uses protected virtual functions ta provide tha actual thangs up in dis biatch. Da hood accessors forward tha call ta tha virtual functions. These virtual functions is hooks fo' pimpers ta implement tha behavior they require from tha time_get facet.
Definizzle at line 368 of file locale_facets_nonio.h.
Member Typedef Documentation
template<typename _CharT , typename _InIta > typedef _CharT std::time_get< _CharT, _InIta >::char_type
Public typedefs.
Definizzle at line 374 of file locale_facets_nonio.h.
template<typename _CharT , typename _InIta > typedef _InIta std::time_get< _CharT, _InIta >::iter_type
Public typedefs.
Definizzle at line 375 of file locale_facets_nonio.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _InIta > std::time_get< _CharT, _InIta >::time_get (size_t__refs = 0) [inline], [explicit]
Constructor performs initialization. This is tha constructor provided by tha standard.
Parameters:
__refs Passed ta tha base facet class.
Definizzle at line 390 of file locale_facets_nonio.h.
template<typename _CharT , typename _InIta > virtual std::time_get< _CharT, _InIta >::~time_get () [inline], [protected], [virtual]
Destructor.
Definizzle at line 546 of file locale_facets_nonio.h.
Member Function Documentation
template<typename _CharT , typename _InIta > dateorder std::time_get< _CharT, _InIta >::date_order () const [inline]
Return preferred order of month, day, n' year. This function returns a enum from timebase::dateorder givin tha preferred orderin if tha format x given ta time_put::put() only uses month, day, n' year. If tha format x fo' tha associated locale uses other fields, dis function returns timebase::dateorder::noorder.
NOTE: Da library always returns noorder all up in tha moment.
Returns:
A gangmember of timebase::dateorder.
Definizzle at line 407 of file locale_facets_nonio.h.
References std::time_get< _CharT, _InIta >::do_date_order().
template<typename _CharT , typename _InIta > time_base::dateorder std::time_get< _CharT, _InIta >::do_date_order () const [protected], [virtual]
Return preferred order of month, day, n' year. This function returns a enum from timebase::dateorder givin tha preferred orderin if tha format x given ta time_put::put() only uses month, day, n' year. This function be a hook fo' derived classes ta chizzle tha value returned.
Returns:
A gangmember of timebase::dateorder.
Definizzle at line 620 of file locale_facets_nonio.tcc.
Referenced by std::time_get< _CharT, _InIta >::date_order().
template<typename _CharT , typename _InIta > _InIta std::time_get< _CharT, _InIta >::do_get_date (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [protected], [virtual]
Parse input date string. This function parses a thugged-out date accordin ta tha format X n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get_date() fo' details.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond date string.
Definizzle at line 1047 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), n' std::ios_base::eofbit.
Referenced by std::time_get< _CharT, _InIta >::get_date().
template<typename _CharT , typename _InIta > _InIta std::time_get< _CharT, _InIta >::do_get_monthname (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [protected], [virtual]
Parse input month string. This function parses a month name n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get_monthname() fo' details.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond month name.
Definizzle at line 1092 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), std::ios_base::eofbit, std::ios_base::failbit, n' std::ios_base::goodbit.
Referenced by std::time_get< _CharT, _InIta >::get_monthname().
template<typename _CharT , typename _InIta > _InIta std::time_get< _CharT, _InIta >::do_get_time (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [protected], [virtual]
Parse input time string. This function parses a time accordin ta tha format x n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get_time() fo' details.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond time string.
Definizzle at line 1030 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), n' std::ios_base::eofbit.
Referenced by std::time_get< _CharT, _InIta >::get_time().
template<typename _CharT , typename _InIta > _InIta std::time_get< _CharT, _InIta >::do_get_weekdizzle (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [protected], [virtual]
Parse input weekdizzle string. This function parses a weekdizzle name n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get_weekday() fo' details.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond weekdizzle name.
Definizzle at line 1064 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), std::ios_base::eofbit, std::ios_base::failbit, n' std::ios_base::goodbit.
Referenced by std::time_get< _CharT, _InIta >::get_weekday().
template<typename _CharT , typename _InIta > _InIta std::time_get< _CharT, _InIta >::do_get_year (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [protected], [virtual]
Parse input year string. This function readz up ta 4 charactas ta parse a year strang n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. This function be a hook fo' derived classes ta chizzle tha value returned.
See Also:
get_year() fo' details.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond year.
Definizzle at line 1120 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), std::ios_base::eofbit, std::ios_base::failbit, n' std::ios_base::goodbit.
Referenced by std::time_get< _CharT, _InIta >::get_year().
template<typename _CharT , typename _InIta > iter_type std::time_get< _CharT, _InIta >::get_date (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [inline]
Parse input date string. This function parses a thugged-out date accordin ta tha format x n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. Da result is returned by callin time_get::do_get_date().
If there be a valid date strang accordin ta format x, tm is ghon be filled up in accordingly n' tha returned iterator will point ta tha straight-up original gangsta characta beyond tha date string. If a error occurs before tha end, err |= ios_base::failbit. If parsin readz all tha characters, err |= ios_base::eofbit.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond date string.
Definizzle at line 456 of file locale_facets_nonio.h.
References std::time_get< _CharT, _InIta >::do_get_date().
template<typename _CharT , typename _InIta > iter_type std::time_get< _CharT, _InIta >::get_monthname (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [inline]
Parse input month string. This function parses a month name n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. Da result is returned by callin time_get::do_get_monthname().
Parsin starts by parsin a abbreviated month name. If a valid abbreviation is followed by a cold-ass lil characta dat would lead ta tha full month name, parsin continues until tha full name is found or a error occurs. Otherwise parsin finishes all up in tha end of tha abbreviated name.
If a error occurs before tha end, err |= ios_base::failbit. If parsin readz all tha characters, err |= ios_base::eofbit.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond month name.
Definizzle at line 513 of file locale_facets_nonio.h.
References std::time_get< _CharT, _InIta >::do_get_monthname().
template<typename _CharT , typename _InIta > iter_type std::time_get< _CharT, _InIta >::get_time (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [inline]
Parse input time string. This function parses a time accordin ta tha format X n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. Da result is returned by callin time_get::do_get_time().
If there be a valid time strang accordin ta format X, tm is ghon be filled up in accordingly n' tha returned iterator will point ta tha straight-up original gangsta characta beyond tha time string. If a error occurs before tha end, err |= ios_base::failbit. If parsin readz all tha characters, err |= ios_base::eofbit.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond time string.
Definizzle at line 431 of file locale_facets_nonio.h.
References std::time_get< _CharT, _InIta >::do_get_time().
template<typename _CharT , typename _InIta > iter_type std::time_get< _CharT, _InIta >::get_weekdizzle (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [inline]
Parse input weekdizzle string. This function parses a weekdizzle name n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. Da result is returned by callin time_get::do_get_weekday().
Parsin starts by parsin a abbreviated weekdizzle name. If a valid abbreviation is followed by a cold-ass lil characta dat would lead ta tha full weekdizzle name, parsin continues until tha full name is found or a error occurs. Otherwise parsin finishes all up in tha end of tha abbreviated name.
If a error occurs before tha end, err |= ios_base::failbit. If parsin readz all tha characters, err |= ios_base::eofbit.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond weekdizzle name.
Definizzle at line 484 of file locale_facets_nonio.h.
References std::time_get< _CharT, _InIta >::do_get_weekday().
template<typename _CharT , typename _InIta > iter_type std::time_get< _CharT, _InIta >::get_year (iter_type__beg, iter_type__end, ios_base &__io, ios_base::iostate &__err, tm *__tm) const [inline]
Parse input year string. This function readz up ta 4 charactas ta parse a year strang n' puts tha thangs up in dis biatch tha fuck into a user-supplied struct tm. Da result is returned by callin time_get::do_get_year().
4 consecutizzle digits is interpreted as a gangbangin' full year. If there be exactly 2 consecutizzle digits, tha library interprets dis as tha number of muthafuckin years since 1900.
If a error occurs before tha end, err |= ios_base::failbit. If parsin readz all tha characters, err |= ios_base::eofbit.
Parameters:
__beg Start of strang ta parse.
__end End of strang ta parse.
__io Source of tha locale.
__err Error flags ta set.
__tm Pointa ta struct tm ta fill in.
Returns:
Iterator ta first char beyond year.
Definizzle at line 539 of file locale_facets_nonio.h.
References std::time_get< _CharT, _InIta >::do_get_year().
Member Data Documentation
template<typename _CharT , typename _InIta > locale::id std::time_get< _CharT, _InIta >::id [static]
Numpunct facet id.
Definizzle at line 380 of file locale_facets_nonio.h.
Author
Generated automatically by Doxygen fo' libstdc++ from tha source code.