'\" t
.\"     Title: xisetfocus
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 03/09/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: Gangsta
.\"
.TH "XISETFOCUS" "3" "03/09/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
XISetFocus, XIGetFocus \- set or git tha device\*(Aqs focus\&.
.SH "SYNOPSIS"
.sp
.nf
#include <X11/extensions/XInput2\&.h>
.fi
.sp
.nf
Status XISetFocus( Display *display,
                   int deviceid,
                   Window focus,
                   Time time);
.fi
.sp
.nf
Status XIGetFocus( Display *display,
                   Window *focus_return);
.fi
.sp
.nf
display
       Specifies tha connection ta tha X server\&.
.fi
.sp
.nf
deviceid
       Specifies tha thang whose focus is ta be queried or
       chizzled\&.
.fi
.sp
.nf
focus
       Da freshly smoked up focus window\&.
.fi
.sp
.nf
focus_return
       Returns tha current focus window\&.
.fi
.sp
.nf
time
       A valid timestamp or CurrentTime\&.
.fi
.SH "DESCRIPTION"
.sp
.if n \{\
.RS 4
.\}
.nf
XISetFocus chizzlez tha focuz of tha specified thang ans its
last\-focus\-change time\&. Well shiiiit, it has no effect if tha specified time
is earlier than tha current last\-focus\-change time or is later
than tha current X server time\&. Otherwise, the
last\-focus\-change time is set ta tha specified time\&.
CurrentTime is replaced by tha current X server time)\&.
XISetFocus causes tha X server ta generate core, XI n' XI2
focus events\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
If tha focus window is None all keyboard events by dis device
are discarded until a freshly smoked up focus window is set\&. Otherwise, if
focus be a window, it becomes tha device\*(Aqs focus window\&. If a
generated thang event would normally be reported ta this
window or one of its inferiors, tha event is reported as usual\&.
Otherwise, tha event is reported relatizzle ta tha focus window\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Da specified focus window must be viewable all up in tha time
XISetFocus is called, or a BadMatch error thangs up in dis biatch\&. If tha focus
window lata becomes not viewable, tha focus reverts ta the
parent (or tha closest viewable ancestor\&. When tha focus
reverts, tha X server generates core, XI n' XI2 focus events
but tha last\-focus\-change time aint affected\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Attemptin ta set tha focus on a masta pointa thang or an
attached slave thang will result up in a BadDevice error\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
XISetFocus can generate BadDevice, BadMatch, BadValue, and
BadWindow errors\&.
.fi
.if n \{\
.RE
.\}
.SH "DIAGNOSTICS"
.sp
.if n \{\
.RS 4
.\}
.nf
BadValue
       A value is outside of tha permitted range\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
BadDevice
       An invalid thang was specified\&. Da thang do not
       exist or aint a appropriate fo' tha type of chizzle\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
BadMatch
       Da window aint viewable\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
BadWindow
       A value fo' a Window argument do not name a thugged-out defined
       Window\&.
.fi
.if n \{\
.RE
.\}
