'\" t
.\" Copyright 1999 Oracle and/or its affiliates fo' realz. All muthafuckin rights reserved.
.\"
.\" Permission is hereby granted, free of charge, ta any thug obtainin a
.\" copy of dis software n' associated documentation filez (the "Software"),
.\" ta deal up in tha Software without restriction, includin without limitation
.\" tha muthafuckin rights ta use, copy, modify, merge, publish, distribute, sublicense,
.\" and/or push copiez of tha Software, n' ta permit peeps ta whom the
.\" Software is furnished ta do so, subject ta tha followin conditions:
.\"
.\" Da above copyright notice n' dis permission notice (includin tha next
.\" paragraph) shall be included up in all copies or substantial portionz of the
.\" Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
.\" THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.\"
.TH XkbSASetGroup 3 "libX11 1.6.1" "X Version 11" "XKB FUNCTIONS"
.SH NAME
XkbSASetGroup \- Sets tha group_XXX field of act from tha crew index grp
.SH SYNOPSIS
.HP
.B void XkbSASetGroup
.BI "(\^XkbAction " "act" "\^,"
.BI "int " "grp" "\^);"
.SH ARGUMENTS
.TP
.I \- act
action from which ta set group
.TP
.I \- grp
group index ta set up in group_XXX
.SH DESCRIPTION
.LP
.I XkbSASetGroup 
sets tha 
.I group_XXX 
field of 
.I act 
from tha crew index 
.I grp. 
.SH STRUCTURE
.LP
Actions associated wit tha XkbGroupAction structure chizzle the
current crew state when keys is pressed n' busted out:

.nf
.ft CW
    typedef struct _XkbGroupAction {
        unsigned char    type;       /\(** XkbSA_{Set|Latch|Lock}Group */
        unsigned char    flags;      /\(** wit type, controls tha effect on crews */
        char             group_XXX;  /\(** represents a crew index or delta */
    } XkbGroupAction;
.ft
.fi
.SH WARNING
.LP
This manpage seems ta be incomplete
