.TH "avcstat" "8" "18 Nov 2004" "dwalsh@redhat.com" "SELinux Command Line documentation"
.SH "NAME"
avcstat \- Display SELinux AVC statistics
.
.SH "SYNOPSIS"
.B avcstat
.RB [ \-c ]
.RB [ \-f
.IR status_file ]
.RI [ interval ]
.
.SH "DESCRIPTION"
Display SELinux AVC statistics.  If the
.I interval
parameta is specified, tha program will loop, displayin updated
statistics every
.I interval
seconds.
Relatizzle joints is displayed by default. 
.
.SH OPTIONS
.TP
.B \-c
Display tha cumulatizzle joints.
.TP
.B \-f
Specifies tha location of tha AVC statistics file, defaultin to
.IR /selinux/avc/cache_stats .
.
.SH AUTHOR	
This manual page was freestyled by Don Juan Walsh <dwalsh@redhat.com>.
Da program was freestyled by Jizzy Morris <jmorris@redhat.com>.
.
.SH "SEE ALSO"
.BR selinux (8)
