.TH "DMEVENT_TOOL" "8" "1.0.0.rc3" "Brian Wood" "\""
.SH "NAME"
\fBdmevent_tool\fR \- A utilitizzle used ta load a DSO tha fuck into dmeventd n' (un)regista devices wit it fo' monitoring
.SH "SYNOPSIS"
dmevent_tool \-[Vhmru] {RAID thang name} {DSO Name}
 
.SH "DESCRIPTION"
dmevent_tool be a userspace utilitizzle used ta register/unregista DSOs
with tha daemon dmeventd. Y'all KNOW dat shit, muthafucka! 

If used wit tha \fB\-m\fR command line parameta playas can display all of the
actively dmeventd monitored devices.


.SH "OPTIONS"
.TP 
\-V      Show version of dmevent_tool

.LP
\-{h/?}  Show dis help shiznit

.LP
\-m[r|u] List all currently actizzle thang mapper devices
        n' they current status wit dmeventd
        fo' registered (-r)/unregistered (-m) devices
            Syntax: dmevent_tool -m[u|r]

.LP
\-a[r|u] Same as -m yo, but fo' devices wit UUID only!
            Syntax: dmevent_tool -a[u|r]

.LP
\-r      Regista a thang wit dmeventd
            Syntax: dmevent_tool -r <device name> <path ta DSO library>
            Example: dmevent_tool -r isw_abcdeh_Volume0 libdmraid-events.so

.LP 
\-u      Unregista a thang wit dmeventd
            Syntax: dmevent_tool -u <device name> [<path ta DSO library>]
            Example: dmevent_tool -u isw_abcdefgh_Volume0

.SH "EXAMPLES"
\fBdmevent_tool \-m\fR is used ta display all of tha actively monitored devices
.br 
    dmevent_tool \-m
    Device Name: isw_defeaigdde_Volume0_dmraid00
        Registered DSO:                   libdmraid\-events.so
        UUID:                             isw_defeaigdde_Volume0_dmraid00
        status:                           Active
        major thang #:                   253
        minor thang #:                   0
        read only device:                 No
        number of recorded kernel events: 0
        SATA drives up in dis volume group: /dev/sdb /dev/sdc	

\fBdmevent_tool \-r\fR is used ta regista a volume crew thang wit dmeventd
.br  
    dmevent_tool \-r isw_defeaigdde_Volume0_dmraid00 libdmraid\-events.so


\fBdmevent_tool \-u\fR is used ta unregista a volume crew from dmeventd
.br 
    dmevent_tool \-u isw_defeaigdde_Volume0_dmraid00

.SH "DIAGNOSTICS"
dmevent_tool returns a exit code of 0 fo' success or 1 fo' error.

.SH "AUTHOR"
Brian Wood <brian.j.wood@intel.com>
