.TH  "mcelog_selinux"  "8"  "14-12-02" "mcelog" "SELinux Policy mcelog"
.SH "NAME"
mcelog_selinux \- Securitizzle Enhanced Linux Policy fo' tha mcelog processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures tha mcelog processes via flexible mandatory access control.

Da mcelog processes execute wit tha mcelog_t SELinux type. Yo ass can check if you have these processes hustlin by executin tha \fBps\fP command wit tha \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep mcelog_t


.SH "ENTRYPOINTS"

Da mcelog_t SELinux type can be entered via tha \fBmcelog_exec_t\fP file type.

Da default entrypoint paths fo' tha mcelog_t domain is tha following:

/usr/sbin/mcelog
.SH PROCESS TYPES
SELinux defines process types (domains) fo' each process hustlin on tha system
.PP
Yo ass can peep tha context of a process rockin tha \fB\-Z\fP option ta \fBps\bP
.PP
Policy governs tha access confined processes gotta files.
SELinux mcelog policy is straight-up flexible allowin playas ta setup they mcelog processes up in as secure a method as possible.
.PP
Da followin process types is defined fo' mcelog:

.EX
.B mcelog_t
.EE
.PP
Note:
.B semanage permissive -a mcelog_t
can be used ta make tha process type mcelog_t permissive. Right back up in yo muthafuckin ass. SELinux do not deny access ta permissive process types yo, but tha AVC (SELinux denials) lyrics is still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required. Y'all KNOW dat shit, muthafucka!  mcelog policy is mad flexible n' has nuff muthafuckin booleans dat allow you ta manipulate tha policy n' run mcelog wit tha tightest access possible.


.PP
If you wanna determine whether mcelog supports client mode, you must turn on tha mcelog_client boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P mcelog_client 1

.EE

.PP
If you wanna determine whether mcelog can execute scripts, you must turn on tha mcelog_exec_scripts boolean. I aint talkin' bout chicken n' gravy biatch. Enabled by default.

.EX
.B setsebool -P mcelog_exec_scripts 1

.EE

.PP
If you wanna determine whether mcelog can use all tha user ttys, you must turn on tha mcelog_foreground boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P mcelog_foreground 1

.EE

.PP
If you wanna determine whether mcelog supports server mode, you must turn on tha mcelog_server boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P mcelog_server 1

.EE

.PP
If you wanna allow playas ta resolve user passwd entries directly from ldap rather then rockin a sssd server, you must turn on tha authlogin_nsswitch_use_ldap boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you wanna allow all daemons ta write corefilez ta /, you must turn on tha daemons_dump_core boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P daemons_dump_core 1

.EE

.PP
If you wanna enable clusta mode fo' daemons, you must turn on tha daemons_enable_cluster_mode boolean. I aint talkin' bout chicken n' gravy biatch. Enabled by default.

.EX
.B setsebool -P daemons_enable_cluster_mode 1

.EE

.PP
If you wanna allow all daemons ta use tcp wrappers, you must turn on tha daemons_use_tcp_wrapper boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P daemons_use_tcp_wrapper 1

.EE

.PP
If you wanna allow all daemons tha mobilitizzle ta read/write terminals, you must turn on tha daemons_use_tty boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P daemons_use_tty 1

.EE

.PP
If you wanna deny any process from ptracin or debuggin any other processes, you must turn on tha deny_ptrace boolean. I aint talkin' bout chicken n' gravy biatch. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you wanna allow all domains ta use other domains file descriptors, you must turn on tha domain_fd_use boolean. I aint talkin' bout chicken n' gravy biatch. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you wanna allow all domains ta have tha kernel load modules, you must turn on tha domain_kernel_load_modulez boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modulez 1

.EE

.PP
If you wanna allow all domains ta execute up in fips_mode, you must turn on tha fips_mode boolean. I aint talkin' bout chicken n' gravy biatch. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you wanna enable readin of urandom fo' all domains, you must turn on tha global_ssp boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you wanna allow confined applications ta run wit kerberos, you must turn on tha kerberos_enabled boolean. I aint talkin' bout chicken n' gravy biatch. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you wanna allow system ta run wit NIS, you must turn on tha nis_enabled boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you wanna allow confined applications ta use nscd shared memory, you must turn on tha nscd_use_shm boolean. I aint talkin' bout chicken n' gravy biatch. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.SH NSSWITCH DOMAIN

.PP
If you wanna allow playas ta resolve user passwd entries directly from ldap rather then rockin a sssd server fo' tha mcelog_t, you must turn on tha authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you wanna allow confined applications ta run wit kerberos fo' tha mcelog_t, you must turn on tha kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "MANAGED FILES"

Da SELinux process type mcelog_t can manage filez labeled wit tha followin file types.  Da paths listed is tha default paths fo' these file types.  Note tha processes UID still need ta have DAC permissions.

.br
.B cluster_conf_t

	/etc/cluster(/.*)?
.br

.br
.B cluster_var_lib_t

	/var/lib/pcsd(/.*)?
.br
	/var/lib/cluster(/.*)?
.br
	/var/lib/openais(/.*)?
.br
	/var/lib/pengine(/.*)?
.br
	/var/lib/corosync(/.*)?
.br
	/usr/lib/heartbeat(/.*)?
.br
	/var/lib/heartbeat(/.*)?
.br
	/var/lib/pacemaker(/.*)?
.br

.br
.B cluster_var_run_t

	/var/run/crm(/.*)?
.br
	/var/run/cman_.*
.br
	/var/run/rsctmp(/.*)?
.br
	/var/run/aisexec.*
.br
	/var/run/heartbeat(/.*)?
.br
	/var/run/cpglockd\.pid
.br
	/var/run/corosync\.pid
.br
	/var/run/rgmanager\.pid
.br
	/var/run/cluster/rgmanager\.sk
.br

.br
.B mcelog_var_run_t

	/var/run/mcelog.*
.br

.br
.B root_t

	/
.br
	/initrd
.br

.br
.B sysfs_t

	/sys(/.*)?
.br

.SH FILE CONTEXTS
SELinux requires filez ta have a extended attribute ta define tha file type.
.PP
Yo ass can peep tha context of a gangbangin' file rockin tha \fB\-Z\fP option ta \fBls\bP
.PP
Policy governs tha access confined processes gotta these files.
SELinux mcelog policy is straight-up flexible allowin playas ta setup they mcelog processes up in as secure a method as possible.
.PP

.PP
.B STANDARD FILE CONTEXT

SELinux defines tha file context types fo' tha mcelog, if you wanted to
store filez wit these types up in a gangbangin' finger-lickin' diffent paths, you need ta execute tha semanage command ta sepecify alternate labelin n' then use restorecon ta put tha labels on disk.

.B semanage fcontext -a -t mcelog_etc_t '/srv/mcelog/content(/.*)?'
.br
.B restorecon -R -v /srv/mymcelog_content

Note: SELinux often uses regular expressions ta specify labels dat match multiple files.

.I Da followin file types is defined fo' mcelog:


.EX
.PP
.B mcelog_etc_t
.EE

- Set filez wit tha mcelog_etc_t type, if you wanna store mcelog filez up in tha /etc directories.


.EX
.PP
.B mcelog_exec_t
.EE

- Set filez wit tha mcelog_exec_t type, if you wanna transizzle a executable ta tha mcelog_t domain.


.EX
.PP
.B mcelog_initrc_exec_t
.EE

- Set filez wit tha mcelog_initrc_exec_t type, if you wanna transizzle a executable ta tha mcelog_initrc_t domain.


.EX
.PP
.B mcelog_log_t
.EE

- Set filez wit tha mcelog_log_t type, if you wanna treat tha data as mcelog log data, probably stored under tha /var/log directory.


.EX
.PP
.B mcelog_var_run_t
.EE

- Set filez wit tha mcelog_var_run_t type, if you wanna store tha mcelog filez under tha /run or /var/run directory.


.PP
Note: File context can be temporarily modified wit tha chcon command. Y'all KNOW dat shit, muthafucka!  If you wanna permanently chizzle tha file context you need ta use the
.B semanage fcontext
command. Y'all KNOW dat shit, muthafucka!  This will modify tha SELinux labelin database.  Yo ass will need ta use
.B restorecon
to apply tha labels.

.SH "COMMANDS"
.B semanage fcontext
can also be used ta manipulate default file context mappings.
.PP
.B semanage permissive
can also be used ta manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used ta enable/disable/install/remove policy modules.

.B semanage boolean
can also be used ta manipulate tha booleans

.PP
.B system-config-selinux
is a GUI tool available ta customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage".

.SH "SEE ALSO"
selinux(8), mcelog(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8)</textarea>

<div id="button">
<br/>
<input type="submit" name="translate" value="Tranzizzle Dis Shiznit" />
</div>

</form> 

</div>

<div id="space3"></div>
<div id="disclaimer"><h2>Use this to translate your words into gangsta</h2>
<h2>Click <a href="more.html">here</a> to learn more about Gizoogle</h2></div>

</body>
</html>
