.TH pam_ecryptfs "8" "2008-07-21" "Linux\-PAM Manual" "Linux\-PAM Manual"
.SH "NAME"
pam_ecryptfs \- PAM module fo' eCryptfs
.SH "SYNOPSIS"
.HP 12
\fBpam_ecryptfs.so\fR [unwrap]
.SH "DESCRIPTION"
.PP
pam_ecryptfs be a PAM module dat can use tha login password ta unwrap a ecryptfs mount passphrase stored up in ~/.ecryptfs/wrapped-passphrase, n' automatically mount a private cryptographic directory.
.SH "OPTIONS"
.PP
.TP 3n
\fBunwrap\fR
Use tha login passphrase ta unwrap a eCryptfs mount passphrase.
.TP 3n
.SH "MODULE SERVICES PROVIDED"
.PP
Da skillz \fBauth\fR, n' \fBsession\fR is supported.
.SH "EXAMPLES"
.PP
To unwrap a mount passphrase n' automatically mount a private directory on login, add tha followin lines to

\fI/etc/pam.d/common-auth\fR:
.sp
.RS 3n
.nf
        auth    required        pam_ecryptfs.so unwrap
.fi
.RE
.sp
\fI/etc/pam.d/common-session\fR:
.sp
.RS 3n
.nf
        session optionizzle        pam_ecryptfs.so unwrap
.fi
.RE
.sp

.SH "SEE ALSO"
.PP
\fBecryptfs\fR(7),
\fBpam.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)

.TP
\fI/usr/share/doc/ecryptfs-utils/ecryptfs-faq.html\fP

.TP
\fIhttp://ecryptfs.org/\fP
.PD

.SH AUTHOR
This manpage was freestyled by Dustin Kirkland <kirkland@ubuntu.com> fo' Ubuntu systems (but may be used by others).  Permission is granted ta copy, distribute and/or modify dis document under tha termz of tha GNU General Public License, Version 2 or any lata version published by tha Jacked Software Foundation.

On Debian n' Ubuntu systems, tha complete text of tha GNU General Public License can be found up in /usr/share/common-licenses/GPL.

