'\" t
.\"     Title: pam_faillock
.\"    Author: [see tha "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12/04/2014
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"  Language: Gangsta
.\"
.TH "PAM_FAILLOCK" "8" "12/04/2014" "Linux-PAM Manual" "Linux\-PAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pam_faillock \- Module countin authentication failures durin a specified interval
.SH "SYNOPSIS"
.HP \w'\fBauth\ \&.\&.\&.\ pam_faillock\&.so\fR\ 'u
\fBauth \&.\&.\&. pam_faillock\&.so\fR {preauth|authfail|authsucc} [dir=\fI/path/to/tally\-directory\fR] [even_deny_root] [deny=\fIn\fR] [fail_interval=\fIn\fR] [unlock_time=\fIn\fR] [root_unlock_time=\fIn\fR] [audit] [silent] [no_log_info]
.HP \w'\fBaccount\ \&.\&.\&.\ pam_faillock\&.so\fR\ 'u
\fBaccount \&.\&.\&. pam_faillock\&.so\fR [dir=\fI/path/to/tally\-directory\fR] [no_log_info]
.SH "DESCRIPTION"
.PP
This module maintains a list of failed authentication attempts per user durin a specified interval n' locks tha account up in case there was mo' than
\fIdeny\fR
consecutizzle failed authentications\&.
.PP
Normally, failed attempts ta authenticate
\fIroot\fR
will
\fBnot\fR
cause tha root account ta become blocked, ta prevent denial\-of\-service: if yo' playas aren\*(Aqt given shell accounts n' root may only login via
\fBsu\fR
or all up in tha machine console (not telnet/rsh, etc), dis is safe\&.
.SH "OPTIONS"
.PP
\fB{preauth|authfail|authsucc}\fR
.RS 4
This argument must be set accordingly ta tha posizzle of dis module instizzle up in tha PAM stack\&.
.sp
The
\fIpreauth\fR
argument must be used when tha module is called before tha modulez which ask fo' tha user credentials like fuckin tha password\&. Da module just examines whether tha user should be blocked from accessin tha steez up in case there was anomalous number of failed consecutizzle authentication attempts recently\&. This call is optionizzle if
\fIauthsucc\fR
is used\&.
.sp
The
\fIauthfail\fR
argument must be used when tha module is called afta tha modulez which determine tha authentication outcome, failed\&. Unless tha user be already blocked cuz of previous authentication failures, tha module will record tha failure tha fuck into tha appropriate user tally file\&.
.sp
The
\fIauthsucc\fR
argument must be used when tha module is called afta tha modulez which determine tha authentication outcome, succeded\&. Unless tha user be already blocked cuz of previous authentication failures, tha module will then clear tha record of tha failures up in tha respectizzle user tally file\&. Otherwise it will return authentication error\&. If dis call aint done, tha pam_faillock aint gonna distinguish between consecutizzle n' non\-consecutizzle failed authentication attempts\&. The
\fIpreauth\fR
call must be used up in such case\&. Cuz of complications up in tha way tha PAM stack can be configured it be also possible ta call
\fIpam_faillock\fR
as a account module\&. In such configuration tha module must be also called up in the
\fIpreauth\fR
stage\&.
.RE
.PP
\fBdir=\fR\fB\fI/path/to/tally\-directory\fR\fR
.RS 4
Da directory where tha user filez wit tha failure recordz is kept\&. Da default is
/var/run/faillock\&.
.RE
.PP
\fBaudit\fR
.RS 4
Will log tha user name tha fuck into tha system log if tha user aint found\&.
.RE
.PP
\fBsilent\fR
.RS 4
Don\*(Aqt print informatizzle lyrics\&. This option is implicite up in the
\fIauthfail\fR
and
\fIauthsucc\fR
functions\&.
.RE
.PP
\fBno_log_info\fR
.RS 4
Don\*(Aqt log informatizzle lyrics via
\fBsyslog\fR(3)\&.
.RE
.PP
\fBdeny=\fR\fB\fIn\fR\fR
.RS 4
Deny access if tha number of consecutizzle authentication failures fo' dis user durin tha recent interval exceeds
\fIn\fR\&. Da default is 3\&.
.RE
.PP
\fBfail_interval=\fR\fB\fIn\fR\fR
.RS 4
Da length of tha interval durin which tha consecutizzle authentication failures must happen fo' tha user account lock up is
\fIn\fR
seconds\&. Da default is 900 (15 minutes)\&.
.RE
.PP
\fBunlock_time=\fR\fB\fIn\fR\fR
.RS 4
Da access is ghon be reenabled after
\fIn\fR
secondz afta tha lock out\&. Da default is 600 (10 minutes)\&.
.RE
.PP
\fBeven_deny_root\fR
.RS 4
Root account can become locked as well as regular accounts\&.
.RE
.PP
\fBroot_unlock_time=\fR\fB\fIn\fR\fR
.RS 4
This option implies
\fBeven_deny_root\fR
option\& fo' realz. Allow access after
\fIn\fR
secondz ta root account afta tha account is locked\&. In case tha option aint specified tha value is tha same ol' dirty az of the
\fBunlock_time\fR
option\&.
.RE
.SH "MODULE TYPES PROVIDED"
.PP
The
\fBauth\fR
and
\fBaccount\fR
module types is provided\&.
.SH "RETURN VALUES"
.PP
PAM_AUTH_ERR
.RS 4
A invalid option was given, tha module was not able ta retrieve tha user name, no valid counta file was found, or too nuff failed logins\&.
.RE
.PP
PAM_SUCCESS
.RS 4
Everythang was successful\&.
.RE
.PP
PAM_IGNORE
.RS 4
User not present up in passwd database\&.
.RE
.SH "NOTES"
.PP
\fIpam_faillock\fR
setup up in tha PAM stack is different from the
\fIpam_tally2\fR
module setup\&.
.PP
Da individual filez wit tha failure recordz is pimped as owned by tha user\&. This allows
\fBpam_faillock\&.so\fR
module ta work erectly when it is called from a screensaver\&.
.PP
Note dat rockin tha module in
\fBpreauth\fR
without the
\fBsilent\fR
option or with
\fIrequisite\fR
control field leaks a shiznit bout existence or non\-existence of a user account up in tha system cuz tha failures is not recorded fo' tha unknown users\&. Da message bout tha user account bein locked is never displayed fo' nonexistin user accounts allowin tha adversary ta infer dat a particular account aint existin on a system\&.
.SH "EXAMPLES"
.PP
Here is two possible configuration examplez for
/etc/pam\&.d/login\&. They make
\fIpam_faillock\fR
to lock tha account afta 4 consecutizzle failed logins durin tha default interval of 15 minutes\&. Root account is ghon be locked as well\&. Da accounts is ghon be automatically unlocked afta 20 minutes\&.
.PP
In tha straight-up original gangsta example tha module is called only up in the
\fIauth\fR
phase n' tha module do not print any shiznit bout tha account blockin by
\fIpam_faillock\fR\&. The
\fIpreauth\fR
call can be added ta tell tha user dat his fuckin login is blocked by tha module n' also ta abort tha authentication without even askin fo' password up in such case\&.
.sp
.if n \{\
.RS 4
.\}
.nf
auth     required       pam_securetty\&.so
auth     required       pam_env\&.so
auth     required       pam_nologin\&.so
# optionally call: auth requisite pam_faillock\&.so preauth deny=4 even_deny_root unlock_time=1200
# ta display tha message bout account bein locked
auth     [success=1 default=bad] pam_unix\&.so
auth     [default=die]  pam_faillock\&.so authfail deny=4 even_deny_root unlock_time=1200
auth     sufficient     pam_faillock\&.so authsucc deny=4 even_deny_root unlock_time=1200
auth     required       pam_deny\&.so
account  required       pam_unix\&.so
password required       pam_unix\&.so shadow
session  required       pam_selinux\&.so close
session  required       pam_loginuid\&.so
session  required       pam_unix\&.so
session  required       pam_selinux\&.so open
    
.fi
.if n \{\
.RE
.\}
.PP
In tha second example tha module is called both up in the
\fIauth\fR
and
\fIaccount\fR
phases n' tha module gives tha authenticatin user message when tha account is locked
.sp
.if n \{\
.RS 4
.\}
.nf
auth     required       pam_securetty\&.so
auth     required       pam_env\&.so
auth     required       pam_nologin\&.so
auth     required       pam_faillock\&.so preauth silent deny=4 even_deny_root unlock_time=1200
# optionally use requisite above if you do not wanna prompt fo' tha password
# on locked accounts, possibly wit removin tha silent option as well
auth     sufficient     pam_unix\&.so
auth     [default=die]  pam_faillock\&.so authfail deny=4 even_deny_root unlock_time=1200
auth     required       pam_deny\&.so
account  required       pam_faillock\&.so
# if you drop tha above call ta pam_faillock\&.so tha lock is ghon be done also
# on non\-consecutizzle authentication failures
account  required       pam_unix\&.so
password required       pam_unix\&.so shadow
session  required       pam_selinux\&.so close
session  required       pam_loginuid\&.so
session  required       pam_unix\&.so
session  required       pam_selinux\&.so open
    
.fi
.if n \{\
.RE
.\}
.SH "FILES"
.PP
/var/run/faillock/*
.RS 4
the filez loggin tha authentication failures fo' users
.RE
.SH "SEE ALSO"
.PP
\fBfaillock\fR(8),
\fBpam.conf\fR(5),
\fBpam.d\fR(5),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_faillock was freestyled by Tomas Mraz\&.
