'\" t
.\"     Title: pam_namespace
.\"    Author: [see tha "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/19/2013
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"  Language: Gangsta
.\"
.TH "PAM_NAMESPACE" "8" "09/19/2013" "Linux-PAM Manual" "Linux-PAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pam_namespace \- PAM module fo' configurin namespace fo' a session
.SH "SYNOPSIS"
.HP \w'\fBpam_namespace\&.so\fR\ 'u
\fBpam_namespace\&.so\fR [debug] [unmnt_remnt] [unmnt_only] [require_selinux] [gen_hash] [ignore_config_error] [ignore_instance_parent_mode] [unmount_on_close] [use_current_context] [use_default_context] [mount_private]
.SH "DESCRIPTION"
.PP
Da pam_namespace PAM module sets up a private namespace fo' a session wit polyinstantiated directories\& fo' realz. A polyinstantiated directory serves up a gangbangin' finger-lickin' different instizzle of itself based on user name, or when rockin SELinux, user name, securitizzle context or both\&. If a executable script
/etc/security/namespace\&.init
exists, it is used ta initialize tha instizzle directory afta it is set up n' mounted on tha polyinstantiated directory\&. Da script receives tha polyinstantiated directory path, tha instizzle directory path, flag whether tha instizzle directory was newly pimped (0 fo' no, 1 fo' yes), n' tha user name as its arguments\&.
.PP
Da pam_namespace module disassociates tha session namespace from tha parent namespace\& fo' realz. Any mounts/unmounts performed up in tha parent namespace, like fuckin mountin of devices, is not reflected up in tha session namespace\&. To propagate selected mount/unmount events from tha parent namespace tha fuck into tha disassociated session namespace, a administrator may use tha special shared\-subtree feature\&. For additionizzle shiznit on shared\-subtree feature, please refer ta tha mount(8) playa page n' tha shared\-subtree description at http://lwn\&.net/Articles/159077 n' http://lwn\&.net/Articles/159092\&.
.SH "OPTIONS"
.PP
\fBdebug\fR
.RS 4
All dem debug shiznit is logged rockin syslog
.RE
.PP
\fBunmnt_remnt\fR
.RS 4
For programs like fuckin su n' newrole, tha login session has already setup a polyinstantiated namespace\&. For these programs, polyinstantiation is performed based on freshly smoked up user id or securitizzle context, however tha command first need ta undo tha polyinstantiation performed by login\&. This argument instructs tha command ta first undo previous polyinstantiation before proceedin wit freshly smoked up polyinstantiation based on freshly smoked up id/context
.RE
.PP
\fBunmnt_only\fR
.RS 4
For trusted programs dat wanna undo any existin bind mounts n' process instizzle directories on they own, dis argument allows dem ta unmount currently mounted instizzle directories
.RE
.PP
\fBrequire_selinux\fR
.RS 4
If selinux aint enabled, return failure
.RE
.PP
\fBgen_hash\fR
.RS 4
Instead of rockin tha securitizzle context strang fo' tha instizzle name, generate n' use its md5 hash\&.
.RE
.PP
\fBignore_config_error\fR
.RS 4
If a line up in tha configuration file correspondin ta a polyinstantiated directory gotz nuff format error, skip dat line process tha next line\&. Without dis option, pam will return a error ta tha callin program resultin up in termination of tha session\&.
.RE
.PP
\fBignore_instance_parent_mode\fR
.RS 4
Instizzle parent directories by default is sposed ta fuckin have tha restrictizzle mode of 000\&. Usin dis option, a administrator can chizzle ta ignore tha mode of tha instizzle parent\&. This option should be used wit caution as it will reduce securitizzle n' isolation goalz of tha polyinstantiation mechanism\&.
.RE
.PP
\fBunmount_on_close\fR
.RS 4
Explicitly unmount tha polyinstantiated directories instead of relyin on automatic namespace destruction afta tha last process up in a namespace exits\&. This option should be used only up in case it is ensured by other means dat there cannot be any processes hustlin up in tha private namespace left afta tha session close\&. Well shiiiit, it be also useful only up in case there be multiple pam session calls up in sequence from tha same process\&.
.RE
.PP
\fBuse_current_context\fR
.RS 4
Useful fo' skillz which do not chizzle tha SELinux context wit setexeccon call\&. Da module will use tha current SELinux context of tha callin process fo' tha level n' context polyinstantiation\&.
.RE
.PP
\fBuse_default_context\fR
.RS 4
Useful fo' skillz which do not use pam_selinux fo' changin tha SELinux context wit setexeccon call\&. Da module will use tha default SELinux context of tha user fo' tha level n' context polyinstantiation\&.
.RE
.PP
\fBmount_private\fR
.RS 4
This option can be used on systems where tha / mount point or its submounts is made shared (for example wit a
\fBmount \-\-make\-rshared /\fR
command)\&. Da module will mark tha whole directory tree so any mount n' unmount operations up in tha polyinstantiation namespace is private\&. Normally tha pam_namespace will try ta detect tha shared / mount point n' make tha polyinstantiated directories private automatically\&. This option has ta be used just when only a subtree is shared n' / is not\&.
.sp
Note dat mounts n' unmounts done up in tha private namespace aint gonna affect tha parent namespace if dis option is used or when tha shared / mount point be autodetected\&.
.RE
.SH "MODULE TYPES PROVIDED"
.PP
Only the
\fBsession\fR
module type is provided\&. Da module must not be called from multithreaded processes\&.
.SH "RETURN VALUES"
.PP
PAM_SUCCESS
.RS 4
Namespace setup was successful\&.
.RE
.PP
PAM_SERVICE_ERR
.RS 4
Unexpected system error occurred while settin up namespace\&.
.RE
.PP
PAM_SESSION_ERR
.RS 4
Unexpected namespace configuration error occurred\&.
.RE
.SH "FILES"
.PP
/etc/security/namespace\&.conf
.RS 4
Main configuration file
.RE
.PP
/etc/security/namespace\&.d
.RS 4
Directory fo' additionizzle configuration files
.RE
.PP
/etc/security/namespace\&.init
.RS 4
Init script fo' instizzle directories
.RE
.SH "EXAMPLES"
.PP
For tha <service>s you need polyinstantiation (login fo' example) put tha followin line up in /etc/pam\&.d/<service> as tha last line fo' session group:
.PP
session required pam_namespace\&.so [arguments]
.PP
To use polyinstantiation wit graphical display manager gdm, bang tha followin line, before exit 0, up in /etc/gdm/PostSession/Default:
.PP
/usr/sbin/gdm\-safe\-restart
.PP
This allows gdm ta restart afta each session n' appropriately adjust namespacez of display manager n' tha X server\&. If polyinstantiation of /tmp is desired along wit tha graphical environment, then additionizzle configuration chizzlez is needed ta address tha interaction of X server n' font server namespaces wit they use of /tmp ta create communication sockets\&. Please use tha initialization script
/etc/security/namespace\&.init
to ensure dat tha X server n' its clients can appropriately access tha communication socket X0\&. Please refer ta tha sample instructions provided up in tha comment section of tha instizzle initialization script
/etc/security/namespace\&.init\&. In addition, big-ass up tha followin chizzlez ta use graphical environment wit polyinstantiation of /tmp:
.PP
.if n \{\
.RS 4
.\}
.nf
      1\&. Disable tha use of font server by commentin up "FontPath"
         line up in /etc/X11/xorg\&.conf\&. If you do wanna use tha font server
         then yo big-ass booty is ghon gotta augment tha instizzle initialization
         script ta appropriately provide /tmp/\&.font\-unix from the
         polyinstantiated /tmp\&.
      2\&. Ensure dat tha gdm steez is setup ta use pam_namespace,
         as busted lyrics bout above, by modifyin /etc/pam\&.d/gdm\&.
      3\&. Ensure dat tha display manager is configured ta restart X server
         wit each freshly smoked up session\&. This default setup can be verified by
         makin shizzle dat /usr/share/gdm/defaults\&.conf gotz nuff
         "AlwaysRestartServer=true", n' it aint overridden by
         /etc/gdm/custom\&.conf\&.
    
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP
\fBnamespace.conf\fR(5),
\fBpam.d\fR(5),
\fBmount\fR(8),
\fBpam\fR(8)\&.
.SH "AUTHORS"
.PP
Da namespace setup scheme was designed by Stephen Smalley, Janak Desai n' Chad Sellers\&. Da pam_namespace PAM module was pimped by Janak Desai <janak@us\&.ibm\&.com>, Chad Sellaz <csellers@tresys\&.com> n' Steve Grubb <sgrubb@redhat\&.com>\& fo' realz. Additionizzle improvements by Xavier Toth <txtoth@gmail\&.com> n' Tomas Mraz <tmraz@redhat\&.com>\&.
