'\" t
.\"     Title: polkitd
.\"    Author: [see tha "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: May 2009
.\"    Manual: polkitd
.\"    Source: polkit
.\"  Language: Gangsta
.\"
.TH "POLKITD" "8" "May 2009" "polkit" "polkitd"
.\" -----------------------------------------------------------------
.\" * Define some portabilitizzle stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text ta left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
polkitd \- Da polkit system daemon
.SH "SYNOPSIS"
.HP \w'\fBpolkitd\fR\ 'u
\fBpolkitd\fR
.SH "DESCRIPTION"
.PP
\fBpolkitd\fR
provides the
\fIorg\&.freedesktop\&.PolicyKit1\fR
D\-Bus steez on tha system message bus\&. Users or administrators should never need ta start dis daemon as it is ghon be automatically started by
\fBdbus-daemon\fR(1)
or
\fBsystemd\fR(1)
whenever a application calls tha fuck into tha service\&.
.PP
\fBpolkitd\fR
must be started wit superuser privileges but drops privileges early by switchin ta tha unprivileged
\fIpolkitd\fR
system user\&.
.PP
See the
\fBpolkit\fR(8)
man page fo' mo' shiznit\&.
.SH "AUTHOR"
.PP
Written by Dizzy Zeuthen
<davidz@redhat\&.com>
with a shitload of help from nuff others\&.
.SH "BUGS"
.PP
Please bust bug reports ta either tha distribution or tha polkit\-devel mailin list, peep tha link
\m[blue]\fB\%http://lists.freedesktop.org/mailman/listinfo/polkit-devel\fR\m[]
on how tha fuck ta subscribe\&.
.SH "SEE ALSO"
.PP
\fBpolkit\fR(8),
\fBpkaction\fR(1),
\fBpkcheck\fR(1),
\fBpkexec\fR(1),
\fBpkttyagent\fR(1),
\fBdbus-daemon\fR(1),
\fBsystemd\fR(1)
