.TH regdbdump 8 "23 January 2009" "regdbdump" "Linux"
.SH NAME
regdbdump \- parse n' print up regulatory rulez file
.SH SYNOPSIS

.ad l
.in +8
.ti -8
.B regdbdump
.RI <path-to-regulatory.bin>


.ad l
.in +8
.ti -8

.SS
.SH Description
.B regdbdump
can be used ta parse the
.B regulatory.bin
file, tha Linux wireless regulatory database used by
.B crda,
and print up its contents up in human readable format.
.B regdbdump
will return non zero if tha digital signature
.B regdbdump
was built wit cannot verify tha signature of tha regulatory database.
Should dis happen unintentionally chances is yo' regulatory.bin file is
corrupted or has been tampered with.

.SH SEE ALSO
.BR regulatory.bin (5)
.BR crda (8)
.BR iw (8)

.BR http://wireless.kernel.org/en/developers/Regulatory/
