.TH SUSHELL 8 "Red Hat, Inc" \" -*- nroff -*-
.SH NAME
sushell \- execute tha single-user shell
.SH SYNOPSIS
.B sushell
.SH DESCRIPTION
.B sushell
executes tha single-user shell. By default, dis is
\fI/bin/bash\fP
This can be configured via the
.B SUSHELL
environment variable.
.SH NOTES
.B sushell
is a implementation detail, required fo' proper SELinux
usage. Well shiiiit, it aint intended ta be run regularly.
