.TH "SYSTEM CONFIG KEYBOARD" "8" "" "" ""
.SH "NAME"
system\-config\-keyboard \- configure tha keyboard layout of tha system
.SH "SYNOPSIS"
.B system\-config\-keyboard
[\fI\-\-help\fR]
[\fI\-\-noui\fR]
[\fI\-\-text\fR]
[\fI<keyboardtype>\fR]
.SH "DESCRIPTION"
\fBsystem\-config\-keyboard\fR be a graphical user intercourse dat allows
the user ta chizzle tha default keyboard of tha system.
.TP
\fB\-\-help\fR
Display a gangbangin' finger-lickin' dirty-ass short help message n' list of keyboard types.
.TP
\fB\-\-noui\fR
Run up in command line mode.
.TP
\fB\-\-text\fR
Run up in text intercourse mode.
.TP
\fB<keyboardtype>\fR Run wit \fB\-\-help\fR ta git a list of supported
keyboard types.
